lms/static/scripts/frontend_apps/components/BookSelector.js
package.json
yarn.lock

This PR bumps `@hypothesis/frontend-shared` to v3.5.0. That version has a breaking change to a prop for `TextInput`, which is updated here in the same commit.
There is an additional tiny commit here to fix a little typo in a placeholder URL in that same `TextInput`.

Update `TextInput` prop (shared component)

---

lms/services/canvas.py
tests/unit/lms/services/canvas_test.py

When launching a Canvas Files assignment and the `CanvasService.public_url_for_file()` method is called:
If there is a `mapped_file_id` in the DB but we nonetheless don't see the `mapped_file_id` in the current course or we get a permissions error when trying to get a public URL for the `mapped_file_id`, use both the `mapped_file_id` and the assignment's original `file_id` to try to find a matching file in the course.
I think this might fix an obscure Canvas course copy edge case involving renaming files in Canvas and possibly requiring chains of multiple course copies. I'm not sure exactly what the edge case that this covers is, yet. But it shouldn't do any harm.

Search by both original and mapped file ID

---

lms/db/_bulk_action.py
tests/unit/lms/db/_bulk_action_test.py
tests/unit/lms/events/subscriber_test.py

Fixes https://github.com/hypothesis/lms/issues/2909
This should work with all style of onupdate parameters except callables that expect a context parameter:
https://github.com/hypothesis/lms/pull/2844/files#diff-5743e15c634a3617289d65def23d8b87bf8cc430af559d08057d883e23467757R35

Use model defined onupdate on bulk_actions' upsert 

---

lms/services/blackboard_api/client.py
tests/unit/lms/services/blackboard_api/client_test.py

Save some time and bandwidth by only getting the fields that we actually need from the Blackboard API.
Fixes https://github.com/hypothesis/lms/issues/2963

Only get needed fields from Blackboard API

---

lms/resources/_js_config/__init__.py
tests/unit/lms/resources/_js_config/__init___test.py

This is something I missed when we did this, the condition to get the groups via rpc is was only checking sections. Now it checks that either sections or groups are enabled
(on `master`, to reproduce the problem)
- Disable sections on http://localhost:8001/admin/instance/Hypothesisb3be0b33d0b5e4b1cf3aaf04e0e1819a/
- Open https://hypothesis.instructure.com/courses/125/assignments/1575 check that the groups the client renders are the group set's ones (Test group, another test group...)
- Force `lms/resources/lti_launch.py::canvas_sections_supported` to return False
- Check  https://hypothesis.instructure.com/courses/125/assignments/1575. Now the group in the client is `Developer Test Course`
(switch to this branch, keep `lms/resources/lti_launch.py::canvas_sections_supported` to returning …

Use rpc groups sync for both canvas groups and sections

---

lms/static/scripts/frontend_apps/utils/AuthWindow.js
lms/static/scripts/frontend_apps/utils/content-item.js
package.json
scripts/gulp/create-bundle.js
yarn.lock

Simplify our dependencies by replacing `query-string` with `URLSearchParams`. An accidental use of Browserify's polyfill for Node's `querystring` module was also replaced. This has the same API as `query-string` (in other words, we accidentally used two different implementations).

Replace `query-string` dependency with URLSearchParams

---

lms/static/scripts/frontend_apps/components/BookPicker.js
lms/static/scripts/frontend_apps/components/BookSelector.js
lms/static/scripts/frontend_apps/components/test/BookSelector-test.js
lms/static/styles/components/_BookSelector.scss

This PR addresses two tuning issues for the VitalSource book-picking flow:
* It makes it possible to press "Enter" again after a book is looked up in the BookSelector to "confirm" that book and move on to the select-chapter state. This is a convenience for users who are using their keyboard to navigate.
* It eliminates some pseudo-semantic markup that isn't really (semantic).
As part of supporting the first objective, focus strategy needed to be adjusted for the `TextInput` and `IconButton` elements in `BookSelector`. 
Previously, they set their underlying elements (`input` and `button`) to be `disabled` when fetch requests were in flight. The objective was to keep users from changing the URL value and attempting to re-submit it while a request was outstanding. However, `disabled` …

Adjust Enter keypress handling and focus flow for VS book selector

---

lms/services/exceptions.py
lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.js
lms/static/scripts/frontend_apps/components/LaunchErrorDialog.js
lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
lms/static/scripts/frontend_apps/components/test/LaunchErrorDialog-test.js
lms/views/api/exceptions.py

Fixes https://github.com/hypothesis/lms/issues/2990
Add a helpful error dialog for the case when the user doesn't have permission to read a Blackboard Files assignment's file.
If the user launching a Blackboard Files assignment (probably a student) doesn't have permission to read the assignment's file then Blackboard's public URL API returns an error message like this:
```json
{
"message": "Target folder or file (xid-9911_1) does not exist or user does not have Read|Write permission.",
"status": 404
}
```
We currently show a generic error dialog in response to this, which doesn't help the user to understand what is wrong or what they can do to fix it. The **Error Details** aren't much use either:
This PR special-cases 404s from Blackboard's public URL API and shows a more helpful error …

Handle Blackboard file permission errors

---

lms/services/__init__.py
lms/services/blackboard_api/_basic.py
lms/services/blackboard_api/factory.py
lms/services/http.py
lms/services/oauth_http.py
tests/unit/lms/services/blackboard_api/_basic_test.py
tests/unit/lms/services/blackboard_api/factory_test.py
tests/unit/lms/services/http_test.py
tests/unit/lms/services/oauth_http_test.py
tests/unit/services.py

Split `HTTPService` into two classes `HTTPService` and `OAuthHTTPService`. Two smaller classes instead of one bigger one. This will make more sense when `OAuthHTTPService.request()` is extended with more OAuth-related functionality.

Split out `OAuthHTTPService` from `HTTPService`

---

lms/services/blackboard_api/_basic.py
lms/services/blackboard_api/factory.py
lms/services/oauth_http.py
tests/unit/lms/services/blackboard_api/_basic_test.py
tests/unit/lms/services/blackboard_api/factory_test.py
tests/unit/lms/services/oauth_http_test.py

Move the Blackboard API client's `BasicClient.get_token()` to `OAuthHTTPService.access_token_request()` .
This is mostly because I want a future commit to add `refresh_token_request()` to `OAuthHTTPService` as well, and `access_token_request()` and `refresh_token_request()` go together (they even share code).
The method was renamed from `get_token()` to `access_token_request()` because I think `access_token_request()` is a better name as it sends an "access token request" (what the OAuth 2.0 spec calls this particular request), and the name goes nicely with `refresh_token_request()` which will be added in a future commit (and which will send what the spec calls a "refresh token request") and with the existing `request()`.
I'm not sure that this `access_token_request()` method is fully …

Move `access_token_request()` into `OAuthHTTPService`

---

tests/unit/lms/services/blackboard_api/_basic_test.py

No functional change to the tests, just splitting one test class into multiple. This is going to make these tests easier to extend in future when more tests need to be added.

Split TestBasicClient into multiple classes

---

lms/services/blackboard_api/_basic.py
lms/services/oauth_http.py
tests/unit/lms/services/blackboard_api/_basic_test.py

Fixes https://github.com/hypothesis/lms/issues/2033.
When a Blackboard API request fails for any reason try to get a new access token without user interaction by doing a refresh token request and then re-try the original API request once more.
If the refresh token request fails raise an `OAuth2TokenError` which will trigger the **Authorize Hypothesis** dialog to get a new access token with user interaction.
If the refresh token request succeeds but then the second attempt at the API request still fails raise an `HTTPError` which will trigger an error dialog (with **Try again** button).
Testing
=======
Delete all the access tokens from your DB. This will make the tests below easier to do by removing irrelevant access tokens from the DB:
tox -qe dockercompose -- exec postgres psql -U …

Add Blackboard refresh-and-retry support

---

lms/resources/_js_config/__init__.py
lms/services/oauth_http.py
lms/static/scripts/frontend_apps/components/OAuth2RedirectErrorApp.js
lms/static/scripts/frontend_apps/components/test/OAuth2RedirectErrorApp-test.js
lms/static/scripts/frontend_apps/config.js
lms/static/scripts/frontend_apps/index.js
lms/views/api/canvas/authorize.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/views/api/canvas/authorize_test.py

This is mostly not Canvas-specific (except for the scopes) and we now need to re-use it for Blackboard, so generalize  `enable_canvas_oauth2_redirect_error_mode()` to just  `enable_oauth2_redirect_error_mode()` and remove all unnecessary references to Canvas.
* Delete all the access tokens from your DB so that the authorization flow is triggered when you launch an assignment:
```
tox -qe dockercompose -- exec postgres psql -U postgres -c 'DELETE FROM oauth2_token;'
```
* Log in to https://hypothesis.instructure.com/ as either a teacher or a student and launch [localhost (make devdata) Canvas Files Assignment](https://hypothesis.instructure.com/courses/125/assignments/875)
* Click **Authorize**
```diff
diff --git a/lms/services/canvas_api/client.py b/lms/services/canvas_api/client.py
index …
```

Generalize `enable_canvas_oauth2_redirect_error_mode()`

---

lms/resources/_js_config/__init__.py
lms/views/api/blackboard/authorize.py
lms/views/api/canvas/authorize.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/views/api/blackboard/authorize_test.py
tests/unit/lms/views/api/canvas/authorize_test.py

Fixes https://github.com/hypothesis/lms/issues/2760
Some of the tests below are testing existing behaviours that were implemented for Canvas and are just being inherited by Blackboard and aren't really implemented by the code in this PR. But there's no harm in re-testing everything to do with our popup window UX. And some of the tests _are_ testing what's actually in this PR.
* Log in to https://aunltd-test.blackboard.com/ as either a teacher or a student
* Delete all the access tokens from your DB in order to trigger the authorization process when you launch a Blackboard Files assignment:
```
tox -qe dockercompose -- exec postgres psql -U postgres -c 'DELETE FROM oauth2_token;'
```
* Revoke your Blackboard API authorization so that Blackboard's authorization popup window doesn't …

Handle errors getting blackboard access tokens

---

lms/static/scripts/frontend_apps/api-types.js
lms/static/scripts/frontend_apps/components/LMSFilePicker.js
lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js

This is an interim change that makes the front-end file-picker for Blackboard files function on top of changes to the proxy API to retrieve a list of files. The returned results now contains some extra properties, and include both files and folders.
For the moment, make `LMSFilePicker` filter out folders such that the interface behaves as it did before the API change: present only root-level files.
The net result is that the behavior is the same as before #2950 — the picker shows a list of root-level files, only.
This branch depends on #2950 
1. Check out this branch
3. Navigate to or create a localhost Blackboard assignment on https://aunltd-test.blackboard.com/ . I have had luck with the `blackboardteacher` user (see 1Password for credentials).
4. Launch the unconfigured assignment and …

Update LMSFilePicker to filter out folders from BB files API results

---

lms/resources/_js_config/__init__.py
lms/resources/lti_launch.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/resources/lti_launch_test.py

It's not enough that groups are enabled at the AI level, the assignment itself needs to be a groups one otherwise we run into a bug where if sections are disabled and groups are enabled, the sync API will still return sections groups for a non-groups assignment.
- Disable sections, either on the DB course or just return False around here https://github.com/hypothesis/lms/blob/4fd826744a269ce0117d0dfd57e1c9ed7d65668e/lms/resources/lti_launch.py#L133
- http://localhost:8001/admin/instance/Hypothesisb3be0b33d0b5e4b1cf3aaf04e0e1819a/ Enable groups
- The groups in the client are "Section 1..."
- Change to this branch
- Keep sections disabled and groups enabled
- Launch …

Get rcp groups for canvas groups only when the assignment has them enabled

---

lms/migrations/versions/da66efab9e5f_enable_canvas_groups.py

(For https://github.com/hypothesis/product-backlog/issues/1221)
Using `make sql`:
- Remove existing AIs
`truncate application_instances cascade;`
- Insert new test ones
```
insert into application_instances (consumer_key, shared_secret, lms_url, requesters_email, created, settings, developer_key, developer_key) values ('test1', 'test1', 'test1', 'test1', now(), '{}', 'test1');
insert into application_instances (consumer_key, shared_secret, lms_url, requesters_email, created, settings, developer_key) values ('test2', 'test2', 'test2', 'test2', now(), '{"canvas": {"sections_enabled": false}}$', 'test1');
insert into application_instances (consumer_key, shared_secret, lms_url, requesters_email, created, settings, developer_key) values ('test3', 'test3', 'test3', 'test3', now(), '{"canvas": …
```

Data migration for enabling canvas groups

---

lms/resources/_js_config/__init__.py
tests/unit/lms/resources/_js_config/__init___test.py

- Force this if to evaluate to false (no sections scopes) https://github.com/hypothesis/lms/blob/4fd826744a269ce0117d0dfd57e1c9ed7d65668e/lms/views/api/canvas/authorize.py#L52
(`False and` is the easiest, or remove any courses with sections locally)
- Also disable sections here https://github.com/hypothesis/lms/blob/4fd826744a269ce0117d0dfd57e1c9ed7d65668e/lms/resources/lti_launch.py#L133
- Enable groups and disable sections here: http://localhost:8001/admin/instance/Hypothesisb3be0b33d0b5e4b1cf3aaf04e0e1819a/
- Launch a non group assignment, it will  get  in an auth loop (eg https://hypothesis.instructure.com/courses/125/assignments/1069)
- While on this branch, with the same setup, the assignment will launch without problems

Don't populate sync API with just groups enabled

---

lms/static/images/folder.svg
lms/static/scripts/frontend_apps/components/Breadcrumbs.js
lms/static/scripts/frontend_apps/components/ContentSelector.js
lms/static/scripts/frontend_apps/components/FileList.js
lms/static/scripts/frontend_apps/components/LMSFilePicker.js
lms/static/scripts/frontend_apps/components/test/Breadcrumbs-test.js
lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js
lms/static/scripts/frontend_apps/icons.js
lms/static/styles/components/_Breadcrumbs.scss
lms/static/styles/components/_FileList.scss
lms/static/styles/frontend_apps.scss

This PR is a cleaned-up implementation, with tests, of https://github.com/hypothesis/lms/pull/3010 . It adds subfolder support, with breadcrumbs, for the `LMSFilePicker` component, specifically to support Blackboard files' subfolders, but available to other integrations.
In a brief nutshell:
* A new `Breadcrumbs` component is added. I've tried to be straightforward and relatively generic here. There are several known follow-up tasks for this component, including handling elision and a11y affordances (e.g. ARIA roles).
* `LMSFilePicker` is extended to maintain state about path, and re-fetch files when the "path" changes (i.e. retrieve files in sub-folders).
* `FileList` is updated to differentiate between files and folders when determining which icon to render
Screen video of current …

Add subfolder support for Blackboard files in LMSFilePicker

---

lms/migrations/versions/d9c9e65c463e_files_parent_id.py
lms/models/file.py
lms/services/blackboard_api/_schemas.py
lms/services/blackboard_api/client.py
lms/services/blackboard_api/factory.py
tests/unit/lms/services/blackboard_api/client_test.py
tests/unit/lms/services/blackboard_api/factory_test.py

For https://github.com/hypothesis/lms/issues/3012
(includes the commits of https://github.com/hypothesis/lms/pull/3045 and https://github.com/hypothesis/lms/pull/3044 that need to be rebased out after merging those)
- Adds a new parent_lms_id nullable column to File  which seems like important  information to store on the DB in case we need to back the file tree without making a lot of API calls. Canvas has the same concept (but it's called `folder_id` not `parent_id`)
- Request `size` and parentId from BB API 
- Emit event and store files in the DB
- Clear your files table `makes sql` & `truncate file ;`
- Go over https://aunltd-test.blackboard.com/ultra/courses/_19_1/cl/outline
- At the top `Build Content" -> Hypothesis (localhost, make devdata), give it a name 
- Launch the assignment …

Store bb files

---

lms/resources/_js_config/__init__.py
lms/static/scripts/frontend_apps/components/OAuth2RedirectErrorApp.js
lms/static/scripts/frontend_apps/components/test/OAuth2RedirectErrorApp-test.js
lms/static/scripts/frontend_apps/config.js
lms/views/api/blackboard/authorize.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/views/api/blackboard/authorize_test.py

For #2024 
- Log in as admin on BB
- https://aunltd-test.blackboard.com/ultra/admin -> Integrations -> Rest API Integrations and here either disable (`Make unavaialble") Hypothesis Dev or remove it.
- Launch an assignment that uses BB API (eg `localhost (make devdata) Blackboard Files Assignment` or/and try to create a new BB files assignment.
- You should get an "authorize" modal followed by another modal explaining the situation
- After testing re-enable the Rest integration (or recreate it using application id: `b7a1baf5-3545-4f5d-897f-c036b0d5bd5b` and learn user `administrator`

Bb missing integration dialog

---

lms/resources/_js_config/__init__.py
lms/static/scripts/frontend_apps/components/OAuth2RedirectErrorApp.js
lms/static/scripts/frontend_apps/components/test/OAuth2RedirectErrorApp-test.js
lms/static/scripts/frontend_apps/config.js
lms/views/api/canvas/authorize.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/views/api/canvas/authorize_test.py

Small refactor to remove the boolean field and just use an error code
- Change the requested scopes at https://github.com/hypothesis/lms/blob/c66700613707002b52309f0e83303e04895346f3/lms/views/api/canvas/authorize.py#L22 (just change one line or modify one to FILES_SCOPES)
- Launch an assignment (eg: https://hypothesis.instructure.com/courses/125/assignments/873) The modal should show up

Replace is_scope_invalid flag with an error code

---

lms/static/scripts/frontend_apps/utils/google-picker-client.js
lms/static/scripts/frontend_apps/utils/test/google-picker-client-test.js

If a user selects a PDF file for an assignment which has a "resource key" associated with it, capture this key from the Google
Picker-provided file metadata and add it to the file download URL as a `resourcekey` query parameter. This mirrors the updated download URL for affected files if you use the "Download" action for the file in the Google Drive UI.
The `resourceKey` field on file objects returned by the picker API is not documented at https://developers.google.com/picker/docs/reference#document but it is present in my testing.
It would still be preferable for us not to generate this URL ourselves, but this commit is an easy incremental change that captures the necessary information for files affected by the security update. I'm going to look into other ways to generate this URL as a …

Add `resourcekey` parameter to Google Drive PDF URLs

---

tests/unit/lms/assets_test.py

Another bit of coverage missing. 
This is a bit light on asserts. Not sure what's important here https://github.com/hypothesis/lms/blob/70f52f90cac40658e74ad0103205a0a2aa012996/lms/assets.py that might be worth explicilty testing for. 
Before most of this file was move to `h_assets` the include had a `no cover`.

Fix missing test coverage for lms.assets

---

tests/unit/lms/services/oauth2_token_test.py

This was broken inadvertently on b08857160cfedee385bb4937c79e15cc263e3ab0,
the sqla fix had the effect of, as stated in the removed comment, always
adding the object to the session and missing the creating part of save().
`oauth_token_in_db_or_not` is only used in this test and it doesn't need
the not in the DB OAuth2Token object so the fixture is changed to return
None instead of a not yet added to the session object.
Another alternative could be splitting the test into two explicit tests, one for each get/create paths of save.

Fix missing test coverage on services/oauth2_token.

---

lms/static/scripts/frontend_apps/components/LMSFilePicker.js
lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js

This PR refactors the `LMSFilePicker` component's internal state to make them more clearly typed, extensible and comprehensible. This work builds on @robertknight 's initial refactor spike here: https://github.com/hypothesis/lms/pull/2736
This primarily follows the lead in https://github.com/hypothesis/lms/pull/2736 with a few tweaks:
* There was a state/action combination missing from what was previously called "auth_retry". This state represents the situation in which a user has been prompted for authz and goes through that flow but we're still unable to fetch files in a way that looks to us like an authz failure. In this state, the user should see different text in the authorization messaging. I've added this by adding a prop to `AuthorizingState` (`isRetry`) and hooking into the …

Refactor LMSFilePicker internal state

---

lms/static/scripts/frontend_apps/components/BookPicker.js
lms/static/scripts/frontend_apps/components/ChapterList.js
lms/static/styles/components/_BookPicker.scss
lms/static/styles/components/_BookSelector.scss
lms/static/styles/components/_ChapterList.scss
lms/static/styles/frontend_apps.scss

Update ChapterList to use a shared Table component, which standardizes
the loading state as well. Update some styling to set some dimensions
on the related modals.
Before, Blackboard:
After, Blackboard:
Before, Canvas:
After, Canvas:
Fixes #3096
1. Check out and run this branch.
2. Enable VitalSource feature flag by visiting http://localhost:8001/flags
1. Log in to https://aunltd-test.blackboard.com/ as `blackboardteacher`
2. Create a new assignment in [this course](https://aunltd-test.blackboard.com/ultra/courses/_19_1/cl/outline) (Content -> Build Content -> Hypothesis, localhost, make devdata) (All you need to do is give it a name and click Submit)
3. Launch the unconfigured assignment and click the “Select book from VitalSource” button.
1. Go to the [Sections Enabled …

Update ChapterList to use shared Table component

---

Makefile
bin/dev_host_bridge.sh
docker-compose.yml

Currently in LMS the `make run-docker` command doesn't work and contains instructions saying you should fill out all the environment variables.
Even if you do this, there's no route by default from the container to the host, so it wouldn't work. 
This attempts to automate the process by filling in some values and loading directly from devdata. It turns out (after many blind alleys), that `docker-compose` is completely setup to read directly from our env file already. Which is nice. We then steal some tricks from ViaHTML to get a stable name for the host IP.
* `make devdata`
* `make docker`
* `make run-docker`
* Start all the other services
* Visit some testing assignments
You should now have a functioning LMS instance hopefully

Make it possible to run `make run-docker` and get a functioning system

---

lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.js

Override browser `iframe` styling defaults (inset border, etc.) with
Hypothesis-standard border

Reset iframe border to simple Hypothesis border

---

lms/static/scripts/frontend_apps/components/ErrorDisplay.js
lms/static/scripts/frontend_apps/components/LMSGrader.js
lms/static/scripts/frontend_apps/components/LaunchErrorDialog.js
lms/static/scripts/frontend_apps/components/VitalSourceBookViewer.js
lms/static/scripts/frontend_apps/config.js
lms/static/scripts/frontend_apps/services/client-rpc.js
lms/static/scripts/frontend_apps/utils/AuthWindow.js
lms/static/scripts/frontend_apps/utils/api.js
lms/static/scripts/frontend_apps/utils/google-picker-client.js
lms/static/scripts/postmessage_json_rpc/server.js

For the past few months, we have started to use the `object` type instead of `Object`. Both are almost interchangeable, but we prefer `object` for simplicity.
This PR substitutes all `Object` to `object` and `Object.<...>` to `Record<...>` and makes the code more consistent.
* First commit is an automatic transformation
* Second commit is a manual fix of a few types

Rename Object to object

---

lms/static/scripts/ui-playground/index.js

The Pattern Library no longer serves by default at `/ui-playground`, so we need to set a `baseURL`.
This will make the Pattern Library serve correctly again at https://lms.hypothes.is/ui-playground/
You can see it locally at http://localhost:8001/ui-playground

Update `baseURL` for pattern library

---

lms/static/scripts/frontend_apps/utils/test/google-api-client-test.js
lms/static/scripts/frontend_apps/utils/test/google-picker-client-test.js

While working on the OneDrive support I modelled my tests on the google
drive tests and I noticed a few minor issues:
* google-api-client-test.js leaves some HTML elements in the body
* google-picker-client-test.js is not restoring the mocked imports
* an unnecessary async

Minor improvements in google-*-client-test.js

---

lms/resources/_js_config/file_picker_config.py
lms/routes.py
lms/templates/onedrive.html.jinja2
lms/views/onedrive.py
tests/unit/lms/resources/_js_config/file_picker_config_test.py
tests/unit/lms/views/onedrive_test.py

By default the OneDrive picker uses the page it was launched from as the redirect
URL for authentication. In the LMS context, the OneDrive picker opens a
window with the URL '/content_item_selection' and some AOuth specific parameters (`?oauth=....`). That causes the LMS to return a 404 `Page not found`.
OneDrive has a `redirectUri` option to launch the picker in a different
URL (see
https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online).
This URL must be registered on the app's registration portal as a
redirect URL.
The redirect page for authentication must content the OneDrive JS
bundle.

Add redirect page for MS OneDrive authentication (OAuth)

---

lms/services/__init__.py
lms/services/exceptions.py

Just inherit directly from `Exception` instead of `ServiceError`.
The purpose of `ServiceError` is merely to have a common base class for all `lms.services exceptions` (all exceptions that might be deliberately raised by any code in `lms.services`). But it's not actually serving any practical need: nothing catches `ServiceError`, and `ServiceError` doesn't contain any code that's being inherited by the other exception classes. So just remove it.

Remove ServiceError

---

lms/services/__init__.py
lms/services/application_instance.py
lms/services/exceptions.py
lms/services/launch_verifier.py

These exception classes are actually only ever raised (and only intended to be raised) by these particular services, so move them into the same files with the service classes that they belong to. This discourages reused but that's the intention here, and doing this makes the intention clearer.

Move exceptions into the files that raise them

---

lms/services/__init__.py
lms/services/exceptions.py
lms/services/h_api.py

`HAPIError` is only ever raised (and only ever intended to be raised) by the `HAPI` service so move it into the same file with `HAPI` service. This discourages reuse but that's the intention here, and doing this makes the intention clearer.
A downside of this change is that it's now harder to see all the `ExternalRequestError` subclasses (they're no longer all in one file).

Move `HAPIError` into the file that raises it

---

lms/resources/_js_config/__init__.py
lms/resources/lti_launch.py
lms/services/__init__.py
lms/services/application_instance.py
lms/services/exceptions.py
lms/services/launch_verifier.py
lms/services/lti_h.py
lms/views/admin.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/services/application_instance_service_test.py
tests/unit/lms/services/launch_verifier_test.py
tests/unit/lms/services/lti_h_test.py
tests/unit/lms/views/admin_test.py

**Problem:** `services.ConsumerKeyError` is being abused for two different purposes.  `ConsumerKeyError` is a subclass of `LTILaunchVerificationError` and as such it's *supposed* to be raised by the `LTILaunchVerifier` service when LTI launch verification fails. But `ConsumerKeyError` is *also* being raised by `ApplicationInstanceService.get(consumer_key)` when there's no `ApplicationInstance` for the given `consumer_key` in the DB. This second case
is not an LTI launch verification error and is not an appropriate use of an `LTILaunchVerificationError` subclass.
**Solution:** split `services.ConsumerKeyError` into two separate classes:
1. `services.ConsumerKeyLaunchVerificationError(LTILaunchVerificationError)`:
This is raised by the `LTILaunchVerifier` service when LTI launch …

Split `services.ConsumerKeyError` into two

---

lms/views/api/exceptions.py
tests/unit/lms/views/api/exceptions_test.py

Merge the `canvas_api_error()` exception view into the general `api_error()` one (the one that catches the base `Exception` class).
The `canvas_api_error()` exception view was getting a little silly because it has an ever-growing list of `@exception_view_config()`'s on it:
```python
@exception_view_config(context=BlackboardFileNotFoundInCourse)
@exception_view_config(context=CanvasAPIPermissionError)
@exception_view_config(context=CanvasFileNotFoundInCourse)
@exception_view_config(context=CanvasGroupError)
def canvas_api_error(self):
...
```
And more need to be added in future.
The name `canvas_api_error()` has become out of date because the view now catches:
1. Blackboard exceptions not just Canvas ones
2. Not all Canvas exceptions. Some other `CanvasAPIerror` subclasses go to other …

Merge the `canvas_api_error()` and `api_error()` exception views

---

lms/static/scripts/frontend_apps/types.d.ts
lms/static/scripts/frontend_apps/utils/onedrive-api-client.js
lms/static/scripts/frontend_apps/utils/test/onedrive-api-client-test.js
lms/static/scripts/tsconfig.json

Added a function that creates the `<script>` element to load the
OneDrive client.
The `OneDrive` type has been globally added to the `window` similarly to
what happens with `window.gapi`.

Load MS OneDrive client

---

lms/services/lti_h.py
lms/views/exceptions.py
tests/unit/lms/services/lti_h_test.py
tests/unit/lms/views/exceptions_test.py

I'm not sure why the code does this: `LTIHService` doesn't need to raise an `HAPIError` wrapped in an `HTTPInternalServerError`. It can just raise the `HAPIError` directly and the exception view can catch `HAPIError`.
This is easier to follow because you can just see that the `HAPI` service raises `HAPIError` and the exception view catches `HAPIError` and you can see what the exception view does with that error. Rather than having to know that the `HAPI` service raises `HAPIError` which `LTIHService` catches and turns into an `HTTPInternalServerError` which
is then caught by the exception view for `HTTPServerError` (a parent class of `HTTPInternalServerError`).
Note that the exception view previously caught `HTTPServerError` and all its subclasses, which is all the Pyramid 5xx …

Don't wrap `HAPIError` in `HTTPInternalServerError`

---

lms/services/oauth2_token.py
tests/unit/lms/services/oauth2_token_test.py

We seem to be prompting the users to complete an oauth more often than before in canvas: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1632415274068500
This should only happen if the refresh token is no longer valid which seem to happen from time to time: https://my.papertrailapp.com/groups/14104911/events?q=refresh_token+not+found
A refresh token could be no longer valid if canvas decides that's the case or, if canvas sent us a new one and we still used the old one.
The refresh token changing should to not occur according to Canvas's docs: `The response to this request will not contain a new refresh token; the same refresh token is to be reused.`  https://canvas.instructure.com/doc/api/file.oauth.html but I'd like to log that to confirm it.
If refresh tokens did in fact change we …

Log refresh token changes

---

lms/views/exceptions.py
tests/unit/lms/views/exceptions_test.py

If an exception is handled by an exception view then Sentry's Pyramid integration won't automatically report the exception *unless* the exception view results in a 500 response. Since this exception view does always result in a 500 there's no need for us to manually report the exception.

Don't unnecessarily manually report things to Sentry

---

lms/views/exceptions.py

Because of recent changes (in https://github.com/hypothesis/lms/pull/3155/) this helper function is now only called in one place and its docstring is inaccurate.

Remove an unnecessary helper function

---

lms/services/assignment.py

The previous query was used in other cases but after a number of refactors it was left intact.

Simplify query for canvas assignment launch.

---

lms/static/scripts/frontend_apps/components/ContentSelector.js
lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js
lms/static/scripts/frontend_apps/config.js
lms/static/scripts/frontend_apps/utils/onedrive-picker-client.js
lms/static/scripts/frontend_apps/utils/test/onedrive-picker-client-test.js
lms/static/scripts/test-util/wait.js

I created the `OneDrivePickerClient` class that uses the
`loadOneDriveAPI` to load the OneDrive JS bundle asynchronously.
`OneDrivePcikerClient` has a single method, `showPicker` to launch the
OneDrive picker. It is a callback based method.
To test this PR:
* Login into http://localhost:8001/admin
* Find  the following consumer key: `Hypothesisb3be0b33d0b5e4b1cf3aaf04e0e1819a`
* Click on the `Microsoft OneDrive enabled` checkbox
* Click Save
Then, you should be able to see the `Select PDF from OneDrive` option when setting an assignment in LMS:

Integrate OneDrive file picker

---

lms/views/exceptions.py

It's pretty obvious that this method handles `HTTPClientError`'s:
```python
@exception_view_config(context=HTTPClientError)
def http_client_error(self):
...
```
So a docstring that says "Handle an HTTP 4xx (client error) exception" really isn't adding much (except possibly explaining that `HTTPClientError` = 4xx?).

Remove a pointless docstring

---

lms/views/exceptions.py

It was tempting to also change the `validation_error()` view to use the helper method:
```python
@exception_view_config(context=ValidationError, renderer="lms:templates/validation_error.html.jinja2")
def validation_error(self):
self.request.response.status_int = self.exception.status_int
return {"error": self.exception}
```
The `error_response()` would need to optionally accept either a `message` or an `error` kwarg and return either `{"message": message}` or `{"error": error}`. I decided it wasn't worth adding the complexity to `error_response()` just to reduce `validation_error()`'s two lines to one. `validation_error()` is legitimately different to the other views: it's returning data for the `validation_error.hml.jinja2` template instead of the `error.html.jinja2` template.
The …

Deduplicate some code with a helper method

---

lms/resources/_js_config/__init__.py
lms/static/scripts/frontend_apps/components/ErrorDialogApp.js
lms/static/scripts/frontend_apps/components/test/ErrorDialogApp-test.js
lms/static/scripts/frontend_apps/config.js
lms/views/exceptions.py
tests/unit/lms/views/exceptions_test.py

The thing being reused here is called a "consumer key" (or "OAuth consumer key") in LTI not a "tool GUID". The LTI spec actually contains something else called a "tool GUID" (or "tool consumer instance GUID") so it's probably best not to use "tool GUID" in place of "consumer key".
There's a sense in which "tool GUID" is actually correct here. The LTI app (us) is called the "tool provider" and the LMS (Canvas etc) is the "tool consumer" and the thing that is shared between the two (the "application instance" in our own code's terminology) is the "tool". Since the OAuth consumer key is the thing that uniquely identifies a particular application instance I can see why you might call that the "tool GUID". Nonetheless, I think LTI always calls this the "consumer key", introducing our own terms …

Rename "reused tool GUID" to "reused consumer key"

---

lms/resources/_js_config/__init__.py
lms/static/scripts/frontend_apps/components/ErrorDialogApp.js
lms/static/scripts/frontend_apps/components/test/ErrorDialogApp-test.js
lms/static/scripts/frontend_apps/config.js
lms/views/api/exceptions.py
lms/views/exceptions.py
tests/unit/lms/views/api/exceptions_test.py
tests/unit/lms/views/exceptions_test.py

Fixes https://github.com/hypothesis/lms/issues/3148
Use a `path_info=not_("^/api/.*")` view predicate to ensure that the non-API exception views are never used for API requests, and a similar `path_info="^/api/.*"` predicate to ensure that API exception views are _only_ used for API requests.
The exception views in `views/exceptions.py` are only intended to be used for non-API requests but in fact most of them are registered for all requests not just non-API requests. If one of these exceptions was raised during an API request, and not caught by a more specifically-configured exception view in `views/api/exceptions.py`, then it would be caught by a `views/exceptions.py` exception view. This would result in an HTML error page being sent as in API response.
Fix this by registering all the …

Don't register API exception views for non-API requests and vice-versa

---

lms/static/scripts/frontend_apps/components/BookPicker.js
lms/static/scripts/frontend_apps/components/ContentSelector.js
lms/static/scripts/frontend_apps/components/ErrorDialog.js
lms/static/scripts/frontend_apps/components/ErrorDialogApp.js
lms/static/scripts/frontend_apps/components/ErrorDisplay.js
lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/LMSFilePicker.js
lms/static/scripts/frontend_apps/components/OAuth2RedirectErrorApp.js
lms/static/scripts/frontend_apps/components/SubmitGradeForm.js
lms/static/scripts/frontend_apps/components/test/BookPicker-test.js
lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js
lms/static/scripts/frontend_apps/components/test/ErrorDialog-test.js
lms/static/scripts/frontend_apps/components/test/ErrorDialogApp-test.js
lms/static/scripts/frontend_apps/components/test/ErrorDisplay-test.js
lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js
lms/static/scripts/frontend_apps/components/test/OAuth2RedirectErrorApp-test.js

There is a huge amount of information in this PR description, but in summary:
This work ensures that auto-generated, useless error messaging doesn't get displayed by the front-end apps when there is already other contextual error information present. It does this by adjusting logic about how error descriptions and messages are displayed (or not displayed) within the `ErrorDisplay` component.
It also:
* Makes the "error app" components `ErrorDialogApp` and `OAuth2RedirectErrorApp` not crash in edge cases where error information is not present (this may not be a valid real-world state).
* Fixes a small visual bug in which the VitalSource book picker modal was too tall when an error is present.
What follows is a lot of explanation and screenshots, but a lot of this is documentation of how to …

Ensure frontend errors show appropriate error messages depending on context

---

lms/static/scripts/frontend_apps/icons.js

This is a prerequisite for moving to a modern ES-module oriented bundler
such as Rollup. See also https://github.com/hypothesis/client/pull/3795.

Convert remaining CommonJS imports to ES imports

---

lms/static/scripts/frontend_apps/components/ContentSelector.js
lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js
lms/static/scripts/frontend_apps/errors.js
lms/static/scripts/frontend_apps/utils/google-picker-client.js
lms/static/scripts/frontend_apps/utils/onedrive-picker-client.js
lms/static/scripts/frontend_apps/utils/test/google-picker-client-test.js
lms/static/scripts/frontend_apps/utils/test/onedrive-picker-client-test.js

Both `GooglePickerClient` and `OneDrivePickerClient` use
`PickerCanceledError`. @robertknight suggested to extract this error and
move it to a common location:
https://github.com/hypothesis/lms/pull/3134#discussion_r717529172

Extract common `PickerCanceledError` to a common path

---

lms/static/scripts/frontend_apps/components/ContentSelector.js

Currently, `setLoadingIndicatorVisible(false)` is only call when the
pickers encounter an error. However, it would be more correct to call
`setLoadingIndicatorVisible(false)` always, either on success or on
error. Thus I move the line inside a `finally` clause. Suggested by
@robertknight here:
https://github.com/hypothesis/lms/pull/3134#discussion_r718334171

Call `setLoadingIndicatorVisible(false)`

---

lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js

I use the `delay` function to simplify a few tests. Previously,
execution of `await FakeGooglePickerClient().showPicker()` had the same
effect (waiting for the macrotask execution) but it had other
consequences.
I removed the `FakeGooglePickerClient.resetHistory` line because it was
unnecessary: on every test, a new `sinon.stub` is assigned to the
FakeGooglePickerClient, and FakeGooglePickerClient is instantiated only
once per test.

Simplify tests for `ContentSelector-test.js`

---

tests/unit/lms/services/assignment_test.py

Note that there are a couple of `@pytest.mark.xfail`'s in these tests that should be removed once the service itself has been fixed.

Add more thorough tests for assignment service

---

lms/services/assignment.py

The `extra` argument doesn't appear to be used.
I'm not sure whether we should add an `extra` argument to `set_document_url()`: it's `set_document_url()` not
`set_document_url_and_merge_extras()`. Let's at least hold off until we have some code that uses the new argument.

Remove extra from set_document_url

---

lms/routes.py
lms/views/onedrive.py
tests/unit/lms/views/onedrive_test.py

One Drive consent screen still shows a "unverified" notice despite we having verified the "web.hypothes.is" domain with a static file on word press.
Is hard to be sure but this could be due to us verifying one subdomain while having the oauth redirect point to another one (the lms one).
With this PR we get to also verify both the qa and prod apps which might come handy for testing.
The verifying instructions look like:
- Go to http://localhost:8001/.well-known/microsoft-identity-association.json,  get some json back.

Add route to verify lms domain on MS app for one drive

---

lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js

From time to time we see the following errors in the CI/CD (specially in
GH):
> FAILED TESTS:
>   LMSFilePicker
>     ✖ updates the folder path when a user chooses a folder
>       Chrome Headless 94.0.4606.61 (Linux x86_64)
>     Error: waitFor(() => fakeApiCall.calledTwice) failed after 10 ms
>         at /tmp/test-util/wait.js:36:16 <- /tmp/e36ef211e9dc3af9693aa007befe49a6.browserify.js:43841:16a
I was able to reproduce this error locally if I attempted the test
several times. Increasing the timeout seems to solve the issue.

Increase the timeout in one LMSFilePicker test

---

lms/static/scripts/frontend_apps/components/ErrorDialogApp.js
lms/static/scripts/frontend_apps/components/ErrorDisplay.js
lms/static/scripts/frontend_apps/components/LaunchErrorDialog.js
lms/static/scripts/frontend_apps/components/OAuth2RedirectErrorApp.js

Make `ErrorDisplay` able to render children, and thus be able to render
everything pertinent to an error. This will allow for more straightforward
overflow and scroll control as we transition to shared components.
We have to manage the display of error information in a wild assortment
of contexts and viewports, so it's easier to manage if error UI is more
encapsulated.
No significant user-facing changes here. Scroll behavior is slightly different in very constrained viewports: the entirety of the modal content (excepting heading, buttons) will scroll. It would be lovely to just scroll the error details section, when expanded, but some of the error description text is so long that it leaves just a tiny, bitty space for error details in constrained viewports. 
Before:
After:
I've got more …

Make `ErrorDisplay` render `children`

---

lms/migrations/versions/a58605fdd398_add_ext_lti_assignment_id.py

For #2527
Generated from model changes in https://github.com/hypothesis/lms/pull/3118
Test migrating forward and backwards:
- `hdev alembic upgrade head`
- `hdev alembic downgrade d9c9e65c463e`
and check the output of `\d module_item_configurations` on `make sql`'s prompt

Migration for new ext_lti_assignment_id column

---

lms/views/onedrive.py
tests/unit/lms/views/onedrive_test.py

Set the exact same content and answer with a content-length header.
Set application_id to `f49d0253-f947-43f1-9735-ce73fde94af3` and compare the output with https://web.hypothes.is/.well-known/microsoft-identity-association.json
```
curl  https://web.hypothes.is/.well-known/microsoft-identity-association.json | md5sum 
1814193bf1f9c27500f60a05077b43b2                         
curl  http://localhost:8001/.well-known/microsoft-identity-association.json | md5sum
1814193bf1f9c27500f60a05077b43b2 
````

One drive verify size

---

lms/views/onedrive.py

Length header is not present when deployed 
````
curl -I --http1.1  https://qa-lms.hypothes.is/.well-known/microsoft-identity-association.json
````
(same result without the I --http1.1 flag)
I'm not sure if this will fix/change anything it but adding the header explicitly to the Response here.

Explicitly set Content-Length header

---

lms/views/onedrive.py

https://github.com/hypothesis/lms/pull/3199 broke the inclusion of `content-type`
On this PR:
```
curl -I  http://localhost:8001/.well-known/microsoft-identity-association.json 
HTTP/1.1 200 OK
Server: gunicorn
Date: Tue, 05 Oct 2021 15:28:00 GMT
Connection: close
Content-Length: 111
Content-Type: application/json
```

Explicitly include content type header

---

lms/resources/_js_config/__init__.py
lms/routes.py
lms/validation/_lti_launch_params.py
lms/views/api/canvas/files.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/validation/_lti_launch_params_test.py
tests/unit/lms/views/api/canvas/files_test.py

Changes the parameters the via url endpoint takes, from course and file ids as separate arguments to one `canvas://` like URL with both params encoded there.

Via url endpoint for canvas files takes a document_url

---

lms/resources/_js_config/__init__.py
lms/routes.py
lms/validation/_lti_launch_params.py
lms/views/api/canvas/files.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/validation/_lti_launch_params_test.py
tests/unit/lms/views/api/canvas/files_test.py

Reverts hypothesis/lms#3186
I'm seeing strange behavior around speed grader and I'm not sure if it's caused by the changes in this PR but I rather investigate with the revert merged.

Revert "Via url endpoint for canvas files takes a document_url"

---

lms/resources/lti_launch.py
lms/views/basic_lti_launch.py
lms/views/predicates/_lti_launch.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/views/basic_lti_launch_test.py
tests/unit/lms/views/predicates/_lti_launch_test.py

Using `resouce_link_id` in a launch is going to become more complex, involving conditionals so we might as well centralize the behavior first.

Take resouce_link_id from a context property

---

lms/resources/lti_launch.py
lms/views/api/lti.py
tests/unit/lms/resources/lti_launch_test.py

The `resource_link_id` provided by canvas on launches done while using
speedgrading is incorrectly set to the value of "context_id` (the course
ID). This is not causing any problems (apart from some orphan
assignments
on the DB) because we are using the `url` and `file_id` URL params to
get the assignment details.
This would become a problem once we switch to reading the assignments
info from the DB instead of the URL like we do for other LMS so it needs
to be fixed.
On master:
- Delete your assignments:
`truncate module_item_configurations ;`
- Launch a canvas assignment as a student: https://hypothesis.instructure.com/courses/125/assignments/1967
- Check `module_item_configurations` new row on database with resource_link_id `ec05d6beddad805005f98816f7e1bf26707a346f`.
- Launch now the …

Take resource_link_id from query params when speed grading

---

lms/resources/lti_launch.py
lms/views/basic_lti_launch.py
lms/views/predicates/_lti_launch.py
tests/unit/lms/resources/lti_launch_test.py

Same as the work previously done for `resource_link
t_id` https://github.com/hypothesis/lms/pull/3227 but now applying to `ext_lti_assignment_id`.
Note that ext_lti_assignment_id is never sent on SpeedGrader so `resource_link
t_id` should be enough to identify the assignment but getting both will make regular and speed grading launches to behave exactly the same.

Take ext_lti_assignment_id from query params when speed grading

---

lms/views/api/exceptions.py
lms/views/api/vitalsource.py
tests/unit/lms/views/api/exceptions_test.py
tests/unit/lms/views/api/vitalsource_test.py

If the frontend sends a request to the backend's `/api/vitalsource/books/{book_id}` or `/api/vitalsource/books/{book_id}/toc` API with an invalid `{book_id}` in the URL then `VitalSourceAPIViews` raises `ExternalRequestError`.
This is a misuse of `ExternalRequestError`: there hasn't been a problem with a request to an external service. The frontend's request to our API was bad.
So fix it to raise Pyramid's `HTTPBadRequest` instead of `ExternalRequestError`.
This requires adding a new API exception view for `HTTPBadRequest` because the fallback exception view (for `Exception`) doesn't seem to catch `HTTPBadRequest`'s. The `HTTPBadRequest` ends up not getting caught by any exception view and sending back Pyramid's builtin HTML 400 response. I guess Pyramid treats `HTTPException`'s specially …

Fix misuse of `ExternalRequestError` by `VitalSourceAPIViews`

---

lms/services/__init__.py
lms/services/blackboard_api/_basic.py
lms/services/blackboard_api/client.py
lms/services/exceptions.py
lms/services/h_api.py
lms/services/http.py
lms/services/lti_outcomes.py
lms/services/oauth_http.py
lms/services/vitalsource/client.py
tests/unit/lms/services/blackboard_api/_basic_test.py
tests/unit/lms/services/blackboard_api/client_test.py
tests/unit/lms/services/h_api_test.py
tests/unit/lms/services/http_test.py
tests/unit/lms/services/lti_outcomes_test.py
tests/unit/lms/services/oauth_http_test.py
tests/unit/lms/services/vitalsource/client_test.py

`HTTPError` is the exception class raised by `HTTPService` whenever anything goes wrong with a server-to-server HTTP request.
`HTTPService` is almost always used when sending HTTP requests: `HAPI`, `LTIOutcomesAPIClient`, `VitalSourceService` and `BlackboardAPIClient` all use `HTTPService`. `CanvasAPIClient` is the one thing that sends external HTTP requests without using `HTTPService` and that's only because `CanvasAPIClient`'s code is unusual and can't be easily refactored to work like the others do.
`HTTPError` is kind of the same thing as `ExternalRequestError` but with fewer attributes and less functionality:
```python
class ExternalRequestError(Exception):
"""
A problem with a network request to an external service.
...
"""
def __init__(self, explanation=None, response=None, …
```

Remove `HTTPError` (use `ExternalRequestError` instead)

---

lms/services/canvas_api/_basic.py
lms/services/exceptions.py
tests/unit/lms/services/canvas_api/_basic_test.py
tests/unit/lms/services/exceptions_test.py

We've recently done work to add the details of the request and response to Papertrail, Sentry, and the frontend's error dialog when an external HTTP request fails: https://github.com/hypothesis/lms/pull/3300, https://github.com/hypothesis/lms/pull/3299, https://github.com/hypothesis/lms/pull/3286, https://github.com/hypothesis/lms/pull/3264.
This doesn't work for Canvas: trigger an external request error from the Canvas API and you'll see that the request and response details are missing from the logs, Sentry and the error dialog.
We've added `ExternalRequestError.request` and `ExternalRequestError.response` properties and used these properties in `ExternalRequestError.__str__()` (for Papertrail) and in the `external_request_error()` exception view (for Sentry and the frontend).
The …

Fix Canvas API errors

---

lms/static/scripts/frontend_apps/components/URLPicker.js

Set preferred width on this modal such that longer error strings don't cause the modal to change width. The error displayed when a user enters a local-file URL was making the modal too wide:
And is now fixed:

Add content class to constrain width of URLPicker Modal

---

lms/validation/_base.py

This is unnecessary and it's also out of date: it doesn't actually contain all the public names that are currently in this module.

Remove an unnecessary `__all__`

---

lms/services/exceptions.py
lms/services/lti_outcomes.py
lms/views/api/canvas/exceptions.py
lms/views/api/exceptions.py
tests/unit/lms/services/exceptions_test.py
tests/unit/lms/views/api/exceptions_test.py

`ExternalRequestError` is starting to have too many attributes, especially since I want to add a new `ExternalRequestError.validation_errors` attr in a future PR.
The `ExternalRequestError.extra_details` attr isn't really necessary and isn't used for anything that we really need, so this commit removes it.

Remove `ExternalRequestError.extra_details`

---

lms/services/blackboard_api/_basic.py
lms/services/canvas_api/_basic.py
lms/services/exceptions.py
lms/services/oauth_http.py
lms/validation/_base.py
lms/views/api/exceptions.py
tests/unit/lms/services/blackboard_api/_schemas_test.py
tests/unit/lms/services/canvas_api/_basic_test.py
tests/unit/lms/services/exceptions_test.py
tests/unit/lms/validation/_base_test.py
tests/unit/lms/validation/authentication/_oauth_test.py
tests/unit/lms/views/api/exceptions_test.py

Depends on https://github.com/hypothesis/lms/pull/3326. Fixes https://github.com/hypothesis/lms/issues/3319
This works by changing `RequestsResponseSchema` to raise `ExternalRequestError`'s which will be handled by the same `external_request_error()` exception view that handles `ExternalRequestError`'s from `HTTPService`. A new `validation_errors` attr is added to `ExternalRequestError` so that it can record any validation errors along with the request and response.
Let's break some of the Blackboard and Canvas schemas to trigger some validation errors:
```diff
diff --git a/lms/services/blackboard_api/_schemas.py b/lms/services/blackboard_api/_schemas.py
index 3f609e14..1c9e8300 100644
--- a/lms/services/blackboard_api/_schemas.py
+++ b/lms/services/blackboard_api/_schemas.py
@@ -36,6 …
```

Log and monitor external requests and responses that fail validation

---

lms/resources/_js_config/__init__.py
lms/views/api/canvas/authorize.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/views/api/canvas/authorize_test.py

Make the `errorDetails` that the backend sends to the frontend in the `JSConfig` object always be a dict, rather than sometimes a dict and sometimes a string.
The purpose of `errorDetails` is that the frontend renders it in the **Error Details** box in the error dialog. Other than expecting it to be a dict (or "object" in JavaScript terms) the frontend treats it as an opaque value.
Depends on https://github.com/hypothesis/lms/pull/3336/
Fixes https://github.com/hypothesis/lms/issues/3333

Make errorDetails always a dict

---

lms/static/scripts/frontend_apps/config.js

This PR attempts to add some clarity around error data pertaining to errors that are inferred from the backend-provided config JS object.
It clarifies some typing in the config module to establish a base "interface" of expected fields about config-provided errors (errorCode, errorDetails).

Tighten up typing for JS configuration object

---

lms/views/onedrive.py
tests/unit/lms/views/onedrive_test.py

This never worked and it's not needed anymore.
Verification using Azure's "app registrations" option using this never worked and we ended
up using the "Microsoft Partner Network" instead where verification could be done with a TXT record on the DNS.

Remove MS OneDrive verification endpoint

---

lms/views/basic_lti_launch.py
tests/functional/views/basic_lti_launch_test.py

Until canvas assignments are stored on the DB on creation/editing this view will only handle launches of already present in the DB canvas file assignments (regular and SpeedGrader launches).
The view was disabled after the problems with legacy SpeedGrader launches. This enables it again with a `legacy_speedgrader=False` to guard against those problems.
In summary, before https://github.com/hypothesis/lms/pull/3126 is merged, in this PR:
- All url configured assignments (ie all no canvas-files assignments) use the  `url_configured_basic_lti_launch` view. That includes legacy speedgrader url assignments which where not covered by the functional tests yet.
- Newly created canvas file assignment will be handled `legacy_canvas_file_basic_lti_launch` (which will create a new row in the DB)
- …

Re-enable canvas_db_configured_basic_lti_launch view

---

tests/unit/lms/services/canvas_api/_basic_test.py

It's important for monitoring to pass the request and response when raising, but these tests weren't covering it.

Add some missing test coverage

---

lms/validation/_api.py
tests/unit/lms/validation/_api_test.py

- On https://github.com/hypothesis/lms/pull/3126, try to create a VS assignment. Fail.
- Rebase that branch onto this one, the creation will still fail, but the message won't be marshmallow's validation one.

Handle VitalSource assignments in the creation endpoint schema

---

lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.js
lms/static/scripts/frontend_apps/components/ErrorDialog.js
lms/static/scripts/frontend_apps/components/ErrorDisplay.js
lms/static/scripts/frontend_apps/components/LaunchErrorDialog.js
lms/static/scripts/frontend_apps/components/test/ErrorDisplay-test.js
lms/static/scripts/frontend_apps/components/test/LaunchErrorDialog-test.js
lms/static/scripts/frontend_apps/errors.js
lms/static/scripts/frontend_apps/services/test/vitalsource-test.js
lms/static/scripts/frontend_apps/test/errors-test.js
lms/static/scripts/frontend_apps/utils/test/api-test.js

This PR updates the `ErrorDisplay` component and `APIError` to help ensure that the "message" that gets displayed by `ErrorDisplay`, if any, is the appropriate one for the given error context.
In cases where the `ErrorLike` object passed to `ErrorDisplay` as the `error` prop has an extant `errorMessage`, that will get displayed (superseding `error.message`). In the case of APIErrors, the `errorMessage` field is populated from response data from the backend, or set to an empty string if the backend does not provide a message.
This prevents `ErrorDisplay` from rendering a generic message in these cases, but ensures that a server-provided message _will_ get displayed.
Some logic requiring the presence of `description` to render a message in `ErrorDisplay` has been removed, thankfully.
This …

Prefer `error.errorMessage` over `error.message` when displaying error details in `ErrorDisplay`

---

lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.js
lms/static/scripts/frontend_apps/components/ErrorDisplay.js
lms/static/scripts/frontend_apps/components/LMSFilePicker.js
lms/static/scripts/frontend_apps/components/LaunchErrorDialog.js
lms/static/scripts/frontend_apps/components/test/ErrorDisplay-test.js
lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js
lms/static/scripts/frontend_apps/components/test/LaunchErrorDialog-test.js
lms/static/scripts/frontend_apps/components/test/SubmitGradeForm-test.js
lms/static/scripts/frontend_apps/errors.js
lms/static/scripts/frontend_apps/services/test/vitalsource-test.js
lms/static/scripts/frontend_apps/test/errors-test.js
lms/static/scripts/frontend_apps/utils/test/api-test.js

This PR follows up on a request made during review of https://github.com/hypothesis/lms/pull/3345 to name the `APIError` field pertaining to the back-end-provided error message something more clear to its meaning.
`errorMessage` is renamed `serverMessage`.

Rename `errorMessage` -> `serverMessage` on `APIError`

---

lms/static/scripts/frontend_apps/components/SubmitGradeForm.js

Render `ErrorDialog`s (when relevant) outside of the component's
`<form>` element to prevent form styling, etc., from interfering with
the dialog contents.
The cause of #3352 specifically was a `white-space: nowrap` rule applied to `.SubmitGradingForm`. This was being applied to dialog contents (because the dialog was inside of `form.SubmitGradingForm`), causing the dialog to have horizontal scroll.
This is on Chrome. In some browsers/OSes, this will look different, e.g. may have a scrollbar always visible:
The description is cut off on the right mid-sentence:
Scrolling right looks like:
Everything fits as expected:
Fixes #3352
There are steps to reproduces this error in the original issue #3352

Prevent `SubmitGradeForm` styling from applying to error dialogs

---

package.json
yarn.lock

- @types/classnames is no longer needed because classnames has its own
types
- mkdirp is no longer used
- @types/gapi only needs to be listed in `devDependencies`, not
`dependencies`

Remove obsolete JS dependencies

---

lms/static/scripts/ui-playground/components/ErrorComponents.js
lms/static/styles/ui-playground/ui-playground.scss

This is the first of probably two or three PRs adding examples and documentation to the pattern library. To keep myself from getting overwhelmed, I'm chunking this work. This stuff is hard to nail down, but I've tried to get stuff out of my head as I understand it. We can edit for clarity as we proceed. I figure this is better than nothing at all?
Part of https://github.com/hypothesis/lms/issues/3191
Check out this branch and run `make dev` and then visit http://localhost:8001/ui-playground/errors

Add summary documentation about frontend errors, error "modes"

---

lms/resources/_js_config/__init__.py
lms/services/vitalsource/client.py
lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.js
lms/validation/_lti_launch_params.py
lms/views/basic_lti_launch.py
lms/views/predicates/__init__.py
lms/views/predicates/_lti_launch.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/services/vitalsource/client_test.py
tests/unit/lms/views/basic_lti_launch_test.py
tests/unit/lms/views/predicates/__init___test.py
tests/unit/lms/views/predicates/_lti_launch_test.py

For https://github.com/hypothesis/lms/issues/3329
Handles VitalSource assignments like any other type of assignment on Canvas.
Testing as https://github.com/hypothesis/lms/pull/3126 but using VS assignments as well.

Store VS assignments on the DB

---

lms/static/scripts/frontend_apps/components/ErrorDialogApp.js
lms/static/scripts/frontend_apps/components/ErrorDisplay.js
lms/static/scripts/frontend_apps/components/LaunchErrorDialog.js
lms/static/scripts/frontend_apps/components/OAuth2RedirectErrorApp.js
lms/static/scripts/frontend_apps/components/test/ErrorDisplay-test.js
lms/static/scripts/frontend_apps/components/test/OAuth2RedirectErrorApp-test.js

This PR provides a link to create a support issue from the current error wherever we display information about errors to users. It reworks the text shown to remove the "send us an email" option, and updates the link to create a support ticket to prefill the ticket form with relevant error information. This aims to make it easier for the support team to understand what a user is having trouble with.
Because the time was ripe, this PR also converts all links within help text to use the shared `Link` component. This does change the appearance of links, making them look like our "standard" (red) links.
I am going to open this PR in draft because there are still some nuances to work through, and I want to be sure to get input from @mattdricker .
The URL generated for the "open a support …

Provide link to create a support ticket from an error

---

lms/static/scripts/frontend_apps/components/BookSelector.js
lms/static/scripts/frontend_apps/components/ErrorDialog.js
lms/static/scripts/frontend_apps/components/ErrorDisplay.js
lms/static/scripts/frontend_apps/components/LaunchErrorDialog.js
lms/static/scripts/frontend_apps/components/SubmitGradeForm.js
lms/static/scripts/frontend_apps/components/test/BookSelector-test.js
lms/static/scripts/frontend_apps/components/test/ErrorDisplay-test.js
lms/static/scripts/frontend_apps/errors.js
lms/static/scripts/frontend_apps/test/errors-test.js

Depends on #3361 
This PR extracts the logic used to format error messages and error details into the `errors` module, and moves the `ErrorLike` type into this module as well. 
The goal is to centralize some of this logic so that we don't end up with regressions like https://github.com/hypothesis/lms/pull/3366 aims to address. This work represents a more "proper" fix than https://github.com/hypothesis/lms/pull/3366, but it has a dependency. This work could supersede that work if the dependency lands quickly.

Extract message- and details-formatting logic to `errors` module

---

lms/resources/_js_config/__init__.py
lms/services/vitalsource/client.py
lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.js
lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/FilePickerFormFields.js
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
lms/static/scripts/frontend_apps/components/test/FilePickerFormFields-test.js
lms/validation/_lti_launch_params.py
lms/views/basic_lti_launch.py
lms/views/predicates/__init__.py
lms/views/predicates/_lti_launch.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/services/vitalsource/client_test.py
tests/unit/lms/views/basic_lti_launch_test.py
tests/unit/lms/views/predicates/__init___test.py
tests/unit/lms/views/predicates/_lti_launch_test.py

This is the final piece needed for storing all canvas assignments on the DB using the assigments.create endpoint merged already.
Here, the frontend will use this API if the backend provided the details only when creating/editing assignments.
- `delete from module_item_configurations ;` unless you want to keep some of your db assignments
- HTML assignment, https://hypothesis.instructure.com/courses/125/assignments/1513. It won't store any record on the DB
- Canvas file assigment, https://hypothesis.instructure.com/courses/125/assignments/875, It will store a new record in the DB, but not using the new code.
- Edit https://hypothesis.instructure.com/courses/125/assignments/1513 ( https://en.wikipedia.org/wiki/Margaret_(singer))
- New record will show up on the DB ( no `resource_link_id`)
- …

Enable canvas assignment creation API

---

lms/resources/_js_config/__init__.py
lms/services/vitalsource/client.py
lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.js
lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/FilePickerFormFields.js
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
lms/static/scripts/frontend_apps/components/test/FilePickerFormFields-test.js
lms/validation/_lti_launch_params.py
lms/views/basic_lti_launch.py
lms/views/predicates/__init__.py
lms/views/predicates/_lti_launch.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/services/vitalsource/client_test.py
tests/unit/lms/views/basic_lti_launch_test.py
tests/unit/lms/views/predicates/__init___test.py
tests/unit/lms/views/predicates/_lti_launch_test.py

Reverts hypothesis/lms#3126
We seem to be missing a value for `ext_lti_assignment_id` while configuring the assignment on some Canvas instances.
https://hypothes-is.slack.com/archives/C01RAT0PE72/p1636982594002600
To test it, create assignments using master:
1. Configured but never launched (will only have ext_lti_assignment_id)
2. Configured and launched (will have values for both ext_lti_assignment_id and resource_link_id)
Launch them in this branch, they should launch successfully and to the same document.

Revert "Enable canvas assignment creation API"

---

lms/static/styles/_frontend-shared.scss

Dialogs influenced by local width styles were displaying off-center on
narrow screens in certain circumstances.
The rem-based widths in the LMS local dialog-width overrides were in
conflict with underlying styles for narrow screens. Narrow screens
already make dialogs the right size and position, and these adjustments
should only apply to wider breakpoints. The comment even hinted to that.
Fix by wrapping in a harmonious media query: dialogs will not appear
off-center on narrow screens.
Before:
After:

Wrap dialog widths in media query for correct size on narrow screens

---

lms/services/canvas_api/_basic.py

Fix the Canvas API code to use the same timeout as used by HTTP service.
This is a slightly longer timeout (10s instead of 9s) to follow the
requests docs advice:
>  It's a good practice to set connect timeouts to slightly larger than
> a multiple of 3, which is the default TCP packet retransmission
> window.
See:
https://docs.python-requests.org/en/latest/user/advanced/#timeouts
We also pass both timeouts separately, even though they're the same
value, just to be explicit that there are separate connect and read
timeouts.

Fix Canvas API timeout

---

requirements/format.txt

On master:
`hdev requirements` fails as it can't satisfy a constraint on `tomli`
I removed `requirements/format.txt`, run `hdev requirements` and this is the result.

Refresh format requirements

---

lms/services/canvas_api/_authenticated.py
lms/services/canvas_api/_basic.py
lms/services/canvas_api/client.py
tests/unit/lms/services/canvas_api/_authenticated_test.py
tests/unit/lms/services/canvas_api/_basic_test.py
tests/unit/lms/services/canvas_api/client_test.py

This is an attempt to fix https://github.com/hypothesis/lms/issues/3392.
Use `(20, 20)` (instead of the default `(10, 10)`) as the `requests` timeout only when making `courses/{course_id}/groups?include[]=users` requests. Keep the default timeout for all other requests.
This requires refactoring `BasicClient` and `AuthenticatedClient` to allow `CanvasAPIClient` to pass in a custom timeout only for the `courses/{course_id}/groups?include[]=users` calls. `CanvasAPIClient` needs to pass the custom timeout to `AuthenticatedClient.send()` which needs to pass it to `BasicClient.send()` which needs to pass it to `BasicClient._send_prepared()` which passes it to `requests.Session.send()`.

Use a longer timeout for "user's groups" requests

---

lms/services/user.py
tests/unit/lms/services/user_test.py

Note that the service is no longer a dataclass as it was not possible to use `lru_cache` without extra modification.
Between having to either have to play with different dataclass option and/or having to add a __hash__ method I prefer switching to a traditional class, there's no really data here. Renamed a db_session to db and added `_` for all fields to match other services.

New get method on UserService

---

lms/resources/lti_launch.py
lms/services/course.py
lms/services/grouping.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/services/course_test.py
tests/unit/lms/services/grouping_test.py

This was a bit scattered around. 
We don't usually receive an authority_provided_id so calling the course service it's a bit awkward, construct the authority_provided_id then call get with it so maybe another version of `get` could be useful but I reckon this goes in the right direction anyway.

Add CourseService.generate_authority_provided_id

---

lms/migrations/versions/1693f6ade03d_enable_ms_one_drive.py

Even if OneDrive is enabled by default any application instance that had previously a "false" value on the DB will override the default.
(on master)
- Leave only the devdata AI to compare:
`docker stop lms_postgres_1; docker rm lms_postgres_1; make services db devdata`
- Disable OneDrive an add a bunch of settings to one of the instances, on `make sql`:
`update application_instances set settings = '{"canvas": {"groups_enabled": false, "sections_enabled": false}, "blackboard": {"files_enabled": true}, "microsoft_onedrive": {"files_enabled": false}}' where id = 11;`
- Check the values of settings
`select id, settings from application_instances;`
(switch to this branch)
- `make db` to run the migration
- `select id, settings from application_instances;` ID 11 should have now the value set to …

Enable MS OneDrive on instances where it was explicitly disabled.

---

lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.js
lms/validation/_api.py
lms/views/api/lti.py
tests/unit/lms/views/api/lti_test.py

- Create a new VitalSource assignment (for example 0077383966) so there's no SG submissions
- Launch in SpeedGrader, there won't be any submissions.
- Launch as a student
- Back at SpeedGrader, refresh, there will be one submission now.

Support VS launches in SpeedGrader

---

tests/unit/conftest.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/services/user_test.py
tests/unit/services.py

application_instance_service returns application_instance on get_current
otherwise two different, conflicting application_instances rows are
created on the DB.

Reorg application_instances fixtures to work together

---

lms/migrations/versions/f359b6f378a9_add_grouping_membership_table.py

Auto generated from: https://github.com/hypothesis/lms/pull/3419
- On master
- `hdev alembic history`
`2fd66b9ab1a1 -> 1693f6ade03d (head), Enable MS OneDrive on instances that have previously been disabled.`
- On this branch
- `hdev alembic history`
`1693f6ade03d -> f359b6f378a9 (head), Adds grouping_membership table.`
- make db
```
INFO  [alembic.runtime.migration] Running upgrade 1693f6ade03d -> f359b6f378a9, Adds grouping_membership table.
```
- make sql
```
postgres=# \d grouping_membership 
Table "public.grouping_membership"
Column    |            Type             | Collation | Nullable | Default 
-------------+-----------------------------+-----------+----- …
```

Migration to add new grouping_membership table

---

lms/services/grouping.py
lms/views/api/canvas/sync.py
tests/factories/grouping.py
tests/unit/lms/services/grouping_test.py
tests/unit/lms/views/api/canvas/sync_test.py

Merges `upsert_canvas_section` and `upsert_canvas_group` methods of the grouping service into one.
This is in anticipation for what would become `upsert_blackboard_group`
- Renamed the existing upsert to `_upsert`
- New method is named `upsert_with_parent` and takes a non optional parent grouping.
- `upsert_with_parent` generates the authority_provided_id based on a `type_` param. It doesn't handle `type_` as in the current data model course don't have a parent grouping.

Merges upsert_canvas_section and upsert_canvas_group methods

---

lms/resources/_js_config/__init__.py
tests/unit/lms/resources/_js_config/__init___test.py

The `resource_link_id` param is part of the assignment (it's a unique identifier for the assignment), not part of the course.

Tweak the Blackboard sync API params

---

lms/migrations/versions/4a4c2539c666_add_check_constraint_to_grouping_table.py
lms/models/grouping.py

Course groupings cannot have parents, whilst all non-course groupings must have parents. This is true of the production data currently. This commit adds a DB-level constraint to ensure it.

Add a `CHECK` constraint to the grouping table

---

lms/migrations/versions/6882c201b56e_add_type_constraint_to_grouping_table.py
lms/models/grouping.py

This means that each time we add a new type of grouping we'll need to do a simple DB migration to widen this constraint. For that cost we get the benefit of ensuring at the DB-level that the `type` column can only contain valid values.
The code actually contains a [`Grouping` model](https://github.com/hypothesis/lms/blob/67d2266f919a63adaf14e4274bd838ced9aba053/lms/models/grouping.py#L14-L96) which is the base class for the [`CanvasSection`, `CanvasGroup`, `BlackboardGroup` and `Course` models](https://github.com/hypothesis/lms/blob/67d2266f919a63adaf14e4274bd838ced9aba053/lms/models/grouping.py#L99-L112). But it's never valid to actually instantiate the `Grouping` model: all groupings must be a Canvas section, Canvas group, Blackboard group or course, never just a "grouping".
By adding a …

Constrain the `grouping.type` column to valid values

---

lms/views/api/blackboard/sync.py
tests/unit/lms/views/api/blackboard/sync_test.py

This takes the current sync API that returns just [] and change it to return all the groups in the group set.
- No error handling for non existing group set or no groups in it.
- No error handling for the student not having access to that particular endpoint
This doesn't add much value on itself but I think it easier to review here the private methods and the consecutive PRs that add the conditionals (if student/teacher/grading) and error handling will be more focused.
- Switch to `bb-poc-testing`
- Pick this branch there `git cherry-pick bb-sync-teacher`
- Create a new assignment on BB, select group assignment and pick a group set.
- Launching the assignment as a teacher should diplay all the groups in the group set.

BB sync API returns all groups in the group set for all users

---

lms/resources/lti_launch.py
lms/validation/_assignment.py
lms/views/basic_lti_launch.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/views/basic_lti_launch_test.py

Store the group set of the assignment on extra for DB configured ones.
Note the change from "group_set" -> "group_set_id". We are storing currently the same value for canvas on the groupings themselves and it's probably  nicer if the names match between different extras even if they are in different tables.
```
select extra from grouping where type = 'canvas_group' and extra is not null  order by id desc limit 5;
{"group_set_id": 2631}
{"group_set_id": 2631}
{"group_set_id": 2631}
{"group_set_id": 2631}
{"group_set_id": 2631}
```
As a follow up this values in devdata will need to change: https://github.com/hypothesis/devdata/blob/1e24cf8f088c51cfd13439de4f4420fd763a3f7e/lms/devdata.json#L290

Store group set on the assignment while configuring it

---

lms/services/blackboard_api/_schemas.py
lms/services/blackboard_api/client.py
tests/unit/lms/services/blackboard_api/_schemas_test.py
tests/unit/lms/services/blackboard_api/client_test.py

It will be necessary to distinguish between groups can see but don't
necessary belong to (SelfEnrollment) and groups the student can only see if the
are member (InstructorOnly)

BlackboardListGroups schema exposes enrollment.type

---

lms/static/scripts/ui-playground/components/ErrorComponents.js

Phew, I think this satisfies https://github.com/hypothesis/lms/issues/3191, finally. It:
* Greatly simplifies the stuff that was in the local pattern-library documentation for error patterns;
* Reorders it;
* Adds examples for `LaunchErrorDialog`
At this point, I think it captures the intent of the various error-rendering components, without so much noise and fury. 
To review, check this branch out, run `make dev` and visit http://localhost:8001/ui-playground/errors
Fixes #3191

Finish adding local error patterns to pattern library

---

lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.js
lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js

This PR adds tests for newly-added functionality around assignment submission for assignments with VitalSource content, and tightens up a little bit of related logic (first commit, d7341a812c813a61ced08a623b87cd2478c613f7).
A second commit here updates some reference names per casing conventions (e.g. `contentUrl` => `contentURL` and `apiSync` => `groupAPICallInfo`) but has no functional changes (e01e4842cfe49a41ffad56ddb76c88c9cde0de56).

Clarify logic, add tests, and update reference naming in `LTIBasicLaunchApp`

---

lms/templates/admin/instance.html.jinja2

Renamed the generic "Sections" and "Groups" to include "Canvas" and reorganized a bit so it's clearer to see group of settings.
Added a check for the new `"blackboard", "groups_enabled"`

Reorg settings presentation and added blackboard.groups_enabled

---

lms/resources/_js_config/__init__.py
tests/unit/lms/resources/_js_config/__init___test.py

Will be later needed to get the value back on the sync API.

Expose the user.user_id while grading

---

lms/services/group_info.py

Needed to store `GroupInfo` when BLACKBOARD_GROUPS are involved.

Group info service aware of Blackboard groups

---

lms/services/blackboard_api/client.py
tests/unit/lms/services/blackboard_api/client_test.py
tests/unit/services.py

~~This PR includes the commits from https://github.com/hypothesis/lms/pull/3446~~
Method to get groups of a course it needs more complexity that initially thought:
- Using AsyncOauthService to make multiple request the the API 
- Make those request only for self-enrollment groups.

Blackboard course groups

---

lms/views/basic_lti_launch.py
tests/unit/lms/views/basic_lti_launch_test.py

After the assignment is configure parts of the JSConfig might have
changed so we need to re-enable lti launch mode.
The existing case this fix is while configuring a groups assignments.
The first call to enable_lti_launch_mode on `__init__` won't populate
the sync API but once the assignment is configured a second call will.
As parts of js_config are memoized we need to manually clear its cache.

Re-enable_lti_launch_mode on basic_lti_launch.configure_assignment

---

lms/views/api/blackboard/sync.py

The purpose of leading underscores is to distinguish a package/class/module's public interface from its private parts.
View classes don't have a public interface in the sense of attributes that're used by other parts of our code: we don't write code to call our views, they just get called by Pyramid.
The leading underscores could be useful to visually identify which things are going to be called by Pyramid (e.g. the actual view functions/methods) and which things are not called directly by Pyramid (e.g. helpers). But the actual view functions/methods are already identifiable by their `@view_config` decorators.
So I don't think there's any purpose to using leading underscores in view modules/classes (?), therefore there's no reason to ugly-up the code with them.
Note that we absolutely do …

Remove underscores from Blackboard sync API view

---

lms/resources/_js_config/__init__.py
lms/resources/_js_config/file_picker_config.py
lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/FilePickerFormFields.js
lms/static/scripts/frontend_apps/components/GroupConfigSelector.js
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
lms/static/scripts/frontend_apps/components/test/FilePickerFormFields-test.js
lms/static/scripts/frontend_apps/components/test/GroupConfigSelector-test.js
lms/static/scripts/frontend_apps/config.js
tests/unit/lms/resources/_js_config/file_picker_config_test.py

This PR contains front-end support for configuring assignments with Blackboard groups. It does not support grading these assignments; that will come later.
This branch contains frontend implementation, including tests, for configuring assignments with Blackboard groups. Several leading commits on this branch represent related backend changes that underpin the work. For each of these back-end commits, we'll need to determine:
* Whether the commit belongs with this set of work at all or not;
* Whether the commit can be landed independently of these changes, or;
* Whether the commit is a direct dependency for these changes directly and perhaps _should_ be included on this branch (tests needed). The `ltiLaunchUrl` configuration change and not returning `blackboard` or `canvas` file-picker …

Front-end support for assignment configuration with BB groups

---

lms/resources/lti_launch.py
tests/unit/lms/resources/lti_launch_test.py

If `LTILaunchResource.blackboard_groups_enabled` checks `application_instance.product` (and returns `False` if `tool_consumer_info_product_family_code` isn't `"BlackboardLearn"`) we run the risk of the Blackboard Groups feature being disabled when it should be enabled if there are Blackboard instances that use a different `tool_consumer_info_product_family_code`. The code is also more complicated.
On the other hand if `LTILaunchResource.blackboard_groups_enabled` just checks the value of `application_instance.settings.get("blackboard", "groups_enabled")` without checking the product then the risk is that we'll enable Blackboard Groups in a non-Blackboard LMS. This would result in broken behaviour, but:
* It would only happen if a Hypothesis admin incorrectly enabled Blackboard Groups for …

Simplify the blackboard_groups_enabled property

---

lms/static/scripts/frontend_apps/components/ContentSelector.js
lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
lms/static/scripts/frontend_apps/utils/content-item.js
lms/static/scripts/frontend_apps/utils/google-picker-client.js
lms/static/scripts/frontend_apps/utils/onedrive-picker-client.js
lms/static/scripts/frontend_apps/utils/test/google-picker-client-test.js
lms/static/scripts/frontend_apps/utils/test/onedrive-picker-client-test.js

When configuring an assignment in an LMS with some sort of groups (Canvas, Blackboard) enabled, there is a second step after choosing content for configuring groups. On this step, we show the user information about the content they just selected. These changes make the actual filename show up for selected Google and OneDrive PDFs in this case, instead of meaningless URLs.
With long filenames, I've elected to harshly wrap vs. truncate the filename, as sometimes the most important part of the filename is at the beginning, and sometimes the end, and I don't think this is a big crisis, e.g.:
On this branch, configure a groups-enabled assignment (Canvas or BB) and select OneDrive and/or Google Drive content.
Fixes https://github.com/hypothesis/lms/issues/3365

Show real filenames for Google-, OneDrive-picked LMS files 

---

lms/resources/_js_config/file_picker_config.py
lms/templates/admin/instance.html.jinja2
lms/views/admin.py
tests/unit/lms/resources/_js_config/file_picker_config_test.py
tests/unit/lms/views/admin_test.py

For https://github.com/hypothesis/product-backlog/issues/1255
- Create/Edit a Canvas assignment
- The VitalSource option won't be present
- Toggle the VS settings for `Hypothesisb3be0b33d0b5e4b1cf3aaf04e0e1819a` on http://localhost:8001/admin
- Edit the assignment again, the VS option will be present.

Use an ApplicationInstance switch to toggle VitalSource on/off

---

lms/static/scripts/frontend_apps/components/LMSGrader.js
lms/static/scripts/frontend_apps/components/test/LMSGrader-test.js
lms/static/scripts/frontend_apps/config.js
lms/static/scripts/frontend_apps/services/client-rpc.js
lms/static/scripts/frontend_apps/services/test/client-rpc-test.js

This PR adds support for passing a set of focused-user groups along to the `setFocusedUser` RPC call to the client. 
Depends on corresponding changes in the client app (however, these changes appear innocuous if run without client-side support). Please see https://github.com/hypothesis/client/pull/3991 for further details of the bigger picture.
Based on discussions with team members, further error handling will be taken care of as a subsequent task. The failure mode in these changes is that all of the groups in the group set would show up in the sidebar (instead of just the focused-student's groups). That is identical to what currently happens anyway, without these changes.
Part of https://github.com/hypothesis/lms/issues/3416

Show only currently-focused-student's groups in grading mode

---

lms/static/scripts/frontend_apps/components/BookSelector.js
lms/static/scripts/frontend_apps/components/URLPicker.js
lms/static/scripts/frontend_apps/components/ValidationMessage.js
tailwind.config.mjs

This is based on some reviewer feedback on a previous PR and some rumination of my own.
Naming a color (token/variable) `success` or `error` means that some of the tailwind- generated utility classnames are less than crystal clear in some contexts. For example, `.text-error` doesn't clearly communicate that it is setting foreground/text color.
For this reason, I've elected to change these to `green-success`, `yellow-notice` and `red-error`. I believe this communicates more clearly the meaning of these utility classes (e.g `.text-red-error`).
Once this is landed, we can make this change to the global preset in `frontend-shared` and remove this local `tailwind.config` change.

Rename tailwind colors related to state to be less ambiguous

---

tests/factories/user.py

`factories.User()` has never worked: subfactories must be other factories not model objects.
Tip: a good way to test your factories is using `make shell`:
```python
$ make shell
...
Environment:
...
f            The test factories for quickly creating objects.
factories    The test factories for quickly creating objects.
...
>>> user = factories.User()
---------------------------------------------------------------------------
AssociatedClassError                      Traceback (most recent call last)
...
AssociatedClassError: <BuildStep for <StepBuilder(<SQLAlchemyOptions for UserFactory>, strategy='create')>>: Attempting to recursing into a non-factory object <class 'lms.models.application_instance.ApplicationInstance'>
```
The reason why the tests were still passing is that they never …

Fix `factories.User.application_instance` subfactory

---

tests/factories/attributes.py

The `* 30` in `H_USERID` looks like a mistake:
```python
$ make shell
>>> factories.User().h_userid
'acct:5@example.comacct:f@example.comacct:f@example.comacct:f@example.comacct:5@example.comacct:8@example.comacct:c@example.comacct:1@example.comacct:2@example.comacct:9@example.comacct:4@example.comacct:0@example.comacct:f@example.comacct:8@example.comacct:e@example.comacct:6@example.comacct:2@example.comacct:1@example.comacct:0@example.comacct:a@example.comacct:b@example.comacct:b@example.comacct:5@example.comacct:1@example.comacct:3@example.comacct:f@example.comacct:8@example.comacct:2@example.comacct:8@example.comacct:6@example.com'
```
With this commit it's now:
```python
$ make shell
>>> factories.User().h_userid
'acct:9@example.com'
```

Fix `factories.User.h_userid`

---

tests/factories/attributes.py

`factories.User.h_userid` is using a single random hex digit to try to make each user ID different from the previous:
```python
Faker("hexify", text="acct:^@example.com")
```
This quickly results in duplicate user IDs being generated:
```
$ make shell
>>> factories.User()
User(..., h_userid='acct:f@example.com')
>>> factories.User()
User(..., h_userid='acct:4@example.com')
>>> factories.User()
User(..., h_userid='acct:4@example.com')
```
Change it to use a sequence number instead, which is guaranteed to never generate the same ID twice:
```python
$ make shell
>>> factories.User()
User(..., h_userid='acct:user_1@example.com')
>>> factories.User()
User(..., h_userid='acct:user_2@example.com')
>>> factories.User()
User(..., h_userid='acct:user_3@example.com')
```

Make `factories.User.h_userid` unique

---

lms/resources/lti_launch.py
tests/unit/lms/resources/lti_launch_test.py

Before this fix disabling the groups feature at the AI level
will silently convert all existing groups assignments to sections ones.
With this commit the AI toggle only enables/disable the possibility to
create new groups assignments.

canvas_is_group_launch doesn't depend on the AI setting.

---

lms/validation/__init__.py
lms/validation/_api.py
lms/views/api/blackboard/sync.py
tests/unit/lms/validation/_api_test.py
tests/unit/lms/views/api/blackboard/sync_test.py

A more focused version of https://github.com/hypothesis/lms/pull/3514 with only the param validation.
Left on that PR are:
- A refactor or the sync view. Fetch most params on the main view function and pass them along to helper functions.
- Validate also the params the backed sends to the frontend so they are in sync in both directions.
for which I made a note to revisit once the rest of the BB sprint issues are closed.
No new feature or behavior changes. 
Open a BB group assignment as both a teacher and student.

Validate params on BB sync API

---

lms/views/__init__.py
lms/views/api/blackboard/sync.py
lms/views/api/canvas/exceptions.py
lms/views/api/exceptions.py
tests/unit/lms/views/api/blackboard/sync_test.py

Handles `blackboard_student_not_in_group` and `blackboard_group_set_empty`
Sync API returns
```
{
"error_code": "blackboard_student_not_in_group",
"details": {
"group_set": "_55_1"
}
}
```
- Use `localhost (make devdata) Groups Assignment With No Groups` and `localhost (make devdata) Groups Assignment with No Members` to  trigger the error conditions.

Handle Blackboard  groups edge cases

---

lms/resources/lti_launch.py
tests/unit/lms/resources/lti_launch_test.py

If the Blackboard Groups feature is enabled for an application instance and users create some groups assignments and then the feature gets disabled for the application instance those pre-existing groups assignments should remain groups assignments, theys shouldn't become course assignments.
Slack thread:
https://hypothes-is.slack.com/archives/C4K6M7P5E/p1638379099478700

Keep Blackboard groups assignments if feature is disabled

---

lms/static/scripts/frontend_apps/components/LaunchErrorDialog.js
lms/static/scripts/frontend_apps/components/test/LaunchErrorDialog-test.js
lms/static/scripts/frontend_apps/errors.js
lms/views/api/blackboard/sync.py
tests/unit/lms/views/api/blackboard/sync_test.py

For #3479 
- Open `localhost (make devdata) Groups Assignment Whose Group Set Has Been Deleted` as a instructor. You should see an error dialog.

Handle Blackboard Groups assignments whose group set no longer exists

---

lms/services/exceptions.py
lms/views/api/exceptions.py
tests/unit/lms/services/exceptions_test.py
tests/unit/lms/views/api/exceptions_test.py

Based on comments from https://github.com/hypothesis/lms/pull/3503.

Expose cause on ExternalRequestError

---

lms/migrations/versions/f581d8a273cc_constrain_child_groupings_to_parents_.py
lms/models/grouping.py
lms/services/grouping.py
tests/unit/lms/services/grouping_test.py

On master it's possible to create a grouping (e.g. a Blackboard group) whose parent grouping (a Blackboard course) belongs to a different application instance, which makes no sense.
For example this first creates `PARENT_GROUPING` with `application_instance_id` `1` and then creates `CHILD_GROUPING` with `application_instance_id` `2` and with `PARENT_GROUPING` (`parent_id` `1`) as its parent:
```sql
postgres=# INSERT INTO grouping (application_instance_id, authority_provided_id, lms_id, lms_name, type) VALUES (1, 'authority_provided_id', 'lms_id_1', 'PARENT_GROUPING', 'course');
INSERT 0 1
postgres=# INSERT INTO grouping (application_instance_id, authority_provided_id, parent_id, lms_id, lms_name, type) VALUES (2, 'authority_provided_id', 1, 'lms_id_2', 'CHILD_GROUPING', …
```

Ensure that child groupings must belong to the same application instance as their parents

---

lms/migrations/versions/7a4812876915_fix_user_id_unique_constraint.py
lms/models/user.py

`user_id` (the LTI user ID) should be unique (within an application instance).
And, separetely from that, `h_userid` (the user ID of the corresponding h user) should also be unique (again, within an application instance).
But those are two separate unique constraints not one. The current constraint allows two users to have the same LTI ID as long as they have different h IDs and vice-versa:
```sql
INSERT INTO public.user (application_instance_id, user_id, h_userid) VALUES (1, 'user_id_1', 'h_userid_1');
-- Insert a second user with the same user_id as the first.
INSERT INTO public.user (application_instance_id, user_id, h_userid) VALUES (1, 'user_id_1', 'h_userid_2');
--Insert a second user with the same h_userid as the first.
INSERT INTO public.user (application_instance_id, user_id, …
```

Fix user unique constraint

---

lms/services/user.py

Fixes https://github.com/hypothesis/lms/issues/3604
If an LMS changes its `tool_consumer_instance_guid` (or if a `consumer_key` gets installed in a second LMS with a different `tool_consumer_instance_guid`) we're supposed to refuse to launch and show an error dialog: https://github.com/hypothesis/lms/pull/3053
But since we added a new DB constraint (https://github.com/hypothesis/lms/pull/3494) we're now crashing with an `IntegrityError` instead.
The reason is that the changed `tool_consumer_instance_guid` causes us to generate a different `h_userid` and then when looking for the user in the DB we unnecessarily include the `h_userid` in the query. Fix it by removing the `h_userid` from the query so that we do find the existing user with the same `user_id` and `application_instance` even …

Don't crash if `tool_consumer_instance_guid` changes

---

lms/services/file.py
lms/services/upsert.py
tests/unit/lms/services/upsert_test.py

Remove some complexity to try to auto detect columns defined with "onupdate" on the ORM model.
This might not even be complex enough as SQLA has lots of edge cases for every feature.
Doing this only for some hardcoded condition (the name of the column is "updated" or that the class uses `CreatedUpdatedMixin) might achieve the same thing now but I think it will hide the fact that it's not doing it in general.
Just removing all of this and remembering to pass all the columns that need updating explicitly it's cleaner.

Remove autodetecting of columns defined in the ORM on bulk_upsert

---

lms/services/grouping.py
tests/unit/lms/services/grouping_test.py

- `truncate grouping_membership` on `make sql`
- Launch a groups assignment in blackboard.
- `select * from grouping_membership;` should return rows.
- Launch the assignment again.
- `select * from grouping_membership;` created` should be different than `updated`.

Use bulk_upsert for gruping memberships

---

lms/static/styles/ui-playground.scss
tailwind.config.mjs

This PR makes a few tweaks such that this project is ready for a forthcoming release of `frontend-shared`, which will provide pattern-library styling via tailwind.
The upcoming pattern-library styles will assume that all Tailwind layers (base, components, utilities) are enabled, and adds some rules to base and components layers. Thus, local pattern-library stylesheet entry point needs to activate those layers (this is already done in the `client`).
The next release of `frontend-shared` contains an updated tailwind preset that will provide the "success-green" color, but in a slightly different location than the current local tailwind configuration expects. There is a little conditional here for the interim to allow it to find that color in different places as we change over.
It also adds …

Prepare for next version of `frontend-shared` (tailwind tweaks)

---

tests/unit/lms/services/grouping_test.py

Tidy up the `generate_authority_provided_id()` tests a little:
- Add a missing test for when it raises `AssertionError`
- Add a missing test case for generating Blackboard group `authority_provided_id`'s
- Remove an unnecessary `db_session.flush()`

Tidy `generate_authority_provided_id()` tests

---

lms/services/grouping.py
tests/unit/lms/services/grouping_test.py

`generate_authority_provided_id()` raises if you try to generate an `authority_provided_id` for a non-course grouping with no parent. For good measure it should also raise if you try to generate one for a _course_ grouping _with_ a parent: if `type_ == Grouping.Type.COURSE` then the `parent` argument would not be used to it makes no sense to call `generate_authority_provided_id()` in this way.

Raise if a course grouping has a parent

---

lms/static/scripts/frontend_apps/components/AuthorizationModal.js
lms/static/scripts/frontend_apps/components/GroupConfigSelector.js
lms/static/scripts/frontend_apps/components/test/AuthorizationModal-test.js
lms/static/scripts/frontend_apps/components/test/GroupConfigSelector-test.js

This PR adds error-handling UI for errors encountered during configuring assignments with groups in both Blackboard and Canvas. 
Previously, if any error was encountered in the request to the proxied groups API, the UI would treat it as an authorization error and would provide an auth button in the interface like so (this screen shot is from Canvas, but it also did this in Blackboard):
Clicking that button does indeed trigger the auth process, but if the underlying problem wasn't one of authorization, this could lead to a confusing loop for the user.
After these changes, authorization errors are handled with a (new) `AuthorizationModal` UI and other errors with the pre-existing `ErrorModal` component. All are now displayed in modal dialogs.
Logic detail: Group-set retrieval is triggered …

Add error handling UI for group-set configuration for Blackboard and Canvas

---

tests/unit/lms/services/grouping_test.py

Mostly by using a partial fixture to reduce noise and duplication.

Tidy `upsert_with_parent()` tests

---

lms/services/grouping.py
tests/unit/lms/services/grouping_test.py

For newly created users or groupings the ORM objects will be present in the session but might not be yet flushed and their `.id` fields will be `None` causing upsert to fail.
Fixes https://sentry.io/organizations/hypothesis/issues/2978797202/?project=259908&referrer=slack

upsert_grouping_memberships flushes when necessary

---

lms/services/grouping.py
tests/unit/lms/services/grouping_test.py

This is causing: https://sentry.io/organizations/hypothesis/issues/2981919435/?project=259908&referrer=slack
In retrospect returning a query is the right call for `bulk_upsert` but not a good design (on top of being broken) for `upsert_with_parent`. This allows all the callers to forget about doing .all()/.one().
- On master, launch a canvas assignment, for example: https://hypothesis.instructure.com/courses/125/assignments/1833
You'll hit a ```TypeError: object of type 'Query' has no len()```
- Change to this branch. No crash.

Change upsert_with_parent to return a list instead of a query

---

lms/static/scripts/frontend_apps/components/GroupConfigSelector.js
lms/static/scripts/frontend_apps/components/test/GroupConfigSelector-test.js
lms/static/scripts/frontend_apps/errors.js

This PR adds UI handling for a state in which we get a valid response from the list-group-sets API service (either Canvas or Blackboard) but the list of groups is empty. This happens if an instructor-user is configuring an assignment to use group sets (i.e. checks the checkbox for "This is a group assignment") but there are no group sets for the current course.
In this case, we show an error message to the user explaining that there are no group sets available for the current course and link to some help documents about using groups.
The new modal looks like this: 
The diff looks larger than it "is" because I reorganized a few things in `GroupConfigSelector`, but did not alter any functionality outside of the changes at hand (all existing tests still passed).
There are some instructions …

Add UI handling for empty group sets returned by API during assignment configuration

---

lms/services/grouping.py
lms/services/upsert.py
tests/unit/lms/services/grouping_test.py
tests/unit/lms/services/upsert_test.py

For https://sentry.io/organizations/hypothesis/issues/2982856751/?referrer=slack
This involves a hacky workaround in bulk_upsert to always return the same type.
Also handled the same case directly in Grouping.upsert_with_parent.
I don't think the change in Grouping.upsert_with_parent is enough as it would leave this surprising behaviour in bulk_upsert.
An alternative would be to always return a list in `bulk_upsert` but that will cause a query and serializing the results in File.upsert but it's definitely less hacky.
- Switch to master
- Apply a diff similar to:
```diff --git a/lms/views/api/canvas/sync.py b/lms/views/api/canvas/sync.py
index 80af13c1..580e915c 100644
--- a/lms/views/api/canvas/sync.py
+++ b/lms/views/api/canvas/sync.py
@@ -83,12 +83,12 @@ class Sync:
if …
```

Bulk upsert returning

---

lms/services/exceptions.py
tests/unit/lms/services/exceptions_test.py

Nothing really changed but as a sanity check:
- Open a BB group assignment as a student with these diffs:
- Requests without response:
```diff
diff --git a/lms/services/async_oauth_http.py b/lms/services/async_oauth_http.py
index d00a1152..3e5dd9fe 100644
--- a/lms/services/async_oauth_http.py
+++ b/lms/services/async_oauth_http.py
@@ -55,7 +55,7 @@ async def _prepare_requests(method, urls, **kwargs):
_async_request(
session,
method,
-                    url,
+                    "https://notreallyadomainthatworks.com/",
**kwargs,
)
)
```
Error dialog:
Sentry event: 
https://sentry.io/organizations/hypothesis/issues/2985295889/?project=5952630&query=is%3Aunresolved
- Failed request with a response:
```diff
diff --git a/lms/services/async_oauth_http.py b/lms/services/async_oauth_http.py …
```

Remove unused attributes from ExternalAsyncRequestError

---

lms/services/async_oauth_http.py
lms/services/exceptions.py
tests/unit/lms/services/exceptions_test.py

- Same as https://github.com/hypothesis/lms/pull/3643
- Requests without response, no changes, there's no body.
- Requests with response:
Error dialog: Same error dialog as the response is not rendered here
Sentry event: The event includes the response text.
https://sentry.io/organizations/hypothesis/issues/2985309778/events/4b6d0dd6ef7c46bfb6671d9713a2a7b9/?project=5952630&query=is%3Aunresolved

Expose ExternalAsyncRequestError.response_body

---

lms/services/__init__.py
lms/services/async_oauth_http.py
lms/services/blackboard_api/client.py
lms/services/exceptions.py
lms/views/api/exceptions.py
tests/unit/lms/services/async_oauth_http_test.py
tests/unit/lms/services/blackboard_api/client_test.py
tests/unit/lms/services/exceptions_test.py

- Make a change similar to:
```diff
diff --git a/lms/services/blackboard_api/client.py b/lms/services/blackboard_api/client.py
index 838dfd85..03ba6b97 100644
--- a/lms/services/blackboard_api/client.py
+++ b/lms/services/blackboard_api/client.py
@@ -156,7 +156,7 @@ class BlackboardAPIClient:
self_enrollment_groups.append(group)
self_enrollment_check_urls.append(
self._api._api_url(  # pylint: disable=protected-access
-                        f"/learn/api/public/v2/courses/uuid:{course_id}/groups/{group['id']}"
+                        f"/learn/api/public/v25/courses/uuid:{course_id}/groups/{group['id']}"
)
)
```
- Launch `localhost (make devdata) Groups Assignment` has a student.
- You should get a dialog with some details about the failed request.

Handle all async errors

---

lms/static/scripts/frontend_apps/components/BookPicker.js
lms/static/scripts/frontend_apps/components/ChapterList.js
lms/static/scripts/frontend_apps/components/test/BookPicker-test.js

Use alternate vocabulary for "chapter" and "page" as these concepts
don't map consistently to VitalSource eBooks.
Change Modal title, column header and submit button text.
No functional changes, just wording in UI.
Before:
After:
Fixes https://github.com/hypothesis/product-backlog/issues/1269

Update labeling related to "chapters" in VitalSource book picker

---

lms/static/scripts/frontend_apps/components/LMSGrader.js

On initial launch into grading mode, an instructor's full set of course groups are fetched and available in the client's group menu. Error- and authorization-handling are part of this launch process and are all sorted. Once in the grading mode, the instructor can page through to different students (we call this "focusing" on a given student). When a student is focused, the UI layer makes a request to the sync API to ask for a list of just that student's groups. 
The initial objective had been to add error handling to these requests for a focused-student's groups. However, in poking around for a while, @marcospri and I were unable to come up with a plausible likely error path that justified the effort of implementing additional error handling. The failure mode is quite benign: the UI will …

Clarify that we are not going to add additional error handling for student groups sync in grading mode

---

Makefile

Depends on https://github.com/hypothesis/devdata/pull/44
Automatically read in envvars from the `.devdata.env` file created by the `make devdata` command.
The `make devdata` command writes several environment variables that are needed for development to the git-ignored `.devdata.env` file. When you run `make dev` a tox plugin reads `.devdata.env` into tox. But the `make run-docker` command that runs the app locally in Docker rather than tox doesn't read from the `.devdata.env` file. The user needs to manually copy envvars from `.devdata.env` into `Makefile` before running `make run-docker`, as explained by the comment in `Makefile`:
https://github.com/hypothesis/lms/blob/f7d1d5c0e016de139f8edd7e328f08895411e2df/Makefile#L106-L126
This `Makefile` change can't be committed to git because …

Read envvars from `.devdata.env`

---

lms/views/application_instances.py
tests/unit/lms/views/application_instance_test.py

Disable sections by default for new installs.
Fixes https://github.com/hypothesis/product-backlog/issues/1276
1. Go to <http://localhost:8001/welcome> and register a new application instance **with** a Canvas developer ID and developer key. You can just enter fake values for all fields, including the developer ID and key
2. Inspect the new application instance in your DB. On master, because you provided a developer key, the application instance will have sections enabled. On this branch sections will be disabled (but groups will still be enabled):
```
tox -qe dockercompose -- exec postgres psql -U postgres -c "SELECT settings FROM application_instances WHERE consumer_key = '<CONSUMER_KEY>';"
settings                            
-------------------------------------------------------------- …
```

Disable sections by default for new installs

---

lms/static/scripts/frontend_apps/utils/onedrive-picker-client.js

We've seen some situations where certain properties may be missing or
arrays may be empty [1]. We haven't clarified the details yet, but as a step
towards using types to enforce checking of potentially missing fields,
add some partial types for OneDrive picker responses.
The OneDrive picker is loaded from a remote source and doesn't have its
own types. Microsoft do publish a package,
@microsoft/microsoft-graph-types, for the Microsoft Graph API, but it is
huge, which will slow down tsc, and also doesn't provide good
information on the nullability of properties. Everything is simply listed as
nullable. Therefore I think it may be sensible for us to define our own
partial types based on what we use and observed behavior of the API.
[1] …

Add partial types for OneDrive file picker responses

---

lms/views/api/canvas/sync.py
tests/unit/lms/views/api/canvas/sync_test.py

Part of https://github.com/hypothesis/lms/issues/3640
Store memberships of students/sections
- Start with an empty table `truncate grouping_membership`
- Launch https://hypothesis.instructure.com/courses/125/assignments/873 **as a student**
- `select * from grouping join grouping_membership on grouping.id = grouping_membership.grouping_id;`
```
-[ RECORD 1 ]-----------+-----------------------------------------
created                 | 2022-01-27 10:49:53.646926
updated                 | 2022-02-07 12:00:35.725194
id                      | 116
application_instance_id | 8
authority_provided_id   | d2871e5e1c36b58f207d9ef5b22dcb7829f52e61
parent_id               | 115
lms_id                  | 144
lms_name                | Section 1
type                    | canvas_section
settings …
```

Store student group memberships for canvas sections

---

lms/views/api/exceptions.py
tests/unit/lms/views/api/exceptions_test.py

Return a dataclass from the API exception views.
This is to enable a future addition. Currently the exception views all call a `response_body()` helper method that returns a JSON-serializable dict:
```python
return self.error_response(
message=...,
details=...,
...
)
```
I now want to add refresh API information to some error responses but not others so I'd have to add a `refresh=True` argument to `error_response()` but that's going to trigger PyLint's "too-many-arguments" warning.
So this commit replaces the `error_response()` helper method with a JSON-serializable dataclass called `ErrorResponseBody`. Views can return instances of this dataclass directly and Pyramid's JSON renderer will serialize them to JSON for the response body:
```python
return ErrorResponseBody(
message=..., …
```

Return a dataclass from API exception views

---

lms/services/canvas_api/_authenticated.py
lms/services/canvas_api/factory.py
tests/unit/lms/services/canvas_api/conftest.py
tests/unit/lms/services/canvas_api/factory_test.py

Add a new `"frontend_refresh"` feature flag and disable backend Canvas refresh requests when this feature flag is enabled.
Note that there are also backend *Blackboard* refresh requests that should be disabled by the same feature flag but aren't yet.
I haven't bothered to write unit tests for the feature flag-based behaviour because it's temporary. The feature flag and the whole backend refresh-and-retry logic will be deleted soon.
Feature flags are disabled by default which means that backend Canvas refresh requests will be _enabled_ by default and deploying this PR should have no effect. To test, simulate an expired access token by breaking the access tokens in your DB:
```
tox -qe dockercompose -- exec postgres psql -U postgres -c "update oauth2_token set access_token = 'foo';"
```
Now …

Feature flag Canvas refresh tokens

---

lms/routes.py
lms/services/canvas_api/client.py
lms/views/api/canvas/refresh.py
tests/unit/lms/services/canvas_api/client_test.py
tests/unit/lms/views/api/canvas/refresh_test.py

Add a new `POST /api/canvas/oauth/refresh` API for the frontend to call that causes the backend to refresh the current user's Canvas access token.
The refreshed access token is just stored in the DB (not sent back to the frontend).
You first need to get an access token in your DB to refresh, and you need to generate a bearer token to use in test requests.
1. Log in to Canvas as the __Canvas: Instructor (Testing Account)__ user (in 1Password) and launch an assignment so that you have an access token for this user in your DB
2. Get a bearer token for the user to use in test requests:
```python
$ make shell
>>> from lms.validation.authentication import BearerTokenSchema
>>> bearer_token_schema = BearerTokenSchema(request)
>>> user = …
```

Add refresh API

---

lms/services/exceptions.py
lms/views/api/exceptions.py
tests/unit/lms/services/exceptions_test.py
tests/unit/lms/views/api/exceptions_test.py

Add information to some of our API's error responses instructing the frontend to make a refresh request and try again.
This covers Canvas only, Blackboard is to come later.
Testing
=======
[localhost (make devdata) Canvas Files Assignment](https://hypothesis.instructure.com/courses/125/assignments/875) is a suitable assignment for testing this.
Enable the `frontend_refresh` feature flag
------------------------------------------
You need the [`frontend_refresh` feature flag](https://github.com/hypothesis/lms/pull/3695) on to test this PR:
```
export FEATURE_FLAG_FRONTEND_REFRESH=true
```
Note that the feature flag doesn't actually enable frontend refreshing code (the frontend code hasn't been written yet) it just _disables_ backend refreshing code.
Refreshable error from Canvas …

Add refresh API info to Canvas error responses

---

.github/dependabot.yml

The lms frontend no longer uses the ignored packages.

Remove obsolete Dependabot `ignore` configuration for npm packages

---

lms/services/blackboard_api/_basic.py
lms/services/blackboard_api/client.py
tests/unit/lms/services/blackboard_api/_basic_test.py
tests/unit/lms/services/blackboard_api/client_test.py

Expose `BlackboardAPIClient.refresh_access_token()` as a public service method so that the refresh API view can call it in a future PR.
Same as `BlackboardAPIClient.get_token()`, just forwards to `OAuthHTTPService` (injecting Blackboard-specific details like the token URL).

Add `BlackboardAPIClient.refresh_access_token()`

---

lms/services/oauth2_token.py

`OAuth2TokenService.get()` can get called more than once per request. For example the Canvas API client code will call it during view processing to get the access token to use in requests to Canvas. If a request to Canvas fails with a refreshable error then the `OAuth2TokenService.get()` will also get called during exception view processing because the exception view needs to know whether we have an access token for this user or not.
Remove this duplicate SQL query by adding per-request caching to `OAuth2TokenService.get()` using `lru_cache`.
This relies in the fact that `OAuth2TokenService` is registered with `pyramid_services` using `register_service_factory()` which means that `pyramid_services` constructs one instance of `OAuth2TokenService` *per request*.
Testing
-------
1. Enable …

Add caching to `OAuth2TokenService.get()`

---

lms/services/blackboard_api/_basic.py
lms/services/blackboard_api/factory.py
tests/unit/lms/services/blackboard_api/_basic_test.py
tests/unit/lms/services/blackboard_api/factory_test.py

Same as we [already did for Canvas](https://github.com/hypothesis/lms/pull/3695).
Testing:
1. Make sure you have a Blackboard access token in your DB: launch any Blackboard files or groups assignment and click through the authorization flow if you get it
2. Invalidate the access tokens in your DB:
tox -qe dockercompose -- exec postgres psql -U postgres -c "update oauth2_token set access_token = 'foo';"
3. Re-launch the assignmnent.
With the `frontend_refresh` feature flag enabled (`export FEATURE_FLAG_FRONTEND_REFRESH=true`) no refresh should be attempted and you should get an authorization dialog.
With the feature flag _disabled_ your access token should be automatically refreshed and the assignment should launch without asking you for authorization.

Feature flag Blackboard refresh tokens

---

lms/routes.py
lms/views/api/exceptions.py
lms/views/api/refresh.py
tests/unit/lms/views/api/exceptions_test.py
tests/unit/lms/views/api/refresh_test.py

`request.matched_route`-based approach to adding Blackboard support to the refresh API.
1. Log in to <https://hypothesis.instructure.com/> as the __Canvas: Instructor (Testing Account)__ user (in 1Password) and launch an assignment so that you have an access token for this user in your DB
2. Get a bearer token for the user to use in test requests. The `h_userid` in the code below is that of the __Canvas: Instructor (Testing Account)__ user:
```python
$ make shell
>>> from lms.validation.authentication import BearerTokenSchema
>>> bearer_token_schema = BearerTokenSchema(request)
>>> user = db.query(models.User).filter_by(h_userid="acct:3a022b6c146dfd9df4ea8662178eac@lms.hypothes.is").one()
>>> lti_user = factories.LTIUser(user_id=user.user_id, …
```

Add Blackboard support to the refresh API using `request.matched_route`

---

lms/services/blackboard_api/_basic.py
tests/unit/lms/services/blackboard_api/_basic_test.py

1. Enable the `frontend_refresh` feature flag:
export FEATURE_FLAG_FRONTEND_REFRESH=true
2. Make sure you have a Blackboard access token in your DB: launch any Blackboard files or groups assignment and click through the authorization flow if you get it
1. Invalidate the access tokens in your DB:
tox -qe dockercompose -- exec postgres psql -U postgres -c "update oauth2_token set access_token = 'foo';"
2. Launch any Blackboard files or groups assignment
3. No token refresh will happen because backend refreshing is disabled by the `frontend_refresh` feature flag and frontend refreshing hasn't been written yet. So you should see the authorization dialog
4. If you look at the bodies of the failed `via_url` and/or `sync` API requests you should see that refresh info is included:
```json …
```

Add refresh info to Blackboard API error responses

---

lms/resources/_js_config/__init__.py
lms/resources/_js_config/file_picker_config.py
lms/templates/admin/instance.html.jinja2
lms/views/admin.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/resources/_js_config/file_picker_config_test.py
tests/unit/lms/views/admin_test.py

- New "jstor"->"enabled" in application_instance.settings
- Expose the new setting in "filePicker". Default to `False`.
- Admin pages changes to expose the toogle.
- Start creating/editing an assignment, the response of `http://localhost:8001/content_item_selection` will contain a `<script type="application/json" class="js-config">`, the JSON there will contain:
```
jstor": {
"enabled": false
},
```
- Enable the JSTOR integration on http://localhost:8001/admin/instance using consumer_key `Hypothesisb3be0b33d0b5e4b1cf3aaf04e0e1819a` if testing in Canvas.
- Bring the content creating modal again, this time the value for jstor should be:
```
jstor": {
"enabled": true
},
```

JSTOR settings for application instance

---

lms/static/scripts/frontend_apps/components/ContentSelector.js
lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/JSTORPicker.js
lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
lms/static/scripts/frontend_apps/components/test/JSTORPicker-test.js
lms/static/scripts/frontend_apps/config.js
lms/static/scripts/frontend_apps/utils/jstor.js
lms/static/scripts/frontend_apps/utils/test/jstor-test.js

Depends on https://github.com/hypothesis/lms/pull/3761
Part of https://github.com/hypothesis/product-backlog/issues/1329
This is a PoC of a possible flow for configuring assignments to use JSTOR content.
* Check out and run this branch
* Enable JSTOR for your local LMS application_instance. To do this:
* Locate your app instance `consumer key`. For the `localhost` Canvas-with-sections install, it is `Hypothesisb3be0b33d0b5e4b1cf3aaf04e0e1819a`. You can see other `consumer key` values in the [`devdata` project's LMS data](https://github.com/hypothesis/devdata/blob/master/lms/devdata.json)
* Go to http://localhost:8001/admin , enter your consumer key and hit the checkbox for "JSTOR enabled"
* Configure an assignment...
In Canvas with JSTOR enabled, you should see something like this:
If you …

JSTOR assignment configuration workflow (front-end)

---

tests/unit/lms/validation/authentication/_oauth_test.py

The settings are set a bit below, that's the line that sets them. The removed one doesn't have any effect as far as I can tell:
https://github.com/hypothesis/lms/blob/753b9c0fbcf7fe1634992228f2fd6d0b141c4524/tests/unit/lms/validation/authentication/_oauth_test.py#L165

Remove useless settings set in test

---

lms/models/lti_user.py
lms/validation/authentication/_bearer_token.py
lms/validation/authentication/_launch_params.py
tests/factories/lti_user.py
tests/unit/lms/validation/authentication/_launch_params_test.py

The final goal is to only have the reference to application_instance_id instead of any LTI1/1.3 specific parameters to identify application_instances.
- On `master`, start with no users: 
`tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate \"user\", grouping_membership"`
- Launch this assignment: https://hypothesis.instructure.com/courses/125/assignments/875 
- There's should be now one `user` related to one application_instance
`tox -qe dockercompose -- exec postgres psql -U postgres -c "select * from \"user\""`
- Switch to this branch, re-launch the assignment. The same user still in the DB, related to the same AI.
- Check the value of the token in the `Authentication` header for the `http://localhost:8001/api/canvas/sync` request:
```
base64.urlsafe_b64decode(token+ …
```

Include `application_instance_id` in LTIUser

---

lms/services/oauth2_token.py
tests/unit/lms/services/oauth2_token_test.py

Fills the new column for new and "in fly" rows. Next step will be a migration to fill up the rest and mark the column as non-nullable.
-  Remove existing tokens
```tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate oauth2_token;"```
- On the branch `ai-fk-model`, launch https://hypothesis.instructure.com/courses/125/assignments/875
You'll get a new token with a null application_instance_id
```
tox -qe dockercompose -- exec postgres psql -U postgres -c "select application_instance_id from oauth2_token;"
application_instance_id 
-------------------------
(1 row)
```
- Switch to this branch and invalidate the token with:
```tox -qe dockercompose -- exec postgres psql -U postgres -c "update oauth2_token set access_token = 'nope';"```
- Launch the assignment again, …

Fill application_instance_id in OAuth2TokenService

---

lms/services/grading_info.py
tests/unit/lms/services/grading_info_test.py

Fills the new column for new and "in fly" rows. Next step will be a migration to fill up the rest and mark the column as non-nullable.
-  Remove existing grading info
```tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate lis_result_sourcedid;"```
- Launch the blackboard assignment `localhost (make devdata) HTML Assignment` as the student user `blackboardstudent2`
- https://aunltd-test.blackboard.com/webapps/blackboard/execute/blti/launchPlacement?blti_placement_id=_20_1&content_id=_36_1&course_id=_19_1
The new columns is filled in the new row:
`tox -qe dockercompose -- exec postgres psql -U postgres -c "select application_instance_id from  lis_result_sourcedid;"`
- Set application_instance_id to null
`tox -qe dockercompose -- exec postgres psql -U postgres -c "update …

Fill application_instance_id in GradingInfo

---

lms/services/group_info.py
lms/services/lti_h.py
tests/unit/lms/services/group_info_test.py
tests/unit/lms/services/lti_h_test.py

Fills the new column for new and "in fly" rows. Next step will be a migration to fill up the rest and mark the column as non-nullable.
-  Remove existing group_info
```tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate group_info;"```
```
tox -qe dockercompose -- exec postgres psql -U postgres -c "select application_instance_id from group_info;"
```
you'll get one row per section and one for the course. All with the `application_instance_id`
`tox -qe dockercompose -- exec postgres psql -U postgres -c "select application_instance_id from  lis_result_sourcedid;"`
- Set application_instance_id to null
```tox -qe dockercompose -- exec postgres psql -U postgres -c "update group_info set …
```

Fill application_instance_id in GroupInfo

---

lms/models/lti_user.py
lms/resources/_js_config/__init__.py
lms/security.py
lms/services/application_instance.py
lms/services/grading_info.py
lms/services/lti_h.py
lms/services/oauth1.py
lms/services/oauth2_token.py
lms/services/user.py
lms/validation/authentication/_bearer_token.py
lms/validation/authentication/_launch_params.py
lms/validation/authentication/_oauth.py
lms/views/basic_lti_launch.py
tests/factories/lti_user.py
tests/unit/conftest.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/security_test.py
tests/unit/lms/services/application_instance_service_test.py
tests/unit/lms/services/course_test.py
tests/unit/lms/services/grading_info_test.py
tests/unit/lms/services/lti_h_test.py
tests/unit/lms/services/oauth1_test.py
tests/unit/lms/services/oauth2_token_test.py
tests/unit/lms/services/user_test.py
tests/unit/lms/validation/authentication/_bearer_token_test.py
tests/unit/lms/validation/authentication/_launch_params_test.py
tests/unit/lms/views/application_instance_test.py
tests/unit/lms/views/basic_lti_launch_test.py

Needs https://github.com/hypothesis/lms/pull/3746 to be merged for at least 24h, the longest expiration time of the affected tokens.
-- edit --
#3746 Merged 10/03 at 10:15am
Same as https://github.com/hypothesis/lms/pull/3746. This PR assumes #3746  has been merged for at least 24 so all tokens in flight should be either expired or already include application_instance_id.
- A successful launch means that LTIUser has been correctly created from the LTI parameters.
- The authorization token now contains `application_instance_id` but not the consumer_key on the call to
`http://localhost:8001/api/canvas/courses/125/files`
```
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6Ikluc3RydWN0b3IiLCJkaXNwbGF5X25hbWUiOiJIeXBvdGhlc …
```

Remove `LTIUser.oauth_consumer_key` and make `LTIUser.application_instance_id` required

---

lms/migrations/versions/407ff423b9e3_missing_application_instance_fk.py

Adding the three columns in one migration to avoid extra bookkeeping and PR noise.
All columns added as null able in this first step.
The migration is auto generated from the model changes in: https://github.com/hypothesis/lms/pull/3749/files
Run the migration:
- ```hdev alembic upgrade head```
```
INFO  [alembic.runtime.migration] Running upgrade 7a4812876915 -> 407ff423b9e3, Add missing application_instances FK.
```
- Check the new table structure, new column and FK
```tox -qe dockercompose -- exec postgres psql -U postgres -c "\d group_info" ```
```tox -qe dockercompose -- exec postgres psql -U postgres -c "\d lis_result_sourcedid" ```
```tox -qe dockercompose …
```

Add application_instance_id to GroupInfo, Oauth2Token and GradingInfo

---

lms/security.py
tests/unit/lms/security_test.py

This adds `user` alongside `lti_user` to the request object for convince.
This PR doesn't yet use the new request property.
No functional changes here. Just launch any assignment as a sanity check. 
A diff like 
```diff
diff --git a/lms/views/basic_lti_launch.py b/lms/views/basic_lti_launch.py
index 7eefdde1..c88078b4 100644
--- a/lms/views/basic_lti_launch.py
+++ b/lms/views/basic_lti_launch.py
@@ -58,6 +58,8 @@ class BasicLTILaunchViews:
self.context.js_config.add_document_url(document_url)
+        print("USER" * 10, self.request.user)
+
return {}
def sync_lti_data_to_h(self):
```
can force access to the new property on launching for example: https://hypothesis.instructure.com/courses/125/assignments/875

Add `user` to the request

---

tests/factories/__init__.py
tests/factories/group_info.py
tests/unit/lms/services/group_info_test.py

- Use the global `application_instance` fixture
- Use a factory instead of creating models directly to be align to our testing style.
I few test here could use a deeper refactor but this is a start and gets in the way of another PR.

GroupInfoService test fixtures simplification

---

lms/migrations/versions/0a3bfcc14133_backfill_application_instance_id.py

For: https://github.com/hypothesis/lms/issues/3719
Model changes in: https://github.com/hypothesis/lms/pull/3754
As:
- https://github.com/hypothesis/lms/pull/3752
- https://github.com/hypothesis/lms/pull/3751
- https://github.com/hypothesis/lms/pull/3750
are already merged all new rows should have `application_instance_id`
A quick query on metabase to check that:
```
select 'group_info', application_instance_id from group_info where application_instance_id is not null
union
select 'token', application_instance_id from oauth2_token where application_instance_id is not null
union
select 'grading', application_instance_id from lis_result_sourcedid where application_instance_id is not null
```
Ideally we could test this on a LMS's DB dump to get an ballpark figure of how long is going to …

Migration to backfill application_instance_id

---

lms/resources/lti_launch.py
tests/unit/lms/resources/lti_launch_test.py

For: https://github.com/hypothesis/lms/issues/3699
`LegacyCourse` doesn't have timestamps or an auto-increment primary key so having an exact idea of how often a Course is created from a LegacyCourse (instead of both being created for a new course) is tricky to check with SQL.
Adding a temporary logging statement which we can check on papertrail. 
- Launch an assigment: https://hypothesis.instructure.com/courses/125/assignments/873. Nothing should be logged on the `make dev` console.
- Delete the courses (leaving only the LegacyCourse):
```
tox -qe dockercompose -- exec postgres psql -U postgres -c "delete from grouping where type ='course'"
```
- Re launch the assigment https://hypothesis.instructure.com/courses/125/assignments/873
You'll get a a logging line:
```
web (stderr)         | …
```

Log a warning every time a Course is created from a LegacyCourse

---

lms/models/application_instance.py
lms/models/grading_info.py
lms/models/group_info.py
lms/models/oauth2_token.py
tests/factories/grading_info.py
tests/unit/conftest.py
tests/unit/lms/models/grading_info_test.py
tests/unit/lms/models/group_info_test.py
tests/unit/lms/models/oauth2_token_test.py
tests/unit/lms/services/grading_info_test.py
tests/unit/lms/services/group_info_test.py

For: https://github.com/hypothesis/lms/issues/3719
Migration at https://github.com/hypothesis/lms/pull/3753 required to be merged before this.
The rest are tweaks to the tests that stop passing once application_instance_id is not nullable
The PRs that fill up application_instance_id on the services:
- https://github.com/hypothesis/lms/pull/3752
- https://github.com/hypothesis/lms/pull/3751
- https://github.com/hypothesis/lms/pull/3750
are already merged and the migration at https://github.com/hypothesis/lms/pull/3753 that backfills the ids in the new columns should be merged as well.
After that, as sanity check on each model/service check the following:
- Switch to this branch, apply migrations:
```hdev alembic upgrade head```
- `tox -qe dockercompose -- exec postgres psql -U postgres -c …

Model changes making application_instance_id not nullable

---

lms/migrations/versions/aa40f7e3f053_add_lti_registration.py

Auto-generated from the model changes at: https://github.com/hypothesis/lms/pull/3783
```
INFO  [alembic.runtime.migration] Running upgrade 0a3bfcc14133 -> aa40f7e3f053, Create lti_registration.
```

Migration creating LTIRegistration

---

lms/models/__init__.py
lms/models/lti_registration.py
lms/services/__init__.py
lms/services/lti_registration.py
tests/factories/__init__.py
tests/factories/lti_registration.py
tests/unit/lms/services/lti_registration_test.py

For: https://github.com/hypothesis/lms/issues/3689
This is missing the migration, I'll auto-generate it when we think we are going to merge it.
I think the model and service are small enough to be together in this PR
This is not used yet in any of the existing code paths but can be quickly tested on the shell:
- Start with a fresh DB
```docker stop lms_postgres_1; docker rm lms_postgres_1; make services db devdata``` 
- `make shell`
```
In [1]: db.add(models.LTIRegistration(issuer="https://canvas.instructure.com", client_id="93820000000000200", auth_login_url="https://canvas.instructure.com/api/lti/auth
...: orize_redirect", key_set_url="https://canvas.instructure.com/api/lti/security/jwks", token_url="ttps://canvas.instructure.com/api/lti/authorize"))
In [2]: tm.commit()
```
```
In [4]: …
```

LTIRegistration model and service

---

lms/migrations/versions/2119e1c621de_application_instance_registration.py

Migration for: https://github.com/hypothesis/lms/pull/3786
~~This PR depends also on the the migration at https://github.com/hypothesis/lms/pull/3789 (and the tests will fail until it's merged)~~ In master already.
```
INFO  [alembic.runtime.migration] Running upgrade aa40f7e3f053 -> 2119e1c621de, Add application_instance lti_registration relationship.
```

Migration for ApplicationInstance<->LTIRegistration relationship

---

lms/static/scripts/frontend_apps/utils/api.js
lms/static/scripts/frontend_apps/utils/test/api-test.js

Implement frontend-coordinated refresh [1] of expired access tokens for external
APIs (Canvas, Blackboard). When a frontend API call fails because due to expiry
of an access token for an external API, initiate a refresh from the frontend.
Initiating the request from the frontend has the advantage that a client can
prevent concurrent refreshes, at least from the same browser session within
the scope of a single page load.
[1] https://github.com/hypothesis/lms/issues/3667#issuecomment-1049063194
Part of https://github.com/hypothesis/lms/issues/3667. Will close that issue once the feature flag is turned on.
For testing, I followed [Sean's detailed instructions here](https://github.com/hypothesis/lms/issues/3667#issuecomment-1049063194).

Refresh expired access tokens from the frontend

---

lms/services/blackboard_api/factory.py
lms/services/canvas_api/factory.py
lms/views/api/exceptions.py
tests/unit/lms/views/api/exceptions_test.py

Now that it has been tested, enable this behavior by default.
Fixes https://github.com/hypothesis/lms/issues/3667

Remove the frontend_refresh feature flag

---

lms/migrations/versions/497b20c41fbb_nullable_consumer_keys.py

For: https://github.com/hypothesis/lms/issues/3719
- Allow nulls in consumer_key 
- Remove consumer_keys FKs
- Use the new `application_instance_id` for unique constraint instead of consumer_key.
auto-generated from: https://github.com/hypothesis/lms/pull/3768.
Nothing should have changed but let's exercise the services that directly handle this tables.
- Start with a fresh DB and apply the migration:
```shell
git checkout master
docker stop lms_postgres_1
docker rm lms_postgres_1
git checkout ai-fk-nullable-key
```
- `tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate group_info;"`
- Check the new rows
```
tox -qe dockercompose -- exec postgres psql …
```

Migration to allow null consumer_keys in tables with a new FK

---

lms/models/grading_info.py
lms/models/group_info.py
lms/models/oauth2_token.py
tests/unit/lms/models/grading_info_test.py
tests/unit/lms/models/oauth2_token_test.py

For: https://github.com/hypothesis/lms/issues/3719
Migration in https://github.com/hypothesis/lms/pull/3753
- Set the DB
```shell
git checkout master
docker stop lms_postgres_1
docker rm lms_postgres_1
git checkout ai-fk-nullable-key-model
```
Same as in https://github.com/hypothesis/lms/issues/3719, copy pasting it here:
- `tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate group_info;"`
- Check the new rows
```
tox -qe dockercompose -- exec postgres psql -U postgres -c "select consumer_key from group_info;"
consumer_key                
--------------------------------------------
Hypothesisb3be0b33d0b5e4b1cf3aaf04e0e1819a …
```

Model changes to make consumer_keys nullables in tables with new FK

---

lms/migrations/versions/497b20c41fbb_nullable_consumer_keys.py
lms/models/grading_info.py
lms/models/group_info.py
lms/models/oauth2_token.py
lms/resources/_js_config/__init__.py
lms/services/grading_info.py
tests/factories/grading_info.py
tests/unit/lms/models/grading_info_test.py
tests/unit/lms/models/oauth2_token_test.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/services/grading_info_test.py

For https://github.com/hypothesis/lms/issues/3719
Stop filling the old column now that it can hold nulls.
- `tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate lis_result_sourcedid;"`
- Launch the blackboard assignment `localhost (make devdata) HTML Assignment` as the student user `blackboardstudent2`
https://aunltd-test.blackboard.com/webapps/blackboard/execute/blti/launchPlacement?blti_placement_id=_20_1&content_id=_36_1&course_id=_19_1
- Check the new rows:
```
tox -qe dockercompose -- exec postgres psql -U postgres -c "select oauth_consumer_key, application_instance_id from lis_result_sourcedid;"
oauth_consumer_key | application_instance_id 
--------------------+-------------------------
|                      16
(1 row)
```
- Login now as `blackboardteacher` and …

Stop filling Grading.info consumer_key

---

lms/services/oauth2_token.py
tests/unit/conftest.py
tests/unit/lms/models/oauth2_token_test.py
tests/unit/lms/services/oauth2_token_test.py

For https://github.com/hypothesis/lms/issues/3719
Stop filling the old column now that it can hold nulls.
- `tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate oauth2_token;"`
- Check the rows again:
```
tox -qe dockercompose -- exec postgres psql -U postgres -c "select consumer_key, application_instance_id from oauth2_token;"
consumer_key | application_instance_id 
--------------+-------------------------
|                       8
(1 row)
```

Stop filling OAuth2Token consumer_key

---

tests/functional/conftest.py

We were only closing the session but the connection was kept open and every  tests was creating a new one, eventually reaching the connection limit.
This is not a problem in master as we don't seem to have enough tests to hit the connection limit.
We already do this for unit tests: https://github.com/hypothesis/lms/blob/c1e6bdfc06d9e98cf8a9490b853933a1d0b1851a/tests/unit/conftest.py#L147

Close connection on functional tests

---

lms/services/lti_registration.py
lms/views/lti/oidc.py
tests/unit/lms/services/lti_registration_test.py
tests/unit/lms/views/lti/oidc_test.py

The single tenant vs multi tenant distinction in the LTI spec is supported in our data model where:
- single tenant: 1 to 1 relationship between LTIRegistration.issuer <-> ApplicationInstance
- multi tenant: 1 to many relationship between them.
All LMS I've tried use the multi tenant setup (and the spec recommends it) but the certification tool uses the single tenant model and, as there's only one registration -> application instance per "issuer" it doesn't seen the `client_id` value on the OIDC request.
For that case we have to make `client_id` optional and take it form the DB.
- `make shell`
```python
db.add(
models.LTIRegistration(
issuer="https://canvas.instructure.com", 
client_id="93820000000000200", 
auth_login_url="https://canvas.instructure.com/api/lti/authorize_redirect", …
```

Support for LTI1.3 single tenant flow

---

lms/validation/_lti_launch_params.py
lms/validation/authentication/_lti.py
tests/functional/lti_certification/v13/core/test_bad_payloads.py
tests/unit/conftest.py
tests/unit/lms/validation/_lti_launch_params_test.py
tests/unit/lms/validation/authentication/_lti_test.py

Any missing parameters should make their way to the schema and fail the
validation step, not cause an exception.
These conditions don't occur in normal operation but when they happen, for example in the LTI certification, this PR makes the schema handle the missing data instead of raising some `KeyError` or `AttributeError`

Injection of LTI1.3 params doesn't fail when missing

---

lms/services/group_info.py
tests/unit/lms/models/group_info_test.py
tests/unit/lms/services/group_info_test.py

Before merging this changes need to be make on the sparky side to join on application_instance_id instead of consumer_key. 
The analytics side should be already be prepared as we recreate the consumer_key column there using the new FK.
---
For https://github.com/hypothesis/lms/issues/3719
Stop filling the old column now that it can hold nulls.
- `tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate oauth2_token;"`
- Check the rows:
```
tox -qe dockercompose -- exec postgres psql -U postgres -c "select consumer_key, application_instance_id from group_info;"
```
```
consumer_key | application_instance_id 
--------------+-------------------------
|                       8
|                       8
| …
```

Stop filling GroupInfo consumer_key

---

lms/models/lti_params.py
tests/functional/lti_certification/v13/conftest.py
tests/functional/lti_certification/v13/core/test_bad_payloads.py
tests/functional/lti_certification/v13/core/test_valid_student_launches.py
tests/functional/lti_certification/v13/core/test_valid_teacher_launches.py

An alternative for https://github.com/hypothesis/lms/pull/3819
Using the custom variables feature of the certification tool we can include custom variables/values (which in LTI1.3 are all included under the `/custom` claim) and map one of those to the tool_consumer_instance_guid.

Take GUID from custom parameter in LTI1.3 certification tool

---

lms/app.py
lms/models/lti_params.py
lms/security.py
lms/services/__init__.py
lms/services/jwt.py
tests/functional/lti_certification/v13/conftest.py
tests/functional/lti_certification/v13/core/test_bad_payloads.py
tests/functional/lti_certification/v13/core/test_valid_student_launches.py
tests/functional/lti_certification/v13/core/test_valid_teacher_launches.py
tests/unit/lms/security_test.py
tests/unit/lms/services/jwt_test.py
tests/unit/lms/views/lti/oidc_test.py
tests/unit/services.py

Nothing should have change but while in master we had a warning about using insecure JWTs now that can be removed as we are verifying them.
- `make shell`
```python
db.add(
models.LTIRegistration(
issuer="https://canvas.instructure.com", 
client_id="93820000000000200", 
auth_login_url="https://canvas.instructure.com/api/lti/authorize_redirect",                 
key_set_url="https://canvas.instructure.com/api/lti/security/jwks", 
token_url="ttps://canvas.instructure.com/api/lti/authorize"
)
)
tm.commit()
```
```python
ai = db.query(models.ApplicationInstance).order_by(models.ApplicationInstance.id.desc()).first()
ai.lti_registration_id = db.query(models.LTIRegistration).one().id
ai.deployment_id = "609:6ed5aff92b5257ab607ec9c629844ea8586fde68"
tm.commit()
```
You should be able to launch …

Extend JWTService to support LTI 1.3 token decoding

---

lms/migrations/versions/34f28d992b18_new_rsa_key_table.py

Model defined in #3862 and autogenerated with alembic.
- Start with a clean DB, from `master`:
`git checkout master; docker stop lms_postgres_1; docker rm lms_postgres_1; make services db devdata`
- In this branch, `rsa-key-migration`, run the migration:
```
dev installed: *** listing modules disabled by tox-pip-sync in pyproject.toml ***
dev run-test-pre: PYTHONHASHSEED='834933708'
INFO  [alembic.runtime.migration] Running upgrade 497b20c41fbb -> 34f28d992b18, New rsa_key table.
```

Migration for the new RSAKey model

---

lms/models/__init__.py
lms/models/rsa_key.py
lms/routes.py
lms/services/__init__.py
lms/services/rsa_key.py
lms/views/lti/jwk.py
requirements/bddtests.txt
requirements/dev.txt
requirements/functests.txt
requirements/lint.txt
requirements/requirements.in
requirements/requirements.txt
requirements/tests.txt
tests/factories/__init__.py
tests/factories/rsa_key.py
tests/unit/lms/models/rsa_key_test.py
tests/unit/lms/services/rsa_key_service_test.py
tests/unit/lms/views/lti/jwk_test.py
tests/unit/services.py

Requires:
* https://github.com/hypothesis/lms/pull/3876
- Run the migration to create the new table 
```hdev alembic upgrade head```
- Create a couple of keys in `make shell`
```
from lms.services import RSAKeyService
rsa_service = request.find_service(RSAKeyService)
key_1 = rsa_service.generate()
key_2 = rsa_service.generate()
tm.commit()
```
- Check the new endpoint exposing them: http://localhost:8001/lti/1.3/jwks
- Mark one of the as expired in a new `make shell`
```
key = session.query(models.RSAKey).first()
key.expired=True
tm.commit()
```
- Check http://localhost:8001/lti/1.3/jwks only exposes one key now.

RSA Key management and new JWK endpoint

---

lms/static/scripts/frontend_apps/services/client-rpc.js
lms/static/scripts/frontend_apps/services/test/client-rpc-test.js
lms/static/scripts/postmessage_json_rpc/server.js
lms/static/scripts/postmessage_json_rpc/test/server-test.js

This PR breaks off a piece of the https://github.com/hypothesis/lms/pull/3825 PoC. It registers a `reportActivity` method on the "RPC" server. Nothing is using this yet. Adding this independently allows related configuration (which will "turn this on" and cause the client to send requests to that method) to be landed independently. 
Part of https://github.com/hypothesis/lms/issues/3647

Add support for `reportActivity` method

---

lms/validation/_api.py
lms/views/api/lti.py
tests/unit/lms/views/api/lti_test.py

For #3647 
Added as an optional parameter first to make the deployment/rollout easier. As of now there's no code that that sets the date in the frontend so all submissions still should use the default 2001 date.
- Create a new assignment in canvas as a techer https://hypothesis.instructure.com/courses/125/assignments/new?submission_types=none&name=&due_at=null&points_possible=0&assignment_group_id=166
- Launch the assignment as `eng+canvasstudent@hypothes.is`
- Back to the teacher account, open the assignment in speed-grader, the date of the submission will be `Submitted:
Dec 31, 2000 at 5pm`

Expose `submitted_at` in canvas grading API 

---

conf/development.ini
lms/resources/_js_config/__init__.py
tests/unit/lms/resources/_js_config/__init___test.py

Following the conversation here:
https://hypothes-is.slack.com/archives/C4K6M7P5E/p1650458302131809?thread_ts=1650415818.372909&cid=C4K6M7P5E
Added the new config option only for canvas. Leaving it out for other LMSs
- Launch https://hypothesis.instructure.com/courses/125/assignments/2947, check the configuration at `http://localhost:8001/lti_launches?url=https://example.com`.
- Ctrl+F for `hypothesisClient` in the response. Nothing has changed, the config doesn't include the new property:
```hypothesisClient": {"services"...}```
- Enable `submit_on_annotation` on  http://localhost:8001/flags
- Refresh the launch and check the response again for `http://localhost:8001/lti_launches?url=https://example.com`, Ctrl+F for `hypothesisClient`. 
The new `{"reportActivity": {"events": ["create", …

Enable `reportActivity` setting on the client config on canvas instances

---

lms/resources/_js_config/__init__.py
lms/views/basic_lti_launch.py
tests/unit/conftest.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/validation/authentication/_lti_test.py
tests/unit/lms/views/basic_lti_launch_test.py

In preparation for LTI1.3
In LTI1.1 `lti_params` <-> `params`:
https://github.com/hypothesis/lms/blob/bdc06426d1a65ff198534bd9c55ec11505198fc2/lms/resources/lti_launch.py#L251
Nothing should have changed for LTI1.1 launches. I'm launching a few assignments and doing a sanity check.
https://aunltd-test.blackboard.com/webapps/blackboard/execute/blti/launchPlacement?blti_placement_id=_20_1&content_id=_36_1&course_id=_19_1

Pick parameters from lti_params instead of the raw request.params

---

tests/unit/lms/services/lti_grading/_v11_test.py

This is a grab bag of various improvements. Each has been put in it's own commit for easy reference.
Highlights:
* Using sentinels
* Making test which apply to both methods use both methods
* Collapsing some tests together
* More declarative comparisons with dicts

Refactor grading service V11 tests

---

lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.js
lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
lms/static/scripts/frontend_apps/config.js
lms/static/scripts/frontend_apps/services/client-rpc.js

This PR adds front-end support to hold off on submitting an empty grading submission in Canvas until after first annotation activity if configured to do so (i.e. in this case, if the feature flag is enabled), and it will send a "meaningful date" for the submission in these cases.
Otherwise, behavior should remain unchanged: submit empty grading submission on launch, with no associated date (backend will use "dummy" date).
*NB: It's not expected that a reviewer will run through this _entire_ set of tests if it does not feel useful.*
Make sure to pull latest `master` for the `client` and run this branch locally.
I'd suggest creating new (grading-enabled) assignments for both branches of testing here, as the situation can be muddied/hard to test with an existing assignment that has been …

Conditionally submit empty grading submission after activity, if configured as such

---

lms/models/lti_params.py
lms/services/__init__.py
lms/services/grading_info.py
lms/services/jwt.py
lms/services/lti_grading/_v13.py
lms/services/lti_grading/factory.py
lms/services/ltia_http.py
lms/services/rsa_key.py
tests/functional/lti_certification/v13/grading/test_assignment_and_grading.py
tests/unit/conftest.py
tests/unit/lms/services/jwt_test.py
tests/unit/lms/services/lti_grading/_v13_test.py
tests/unit/lms/services/lti_grading/factory_test.py
tests/unit/lms/services/ltia_http_test.py
tests/unit/lms/services/rsa_key_service_test.py
tests/unit/services.py

- Start the server with more than one worker so the LMS can make a request to the `/lti/1.3/jwks` endpoint while the server handles another request.
```diff
diff --git a/conf/supervisord-dev.conf b/conf/supervisord-dev.conf
index 63063eb8..aec0ab0d 100644
--- a/conf/supervisord-dev.conf
+++ b/conf/supervisord-dev.conf
@@ -3,7 +3,7 @@ nodaemon = true
silent = true
[program:web]
-command=gunicorn --workers 1 --paste conf/development.ini
+command=gunicorn --workers 2 --paste conf/development.ini
stdout_events_enabled=true
stderr_events_enabled=true
stopsignal = KILL
```
- `make devdata` 
- Start a tunnel to `blackboard-jon`
`loophole http 8001 --hostname blackboard-jon`
- Launch https://aunltd-test.blackboard.com/webapps/blackboard/content/contentWrapper.jsp?content_id=_664_1&displayName=Test …

LTI Advantage service and LTI1.3 grading

---

lms/migrations/versions/911d1f7da759_backfill_course_groupings.py

For #3699 
`course` doesn't contain all the information we have in Grouping, missing most importantly the required:
- `lms_id`  (the ID of the course within the LMS)
- `custom_canvas_course_id` (required to build the `extra` dict)
- Start with a fresh DB
```
git checkout 05a4712aad54ab0f99e15b6b5e21a5ad64de7617; docker stop lms_postgres_1; docker rm lms_postgres_1; make services db devdata; hdev alembic upgrade head
```
This needs to be done in a commit before:
```
commit 0908431ed5f3f01d00d092fa5ab8cae45a5272db (HEAD)
Author: Marcos Prieto <marcospri@gmail.com>
Date:   Mon Mar 14 10:45:41 2022 +0100
Stop filling GroupInfo consumer_key
```
**Unfortunately that also implies a previous commit on dev data `773fd7e647d80852049472b2244f25644c8397d2`**
and a diff in LMS
```diff
diff --git …
```

Backfill course in groupings from LegacyCourse

---

lms/services/blackboard_api/factory.py
lms/services/canvas_api/factory.py
tests/unit/lms/services/blackboard_api/factory_test.py
tests/unit/lms/services/canvas_api/factory_test.py

Slack thread: https://hypothes-is.slack.com/archives/C1MA4E9B9/p1652200138759249
I've also got a draft PR to actually remove the will-no-longer-be-used backend refresh code: https://github.com/hypothesis/lms/pull/3943, but I guess we should deploy this PR to disable backend refresh/enable frontend refresh and let it run for a while first.
When we [removed the `frontend_refresh` feature flag](https://github.com/hypothesis/lms/pull/3806) we removed it and _disabled_ the feature rather than enabling it: the new frontend-based OAuth 2 refresh code is currently *not* being used on master or on production. The old backend-based refresh is in use instead. To verify this:
Canvas
------
On master:
1. Launch [localhost (make devdata) Canvas Files …

Enable the new frontend refresh feature

---

lms/static/scripts/postmessage_json_rpc/client.js
lms/static/scripts/postmessage_json_rpc/index.js
lms/static/scripts/postmessage_json_rpc/server.js
lms/static/scripts/postmessage_json_rpc/test/client-test.js
lms/static/scripts/postmessage_json_rpc/test/server-test.js

This PR adds support for [JSON-RPC 2.0](https://www.jsonrpc.org/specification) notification requests — that is, requests that are notifications and do not need a response. This will allow the `client` to send annotation-activity notifications without us having to fuss with sending (empty) responses. I've tried to bolt this on with minimal fuss.
According to the spec, the non-presence of an `id` property in a request object defines it as a "notification" request and no response should be sent.
I've also added support here for the ability to _send_ such requests (`notify` vs. `call`), though this is mostly to have symmetry with what I intend to add to the client—it is currently unused.
Part of https://github.com/hypothesis/client/issues/4484

Add support for JSON-RPC 2.0 Notification requests

---

lms/resources/_js_config/__init__.py
lms/views/basic_lti_launch.py
lms/views/content_item_selection.py
tests/functional/lti_certification/v13/core/test_valid_teacher_launches.py
tests/functional/views/basic_lti_launch_test.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/views/basic_lti_launch_test.py
tests/unit/lms/views/content_item_selection_test.py

Naming was confusing as it was mixing to different concepts:
- Our app displaying the filepicker
- Enabling or not the use of LTI's content_item_selection / deeplinking
API to communicate the selected document to the LMS.

Rename `content_item_selection` mode to `file_picker`

---

docs/configuration.md
lms/config/__init__.py
lms/services/jstor.py
tests/unit/lms/services/jstor_test.py
tox.ini

For: 
* https://github.com/hypothesis/private-issues/issues/110
Requires:
* https://github.com/hypothesis/h-vialib/pull/35
* An update in Via to add the above
This completely removes the need to have any JSTOR specific code in Via.
* Get the devdata as of (https://github.com/hypothesis/devdata/pull/53)
* Start all the services
* Open the dev tools with caching disabled
* Visit https://hypothesis.instructure.com/courses/125/assignments/2968
* You should see a request go to Via with a normal URL in it
* You should see the JSTOR content banner in Via

Handle all JSTOR work on the LMS side

---

lms/validation/__init__.py
lms/validation/_lti_launch_params.py
lms/views/basic_lti_launch.py
lms/views/lti/deep_linking.py
lms/views/lti/oidc.py
lms/views/predicates/_lti_launch.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/validation/_lti_launch_params_test.py
tests/unit/lms/views/lti/deep_linking_test.py

In preparation for LTI1.3 / Deeplinking 2.0 using the same namespace.
We use deeplinking and content-item-selection as equivalent terms and deeplinking seems to be the preferred name in the spec in LTI1.0 and the only one in LTI1.3
https://www.imsglobal.org/specs/lticiv1p0
https://canvas.instructure.com/doc/api/file.content_item.html
Just as a sanity check try to configure/edit an assignment in Canvas.

Rename `content_item_selection` module to `deep_linking`

---

lms/routes.py
lms/templates/admin/instance.html.jinja2
lms/templates/admin/instances.html.jinja2
lms/templates/admin/instances.results.html.jinja2
lms/views/admin.py
tests/unit/lms/views/admin_test.py

- Added the new fields identifying AI to the detail page
- Add a new form to search by a few fields.
Main motivation here is to make the admin pages useful in development while wokring on LTI1.3. This PR doesn't try to tackle https://github.com/hypothesis/lms/issues/3690 (ie how to get new registration/application instances) into the DB.
In LTI1.3 install are identified by three fields: issuer, client_id and deployment ID. Typing all of them would be cumbersome so opted for a search form instead.
Added GUID to the search fields as it might be useful. 
- Go to http://localhost:8001/admin/instances/
- Test find by consumer key still works
- Test editing an application instance works as expected.
- Test the search funtiallity, some test data to make some queries
```
Consumer key: …
```

Search for application instances in the admin pages

---

lms/models/lti_params.py
lms/resources/_js_config/__init__.py
lms/routes.py
lms/services/ltia_http.py
lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
lms/static/scripts/frontend_apps/config.js
lms/validation/_lti_launch_params.py
lms/views/lti/deep_linking.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/validation/_lti_launch_params_test.py
tests/unit/lms/views/lti/deep_linking_test.py

For: #3911 
First half of https://github.com/hypothesis/lms/pull/3908
Here we only make changes for LTI1.3 launches:
- We set a new "deeplinkingAPI" field in the config the backend sends to the frontend.
- When that's present the frontend calls the new API with the content selected by the user and the backend answers with the form fields required for the deeplinking form submission. For LT1.3 that's only a `JWT` field with all the encoded fields in it.
- The frontend submits the form to canvas as usual.
Log into canvas as a teacher
- `make devdata` 
- Edit https://hypothesis.instructure.com/courses/319/assignments/2781  using the `Hypothesis LTI1.3 (localhost)` install
There will be now a call to `http://localhost:8001/lti/1.3/deeplinking/formfields` showing up on the network tab of your …

Deep Linking in LTI1.3 launches

---

lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.js
lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
lms/static/scripts/frontend_apps/services/client-rpc.js
lms/static/scripts/frontend_apps/services/test/client-rpc-test.js

Update grading submission such that an automated empty grading submission is only made if annotation activity pertains to a shared annotation.
Running this branch, try these things or a combination of:
1. Ensure that the `submit_on_annotation` feature flag is enabled on http://localhost:8001/flags
2. Launch a grade-able assignment as a student
3. Add a new _highlight_ or private (only me) annotation.
4. Log out
5. Log in as an instructor and launch the same assignment; go into Speed Grader
6. You should not see a recent submission from the student who created the highlight
7. Log out; log in as student
8. Launch assignment. Create or edit a shared annotation.
9. Log out; log in as instructor; launch assignment; go into Speed Grader
10. You should see a recent submission from the student …

Canvas: Only submit for grading if annotation is shared

---

lms/resources/_js_config/__init__.py
tests/unit/lms/resources/_js_config/__init___test.py

Enable anonymous (non LTI-authenticated) launches of VitalSource
assignments by default, and remove the feature flag that was needed to
enable it before.
The code that supports LTI-authenticated launches still exists and will
be removed in a follow-up.
Fixes https://github.com/hypothesis/private-issues/issues/102

Remove vitalsource_anon_launch feature flag

---

lms/routes.py
lms/views/canvas/config.py
tests/unit/lms/views/canvas/config_test.py

Add the same configuration endpoint concept for LTI1.3. 
In LTI1.3 the endpoint must return json instead of xml but the information is basically the same.
Head to: http://localhost:8001/canvas/1.3/config

Add LTI1.3 config endpoint for canvas

---

lms/models/lti_params.py
lms/resources/_js_config/__init__.py
lms/resources/_js_config/file_picker_config.py
lms/validation/_lti_launch_params.py
lms/views/basic_lti_launch.py
lms/views/lti/deep_linking.py
tests/functional/lti_certification/v13/conftest.py
tests/unit/lms/models/lti_params_test.py
tests/unit/lms/resources/_js_config/file_picker_config_test.py
tests/unit/lms/validation/_lti_launch_params_test.py
tests/unit/lms/views/basic_lti_launch_test.py
tests/unit/lms/views/lti/deep_linking_test.py

Main thing is using `lti_params` instead of params. I rather do this feature by feature instead of a good old search and replace as is easier to test individually. 
When we are "done" I think it will be easier to review the ones that still use `request.params` one by one.
There was also a couple of things getting on the way of these features working on LTI1.3:
- A bug on LTIParams. Fixed and added a test for that.
- A difference between versions in one parameter canvas sends. `str` vs `int` depending on the version.
(you can test a broken version of this in `master` first)
- `make devdata`
- Edit an LTI1.3 assignment https://hypothesis.instructure.com/courses/319/assignments/2781/edit?return_to=https%3A%2F%2Fhypothesis.instructure.com%2Fcourses%2F319%2Fassignments%2F2781
- Select Canvas …

Fixes for canvas files and canvas groups in LTI1.3

---

lms/routes.py
lms/services/application_instance.py
lms/templates/admin/instance.html.jinja2
lms/templates/admin/instances.html.jinja2
lms/templates/admin/instances.results.html.jinja2
lms/views/admin.py
tests/unit/lms/services/application_instance_service_test.py
tests/unit/lms/views/admin_test.py

https://user-images.githubusercontent.com/1433832/168567305-adc225e5-a9d1-46d6-9f5a-6085f4b23776.mp4
Main motivation here is to make the admin pages useful in development while working on LTI1.3. This PR doesn't try to tackle https://github.com/hypothesis/lms/issues/3690 (ie how to get new registration/application instances) into the DB.
In LTI1.3 install are identified by three fields: issuer, client_id and deployment ID. Typing all of them would be cumbersome so opted for a search form instead and merged the existing `consumer_key` query into that.
Added GUID to the search fields as it might be useful. 
- Go to http://localhost:8001/admin/instances/
- Test the search functionality, some test data to make some queries
- Test editing an application instance works as expected.
```
Consumer …
```

Allow to search for application instances in the admin pages

---

lms/resources/_js_config/__init__.py
lms/resources/_js_config/file_picker_config.py
tests/unit/lms/resources/_js_config/file_picker_config_test.py

Just some `params` -> `lti_params` replacements.
- `loophole http 8001 --hostname blackboard-jon` (This is needed until a better workflow comes of #3916)
- https://github.com/hypothesis/devdata/pull/56 review and self-server merge
- `make devdata`
- Login into blackboard as `blackboardteacher` https://aunltd-test.blackboard.com/?new_loc=%2Fultra%2Fstream
- Create a new assignment (Build Content -> Hypothesis LTI1.3) use both canvas files and groups.
- Launch the assignment.

Prefer lti_params over raw params for blackboard APIs

---

lms/models/lti_params.py
lms/resources/_js_config/__init__.py
lms/services/lti_grading/_v11.py
lms/services/lti_grading/_v13.py
lms/views/api/lti.py
tests/functional/lti_certification/v13/conftest.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/services/lti_grading/_v11_test.py
tests/unit/lms/services/lti_grading/_v13_test.py
tests/unit/lms/views/api/lti_test.py

Canvas grading extensions for LTI1.3. 
Very similar to the LTI1.1 just on the JSON body instead of the XML one.
Instructions mostly copied from https://github.com/hypothesis/lms/pull/3956.
Note that `submit_on_annotation` is not really necessary for this but it makes the testing much simpler IMO.
---
- Ensure that the `submit_on_annotation` feature flag is enabled on http://localhost:8001/flags
or start the server with `export FEATURE_FLAG_SUBMIT_ON_ANNOTATION=true`
- Launch a grade-able assignment as a student
LTI1.1 https://hypothesis.instructure.com/courses/125/assignments/2956
LTI1.3 https://hypothesis.instructure.com/courses/319/assignments/2988
- Add an annotation
- Log in as an instructor (incognito window / different browser) and launch the same assignment; go into Speed Grader
- …

CanvasPreRecordHook support for LTI1.3

---

lms/views/predicates/__init__.py
lms/views/predicates/_lti_launch.py
tests/unit/lms/views/predicates/__init___test.py
tests/unit/lms/views/predicates/_lti_launch_test.py

For https://github.com/hypothesis/lms/issues/3990
This predicate was no used in any views. Removed it.

Remove unused legacy_speedgrader predicate

---

lms/views/basic_lti_launch.py
tests/unit/lms/views/basic_lti_launch_test.py

For https://github.com/hypothesis/lms/issues/3990
This view was part of an effort to store all canvas assignments on the
DB. Due to some bugs/particularities of Canvas that effort failed but the
code dealing with it was never deleted.
The view is not used as `url_configured=False` (the launch URL contains a `url` parameter) and `db_configured` (there's a record of the assignment on our DB) are never true at the same-time; We continue to include the `url` parameter in canvas and we don't store the assignments (other than Canvas files ones, which are excluded by `canvas_file=False`)

Removed unused view to handle canvas assignment launches

---

lms/resources/_js_config/__init__.py
lms/resources/lti_launch.py
lms/views/basic_lti_launch.py
lms/views/lti/deep_linking.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/views/basic_lti_launch_test.py
tests/unit/lms/views/lti/deep_linking_test.py

For: 
This was just calling get or create course. This has also pointed out that we were clearly calling it more than once in lots of places.

Remove `h_group` property from the context

---

lms/services/group_info.py
lms/services/lti_h.py
tests/unit/lms/services/group_info_test.py
tests/unit/lms/services/lti_h_test.py

For:
Some time ago we move from `HGroup` domain model objects to `Grouping` DB model objects, but never updated the code. 
This makes it clear that we are using grouping objects and also makes use of the embedded link to application instance instead of requiring it be passed in.

Make the `GroupInfoService` grouping centric

---

lms/services/lti_h.py
tests/unit/lms/services/lti_h_test.py

For:
Requires:
* https://github.com/hypothesis/lms/pull/4014
Some time ago we move from `HGroup` domain model objects to `Grouping` DB model objects, but never updated the code. This is mostly a cosmetic difference, as the code is basically the same.

Make LTI-H grouping centric.

---

lms/resources/_js_config/__init__.py
lms/resources/lti_launch.py
lms/views/lti/basic_launch.py
lms/views/lti/deep_linking.py
tests/functional/conftest.py
tests/functional/lti_certification/v13/core/test_valid_teacher_launches.py
tests/functional/views/basic_lti_launch_test.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/views/lti/basic_launch_test.py
tests/unit/lms/views/lti/deep_linking_test.py

For: 
This PR involves two changes:
* Calling the sync data methods from `unconfigured_launch()`
* Rename the method and make it a property
The change to calling data sync means we will be capturing launches when teachers are configuring records, which they would not have been before.

Rename `get_or_create_course()` to `course` as a property

---

lms/migrations/versions/bdfe1c72813f_rename_module_item_configurations_to_assignment.py

For: 
I'm sure there's a better way, but this certainly forces it to happen:
```shell
git checkout master
make services
make db
git checkout rename-assignments-table
```
* In `make sql` - `\d+ module_item_configurations` you should see:
```sql
Column            |       Type        | Collation | Nullable |                        Default                         | Storage  | Stats target | Description 
-----------------------------+-------------------+-----------+----------+--------------------------------------------------------+----------+--------------+-------------
id                          | integer           |           | not null | nextval('module_item_configurations_id_seq'::regclass) | plain    | …
```

Migration for renaming `module_item_configurations` to `assignment`

---

tests/unit/lms/services/assignment_test.py

For:
Use a more involved fixturing setup to simplify the tests. This also removes a strange backwardness in the tests where two constants "MATCHING_*" seemed to be used in many places where we didn't want a match.
It's a bit more explicit now.
You probably want to side by side the two versions yourself. The diff isn't helpful as I completely rewrote it.

Refactor the `AssignmentService` tests to use fixtures

---

lms/static/scripts/frontend_apps/services/vitalsource.js
lms/static/scripts/frontend_apps/utils/api.js
lms/static/scripts/frontend_apps/utils/test/api-test.js

This PR adds some general functionality for LMS frontend -> backend API calls which will be used by the JSTOR picker.
1. A `signal` argument to `apiCall`, which can be used to pass an [AbortSignal](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal) to fetch, to enable later cancelation of the request
2. A `urlPath` helper for safely generating API URL Paths that include parameters

Support API call cancelation via AbortSignal

---

tests/unit/lms/views/lti/basic_launch_test.py

For:
This PR rewrites the unit tests for the Basic LTI launch views to:
* Reduce the length from 510 lines to 342
* Remove the caller pattern
* Test commonly used internal methods once, and then use fixtures to assert that other things call the right things
* Increase test coverage in a number of places
* Make the test layout closely follow the file layout, to make it obvious to spot coverage issues
The end result is it should be much easier to make changes to the class, and know where to put tests for them, and have confidence you've actually covered all the cases.

Refactor LTI launch tests to remove caller pattern and make them easier to maintain

---

lms/static/scripts/frontend_apps/utils/fetch.js
lms/static/scripts/frontend_apps/utils/test/fetch-test.js

Whenever API data is fetched for display in a component, there are a common
set of states that we need to keep track of and side effects that need
to be performed:
- The render function needs to know whether a fetch is happening, or
succeeded, or failed
- If the inputs to the fetch change or the component is unmounted, the
previous fetch needs to be canceled
Add a hook to encapsulate this. The API is intentionally a very minimal subset of SWR's [1]. That has a bunch of additional
functionality and associated complexities that we don't yet need, but it would make a transition easy in future if we wanted to.
See the changes to JSTORPicker.js in https://github.com/hypothesis/lms/pull/4026 to see how this gets used in practice.
[1] https://swr.vercel.app

Add useFetch hook to make managing API fetches in components easier

---

lms/resources/lti_launch.py
lms/services/assignment.py
lms/views/api/blackboard/sync.py
lms/views/api/canvas/files.py
lms/views/lti/basic_launch.py
lms/views/predicates/_lti_launch.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/services/assignment_test.py
tests/unit/lms/views/api/blackboard/sync_test.py
tests/unit/lms/views/api/canvas/files_test.py
tests/unit/lms/views/lti/basic_launch_test.py
tests/unit/lms/views/predicates/_lti_launch_test.py

For:
This is to make it easier to find where they are used and to be sure when refactoring that we've got everything.
It's a bit ugly, but overall more maintainable I think. Which is a tradeoff probably worth making.

Rename the assignment service methods to have `assignment` in them

---

tests/functional/lti_certification/v13/assertions.py
tests/functional/lti_certification/v13/conftest.py
tests/functional/lti_certification/v13/core/test_valid_student_launches.py
tests/functional/lti_certification/v13/core/test_valid_teacher_launches.py

For:
* https://github.com/hypothesis/lms/issues/3995
Currently we assume the error page has JS config, but it doesn't need any,  so the tests being this way prevent us from changing that.
We still want to use the error page as an indicator of whether you are a student or a teacher, but this can be accomplished by some text matching.

Refactor the LTI 1.3 func tests to not rely on JS config on the error page

---

lms/models/lti_params.py
lms/resources/_js_config/__init__.py
lms/validation/_lti_launch_params.py
tests/unit/lms/models/lti_params_test.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/validation/_lti_launch_params_test.py

- Refactor the `_to_lti_v11`. Stop using `for...else` and use a more explicit `KeyError` except block.
- Move handling of int -> str conversion for custom canvas parameters to LTIParams .

LTIParams changes

---

lms/views/lti/basic_launch.py
tests/unit/lms/views/lti/basic_launch_test.py

There were quite a few places where we didn't use the 1.1 -> 1.3 compat
layer. I think this might mean these were not working correctly for those
situations?

Use `lti_params` for 1.3 compatibility in the LTI launches

---

lms/models/assignment.py

For:
Remove the code first, migration will follow on https://github.com/hypothesis/lms/pull/4037.
The order is reversed from other DB changes as here we are deleting a column, we want to the code to stop using it before we delete it for real in the DB.
Launch a few canvas assignments as a sanity check:
- https://hypothesis.instructure.com/courses/125/assignments/873 
- https://hypothesis.instructure.com/courses/125/assignments/875
- Also SpeedGrading https://hypothesis.instructure.com/courses/125/gradebook/speed_grader?assignment_id=873&student_id=35

Remove the `ext_lti_assignment_id` column from the model

---

lms/models/application_instance.py
lms/views/lti/basic_launch.py
tests/unit/lms/models/application_instance_test.py
tests/unit/lms/views/lti/basic_launch_test.py

For:
This is mostly "for show" to allow us to see what's happening. This allows a clean division between things we need for the view  to work (checking the GUID) and data storage for our persisted model.
The code here is the same / a little worse, as it calls the check GUID twice effectively. But it makes the intent clearer.
This also avoids a potential problem where something crucial is happening as a side effect of updating the data, but it's not clear. So you could easily think you are doing something safe by moving the update, where you are actually creating a huge problem.

Separate checking for the application instance GUID and updating in the launch view

---

lms/views/lti/basic_launch.py
tests/unit/lms/views/lti/basic_launch_test.py

For:
* https://github.com/hypothesis/lms/issues/3995
Previously every launch either did, or didn't update the assignment:
* `configure_assignment` - Yes (unchanged)
* `blackboard_copied_launch` - Yes (unchanged)
* `brightspace_copied_launch` - Yes (unchanged)
* `canvas_file_launch` - Yes (unchanged)
* `db_configured_launch` - No (now **Yes**)
* `url_configured_launch` - No (now **Yes**)
* `legacy_vitalsource_launch` - No (now **Yes**)
* `unconfigured_launch` - No (unchanged)
* `unconfigured_launch_not_authorized` - No (unchanged)
In addition to doing this for all configured launches:
* We also only do it in one place
* `_do_launch` has been renamed `_show_document` to reflect the fact it's only document based launches, not all launches

Upsert data about assignments on every launch

---

Jenkinsfile
README.markdown

1. Replaced the onlyOnMaster function with onlyOnMain in the Jenkinsfile
2. Replaced references to master with main in README.markdown
3. ~~Replaced section targeting MASTER branch with MAIN in tests/.pylintrc~~
The update to `tests/.pylintrc` was removed. Move info can be found here: https://hypothes-is.slack.com/archives/C1MA4E9B9/p1654675409844899

Renamed default branch to main

---

lms/resources/_js_config/__init__.py
lms/views/lti/basic_launch.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/views/lti/basic_launch_test.py

For:
* https://github.com/hypothesis/lms/issues/3991
We had a number of methods in the JSConfig class which detected whether they should perform an action and then performed it. These were:
* `maybe_enable_grading()`
* `maybe_set_focused_user()`
* `add_canvas_speedgrader_settings()`
This is bad for a number of reasons:
* When you call them you don't know if anything happened or not or why
* It's not clear from the caller whether you should be calling them (similar, but different)
* JSConfig is bloated with lots of decisions, rather than concentrating on doing
This resulted in a few things:
* The basic launch view was ignorant of whether something actually is graded
* Worse, the basic launch view had a spurious notion of `grading_enabled` which was basically irrelevant / wrong
* A lack of …

Move decision part of `maybe_` JS config to the LTI view

---

lms/static/scripts/frontend_apps/components/JSTORPicker.js
lms/static/scripts/frontend_apps/components/test/JSTORPicker-test.js
lms/static/scripts/frontend_apps/utils/jstor.js
lms/static/scripts/frontend_apps/utils/test/jstor-test.js

**Depends on ~~https://github.com/hypothesis/lms/pull/4025~~, ~~https://github.com/hypothesis/lms/pull/4027~~, https://github.com/hypothesis/lms/pull/4028, ~~https://github.com/hypothesis/lms/pull/4039~~**
This PR adds article metadata and thumbnails to the JSTOR article picker form:
The thumbnail we currently display is of the article itself. There is ongoing discussion [here](https://hypothes-is.slack.com/archives/C07NXBDNW/p1654182208320269) of whether we want to use something else (eg. the issue/book cover) instead, as that may look better.
The current implementation does not check whether the user has access to the content, the plan is to add that in future we'd show some appropriate indication.
The content of this dialog overlaps somewhat with the form used for picking VitalSource …

Add article metadata and thumbnail to JSTOR picker

---

lms/migrations/versions/83ec5ef85d44_add_more_metadata_to_the_assignment.py

For:
* https://github.com/hypothesis/lms/issues/3991
Migration to add the columns used in:
* https://github.com/hypothesis/lms/pull/4056
* `git checkout main`
* `make services args=down; make services db devdata`
* `git checkout launches-stor-mor-migration`
* `make db`
```shell
tox -qe dockercompose -- exec postgres psql -U postgres -c "select * from assignment";
```
* You should see rows with sensible defaults
* `hdev alembic downgrade -1`
```shell
tox -qe dockercompose -- exec postgres psql -U postgres -c "select * from assignment";
```
* The extra columns should have gone

Add a migration for the new assignment columns

---

lms/models/assignment.py
lms/models/lti_params.py
lms/services/assignment.py
lms/views/lti/basic_launch.py
tests/unit/conftest.py
tests/unit/lms/models/lti_params_test.py
tests/unit/lms/services/assignment_test.py
tests/unit/lms/views/lti/basic_launch_test.py

For:
* https://github.com/hypothesis/lms/issues/3991
Cannot be merged before:
* https://github.com/hypothesis/lms/pull/4059
This adds storage of:
* Created date
* Updated date
* Is gradable
* Title
* Description
The two fields we are reading from LTI params are title and description. It's hard to link to these in the spec for 1.1 ('cos the doc is broken):
* https://www.imsglobal.org/specs/ltiv1p1p1/implementation-guide#toc-3 - 1.1
> resource_link_title=My Weekly Wiki
A plain text[[1]](https://www.imsglobal.org/LTI/v1p1p1/ltiIMGv1p1p1.html#_ftn1) title for the resource. This is the clickable text that appears in the link. This parameter is recommended.
>
> resource_link_description=…
A plain text description of the link’s destination, suitable for display alongside the link. Typically no …

Store more metadata with assignments

---

lms/views/lti/basic_launch.py
tests/unit/lms/views/lti/basic_launch_test.py

In LTI1.1 we used the presence of `lis_result_sourcedid` as proxy for
being a student but that's not true in LTI1.3.
We'll check for the role in both LTI versions and also still require
`lis_result_sourcedid` to be present as is mandatory to talk to the
grading API.
- On `master` launch https://hypothesis.instructure.com/courses/319/assignments/2988
Get an error ( the error being `User not found in course or is not a student`)
- Switch to `submision-teacher`, launch again, no error.

Explicitly check for the user roles to send canvas submissions

---

lms/models/__init__.py
lms/models/assignment_membership.py
lms/models/lti_role.py
lms/services/__init__.py
lms/services/assignment.py
lms/services/lti_role_service.py
lms/views/lti/basic_launch.py
tests/factories/__init__.py
tests/factories/assignment_membership.py
tests/factories/lti_role.py
tests/unit/lms/models/assignment_membership_test.py
tests/unit/lms/models/lti_role_test.py
tests/unit/lms/services/assignment_test.py
tests/unit/lms/services/lti_role_service_test.py
tests/unit/lms/views/lti/basic_launch_test.py
tests/unit/services.py

For:
* https://github.com/hypothesis/lms/issues/3993
Needs:
* https://github.com/hypothesis/lms/pull/4063
* Nuke your DB
* Start everything in the world and the visit a lot of assignments as different users
* Observe `lti_role` and `assignment_membership` filling up

Track what roles users have within assignments

---

lms/models/__init__.py
lms/models/assignment_grouping.py
lms/services/assignment.py
lms/views/lti/basic_launch.py
tests/factories/__init__.py
tests/factories/assignment_grouping.py
tests/unit/lms/models/assignment_grouping_test.py
tests/unit/lms/services/assignment_test.py
tests/unit/lms/views/lti/basic_launch_test.py

For:
* https://github.com/hypothesis/lms/issues/3992
Requires:
* https://github.com/hypothesis/lms/pull/4067
We want to know all the other relations between an assignment and sections and groups etc, but it's more complicated as these values aren't available at launch.
* Nuke your DB
* Start everything in the world and the visit a lot of assignments as different users
* Observe `assignment_grouping` filling up

Track assignment course relationships

---

lms/migrations/versions/1e146996cca6_add_assignment_grouping.py

I think this was a merge problem, or perhaps a result of tidying up the automatically generated migration?

Fix the assignment grouping migration to include the indexes correctly

---

lms/services/jstor.py
tests/unit/lms/services/jstor_test.py

The JSTOR API endpoints are being moved to new infrastructure ([Related Slack thread](https://hypothes-is.slack.com/archives/C02T75RKBTK/p1655126049981469)). The old endpoints accepted DOIs with or without percent-encoding of the slash between the DOI prefix and suffix. The new endpoints require that the slash is not percent-encoded.
**Testing:**
Update the `JSTOR_API_URL` env var in your `.devdata.env` file to:
```
export JSTOR_API_URL="https://labs.jstor.org/api/anno"
```
And check that the metadata/thumbnail still load correctly when configuring a JSTOR assignment (eg. using this article link: https://www.jstor.org/stable/26158829)

Update handling of slashes in JSTOR API endpoint paths

---

lms/services/jstor.py
tests/unit/lms/services/jstor_test.py

Fix an issue where the JSTOR article picker would show a thumbnail of the last page of the article instead of the first page.
The resolution of the image has also been increased to make it sharper. The size of the UI in the thumbnail is still too small to really make it possible to check if it is the correct thumbnail, but fixing this requires layout changes in a separate PR.
Fixes https://github.com/hypothesis/lms/issues/4061

Make JSTOR article thumbnail show first page instead of last page.

---

lms/static/scripts/frontend_apps/utils/fetch.js
lms/static/scripts/frontend_apps/utils/test/fetch-test.js

We have various places in our app where an API fetch gets retried after
re-authorization or when manually triggered by the user. Add a `retry` callback
to the `useFetch` hook's result to enable converting some of these fetches to use
`useFetch`/`useAPIFetch`.

Add `retry` callback to `useFetch` result

---

lms/static/scripts/frontend_apps/components/JSTORPicker.js
lms/static/scripts/frontend_apps/components/test/JSTORPicker-test.js
lms/static/scripts/frontend_apps/utils/jstor.js
lms/static/scripts/frontend_apps/utils/test/jstor-test.js

In addition to a JSTOR canonical article URL, also allow the user to enter:
- A plain article ID or DOI
- A JSTOR article URL that is being proxied via EZProxy or a similar service. Such services are one of the most common ways that off-campus access to JSTOR is handled.
- A JSTOR PDF URL or proxied PDF URL
Since we can extract the article ID / DOI from each of these inputs, it makes sense to accept them.
The parsing was informed by looking at [URLs from existing annotations which contain "jstor"](https://gist.github.com/robertknight/5110065b0ad536093f466a60aed0ae23). Note that we don't want to support all of the URLs in that list, as not all of them are JSTOR PDFs that can be chosen in the JSTOR article picker, and a very small proportion of the proxied URLs use unusual formats which are …

Accept more input formats in JSTOR article link entry field

---

lms/app.py
lms/models/__init__.py
lms/models/application_instance.py
lms/models/lti_params.py
lms/models/product.py
lms/resources/_js_config/__init__.py
lms/resources/lti_launch.py
lms/validation/_lti_launch_params.py
tests/unit/conftest.py
tests/unit/lms/models/application_instance_test.py
tests/unit/lms/models/lti_params_test.py
tests/unit/lms/models/product_test.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/validation/_lti_launch_params_test.py
tests/unit/lms/validation/authentication/_lti_test.py

Adds a `.product` property to the request object.
This doesn't look like much of an improvement over the current situation but enables many other refactors.

Product service and model

---

lms/models/grouping.py
lms/resources/_js_config/__init__.py
lms/resources/_js_config/file_picker_config.py
lms/resources/lti_launch.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/resources/_js_config/file_picker_config_test.py
tests/unit/lms/resources/lti_launch_test.py

Use request.product in the methods themselves to provide a more
concise API instead of having methods per LMS.
Again, not a massive improvement but having the same "API" in the LTIResource class allow for further refactors.
- canvas_sections_supported -> sections_enabled
It doesn't have any practical implications but it makes for a cleaner API
-  canvas_sections_supported inlined in sections_enabled
We only used the supported concept in `sections_enabled`. It could make sense as a separate concept if it was used elsewhere.
- canvas_groups_enabled and blackboard_groups_enabled moved/inlined in the filepicker.

Refactor lti_launch group properties

---

lms/static/scripts/frontend_apps/components/ErrorDisplay.js
lms/static/scripts/frontend_apps/components/StudentSelector.js
lms/static/scripts/frontend_apps/components/SubmitGradeForm.js
lms/static/scripts/frontend_apps/components/ValidationMessage.js
lms/static/styles/_utilities.scss
package.json
yarn.lock

This PR bumps `@hypothesis/frontend-shared` to `v4.6.0` to get the added `.focus-ring-visible` utility class and updates components to use it.

Bump `frontend-shared` and use `focus-visible-ring`

---

lms/security.py
lms/views/lti/basic_launch.py
lms/views/lti/deep_linking.py
lms/views/predicates.py
tests/unit/lms/security_test.py
tests/unit/lms/views/lti/basic_launch_test.py
tests/unit/lms/views/predicates_test.py

This PR swaps the `authorized_to_edit_assignment` for a permission as:
* It's weird that it's a predicate when it sounds very like a security thing
* This keeps all the logic for permissions in one place (`security.py`)
* This untangles some sideways linkage between deep linking and LTI launch views
Although I'm not suggesting we do, this also shows how we could have a completely unified launch view without any predicates as well.

Use permissions to tell if someone can edit an assignment

---

lms/services/__init__.py
lms/services/lti_names_roles.py
tests/unit/lms/services/lti_names_roles_test.py

For #933 
Implement the only missing API required for the full LTIA certification. (Deep linking is fully implemented but we have to pair the certification with this one)
This PR just implements the service but it's not used yet in any production code. This is potentially very useful but the focus now is the certification.
- Login in Canvas a teacher
- Apply a diff similar to 
```diff
diff --git a/lms/views/lti/basic_launch.py b/lms/views/lti/basic_launch.py
index 32d17c11..fe2bbf11 100644
--- a/lms/views/lti/basic_launch.py
+++ b/lms/views/lti/basic_launch.py
@@ -352,6 +352,12 @@ class BasicLaunchViews:
self.application_instance.update_lms_data(self.context.lti_params)
+        from lms.services import LTINamesRolesService
+
+        print(
+ …
```

Name and Roles LTI1.3 API service

---

lms/static/scripts/frontend_apps/components/SubmitGradeForm.js
lms/static/scripts/frontend_apps/components/test/SubmitGradeForm-test.js

Use the `useFetch` hook to simplify fetching the grade for a student in
the SubmitGradeForm component. In particular `useFetch` handles ignoring
the results of fetches when the input query changes, avoiding the need
for the component to do it.
There was an error in a test where an async function was faked with a
stub that threw synchronously. This has been corrected to be async like
the real implementation.
---
**Testing:**
Aside from the unit tests, I also did a manual test of the grading bar using the assignment at https://hypothesisuniversity.moodlecloud.com/course/view.php?id=11.
To test error handling I applied this diff to force grade fetches to fail:
```diff
diff --git a/lms/views/api/lti.py b/lms/views/api/lti.py
index f71e233f..baf04b1e 100644
--- a/lms/views/api/lti.py
+++ …
```

Simplify grade fetching using `useFetch` hook

---

lms/static/scripts/frontend_apps/components/JSTORPicker.js
lms/static/scripts/frontend_apps/components/test/JSTORPicker-test.js
lms/views/api/jstor.py
tests/unit/lms/views/api/jstor_test.py

_This PR contains the frontend part of https://github.com/hypothesis/lms/pull/4118._
PDFs are not available for collections, only specific articles in a
collection. For this reason, disable the Submit button in the JSTOR
article picker if the item is a collection and present an error to
explain why and how to resolve the issue.
The `is_collection` property of the article metadata API response is
just a placeholder for the moment, while some schema changes are worked
out on JSTOR's side.
---
**Testing:**
1. Enter an article ID in the JSTOR picker, eg. 123456. The title should appear and the Submit button should be available.2. 
2. Apply the following diff below, then close and re-open the picker and enter the same ID. The title should appear but this time the Submit button will be disabled …

Show error in JSTOR article picker if item is a collection

---

lms/static/scripts/frontend_apps/components/JSTORPicker.js
lms/static/scripts/frontend_apps/components/test/JSTORPicker-test.js

This PR adds a checkbox to the JSTOR content-picking step of assignment configuration which must be checked to submit (select) the JSTOR content.
The updated interface looks like this (no change to interface until metadata is loaded):
I've used the minimal number of words for the checkbox label. Let's check in with folks and see what wording tweaks we might need. Advise for the fewest words possible as this interface is tight and starts looking crowded if the text wraps on the label.
I've adjusted the "confirm-on-enter-press" logic to account for the new input, as well.
Fixes https://github.com/hypothesis/private-issues/issues/137

Add JSTOR terms confirmation checkbox

---

lms/services/jstor.py
tests/unit/lms/services/jstor_test.py

Handle various issues found when extracting article titles from JSTOR API responses. This fixes various cases in which the JSTOR picker form showed incomplete or missing titles.
We could ask JSTOR to do some of this normalization on their side, but doing it on our end gives us more flexibility and the ability to change it when needed. Also some of these differences are due to different item types (articles vs collections of articles vs reviews of other articles) that we will need to treat differently on our end in other ways too.
1. Append subtitle to title, if present. The title often doesn't make sense
without the subtitle part (see https://github.com/hypothesis/lms/issues/4088)
2. Handle container publications, which use a different field for the title
("tb") and subtitle ("tbsub") …

Improve extraction of titles from JSTOR API responses

---

bin/update_dev_data.py
lms/services/rsa_key.py
tests/factories/rsa_key.py
tests/unit/lms/services/rsa_key_service_test.py
tests/unit/services.py

For #3968 
Not yet executed in production as is meant to be called from a Celery task. 
- Truncate rsa_key and `make devdata` before starting.
- `tox -qe dockercompose -- exec postgres psql -U postgres -c "select created, kid, expired from  rsa_key;"`
```
created          |               kid                | expired 
---------------------------+----------------------------------+---------
2022-06-21 07:41:31.52763 | f1a394d0268e4fd8b45391ce4c1ee901 | f
(1 row)
```
(this one comes from devdata)
- Rotate the keys, on `make shell`
```
from datetime import timedelta
from lms.services import RSAKeyService
rsa_service = request.find_service(RSAKeyService)
rsa_service.rotate(5, timedelta(days=1), timedelta(days=1))
tm.commit()
```
- `tox -qe dockercompose -- exec postgres psql -U postgres -c …

Add RSAKeyService.rotate

---

lms/services/jstor.py
tests/unit/lms/services/jstor_test.py

While reviewing https://github.com/hypothesis/lms/pull/4098 I noticed quite a few things, but they weren't introduced in that PR.
This is a quick follow up to remove a lot of the extra private methods with two observations:
* All of the methods that call the API went through the same sequence of steps before calling it
* This has all moved into the API call
* We may need to break this up if future calls which don't fit this pattern are found. We'll see
* Inlined all methods which are only used in one place
* Removed a bit of un-used generality in some of the methods
The aims are to:
* Reduce repetition
* Keep code closer to where it's needed and used
* Make the code easier to read

Simplify the JSTOR service using inlining and refactoring

---

lms/models/lti_params.py
lms/resources/lti_launch.py
lms/services/document_url.py
lms/views/lti/basic_launch.py
tests/unit/lms/models/lti_params_test.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/services/document_url_test.py
tests/unit/lms/validation/authentication/_lti_test.py
tests/unit/lms/views/lti/basic_launch_test.py

We had a quirk where you read all the params from `context.lti_params` except for `resource_link_id` which was read from the context. 
This fixes that weirdness. It also shows a likely place for another plugin to get all the Canvas behavior out of there.

Move `resource_link_id` to the `LTIParams`

---

lms/resources/_js_config/__init__.py
lms/validation/_api.py
tests/unit/lms/resources/_js_config/__init___test.py

Adding this ahead of any changes on the API to populate the client's
config and avoid backwards incompatible changes in the next steps.

Add extra configuration to blackboard and canvas sync API.

---

lms/resources/_js_config/__init__.py
lms/resources/lti_launch.py
lms/views/lti/basic_launch.py
lms/views/lti/deep_linking.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/views/lti/basic_launch_test.py
tests/unit/lms/views/lti/deep_linking_test.py

I reckon we are aiming to reduce the size of `LTILaunchResource` removing LMS specific bits from it.
application_instance is a fundamental part of a launch and fits better here than in JSConfig. 
Removed some, IMO, superfluous exception handling. The application instance is suppose to be there by the time we are handling the launch, if it's not there we rather let any exceptions bubble up to sentry instead of hiding it. We do the same thing for user/lti_user.

Make application instance part of the LTI context

---

lms/resources/_js_config/__init__.py
lms/views/api/blackboard/sync.py
lms/views/api/canvas/sync.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/views/api/blackboard/sync_test.py
tests/unit/lms/views/api/canvas/sync_test.py

After #4133  been merged for a while it would be safer to switch to this approach.
It might not be evident in the diff but with this both sync APIs (canvas/bb) are mostly exactly the same code now. 
The next step is to merge them into one view.
Sanity check with:
Canvas sections https://hypothesis.instructure.com/courses/125/assignments/873
Canvas groups https://hypothesis.instructure.com/courses/125/assignments/1833
Canvas course https://hypothesis.instructure.com/courses/122/assignments/856
BB course https://aunltd-test.blackboard.com/webapps/blackboard/execute/blti/launchPlacement?blti_placement_id=_20_1&content_id=_36_1&course_id=_19_1
BB groups https://aunltd-test.blackboard.com/webapps/blackboard/execute/blti/launchPlacement?blti_placement_id=_20_1&content_id=_398_1&course_id=_19_1

Sync view group set id refactor

---

lms/views/lti/basic_launch.py
tests/unit/lms/views/lti/basic_launch_test.py

For:
* https://github.com/hypothesis/lms/issues/3994
Previously this was only done for groups and sections etc.
* Start all the things
* Run `make sql` and keep a terminal open to type in queries
* Clear existing records:
```sql
TRUNCATE grouping_membership;
```
* Visit any assignment, e.g. https://hypothesis.instructure.com/courses/125/assignments/873
* Select rows from the table:
```sql
SELECT
"user".h_userid,
grouping.lms_name,
grouping.type
FROM "user"
JOIN grouping_membership 
ON grouping_membership.user_id = "user".id
JOIN grouping 
ON grouping_membership.grouping_id = grouping.id;
```
* In `main` you should only see rows for sections
* In this branch you should see the course too

Store group membership data for courses

---

lms/static/scripts/frontend_apps/components/JSTORPicker.js
lms/static/scripts/frontend_apps/components/test/JSTORPicker-test.js

As discussed and agreed, this PR updates the wording and flow associated with accepting JSTOR terms in the assignment configuration content picker.
After these changes, the interface looks like so:

Update UI related to acceptance of JSTOR terms

---

lms/product/factory.py
lms/resources/_js_config/__init__.py
tests/unit/lms/product/factory_test.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/views/api/exceptions_test.py

- Without this fix
```update oauth2_token set access_token = 'nope', refresh_token ='nope';```
and launch https://hypothesis.instructure.com/courses/125/assignments/875
There's this error message that flashes for a while.
That doesn't happen in this branch.

Fix product family for GET endpoints

---

lms/product/blackboard/product.py
lms/product/canvas/product.py
lms/product/product.py
lms/resources/_js_config/__init__.py
lms/resources/_js_config/file_picker_config.py
lms/views/api/blackboard/files.py
lms/views/api/exceptions.py
tests/unit/conftest.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/views/api/exceptions_test.py

This is a small change to parameterize the authentication URLs we use in various places.
This doesn't go as far as replacing it in the views and routes definitions, but it does:
* Remove some conditionality around products
* Means that if we need to add this in future none of the code will need to change to accommodate it

Parameterize auth urls

---

Jenkinsfile
Makefile

This is a pain because it apparently requires there to be a separate `make functests-only` target (although is that really necessary?)
But anyway: I don't think there's any benefit to running the functests on Jenkins after we've already run them on GitHub Actions. It's just more code to maintain and more waiting around for Jenkins to finish. The idea originally was that Jenkins runs the tests actually inside the Docker container so it's more similar to production than GitHub Actions which doesn't run the tests in Docker. But I don't think there's ever been a case of the tests passing on GitHub Actions and then Jenkins catching a problem with its second run of the tests. So in practice I think this is silly.
I think there are better steps that we could take to control CI-versus-prod …

Don't run the functests on Jenkins

---

tests/bdd/steps/lms_db.py

The unit tests and functests both pass `stamp=False`:
https://github.com/hypothesis/lms/blob/b87d3b8f307e868efbc73156d69d66fd5ecf6352/tests/conftest.py#L54
https://github.com/hypothesis/lms/blob/b87d3b8f307e868efbc73156d69d66fd5ecf6352/tests/functional/conftest.py#L49
The BDD tests need to do the same. Currently the BDD tests are actually stamping the dev DB! Using the hard-coded SQLAlchemy URL in `conf/alembic.ini`. (They're not stamping the BDD tests DB.)

Don't stamp the dev DB in the BDD tests

---

tox.ini

These envvars are now read from the environment by the `setenv` section of `tox.ini` with lines like this:
```ini
dev: DATABASE_URL = {env:DATABASE_URL:postgresql://postgres@localhost:5433/postgres}
```
This means it's no longer necessary to list these envvars in the `passenv` section.

Remove duplicate envvars from `tox.ini`

---

lms/product/blackboard/product.py
lms/product/canvas/product.py

For dataclasses class level variables will work as expected when accessing at a class level, but unless you declare them correctly, the dataclass generated init will ignore them and fill out the last correctly defined thing.
For safety it's best to fully declare them all.
To demonstrate this see:
```python
from dataclasses import dataclass
@dataclass
class Base:
foo: str = None
@dataclass
class Both(Base):
foo: str = "both"
@dataclass
class NoType(Base):
foo = "no-type"
class NoDataClass(Base):
foo: str = "no-data-class"
class Neither(Base):
foo = "no-dataclass-no-type"
for class_ in (Both, NoType, NoDataClass, Neither):
print(f"{class_.__name__}> cls={class_.foo}, instance={class_().foo}")
```
This results in:
```
Both> cls=both, instance=both
NoType> cls=no-type, instance=None …
```

Fix route instantiation for Canvas and Blackboard

---

lms/resources/_js_config/__init__.py
lms/services/assignment.py
lms/views/api/sync.py
lms/views/lti/basic_launch.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/services/assignment_test.py
tests/unit/lms/views/api/sync_test.py
tests/unit/lms/views/lti/basic_launch_test.py

For:
* https://github.com/hypothesis/lms/issues/4080
Based on:
* https://github.com/hypothesis/lms/pull/4148
We were already tracking the association between assignments and courses, and this adds tracking between assignments and other types of grouping.
The PR is in two commits. The first adds the required data and the second consumes it. If we want to we can split this into two PRs and merge the first one only to allow clients in the wild to get the new config before it's required.
* Start everything
* Visit: https://hypothesis.instructure.com/courses/125/assignments/873
* Look for assignment grouping relations which aren't to do with course:
```sql
SELECT assignment_id, grouping.type
FROM assignment_grouping
JOIN grouping ON grouping.id = grouping_id
WHERE type != 'course'
```
* In …

Track assignment group / section relationships

---

lms/services/ltia_http.py
lms/views/lti/deep_linking.py
tests/unit/lms/services/ltia_http_test.py
tests/unit/lms/views/lti/deep_linking_test.py

Fixing a couple of awkward spots here:
- LTIAHTTP service was using a set of defaults
- Those defaults were used in both the LTIHTTP own request method to sign token request and also using the `sign` method to sign any payload.
- Those defaults look very similar but are not actually the same.
Sending `nonce` on the token request was causing an error as D2L doesn't allow the unexpected parameters: https://sentry.io/organizations/hypothesis/issues/3394604678/?referrer=slack
The fix here is passing all the parameters in needed in both cases directly to JWTService and removing the public `sign` method on LTIA service.
- Deep link an assignment: 
https://hypothesis.instructure.com/courses/125/assignments/2956/edit?name=Testing+grading+(marcos)&due_at=null&points_possible=10
- Submitting a …

Don't send the unnecessary nonce value in LTIA service

---

lms/resources/_js_config/__init__.py
lms/resources/_js_config/file_picker_config.py
lms/resources/lti_launch.py
lms/services/document_url.py
lms/views/lti/basic_launch.py
lms/views/lti/deep_linking.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/resources/_js_config/file_picker_config_test.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/services/document_url_test.py
tests/unit/lms/views/lti/basic_launch_test.py
tests/unit/lms/views/lti/deep_linking_test.py

The LTI launch context `lti_params` method was just a proxy for the request method of the same name:
```python
@property
def lti_params(self) -> LTIParams:
"""Return the requests LTI parameters."""
return self._request.lti_params
```
This replaces all uses of `context.lti_params` and removes it. In some cases this also removes the need for the context object completely.

Replace `context.lti_params` with `request.lti_params`

---

lms/product/__init__.py
lms/product/blackboard/__init__.py
lms/product/blackboard/_plugin/grouping.py
lms/product/canvas/__init__.py
lms/product/canvas/_plugin/grouping.py
lms/product/plugin/__init__.py
lms/product/plugin/grouping_service.py
lms/product/plugin/plugin.py
lms/product/product.py
lms/services/grouping/service.py
tests/unit/conftest.py
tests/unit/lms/product/blackboard/_plugin/grouping_test.py
tests/unit/lms/product/canvas/_plugin/grouping_test.py
tests/unit/lms/product/plugin/test_plugin.py
tests/unit/lms/product/product_test.py
tests/unit/lms/services/grouping/factory_test.py
tests/unit/lms/services/grouping/service_test.py

I didn't want to go this way initially as I didn't want confusion between plugins and services. Here plugins are registered using the same mechanism as services but they aren't intended to be used stand alone like services, and are a different thing.
The plugins were starting to look quite service like, but attempting to solve up-coming problems was creating an awkward situation where we probably want access to the context sometimes. At that point the interface really is the same as services so :shrug: why not just embrace it?
This is a well understood mechanism. Which has some nice features:
* Naturally lazy loading and caching
* Plugins get full access to the request and context if required, meaning we should never have to pass it in to specific calls - as any plugin that needs it can …

Use pyramid services as the initialisation mechanism

---

lms/session.py

Without at explicit max_age the cookie had a "session" length which
behaves differently across browsers. In Chrome for example it meant that
the cookie didn't survive browser restarts.
Having an explicit max_age means that the autoexpiring mechanism is no
longer needed.

Stop using autoexpiring session in favour of a long max age

---

lms/session.py

This achieves the desired result meant in #4184 
- Go to http://localhost:8001/admin and login, close the browser, open again, still logged in (not changed in this PR)
- Leave the browser session open now for over 20 minutes. The session survives.

Explicilty disable autoexpiring sessions

---

lms/static/scripts/frontend_apps/utils/jstor.js
lms/static/scripts/frontend_apps/utils/test/jstor-test.js

This avoids an error if the article ID was copied and pasted from a selection
that had some extra spaces.

Ignore leading and trailing space in JSTOR input field

---

lms/services/jstor.py
tests/unit/lms/services/jstor_test.py

Adapt to the new JSTOR metadata API schema, as described in https://hypothes-is.slack.com/archives/C02T75RKBTK/p1655930468948019 and in the OpenAPI docs at https://labs.jstor.org/api/anno/docs#/default/get_metadata_new_metadata_new__doi__get.
- Expect "title" and "subtitle" fields to be strings rather than
single-item lists
- Expect "reviewed_works" field to be an array of titles rather than
items
- Expect the "title" and "subtitle" fields to be used for more item
types, reducing the need for us to check different fields depending
on the item type.
The new API has been temporarily exposed under the `/metadata-new`
endpoint. It will be exposed under the original `/metadata` endpoint in
future.
A set of test cases have been collated from existing issues into a list at …

Adapt to new JSTOR metadata API schema

---

lms/services/blackboard_api/client.py

The loop is going to modify that list, removing items from it, which can
cause the iteration to not reach all items.
I'm a bit puzzled by this one, I know this has worked before, specifically with the 50 groups group set as is the one we always tested this case (having to make lots of async requests) but I also can't see how this could have worked before :thinking:.
- On `main` create a BB group assignment, pick the `Group set with 50 groups` group set.
- Launch it as a student. You'll get a long list of groups.
- Switch to this branch. Launch again as a student. You'll get 1 or two groups depending which student you picked.

Make a copy of the groups list before iterating over it.

---

lms/routes.py
lms/views/api/gateway.py
tests/functional/api/gateway_test.py
tests/functional/oauth1.py
tests/unit/lms/views/api/gateway_test.py

For:
* https://github.com/hypothesis/lms/issues/4197
This adds a version of the gateway end-point which only provides information sufficient for connecting to H.
This version enforces that the GUID provided matches the credentials we expect for the application instance. I think this really should happen in our security layer but due to the way we try policies in order this might be a little tricky.
* Check out and try the tools in: https://github.com/hypothesis/lms/pull/4224

Add a gateway end-point which provides H API connection details

---

lms/templates/admin/instance.new.html.jinja2
lms/templates/admin/macros.jinja
lms/views/admin/__init__.py
lms/views/admin/application_instance.py
tests/unit/lms/views/admin/application_instance_test.py

Add a path to upgrade existing instances to LTI 1.3
I went through different options to do this with @chrisshaw and settled on the one implemented here, unifying the creation/upgrading flows into one. In any case we can revisit it once it get enough use.
- Search for issuer `https://blackboard.com` at http://localhost:8001/admin/registrations/
- Pick any of the results and click `New instance`
- Use the consumer key `Hypothesis37c8a8ac186ad5d7e6da83c060c3b18b`
- Save, you are taken to the application instance details, which new include the registration and a deployment id.

Allow LTI1.3 upgrades from the admin pages

---

.eslintrc
package.json
yarn.lock

Update eslint-config-hypothesis and remove local overrides that are no
longer required.
See also notes in https://github.com/hypothesis/client/pull/4657.

Update ESLint config and simplify project config

---

lms/services/jstor.py
tests/unit/lms/services/jstor_test.py

Update PDF URL endpoint from `/pdf-url/{doi}` => `/pdf/{doi}`.
See https://hypothes-is.slack.com/archives/C02T75RKBTK/p1656344325914429?thread_ts=1656076613.726979&cid=C02T75RKBTK
Marked as a draft because authentication is not currently working and the endpoint is returning a 403. I'm investigating this.

Update JSTOR PDF endpoint

---

lms/services/jstor.py
tests/unit/lms/services/jstor_test.py

Change temporary `/metadata-new/{doi}` endpoint back to `/metadata/{doi}` and update `/pdf-url/{doi}` to `/pdf/{doi}`. See [note from Ron](https://hypothes-is.slack.com/archives/C02T75RKBTK/p1656344325914429?thread_ts=1656076613.726979&cid=C02T75RKBTK).
I tested all the article IDs from https://gist.github.com/robertknight/a2b045b717d6c7dda18879df91c16e90 in the JSTOR file picker using the updated endpoint, and they all return some reasonable title. Note that not all of these items have thumbnails, so it is expected that the thumbnail is blank for some of them.
If you're trying to launch an assignment, you'll find that our test account that has access to "everything" doesn't in fact appear to have PDF access to all of these test articles. If you look in the metadata responses you'll see …

Update JSTOR metadata and PDF endpoints

---

lms/services/assignment.py
lms/views/api/sync.py
lms/views/lti/basic_launch.py
tests/unit/lms/services/assignment_test.py
tests/unit/lms/views/api/sync_test.py
tests/unit/lms/views/lti/basic_launch_test.py

This allows us to skip looking up the assignment by id, only to then read the id from it.
This doesn't change other methods which could do the same thing.
Follow up to:
* https://github.com/hypothesis/lms/pull/4158

Accept assignment id instead of just assignment for `upsert_assignment_groupings`

---

lms/services/vitalsource/_client.py
lms/services/vitalsource/service.py
lms/views/api/vitalsource.py
tests/unit/lms/services/vitalsource/_client_test.py
tests/unit/lms/services/vitalsource/service_test.py
tests/unit/lms/views/api/vitalsource_test.py

We were previously returning data verbatim from VitalSource and then manipulating it to be the format we want. We might as well do that all in the client directly as our abstraction over the real API.
There are some other small refactors here as well.

Clean up the VitalSource api view

---

lms/resources/_js_config/__init__.py
lms/resources/_js_config/file_picker_config.py
lms/services/vitalsource/factory.py
lms/services/vitalsource/service.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/resources/_js_config/file_picker_config_test.py
tests/unit/lms/services/vitalsource/factory_test.py
tests/unit/lms/services/vitalsource/service_test.py

Currently if LMS was misconfigured with:
* Vitalsource enabled in the application instance settings
* But the API key not setup
We would still present the VitalSource file picker, which would then fail.
This PR makes the responsibility of deciding whether the picker is available to the service. This has some follow up benefits for future PRs where the decision will become more complicated. This means we can change the service and nothing else should have to change.

Use a service method to decide if `VitalSource` is available

---

bin/gateway/config/gateway_qa_example.json
bin/gateway/config/h_calls_dev.json
bin/gateway/config/h_calls_prod.json
bin/gateway/config/h_calls_qa.json
bin/gateway/h_call.py
bin/gateway/oauth_call.py
docs/gateway/01_overview.md
docs/gateway/02_api_spec.md
docs/gateway/03_authentication.md
docs/gateway/03_testing_tools.md
docs/gateway/04_testing_tools.md
docs/gateway/schema.json

For:
* https://github.com/hypothesis/lms/issues/4197
This adds testing tools to accompany the return of actual data from the new gateway end-point and also documentation which is intended for user consumption. This documents the output from:
* https://github.com/hypothesis/lms/pull/4222
* This adds a new tool `h_call.py`
* [The documentation](https://github.com/hypothesis/lms/blob/gateway-tools/docs/gateway/01_overview.md) should describe how to use it, and basically form the testing instructions.

Add documentation and tools for using Gateway return values

---

requirements/bddtests.txt
requirements/dev.txt
requirements/functests.txt
requirements/lint.txt
requirements/requirements.txt
requirements/tests.txt
tests/unit/lms/views/api/gateway_test.py

For:
* https://github.com/hypothesis/lms/issues/4197
This PR includes consumer testing, which is something we don't do by name, which is to run tests which check the agreement you make with 3rd parties.
If we change our API in a way such that the documentation isn't valid any more (at least as far as the schema goes) this should result in a test failure.
This keeps us honest with the schema we provide to customers and will alert us of any changes.

Add consumer tests to prove we meet our own schema

---

bin/gateway/config/h_calls_dev.json
bin/gateway/config/h_calls_prod.json
bin/gateway/config/h_calls_qa.json
bin/gateway/h_call.py
docs/gateway/schema.json
lms/views/api/gateway.py
tests/functional/api/gateway_test.py
tests/unit/lms/views/api/gateway_test.py

This PR looks a lot bigger than it is. Before the layout was:
```json
{
"h_api": ...
}
```
Now it's:
```json
{
"api": {
"h": ...
}
}
```
This allows us to leave space for calls back to LMS (or something else?) in future without a cluttered root data structure.

Nest in the H connection details to leave space for possible LMS ones in future

---

lms/static/scripts/frontend_apps/components/BookSelector.js
lms/static/scripts/frontend_apps/components/JSTORPicker.js

These fields accept both URLs and item IDs. If the user enters a URL
then browsers can figure out not to apply spell checking. In case the
user enters a book/item ID however, we need to explicitly disable spell
checking.
**Testing:**
Enter an article ID like "10.7249/mg876rc.10" in the JSTOR picker. Previously you'd see a spelling error underline on part of the ID. With this change you shouldn't.

Disable spell-checking for JSTOR and VitalSource input fields

---

lms/templates/admin/instance.html.jinja2
lms/views/admin/application_instance.py

For:
* https://github.com/hypothesis/lms/issues/4218
- The per-instance VitalSource API key needs to be used to query for
information about users or courses associated with a particular
institution.
- The user ID field identifies which field from the LTI launch request
should be passed to VitalSource's `POST /v3/credentials.xml` API in
order to obtain a token for use in subsequent user-specific requests
(eg. to list the books a user has access to)
We need this information to be in place before we can deploy the new work, otherwise existing customers will break.

Add per-instance VitalSource API keys and user ID field settings

---

bin/gateway/config/gateway_qa_example.json
docs/gateway/02_api_spec.md
lms/views/api/gateway.py
tests/functional/api/gateway_test.py
tests/unit/lms/views/api/gateway_test.py

It's possible for a client to launch our gateway view before a user has ever launched us. This will result in the credentials we issue belonging to a user which is not yet in H and so not valid. To get around this we insert the user.
A secondary problem is that the user will have no anntations to look at. We can get some of the way around this by allocating them to the course group. For course grouped assignments, this is actually all you will need.
For groups / sections, the user will still see nothing and will need to launch some assignments.
In all of these cases assume the call is being made for a user which has never interacted with our products.
Assuming we don't sync a user:
* The customer calls the gateway
* **When they try to exchange our token for an OAuth token they are told …

Sync the user before we issue credentials in the Gateway

---

lms/templates/admin/instance.html.jinja2
lms/views/admin/application_instance.py
tests/unit/lms/views/admin/application_instance_test.py

Mistakes while we input these couldn't be solved, allow editing them.
This is more relevant now with the LTI1.3 upgrade flow were these might need updating anyway.

Allow editing of some AI settings in the admin pages

---

lms/static/scripts/frontend_apps/index.js
lms/static/scripts/frontend_apps/test/index-test.js
rollup-tests.config.mjs

Add some minimal tests for the LMS app entry point, to check it runs the right
app depending on the config.
To allow the entry point to only run when explicitly called in the test
environment, define an `LMS_FRONTEND_TESTS` global in the Rollup bundle, which
code can check for.

Add basic test for LMS frontend entry point

---

lms/routes.py
lms/templates/admin/instance.html.jinja2
lms/views/admin/application_instance.py
tests/unit/lms/views/admin/application_instance_test.py

This is something that *in theory* shouldn't be necessary. In practice we have found the need for it 3 times already over the last few days as we are finding bugs, strange behaviors from the LMS, etc.
- Go to http://localhost:8001/admin/registration/id/1/
- Click new instance
```
Consumer key: Hypothesis37c8a8ac186ad5d7e6da83c060c3b18b
Deployment id: DEPLOYMENT_ID
```
Leave the rest blank
- Check that the AI now has a registration and deployment IDs attached
- Scroll to the bottom of the application instance, click downgrade.
- The application instance now longer has the LTI 1.3 fields.

Add a downgrade to LTI 1.1 option in the admin pages

---

lms/services/jstor.py
lms/static/scripts/frontend_apps/api-types.js
lms/static/scripts/frontend_apps/components/JSTORPicker.js
lms/static/scripts/frontend_apps/components/test/JSTORPicker-test.js
lms/views/api/jstor.py
tests/unit/lms/services/jstor_test.py
tests/unit/lms/views/api/jstor_test.py

Show an error and disable the "Continue" button in the JSTOR assignment picker dialog, if the item does not have an associated PDF (eg. because it is a collection) or the PDF is not accessible to the institution that the current user is associated with.
Fixes https://github.com/hypothesis/lms/issues/4082.
These show what the user will see in each of the three situations.
**Content available:**
(Example link: https://www.jstor.org/stable/3314737)
**Item has no content:**
(Example link: https://www.jstor.org/stable/i274509)
**Item has content, but user's institution does not have access:**
(Example link, when using our "hypothes.is" site code: 10.2307/community.30528851. The availability of this particular item might change pending a discussion with JSTOR).

Show error in JSTOR picker if content is not available

---

lms/services/__init__.py
lms/services/jstor/__init__.py
lms/services/jstor/_article_metadata.py
lms/services/jstor/factory.py
lms/services/jstor/service.py
tests/unit/lms/services/jstor/_article_metadata_test.py
tests/unit/lms/services/jstor/factory_test.py
tests/unit/lms/services/jstor/service_test.py

The JSTOR service is getting bigger and quite a lot of it is all to do with parsing article metadata.
This splits up the service into a few parts to make each test shorter, and to make testing the metadata stuff easier.

Split the JSTOR service up into a directory

---

lms/services/jstor/_article_metadata.py
lms/static/scripts/frontend_apps/api-types.js
lms/static/scripts/frontend_apps/components/JSTORPicker.js
lms/static/scripts/frontend_apps/components/test/JSTORPicker-test.js
lms/static/scripts/frontend_apps/services/content-info-fetcher.js
lms/static/scripts/frontend_apps/services/test/content-info-fetcher-test.js
tests/unit/lms/services/jstor/_article_metadata_test.py

This changes the data structure we return from the JSTOR metadata proxy API from:
```json
{
"title": "Title: Subtitle"
}
```
To be:
```json
{
"item": {
"title": "Title",
"subtitle": "Subtitle"
}
}
```
* Start LMS and friends
* Visit: https://hypothesis.instructure.com/courses/125
* Create a new assignment using the localhost LMS instance
* Open the F12 dev tools to the network tab and filter by "jstor"
* Select JSTOR and enter: https://www.jstor.org/stable/3314735
* You should see the data correctly displayed
* You should see the new details in the network output

Return JSTOR titles and sub-titles with less interpretation

---

lms/services/vitalsource/factory.py
tests/unit/lms/services/vitalsource/factory_test.py

This fixes an issue were the api key is required (ValueError is thrown)
for a VitalSourceSerivce.enabled check.
Not sure if this is the right approach, the enable check in the service does check for the presence of the client so this works.
https://github.com/hypothesis/lms/blob/907c512c3929add67987f703d50985f18d068c1b/lms/services/vitalsource/service.py#L18
- On `main` remove `VITALSOURCE_API_KEY` from `.devdata.env` (and restart the server is running)
- Try to configure an assignment, you'll get an error page.
- Same thing on this branch should work.

Inject None as a client to the VS service when the api key is missing

---

lms/static/scripts/frontend_apps/api-types.js
lms/static/scripts/frontend_apps/services/client-rpc.js
lms/static/scripts/frontend_apps/services/content-info-fetcher.js
lms/static/scripts/frontend_apps/services/test/content-info-fetcher-test.js

This PR shuttles some of the additional fields recently added to the proxy API for JSTOR item metadata on over to the client for use in the banner. As a result, the client banner is now able to display:
* The title of the container
* Next and/or previous links, when available
A few tweaks are necessary on the client side before we can show the following, but the metadata supporting them are part of these changes:
* Link to the current item
* Subtitle of the current item
* Configure a Canvas localhost assignment in https://hypothesis.instructure.com/courses/125 to use JSTOR content
* In the JSTOR content picker, enter the ID `26893773` (this item has a subtitle, as well as next/previous links)
* Launch the assignment. **Click the button to open the assignment in a new window**. This is …

Pass on additional JSTOR item metadata to the client for banner

---

lms/services/__init__.py
lms/services/exceptions.py
lms/services/jstor/service.py
lms/views/api/exceptions.py
tests/factories/requests_.py
tests/unit/lms/services/jstor/service_test.py
tests/unit/lms/views/api/exceptions_test.py

The JSTOR API raises 404s when:
* You have a completely broken URL
* You have the right URL but the particular thing you are looking for doesn't exist
There's quite a lot of variation, but by experimenting with various calls I managed to get a set of indicators that narrowed down which type of 404 we have.
Correctly formatted by missing items:
* https://labs.jstor.org/api/anno/metadata/10.2307/9999999999
* `Content-Type: application/json;charset=UTF-8`
* Content: `null`
* https://labs.jstor.org/api/anno/thumbnail/10.2307/999999999?offset=1&width=280
* `Content-Type: text/plain;charset=UTF-8`
Broken URLs:
* https://labs.jstor.org/api/anno/BROKEN
* `Content-Type: application/json;charset=UTF-8`
* Content: `{	"detail": "Not Found"}`
* https://labs.jstor.org/api/BROKEN
* `Content-Type: …

Catch 404's from JSTOR and try and distinguish between no item and wrong URL

---

lms/views/admin/application_instance.py
tests/unit/lms/views/admin/application_instance_test.py

This is broken in `main` currently:
- Go to http://localhost:8001/admin/registration/id/2/new/instance
```
consumer key: Hypothesis37c8a8ac186ad5d7e6da83c060c3b18b
deployment_id: 0f29b2ec-444d-462b-9c5b-fcc0803ab2d2
```
In main it will fail, it will hos a message in this branch.

Rollback failed transaction in admin pages

---

lms/static/scripts/frontend_apps/services/client-rpc.js
lms/static/scripts/frontend_apps/services/content-info-fetcher.js
lms/static/scripts/frontend_apps/services/test/content-info-fetcher-test.js

This is a trivial cleanup PR to remove the now-unused `containerTitle` field from the JSTOR content-info payload sent to the `client` to show the content-info banner. 
This is possible now that https://github.com/hypothesis/client/pull/4684 has landed and the `client` no longer references this field.

Remove unused `containerTitle` field

---

lms/static/scripts/frontend_apps/components/test/SubmitGradeForm-test.js

Fix a mock for an async method to reject rather than throw synchronously.
This required changes to how the test waits for changes in the rendered
output.
The test passed by accident previously because all the state updates within the
component happened to be triggered synchronously.

Make mocked async method, in SubmitGradeForm tests, reject rather than throw

---

docs/gateway/schema.json
lms/services/grouping/service.py
lms/views/api/gateway.py
tests/factories/__init__.py
tests/factories/grouping_membership.py
tests/unit/lms/services/grouping/service_test.py
tests/unit/lms/views/api/gateway_test.py

For:
* https://github.com/hypothesis/lms/issues/4197
This PR adds group return values for the gateway end-point. The groups returned are:
* Groups in the current course
* That the user is in as well
* Start `h` and `lms`
* Ensure you have visited some assignments
* Use `bin/gateway/oauth_call.py` to issue a request and view the results
* If you are missing a config file for this please ask
* You should see profile data dumped in the output

Return details of the current user's groups in the Gateway data

---

lms/views/lti/basic_launch.py
tests/unit/lms/views/lti/basic_launch_test.py

For now we'll allow duplicate records of the same launch in both `Events` and `LtiLaunches`. This will simplify the next step of the migration to eventually just having them in Events.
- Start with no events
```
tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate event,lti_launches cascade"
```
- Launch a couple of assignment
https://hypothesis.instructure.com/courses/125/assignments/1513
- Check the inserted data
```
tox -qe dockercompose -- exec postgres psql -U postgres -c "select * from event"
id |         timestamp          | type_id | application_instance_id | course_id | assignment_id | grouping_id 
----+----------------------------+---------+-------------------------+-----------+---------------+-------- …
```

Store events for configured launches.

---

lms/resources/_js_config/__init__.py
lms/services/vitalsource/factory.py
lms/services/vitalsource/service.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/services/vitalsource/factory_test.py
tests/unit/lms/services/vitalsource/service_test.py

For:
* https://github.com/hypothesis/lms/issues/4349
This allows the original, non SSO, non institutional key solution for VitalSource to continue to work. This will allow us to release this to our customers who have their own API keys without disrupting those that don't.
* If we have a customer key we will use it in preference to the global key for metadata lookup
* If we have a customer key **and** a user id field, we will enable SSO
This leads to a few different modes of operation:
* Global key lookup, no SSO
* User key lookup, no SSO
* User key lookup + SSO
This needs to be merged into `vs-sso` not `main` to enable `vs-sso` to be safe to release without having all the customer details updated.
You may wish to review this as a [diff against …

Re-instate the non-SSO VitalSource path as a fallback

---

lms/resources/_js_config/__init__.py
lms/services/vitalsource/_client.py
lms/services/vitalsource/exceptions.py
lms/services/vitalsource/factory.py
lms/services/vitalsource/service.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/services/vitalsource/_client_test.py
tests/unit/lms/services/vitalsource/factory_test.py
tests/unit/lms/services/vitalsource/service_test.py

For:
* https://github.com/orgs/hypothesis/projects/71/views/1
Previous to this PR we would direct the user straight to the bookshelf on the correct book. This required the user to have independently signed into the bookshelf for this to work.
Now we:
* Check if the user has a licences
*  If not show an error
* Generate a redirect link that signs the user in, and then redirects to the shelf
This means the user does not always need to log in
If the user does not have a licence then we show them an error instead of showing them the book viewer. However users can sometimes be automatically granted a licence by the book viewer. Unfortunately the redirect mechanism doesn't take this into account and fails.
This means we are deciding between our error page and the one generated by the redirect. …

Return a redirect to automatically log users in to Vitalsource

---

lms/resources/_js_config/__init__.py
lms/routes.py
lms/views/api/vitalsource.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/views/api/vitalsource_test.py

For:
* https://github.com/orgs/hypothesis/projects/71/views/1
Requires:
* https://github.com/hypothesis/lms/pull/4269
Put the front-end in charge of getting Vitalsource links to allow more parallelism. 
Nothing should have changed from: https://github.com/hypothesis/lms/pull/4269.
You can follow the instructions there and should get the same outcome, except you should see the calls being made from the front end.

Move the call to get the SSO link to the front end as a call back

---

lms/services/jwt.py
tests/functional/lti_certification/v13/core/test_bad_payloads.py

These are showing up in the logs but we can't identify where (which school) they are coming from.
Adding issuer and aud (client id) should help make the messages more useful.

More complete log message on JWT decoding

---

lms/migrations/versions/396f46318023_events_backfill.py

For #3947 
Using a cutoff date to avoid inserting duplicates now that launches are
being recorded both in events and lti_launches.
Having this done now makes the next step, swapping `lti_launches` by a view, easier as there's no need to coordinate.
Quick count check after last week query issues
```
SELECT 'migration', count(1) FROM (
SELECT
lti_launches.created,
1,
application_instances.id,
MAX(grouping.id)
FROM lti_launches
LEFT OUTER JOIN application_instances
ON lti_launches.lti_key = application_instances.consumer_key
LEFT OUTER JOIN grouping
ON context_id = grouping.lms_id 
AND grouping.application_instance_id = application_instances.id 
AND grouping.type = 'course'
-- We need to group by to pick one (MAX grouping.id) above of the possible
-- multiple courses on the grouping table …
```

Backfill events from `lti_launches`

---

lms/services/exceptions.py
tests/unit/lms/services/exceptions_test.py

For: 
* https://github.com/hypothesis/product-backlog/issues/1368
It seems Canvas have changed the output we get from a 401 to a 403 when the user is not authorized. As there are many different Canvas deploys in the wild we now catch both.
* Login to Canvas as a student
* Visit: https://hypothesis.instructure.com/courses/125/assignments/1371
* On main you see a generic error
* On this branch you should see "Couldn't get the file from Canvas"

Newer Canvas instances will now return a nice error for unavailable files

---

lms/services/vitalsource/factory.py
lms/services/vitalsource/service.py
lms/templates/admin/instance.html.jinja2
lms/views/admin/application_instance.py
tests/unit/lms/services/vitalsource/factory_test.py
tests/unit/lms/services/vitalsource/service_test.py

This seems to unnecessarily cause problems for some customers. This is to provide an option to work around this while we work through the issue.

Add a work around to disable licence checking for VS SSO

---

lms/models/lti_params.py
tests/unit/lms/models/lti_params_test.py

For https://github.com/hypothesis/lms/issues/4369
LTI1.3 reports the roles for the context (same as LTI1.1, the roles for
the current launch) but also any other roles across the institution in
different namespaces.
For the  current layer of compatibility with LTI1.1 we'll take only the
relevant roles for the current course.
https://www.imsglobal.org/spec/lti/v1p3#role-vocabularies
- Clear event_user 
```tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate event_user"```
- Switch  to this branch an launch  
as `Hypothesis 101 Teacher`
check the JWT coming from canvas, it contains:
```
"https://purl.imsglobal.org/spec/lti/claim/roles": [
"http://purl.imsglobal.org/vocab/lis/v2/institution/person#Instructor", …
```

Fix roles reported for LTI1.3 launches

---

lms/migrations/versions/396f46318023_events_backfill.py

Original migration timed out on production:
https://jenkins.hypothes.is/job/lms-tasks/174/console
Running the query side on metabase seem to finish in a reasonable time so the problem might be on inserting side. 
This, the whole table query, finish in metabase:
```
SELECT
lti_launches.created,
1,
application_instances.id,
MAX(grouping.id)
FROM lti_launches
LEFT OUTER JOIN application_instances
ON lti_launches.lti_key = application_instances.consumer_key
LEFT OUTER JOIN grouping
ON context_id = grouping.lms_id
AND grouping.application_instance_id = application_instances.id
AND grouping.type = 'course'
-- Only backfill rows created before we also start tracking them directly on this table
WHERE lti_launches.created < '2022-08-17T13:00:08.241'
-- We need to group by to pick one (MAX …
```

Modify backfilling migration to work on batches.

---

lms/resources/_js_config/__init__.py
lms/services/vitalsource/__init__.py
lms/services/vitalsource/_client.py
lms/services/vitalsource/exceptions.py
lms/services/vitalsource/factory.py
lms/services/vitalsource/service.py
lms/static/scripts/frontend_apps/components/ErrorDialogApp.js
lms/static/scripts/frontend_apps/config.js
lms/templates/admin/instance.html.jinja2
lms/views/admin/application_instance.py
lms/views/exceptions.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/services/vitalsource/factory_test.py
tests/unit/lms/services/vitalsource/service_test.py
tests/unit/lms/views/admin/application_instance_test.py
tests/unit/lms/views/exceptions_test.py

Also change the names a bit to make it clear the user is about SSO.
This PR is a bit longer than it really should have to have been as we didn't have a way of raising a new exception without:
* Writing a custom handler for it in the `views.exceptions.py`
* Writing a custom entry in the Javscript for it
This builds on the `SerializableError` work for the API's which introduced an exception you can raise and expect sensible behavior from the front end.
This really shouldn't be in the location it is in `services.exceptions`, but we don't have a generic `exceptions.py` and I don't want to get into that right now.
* `make devdata` and start everything
* Visit a VS assignment (e.g. https://hypothesis.instructure.com/courses/125/assignments/3158)
* This should work as normal
Error case: too many …

Add a new field for VitalSource user field regexes

---

lms/templates/admin/macros.jinja
lms/templates/admin/registration.html.jinja2
lms/views/admin/lti_registration.py
tests/unit/lms/views/admin/lti_registration_test.py

Allow editing URLs at the registration level (auth, token and JWKs). 
For #4304 
- Go over http://localhost:8001/admin/registration/id/1/
- Edit some URLs
- ????
- :tada:

Allow editing registration URLs in the admin

---

lms/security.py
tests/functional/views/admin_test.py
tests/unit/lms/security_test.py

Instead of trying policies until one of them works explicitly declare
the policy to be used based on the current URL.
This only tackles the "map routes to policies" issue and only applies it to the admin pages which use Google's Oauth. 
- Head over http://localhost:8001/admin login, logout.
- Launch an assignment as a sanity check for the rest of the auth methods: https://hypothesis.instructure.com/courses/125/assignments/875

Refactor SecurityPolicy to map routes to policies

---

lms/views/admin/lti_registration.py
tests/unit/lms/views/admin/lti_registration_test.py

For: https://github.com/hypothesis/lms/issues/4304
This is a common error while pasting the values for a new registration as we have this value (the issuer) but also the "LMS URL" which might look very similar depending of the LMS.
We could just remove the slash if present but I reckon this just makes it more explicit and might be a good prompt to double check things.
- Go over http://localhost:8001/admin/registration try an new issuer ending with `/`

Don't allow `/` on issuer

---

lms/migrations/versions/79eda94de79f_add_organizations_model.py

For:
* https://github.com/hypothesis/lms/issues/4200
Adds a migration for the model in:
* https://github.com/hypothesis/lms/pull/4329
Reset your DB and run the upgrade:
```shell
git checkout main
git checkout orgs-db-migration
make sql
```
Check the results
```sql
\d+ organization;
```
```sql
\d+ application_instances;
```
Note the `organization_id` column and `fk__application_instances__organization_id__organization`.
Downgrade the DB and check the results:
```shell
hdev alembic downgrade -1
make sql
```
```sql
\d+ organization;
```
Gone!
```sql
\d+ application_instances;
```
The org column and relation is gone

Add a DB migration for the organization work

---

lms/routes.py
lms/templates/admin/instance.new.html.jinja2
lms/templates/admin/registration.html.jinja2
lms/views/admin/application_instance.py
tests/unit/lms/views/admin/application_instance_test.py

Refactor the views/forms for new registrations.
The current form is not very clear on the intent as is using the same form/view two do two different things:
- Add a new AI to a registration
- Upgrade an existing AI while adding it to the registration.
This PR makes the split more explicit. 
There's a behavior change, in the version in `main` you can edit `lms url` and `email` (but not canvas key/secret) while upgrading an existing AI. Removing that option here, if you want to change those while upgrading you'll have to first upgrade and then update them on the AI details page.
- Go to http://localhost:8001/admin/registration/id/1/
- Click "Add instance"
- Complete the first form, the one labeled "Create new Application instance"
- You'll be taken to newly created AI.
- Check …

Refactor admin pages to make the new vs upgraded instance actions more clear

---

lms/services/application_instance.py
lms/templates/admin/instance.html.jinja2
lms/views/admin/application_instance.py
tests/unit/lms/services/application_instance_test.py
tests/unit/lms/views/admin/application_instance_test.py

Allow editing AIs Canvas API details
Simpler alternative than https://github.com/hypothesis/lms/pull/4376
For #4304 
- Go over to http://localhost:8001/admin/instance/id/100/
- Enter any values for key/secret
- They are saved on the AI 
```tox -qe dockercompose -- exec postgres psql -U postgres -c "select developer_key, developer_secret, aes_cipher_iv from application_instances where id = 100"```

Allow editing canvas API details in the admin pages

---

lms/db/__init__.py
lms/models/application_instance.py
lms/services/__init__.py
lms/services/application_instance.py
lms/services/organization.py
lms/views/lti/basic_launch.py
lms/views/lti/deep_linking.py
tests/factories/group_info.py
tests/unit/lms/db/__init___test.py
tests/unit/lms/models/application_instance_test.py
tests/unit/lms/services/application_instance_test.py
tests/unit/lms/services/organization_service_test.py
tests/unit/lms/views/lti/basic_launch_test.py
tests/unit/lms/views/lti/deep_linking_test.py
tests/unit/services.py

For:
* https://github.com/hypothesis/lms/issues/4202
This looks at the status of the application instances org and attempts to match it with the following behavior:
* If there is no org
* Search for matching orgs by guid either from the application instances or group info table
* If one or more matches are found, use the first
* If no matches are found, create a new org
* Set the org to the application instance
* If the org has no name, and the application instance `tool_consumer_instance_name` is present, set the name from it
This includes a refactor to move the updating of application instances into the service because:
* That's where I expected to find it and I got confused
* We are not expanding it beyond what's ok to have on a model
This could be a separate PR if you'd prefer it …

Automatically assign application instance to organizations

---

lms/migrations/versions/52755322151e_db_migration_to_back_fill_organizations.py
lms/migrations/versions/52755322151e_db_migration_to_back_fill_organizations.sql

For:
* https://github.com/hypothesis/lms/issues/4201
This should be released after the automatic association of new accounts with orgs in:
* https://github.com/hypothesis/lms/pull/4332
This will ensure there are no gaps in between. This migration will wipe out those records, but that's fine.
* Reset your DB:
```shell
git checkout orgs-db-model
git checkout orgs-backfill
make dev
```
*  Start all the things
* Before the migration will work you will need some application instances with GUIDs, e.g.:
* https://hypothesis.instructure.com/courses/125/assignments/873
* https://aunltd-test.blackboard.com/ultra/courses/_19_1/cl/outline
* Run the migration:
```shell
```
* You should see output about created orgs
* Check the …

Add backfill for organization data

---

lms/migrations/versions/52755322151e_db_migration_to_back_fill_organizations.sql

For:
* https://github.com/hypothesis/lms/issues/4201
The problem was a silly mistake joining on application instance id, rather than guid. Meaning every application instance was only paired with itself, rather than with other application instances with matching GUIDs.
If you want more detailed debugging, then I suggest printing out the edges and grouped items to understand what's going on.
* Start everything
* Ensure you have a clean DB state
```shell
hdev alembic downgrade -1
```
* Visit different application instance assignments with the same GUID:
* https://hypothesis.instructure.com/courses/319/assignments/3308
* https://hypothesis.instructure.com/courses/125/assignments/873
* Observe that the two application …

Fix org backfill migration that caused each AI to get it's own org

---

lms/app.py
lms/models/region.py
lms/resources/_js_config/__init__.py
tests/conftest.py
tests/unit/conftest.py
tests/unit/lms/models/region_test.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/services/h_api_test.py
tests/unit/lms/views/api/gateway_test.py

For:
* https://github.com/hypothesis/lms/issues/4204
This adds dumping a few extra values into the console, including the org id.
* Start everything
* Checkout `orgs-auto-assign` - https://github.com/hypothesis/lms/issues/4202
* Look at https://hypothesis.instructure.com/courses/125/assignments/873
* This will create an org
* Checkout this branch
* Look at https://hypothesis.instructure.com/courses/125/assignments/873
* Open the debug F12 menu and checkout the logs

Add organisation and application instance info to the launch debug data

---

package.json
yarn.lock

This package is needed during the Docker build, and packages listed in
devDependencies are not installed in that context.

Move @babel/preset-typescript from devDependencies to dependencies

---

lms/services/lti_grading/_v13.py
tests/unit/lms/services/lti_grading/_v13_test.py

For:  https://github.com/hypothesis/lms/issues/4443 
Fixes: https://sentry.io/organizations/hypothesis/issues/3486870164/?project=259908
Until now we only seen LMS not sending a value at all when there's no grade but some LMS seem to send a `None` value instead.
https://hypothes-is.slack.com/archives/C2BLQDKHA/p1663045160950229

Fix result retrieval for cases for `None` values

---

lms/views/lti/deep_linking.py
tests/unit/lms/views/lti/deep_linking_test.py

For https://github.com/hypothesis/lms/issues/4438
It looks like most LMS don't send a `data` field but there at least a few instances where the whole `deep_linking_settings` is not present.

Fix deeplinking requests missing `deep_linking_settings`

---

lms/security.py
lms/views/exceptions.py
tests/functional/lti_certification/v13/conftest.py
tests/functional/views/basic_lti_launch_test.py
tests/unit/lms/security_test.py
tests/unit/lms/views/exceptions_test.py

Use `LTIUserSecurityPolicy` introduced in https://github.com/hypothesis/lms/pull/4394 for LTIAuthentication and expose any validation error in them on `forbidden_view`.
- Launch an assignment should work as before in this branch: https://hypothesis.instructure.com/courses/125/assignments/873
- Same for deep linking https://hypothesis.instructure.com/courses/125/assignments/3118/edit?name=Testing+upgrade+-+marcos&due_at=null&points_possible=10
- Switch to `main` a make change that would result in a validation error
```
diff 
--git a/lms/validation/_lti_launch_params.py b/lms/validation/_lti_launch_params.py
index 0ad79a84..e27a7cf8 100644
--- a/lms/validation/_lti_launch_params.py
+++ b/lms/validation/_lti_launch_params.py
@@ -25,7 +25,7 @@ class LTIV11CoreSchema(PyramidRequestSchema): …
```

Move LTI authentication to LTIUserSecurityPolicy

---

lms/services/jwt.py
tests/functional/lti_certification/v13/core/test_bad_payloads.py
tests/unit/lms/security_test.py
tests/unit/lms/services/jwt_test.py

Current behavior of the JWT service is to fail silently and return an empty dictionary for invalid JWTs.
Raising `lms.ValidationError` instead which produces a meaningful error message.
- Simulate the three scenarios (not all at the same time):
```diff
--git a/lms/services/jwt.py b/lms/services/jwt.py
index 8beca8fb..a9f9e322 100644
--- a/lms/services/jwt.py
+++ b/lms/services/jwt.py
@@ -73,7 +73,7 @@ class JWTService:
if not id_token:
return {}
-        if not jwt.get_unverified_header(id_token).get("kid"):
+        if jwt.get_unverified_header(id_token).get("kid"):
LOG.debug("Missing 'kid' value in JWT header")
return {}
@@ -82,7 +82,7 @@ class JWTService:
registration = self._registration_service.get(iss, aud)
-        if not registration:
+        if registration:
LOG.debug("Unknown …
```

JWT better error handling

---

lms/db/__init__.py
lms/services/event.py
tests/unit/lms/services/event_test.py

Instead of keeping them in sync with migrations and other methods for testing.

Insert new event types when first seen.

---

lms/services/organization.py
tests/unit/lms/services/organization_service_test.py

For: https://github.com/hypothesis/lms/issues/4448
Both PK and a `_public_id`. In some cases this might work as:
- The new org is added to the session implicitly on the AI relationship.
- Any query or the final commit will have the same effect as the flush.
but at least in the "unconfigured_launch" case an implicit flush doesn't happen before we try to use `public_id` on the organization.
- Set un-org your application instances:
```update application_instances set organization_id = null;```
- On `main`, go to blackboard, create a new assignment and launch it, it will fail.
- Test again on this branch, it will succeed.

Make sure newly created Organization have IDs

---

lms/models/__init__.py
lms/services/application_instance.py
lms/services/organization.py
lms/services/public_id.py
lms/templates/admin/instance.html.jinja2
lms/views/admin/application_instance.py
tests/unit/lms/models/organization_test.py
tests/unit/lms/services/application_instance_test.py
tests/unit/lms/services/organization_service_test.py
tests/unit/lms/services/public_id_test.py
tests/unit/lms/views/admin/application_instance_test.py

For https://github.com/hypothesis/lms/issues/4417
this doesn't yet tackle:
- Creating a new organisation from an application instance
- Go to an AI that has an organization
- Save without filling the new field with any value. Nothing will  update
- Save with an invalid/non existing ID. You'll get feedback on the error.
- Save with an existing valid ID. The organization wolud be updated.

Allow moving AI to different organizations

---

lms/services/jstor/factory.py
lms/services/jstor/service.py
tests/unit/lms/services/jstor/factory_test.py
tests/unit/lms/services/jstor/service_test.py

Add a unique user ID and user agent (browser) information to JSTOR API requests as `Tracking-User-ID` and `Tracking-User-Agent` headers respectively. These are needed by JSTOR for usage counting purposes. See https://github.com/hypothesis/lms/issues/4340 for background.
Example of the headers that are now sent with each API request:
```py
{'Authorization': 'Bearer ...', 'Tracking-User-ID': '3a022b6c146dfd9df4ea8662178eac', 'Tracking-User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36'
```
Fixes https://github.com/hypothesis/lms/issues/4340

Add user ID and browser ID info to JSTOR API requests

---

lms/services/organization.py
lms/templates/admin/organizations.html.jinja2
lms/views/admin/organization.py
tests/unit/lms/services/organization_service_test.py
tests/unit/lms/views/admin/organization_test.py

Search organizations by name or public id.
- Go over http://localhost:8001/admin/orgs
- Search by public id
- Search by name

Allow organizations search in the admin pages

---

lms/events/__init__.py
lms/events/event.py
lms/models/event.py
lms/views/admin/organization.py
tests/unit/conftest.py
tests/unit/lms/events/test_event.py
tests/unit/lms/views/admin/organization_test.py

The audit mechanism is more general than strictly needed for keeping changes for `enabled`.
My plan is to apply this to other type of objects in the admin pages. Ideally with one liner PRs after some testing.
- Go over the admin pages, to one particular organization 
- Toggle the enabled status at the bottom
- Check the audit trail on the database with a query like:
```
select * from event 
join event_data on event.id = event_data.event_id 
join event_type on event.type_id = event_type.id
where type ='audit';
```

Audit changes made to `organization.enabled`

---

lms/services/vitalsource/_client.py
tests/unit/lms/services/vitalsource/_client_test.py

For:
* https://github.com/hypothesis/lms/issues/4462
This pulls all the error handling for the two book methods into a single chain of methods and unifies the testing.
There's not much we can do to test this really, as it requires a situation on VitalSource's side. If you want to see the exception you can hack the code to raise the exception.
* Hack `lms.services.vitalsource._client` to add `raise VitalSourceConfigurationError("test")` in `get_book_info()`
* Start all the things
* Visit: http://localhost:8001/admin/instance/id/8/
* Enable Vitalsource
* Visit: https://hypothesis.instructure.com/courses/125/
* Create your own localhost assignment with VitalSource
* Paste in any book, e.g. https://bookshelf.vitalsource.com/reader/books/9781786894700
* You should see a message indicating …

Handle catalog errors and group our error handling

---

bin/update_dev_data.py

The easiest way to set up Git->GitHub.com authentication nowadays is by
installing [GitHub CLI](https://cli.github.com/), running
[gh auth login](https://cli.github.com/manual/gh_auth_login), and
answering "Yes" (the default) when it asks "Authenticate Git with your
GitHub credentials?". By default this will set up authentication for
HTTPS git clone URLs but not SSH ones so `make devdata` will fail with
an authentication error because it tries to clone the private devdata
repo using the SSH clone URL.
Fix this by changing the devdata clone URL to the HTTPS one.

Change to HTTPS for the devdata clone URL

---

lms/app.py
lms/models/region.py
tests/unit/lms/app_test.py
tests/unit/lms/models/region_test.py

For:
* https://github.com/hypothesis/lms/issues/4500
This keeps the request method for now, but makes it optional. This is just to demonstrate the way of setting this up.

Using a global singleton instead of a request method for region

---

lms/services/organization.py
lms/views/admin/organization.py
tests/unit/lms/services/organization_service_test.py
tests/unit/lms/views/admin/organization_test.py

For:
* https://github.com/hypothesis/lms/issues/4480
This merges public id and name searching into one function under the hood. This allows a few improvements:
* This allows an OR search across both
* You can also hit search with no values and get a list of orgs. This could be handy for devs
This also fixes text searching (hopefully) in QA and Live

A more powerful unified search function for the organization service

---

lms/services/organization.py
lms/templates/admin/organizations.html.jinja2
lms/views/admin/organization.py
tests/unit/lms/services/organization_service_test.py
tests/unit/lms/views/admin/organization_test.py

For:
* https://github.com/hypothesis/lms/issues/4480
Depends on:
* https://github.com/hypothesis/lms/issues/4480
Now we have a unified search, it's quite easy to add more variations to it. This PR:
* Inlines searching by primary key into the unified search
* Exposes this on the organization search page

Allow searching for organizations by primary key

---

lms/services/organization.py
lms/templates/admin/organizations.html.jinja2
lms/views/admin/organization.py
tests/unit/lms/services/organization_service_test.py
tests/unit/lms/views/admin/organization_test.py

For:
* https://github.com/hypothesis/lms/issues/4480
Depends on:
* https://github.com/hypothesis/lms/issues/4480
* https://github.com/hypothesis/lms/pull/4478
Now we have a unified search, it's quite easy to add more variations to it. This PR:
* Inlines the GUID search into the unified search function
* Adds it to the admin pages
* Removes the old function which is completely superseded by search now

Allow searching for organizations by GUID

---

lms/templates/admin/organizations.html.jinja2

Just a small quality of life improvement. The page looks kind of goofy with an empty table.

Present a message on the organization search instead of a blank table when there are no results

---

lms/static/scripts/frontend_apps/utils/onedrive-picker-client.js

Make sure we check the top-level domain as a whole. The check should match hostnames like "companyname.sharepoint.com" but not "notsharepoint.com". As far as I know, the hostname should always have a subdomain (ie. will never be just "sharepoint.com").
This issue was found by CodeQL. See https://github.com/hypothesis/lms/issues/4507

Refine check for whether a sharing URL refers to SharePoint

---

.github/workflows/deploy.yml

Deploys were taking too long. This update moves concurrency settings inside the individual jobs.
- continuous integration (allow in parallel)
- create-image (allow in parallel)
- qa-us-west-1 (queue, don't cancel)
- prod-us-west-1 (cancel others)
- prod-ca-central-1 (cancel others)
For more information see: https://github.com/hypothesis/playbook/issues/987

Update concurrency settings

---

lms/routes.py
lms/templates/admin/instance.html.jinja2
lms/views/admin/application_instance.py
tests/unit/lms/views/admin/application_instance_test.py

Fixes https://github.com/hypothesis/product-backlog/issues/1398
- Go over an AI in the admin pages http://localhost:8001/admin/instance/id/101/
- Make sure it has some settings set
- Move it to a an org 
- All the settings are preserved
- In `main`, repeat org moving operation.
- All settings are set to false/null

Fix AI moving organization overriding all settings

---

lms/models/lti_params.py

For #4492 
Canvas now sends custom LTI params as strings in both LTI versions.
Added a logging statement to detect how many older canvas instances we server and eventually remove the coercing step.

Document changes in canvas custom parameter typing

---

.gitignore
bin/update_dev_data.py
conf/supervisord-dev.conf

This is not a solution for #3690  but it will help in some cases.
The main motivation for this is D2L requirement that oauth2 callbacks are in https domains. They allow https://localhost so this is a much simpler solution that anything involving tunnels.
To test this requirement head over https://aunltd.brightspacedemo.com/d2l/lp/extensibility/oauth2
(credentials in 1Password) and try to edit the existing key to use http.
---
Using certificates stored in devdata server the main application at '48001' using gunicorn builtin HTTPS support.
- Using '4' + '8001' as the HTTPS port I think this could be an easy to remember convention if we exteneed this to other projects.
- Running the HTTPS server in the main `make dev` command. This will fail if some of the HTTPS setup is wrong but will avoid …

Support HTTPS in `make dev`

---

.github/workflows/deploy.yml

This commit reverts the job level concurrency settings that we changed in attempt to improve the performance of the workflow.
https://hypothes-is.slack.com/archives/C4K6M7P5E/p1666871158716429

Reverted `deploy.yml` to known working state

---

docker-compose.yml

This allows containers in other projects to talk directly to H's DB.
With this change we can mimic the foreign data wrapper setup we have in production locally.

Add the postgres container to an external network

---

lms/static/scripts/frontend_apps/utils/jstor.js
lms/static/scripts/frontend_apps/utils/test/jstor-test.js

This fixes a mistake found by CodeQL. See https://github.com/hypothesis/lms/issues/4507.

Escape "." in DOI regex

---

.github/workflows/tasks.yml

Changed default timeout to 900 seconds. This value is used in two contexts:
- It is passed to AWS when requesting an ODIC token. The timeout defines the life of the token, and the default is 900 seconds. If you pass a value lower it will result in an error. This happens through the reusable [eb-task.yml](https://github.com/hypothesis/workflows/blob/main/.github/workflows/eb-task.yml) workflow being called.
- The value is also used to constrain the length of the H task being executed.

Increased default timeout: tasks.yml

---

lms/sql_tasks/sql_query.py
tests/unit/lms/sql_tasks/sql_query_test.py

This is a pretty silly method but I'm convinced the real solution should be done at the variable level (which contains the secrets) rather then at the script/line level.
I added a note to revisit this for this project but with this I'm sure if we remember something is a secret will stick a `-- secret` to it without worrying to much about messing up the formatting.

Hide lines marked as secret in SQL tasks

---

Makefile
docker-compose.yml
tox.ini

(Needs to be tested together with the equivalent in H https://github.com/hypothesis/h/pull/7673)
The `dbs` network is used by multiple projects is available without needing to synchronize which project creates it first.
- `docker-compose down` in both H and LMS
- `docker network rm dbs` (if you have created it manually)
- `make services` in both H and LMS, in any other.

Make sure the network `dbs` exists for `make services`

---

lms/sql_tasks/tasks/report/create_from_scratch/02_entities/04_group_map/01_create_view.sql

For:
* https://github.com/hypothesis/report/issues/4
Previously we were missing anything which joined onto this table and didn't have a `grouping` entry, which would be a lot of older stuff.
* In `h`:
* `make services`
* tox -e dev --run-command "python bin/run_sql_task.py --config-file conf/development-app.ini --task report/create_from_scratch"
* In `lms`:
* `make services`
* `tox -e dev --run-command "python bin/run_sql_task.py --config-file conf/development.ini --task report/create_from_scratch"`
* `make db`
* `select * from report.organization_activity;`
* You should see some stuff
* `tox -e dev --run-command "python bin/run_sql_task.py --config-file conf/development.ini --task report/refresh"`
* It shouldn't crash
You can also comment out the `xfail` in the functional tests in: …

Include group info data when mapping groups to ensure we include old values

---

.github/workflows/report_refresh.yml

For:
* https://github.com/hypothesis/report/issues/4
Trigger the refresh job to happen 30 minutes after the `h` one. We can tweak the time eventually, but it's intended to run during times we will be around to see it fail (rather than waking someone up).
This will make it less reliable as people will probably disrupt it with deploys, but we can fix that later.

Set the refresh job to happen 30 minutes after `h`

---

lms/templates/admin/macros.html.jinja2

Fix for https://github.com/hypothesis/product-backlog/issues/1401
- Head to http://localhost:8001/admin/registrations/
- Search for issuer `https://blackboard.com`
- The view button takes you to the right registration instead of a random AI.

Fix registration macro to point to the right view

---

lms/services/document_url.py

For: 
- https://github.com/hypothesis/lms/issues/4451
This is used from a predicate so it might be called for unrelated views while finding the appropriate one.
Take advantage of the existing path to return None when the conditions are not meet.
When the predicate fails in an unrelated view we get errors like
https://sentry.io/organizations/hypothesis/issues/3406054455/?referrer=github_integration
That add noise and hide the real issue (sometimes the real issue might be a legit 401 or 403)
- Canvas files assignment keep working as expected: 

Check for canvas values for canvas files

---

lms/product/blackboard/product.py
lms/product/canvas/product.py
lms/product/factory.py
lms/product/product.py
lms/resources/_js_config/__init__.py
lms/resources/_js_config/file_picker_config.py
lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/GroupConfigSelector.js
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
lms/static/scripts/frontend_apps/components/test/GroupConfigSelector-test.js
lms/static/scripts/frontend_apps/config.js
tests/unit/conftest.py
tests/unit/lms/product/factory_test.py
tests/unit/lms/product/product_test.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/resources/_js_config/file_picker_config_test.py

While doing the D2L groups PoC there was lots of repetition around the config (is the feature enabled? what are the endpoint details?)
This aims to reduce the duplication exposing the details once, not once per product.
To check nothing's been broken in the process:
- Reconfigure https://hypothesis.instructure.com/courses/125/assignments/3118/edit?name=Testing+upgrade+-+marcos&due_at=null&points_possible=10
Set it to any document source and pick groups and a groupset. Launch it.
- Same testing with https://aunltd-test.blackboard.com/webapps/blackboard/execute/blti/launchPlacement?blti_placement_id=_20_1&content_id=_183_1&course_id=_19_1

Refactor groups config

---

lms/models/application_settings.py
lms/product/d2l/product.py
lms/services/aes.py
lms/templates/admin/instance.html.jinja2
lms/views/admin/application_instance.py
tests/unit/lms/models/application_settings_test.py
tests/unit/lms/views/admin/application_instance_test.py

Make room for D2L setting on the admin pages.
Took the opportunity I was around this code to tackle: https://github.com/hypothesis/product-backlog/issues/1399 
(requires https://github.com/hypothesis/devdata/pull/65)
- Ahead to http://localhost:8001/admin/instance/id/106/
- Play with the settings for D2L

D2L details in the admin pages

---

.pylintrc
lms/product/d2l/product.py
lms/routes.py
lms/services/__init__.py
lms/services/d2l_api/__init__.py
lms/services/d2l_api/_basic.py
lms/services/d2l_api/client.py
lms/services/d2l_api/factory.py
lms/views/api/d2l/authorize.py
lms/views/api/d2l/groups.py
lms/views/api/refresh.py
tests/unit/lms/services/d2l_api/_basic_test.py
tests/unit/lms/services/d2l_api/client_test.py
tests/unit/lms/services/d2l_api/factory_test.py
tests/unit/lms/views/api/blackboard/authorize_test.py
tests/unit/lms/views/api/d2l/authorize_test.py
tests/unit/lms/views/api/d2l/groups_test.py
tests/unit/lms/views/api/refresh_test.py
tests/unit/services.py

Adds the required service and views for D2L oauth2 authentication.
On top of that adds a method and view to get the list of group categories so we can test the whole oauth2 process using the UI.
- `make devdata` to start with.
- Go to https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2120/View as a teacher
- Select any type of document and check the group assignment
- When prompted to authorize, deny the request (to test https://github.com/hypothesis/lms/pull/4639/files#diff-acd99c9193ec519d3248994780ce552fef977e8915329f06f5d300e18aee5a5eR73)
- Try again and authorize the request this time
- You'll get a group category in the drop down coming from the D2L API.

D2L API authentication

---

lms/models/lti_params.py
tests/unit/lms/models/lti_params_test.py

We want consider admins to be teacher for authorization purposes, ie we allow them to create/edit assignments.
Currently we exclude non-context scoped roles to avoid mixing roles from other courses in the current one but we make an exception here for admin.
This is a much simpler approach than:
- https://github.com/hypothesis/lms/pull/4641
and directly fixes:
- https://github.com/hypothesis/product-backlog/issues/1394
but it doesn't fix any of the refactor aspects of that PR, doesn't unify the roles handling or exposes the scope of the role to the rest of the app.
- In `main`
- Log in as `Canvas Admin` in canvas and head try to edit (use the `Hypothesis LTI1.3 (localhost)` LTI app) 
https://hypothesis.instructure.com/courses/319/assignments/2988/edit?name=No+grade+LTI1.3&due_at=null&points …

Consider admin role regardless of their scope

---

lms/migrations/versions/6eb9de301ac3_d2l_group_grouping.py

Based on the changes on 
https://github.com/hypothesis/lms/pull/4659/files#diff-1247685c2ce802726b483f8d3f351f5ff88a47bd45305ba5cb00c0376a6b77e9R70
The migration is not autogenerated, as the constraint already exists, both the upgrade and downgrade paths first delete it and then re-create with the right shape.
`hdev alembic upgrade head`
```
dev run-test-pre: PYTHONHASHSEED='3981211424'
INFO  [alembic.runtime.migration] Running upgrade 52755322151e -> 6eb9de301ac3, New d2l_group type for groupings.
```
- Check the constraint
```
ox -qe dockercompose -- exec postgres psql -U …
```

Migration for new D2L grouping type

---

lms/models/grouping.py
lms/product/d2l/__init__.py
lms/product/d2l/_plugin/grouping.py
lms/product/d2l/product.py
lms/product/plugin/grouping_service.py
lms/resources/lti_launch.py
lms/services/d2l_api/client.py
lms/services/group_info.py
lms/sql_tasks/tasks/report/create_from_scratch/02_entities/03_groups/01_create_view.jinja2.sql
tests/unit/lms/product/d2l/_plugin/grouping_test.py
tests/unit/lms/services/d2l_api/client_test.py

Needs
- Migration on https://github.com/hypothesis/lms/pull/4660
- devdata from https://github.com/hypothesis/devdata/pull/69
- and... this fix in H https://github.com/hypothesis/h/pull/7712
---
Implements the grouping plugin for D2L. We can get away with just two API method endpoints and a query to our grouping service (ie getting them from the DB).
Using the asssigments in https://aunltd.brightspacedemo.com/d2l/le/content/6782/Home?itemIdentifier=D2L.LE.Content.ContentObject.ModuleCO-2122
I created assignment for LTI 1.1 and 1.3 for completeness but there's not differences in the code of this PR about any differences between them.
- Launch as an instructor
- You might need to visit https://localhost:48001/lti/1.3/oidc and approve a fake SSL certificate …

D2L grouping plugin

---

lms/static/scripts/frontend_apps/components/LaunchErrorDialog.js
lms/static/scripts/frontend_apps/components/test/LaunchErrorDialog-test.js
lms/static/scripts/frontend_apps/errors.js

Use the same dialog as for other products except for "user not in group" where we want to make explicit that the user missing is the one in D2L, not hypothesis (or at least I reckon that the rationale for the existing Canvas/Blackboard ones).
The dialogs look like:
- (You'll need the latest commits in H to test this locally)
- `make devdata`
- Testing this locally relies on a self signed HTTPS certificate, in chrome you might need to either:
- Visit https://localhost:48001/lti/1.3/oidc and approve a the certificate
- Or enable the toggle in chrome://flags/#allow-insecure-localhost
- Head over https://aunltd.brightspacedemo.com/d2l/le/content/6782/Home?itemIdentifier=TOC
(credentials in 1Pass)
and launch the assignments (no LTI1.1 vs 1.3 differences here are relevant)
As teacher 
- …

Handle D2L group related error codes

---

docs/configuration.md
lms/config.py
lms/tasks/rsa_key.py
tests/conftest.py
tests/unit/lms/tasks/rsa_key_test.py
tox.ini

For 
- #3916 
---
`DISABLE_KEY_ROTATION` allows disabling RSA key rotation in one environment.
This is useful in QA, where we could disable key rotation and point external servers to the QA environment and share the same keys in the local environments.
The alternative to this is using tunneling but that can be cumbersome as:
- Tunnels can't be shared, two developers can't use the same tunnel at the same time.
- Using different tunnels would require the LMS config to have multiple registrations/application instances. This are time consuming to create and then assignment are linked to one of them. Testing the same thing by different developer will require duplicating the assignments.
- Start `make dev`
- Start a new shell with `make shell` and run
```
from lms.tasks.rsa_key import …
```

Allow disabling key rotation task with a new setting

---

lms/sql_tasks/tasks/report/create_from_scratch/02_entities/05_events/01_create_view.sql

For:
* https://github.com/hypothesis/report/issues/92
We didn't need this before (as we were only interested in organizations), but without rows which have no user, we miss a massive number of launches from the before times.

Include events which don't have user records

---

lms/services/application_instance.py
lms/services/lti_registration.py
lms/templates/admin/instances.html.jinja2
lms/templates/admin/registrations.html.jinja2
lms/views/admin/__init__.py
lms/views/admin/application_instance.py
lms/views/admin/lti_registration.py
lms/views/admin/organization.py
tests/unit/lms/services/application_instance_test.py
tests/unit/lms/services/lti_registration_test.py
tests/unit/lms/views/admin/__init___test.py
tests/unit/lms/views/admin/application_instance_test.py
tests/unit/lms/views/admin/lti_registration_test.py
tests/unit/lms/views/admin/organization_test.py

For both registrations and application instances:
- Search by ID.
- Searching with no criteria returns some results.
- Don't redirect to the result when there only one. It's a bit confusing, you just might want to copy something from the results table for example.
- Correctly 404 when registration doesn't exist.
- http://localhost:8001/admin/registrations/
- Search directly there, you'll get results
- Search using ID `1`
- http://localhost:8001/admin/registration/id/78789789/ is a 404 not an empty page
- http://localhost:8001/admin/instances/
- Search directly there, you'll get results
- Search using ID `100`

Admin pages tweaks

---

lms/services/document_url.py
tests/unit/lms/services/document_url_test.py

For 
- https://github.com/hypothesis/product-backlog/issues/1408
Speedgrader double-quotes URLs so we need to fix our `document_url` url param before anything else.
Change the regexp from a whitelisted set of schemas to a more general one.
See https://github.com/hypothesis/lms/pull/4710

Use a more general regexp to handle double quoting

---

lms/templates/admin/instance.html.jinja2
lms/views/admin/__init__.py
lms/views/admin/_schemas.py
lms/views/admin/application_instance.py
lms/views/admin/lti_registration.py
lms/views/admin/organization.py
tests/unit/lms/views/admin/__init___test.py
tests/unit/lms/views/admin/_schema_test.py
tests/unit/lms/views/admin/application_instance_test.py

For:
- https://github.com/hypothesis/lms/issues/4700
Add a note field in the admin pages for Application instances.
Also took the opportunity to move the admin schema to their own file in a separate commit
- Go to http://localhost:8001/admin/instance/id/2/
- Write some (funny) note
- Save
- Refresh the page, it should appear again.

Notes fields on application instances admin pages

---

lms/product/canvas/_plugin/grouping.py
lms/product/plugin/grouping.py
lms/resources/_js_config/__init__.py
lms/resources/lti_launch.py
lms/services/grouping/service.py
tests/unit/lms/product/canvas/_plugin/grouping_test.py
tests/unit/lms/product/plugin/grouping_service_test.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/services/grouping/service_test.py
tests/unit/services.py

Extend the existing grouping plugin to include a few grouping related methods from the LTIResource.
We can remove a couple of `is_canvas` and put all grouping related functionality together.
Launching these should bring the right group select in the client.
- Groups https://hypothesis.instructure.com/courses/125/assignments/1833
- Sections https://hypothesis.instructure.com/courses/125/assignments/873
- Course https://hypothesis.instructure.com/courses/124/assignments/868 
- Course https://aunltd-test.blackboard.com/webapps/blackboard/execute/blti/launchPlacement?blti_placement_id=_20_1&content_id=_36_1&course_id=_19_1
- Groups https://aunltd-test.blackboard.com/webapps/blackboard/execute/blti/launchPlacement?blti_placement_id=_20_1&content_id=_398_1&course_id=_19_1

Extend grouping plugin 

---

lms/product/factory.py
tests/unit/lms/product/factory_test.py

Not all JSON request include the product hint we rely on. If not present use the next fallback methods.
This is not a problem in production right now but as we include more product/plugins (eg D2L in follow up PRs) we'll reach for the value of `product.family` in more contexts which might not currently send the hint.
This allows using the next fallback method in the chain. Ideally we'll settle just in one or two methods but that would be bigger PR/refactor.

Fix product guessing for json request

---

lms/models/lti_params.py
lms/product/d2l/__init__.py
lms/product/d2l/_plugin/misc.py
lms/product/d2l/product.py
lms/product/product.py
lms/services/lti_grading/_v11.py
lms/services/lti_grading/_v13.py
lms/services/lti_grading/factory.py
lms/services/lti_grading/interface.py
lms/templates/admin/instance.html.jinja2
lms/views/admin/application_instance.py
lms/views/lti/basic_launch.py
tests/unit/lms/product/d2l/_plugin/misc_test.py
tests/unit/lms/services/lti_grading/_v13_test.py
tests/unit/lms/services/lti_grading/factory_test.py
tests/unit/lms/views/lti/basic_launch_test.py

For:
- https://github.com/hypothesis/lms/issues/4699
Workaround for  a behavior difference in D2L in LTI 1.1 vs 1.3.
In LTI 1.1 creating an assignment also creates the "container" to hold grades for it. In LTI1.3 the container is not created.
The fix is to create it from our end as soon as the assignment is configured. We use a setting/feature flag to control the roll out of the fix and in case D2L changes the behavior again.
- Create a new assignment in https://aunltd.brightspacedemo.com/d2l/le/content/6782/Home
- "Existing activites" -> "External Learning Tools" -> "Create new LTI link " at the bottom 
Use http://localhost:8001/lti_launches for LTI1.1
Finish the setup and launch the assignment. Note the grading bar at the top.
- Same as in LTI1.1 but use …

Auto create D2L grade items

---

docs/getting-google-credentials.md
lms/config.py
lms/static/scripts/frontend_apps/utils/google-api-client.js
lms/static/scripts/frontend_apps/utils/google-picker-client.js
lms/static/scripts/frontend_apps/utils/test/google-api-client-test.js
lms/static/scripts/frontend_apps/utils/test/google-picker-client-test.js
package.json
tests/conftest.py
tox.ini
yarn.lock

Migrate from the "gapi.auth2" module to the [Google Identity Services client library](https://developers.google.com/identity/oauth2/web/reference/js-reference) for getting an access token for use with Google Drive.
This migration fixes a browser console warning about use of deprecated libraries when clicking the "Select PDF from Google Drive" option in the assignment picker:
> Your client application uses libraries for user authentication or authorization that will soon be deprecated. See the [Migration Guide](https://developers.google.com/identity/gsi/web/guides/gis-migration) for more information.
This _may_ resolve https://github.com/hypothesis/lms/issues/4696. I was able to test in Firefox locally but testing the assignment picker in Safari locally is difficult due to mixed-content …

Migrate to Google Identity Services JS client library

---

lms/migrations/versions/c14193c4afb4_role_scope.py

For:
Based on the model changes in https://github.com/hypothesis/lms/pull/4738
And split from https://github.com/hypothesis/lms/pull/4641
Adds a new, nullable, column to hold the scope of each role.

Migration for lti_role.scope

---

lms/data_tasks/report/create_from_scratch/04_activity_counts/01_group_activity/01_create_view.jinja2.sql

For:
* https://github.com/hypothesis/report/issues/119
This adds the following metrics to the group counts table:
* annotation_shared_count
* annotation_replies_count
* launch_count
This doesn't do anything on it's own, but will help with what we need to deliver.

Add non-recursive group counts for replies and shared annotations

---

lms/templates/admin/instance.html.jinja2

Setting the value would override the setting in the DB.
Using placeholder as a hint of the presence of the value.

Fix secret field value in application instance settings

---

lms/services/organization.py
lms/templates/admin/instance.html.jinja2
lms/templates/admin/macros.html.jinja2
lms/templates/admin/organization.html.jinja2
lms/views/admin/organization.py
tests/unit/lms/services/organization_service_test.py
tests/unit/lms/views/admin/organization_test.py

Removed by mistake in instances, added also to organizations.
Play with the notes in orgs and AIs:
- http://localhost:8001/admin/org/1
- http://localhost:8001/admin/instance/id/4/

Notes field on the admin pages

---

lms/models/lti_role.py
lms/services/lti_role_service.py
tests/unit/lms/models/lti_role_test.py
tests/unit/lms/services/lti_role_service_test.py

For:
Introduces the `scope` concept in the LTIRole table and simplifies the parsing.
Note that we don't yet based any authorization decisions on this table but having this here will make that possible.
The plan is to, after we have this out for a little bit,  connect LTIUser with LTIRole and have only one role parsing/checking location in the code base.
- Launch any assignment, maybe with both a student and teacher:
- Check scopes are now in the DB
```tox -qe dockercompose -- exec postgres psql -U postgres -c "select * from lti_role where scope is not null"```
```
id |   value    |    type    | scope  
----+------------+------------+--------
7 | Learner    | learner    | course
4 …
```

Roles scope parsing

---

lms/data_tasks/report/create_from_scratch/04_activity_counts/01_groups/01_group_activity/01_create_view.jinja2.sql

For:
* https://github.com/hypothesis/report/issues/119
I think what's happening here is when we have no annotations we don't get any launches.

Ensure we get launch counts even if there are no annotations

---

lms/services/user.py
tests/unit/lms/services/user_test.py

For:
* https://github.com/hypothesis/lms/issues/4730
- Remove any that from other testing:
```tox -qe dockercompose -- exec postgres psql -U postgres -c "update \"user\" set display_name=null, email=null;"```
- Launch https://hypothesis.instructure.com/courses/125/assignments/873 both as an student and instructor.
- Check what's store for each user
```
tox -qe dockercompose -- exec postgres psql -U postgres -c "select roles,email,display_name from \"user\""
roles    |             email             |      display_name      
------------+-------------------------------+------------------------
Instructor | eng+canvasteacher@hypothes.is | Hypothesis 101 Teacher
Learner    |                               | 
(2 rows)
```

Store and update email and name in "User"

---

lms/migrations/versions/0b7391f5b1e3_backfill_user_email.py
lms/services/user.py
tests/unit/lms/services/user_test.py

For:
* https://github.com/hypothesis/lms/issues/4730
- Launch https://hypothesis.instructure.com/courses/125/assignments/873 as different users to fill up `group_info`
- Clear the "user" table  ```update "user" set display_name=null, email=null;```
- Run the migration
```hdev alembic upgrade head```
- Check the data copied over to "user":
```
tox -qe dockercompose -- exec postgres psql -U postgres -c "select roles,email,display_name from \"user\""
roles    |             email             |      display_name      
------------+-------------------------------+------------------------
Learner    |                               | 
Instructor | eng+canvasteacher@hypothes.is | Hypothesis 101 Teacher
(2 rows)
```

Backfill user emails and names from group_info

---

lms/product/product.py
lms/resources/_js_config/__init__.py
lms/resources/_js_config/file_picker_config.py
lms/routes.py
lms/services/d2l_api/client.py
lms/static/scripts/frontend_apps/components/ContentSelector.js
lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
lms/static/scripts/frontend_apps/config.js
lms/templates/admin/instance.html.jinja2
lms/views/admin/application_instance.py
lms/views/api/d2l/authorize.py
lms/views/api/d2l/files.py
tests/unit/lms/resources/_js_config/file_picker_config_test.py
tests/unit/lms/services/d2l_api/client_test.py
tests/unit/lms/views/api/d2l/authorize_test.py
tests/unit/lms/views/api/d2l/files_test.py

This PRs add some of the bolilerplate needed for authorization, basic fetching of the list of file from D2L and the bits needed on the frontend to be able to test it all together.
This PR doesn't however support:
- https://github.com/hypothesis/lms/issues/4769
- https://github.com/hypothesis/lms/issues/4768
- https://github.com/hypothesis/lms/issues/4771
It also doesn't try to find a better abstraction for files/file pickers. We can tackle that  once this lands and we have canvas, blackboard and D2L examples to build that abstraction.
- Lunch https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2184/View
There should not be a D2L files button.
- Enable the files setting on http://localhost:8001/admin/instance/id/106/
Now you'll get a D2L files button.
- Click the "D2L files …

D2L files: Authorization and API endpoints

---

lms/resources/_js_config/file_picker_config.py
tests/unit/lms/resources/_js_config/file_picker_config_test.py

Just checking "files_enabled" will be true in both d2l and blackboard at the same time.
Added a family check.
Launch as teacher:
https://aunltd-test.blackboard.com/webapps/blackboard/execute/blti/launchPlacement?blti_placement_id=_20_1&content_id=_183_1&course_id=_19_1
You'll see the D2L button in the file picker.
https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2128/View?ou=6782
(with the toggle enabled at http://localhost:8001/admin/instance/id/107/)
the D2L files button will appear.
https://aunltd-test.blackboard.com/webapps/blackboard/execute/blti/launchPlacement?blti_placement_id=_20_1&content_id=_183_1&course_id=_19_1
doesn't show the toggle
While in D2L https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2128/View?ou=6782
it does appaear.

Fix D2L file enable toggle

---

lms/models/lti_user.py
lms/validation/authentication/__init__.py
lms/validation/authentication/_bearer_token.py
lms/validation/authentication/_exceptions.py
lms/validation/authentication/_oauth.py
tests/unit/conftest.py
tests/unit/lms/security_test.py
tests/unit/lms/services/application_instance_test.py
tests/unit/lms/services/grading_info_test.py
tests/unit/lms/services/group_info_test.py
tests/unit/lms/services/user_test.py
tests/unit/lms/validation/authentication/_bearer_token_test.py
tests/unit/lms/validation/authentication/_oauth_test.py
tests/unit/lms/views/api/canvas/files_test.py

LTIUser, security policies and marshmallow schemas are all part of various authentication schemes which are all interconnected in sometimes, surprisingly ways.
This PR tries to untangle one of the pieces and simplify one of the marshmallow schemas to be more explicit about the data flow around LTIUser.
LTIUser is now in charge of it's own serialization in both BearerTokenSchema  and OAuthCallbackSchema.
There's no new behavior in this branch but to sanity check the changes make any launch that will use the sync API (which needs to get LTIUser using BearerTokenSchema)
- Launch https://hypothesis.instructure.com/courses/125/assignments/1833 successfully

Simplify `BearerTokenSchema`

---

lms/migrations/versions/debaebd4a95c_remove_enum_constraint.py
lms/models/grouping.py

For:
- https://github.com/hypothesis/lms/issues/4773
```
dev run-test-pre: PYTHONHASHSEED='551793646'
INFO  [alembic.runtime.migration] Running upgrade 0b7391f5b1e3 -> debaebd4a95c, Remove enum DB constraint.
```
```
dev alembic downgrade -1
dev run-test-pre: PYTHONHASHSEED='3452916469'
dev run-test: commands[0] | alembic -c /home/marcos/hypo/lms/conf/alembic.ini downgrade -1
INFO  [alembic.runtime.migration] Running …
```

Remove check constraint in Grouping.type

---

lms/resources/_js_config/__init__.py
lms/routes.py
lms/services/d2l_api/client.py
lms/views/api/d2l/authorize.py
lms/views/api/d2l/files.py
lms/views/helpers/_via.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/services/d2l_api/client_test.py
tests/unit/lms/views/api/d2l/authorize_test.py
tests/unit/lms/views/api/d2l/files_test.py

- https://github.com/hypothesis/h-vialib/pull/42 
- https://github.com/hypothesis/via/pull/845
- Checkout https://github.com/hypothesis/h-vialib/pull/42  h_vialib
- Checkout https://github.com/hypothesis/via/pull/845 in Via
- Install the local version of h-vialib in both Via and LMS
I've been using 
```.tox/dev/bin/pip install -e /home/marcos/hypo/h-vialib``` for this.
- Enable D2L files in http://localhost:8001/admin/instance/id/106/
- Launch a D2L assignment as a teacher and configure it as D2L assignment:
https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2184/View
- You should be able to see the contents of the file a follow the trip of URL
- via_url request to LMS to get the file which contains the `via.secret.headers`
- Via request to get the pdf, again with the …

Suppport for D2L files proxing using Via

---

lms/services/document_url.py
tests/unit/lms/services/document_url_test.py

In blackboard and D2L we rely on a parameter to point to the old id of an assignment and get its URL from the old one in the DB.
For LTI1.3 this parameter is in a different location.
- Configure the original assignment 
https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2177/View?ou=6782
for with example with: https://buildmedia.readthedocs.org/media/pdf/docs/latest/docs.pdf
You'll need something like 
`make sql` 
`truncate assignment cascade;`
if you already configured it before.
- Launch the equivalent assignment in the copied course. 
https://aunltd.brightspacedemo.com/d2l/le/content/6845/viewContent/2310/View
In `main` it will show the `configure assignment` selector.
In `course-copy-1.3` it will point already to the same PDF as the orignial.

Fix course copy assignment URL for BB and D2L in 1.3

---

lms/views/api/d2l/authorize.py
tests/unit/lms/views/api/d2l/authorize_test.py

No need to require more than we need.
The two endpoints we use:
https://docs.valence.desire2learn.com/res/groups.html#get--d2l-api-lp-(version)-(orgUnitId)-groupcategories-
https://docs.valence.desire2learn.com/res/groups.html#get--d2l-api-lp-(version)-(orgUnitId)-groupcategories-(groupCategoryId)-groups-
need the same scope.
We might be able to also remove the `core:*` one but I'll do more testing and a separate PR
Test the assignment in https://aunltd.brightspacedemo.com/d2l/le/content/6782/Home?itemIdentifier=D2L.LE.Content.ContentObject.ModuleCO-2122

Limit the scopes for groups to the minimum necessary

---

lms/services/d2l_api/client.py
lms/services/d2l_api/factory.py
tests/unit/lms/services/d2l_api/client_test.py
tests/unit/lms/services/d2l_api/factory_test.py

For:
- https://github.com/hypothesis/lms/issues/4771
- `make sql` 
- `truncate "file";` to get a blank slate.
- Reconfigure https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2177/View
- Pick the D2L files option (no need to pick any),
- Check the new data on the DB with `select * from file;`

Store D2L files into the DB

---

.eslintrc
lms/static/scripts/frontend_apps/api-types.js
lms/static/scripts/frontend_apps/components/LMSFilePicker.tsx

While working on #4769, I took the opportunity to migrate the `LMSFilePicker` component to TS, as the majority of changes are happening there and it's more convenient to not have to deal with JSDocs.

Migrate LMSFilePicker to TS

---

lms/security.py
tests/unit/lms/security_test.py

Instead of trying different locations in succession explicitly have a one to one relationship between security policy and the current path.
Google oauth routes
Go to http://localhost:8001/admin and logout (or follow the auth flow if not already logged in)
Auth in all the admin pages
Navigate around http://localhost:8001/admin
Display the configure assignment screen in non-deeplinking LMS's. 
Reconfigure https://hypothesis.instructure.com/courses/125/assignments/3930
Regular launch in all LMS's
Launch https://hypothesis.instructure.com/courses/125/assignments/3930
Oauth flow in canvas
`make sql` and then `truncate oauth2_token ;`
then re-launch Launch https://hypothesis.instructure.com/courses/125/assignments/3930
and complete the oauth flow.
Oauth flow in blackboard
Launch …

Make the security policy/path relationship explicit

---

lms/services/organization.py
lms/templates/admin/organization.html.jinja2
lms/views/admin/organization.py
tests/unit/lms/services/organization_service_test.py
tests/unit/lms/views/admin/organization_test.py

For:
* https://github.com/hypothesis/lms/issues/4861
Requires: 
* https://github.com/hypothesis/lms/pull/4866
* Create a hierarchy of orgs
* Look at them
* You should be able to navigate between and view the full hierarchy
* The organization you are on is not navigable and should be highlighted

Display organization hierarchy in the admin pages

---

lms/templates/admin/organization.html.jinja2
lms/views/admin/organization.py
tests/unit/lms/views/admin/organization_test.py

In Python 3 None has no natural sort, so the built in sort operation in Jinja2 isn't very useful over objects with attributes which can be None. To fix that we inject our own sorting method here.
In order to trigger this issue you need two organizations at the same level, where one has a string name and another has a null name. You cannot set a null name through the interface (it interprets an empty string as "don't set a name").
You can see a failing example in live here:
* https://lms.hypothes.is/admin/org/378
To set this up:
* Pick an organization to be the parent and copy the public id
* Pick two other orgs and set them to be children of that org
* Pick the id of one of the child orgs
* `UPDATE organization SET name = NULL where id=<ID>`
* On `main`: This should fail with an exception …

Fix crashes in the organization hierarchy view caused by null names

---

lms/views/api/d2l/authorize.py
tests/unit/lms/views/api/d2l/authorize_test.py

I added this initially as it was part of D2L examples in the documentation I thought it was a requirement but it's not needed at all.
---
`core:*` scopes don't seem to be a requirement for any of the endpoints we use.
See the full list at:
* https://docs.valence.desire2learn.com/http-scopestable.html
- Remove existing tokens:
```shell
tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate oauth2_token"
```
- Remove assignments to allow re-configuring:
```shell
tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate assignment cascade"
```
- Configure: https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2177/View
with either files or groups or both. 
- It will succeed.

Don't request unnecessary scopes for D2L

---

lms/services/d2l_api/_basic.py
lms/views/api/d2l/authorize.py
tests/unit/lms/services/d2l_api/_basic_test.py
tests/unit/lms/views/api/d2l/authorize_test.py

For:
- #4856 
Raise OAuth2TokenError to force a new token generation with the necessary tokens.
From the PoV of the user this just changes the name of the button where they have to click ("Try again" vs "Authorize"). It's a slightly better experience but it's also more explicit in the code around what's going on in this case. It's not a lot of code to manage it in any case.
While on `main`:
- Remove existing tokens
`tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate oauth2_token"`
- Disable files for http://localhost:8001/admin/instance/id/106/
- Configure https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2177/View?ou=6782 to use groups
This will get a token with only the scopes needed for groups.
- Re-enable files: …

Handle tokens with not all the required scopes

---

lms/routes.py
lms/templates/admin/instance.html.jinja2
lms/templates/admin/instance.new.html.jinja2
lms/templates/admin/instances.html.jinja2
lms/templates/admin/registration.html.jinja2
lms/views/admin/__init__.py
lms/views/admin/application_instance.py
lms/views/admin/lti_registration.py
tests/unit/lms/views/admin/application_instance_test.py
tests/unit/lms/views/admin/lti_registration_test.py

For:
* https://github.com/hypothesis/lms/issues/4863
This also disentangles the registration from the application instance and makes it optional.
* `/admin/instance/new/registration` has become `/admin/instance/new`
* Some of the methods have moved over to the application instance view as a result
* We now read all of the values from params instead of any path params
* This makes is possible to optionally accept a registration id (which enables 1.3 mode)
* If it's missing we use a different schema and only expect 1.1 values
* As the `POST` methods all return redirects we don't need `error_render_to_response` any more
This mixes in a refactor for a `_redirect()` which is probably better as a separate PR / commit.
The LTI 1.3 path should not be effected and should keep working:
* Visit: …

Refactor the new application instance to allow the creation of LTI 1.1

---

lms/services/application_instance.py
lms/templates/admin/instance.new.html.jinja2
lms/templates/admin/organization.html.jinja2
lms/views/admin/application_instance.py
lms/views/application_instances.py
tests/unit/lms/services/application_instance_test.py
tests/unit/lms/views/admin/application_instance_test.py

For:
* https://github.com/hypothesis/lms/issues/4863
This PR:
* Moves to kwargs for calls to `create_application_instance` to make it easier to change them
* Fixes some oddities in the test for `create_application_instance`
* Makes organization id mandatory on create
* Adds a path to jump from org to the creation of a 1.1 application instance (but not 1.3)
* Visit an org: http://localhost:8001/admin/org/1
* Press "Add New LTI 1.1 Instance"
* Notice the organization id is passed through
* Delete the id
* Try to save
* Notice you get an error about organization id
* Fill out all the required fields, but put a mangled value in organization id
* Try to save
* Notice you get a malformed public id error
* Add the original public id back again from  http://localhost:8001/admin/org/1
* Save
* It …

Make organization a required field in admin pages application instance create

---

lms/services/application_instance.py
lms/views/application_instances.py
tests/unit/lms/services/application_instance_test.py
tests/unit/lms/views/application_instance_test.py

For:
* https://github.com/hypothesis/lms/issues/4863
Requires:
* https://github.com/hypothesis/lms/pull/4886
Our internal and external application instance creation pages apply different settings as defaults. This moves those settings inside the service and ensures both will set the same value.

Move settings defaults for application instances into the service

---

lms/static/scripts/frontend_apps/api-types.js
lms/static/scripts/frontend_apps/components/LMSFilePicker.tsx
lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js

This PR enhances the `LMSFilePicker` so that it can transparently load children of the last folder in the active folderPath, without re-fetching the API.
It is done primarily to support D2L, where the full multi-dimensional file tree is returned in one go, but it opens the door to:
* Add support for other LMSs which behave like D2L, without having to change the client
* Start "caching" already loaded paths client-side, for LMSs which require querying the API for every folder, so that once the folder is opened, if the user comes back to it, we don't have to re-fetch the API (this has other considerations, of course, but would be possible with some extra changes if we wish to).
* If at some point we want file management for Canvas/Blackbopard/Others to behave consistently and make our …

Add support to load nested children in the file picker if we already have them

---

lms/services/async_oauth_http.py
tests/unit/lms/services/async_oauth_http_test.py

Emulate the behavior or `requests.Response.json()` in our async wrapper for aiohttp.
There's probably a better way to exercise this but with this diff I reckon I can prove that what I'm trying to accomplish works, the client code using responses from either `ouath_http` or `async_oauth_http` is agnostic to where the `json()` comes from.
We don't plan to a whole replacement like this.
```diff
diff --git a/lms/services/async_oauth_http.py b/lms/services/async_oauth_http.py
index b1dc06aa0..f5e5c39b2 100644
--- a/lms/services/async_oauth_http.py
+++ b/lms/services/async_oauth_http.py
@@ -45,7 +45,9 @@ async def _async_request(aio_session, method, url, **kwargs):
response.sync_text = await response.text()
-        # For json we want to emulate the behavour of the sync version, calling json …
```

Support json() for async responses

---

lms/product/canvas/_plugin/grouping.py
lms/services/canvas_api/client.py
tests/unit/lms/product/canvas/_plugin/grouping_test.py
tests/unit/lms/services/canvas_api/client_test.py

The student will only appear in Speedgrader if he did a submissions so there must be annotations for the student in *some* group.
Different edge cases around the course roster, groups memberships, etc might prevent us from finding the right group, fallback to list all of them and let the teacher find the relevant annotations.
In addition to this we have seen at least one instance of canvas not returning the groups memberships when requested, this PR should solve that.
- https://sentry.io/organizations/hypothesis/issues/3885445215/?project=259908&query=&referrer=issue-stream&sort=freq&statsPeriod=14d
- https://github.com/hypothesis/product-backlog/issues/1415
(when it comes to speed grader not sure how much of this could be skiped as is stored on canvas side, anyway giving the full process …

Return all groups in Canvas SpeedGrader if we can't find the right one

---

lms/resources/lti_launch.py
tests/unit/lms/resources/lti_launch_test.py

While working on course copy I found that we never persist the extra portion of course other than the one we set on creation.
Arguably this is a bug that we are not yet hitting but worth fixing in preparation for course copy and not mixed with the rest of the changes.
- Remove courses
`tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate grouping cascade;"`
- Check the course's extra
```
tox -qe dockercompose -- exec postgres psql -U postgres -c "select extra from grouping where type = 'course'" 
extra                                                           
------------------------------------------------                                     
{"canvas": {"custom_canvas_course_id": "125"}} …
```

Get existing course instead of trying to recreate it

---

lms/product/canvas/_plugin/grouping.py
lms/services/canvas_api/client.py
lms/static/scripts/frontend_apps/components/LaunchErrorDialog.js
lms/static/scripts/frontend_apps/components/test/LaunchErrorDialog-test.js
tests/unit/lms/product/canvas/_plugin/grouping_test.py
tests/unit/lms/services/canvas_api/client_test.py

For:
- https://github.com/hypothesis/lms/issues/4865
- Launch in the original course as a teacher:
Evertying should work as before.
- Launch in the copied course 
https://hypothesis.instructure.com/courses/518/assignments/4211
You'll get the modified error modal.
- Compare to `main`
Checkout main and launch the copied assignment, everything would appear to work but you'll be pointing to the old course's groups.
https://hypothesis.instructure.com/courses/518/assignments/4211

Handle course copy for Canvas groups

---

lms/data_tasks/report/create_from_scratch/04_activity_counts/03_organization_activity/01_create_view.sql

It appears we inadvertently changed the definition of billable users during the creation of report by missing out the requirement that a billable user be in a group with at least one annotation.
For more details see:
* https://github.com/hypothesis/report/pull/167
This leads to a larger amount of users being counted as billable as a teacher can end up including users into other periods of time simply by visiting groups.

Fix the definition of billable to include at least one annotation in the group

---

lms/migrations/versions/53f9ad3b93a4_add_a_name_to_application_instances.py

For:
* Reset your DB state:
```shell
git checkout main
make services db
``` 
* Run the update
```shell
git checkout ai-name-migration
make sql
```
* `\d+ application_instances;`
* You should see the new name column
* Run the downgrade:
```shell
hdev alembic downgrade -1
make sql
```
* `\d+ application_instances;`
* You should see the column gone

DB migration to add name to the application instance

---

lms/models/application_instance.py
lms/services/application_instance.py
lms/templates/admin/instance.html.jinja2
lms/templates/admin/instance.new.html.jinja2
lms/views/admin/application_instance.py
tests/unit/lms/services/application_instance_test.py
tests/unit/lms/views/admin/application_instance_test.py

For:
Depends on:
* https://github.com/hypothesis/lms/pull/4912
* https://github.com/hypothesis/lms/pull/4914
* `make devdata dev`
* Visit: http://localhost:8001/admin/instance/id/1/
* Name should be empty
* Save
* Name is still empty (not "None" etc)
* Fill out a name and save
* Refresh the page
* The name should remain
* Visit: http://localhost:8001/admin/instance/new
* Name field should be visible
* Press "New"
* Note name is not required
* Fill out a name and all required fields
* The name should persist

Allow editing and viewing the application instance name

---

lms/db/__init__.py
lms/db/_text_search.py
lms/services/application_instance.py
lms/services/organization.py
lms/templates/admin/instances.html.jinja2
lms/templates/admin/macros.html.jinja2
lms/views/admin/application_instance.py
tests/factories/application_instance.py
tests/unit/lms/services/application_instance_test.py
tests/unit/lms/views/admin/application_instance_test.py

For:
Depends on:
* https://github.com/hypothesis/lms/pull/4913
* Visit: http://localhost:8001/admin/instances/search
* Add a name like "Name one" to one application instance and "Name two" to another
* Try searching for name "one OR two" - You should see both
* Try searching for "NAME" - You should see both
* Try searching for "name one"  - You should only see one

Add searching for application instance by name to the admin pages

---

lms/services/blackboard_api/client.py
lms/services/file.py
tests/unit/lms/services/blackboard_api/client_test.py
tests/unit/lms/services/file_test.py

To populate the file picker in blackboard we make one API request per folder as the user navigates the tree. This is sensible as it keeps the API requests themselves small and fast.
Unfortunately for course copy we need the full tree of files to be able to:
- Find the current file that triggered the course copy process
- Guarantee that subsequent launches of other assignments in the course will also find their files without instructor intervention.
We'll use the new method only while doing course copy and keep the original `list_files` as the driver of the file picker.
We need this method for course copy but it's not used in the code base yet, one way to quickly check it is to apply a diff like:
```diff
diff --git a/lms/views/api/blackboard/files.py b/lms/views/api/blackboard/files.py …
```

New `list_all_files` method in BB API client

---

lms/routes.py
lms/views/index.py
tests/functional/ui/landing_page_test.py
tests/unit/lms/views/index_test.py

For:
* https://github.com/hypothesis/lms/issues/4864
Requires:
* https://github.com/hypothesis/lms/pull/4876
We are removing the welcome page, but curious users might still visit. We help them better by redirecting them to some relevant help.
* Visit: http://localhost:8001/
* Visit: http://localhost:8001/welcome
* Both should redirect you to: https://web.hypothes.is/help/installing-the-hypothesis-lms-app/

Redirect users who visit us directly to help pages

---

lms/services/lti_h.py
lms/services/user.py

For:
* https://github.com/hypothesis/report/issues/168
This might hopefully steer us clear from storing users for some operational reason in the future without considering the effect it might have on reporting related things.

Add some warning notes in locations related to users about report implications

---

lms/services/d2l_api/client.py
tests/unit/lms/services/d2l_api/client_test.py

~~This needs #4769 before it can be tested without messing around with different branches.~~
We need to filter out non-PDF files as those are the only ones we can proxy / annotate.
In other LMS's this is done by either the API exposing a content-type query parameter (the LMS does the filtering for us) or a content type field we can filter ourselves by.
D2L offers neither of those we we'll have to rely on the extension of the file.
- Compare the files in `Scratch area" while configuring: https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2177/View?ou=6782 and selecting D2L files
In main you'll get a `this_is_not_fine` file (which is an image).
In this branch you'll only get the PDF.

Filter out non-PDFs for D2L files

---

lms/product/blackboard/__init__.py
lms/product/blackboard/_plugin/course_copy.py
lms/product/blackboard/product.py
lms/product/plugin/course_copy.py
lms/views/api/blackboard/files.py
tests/unit/lms/product/blackboard/_plugin/course_copy_test.py
tests/unit/lms/product/plugin/course_copy_test.py
tests/unit/lms/views/api/blackboard/files_test.py
tests/unit/services.py

This PR adds the `CourseCopyPlugin`  implementation for Blackboard.
After a better understanding of #4877 I reckon this is very similar but better approach. 
Login into BB as `blackboardteacher`, `make devdata`
- Launch the original `localhost (make devdata) Blackboard Files Assignment`
https://aunltd-test.blackboard.com/webapps/blackboard/execute/blti/launchPlacement?blti_placement_id=_20_1&content_id=_39_1&course_id=_19_1
It should work as before
- Launch the original `localhost (make devdata) Blackboard Files Assignment Whose File Has Been Deleted`
https://aunltd-test.blackboard.com/webapps/blackboard/execute/blti/launchPlacement?blti_placement_id=_20_1&content_id=_80_1&course_id=_19_1
It should display the corresponding error dialog.
- Before heading to the copied assignments, reset …

Files course copy fix for Blackboard

---

lms/services/organization.py
tests/unit/lms/services/organization_service_test.py

For:
* https://github.com/hypothesis/lms/issues/4864
This does two things:
* Point out when an application instance was automatically added to an organization
* Point out when an organization was created for this process
This allows us to vet them at a later date if we want to. Currently it has no effect, but if we capture the information we can chose to act on it.

Flag auto assigned application instances

---

lms/services/application_instance.py
tests/unit/lms/services/application_instance_test.py

For:
* https://github.com/hypothesis/lms/issues/4864
Requires:
* https://github.com/hypothesis/lms/pull/4886
* https://github.com/hypothesis/lms/pull/4887
* https://github.com/hypothesis/lms/pull/4876
This has a pile of merging and cherry picking and will need rebasing when the other PRs are all merged through. The only relevant commit to review is the last one.

Make organization id a required param on application instance creation

---

lms/data_tasks/report/create_from_scratch/01_functions/01_date_functions.sql
lms/data_tasks/report/create_from_scratch/04_activity_counts/03_organization_activity/01_create_view.sql
tests/unit/lms/data_tasks/report/create_from_scratch/test_01_functions/test_01_date_functions.py

For: 
* https://github.com/hypothesis/report/issues/169
To capture more recent trends, Sales people would like to see years centered on the trailing last 12 months.
This means the most recent period would be from today to one year ago today. The next period would be the year before that etc. Technically we only want the most recent year I think, but it's actually easier for us to do them all.

Add trailing year as a timescale

---

lms/product/plugin/course_copy.py
tests/unit/lms/product/plugin/course_copy_test.py

OAuth2TokenError is a ExternalRequestError and the more general except could in some cases shallow the need for a new token or refreshing the existing one before getting a relevant answer from the API.
Catch OAuth2TokenError independently and raise it to get a new token.
I'm struggling to reproduce the exact same issue but I reckon this makes sense in isolation.
If we look at:
https://github.com/hypothesis/lms/blob/d42e45267255cc0efdab30fd4b716038deaf120b/lms/views/api/blackboard/files.py#L77-L99
If self.request.lti_user.is_instructor is True
and `self.course_copy_plugin.is_file_in_course(course_id, file_id)` is False.
The first API request might be made inside `find_matching_file_in_course`.If that returns false will raise `BlackboardFileNotFoundInCourse`. If find_matching_file_in_course …

Handle OAuth2TokenError during course copy

---

lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.js
lms/static/scripts/frontend_apps/components/GradingToolbar.tsx
lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
lms/static/scripts/frontend_apps/components/test/GradingToolbar-test.js

The "LMS" part of the component name was redundant, and the "Toolbar" suffix makes it more obvious what kind of control this is.
This might not be the final name, as we're considering adding an "edit assignment" button to this toolbar in future and displaying it even when grading is not active.

Rename LMSGrader => GradingToolbar and convert to TS

---

lms/routes.py
lms/templates/admin/instance.new.html.jinja2
lms/templates/admin/instance.upgrade.html.jinja2
lms/templates/admin/registration.html.jinja2
lms/views/admin/application_instance.py
tests/unit/lms/views/admin/application_instance_test.py

This PR splits up the journey for application instance upgrade and new 1.3 instance so they have different starting and templates. 
This makes each journey and template simpler for the user and in the code, at the cost of making the overall size bigger.
Testing new
* `make dev`
* Visit: http://localhost:8001/admin/registration/id/2/
* Click "Add LTI 1.3 instance"
* The registration you started with should appear
* The section at the bottom of the page for upgrading should not appear
* Everything here should work as normal
Testing upgrade
* Visit: http://localhost:8001/admin/registration/id/2/
* Click "Upgrade LTI 1.3 instance"
* The registration you started with should appear
* The regular "new" fields should not appear
* Press "Save"
* You should get validation errors for both …

Split out upgrading application instances as a separate activity

---

lms/static/scripts/browser_check/.babelrc
lms/static/scripts/browser_check/index.ts
lms/static/scripts/tsconfig.json

This will catch mistakes where code is unintentionally omitted from checking. It also makes the lms TS setup more similar to the client's.

Switch type-checking from opt-in to opt-out

---

package.json

This indicates to tools and readers that we don't publish this package, it just exists to track dependencies and declare metadata used by various tools. Also remove the obsolete description field and correct the incorrect license ID.
h's package.json is similar.

Mark package.json as private

---

lms/templates/admin/instance.html.jinja2
lms/templates/admin/macros.html.jinja2
lms/templates/admin/organization.html.jinja2

Caused by:
* https://github.com/hypothesis/lms/pull/4967
The name of the route changed, but I missed some places where it was referenced as I was focussed on the page itself.
This effects places that use the standard macros to list application instances which are:
* AI search page
* Organization view
* Registration view?
The following should all fail on `main` but work on this branch:
AI search page:
* Visit: http://localhost:8001/admin/instances
* Press "Search"
Registration view:
* http://localhost:8001/admin/registration/id/2/
Organization view:
* You will need to have an org in your DB, so launch something if you don't
* Look at an org

Fix broken application instance routes after refactor

---

lms/services/application_instance.py
lms/views/admin/application_instance.py
tests/unit/lms/views/admin/application_instance_test.py

For:
Requires:
* https://github.com/hypothesis/lms/pull/4913
* https://github.com/hypothesis/lms/pull/4876
This makes application instance name mandatory when creating a new one. The idea is to prevent patchy data collection in future.
* `make dev`
* Visit: http://localhost:8001/admin/instance/new
* Try and save without filling in a name
* You should get a validation error

Make application instance name mandatory on create

---

lms/views/admin/application_instance.py
tests/unit/lms/views/admin/application_instance_test.py

For:
Requires:
* https://github.com/hypothesis/lms/pull/4918
This makes application instance name mandatory when updating an existing application instance. The idea is to encourage better data quality over time.
* `make dev`
* Visit: http://localhost:8001/admin/instance/id/5/
* If that has a name search for one without
* Try saving
* You should get a name validation error
* Fill out a name
* It should save now

Make application instance name mandatory on update

---

lms/services/assignment.py
lms/services/document_url.py
tests/unit/lms/services/assignment_test.py
tests/unit/lms/services/document_url_test.py

This makes the behavior of DocumentUrlService more explicit around course copy.
Ideally the final state of this would be to have each of the possible parameter locations be part of the individual product/product plugins instead of trying them in succession. Unfortunately the exact behaviour we rely on doesn't seem to be documented in D2L / Blackboard and we might be relying in it for other smaller LMS's even if it's not documented here.
Keeping the same behaviour for now in all LMS's while making the course copy aspect of it more apparent.
These all should point to the same document after:
```tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate assignment cascade"```
```make devdata```
- Original
https://aunltd-test.blackboard.com/webapps/blackboard/execute/blti/launchPlace …

Add AssignmentService.get_copied_from_assignment

---

.eslintrc
lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.js
lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/GroupConfigSelector.js
lms/static/scripts/frontend_apps/components/JSTORPicker.js
lms/static/scripts/frontend_apps/components/LMSFilePicker.tsx
lms/static/scripts/frontend_apps/components/OAuth2RedirectErrorApp.js
lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
lms/static/scripts/frontend_apps/config.ts
lms/static/scripts/frontend_apps/services/content-info-fetcher.js
lms/static/scripts/frontend_apps/types.d.ts
lms/static/scripts/frontend_apps/utils/google-api-client.js
lms/static/scripts/frontend_apps/utils/jwt.js

It was unclear which fields in the `ConfigObject` type are present in which apps, and the optional-ness of many fields did not match the code which used them. ie. We had code testing for the presence of fields that were marked non-optional in the type.
This commit begins to clean that up by:
- Organizing fields in `ConfigObject` by the application modes they appear in
- Enabling the [@typescript-eslint/no-unnecessary-condition](https://typescript-eslint.io/rules/no-unnecessary-condition/) rule to check for conditionals that always evaluate to the truthy or falsey according to the types. This helps catch cases where a field is incorrectly marked as non-optional. [1]
- Correcting the errors found by the above lint rule, which included incorrect optional-ness for several fields as well as …

Begin to clarify which frontend config is available in different modes

---

lms/migrations/versions/64fd59a9f4b6_add_updated_last_launched_to_ai.py

For:
This PR:
* Adds a new `last_launched` column and defaults it to the last launched in the events table
* Adds a bog standard `updated` column and sets it to the max of the last launched / created
* Reset the DB
```shell
git checkout main
```
* To test this you will need to have launched some assignments.
* Visit: https://hypothesis.instructure.com/courses/125/assignments/873
* Perform the update:
```shell
git checkout ai-last-launched-migration
make sql
```
* Run:
```sql
select id, created, updated, last_launched FROM application_instances;
```
* You should see `updated` and `last_launched` columns
* Row 8 should have a more recent updated / last_launched date
* …

Add DB migration updated and last_launched dates for application instances

---

lms/migrations/versions/64fd59a9f4b6_add_updated_last_launched_to_ai.py
lms/models/application_instance.py
lms/services/application_instance.py
tests/unit/lms/services/application_instance_test.py

For:
This PR adds tracking of last launch date to the application instance service. There is a slight fudge as we count a deep link as a launch because the follow the same code path.
This is probably technically wrong, practically right. People want to know the most recent and "in-play" application instances. Something you just created would meet this brief.
Requires:
* https://github.com/hypothesis/lms/pull/4969
* Follow the notes in: https://github.com/hypothesis/lms/pull/4969
* `make sql`
* `SELECT created, updated, last_launched FROM application_instances WHERE id=8`
* Keep the values on screen to compare
* Relaunch: https://hypothesis.instructure.com/courses/125/assignments/873
* `SELECT created, updated, last_launched FROM …

Track last launched date against application instances

---

lms/templates/admin/instance.html.jinja2
lms/templates/admin/macros.html.jinja2
lms/templates/admin/organization.html.jinja2

For:
Requires:
* https://github.com/hypothesis/lms/pull/4968
* https://github.com/hypothesis/lms/pull/4969
There are some big rough edges on this one. 
The first is date formatting. We haven't tried harder anywhere else by we are showing dates to the micro-second, which is long and unhelpful.
~The second is that we are triggering horizontal scrolling in the application instance tables. I've asked support if we can drop / re-order / truncate any of the fields (https://hypothes-is.slack.com/archives/C2BLQDKHA/p1675706515773809)~. There are some extensive notes at the bottom about new more useful (and compact) columns.
These new columns have more likely break points for inserting softbreaks, so they tend to wrap and don't trigger horizontal …

Display the last launched dates on application instances admin pages

---

lms/migrations/versions/d737e73915b8_add_a_default_to_application_instance_.py

I think this was missed as we introduced the `CreatedUpdateMixin` which uses server side defaults over an existing column with Python defaults. I used an automatic alembic upgrade which didn't seem to spot the change.
This should fix problems with the create date with `make devdata`.

Add a server side (postgres) default for application instance create

---

lms/static/scripts/frontend_apps/components/GradingToolbar.tsx
lms/static/scripts/frontend_apps/components/StudentSelector.tsx
package.json
yarn.lock

This PR updates the `StudentSelector` component and makes some small adjustments to the `GradingToolbar` in advance of some UI enhancements in this area.
It:
* Converts `StudentSelector` to TSX
* Updates the `@hypothesis/frontend-shared` package such that the `Select` component is available
* Updates shared components in `StudentSelector`, including the use of `Select` and simplifies component use/layout
* Tightens and lightens some text in `GradingToolbar` to reduce vertical space used and to de-emphasize the course name a tad
User-facing changes:
* Text weight and color of assignment name, course name at left side of `GradingBar`
* Shorter overall height of `GradingBar`[^1]
* Padding and proportional icon sizes in the student-selector drop-down and adjacent `IconButton`s. These small …

Prep the `StudentSelector`, `GradingToolbar` components for UI enhancements

---

lms/models/grouping.py
lms/product/blackboard/_plugin/course_copy.py
lms/product/d2l/_plugin/course_copy.py
lms/product/plugin/course_copy.py
lms/services/__init__.py
lms/views/api/blackboard/files.py
lms/views/api/d2l/files.py
tests/unit/lms/models/grouping_test.py
tests/unit/lms/product/blackboard/_plugin/course_copy_test.py
tests/unit/lms/product/d2l/_plugin/course_copy_test.py
tests/unit/lms/product/plugin/course_copy_test.py
tests/unit/lms/views/api/blackboard/files_test.py
tests/unit/lms/views/api/d2l/files_test.py
tests/unit/services.py

This tackles a few things mentioned in reviews before we introduce the new helper for groups:
- Makes the existing helper a service. This avoids having to pass a service around.
- Moves `extra` handling to he model
- Uses sane parameter names in the empty implementation of the plugin.
No behavior changes here, as a sanity check:
- make devdata
- tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate grouping cascade;"
- Launch the scratch assignments and get a list of D2L and blackboard files in the original courses:
https://aunltd-test.blackboard.com/webapps/blackboard/execute/blti/launchPlacement?blti_placement_id=_20_1&content_id=_183_1&course_id=_19_1
https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2431/View
Try these original courses: …

Files course copy small refactors

---

lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.js
lms/static/scripts/frontend_apps/components/ContentSelector.js
lms/static/scripts/frontend_apps/components/ErrorDialogApp.js
lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/GradingToolbar.tsx
lms/static/scripts/frontend_apps/components/GroupConfigSelector.js
lms/static/scripts/frontend_apps/components/OAuth2RedirectErrorApp.js
lms/static/scripts/frontend_apps/config.ts
lms/static/scripts/frontend_apps/test/config-test.js
lms/static/scripts/frontend_apps/utils/api.js
lms/static/scripts/frontend_apps/utils/test/api-test.js

This PR adds a `useConfig` hook to simplify reading configuration embedded into the page by the backend, from within UI components. It is a simple wrapper around the previous `useContext(Config)` pattern, which checks that certain app/route-specific keys are provided and throws a sensible error if missing.
I have converted the existing uses of `useContext(Config)` to use this new hook.

Add `useConfig` hook to read frontend configuration from UI components

---

lms/static/scripts/frontend_apps/components/StudentSelector.tsx

I made a miscalculation when I created the `Select` shared component last week. It was based on this specific select interface (student drop-down) and I carried over the `h-touch-minimum` class (this sets the height of the `<select>` to 44px). The shared component itself shouldn't set an explicit height.
Add the class here to the passed `classes` so that it can be removed from the shared component.

Add explicit height to student select drop-down

---

lms/services/assignment.py
lms/services/document_url.py
tests/unit/lms/services/assignment_test.py
tests/unit/lms/services/document_url_test.py

upsert_assignment already takes lti_params as one of the mandatory parameters.
Use LTIParams in combination with the new get_copied_from_assignment to, in new assignments to copy some of the configuration of the old assignment over to he new one.
We only copy the value of `group_set_id` for now. As a result copied assignments will still be group ones after copy. They will point to an unavailable group set for now.
We don't look at document_url for now as that handled separately at the moment over in DocumentService.
- Reset assignment (once per branch):
```tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate assignment cascade"; make devdata```
- Now both in `main` and this branch (`course-copy-group-set`) try:
https://aunltd.brightspacedemo.com/d2l/le/content/6855/viewCont …

Show error for copied Blackboard and D2L groups assignments.

---

lms/routes.py
lms/templates/admin/base.html.jinja2
lms/templates/admin/instance.search.html.jinja2
lms/views/admin/__init__.py
lms/views/admin/application_instance.py
tests/unit/lms/views/admin/__init___test.py
tests/unit/lms/views/admin/application_instance_test.py

For:
* https://github.com/hypothesis/lms/issues/4998
Previously we had `GET:admin.instances` to start the search and `POST:admin.instances.search` for the callback. In all other cases we have the same route and distinguish by HTTP method. This keeps the two halves of the search more obviously intertwined. I've also named them similarly and put them next to each other.
We have `admin.instance.blah` for pretty much everything else, so I've made this `admin.instance.search` and renamed the template accordingly.

Use a single name for searching for instances which matches the pattern

---

lms/static/scripts/frontend_apps/components/BookPicker.tsx
lms/static/scripts/frontend_apps/components/test/BookPicker-test.js
yarn.lock

Part of #5013 
This PR updates the shared components in `BookPicker` (the component that renders the modal and main controls for selecting VitalSource content). The updated `Modal` component uses the updated `Panel` patten, so there are some minor differences in heading font proportions as there were in the `client` during these updates, but you'd have to be a pretty observant user to notice the change.
If the reviewer would like to test these changes:
* Ensure the local [Vitalsource Feature flag is enabled](http://localhost:8001/flags) (though I think it may be enabled by default now?). _NB_: LMS feature flags are managed in a different place than `h` feature flags.
* Create and/or launch a localhost assignment in Canvas, and get into the assignment configuration view.
* Choose the …

Update shared components in `BookPicker`

---

lms/static/scripts/frontend_apps/components/BookSelector.tsx
lms/static/scripts/frontend_apps/components/test/BookSelector-test.js

Part of #5013 
This PR updates shared components in the `BookSelector` component.
There are very minor visual changes: the dimensions of the thumbnail at left, padding and/or size of input field and submit button — a couple of pixels here or there, but nothing that most folks would notice.
This component is responsible for the contents of the book-picker modal for selecting a book (step one of two in the VitalSource picker flow) not including the modal "chrome" and buttons:
Happy path:
Sad path:
See initial steps in https://github.com/hypothesis/lms/pull/5017 (to get to the picker)
Valid VitalSource book URLs you can use are:
* `https://bookshelf.vitalsource.com/#/books/9781400847402`
* `https://bookshelf.vitalsource.com/#/books/BOOKSHELF-TUTORIAL`
During update I kicked up a shortcoming …

Update shared components in `BookSelector`

---

lms/static/scripts/frontend_apps/components/ErrorDialogApp.tsx

Migrating to TypeScript at the same time, as the component does not really need any changes related to that.
This PR is part of #5013

Migrate ErrorDialogApp to non-deprecated components from the pattern library

---

lms/product/blackboard/_plugin/grouping.py
lms/product/canvas/_plugin/grouping.py
lms/product/d2l/_plugin/grouping.py
lms/product/plugin/grouping.py
lms/resources/_js_config/__init__.py
lms/services/course.py
lms/views/api/blackboard/files.py
lms/views/api/d2l/files.py
lms/views/api/groups.py
lms/views/api/sync.py
tests/unit/lms/product/blackboard/_plugin/grouping_test.py
tests/unit/lms/product/canvas/_plugin/grouping_test.py
tests/unit/lms/product/d2l/_plugin/grouping_test.py
tests/unit/lms/services/course_test.py
tests/unit/lms/views/api/blackboard/files_test.py
tests/unit/lms/views/api/d2l/files_test.py
tests/unit/lms/views/api/sync_test.py
tests/unit/lms/views/groups_test.py

Based on `context_id` we can get the course from the DB get the relevant data from there.
`course_id` was a different ID only in canvas and the grouping plugin was already aware of that difference.
- There should not be behavior changes here but as sanity check we'll see if retrieving the group sets is still working on all LMS's
- Clear any local state in the DB: `tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate assignment,grouping cascade"; make devdata`
https://hypothesis.instructure.com/courses/125/assignments/3930/edit?name=Marcos+Assignment&due_at=null&points_possible=0
(pick the right LTI tool, configure with any document and check the `This is a group assignment`)
Getting the drop-down to populate with a list of group sets is what we are after. …

Take only `context_id` in `api.courses.group_sets.list`

---

lms/models/grouping.py
lms/product/blackboard/_plugin/grouping.py
lms/product/canvas/_plugin/grouping.py
lms/product/d2l/_plugin/grouping.py
tests/factories/grouping.py
tests/unit/lms/models/grouping_test.py
tests/unit/lms/product/blackboard/_plugin/grouping_test.py
tests/unit/lms/product/canvas/_plugin/grouping_test.py
tests/unit/lms/product/d2l/_plugin/grouping_test.py

Store group sets in Courses
Store the group sets metadata (name and ID) when we get it from the LMS's
API.
We'll later use this information to fix uses with groups and course
copy.
- Clear any local state in the DB: `tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate assignment,grouping cascade"; make devdata`
https://hypothesis.instructure.com/courses/125/assignments/3930/edit?name=Marcos+Assignment&due_at=null&points_possible=0
(pick the right LTI tool, configure with any document and check the `This is a group assignment`)
Getting the drop-down to populate with a list of group sets is what we are after.
https://aunltd-test.blackboard.com/webapps/blackboard/execute/blti/launchPlacement?blti_placement_id=_20_1&content_id=_183_1&course_id=_19_1
Same process, configure …

Store course group sets in the DB for course copy fixes

---

lms/services/application_instance.py
tests/unit/lms/services/application_instance_test.py

For:
Generally the most recently launched or updated application instances are the most relevant. 
Due to our recent DB migration the updated date has been set by the last launched date, but in future it's possible that application instances could be created which never get launched. So that these application instances are not un-order we additionally sort by updated date as well.

Sort application instance search by last launched / updated

---

lms/static/scripts/frontend_apps/components/ContentSelector.tsx
lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js
lms/static/styles/components/_FilePickerApp.scss

Refactor `ContentSelector` to replace deprecated components from the pattern library by their "next" equivalents.
This PR is part of #5013

Update `ContentSelector` to use non-deprecated components from pattern library

---

lms/templates/admin/macros.html.jinja2

For:
After slamming my head off of many different ways to try and get this done, I've settled on a slightly auto-magical system which applies formatting to many places we present information. This will get applied to:
* All table fields
* All disabled value fields
And attempts to detect a sensible way to format something based on the content it's formatting. 
The nice feature of this approach is it's all native Jinja2 and requires no Python code at all.
* Search for application instances
* Observe the create and update dates are formatted
* Look for missing last_update dates and see that they get a `-` 
* Observe the LMS URL is formatted as a link
View various other objects like application instances or organizations on their detail pages:
* …

Add formatting to dates and URLs in tables and disabled form fields

---

lms/services/jwt.py
tests/unit/lms/services/jwt_test.py

During development we have seen occassional issues where the server generates an `nbf` time that is slightly ahead of the local system ([Slack thread](https://hypothes-is.slack.com/archives/C1MA4E9B9/p1676452155666069)).  Allow a small leeway, using the same value as we have been using in h, to JWT decoding.
The error that led to this PR looks like this:

Add small leeway when decoding JWTs

---

lms/templates/admin/application_instance/new.html.jinja2
lms/templates/admin/application_instance/search.html.jinja2
lms/templates/admin/application_instance/show.html.jinja2
lms/templates/admin/application_instance/upgrade.html.jinja2

For:
* https://github.com/hypothesis/lms/issues/4998
This removes some warnings we were getting from Jinja2 about relative imports.

Fix the relative imports in the templates

---

gulpfile.mjs
lms/static/scripts/frontend_apps/components/ContentSelector.tsx
lms/static/scripts/frontend_apps/components/FilePickerApp.tsx
lms/static/scripts/frontend_apps/components/GroupConfigSelector.tsx
lms/templates/file_picker.html.jinja2

This is the first of 2 or 3 PRs to address some design technical debt in the `FilePickerApp`. The changes in this PR address the broader layout and design _structure_. A subsequent PR will address the file-picker buttons, which are, let's be honest, a little bit hideous.
This PR:
* Adds a grey backdrop to the app so that file-picker controls don't look at sea on larger screens (e.g. in BlackBoard, D2L...)
* Uses a `Card` and other common components to make design patterns more conventional
* Ensures that over-height content (but not headers or buttons) will scroll. Having said that, the full set of file-picker buttons _should_ fit in the shortest known context, the little Canvas modal, without scrolling.
* Drops in the shared `Select` component for the group-configuration step and styles …

`FilePickerApp` design updates, part 1: "Chrome"/layout structure

---

lms/models/application_settings.py
lms/services/application_instance.py
lms/templates/admin/application_instance/search.html.jinja2
lms/views/admin/application_instance.py
tests/unit/lms/models/application_instance_test.py
tests/unit/lms/models/application_settings_test.py
tests/unit/lms/services/application_instance_test.py
tests/unit/lms/views/admin/application_instance_test.py

For:
* https://github.com/hypothesis/lms/issues/5002
This PR adds the ability to:
* Search for application instances that have a given setting (regardless of content)
* Search for application instances with a specific value in that setting
* `make devdata` - We rely on the settings to get the same results
* Visit: http://localhost:8001/admin/instances/
* Press "Search"
* You should get lots of results
* Pick "vitalsource.enabled" and search again
* You should see three results
* Visit one application instance and uncheck "vitalsource.enabled" add and name and save
* Return to http://localhost:8001/admin/instances/
* Pick "vitalsource.enabled" and search again
* You should still see three results
* Now fill out truthy type values "1" "True" etc. and search
* You should only see two rows
* …

Add the ability to search for application instances by setting

---

lms/routes.py
lms/templates/admin/application_instance/create.html.jinja2
lms/templates/admin/application_instance/search.html.jinja2
lms/templates/admin/organization.html.jinja2
lms/templates/admin/registration.html.jinja2
lms/views/admin/application_instance/_core.py
lms/views/admin/application_instance/create.py
lms/views/admin/application_instance/downgrade.py
lms/views/admin/application_instance/move_organization.py
lms/views/admin/application_instance/search.py
lms/views/admin/application_instance/show.py
lms/views/admin/application_instance/update.py
lms/views/admin/application_instance/upgrade.py
lms/views/admin/application_instance/view.py
tests/functional/views/admin_test.py
tests/unit/lms/views/admin/application_instance/_core_test.py
tests/unit/lms/views/admin/application_instance/conftest.py
tests/unit/lms/views/admin/application_instance/create_test.py
tests/unit/lms/views/admin/application_instance/downgrade_test.py
tests/unit/lms/views/admin/application_instance/move_organization_test.py
tests/unit/lms/views/admin/application_instance/search_test.py
tests/unit/lms/views/admin/application_instance/show_test.py
tests/unit/lms/views/admin/application_instance/update_test.py
tests/unit/lms/views/admin/application_instance/upgrade_test.py
tests/unit/lms/views/admin/application_instance/view_test.py

For:
* https://github.com/hypothesis/lms/issues/4998
Changes in this PR:
* The existing views are split off into their own classes
* Tests have been split up too
* This results in more lines overall, but each is much smaller and easier to read
* A small base class for the views has been introduced
* This changed the `_get_ai_or_404` into a property `application_instance`
* New has been renamed to "create" to be more CRUD'y
* Expanded the functional tests to hit all of the end-points to ensure we have the new classes covered by the admin permission
The idea here is that the search is about to get more complicated, and it would be good to not bloat the already huge files.

Split the application instance admin pages into separate pages

---

lms/templates/admin/application_instance/search.html.jinja2
lms/templates/admin/macros.html.jinja2
lms/views/admin/application_instance/search.py
tests/unit/lms/views/admin/application_instance/search_test.py

For:
* https://github.com/hypothesis/lms/issues/5002
Requires:
* https://github.com/hypothesis/lms/pull/5041
This PR adds an extra column that shows up in the search results when a setting value is searched for. It displays the value as the last value.
* Visit: http://localhost:8001/admin/instances/
* Press search
* You should see the normal number of columns (without a settings value)
* Choose `vitalsource.enabled` and search again
* You should see values with a new column `vitalsource.enabled`
* Disable `vitalsource.enabled` in one application instance and search again
* You should see the value is presented as a check mark or cross according to the value
* Search using `jstor.site_code`
* You should see the results as a text value

Display the searched for setting in the application instance table

---

lms/models/__init__.py
lms/models/application_instance.py
lms/models/application_settings.py
lms/models/course.py
lms/models/grouping.py
lms/models/json_settings.py
lms/models/organization.py
lms/services/application_instance.py
lms/templates/admin/application_instance/search.html.jinja2
lms/views/admin/application_instance/_core.py
lms/views/admin/application_instance/search.py
lms/views/admin/application_instance/update.py
tests/unit/lms/models/json_settings_test.py
tests/unit/lms/product/canvas/_plugin/grouping_test.py
tests/unit/lms/views/admin/application_instance/search_test.py

For:
* https://github.com/hypothesis/lms/issues/5002
This PR:
* Splits the `ApplicationSettings` object into a specialized sub-class and a more generic `JSONSettings` class
* `JSONSettings` is used on groups and organizations
* `ApplicationSettings` is only used on the application instance
* We now list the fields which are supported directly on the object
* The admin pages uses these values
* Added the `hypothesis.auto_assigned_to_org` field
* Added a "label" which can be based on a name different from the compound key
A bit unrelated from this PR:
* Added some more notes and clarity to the `matching()` function for settings
* Visit: http://localhost:8001/admin/instances/
* Notice the drop down has "Notes" and "Auto Assigned To Organisation"
* Select "Notes" and search
* Notice that the …

Refactor `ApplicationSettings` to include a field spec

---

lms/services/application_instance.py
lms/templates/admin/application_instance/search.html.jinja2
lms/templates/admin/organization.html.jinja2
lms/views/admin/application_instance/_core.py
lms/views/admin/application_instance/search.py
tests/unit/lms/services/application_instance_test.py
tests/unit/lms/views/admin/application_instance/search_test.py

For:
* https://github.com/hypothesis/lms/issues/5054
* You will need to have launched an assignment at least once to have an organization (dev data this?)
* Visit: http://localhost:8001/admin/orgs
* Find an org with at least one application instance
* Click "Start search"
* Use this to filter the search, it should work and display the correct application instances
* Try breaking the organization id structure
* You should see warnings

Add searching by public id to the application instance admin pages

---

lms/static/scripts/frontend_apps/components/GradingControls.tsx
lms/static/scripts/frontend_apps/components/test/GradingControls-test.js

Use the browser's native API for case-insensitive comparison instead of rolling our own. The behavior should be the same as before for English locales, but the results should now be appropriate for the user's locale.
See also https://stackoverflow.com/a/2140723/434243 and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator.

Use `Intl.Collator` to sort students

---

lms/models/grouping.py
lms/product/blackboard/_plugin/course_copy.py
lms/product/canvas/__init__.py
lms/product/canvas/_plugin/course_copy.py
lms/product/canvas/product.py
lms/product/d2l/_plugin/course_copy.py
lms/product/plugin/course_copy.py
lms/services/__init__.py
lms/services/course.py
lms/views/api/sync.py
tests/unit/lms/models/grouping_test.py
tests/unit/lms/product/blackboard/_plugin/course_copy_test.py
tests/unit/lms/product/canvas/_plugin/course_copy_test.py
tests/unit/lms/product/canvas/_plugin/grouping_test.py
tests/unit/lms/product/d2l/_plugin/course_copy_test.py
tests/unit/lms/product/plugin/course_copy_test.py
tests/unit/lms/services/course_test.py
tests/unit/lms/views/api/sync_test.py
tests/unit/services.py

Handle course copy & group sets in Blackboard.
Canvas doesn't copy group set during course copy so this code shound'thave any effect there:
- Reset the DB state
`tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate grouping,assignment cascade;"; make devdata;`
- Launch a non-copied groups assignment 
Working
- Launch a copied group assignment:
https://hypothesis.instructure.com/courses/521/assignments/4311
You'll get a modal poiting to the missing group as one of the possibliilties.
We are not tackling D2L groups in this PR (to simplify these testing instructions). Just check that everything works as it was before
- Reset the DB state
`tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate …

Fix course copy for groups assignments in blackboard

---

lms/product/d2l/_plugin/course_copy.py
lms/services/course.py
tests/unit/lms/product/d2l/_plugin/course_copy_test.py
tests/unit/lms/services/course_test.py

Handle course copy & group sets in D2L.
- Reset the DB state
`tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate grouping,assignment cascade;"; make devdata;`
- Launch the original group assignment:
https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2132/View
You'll get just one group on the drop-down (the one you are a member of, `Test group 1`)
- Launch the copied groups assignment
https://aunltd.brightspacedemo.com/d2l/le/content/6861/viewContent/2524/View?ou=6861
You'll get an un-handled error with a 404
(not that this PR doesn't address that not being handled, see https://github.com/hypothesis/lms/issues/5055
You can see in the modal the failed URL containing the original group set ID, 22.
- Launch the original group assignment: …

Fix course copy for groups assignments in D2L

---

lms/models/application_instance.py
lms/resources/_js_config/__init__.py
lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.tsx
lms/static/scripts/frontend_apps/components/GradingControls.tsx
lms/static/scripts/frontend_apps/components/InstructorToolbar.tsx
lms/static/scripts/frontend_apps/components/test/GradingControls-test.js
lms/static/scripts/frontend_apps/components/test/InstructorToolbar-test.js
lms/static/scripts/frontend_apps/config.ts
lms/templates/admin/application_instance/show.html.jinja2
lms/views/lti/basic_launch.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/views/lti/basic_launch_test.py

This PR adds a `hypothesis.edit_assignments_enabled` setting to application instances and adds the plumbing needed to make the setting available to the frontend and display a placeholder "Edit" button in the instructor toolbar if enabled.
**Summary of changes:**
- Add `hypothesis.edit_assignments_enabled` setting to application instances
- Rename `grading` key in frontend config to `instructorToolbar`, and rename the associated JSConfig methods
- Rename `grading.enabled` to `instructorToolbar.gradingEnabled`
- Add `instructorToolbar.editingEnabled` field which reflects the `edit_assignments_enabled` application instance setting
- In the backend, the instructor toolbar to be displayed if we're not in Canvas and either grading is enabled or assignment editing is enabled
- In the frontend, …

Add application instance setting to enable editing assignments, and placeholder button in instructor toolbar

---

lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.tsx
lms/static/scripts/frontend_apps/components/GradingControls.tsx
lms/static/scripts/frontend_apps/services/client-rpc.js
lms/static/scripts/frontend_apps/utils/api.ts

- Convert utilities for frontend -> backend API calls to TypeScript
- Make `apiCall` generic over the return type and change the default from `any` to `unknown`. This forces callers to specify what properties they expect the result to have, if they try to use it. If they don't care about the shape of the response, they can just await the `Promise<unknown>` default.

Convert API call helpers to TS, make return type generic

---

lms/static/scripts/frontend_apps/components/LMSFilePicker.tsx
lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js

This PR updates the shared components in the `LMSFilePickerApp` component. User-visible changes are minor as we move to the updated `Modal` component and its `Panel`.
This component is best exercised through BlackBoard[^1], where you can see the contained file list in tandem with breadcrumbs.
Part of #5013
[^1]: You can get to this component from assignment configuration by clicking the "Select PDF from BlackBoard" options.

Update shared components in `LMSFilePickerApp`

---

lms/static/scripts/frontend_apps/components/ErrorDisplay.tsx
lms/static/scripts/ui-playground/components/ErrorComponents.js
lms/static/styles/components/_shared.scss

> This depends on https://github.com/hypothesis/lms/pull/5069
Migrate `ErrorDisplay` to non-deprecated components from the shared library.
There should be no visual changes. See the comparison here:
Before:
https://user-images.githubusercontent.com/2719332/220074105-b681e73b-2c07-4f15-8363-c3a209fb453a.mp4
After:
https://user-images.githubusercontent.com/2719332/220075744-271d427b-24ba-41a6-acc2-0d740eae3444.mp4

Migrate to non-deprecated components in ErrorDisplay

---

lms/migrations/versions/5f0057d6d60f_assignment_copied_from.py

Usage in https://github.com/hypothesis/lms/pull/5068
Adds the new column as nullable
We currently use this information for course copy but we don't store in on the DB. Having this on the DB will allow us to answer questions about the efficacy of our course copy fix, how often course copy is issued etc.
- Execute migration forward:
```hdev alembic upgrade head```
- Check the presence of the new column
``` tox -qe dockercompose -- exec postgres psql -U postgres -c "select copied_from_id from assignment;"```
- Execute migration backwards:
```hdev alembic downgrade -1```

Migration for Assignment.copied_form_id

---

lms/static/scripts/ui-playground/components/ToolbarPage.tsx
lms/static/scripts/ui-playground/index.js

This PR adds a new page to the local Pattern Library to use to prototype some UI in the `InstructorToolbar`.
You can see this page by checking out this branch and running `make dev`, then visiting http://localhost:8001/ui-playground/toolbar
This page is a WIP: the "full layout" hasn't been resolved yet, but there are several sketches with options for assignment-edit buttons.
NB: The fonts are tiny because LMS' local fonts are...tiny. The pattern library doesn't assert any base styling.

Add `InstructorToolbar` layout sketches to the local Pattern Library

---

lms/static/scripts/frontend_apps/components/InstructorToolbar.tsx

This PR converts the placeholder button in `InstructorToolbar` to a simple `LinkButton`. This is one of the sketched treatments in #5078 — we can swap it out for any number of things as preferred. But this tames the layout some, at least.
NB: I don't know where to go to flip on the "Edit assignment" capability so I did the implementation here by inverting the conditional that renders the button. Someone should enlighten me :).
The button looks like so:

Add simple `LinkButton` to `Toolbar` for editing assignment

---

lms/services/d2l_api/_basic.py
lms/views/api/d2l/authorize.py
tests/unit/lms/services/d2l_api/_basic_test.py
tests/unit/lms/views/api/d2l/authorize_test.py

D2L classifies API calls in different internal products (eg Learning Platform, Learning Environment) each one of them having different API versioning.
Here we explicitly use one version number per product using the last non-legacy version listed here:
https://docs.valence.desire2learn.com/about.html#principal-version-table
As a side effect of updating the version for `le` we need a new scope for the files feature. The feature is not yet released to the costumers so it's not a problem.
After merging the PR we need to upgrade: https://github.com/hypothesis/lms/wiki/D2L-API-endpoints-and-scopes-Used-by-the-Hypothesis-LMS-App
- Reset the DB state
```tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate grouping,assignment cascade;"; make devdata;```
- Exercise all our D2L …

Handle D2L api versioning per product

---

lms/security.py
tests/unit/lms/security_test.py

Tag sentry reports with the ApplicationInstance ID
Useful to find specific reports while investigating issues at a particular institution.
See a tagged event on the testing project:
https://hypothesis.sentry.io/issues/?project=5952630&query=application_instance_id%3A8&referrer=issue-list&sort=freq&statsPeriod=30d

Explicitly tag sentry reports with AI.id

---

README.md

Explicitly mention the need to trust the self signed certificate as part of the README instructions.

Document the usage of HTTPS in make dev

---

lms/static/scripts/frontend_apps/components/OAuth2RedirectErrorApp.tsx

This PR converts `OAuth2RedirectErrorApp` to TSX and updates its shared components. The only change here is that I snuck in some underlines on the inline links.
Part of #5013

Update shared components in `OAuth2RedirectErrorApp`

---

lms/static/scripts/frontend_apps/components/GradingControls.tsx
lms/static/scripts/frontend_apps/components/StudentSelector.tsx
lms/static/scripts/frontend_apps/components/test/GradingControls-test.js
lms/static/scripts/frontend_apps/components/test/StudentSelector-test.js

This PR does some refactoring of `GradingControls` and `StudentSelector` to simplify internal implementation and make `StudentSelector` behave in a more controlled manner. It eliminates a layer of abstraction (`selectedStudentIndex`) by dealing in `StudentInfo` or `StudentOption` types. The goal I'm working towards is making `StudentSelector` and `SubmitGradeForm` insomuch as possible controlled components, and `GradingControls` more like the controller. This is more conventional and will also lend itself to more convenient UI prototyping (i.e. ability to reuse the controlled components without a heavy burden of context).

Refactor `StudentSelector` to behave more like a controlled component

---

lms/static/scripts/frontend_apps/components/FileList.tsx
lms/static/scripts/frontend_apps/components/test/FileList-test.js

This PR updates the shared components in `FileList`, using the new `DataTable` component. This looks pretty much like it did before (screenshots from BlackBoard, which has nested folders and thus breadcrumbs).
Part of #5013

Update shared components in `FileList`

---

lms/services/ltia_http.py
tests/unit/lms/services/ltia_http_test.py

We've seen a high number of timeouts while hitting this endpoint, increasing the timeout to see the effect in the logs and adjust accordingly.
There's no clear way to test the timeout but:
- After the increase in the number of workers in LMS EBS I'm more confident that this won't have a negative effect
- I got one of this while testing the submissions locally so somehow Canvas does take over 10s to answer that call.
- They seem to be very frequent from this sentry search:
https://hypothesis.sentry.io/issues/?project=259908&query=is%3Aunresolved+%2Flogin%2Foauth2%2Ftoken&referrer=issue-list&sort=freq&statsPeriod=14d

Increase timeout to get LTI1.3 tokens

---

lms/views/api/grading.py
tests/unit/lms/views/api/grading_test.py

Although the views end up using LTI APIs, "grading" better reflects the focus of the views .

Rename views.lti to views.grading

---

lms/static/scripts/frontend_apps/components/BookPicker.tsx
lms/static/scripts/frontend_apps/components/ChapterList.tsx
lms/static/scripts/frontend_apps/components/test/ChapterList-test.js

This PR converts `ChapterList` (VitalSource chapter-selection UI) to TSX and updates shared components within it. To maintain the same scroll and visual behavior, some adjustments were needed on the containing `Modal` in `BookPicker`.
The interface looks like so, unchanged from before:
Part of #5013
* Configure/Edit a Canvas assignment on localhost (I hope that localhost installs have VitalSource enabled by default?) and click the 'Select book from Vitalsource' button
* Select a VitalSource book (https://bookshelf.vitalsource.com/#/books/9781400847402 is a good option)
* Then you should see the chapter-selection interface relevant to these changes

Convert `ChapterList` to TSX and update shared components

---

lms/static/scripts/frontend_apps/components/GradingControls.tsx
lms/static/scripts/frontend_apps/components/InstructorToolbar.tsx
lms/static/scripts/frontend_apps/components/StudentSelector.tsx
lms/static/scripts/frontend_apps/components/SubmitGradeForm.tsx
lms/static/scripts/frontend_apps/components/ValidationMessage.js

This PR makes some adjustments to the layout of the `InstructorToolbar` (assignment and metadata bar) displayed above assignments in LMS. Its goals are to:
* Make the layout's typography proportions, spacing and rhythm consistent across screen sizes
* Make the UI more consistent with established design patterns
* Simplify the layout implementation
* Encapsulate layout implementation to the appropriate components and ensure it's got comments where needed
Height of controls and label font size is more proportionate.
Before:
After:
Tighter vertical space usage; label font weight increased; available space given to assignment metadata instead of stretching the student select[^1].
Before:
After:
Stacked labels are more consistent with H design patterns and easier to scan; control height …

Simplify and consolidate `InstructorToolbar` and grading control layout

---

lms/static/scripts/frontend_apps/components/ErrorModal.tsx

[Linting fail in CI](https://github.com/hypothesis/lms/actions/runs/4283069533/jobs/7458146748#step:5:12) when merging PRs today; looks like changes to `ErrorModal` preceded some changes to `prettier` import ordering.

Fix import ordering in `ErrorModal`

---

lms/static/scripts/frontend_apps/components/JSTORPicker.tsx
lms/static/scripts/frontend_apps/components/test/JSTORPicker-test.js

This is it! The last component to update!
Unfortunately, the JSTOR Thumbnail API service isn't working for me today, so I wasn't able to exercise the component fully in-situ. I used some "placekitten" images to ensure that the `Thumbnail` object-fit and aspect ratio was still as we desire (to wit: fill the thumbnail space per its aspect ratio, clip off the bottom of the thumbnail image it exceeds the height of the thumbnail dimentions):
There should not be any significant visual changes here (missing thumbnail image is because of API issues):
Fixes #5013

Update shared components in `JSTORPicker`

---

lms/static/scripts/ui-playground/components/ErrorComponents.tsx

This conversion exposed the down side of contexts in (p)react: I pulled out some `@ts-ignore-nexts` in a few places because the associated configuration object type is quite complex. This is a smell, but not one I am going to deodorize right at the moment.

Convert errors pattern-library page to TSX, update shared components

---

lms/services/lti_grading/_v13.py
tests/unit/lms/services/lti_grading/_v13_test.py

The spec allows the response to be empty (204 No Content) so this was causing issues in some LMS.
Some LMS do return json all the time and others return it only for errors.
Introduced in #5098

Return the response instead of json for record_result

---

lms/events/event.py
lms/models/lti_user.py
lms/services/__init__.py
lms/services/lti_user.py
lms/validation/authentication/_bearer_token.py
lms/validation/authentication/_lti.py
lms/validation/authentication/_oauth.py
lms/views/lti/basic_launch.py
tests/factories/lti_user.py
tests/unit/lms/events/test_event.py
tests/unit/lms/models/lti_user_test.py
tests/unit/lms/services/lti_user_test.py
tests/unit/lms/validation/authentication/_bearer_token_test.py
tests/unit/lms/validation/authentication/_lti_test.py
tests/unit/lms/validation/authentication/_oauth_test.py
tests/unit/lms/views/lti/basic_launch_test.py
tests/unit/services.py

For:
Include LTIRoles in LTIUser.
The main motivation will be to later use this objects to determine the role of the current user, leveraging LTIRole instead of just matching strings:
https://github.com/hypothesis/lms/blob/668361e73615f9efc6b351bb2533433cc926d983/lms/models/lti_user.py#L39
That would centralize all role decision in LTIRole.
See a draft of that here:
- https://github.com/hypothesis/lms/pull/5123

Include LTIRoles in LTIUser

---

lms/tasks/email_digests.py
tests/unit/lms/tasks/email_digests_test.py

Nothing calls this celery task yet. In the future it will be called by an admin page and by a periodic celery task.
This celery task doesn't actually call the services to send emails yet since the services don't exist yet. For now it just logs a message instead.

Add a Celery task for sending instructor email digests

---

lms/routes.py
lms/templates/admin/base.html.jinja2
lms/templates/admin/email.html.jinja2
lms/views/admin/email.py
tests/unit/lms/views/admin/email_test.py

The page is very basic and unhelpful: it's only intended to be the quickest possible thing that I could implement that will enable me to test the email digests feature on QA and in prod. If we want to we can improve the page later when we have more time and less urgency around shipping an MVP of the feature.
Go to <http://localhost:8001/admin/email>, enter an email address, and submit the form (the default values will do for the rest of the fields). In the terminal you should see [the celery task](https://github.com/hypothesis/lms/pull/5127) logging from the celery worker process that it was called with the right values.

Add an admin page for testing the email digests feature

---

lms/resources/_js_config/__init__.py
lms/services/__init__.py
lms/services/h_api.py
lms/services/lti_h.py
tests/unit/lms/services/__init___test.py
tests/unit/lms/services/h_api_test.py
tests/unit/services.py

For:
* https://github.com/hypothesis/h/issues/7857
Requires:
* https://github.com/hypothesis/h/pull/7865
This PR:
* Adds a `get_annotations()` to the `HAPI` method.
* We also move from an older style service which accepts context and request, to a separate service factory
* This makes it more convenient to test it with the script as below
* Start all the services
* Sign into: https://hypothesis.instructure.com/courses/125/assignments/873
* As Hypothesis 101 Teacher: `eng+canvasteacher@hypothes.is`
* Make an annotation
* Copy the following script to your LMS directory:
```python
import os
from datetime import datetime, timedelta
from lms.services.h_api import HAPI
from lms.services.http import HTTPService
h_api = HAPI(
authority=os.environ['H_AUTHORITY'], …
```

Add a method for calling the `h` bulk annotation end-point

---

lms/static/scripts/frontend_apps/components/LaunchErrorDialog.tsx

Since these links appear in the middle of a sentence or paragraph, they should always be underlined for a11y reasons.
Fixes #4355

Always underline links in LTI launch error messages

---

lms/static/scripts/frontend_apps/components/ContentFrame.tsx
lms/static/scripts/frontend_apps/components/FilePickerFormFields.tsx
lms/static/scripts/frontend_apps/components/ValidationMessage.tsx

This converts the few remaining components that were still using JSDoc types to `.tsx` files.

Convert remaining Preact components to TypeScript

---

lms/services/h_api.py
lms/services/mailchimp.py
tests/unit/lms/services/h_api_test.py
tests/unit/lms/services/mailchimp_test.py

The bulk annotations API that was added to h works with h usernames not
userids (i.e. just the `"foo"` part from `"acct:foo@lms.hypothes.is"`)
both in the parameters that it accepts and in the body data that it
returns.
But the LMS app has only the full userids and not the usernames in its
DB.
So unless we change the h API to use full userids something in LMS is
going to have to do userid->username and username->userid conversion.
If we're going to be using usernames not userids in h APIs then these
userid->username and username->userid conversion methods are generally
going to be needed, and the `HAPI` service itself seems like a good
place to add them (most convenient for other code).
In the longer term we may want to change the bulk API in h to accept and
return full userids. This is …

Support full h userids in `HAPI.get_annotations()`

---

lms/static/scripts/frontend_apps/components/AppRoot.tsx
lms/static/scripts/frontend_apps/components/DataLoader.tsx
lms/static/scripts/frontend_apps/components/InstructorToolbar.tsx
lms/static/scripts/frontend_apps/components/test/AppRoot-test.js
lms/static/scripts/frontend_apps/components/test/DataLoader-test.js
lms/static/scripts/frontend_apps/index.tsx
package.json
yarn.lock

Add infrastructure to the LMS frontend to support transitioning between modes/routes after the application is initially launched, and connect up the "Edit assignment" link in the instructor toolbar to show how this can be used.
- In order to enable Back/Forwards to work, and to enable us to use off-the-shelf routing solutions, change the LMS frontend to store the current frontend "mode" or application in the URL. The initial URL structure for frontend apps is `/app/${mode}`.  The URLs are only referenced on the client side and cannot be visited directly (doing so will return a 404).
- Add [wouter](https://github.com/molefrog/wouter) dependency for routing. This is a popular minimalist solution with Preact support.
- Convert the "Edit" button in the instructor toolbar to a `<Link>` and …

Add router to LMS frontend and dummy implementation of View => Edit Assignment transitions

---

tox.ini

Moving `pip-sync-faster` execution from tox's `commands` to `commands_pre`, so that it gets executed even when `commands` is overwritten via `--run-command`.

Install dependencies pip-sync-faster in tox's commands_pre instead of command

---

lms/models/lti_params.py
lms/models/lti_user.py
tests/unit/conftest.py
tests/unit/lms/models/lti_params_test.py
tests/unit/lms/models/lti_user_test.py
tests/unit/lms/services/user_test.py
tests/unit/lms/views/api/blackboard/files_test.py
tests/unit/lms/views/api/d2l/files_test.py

For:
We already deal with parsing the raw LTI "roles" parameter in LTIRole but we are trying to parse them again in LTIParams to use them to decide authorisation in LTIUser.
With this PR we use LTIRoles instead and centralizing the role handling in LTIRole.
Quick sanity check:
- Reset the DB state
`tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate grouping,assignment,file cascade;"; make devdata`
- Launch the un-configured assignment as `aunltd.S1`
https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2431/View?ou=6782
You'll get:
```
Hypothesis assignment isn't configured
This assignment hasn't been configured yet. An instructor needs to launch the assignment to configure it.
```
- Try the same assignment as …

Use LTIRoles for authorization

---

lms/static/scripts/frontend_apps/index.tsx

Import `preact/debug` in entry point to enable Preact devtools. There also needs to be Rollup configuration to strip this import in production builds. That was [already present](https://github.com/hypothesis/lms/blob/8e46bafc3b39efeaebb1db93c3e6aec8db8c207d/rollup.config.mjs#L17) due to the config having been copied from the client repository.
**Testing:**
1. Install [Preact devtools](https://chrome.google.com/webstore/detail/preact-developer-tools/ilcajpmogmhpliinlbcdebhbcanbghmd) and pin the extension.
2. Launch an assignment from this branch.  The extension's icon should be enabled and a "Preact" tab should appear in the browser devtools when open

Enable Preact devtools in LMS frontend

---

lms/static/scripts/frontend_apps/utils/google-picker-client.ts
lms/static/scripts/frontend_apps/utils/onedrive-picker-client.ts
lms/static/scripts/frontend_apps/utils/test/google-picker-client-test.js
package.json
yarn.lock

Convert our wrappers around the Google and OneDrive file picker JS libs to TS.
**TODO:**

Convert Google and OneDrive file picker clients to TypeScript

---

lms/services/digest.py
tests/unit/lms/services/digest_test.py

Whoops. I guess this is why dataclasses are preferable to dicts.

Fix a `KeyError` in `DigestService`

---

lms/templates/admin/email.html.jinja2

I've created test courses with nice names, instructors, student,
assignments and annotations on QA and prod that match the time frame in
this PR so that the admin page's default values will produce an
interesting-looking email.

Improve email admin page defaults

---

lms/resources/_js_config/__init__.py
tests/unit/lms/resources/_js_config/__init___test.py

When using the "Edit assignment" action in the instructor toolbar after
launching an assignment, we need this information, but previously it was only
available when the file picker app was launched directly.
Trying to add it in the base case created a problem where we needed to
read LTIParams to determine the product while rendering a template about
a validation error in LTIParams in the first place.
Will just add `product` in the modes where we need it for now.

Include `product` in the config for lti launch mode

---

lms/tasks/email_digests.py
tests/unit/lms/tasks/email_digests_test.py

This is the task that will be called every morning at 5:15AM UTC (12:15AM EST) by h-periodic (h-periodic PR: https://github.com/hypothesis/h-periodic/pull/297/). It's job is to find all the instructors at participating application instances and call the other task for each instructor (in batches).
Deploying this won't actually do anything yet without the corresponding h-periodic PR. Even with the h-periodic PR deploying this won't send any emails until we enable the feature for some application instances.
1. Make sure you're running the latest version of h's `main` branch
2. [Login to Canvas](https://hypothesis.instructure.com/login/canvas) as `eng+canvasteacher@hypothes.is` and launch [localhost (make devdata) HTML Assignment
](https://hypothesis.instructure.com/courses/125/assignments/87 …

Add email digests periodic task

---

lms/static/scripts/frontend_apps/components/LaunchErrorDialog.tsx

This will make it easier to add additional props to all `ErrorModal` cases in future. I currently expect we will use this to add an "Edit assignment" link or button to all of the dialogs, if the user is an instructor.
For the `onRetry` prop, I defaulted to enabling this action, but retained the existing behavior for the many cases which disable it and added a note that we might want to revisit this in future.

Factor out common ErrorModal props in LaunchErrorDialog

---

lms/static/scripts/frontend_apps/components/AppRoot.tsx
lms/static/scripts/frontend_apps/components/FilePickerApp.tsx
lms/static/scripts/frontend_apps/components/test/AppRoot-test.js
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
lms/static/scripts/frontend_apps/config.ts

This PR extends https://github.com/hypothesis/lms/pull/5134 to fetch the real file picker app configuration using backend APIs when clicking the "Edit" link from the assignment view route. With this change, it is now possible to change the content for an existing assignment, when editing is enabled for the LMS instance.
**Testing:**
1. View https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2424/View as an instructor
2. Click "Edit" link in toolbar. You should see the assignment edit view, with the same content options as when configuring an assignment from scratch in this environment (URL, D2L file, Google Drive, OneDrive)
3. Click the URL option and enter a different PDF URL than the one that was previously used. Then click "Continue" to save changes.
4. Repeat steps 1-3 …

Fetch real file picker config when transitioning from View => Edit assignment

---

lms/static/scripts/frontend_apps/components/ContentSelector.tsx
lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js

For:
- https://github.com/hypothesis/lms/issues/4770
I used the /d2l/ folder before as a placeholder, using the new article about this now.

Link to a more concrete article for missing D2L files

---

lms/models/event.py
lms/routes.py
lms/security.py
lms/views/lti/basic_launch.py
tests/unit/lms/views/lti/basic_launch_test.py

We'll point the frontend to this endpoint on `reconfigure_assignment_config`.
This view is very similar to the creation assignment except that we do
record a new event, `EDITED_ASSIGNMENT` for the editing one.
Existing behavior, nothing should have changed but as a sanity check:
- Reset the DB state:
```shell
tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate grouping,assignment,file cascade;"; make devdata;
```
- Configure this assignment:
https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2424/View
- Enable "edit assignments" for the AI: http://localhost:8001/admin/instance/106/
- Launch https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2424/View
again, click the edit button and see a new request made to …

New endpoint to reconfigure assignments 

---

lms/static/scripts/frontend_apps/components/ErrorModal.tsx
lms/static/scripts/frontend_apps/components/LaunchErrorDialog.tsx
lms/static/scripts/frontend_apps/components/test/ErrorModal-test.js
lms/static/scripts/frontend_apps/components/test/LaunchErrorDialog-test.js

Add an "Edit assignment" link to the launch error dialog, if the user is an instructor and assignment editing is enabled. This makes it possible to fix certain errors by editing the assignment, when previously it would have required re-creating the assignment.
See https://github.com/hypothesis/lms/pull/5163#issuecomment-1463681889 for testing notes.

Support editing assignment from launch error dialog

---

lms/services/application_instance.py

This PR has two pretty un-related changes in it which both change the Application Instance service:
* We have a search based service for the most part (a service with various end-points around a powerful private search function), but one method which could have used this internal search method was instead re-implementing it. This fixes that.
* There was a suggestion in feedback in other PRs to move the code for matching emails out into the same file as the full text search helper `full_text_match`
* This PR moves it into a private helper in the same file
* We don't use it anywhere else yet, so moving it to the shared file seems premature
* This hopefully helps readability of the main search function
The two different changes are in different commits.

Misc Application Instance refactors

---

lms/static/scripts/ui-playground/components/EditAssignment.tsx
lms/static/scripts/ui-playground/index.js

This PR adds a new page in the LMS pattern library to hold sketches of UI options for the edit-assignment workflow. It:
* Captures the existing UI (roughly) for the configure-assignment workflow (i.e. configuring a new assignment)
* Provides some sketches of a possible initial view that an instructor would see after clicking into the edit-assignment workflow from a launched assignment (via the "Edit" button in the instructor toolbar).
* Gives examples to look at when we next discuss the project.
It does not:
* Address behavior in the edit-assignment workflow (yet)
* Provide cleaned-up implementation or full documentation of these interfaces
I want to keep these iterations tight so I don't end up delving too long into UI exploration at any one time. This is purposely in the "messy" stage …

Add sketches of edit-assignment workflow starting point to pattern library

---

lms/views/lti/basic_launch.py
tests/unit/lms/views/lti/basic_launch_test.py

Requires:
* https://github.com/hypothesis/lms/pull/5157
Store the ID of the group set for groups assignments and null in other cases.
This allows for edits to clear the existing value.
In `main` group_set is never sent as null, it is in this branch: `edit-assignment-display-prev-url`
So we'll rebase that to test the behavior. I din't make that the target branch as it might take longer to get that merged until the UI design is final.
- 
```shell
git checkout non-optional-group-set-extra; 
git rebase origin/edit-assignment-display-prev-url
```
- Enable editing on: http://localhost:8001/admin/instance/106/
- Launch and edit: https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2132/View
- Toggle between groups enabled/disabled. The groups drop down will change between the …

Store group_set_id in all assignments

---

lms/services/d2l_api/client.py
lms/services/d2l_api/factory.py
lms/static/scripts/frontend_apps/components/LaunchErrorDialog.tsx
lms/static/scripts/frontend_apps/components/test/LaunchErrorDialog-test.js
lms/static/scripts/frontend_apps/errors.ts
lms/static/scripts/ui-playground/components/ErrorComponents.tsx
lms/views/api/d2l/files.py
tests/unit/lms/services/d2l_api/client_test.py
tests/unit/lms/services/d2l_api/factory_test.py
tests/unit/lms/views/api/d2l/files_test.py

For:
- https://github.com/hypothesis/lms/issues/4946
- Login as `HypothesisEng.Teacher`
- Launch https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2376/View?ou=6782
- Login as `aunltd.S1`
- Launch https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2376/View?ou=6782

Different error codes for missing D2L files based on role

---

lms/product/d2l/_plugin/grouping.py
tests/unit/lms/product/d2l/_plugin/grouping_test.py

For:
- https://github.com/hypothesis/lms/issues/5055
Show a relevant error instead of an unhandled 404 error.
Launch https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2133/View as `aunltd.S1` you'll see an error dialog about the situation instead of the 404 one in `main`.

Handle group set not found for D2L learners

---

lms/resources/_js_config/__init__.py
lms/services/assignment.py
lms/views/api/sync.py
lms/views/lti/basic_launch.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/services/assignment_test.py
tests/unit/lms/views/api/sync_test.py
tests/unit/lms/views/lti/basic_launch_test.py

Non sequential IDs are less guessable and resource_link_id is scoped to one institution.
No functional changes here, just check that assignments that need the /sync API (groups, sections) still work:
https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2132/View
the payload for https://localhost:48001/api/sync
now includes the resource_link_id.

Use resource_link_id instead of assignment.id in /sync

---

lms/services/digest.py
tests/unit/lms/services/digest_test.py

Use a tuple of `models.User.id` ints instead of a tuple of `models.User` objects. This means that `DigestContext.unified_users()` and `DigestContext.unified_courses()` now don't return any ORM objects which may make them easier to optimise because they no longer need to use the SQLAlchemy ORM.
This might also be useful in future if we want to record each individual email send in the DB immediately (rather than at the end of the whole batch) because that would require us to commit a transaction after each send and by not holding on to any ORM objects we avoid any potential `DetachedInstanceError`'s caused by the transaction commits.

Change `UnifiedUser.users` to `UnifiedUser.user_ids`

---

lms/resources/_js_config/__init__.py
lms/resources/lti_launch.py
lms/services/course.py
lms/views/api/gateway.py
lms/views/lti/basic_launch.py
lms/views/lti/deep_linking.py
tests/unit/conftest.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/services/course_test.py
tests/unit/lms/views/api/gateway_test.py
tests/unit/lms/views/lti/basic_launch_test.py
tests/unit/lms/views/lti/deep_linking_test.py

[For a cleanup task on the course copy project](https://github.com/hypothesis/lms/issues/4924)
Refactor to move `LTIResrouce.course` to `CourseService`.
I don't think the line count reflects a massive simplification butit addresses a few small issues:
- `.course` being a property it needed an explanation about it's side effect nature.
- I much prefer the patter of query thing -> use thing/pass thing along. Rather than potentially caching it along the way.
- Some of the tests is JSConfig tested the same thing twice which made changes a bit of a pain. There's room for improvement there but they are  clearer now. 
It doesn't however:
- Continue moving things out of LTIResource. Had to stop somewhere.
- Tackle the conditional for Product.Family.Canvas which is now in the service
- Make a …

Refactor LTIResource.course and move it to CourseService

---

lms/services/digest.py
tests/unit/lms/services/digest_test.py

Replace `UnifiedCourse.instructors` (a list of `UnifiedUser` objects) with `UnifiedCourse.instructor_h_userids` (a list of strings). This makes the tests a bit simpler and will make some upcoming code changes simpler. We only actually use the `h_userid`'s of `UnifiedCourse.instructors` anyway.

Replace `UnifiedCourse.instructors` with `instructor_h_userids`

---

lms/templates/admin/email.html.jinja2

This uses the `request.identity.userid` which happens to be your email address as a result of our integration of Google auth.
* `make dev`
* Visit: http://localhost:8001/admin/email
* Notice your email address has filled out the email field by default

Use the logged in users email to set the default in the admin pages

---

lms/static/scripts/frontend_apps/components/ContentSelector.tsx
lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js

The D2L file URLs given in tests and comments in the frontend did not match the actual structure used. This didn't cause any functional problems because the frontend treats these URLs as opaque, except for the scheme. Having incorrect examples may cause confusion for developers in future though.

Correct example D2L file URLs in frontend comments and tests

---

lms/migrations/versions/f3d631c110bf_canvas_files_enabled.py

For:
- https://github.com/hypothesis/lms/issues/4807
- Launch a Canvas assignment to the course into the DB: https://hypothesis.instructure.com/courses/125/assignments/873
- Run the migration: `hdev alembic upgrade head`
```
INFO  [alembic.runtime.migration] Running upgrade 5f0057d6d60f -> f3d631c110bf, Make canvas files enabled an AI setting.
Application instances marked with canvas->files_enabled: 1
```

Migration to store canvas files as a setting

---

lms/models/application_instance.py
lms/resources/_js_config/file_picker_config.py
lms/services/application_instance.py
lms/static/scripts/frontend_apps/components/ContentSelector.tsx
lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js
lms/static/scripts/frontend_apps/config.ts
lms/templates/admin/application_instance/show.html.jinja2
tests/unit/lms/resources/_js_config/file_picker_config_test.py
tests/unit/lms/services/application_instance_test.py

After the canvas change the toggle for google drive  is the only one missing.
This change makes possible to disable google drive for schools that don't use it and makes the code more homogeneous around this. 
- Check the initial state after `make devdata`
```
select  settings from application_instances where id = 8;
settings                                                                                                       
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
{"jstor": {"enabled": true, "site_code": "hypothes.is"}, "canvas": {"groups_enabled": true, "sections_enabled": true}, "vitalsource": {"api_key": …
```

New toggle to allow enabling/disabling google drive files

---

lms/resources/lti_launch.py
lms/views/lti/basic_launch.py
tests/unit/lms/resources/_js_config/__init___test.py
tests/unit/lms/resources/_js_config/file_picker_config_test.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/views/lti/basic_launch_test.py

Requires:
* https://github.com/hypothesis/lms/pull/5224
I had originally thought to try removing all parts, but I think the next two are a bit harder for different reasons.
There should be no functional differences here.

Remove `is_canvas` from the `LTILaunchResource`

---

lms/views/canvas/config.py
tests/unit/lms/views/canvas/config_test.py

The JSON configuration for new LTI1.3 installs allows to explicitly assign a with and height.
This PR only changes the configuration for new LTI1.3 installs so admins following the instructions over https://web.hypothes.is/help/installing-hypothesis-in-canvas-lti-1-3-worldwide/ get the new size.
We could tackle 1.1 on the XML config in another PR but given that:
- Testing the XML path is way more complicated
- No new 1.1 installs have been created since January 
I'll leave this out of this PR.
Using a shortcut to test this:
- Loging Canvas admin in https://hypothesis.instructure.com/
- Head over https://hypothesis.instructure.com/accounts/1/developer_keys#
- Find `Hypothesis LTI1.3 (QA)`
- Toggle the selector at the top to "Paste JSON"
- Check that the changes of this PR are already …

Make the deep linking window bigger in Canvas

---

lms/static/scripts/frontend_apps/components/BookSelector.tsx
lms/static/scripts/frontend_apps/components/ContentSelector.tsx
lms/static/scripts/frontend_apps/components/FilePickerApp.tsx
lms/static/scripts/frontend_apps/components/FilePickerFormFields.tsx
lms/static/scripts/frontend_apps/components/GroupConfigSelector.tsx
lms/static/scripts/frontend_apps/components/JSTORPicker.tsx
lms/static/scripts/frontend_apps/components/OAuth2RedirectErrorApp.tsx
lms/static/scripts/frontend_apps/components/URLPicker.tsx
lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
lms/static/scripts/frontend_apps/components/test/FilePickerFormFields-test.js
lms/static/scripts/frontend_apps/components/test/JSTORPicker-test.js
lms/static/scripts/frontend_apps/components/test/URLPicker-test.js
lms/static/scripts/frontend_apps/config.ts

This updates the assignment configuration screens to display the existing assignment configuration when clicking "Edit" in the instructor toolbar, and allow the user to edit that configuration.
This PR doesn't include the latest changes from https://github.com/hypothesis/lms/pull/5215. I want to get the functional changes in this PR landed first, and then we can iterate from there.
**Summary of changes:**
- Display existing content and group configuration after clicking "Edit" button in instructor toolbar
- Add "Change" button next to content description
- When editing the content, pre-fill the URL and JSTOR picker dialogs with the existing content selection. Other picker types will require more work to support pre-filling
- Add a "Back to assignment" link at the top of the edit dialog
- …

Display existing configuration when editing an assignment

---

lms/static/scripts/frontend_apps/components/LaunchErrorDialog.tsx
lms/static/scripts/frontend_apps/components/test/LaunchErrorDialog-test.js

When editing assignments is supported in the LMS, change the error message to mention _editing_ rather than _recreating_ the assignment.
There is one caveat which is that when a _student_ sees an error message in Blackboard, the frontend doesn't know whether editing is available for instructors or not. In that case the student will see "recreate" in the error message but the instructor will see "edit". This issue will go away once we have enabled editing assignments everywhere, as we can remove the code path that mentions recreating the assignment.
Part of #5219

Change "re-create" to "edit" in several launch errors

---

lms/services/mailchimp.py
tests/unit/lms/services/mailchimp_test.py

Depends on https://github.com/hypothesis/devdata/pull/80/
Now that we have a Mailchimp API key in dev don't bother with handling the case of a missing API key. Just let the `mailchimp_transactional` client crash when you try to send an email.
Unfortunately this doesn't result in a nice error message. We do get a nice JSON error response from the Mailchimp API with "Invalid API key" as the error message. But Mailchimp's Python client swallows this error response and completely hides it, and then raises a `PicklingError` instead. This appears to be a bug in the Mailchimp Transactional Python client's error handling.
As long as you've run `make devdata` this should never happen, but it might happen if someone is setting up a new production instance of LMS and doesn't set `MAILCHIMP_API_KEY`. …

Remove handling of missing Mailchimp API keys

---

lms/services/digest.py
lms/services/mailchimp.py
tests/unit/lms/services/digest_test.py
tests/unit/lms/services/mailchimp_test.py

Fixes https://github.com/hypothesis/lms/issues/5276
**Problem:** `DigestService` loops over a batch of users calling `MailchimpService.send_template()` for each user. Currently there's no handling of any exceptions raised by `MailchimpService.send_template()` so if trying to email one user raises an exception then it'll crash out of the `for` loop and none of the following users in the batch will get their digest emails either.
**Solution:** catch any exceptions from `MailchimpService` and continue through the `for` loop, but also log the exception and report it to Sentry so that we don't swallow Mailchimp errors silently.
1. Create a free Sentry account for yourself and a project within that account and then set the `SENTRY_DSN` envvar:
```terminal
$ export …
```

Handle Mailchimp API errors when sending email digests

---

lms/models/email_unsubscribe.py
lms/services/digest.py
lms/services/email_unsubscribe.py
lms/services/mailchimp.py
lms/tasks/email_digests.py
tests/unit/lms/services/digest_test.py
tests/unit/lms/services/email_unsubscribe_test.py
tests/unit/lms/services/mailchimp_test.py
tests/unit/lms/tasks/email_digests_test.py

- Tweak the sending code to use a new test template:
```diff 
--git a/lms/services/digest.py b/lms/services/digest.py
index 37c4b6f69..a87fdffd5 100644
--- a/lms/services/digest.py
+++ b/lms/services/digest.py
@@ -72,7 +72,8 @@ class DigestService:
continue
self._mailchimp_service.send_template(
-                "instructor-email-digest",
+                # "instructor-email-digest",
+                "test-unsubcribe-link",
self._sender,
recipient=EmailRecipient(to_email, unified_user.display_name),
template_vars=digest,
```
- Check the new template 
https://mandrillapp.com/templates/code?id=test-unsubcribe-link
The HTML is copied from GH simple emails and the wording from mailchimp unsubscribe links.
- Go over http://localhost:8001/admin/email and kick-off a task
- Check the values in …

Use EmailUnsubscribeService for digest emails

---

lms/tasks/email_digests.py
tests/unit/lms/tasks/email_digests_test.py

The `send_instructor_email_digests_tasks()` task does a DB query to retrieve the `h_userids`, splits them into batches, and then does a `for` loop to schedule instances of the `send_instructor_email_digests()` task for each batch:
https://github.com/hypothesis/lms/blob/95bdcdb3efe9ec88c7aab3f0f1c89e1ae12b8c2b/lms/tasks/email_digests.py#L17-L72
This could fail in a couple of ways:
1. The DB query could raise an exception (for example perhaps Postgres is overloaded and the query times out)
2. One of the Celery calls could raise an exception (for example perhaps CloudAMQP has an outage)
In either case the task could fail to schedule `send_instructor_email_digests()` instances for one or more of the batches of `h_userids`, meaning that users would not receive their email digests.
Catch any …

Add retries to the `send_instructor_email_digests_tasks()` task

---

lms/migrations/versions/9f1e88367596_email_unsubscribe.py

`hdev alembic upgrade head`
```
dev run-test-pre: PYTHONHASHSEED='145102197'
INFO  [alembic.runtime.migration] Running upgrade f3d631c110bf -> 9f1e88367596, Add the email_unsubscribe table.
```
`hdev alembic downgrade -1`
```
dev run-test-pre: PYTHONHASHSEED='1070460438'
dev run-test: commands[0] | alembic -c /home/marcos/hypo/lms/conf/alembic.ini downgrade -1 …
```

Migration for the `email_unsubscribe` table

---

docs/configuration.md
lms/config.py
lms/models/__init__.py
lms/models/email_unsubscribe.py
lms/routes.py
lms/services/__init__.py
lms/services/digest.py
lms/services/email_unsubscribe.py
lms/services/mailchimp.py
lms/tasks/email_digests.py
lms/templates/base.plain.html.jinja2
lms/templates/email/unsubscribe_error.html.jinja2
lms/templates/email/unsubscribed.html.jinja2
lms/templates/message.html.jinja2
lms/views/email.py
tests/conftest.py
tests/factories/__init__.py
tests/factories/email_unsubscribe.py
tests/unit/lms/services/digest_test.py
tests/unit/lms/services/email_unsubscribe_test.py
tests/unit/lms/services/mailchimp_test.py
tests/unit/lms/tasks/email_digests_test.py
tests/unit/lms/views/email_test.py
tests/unit/services.py
tox.ini

Adds the basic model, service and view to handle email unsubscribed.
Needs: https://github.com/hypothesis/lms/pull/5261
- Tweak the sending code to use a new test template:
```diff 
--git a/lms/services/digest.py b/lms/services/digest.py
index 37c4b6f69..a87fdffd5 100644
--- a/lms/services/digest.py
+++ b/lms/services/digest.py
@@ -72,7 +72,8 @@ class DigestService:
continue
self._mailchimp_service.send_template(
-                "instructor-email-digest",
+                # "instructor-email-digest",
+                "test-unsubcribe-link",
self._sender,
recipient=EmailRecipient(to_email, unified_user.display_name),
template_vars=digest,
```
- Check the new template 
https://mandrillapp.com/templates/code?id=test-unsubcribe-link
The HTML is copied from GH simple emails and the wording …

New unsubscribe mechanism for digest emails

---

lms/views/email.py
tests/unit/lms/views/email_test.py

For: 
https://hypothesis.sentry.io/issues/4090125145/?referrer=slack
Without the default we get:
```
ValueError: Could not convert return value of the view callable function
lms.views.email.unsubscribe into a response object. The value returned was {}.
You may have forgotten to define a renderer in the view configuration.
```
even if the template does indeed render correctly but we get a 500 error.
With this change we get the same response but with a 200 instead.

Add a default renderer instead of using override_renderer

---

lms/static/scripts/frontend_apps/components/BookPicker.tsx
lms/static/scripts/frontend_apps/components/ChapterList.tsx
lms/static/scripts/frontend_apps/components/test/ChapterList-test.js

This PR updates the `BookPicker` modal from `Modal` to the newer `ModalDialog` to benefit from improved behavior. The contents of this modal show either a "book selector" or a list of chapters in the selected book.
Once the modal was updated and had focus trapping and routing, it was more obvious that we needed to route focus for the "chapter selection" step, so that has been added here as well — the table of chapters receives focus so that the user can navigate more quickly.
Part of #5293
No visual/design changes, just behavior.
On this branch, create or edit an assignment locally in an LMS with VitalSource enabled (I believe it is enabled for our canvas instance, e.g.). Click into the "VitalSource book" option.

Update book-picker modal and focus routing

---

lms/static/scripts/frontend_apps/components/URLPicker.tsx

This PR updates `URLPicker` to use the newer `ModalDialog` to get focus-trapping and keyboard-navigation and other behavioral improvements. No design changes, just behavior changes.
Part of #5293
Create/configure an assignment on this branch and choose the "Enter URL of web page or PDF" option. Focus should be trapped in the modal, and clicking or tabbing or focusing outside of the modal should not close it.

Update modal in `URLPicker` to use `ModalDialog`

---

lms/static/scripts/frontend_apps/components/JSTORPicker.tsx

Another part of #5293 
This PR uses `ModalDialog` in the `JSTORPicker`
Create or edit an assignment in an instance with JSTOR enabled. Select content via "Select JSTOR Article" button. Modal dialog should trap focus, not close on external click.

Update modal in `JSTORPicker` to `ModalDialog`

---

lms/static/scripts/frontend_apps/components/LMSFilePicker.tsx

This PR updates `LMSFilePicker` to use updated `ModalDialog` to get its accessibility and keyboard-navigation enhancements.
Part of #5293 
A nice follow-up at some point would be to put initial focus on the table of files.
Create or configure an assignment in Canvas with Canvas files enabled. Select the "PDF from Canvas" content option. The modal should trap focus and not close when clicks or focuses happen outside of it.

Update `LMSFilePicker` to use `ModalDialog`

---

lms/static/scripts/frontend_apps/components/ErrorModal.tsx
lms/static/scripts/frontend_apps/components/test/ErrorModal-test.js

All right, this is the last modal update! This PR updates `ErrorModal` to use `ModalDialog` for its improved behavior.
You can explore this by visiting the [LMS errors pattern library page](http://localhost:8001/ui-playground/errors) on this branch (easy testing!). Most of the modal examples here don't have a proper `onClose` handler, but the first example under "ErrorModal" does. 
The other modal examples on this page should show focus trapping and keyboard navigation is working.
Note that `summary` elements (e.g. the "Error Details" sections) are not part of the tab navigation sequence. This is probably not great, but would need to be fixed in the hook in `frontend-shared` that generates the tab sequence. And I'll do a little research on it beforehand.
Part of #5293

Use `ModalDialog` in `ErrorModal`

---

lms/models/application_instance.py
lms/resources/_js_config/file_picker_config.py
lms/services/canvas_api/client.py
lms/services/canvas_api/factory.py
lms/static/scripts/frontend_apps/components/ContentSelector.tsx
lms/static/scripts/frontend_apps/config.ts
lms/templates/admin/application_instance/show.html.jinja2
lms/views/api/canvas/authorize.py
tests/unit/lms/resources/_js_config/file_picker_config_test.py
tests/unit/lms/services/canvas_api/client_test.py
tests/unit/lms/services/canvas_api/factory_test.py
tests/unit/lms/views/api/canvas/authorize_test.py

- Reconfigure https://hypothesis.instructure.com/courses/125/assignments/4682/edit?name=Testing+creation+-+marcos&due_at=null&points_possible=0 
- Enable folder support: http://localhost:8001/admin/instance/8/
- Reconfigure https://hypothesis.instructure.com/courses/125/assignments/4682/edit?name=Testing+creation+-+marcos&due_at=null&points_possible=0 check the folder structure there matches the one at: https://hypothesis.instructure.com/courses/125/files/folder/Foo

Add support for Canvas folders in the LMS filepicker

---

lms/tasks/celery.py

Use a durable RabbitMQ exchange and queue so that any messages are persisted to disk and will survive after a RabbitMQ crash or restart.
A durable exchange and queue may not have been necessary when all we had was the `rotate_keys()` periodic task (although it wouldn't have done any harm) but now that we have the email digests tasks we want our messages to survive RabbitMQ crashes or restarts. We don't want queued messages to be lost and emails not to be delivered.
In general we should set `durable=True` unless we have a good reason not to: it generally won't do any harm and often it will be important not to lose messages in RabbitMQ restarts.
In order for messages to actually be persisted to disk the `delivery_mode` of the message also needs to be set to `2`. Celery does this by default …

Use a durable RabbitMQ exchange and queue

---

lms/data_tasks/report/refresh/01_entities_refresh.sql

For:
* https://hypothesis.sentry.io/issues/4110010386/?project=259908&referrer=slack
* https://github.com/hypothesis/report/issues/194
This was a materialized view, but now it's not, and so can't be updated.

Remove the update to `users_sensitive` which is now a view

---

lms/models/lti_user.py
tests/unit/lms/models/lti_user_test.py

Our `is_learner` check doesn't exclude teachers so every teacher that also has a role we identify as a student will cause issues.
This situation is caused by:
- Legit teacher and instructor roles in the same course. Now we check the scope of the roles so a teacher that's also a student *in the same course* is probably a very rare occurrence.
- Unknown/un-mapped roles are always mapped to "learner" which is the less privileged role. The `is_learner` check will see those and return true. 
Other possible fixes:
- We could change the order of the conditionals listed below. Once the change is made it wouldn't be very clear that the ordering is relevant (ie checking is_instructor before is_learner). I reckon it would be easy to reintroduce bugs that way.
- Leave unknown roles as unmapped or map …

Explicitly exclude teachers from the is_learner check

---

lms/tasks/celery.py

I'm pretty sure this doesn't do anything: we don't have a results backend configured. If we did have one I don't see why we'd change Celery's default here.

Remove unnecessary `task_ignore_result` setting

---

lms/tasks/celery.py

`worker_prefetch_multiplier` is `4` by default and the docs say this is usually a good choice unless you have very long-running tasks. We don't have very long-running tasks (nor should we: they'd be too likely to get terminated mid-task by a deployment or autoscaling down and have to begin again from the start with another worker). I don't see any reason to change Celery's default here:
https://docs.celeryq.dev/en/stable/userguide/configuration.html#worker-prefetch-multiplier
`worker_disable_rate_limits` disables all rate limits even if tasks have explicit rate limits set. I see no reason why we would want to do this:
https://docs.celeryq.dev/en/stable/userguide/configuration.html#worker-disable-rate-limits

Remove some unnecessary Celery worker settings

---

lms/models/application_instance.py
lms/resources/_js_config/__init__.py
lms/templates/admin/application_instance/show.html.jinja2
lms/views/lti/basic_launch.py
tests/unit/lms/views/lti/basic_launch_test.py

**Don't merge until we have the green light to enable this for all schools.**
For:
- https://github.com/hypothesis/lms/issues/5195
Show the editing controls for all teachers in non-Canvas launches.
Doing this as a code change instead of a migration as it simplifies the code a bit and also allows an hypothetical rollback (a revert in this case) to go back to the exact same state relying on the DB data.
- In `main` disable editing for http://localhost:8001/admin/instance/106/
- Switch to this branch, check the option is no longer configurable in the admin
- Launching https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2132/View?ou=6782 as an instructor show the editing option.

Enable assignment editing for all institutions

---

lms/static/scripts/ui-playground/components/EditAssignment.tsx

This PR is a response to some discussion we had related to https://github.com/hypothesis/lms/pull/5157
It:
* Updates wording on the "commit" button action in the initial view to be more clear that it is a save/commit action
* Updates description of available actions on initial view
* Adds a section to hold sketches of "re-select content" view, with some notes about available actions in that UI
Not done yet: there are still problems to solve with the "re-select content" view. Coming soon. Trying to keep this stuff bite-sized.
See updates at http://localhost:8001/ui-playground/edit-assignment
Part of #5141 
Part of #5142

Update pattern-library sketches for edit-assignment workflow

---

lms/templates/admin/base.html.jinja2

For:
- https://github.com/hypothesis/lms/issues/5012
Default to the same value as the `header` block.
http://localhost:8001/admin/instances/
http://localhost:8001/admin/instance/106/
http://localhost:8001/admin/instance/create
http://localhost:8001/admin/registrations/
http://localhost:8001/admin/registration/id/3/
http://localhost:8001/admin/instance/upgrade?lti_registration_id=3
http://localhost:8001/admin/orgs
http://localhost:8001/admin/org
http://localhost:8001/admin/org/1

Include meaningful titles for the admin pages

---

lms/services/__init__.py
lms/services/digest.py
lms/tasks/mailchimp.py
tests/unit/lms/services/digest_test.py
tests/unit/lms/tasks/mailchimp_test.py
tests/unit/services.py

There are two reasons for doing this:
1. It makes the code in https://github.com/hypothesis/lms/pull/5347 simpler because the Celery task doesn't have to commit multiple transactions in a single task run
2. It makes for a large number of small tasks (one per email to be sent, one Mailchimp API call per task run) rather than a single large task (a single instance of a task looping over a list of emails to send and calling the Mailchimp API once for each).
Lots of small tasks is better than one large task for a few reasons:
1. It avoids hogging a Celery worker for a long time, allows other types of tasks to be interleaved
2. A worker executing a long-running is more likely to get terminated mid-task. If late acknowledgement is used Rabbit will re-deliver the task to another worker which …

Split email sending into a separate Celery task

---

lms/models/__init__.py
lms/models/task_done.py
lms/services/digest.py
lms/services/mailchimp.py
lms/tasks/email_digests.py
lms/tasks/mailchimp.py
lms/views/admin/email.py
tests/unit/lms/services/digest_test.py
tests/unit/lms/services/mailchimp_test.py
tests/unit/lms/views/admin/email_test.py

Fixes https://github.com/hypothesis/lms/issues/5346.
Depends on https://github.com/hypothesis/lms/pull/5331 and https://github.com/hypothesis/lms/pull/5337.
As discussed in https://github.com/hypothesis/lms/discussions/5284 use a new `task_done` DB table to avoid sending duplicate emails.
This isn't perfect because a Celery worker could be terminated after sending an email but before committing its transaction to the `task_done` table, in which case a duplicate email could still be sent. But it's probably good enough and probably the best we can do.
1. Re-create your DB in order to get the `task_done` table from the models in this PR:
```terminal
make services args=down && make services && make devdata
```
2. Log in to https://hypothesis.instructure.com/ as the …

Use the DB to avoid sending duplicate emails

---

rollup-tests.config.mjs
yarn.lock

Get rid of a warning during tests, by adding `context: 'void(0)'` to rollup config.
The difference when running tests is this:
```diff
[09:56:30] Using gulpfile ~/work/lms/lms/gulpfile.mjs
[09:56:30] Starting 'test'...
[09:56:30] Starting 'build-css'...
[09:56:30] Starting '<anonymous>'...
[09:56:30] Building test bundle... (53 files)
[09:56:32] Finished 'build-css' after 1.88 s
- [09:56:40] Rollup warning: node_modules/@hypothesis/frontend-shared/lib/components/transition/Slider.js (86:5) The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten (https://rollupjs.org/guide/en/#error-this-is-undefined)
[09:56:43] Starting Karma...
```

Add context: 'void(0)' in tests rollup config

---

.github/workflows/deploy.yml

Add patterns to be ignored on deploy pipeline for FE tests and test-related configs.
This will help us avoid a deployment to be triggered when only non-production files have been changed.

FE deploy paths-ignore

---

lms/static/scripts/frontend_apps/components/ContentSelector.tsx
lms/static/scripts/frontend_apps/components/URLFormWithPreview.tsx
lms/static/scripts/frontend_apps/components/YouTubePicker.tsx
lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js
lms/static/scripts/frontend_apps/components/test/URLFormWithPreview-test.js
lms/static/scripts/frontend_apps/components/test/YouTubePicker-test.js
lms/static/scripts/frontend_apps/errors.ts
lms/static/scripts/frontend_apps/utils/test/youtube-test.js
lms/static/scripts/frontend_apps/utils/youtube.ts

> This PR is part of https://github.com/hypothesis/lms/issues/5328
This PR adds a new content picker for YouTube videos, which is based in `JSTORPicker`.
- Design of the content selectors. This just adds a new button as a simple entry point until the whole section is redesigned.
- Implement the logic after a valid YouTube URL has been set. That will come on a follow-up PR.
- Check out this branch.
- Enable the feature flag by going to `http://localhost:8001/admin/instance/{instance_id}/` and checking **YouTube enabled**:
- Open an assignment pointing to your localhost lms instance
- Click on `Select video from YouTube`.
- Verify that an error is displayed if the URL is not any of the known YouTube video patterns.
- Verify a dummy thumbnail, title and channel name is displayed when a valid …

Youtube picker (JSTORPicker-based)

---

.github/workflows/deploy.yml

Some of the glob expressions in the `paths-ignore` for the deploy workflow are only taking into consideration the first directory level.
This changes that so that they are recursively ignored.

Make sure directories ignored for deployment workflow are ignored recursively

---

lms/product/canvas/_plugin/course_copy.py
lms/services/canvas.py
tests/unit/lms/product/canvas/_plugin/course_copy_test.py
tests/unit/lms/services/canvas_test.py

Adapt the course copy fix for Canvas to the CourseCopyPlugin
format without any functional changes.
It should be possible to eventually share more code with the rest of the
LMS's but that will require data migrations and more careful testing.
This change aligns the code location so it matches the expectations set
by the plugin.
Nothing should have changed regarding Canvas files but lets do a sanity check of the process:
- Reset you DB state
tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate grouping,assignment,file cascade;"; make devdata;
- Launch a copied assignment that uses Canvas files
https://hypothesis.instructure.com/courses/521/assignments/4305
It will fail
- Get the list of files from the orignial course
Configure an assignment there, pick the localhost tool …

Adapt Canvas course copy fix to follow CourseCopyPlugin

---

lms/services/jstor/factory.py
tests/unit/lms/services/jstor/factory_test.py

Getting the app settings already implicitly relies on lti_user existing to get the right application instance.
Simplify the code eliminating the conditional.
(Prompted by the WIP refactor in https://github.com/hypothesis/lms/pull/5334)

Don't guard against no user for JSTOR tracking ID

---

lms/services/assignment.py
tests/unit/lms/services/assignment_test.py

`resource_link_id_history` points to the resource link id the current one
was copied from.
For copies of a copy the LMS might include a comma separated list of ID.
From the spec https://www.imsglobal.org/spec/lti/v1p3#lti-resourcelink-variables
```
ResourceLink.id.history
A comma-separated list of URL-encoded resource link ID values representing the ID of the link from a previous copy of the context;
the most recent copy should appear first in the list followed by any earlier IDs in reverse chronological order.
If the link was first added to the current context then this variable should have an empty value.
```
Needs:
- https://github.com/hypothesis/devdata/pull/82 merged
- Reset your local assignments
`tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate assignment …

Handle multiple entries on the _history LTI parameter

---

lms/tasks/email_digests.py
tests/unit/lms/tasks/email_digests_test.py

There's no need for the task to catch exceptions raised by
`send_instructor_email_digests.apply_async()`. This used to make more
sense because `send_instructor_email_digest_tasks()` used to manually
retry itself with only those `h_userids` for which
`send_instructor_email_digests.apply_async()` hadn't already been
successfully scheduled. But now that we use the `task_done` table to
avoid sending duplicate emails
(https://github.com/hypothesis/lms/pull/5347) this is less necessary:
If a call to `send_instructor_email_digests.apply_async()` fails then
`send_instructor_email_digest_tasks()` will raise, breaking out of its
`for` loop, and Celery will retry the whole
`send_instructor_email_digest_tasks()` call again. Hopefully on the
second or third attempt it'll make it all the way through …

Simplify `send_instructor_email_digest_tasks()`

---

lms/services/exceptions.py
lms/services/lti_grading/_v13.py
tests/unit/lms/services/lti_grading/_v13_test.py

We can't detect this situation before we try to submit the grade but we can detect the error returned by the grading API.
We could take other actions from here but for now we are only detecting the situation.
We return a new error code that the frontend can't yet handle differently.
D2L: https://hypothesis.sentry.io/issues/3971708774/events/1a08561d4c7e4b38b8f226b34a1054f4/?project=259908
BB: https://hypothesis.sentry.io/issues/3971708774/events/5e01537778014ecd89fce8af70cd7e75/?project=259908
- Needs  https://github.com/hypothesis/devdata/pull/83 merged
- `make devdata`
- Login an instructor and try to grade "Student Not In Courses" for this assignment: https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2424/View?ou=6782
- You'll get an error dialog. Note this won't have …

Handle students no longer in the course while scoring them

---

lms/static/scripts/ui-playground/components/ToolbarPage.tsx
yarn.lock

This PR:
* Bumps `@hypothesis/frontend-shared` to v6.2.0 to fix a regression in non-closeable Dialogs
* Updates a local pattern-library page to use `ModalDialog` instead of deprecated `Modal`
Before (note non-functioning close button):
After:

Update `frontend-shared`; don't use deprecated `<Modal>`

---

lms/tasks/celery.py

Fixes https://github.com/hypothesis/lms/issues/5428.
This is to protect against Celery task runs hanging forever blocking a Celery worker and preventing Celery retries from kicking in.
Arguably this might actually shoot us in the foot: in [yesterday's incident with the email digests tasks](https://docs.google.com/document/d/1kLX8qEjik3K8kwL-g_p_ovKwSFehQ5if4A5iXu6qp1g/) we saw a task that should only take a few seconds take instead 5.5hrs but the task then did complete successfully. If we had a task time limit (of less than 5.5hrs) then Celery would have killed the task and, assuming the issue was persistent so that each of Celery's two retries of the task would also have tried to take 5.5hrs, Celery would have killed the two retries and the task would never have completed at all.
On the …

Add Celery task time limits

---

lms/config.py
lms/routes.py
lms/services/youtube.py
lms/views/api/youtube.py
tests/unit/lms/routes_test.py
tests/unit/lms/services/youtube_test.py
tests/unit/lms/views/api/youtube_test.py

This PR adds the basic functionality to proxy requests to YouTube API to get video information.
This is done 
1. Check out this branch
2. Run `make devdata` to get the API key
3. Run the following request, and check that you get proper video information
```shell
curl --request GET \
--url http://localhost:8001/api/youtube/videos/EU6TDnV5osM \
--header 'Authorization: Bearer <add_token_here>'
```
It should produce a response like this:
```json
{
"image": "https://i.ytimg.com/vi/EU6TDnV5osM/mqdefault.jpg",
"title": "Hypothesis and Atlassian New Partnership Announced at the Team23 Conference",
"channel": "Hypothesis",
"duration": "PT2M20S"
}
```
(feel free to try other IDs and see the result)
4. Run the same command but providing an invalid video ID, and check the response looks like this: …

Youtube api proxy

---

lms/static/scripts/frontend_apps/components/Breadcrumbs.tsx
lms/static/scripts/frontend_apps/components/ErrorDialogApp.tsx
lms/static/scripts/frontend_apps/components/ErrorDisplay.tsx
lms/static/scripts/frontend_apps/components/GroupConfigSelector.tsx

This little PR updates usages of `Link` and `LinkButton` components to ensure they always set the `underline` prop. This will allow us to change the default value of that prop for future uses without disrupting any existing styling.

Always set `underline` prop for `Link`, `LinkBase`

---

lms/views/api/grading.py
tests/unit/lms/views/api/grading_test.py

Part of the effort to fix and reduce noise of exceptions around grading:
- https://github.com/hypothesis/product-backlog/issues/1305
Avoid any artifacts caused by float point arithmetic.
Should fix errors like: https://hypothesis.sentry.io/issues/3971708774/events/ad948f09096c4b8d957ce7c9f9960605/?project=259908
```
Response(status_code=400, reason='Incorrect score received{"scoreMaximum": 1, "scoreGiven": 0.7000000000000001
```

Round scores submitted to the grading API.

---

lms/services/ltia_http.py

Help debug some issues we are seeing where the LTIA service is returning a 200 response but with no JSON.
See: https://hypothesis.sentry.io/issues/4209873926/?project=259908&referrer=slack

Log non-JSON responses from LTIA token requests

---

lms/resources/_js_config/file_picker_config.py
lms/services/__init__.py
lms/services/youtube.py
lms/views/api/youtube.py
tests/unit/lms/services/youtube_test.py
tests/unit/services.py

This PR fixes some typos in the usage of `YouTube` brand, making sure we either use it all in lowercase, or with a capital `T`, so the possible values are `youtube` or `YouTube`, but never `Youtube`.

Fix typo in YouTube brand name

---

lms/static/scripts/frontend_apps/components/URLFormWithPreview.tsx
lms/static/scripts/frontend_apps/components/YouTubePicker.tsx
lms/static/scripts/frontend_apps/components/test/URLFormWithPreview-test.js
lms/static/scripts/frontend_apps/components/test/YouTubePicker-test.js

This PR makes sure invalid content cannot be saved in YouTube picker if you introduce a valid URL (which enables the "continue" button), but before pressing "continue" you edit it to set invalid content.
It also resets any visible error message to make it behave like the JSTORPicker.
Before:
[Grabación de pantalla desde 2023-05-31 10-01-16.webm](https://github.com/hypothesis/lms/assets/2719332/32aed01f-4677-4ba3-8186-6177f9f569d6)
After:
[Grabación de pantalla desde 2023-05-31 10-13-30.webm](https://github.com/hypothesis/lms/assets/2719332/060998cf-d545-47ff-be48-4834911a7f98)
1. Checkout this branch
2. Enable youtube in an LMS instance (http://localhost:8001/admin/instance/{id}/)
3. Try to edit/create a course on that instance
4. Select YouTube video, and introduce a valid video URL in …

Make sure YouTube picker save is reset when editing its content

---

lms/static/scripts/frontend_apps/components/ContentSelector.tsx
lms/static/scripts/frontend_apps/components/FilePickerApp.tsx
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
yarn.lock

This PR updates the buttons and polishes the layout of the `FilePickerApp` and `ContentSelector` components, that is, the assignment-configuration UI.
User-visible changes include:
* New buttons (`OptionButton`) for selecting assignment content, and these are laid out in two columns to optimize space
* Change `Button` to `LinkButton` for the "Change" (content) button for improved alignment and visibility
* Small fixes to alignment and consistency in spacing
Dev-visible changes include styling/layout refactoring in `FilePickerApp` and some removal of unnecessary styles.
Fixes https://github.com/hypothesis/lms/issues/2955
Part of https://github.com/hypothesis/lms/issues/5328

Update buttons and layout of `FilePickerApp` (configure-assignment panels)

---

lms/services/youtube.py
tests/unit/lms/services/youtube_test.py

Extend the `video_info` YouTube API to include a property telling if a video has restrictions somehow.
The property currently only takes into consideration if the video is age-restricted, but it can include other restrictions afterwards (`"restrictions": [ <list of strings> ]`).
The `/api/youtube/videos/{id}` endpoint now returns an `is_restricted` property that should be `true` if the video is age-restricted.
You can try this call using different videos to see the response:
```bash
curl --request GET \
--url http://localhost:8001/api/youtube/videos/{id} \
--header 'Authorization: Bearer <token>'
```
* Example video with age restriction: https://www.youtube.com/watch?v=HFlmHY8QFiY&ab_channel=JakePaul (`HFlmHY8QFiY`)
```json
{
"image": "https://i.ytimg.com/vi/HFlmHY8QFiY/mqdefault.jpg", …
```

Expose restricted YouTube videos through the video_info API

---

lms/static/scripts/frontend_apps/components/BookSelector.tsx
lms/static/scripts/frontend_apps/components/JSTORPicker.tsx
lms/static/scripts/frontend_apps/components/UIMessage.tsx
lms/static/scripts/frontend_apps/components/URLFormWithPreview.tsx
lms/static/scripts/frontend_apps/components/URLPicker.tsx
lms/static/scripts/frontend_apps/components/YouTubePicker.tsx
lms/static/scripts/frontend_apps/components/test/BookSelector-test.js
lms/static/scripts/frontend_apps/components/test/JSTORPicker-test.js
lms/static/scripts/frontend_apps/components/test/UIMessage-test.js
lms/static/scripts/frontend_apps/components/test/URLFormWithPreview-test.js
lms/static/scripts/frontend_apps/components/test/URLPicker-test.js

This PR extracts a common component for styling success and error messages in content pickers. This ensures that colors, spacing, alignment and sizing are consistent.
For the most part, user-facing changes are very subtle, but I notice that it does fix one visual nit with multi-line messages (icons too small), as shown below (`UIMessage` icons are always a fixed size, preventing this).
This change removes `items-center` (vertical icon centering) rules; icons are always top-aligned with text now.
The motivation for this change was message styling in the new YouTube picker.
Before:
After:

Consolidate styling for UI messages in content pickers

---

lms/services/youtube.py
tests/unit/lms/services/youtube_test.py

This adds a new `no_embed` restriction to videos which are not embeddable.
The `/api/youtube/videos/{id}` endpoint should now include `"no_embed"` in the `restrictions` property for non-embeddable videos.
You can try this call using different videos to see the response:
```bash
curl --request GET \
--url http://localhost:8001/api/youtube/videos/{id} \
--header 'Authorization: Bearer <token>'
```
* Example non-embeddable video: https://youtu.be/rw_scW4D3ik (`rw_scW4D3ik`)
```json
{
"image": "https://i.ytimg.com/vi/rw_scW4D3ik/mqdefault.jpg",
"title": "youtube picker",
"channel": "Alejandro Celaya",
"duration": "PT38S",
"restrictions": ["no_embed"]
}
```
* Example video with no age restriction: https://youtu.be/EU6TDnV5osM (`EU6TDnV5osM`)
```json
{
"image": …
```

Handle non-embeddable YouTube videos in video_info API

---

lms/migrations/versions/973c9358b616_jwt_token_table.py

For the model changes over 
https://github.com/hypothesis/lms/pull/5447
Upgrade with `hdev alembic upgrade head`
```
dev run-test-pre: PYTHONHASHSEED='3079560949'
INFO  [alembic.runtime.migration] Running upgrade 3a786e91f59c -> 973c9358b616, Create the jwt_token_table.
```
downgrade with:  `hdev alembic downgrade -1`
```
dev run-test-pre: PYTHONHASHSEED='319216996'
dev run-test-pre: commands[0] | pip-sync-faster requirements/dev.txt --pip-args …
```

LTIA token table migration

---

lms/models/__init__.py
lms/models/jwt_oauth2_token.py
lms/services/__init__.py
lms/services/jwt_oauth2_token.py
lms/services/ltia_http.py
tests/factories/__init__.py
tests/factories/jwt_oauth2_token.py
tests/unit/conftest.py
tests/unit/lms/services/jwt_oauth2_token_test.py
tests/unit/lms/services/ltia_http_test.py
tests/unit/services.py

Continuation the quest of reducing noise around grading. 
We've seen lots of timeouts while getting tokens to use with the grading APIs, increasing the timeout is an option but caching these like we do for regular oauth2  tokens is a no-brainier and has been a TODO of the LTI1.3 integration for a while now.
These tokens can be reused by all users in a registrations so we should see a high rate of cache hits.
Apply the migration to create the new table with:
```hdev alembic upgrade head```
In theory this should be the same in every LMS that supports LTI1.3 but let's try it in every one.
- Launch https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2424/View?ou=6782 **as an instructor**
- In the student selector pick "auntltd Learner"
- Check a new token is stored in the DB …

Cache LTIA tokens in the DB

---

lms/static/scripts/frontend_apps/api-types.ts
lms/static/scripts/frontend_apps/components/URLFormWithPreview.tsx
lms/static/scripts/frontend_apps/components/YouTubePicker.tsx
lms/static/scripts/frontend_apps/components/test/YouTubePicker-test.js

This PR is part of https://github.com/hypothesis/lms/issues/5449
It adds the ability to display meaningful errors when a proper YouTube video URL is provided, but the video itself has one or more restrictions that would make it impossible to use in an assignment.
The implementation is based on suggestions from https://github.com/hypothesis/lms/pull/5480#discussion_r1227089387
Age-restricted video (https://youtu.be/HFlmHY8QFiY)
Not embeddable video (https://youtu.be/rw_scW4D3ik)
Multiple restrictions (https://youtu.be/VdjCpC2_vSA)
- ~Choose the right messages to display for every restriction. Current messages are placeholders.~ On a follow-up PR
- ~Consider extracting `restrictionsToError` from `YouTubePicker`. It could even be a component on its own.~ Discarded. Too soon to build …

Support displaying restrictions in YouTubePicker

---

lms/static/scripts/frontend_apps/components/ContentSelector.tsx
lms/static/scripts/frontend_apps/components/YouTubePicker.tsx
lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js
lms/static/scripts/frontend_apps/components/test/YouTubePicker-test.js

Closes #5484
This enables the logic to actually save the selected URL on the YouTubePicker, allowing to create/edit assignments.
1. Check out this branch
2. Try to create an assignment, selecting YouTube from the content selector
* *This course https://hypothesis.instructure.com/courses/125/assignments has YouTube enabled*
3. Make sure you can complete the process, and then the video player with transcript is loaded for that video.
It's important to have your local `via` up to date for this to work.

Support saving assignments where the URL has been picked using the YouTubePicker

---

lms/static/scripts/frontend_apps/components/ContentSelector.tsx
lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js
lms/static/scripts/frontend_apps/utils/test/youtube-test.js
lms/static/scripts/frontend_apps/utils/youtube.ts

This PR improves the `YouTubePicker` so that it pre-fills the selected URL when changing it, in case it is a valid YouTube URL.
1. Edit/create an assignment, and choose YouTube in the content selector
2. Set a valid YouTube URL, for example https://youtu.be/EU6TDnV5osM
3. Press `Enter`, and once video details are loaded, click Continue
4. You'll see the selected URL, and next to it, a `Change` link. Clicking on it you'll get back to the content selector
5. If you select `YouTube` again, it will set the URL and load its details.
There are some considerations to tackle next:
1. Right now we are using the raw YouTube URL. This means the URL will also be preset in the `URLPicker`. We might need to handle this somehow. To be discussed.
2. If you first use the `URLPicker` to set a non-YouTube …

Prefil YouTube URLs in YouTubePicker when there's a valid URL already selected

---

lms/static/scripts/frontend_apps/components/ContentSelector.tsx
lms/static/scripts/frontend_apps/components/FilePickerApp.tsx
lms/static/scripts/frontend_apps/components/YouTubePicker.tsx
lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js
lms/static/scripts/frontend_apps/components/test/YouTubePicker-test.js

This PR changes the YouTubePicker to use selected video title and channel as the content name, instead of using the raw truncated URL.
1. Create an assignment selecting YouTube content
2. Paste a valid video URL, like https://youtu.be/qQ6a0iOzyHE
3. Click `Continue`.
4. The Content should display `YouTube: {video name} ({video channel})` instead of the raw video URL.
This PR does not cover the next things:
* Refactor layout to properly handle multi-line content names, or truncate content so that it does not span more than one line.
* Handle content name when an existing assignment is re-opened for edition (Blackboard and D2L only). See https://github.com/hypothesis/lms/pull/5500#issuecomment-1594694925

Use YouTube video title as assignment description

---

lms/tasks/email_digests.py
lms/tasks/mailchimp.py

Fixes https://github.com/hypothesis/lms/issues/5508.
Several of our Celery tasks have `retry_backoff=3600` which activates
Celery's exponential backoff feature for retries (see <https://docs.celeryq.dev/en/stable/userguide/tasks.html#Task.retry_backoff>).
The intention was that:
1. The first retry of a task would be scheduled for `3600` secs (one
hour) after the failure of the initial attempt
2. Following the rules of exponential backoff the second retry would be
scheduled for `2 * 3600` secs (two hours) after the failure of the
first retry
When accounting for Celery's enabled-by-default `retry_jitter` setting
(<https://docs.celeryq.dev/en/stable/userguide/tasks.html#Task.retry_jitter>)
the delays should actually be randomly chosen times between `0` and
`3600` and between `0` and `7200` …

Fix Celery task retry delays

---

lms/services/h_api.py
tests/unit/lms/services/h_api_test.py

Increase the timeout on all of LMS's requests to the h API from 10s to
60s.
Fixes https://github.com/hypothesis/lms/issues/5510.
LMS's requests to h's bulk annotation API have been timing out. Ideally
we've like these requests to be fast enough that they don't time out.
But if the requests do take a long time I think we'd prefer for LMS to
wait longer for the responses rather than failing.

Increase the timeout on h API requests

---

lms/tasks/email_digests.py

Fixes https://github.com/hypothesis/lms/issues/5509.
The `send_instructor_email_digests()` task has been [overloading h's DB](https://docs.google.com/document/d/1AimkRirwYirz-LWVyyDIRGKB4-HsYOKO0KoOFH_dhg4/).
Add a rate limit to the task so that it doesn't put so much load on h.
See https://docs.celeryq.dev/en/stable/userguide/tasks.html#Task.rate_limit.
Note that Celery task rate limits are per-worker so if the rate limit
"1/m" (one per minute) and there are two workers then the system will
actually process up to two tasks per minute.
I think there are usually four LMS instances and therefore four Celery
workers at the time when the `send_instructor_email_digests()` task is
run.
It looks like we currently run this task about 262 times each morning
(and this number is slowly increasing): …

Add a rate limit to the `send_instructor_email_digests()` task

---

lms/static/scripts/frontend_apps/components/ContentSelector.tsx
lms/static/scripts/frontend_apps/components/URLPicker.tsx
lms/static/scripts/frontend_apps/components/test/URLPicker-test.js

Since we are currently using raw YouTube video URLs for video assignments, there's a possibility that someone configures it using the regular `URLPicker` instead of the `YouTubePicker`.
This is problematic, as the latter performs some extra validation that is not performed by the `URLPicker` (is a public existing video, it's not age-restricted, it's embeddable, etc).
Bypassing these validations could result in an assignment which fails for students at a later point in time.
This PRs adds a simple check that displays an error if a YouTube video URL is set in the `URLPicker`. The message is different if youtube is not allowed for the active course.
YouTube enabled:
YouTube not enabled:
This PR closes #5499

Do not allow YouTube video URLs when using the URLPicker

---

lms/data_tasks/report/create_from_scratch/05_entities_decorated/01_users/01_create_view.jinja2.sql

For:
* https://github.com/hypothesis/product-backlog/issues/1460
This adds a few extra date fields to the user:
* `first_active_date`
* `last_active_date`
They are all a slightly merged and fudged version of the truth from many different sources, but approximate the suggested values.
This is useful for seeing when someone first became a user and when they last interacted with the system. This will simplify some down-stream requests, and allow us to put this on the user dashboard easily.
* This query runs fine in metabase, so you can try it out there

Add dates to the user table in reporting

---

lms/data_tasks/report/create_from_scratch/05_activity_counts/02_groups/02_group_bubbled_annotation_counts/01_create_view.jinja2.sql

For:
* https://github.com/hypothesis/report/issues/235
This was grouping things by the wrong group_id, which made it useless. This meant any course (e.g. `us-24333504`) would continue to have zero records here.

Fix the bubbling counts to be arranged by parent, not child

---

lms/data_tasks/report/create_from_scratch/02_entities/03_events/01_create_view.sql

From:
* https://github.com/hypothesis/lms/pull/5504
We need to update the reporting types to match the new possible values in the event table. This can be released before the new event type safely, but reporting will fail if run after.

Update reporting with the new "submission" event type

---

lms/events/event.py
tests/unit/lms/events/test_event.py

This might have been necessary in previous versions of LTIParams but it doesn't seem to be necessary now.
- Clear your events `docker compose exec postgres psql -U postgres -c "truncate event cascade;"`
- Test deeplinking in LTI1.1 with:
https://hypothesis.instructure.com/courses/125/assignments/4682/edit?name=Testing+creation+-+marcos&due_at=null&points_possible=0
tool `Hypothesis
localhost (make devdata) with Sections Enabled`
- Test deeplinking in LTI1.3 with:
https://hypothesis.instructure.com/courses/319/assignments/4924/edit?name=Testing+IDs+(marcos)&due_at=null&points_possible=0
tool `Hypothesis LTI1.3 (localhost)`
Should now have two different events linked to two different courses:
- docker compose exec postgres psql -U postgres -c "select timestamp, type, course_id from event …

Remove unnecessary special case to get context_id while deeplinking

---

lms/events/event.py
lms/models/event.py
lms/models/lti_user.py
lms/services/lti_user.py
lms/validation/authentication/_lti.py
lms/views/api/grading.py
tests/factories/lti_user.py
tests/unit/lms/events/test_event.py
tests/unit/lms/services/lti_user_test.py
tests/unit/lms/validation/authentication/_lti_test.py
tests/unit/lms/views/api/grading_test.py

Keep track of submissions made by students. This is now a canvas only feature in our implementation but there's nothing canvas specific about the events themselves.
- Login as `eng+canvasstudent@hypothes.is` in Canvas
- Launch https://hypothesis.instructure.com/courses/125/assignments/4682
- Make an annotation
- Check the newly created event:
```shell
docker compose exec postgres psql -U postgres -c "select course_id, user_id, assignment_id, type from event join event_type on event_type.id = type_id join event_user on event_id = event.id where type = 'submission' order by event.id desc"
```
```
course_id | user_id | assignment_id |    type    
-----------+---------+---------------+------------
155 |       7 |            47 | submission
```
We need to merge the following PRs from reporting …

Store student submissions as events

---

lms/models/event.py
lms/static/scripts/frontend_apps/services/grading.ts
lms/static/scripts/frontend_apps/services/test/grading-test.js
lms/validation/_api.py
lms/views/api/grading.py
tests/unit/lms/validation/_api_test.py
tests/unit/lms/views/api/grading_test.py

For 
- https://github.com/hypothesis/lms/issues/5505
Similar to #5504 but for grades.
On top of user, course and & assignment (part of all LTIEvents), we want here to store also the actual numeric value of the score and the student being graded.
- Make sure to have `make devdata` up to date
- Log into D2L as `HypothesisEng.Teacher`
- Launch https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2424/View?ou=6782
- Grade `aunltd Learner` with any grade
- Check the event is stored in the DB
```
docker compose exec postgres psql -U postgres -c "select event.id, course_id, assignment_id, type, extra from event join event_type on event_type.id = type_id join event_data on event_data.event_id = event.id where type = 'grade' order by event.id desc"
```

Store student grades as events

---

lms/product/canvas/_plugin/misc.py
lms/product/d2l/_plugin/misc.py
lms/product/plugin/misc.py
lms/views/lti/deep_linking.py
tests/unit/lms/product/canvas/_plugin/misc_test.py
tests/unit/lms/product/d2l/_plugin/misc_test.py
tests/unit/lms/product/plugin/misc_test.py
tests/unit/lms/views/lti/deep_linking_test.py

One step towards, still a work in progress
- https://github.com/hypothesis/lms/issues/5543
Unblocks:
- https://github.com/hypothesis/lms/issues/5544
- D2L doesn't allow us to submit a launch URL with query params as part of the return message in deep linking.
- Canvas doesn't fully support (it doesn't send them back) custom parameters in the DL response message but it does allow for them to be part of our DL message.
Based on this: 
- We refactor into a plugin the difference in the launch URL.
- We send the assignment configuration as custom parameters in all LMSes
- We refactor the get_document_url in canvas to explicitly read if from the DL configuration (which happens to be in the query params of the URL).
- In D2L we read the URL form the DL params as a fallback. In this case these …

Deep linking refactor and DL support in D2L

---

lms/static/scripts/frontend_apps/components/GroupConfigSelector.tsx
lms/static/scripts/ui-playground/components/EditAssignment.tsx
tailwind.config.mjs

See similar PR in the `client`: https://github.com/hypothesis/client/pull/5607
In component styles where the intent is to match the default border radius sizing, use unqualified `rounded` instead of `rounded-sm`. The default border radius happens to be 2px, which is equivalent to the default `rounded-sm` value out of the box with Tailwind, but the intent is instead "use the default border radius size". Use `rounded-[4px]` where the intent is literally 4px, not default.
Add a border-radius default to tailwind config.

Use `rounded` instead of `rounded-sm` for border radius defaults
