.travis.yml
tests/lms/conftest.py
tox.ini

- Set the value of the `JWT_SECRET` environment variable in `tox.ini`.
This gets `make test` working locally, without having to manually set
`JWT_SECRET` to a test value before running it.
- Remove `JWT_SECRET` from `passenv` in `tox.ini`. Now that we're
_setting_ `JWT_SECRET` in `tox.ini` we don't need to pass it.
- Remove `JWT_SECRET` from `.travis.yml`. Now that its been added to
`tox.ini` it shouldn't be needed here anymore. Having it in `tox.ini`
should get `make test` working both locally and on Travis instead of
just on Travis.
- Remove the `jwt_secret` from `conftest.py`. I don't think this was
being used at all - the code reads `JWT_SECRET` from the environment,
it doesn't read `jwt_secret` from the Pyramid settings.

Fix `JWT_SECRET` fails in `make test`

---

README.markdown
env.sh
lms/config/__init__.py
tests/lms/conftest.py

These variables aren't used anywhere.

Remove unused environment variables

---

env.sh

This file now contains only a single environment variable (VIA_URL), and
actually doesn't contain other environment variables that are necessary
to run the app. The README instructions already say to set all the
environment variables (including VIA_URL) manually.
If looking for a way to keep track of and easily apply and unapply env
vars, check out direnv:
https://direnv.net/
And add .envrc to ~/.config/git/gitignore_global, see:
https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

Delete the env.sh file

---

lms/routes.py
lms/views/status.py
tests/lms/views/status_test.py

The AWS load balancer will be configured to request this endpoint to
test whether an application instance is healthy and can be added in to
or needs to be removed from the load balancer. The endpoint 500s if the
application server isn't healthy, 200s if it is.

Add a /_status endpoint for load balancers

---

Jenkinsfile

This reverts commit d01843851b7abc6ce8065b7ffbf2d4aa12de2e98.
I think we've made the necessary changes in the playbook repo, the
deployment repo, and Jenkins now. I'm not sure if these qa and prod
deploys will run successfully in Jenkins yet, I think we may need to
manually create lms-qa and lms-prod environments in Elastic Beanstalk
first, but lets give this a try and find out.

Revert "Remove QA and prod deploys from Jenkinsfile"

---

lms/templates/content_item_selection/new_content_item_selection.html.jinja2
lms/views/content_item_selection.py

This PR allows features that ensures that canvas specific actions (I.E. Canvas File Picker, Canvas Oauth) are only taken during an lti launch from canvas. This should allow fix LTI launches from other LMS'. I was able to test in both Canvas and Blackboard, both of which appear to be fully functional. 
We determine if an LTI launch is from canvas by the presence of canvas specific LTI launch parameters, specifically `custom_canvas_course_id`. Which should be included regardless of whether or not we are launching from a course or account context.

Compartmentalize Canvas Specific Code

---

conf/development.ini
lms/config/__init__.py
lms/migrations/versions/51889ae54178_add_oauth_credentials_to_.py
lms/models/application_instance.py
lms/templates/application_instances/new_application_instance.html.jinja2
lms/util/authorize_lms.py
lms/views/application_instances.py
lms/views/content_item_selection.py
lms/views/oauth.py
requirements.in
requirements.txt
tests/lms/conftest.py
tests/lms/util/test_authorize_lms.py
tests/lms/views/test_application_instance.py

Add `ApplicationInstance` specific developer key and secrets. This allows Oauth without the a global instructure developer key and secret. Keys and secrets are both stored in the application_instances table. Developer keys can be accessed via `application_instance.developer_key`. The developer secret is encrypted via AES encryption while at rest. The encrypted secret is can be accessed from an `application_instance` model via `application_instance.developer_secret`. The decrypted secret can be obtained by `application_instance.decrypted_developer_secret(aes_secret)` where the `aes_secret` is a randomly generated byte array of length 16.

Add Application Instance Specific Oauth Credentials

---

lms/migrations/versions/64d9eacab937_add_oauth_support.py

Some where down the road we ended up with migrations that branched off of the main chain. This sets them into one chain so that when we deploy we shouldn't have to run upgrade heads.

fix migration chain

---

lms/config.xml.jinja2

Adds support for `assignment_selection` content item selection. LTI tools are configured with with an xml document that is given to canvas upon installing the application. Adding this section enables content item selection (File chooser app) for selecting an assignment with the hypothesis tool. Unfortunately, because this is a configuration that is set at install time, users must reinstall the app in their canvas instance in order for the update to occur. More information can be found [here](https://canvas.instructure.com/doc/api/file.content_item.html)

Add assignment selection to xml config

---

lms/views/lti_launches.py

Previously we left the created field on the `LtiLaunch` model to be set by the default. I think this was only happening when the database was flushed, and therefore the times showed up in batches according to when they were committed to the database. We now explicitly set to `created` time to reflect the UTC time that the LTI launch actually occurred. 
Below is an example of the reports both before and after the change. Notice all but the last two records have non-unique times. The last two launches occurred after the fix, and have a time that reflects the actual LTI launch time.

Fix Reporting Issue

---

lms/views/lti_launches.py

We were seeing module item configurations being erroneously pulled up when users in Moodle would attempt to configure the tool. We thought we were looking up module item configurations by `tool_consumer_instance_guid` and `resource_link_id`. It turns out we were actually only looking up by `resource_link_id` because of a confusion with the SQLalchemy syntax. This was working previously because Canvas gives a globally unique ID for `resource_link_id` which Moodle does not.

Fix Sqlalchemy Bug

---

lms/models/__init__.py
lms/models/application_instance.py
lms/templates/reports/application_report.html.jinja2
lms/views/__init__.py
lms/views/reports.py
tests/lms/views/test_reports.py

This PR fixes a bug where multiple installs were reported to have the same creation time, even though we knew that they were created at different times. 
It also adds the consumer key and shared secret to the installs table. 
For the launches graph, it now only lists each specific context the app has been launched in a single time, but adds a column to list how many times it has been launched. As well as adding the lms url, requesters email, and consumer key that correspond to the application instance that was launched.

Update Reports Page

---

Makefile

`make dev` was failing on dependency install because `pip` since version 9 ish no longer has the `--use-wheel` option.

Remove deprecated/removed pip `—use-wheel` from Makefile

---

lms/routes.py
lms/templates/base.html.jinja2
lms/views/__init__.py
lms/views/index.py

This PR introduces a view handler and route for the `/` route and updates the base template to include a site verification meta tag. The landing page no longer returns a 404, but the rendered HTML page is currently blank. We could put stuff there if we cared to.
There are no tests for this, though I'm not convinced they'd be warranted beyond testing the route and I don't want to take the time right at this moment to refactor the route tests.
Might fix https://github.com/hypothesis/product-backlog/issues/692

Add verification meta tag to base template and `index` view

---

lms/views/index.py

Linter complained about an unused arg (`request`), so I removed it from the index view handler, but that broke the everything.

Fix linting change that broke index view

---

tox.ini

`make lint` calls `prospector` which uses a library called
requirements-detector which depends on a lib called astroid. Astroid 2.0
was released a few days ago and breaks requirements-detector which
causes `make lint` to crash:
https://github.com/landscapeio/requirements-detector/issues/20
For now pin us to astroid==1.6.5 to avoid this crash. We should be able
to revert this commit once the above github issue is fixed.

Work around a prospector crash with `make lint`

---

tox.ini

Pin pylint to version 1.9.2 to work around a crash we're seeing with 2.0.1 (released 2 days ago) and 2.0 (released 10 days ago). Don't want to deal with getting to the bottom of the linter crash right now so just
pin it for the time being, we'll try upgrading it again later and see whether the problem has been fixed.

Workaround a pylint crash

---

tests/.prospector.yaml

Since we never write code that calls our test methods, there's no reason to keep the names short. Allow test functions to be 84 chars long and test names to be 88 chars long - as long as they can be, while keeping within [Black's default line length of 88](https://github.com/ambv/black#line-length).

Allow longer function and method names in tests

---

lms/config/__init__.py
tests/lms/config/__init___test.py

Also removed an unused default value for the `settings` argument to `configure()` and fixed a couple of crashes with the `LMS_SECRET` envvar.

Add tests for config/__init__.py

---

tests/lms/conftest.py
tox.ini

We never want our tests to be sending real HTTP requests because:
1. It's slow
2. The tests will fail if you have no Internet connection
3. The tests will fail depending on the response of the Internet URL they're sending HTTP requests to
4. It doesn't allow tests to make HTTP responses in order to test how our code responds to different kinds of responses

Mock all HTTP requests in tests

---

lms/util/__init__.py
lms/util/exceptions.py
lms/util/h_api.py
tests/lms/util/test_h_api.py

Add functions for generating h display names, usernames and identities from LTI launch params. Nothing calls these functions yet.

Add utility functions for h user data from LTI data

---

lms/static/styles/lms.css
lms/templates/application_instances/new_application_instance.html.jinja2
lms/templates/login.html.jinja2
lms/templates/reports/application_report.html.jinja2

This PR integrates some pre-work that @sheetaluk has done to improve CSS a little and makes some of the app's interfaces a tad more usable.
Welcome form before:
Welcome form after:
Reports login page before:
Reports login page after:
Reports page before (note: My instance doesn't have any launch data, so those fields are empty):
Reports page after:
Fixes https://github.com/hypothesis/product-backlog/issues/714

Fix low-hanging CSS rules, layouts

---

lms/views/__init__.py
tests/lms/views/test_application_instance.py
tests/lms/views/test_config.py
tests/lms/views/test_content_item_selection.py
tests/lms/views/test_lti_launches.py
tests/lms/views/test_module_item_configuration.py
tests/lms/views/test_reports.py

The view callables aren't part of the public API of the `lms.views` package. No code would import `lms.views` and then call `lms.views.*`. Views isn't that kind of package. Instead, the `config.scan()` in
`lms/views/__init__.py` causes Pyramid to scan all of the `lms/views/*.py` modules for `@view_config`s and register all of the views.

Don't pointlessly export views as public API

---

README.markdown
lms/config/__init__.py
tests/lms/config/__init___test.py
tests/lms/conftest.py

Not used by anything yet. Example usage would be:
```python
if oauth_consumer_key in request.registry.settings["auto_provisioning"]:
...
```

Add optional AUTO_PROVISIONING env var

---

tox.ini

This reverts commit eae31f501c94cd608318224f7410b539fee3d678. The bug was fixed in requirements-detector 0.6, so the workaround is no longer needed:
https://github.com/landscapeio/requirements-detector/issues/20#issuecomment-406849759

Revert "Work around a prospector crash with `make lint`"

---

lms/views/content_item_selection.py
lms/views/decorators/__init__.py
lms/views/decorators/h_api.py
lms/views/lti_launches.py
tests/lms/views/decorators/test_h_api.py

For any successful LTI launch (e.g. request had a valid OAuth 1 signature), whether a student or teacher launching an assignment or a teacher creating a new assignment, call the h API to create a new user in h corresponding to the LTI user.
If the h user already exists pass silently.
If anything goes wrong - something missing from the LTI params, or a timeout or unexpected response from h - then abort the entire LTI launch (assignment will not be shown) and show an error to the user.
Fixes https://github.com/hypothesis/product-backlog/issues/712  
Fixes https://github.com/hypothesis/product-backlog/issues/735
Things to test:

Create h users

---

lms/exceptions.py
lms/views/error.py
lms/views/lti_launches.py
tests/lms/views/error_test.py
tests/lms/views/test_lti_launches.py

Fixes https://github.com/hypothesis/lms/issues/138
Test setup:
In `lms/views/decorators/h_api.py def wrapper`:
1. Set the jwt param to default to None. `def wrapper(request, jwt=None):`
In `lms/views/lti_launches.py def lti_launches`:
1. Remove the `@lti_launch()` decorator
2. Set the jwt param to default to None. `def lti_launches(request, jwt=None, user=None):`
To test context_id param missing error page:
1. `brew install httpie`
2. `http --form POST 'http://0.0.0.0:8001/lti_launches' user_id="someone" oauth_consumer_key="foo" --verify no`
Result:
To test resource_link_id param missing error page:
1. `brew install httpie`
2. `http --form POST 'http://0.0.0.0:8001/lti_launches' user_id="someone" oauth_consumer_key="foo" context_id="bar" --verify no`
Result:

Show user the error page when context_id and resource_link_id params are missing and lti launch fails.

---

lms/util/jwt.py
lms/util/lti_launch.py
lms/views/lti_launches.py
tests/lms/views/test_lti_launches.py

Fixes https://github.com/hypothesis/lms/issues/132
To test:
In `lms/views/lti_launches.py def lti_launches`:
1. Remove the `@lti_launch()` decorator
2. Set the jwt param to default to None. `def lti_launches(request, jwt=None, user=None):`
3. `brew install httpie`
4. `http --form POST 'http://0.0.0.0:8001/lti_launches' user_id="someone" context_id="x" --verify no`
Result:

Show user the error page when oauth consumer key param is missing and lti launch fails.

---

lms/templates/content_item_selection/new_content_item_selection.html.jinja2

I mistakenly assumed that canvas sends the lms_url with the protocol during the lti launch but it doesn't. Because of this we were sending an incorrect url to the google picker to use as its origin, thus causing xframe error we have been seeing with the google picker. 
See https://github.com/hypothesis/product-backlog/issues/692#issuecomment-414373324 for more info regarding the issue.

fixes the google picker origin

---

lms/migrations/env.py

Alembic's `target_metadata` setting is incorrectly set to `None` in `migrations/env.py`, meaning that Alembic migrations scripts generate incorrect names for indexes and unique, check, foreign key and primary key constraints: the names generated by running an Alembic migration differ from the ones that're generated by SQLAlchemy when it creates the database schema anew from the model classes.
Our app's database code sets SQLAlchemy's metadata object to one containing a custom naming convention for indexes and constraints:
https://github.com/hypothesis/lms/blob/947a51874f21ba43d65899d1cd652e8bc4e90371/lms/db/__init__.py#L24-L30
But instead of using the same custom naming convention, our Alembic envirenvironment sets the metadata object to `None`: …

[Create groups 1/n]: Fix Alembic's target_metadata

---

lms/views/content_item_selection.py
lms/views/decorators/__init__.py
lms/views/decorators/h_api.py
lms/views/lti_launches.py
tests/lms/views/decorators/test_h_api.py

On LTI launch (either assignment launch or content item selection launch), if the LTI user is allowed to create groups (e.g. if they're a teacher), then create a group for the LTI course in h if one doesn't exist already.
- Doesn't update group names if the course name is changed (h has no API for doing this yet)
- Crashes or behaves incorrectly if the groups table in the LMS app's DB gets out of sync with the one in h's DB:
- If a group is deleted from h's DB but still exists in the LMS app's DB, then the LMS app will try to use the group (thinking it exists in h) and crash.
- If a group is deleted from the LMS app's DB but still exists in the h's DB then the LMS app will think that no group for the course exists in h yet and will create a second group in h for the same course.
One or …

[Create groups 5/n]: Create groups on LTI launches

---

lms/templates/application_instances/new_application_instance.html.jinja2

Users are confused when using the “welcome” (create credentials) form
because to set up Google Picker integration they were asked to
provide a “Developer Key”, which in Canvas-world has no meaning.
Unfortunately, the imprecise naming of `developer_key` goes all the way
down (to DB column names) so excising it entirely is beyond the scope
of a quick-fix PR.
Fixes https://github.com/hypothesis/lms/issues/184

Change label on `developer_key` form field

---

lms/views/decorators/__init__.py
lms/views/decorators/h_api.py
lms/views/lti_launches.py
tests/lms/views/decorators/test_h_api.py

~Depends on https://github.com/hypothesis/lms/pull/235 and https://github.com/hypothesis/lms/pull/236.~
When a Canvas user launches an assignment call the h API to add their corresponding h user to the assignment's course group.
Manual testing checklist:
When `AUTO_PROVISIONING` _is_ enabled for the application instance:

Add users to groups

---

Dockerfile
package.json
yarn.lock

*Depends on https://github.com/hypothesis/lms/pull/240*
We probably will want to use SASS in the lms app at some point, but we're not using it yet. When we do come to need it, we can add the current versions of just what we need.
For example, we might not need to bother with autoprefixer or postcss any more.

Remove unused sass build dependencies

---

package.json
yarn.lock

Many of the dependencies in package.json came from h's frontend
dependencies, but are not used in the lms app.

Remove unused development dependencies

---

gulpfile.js

This was disabled without explanation when the gulpfile was first added
to the repository. As a result the JS bundle for the file picker is much
larger than it needs to be.

Re-enable minification of frontend code in the Docker build

---

.babelrc
lms/static/scripts/karma.config.js
package.json
scripts/gulp/create-bundle.js
yarn.lock

- Fix invalid configuration for Browserify in package.json (nested
"browserify" objects)
- Avoid specifying the Babel transforms to apply in multiple places. It
is now specified only in .babelrc
- Replace the "stage-0" plugin (which means "support all experimental
JS syntax proposals") with es2015 + object-rest-spread (a feature
from ES 2018 which is actually shipped in multiple browsers).

Simplify Babel + Browserify configuration

---

.travis.yml
Makefile
lms/static/scripts/.eslintrc
lms/static/scripts/file_picker/_file_picker.js
lms/static/scripts/file_picker/canvas_api.js
lms/static/scripts/file_picker/components/component-test.js
lms/static/scripts/file_picker/components/component.js
lms/static/scripts/file_picker/components/file_picker-test.js
lms/static/scripts/file_picker/components/file_picker.js
lms/static/scripts/file_picker/components/picker_footer.js
lms/static/scripts/file_picker/components/picker_table_row-test.js
lms/static/scripts/file_picker/components/picker_table_row.js
lms/static/scripts/file_picker/store-test.js
lms/static/scripts/file_picker/store.js
lms/static/scripts/karma.config.js
package.json

This PR enables running of JS linting in Travis CI builds.
- The first commit enables parsing of ES6 modules by ESLint for files in lms/static
- The second commit uses ESLint's `--fix` mode to autofix most outstanding issues
- The third commit fixes a couple of minor issues that ESLint could not auto-fix
- The last commit enables running of linting on each CI build. I also followed the convention of h of adding an "ACTION=<task>" env var so that the role of each Travis job can easily be distinguished when looking at Travis build output.

Enable JS linting on CI

---

gulpfile.js
package.json
yarn.lock

This was only referenced in package.json and commented-out code in
gulpfile.js

Remove unused bootstrap dependency

---

gulpfile.js
lms/assets.ini
lms/static/scripts/content-item-selection.js
lms/templates/content_item_selection/new_content_item_selection.html.jinja2

_This is part of https://github.com/hypothesis/lms/issues/251_
Move the script for the form used to select a document to annotate out
of the Jinja2 template and into a JS module. This will make it easier to
refactor in future.
This commit makes only a minimum of changes to the actual code itself
needed to support loading the script from a separate file instead of
being inline.
- The functions invoked via event handlers in the template are exposed
via a "contentItemSelection" window global.
- All template-variables have been replaced with access to properties
on the `window.DEFAULT_SETTINGS` global.
- Remove unused `appId` variable.
- Fix lint failures in the code
----
**Testing**
I tested this manually by installing my local lms app into the https://hypothesis.instructure.com instance, …

Move JavaScript for content_item_selection view out of template

---

gulpfile.js
lms/assets.ini
lms/static/scripts/content-item-selection.js
lms/templates/content_item_selection/new_content_item_selection.html.jinja2

**Depends on https://github.com/hypothesis/lms/pull/259**
This rewrites the flow of the "Use Google Picker" button handler to use promises rather than interdependent callbacks in order to make the logic easier to follow.
As a result of doing that, it became easier to initialize the Google client libraries and in particular the `gapi.auth2` authorization library on page startup, before the "Use Google Picker" button is clicked (if the script is slow to load, things should still work). This follows the flow described in the [Google API client library](https://developers.google.com/api-client-library/javascript/reference/referencedocs#auth-setup) docs.
As a result of _that_, clicking the "Use Google Picker" button no longer triggers the popup blocker when clicked.
Fixes #186
----
_As an …

Fix "Use Google Picker" button triggering popup blocker

---

lms/config/resources.py

Also make the pointless `__init__()` method (just `pass`) actually do
something by saving the `request` as `self.request`. This will be made
use of in future commits.

Fix a docstring

---

lms/models/__init__.py
lms/models/oauth_state.py
lms/util/__init__.py
lms/util/authorize_lms.py
lms/util/lti.py
lms/views/oauth.py
tests/lms/models/test_oauth_state.py
tests/lms/util/lti_test.py
tests/lms/util/test_authorize_lms.py

Deduplicate some code for retrieving stashed LTI launch parameters from the database that was duplicated in a couple of places.
This code is going to be needed in a third place too, in an upcoming commit.
The `find_by_state()` function is no longer used outside of the oauth_state.py file itself, so make it a private function.

Login integration 0/n: Deduplicate LTI param retrieval

---

README.markdown
lms/config/__init__.py
lms/config/resources.py
lms/routes.py
lms/templates/lti_launches/new_lti_launch.html.jinja2
tests/lms/config/__init___test.py
tests/lms/config/resources_test.py
tests/lms/conftest.py

Depends on <https://github.com/hypothesis/lms/pull/284>.
This adds three new required config settings:
1. H_JWT_CLIENT_ID
2. H_JWT_CLIENT_SECRET
3. RPC_ALLOWED_ORIGINS
All three will need to be set on QA and production before merging this, otherwise the app will fail to start up.
This PR also makes a `{{ context.hypothesis_config }}` variable available to all templates. It's a JSON-serializable client config object suitable for use in a js-hypothesis-config JSON script. It includes a grant token for the client to use to log the LTI user in to h, generated using the `H_JWT_CLIENT_ID` and `H_JWT_CLIENT_SECRET` (and the user info from LTI).
If the auto provisioning feature is disabled for the current application instance then `{{ context.hypothesis_config }}` will _not_ contain a `services` …

Login integration 1/n: New config settings

---

gulpfile.js
lms/assets.ini
lms/static/scripts/polyfills.js
lms/static/scripts/postmessage_json_rpc/server/index.js
lms/static/scripts/postmessage_json_rpc/server/methods-test.js
lms/static/scripts/postmessage_json_rpc/server/methods.js
lms/static/scripts/postmessage_json_rpc/server/server-test.js
lms/static/scripts/postmessage_json_rpc/server/server.js
lms/templates/lti_launches/new_lti_launch.html.jinja2

Add a JSON-RPC server that responds to JSON messages sent over postMessage.
Currently the only request that is supported is "requestConfig" which returns a client config object for the current LTI launch request. This client config object was already rendered into the HTML document by a previous commit, and the JSON-RPC server reads it from there.
The JSON-RPC server's own config object, including the list of postMessage origins from which RPC requests will be accepted, was also rendered into the document by a previous commit and is now read by the JSON-RPC server.
This depends on <https://github.com/hypothesis/lms/pull/275/>, which adds the client and server config objects into the page. The server will crash without them.
It should be safe to merge this once …

Login integration 2/n: Add JSON-RPC server

---

lms/templates/lti_launches/new_lti_launch.html.jinja2
lms/util/__init__.py
lms/util/via.py
lms/views/lti_launches.py
tests/lms/util/via_test.py

Add two query params to the end of the Via URL used as the src of the Via iframe:
1. `via.open_sidebar=1`, tells Via to configure the client to automatically open its sidebar on launch.
2. `via.request_config_from_frame=<LMS_APP'S_ORIGIN>`, tells Via to configure the client to request a config object from the LMS app's origin over postMessage on launch.
These two query params are appended to the Via URL while maintaining any existing query params in the URL-of-the-document-to-be-annotated part of the Via URL, and their order.
This depends on <https://github.com/hypothesis/lms/pull/275/> and <https://github.com/hypothesis/lms/pull/278>. Without those the client will crash because it'll send a JSON-RPC request and get no response.

Login integration 3/n: Add via.* params to Via URL

---

.prospector.base.yaml
conf/development.ini
conf/production.ini
lms/app.py
lms/views/error.py
requirements.in
requirements.txt
tests/lms/views/error_test.py

Fix the in-browser exception views (error page) and printing of exceptions to the console in dev.
This was all just completely broken. Fix it by using `pyramid_exclog` to log exceptions to the console, and also fix up the exception views / error page to not crash, and tidy up the code and docstrings.
See:
* <https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/logging.html#logging-exceptions>
* <https://docs.pylonsproject.org/projects/pyramid_exclog/en/latest/>

Fix exception handling using pyramid_exclogger

---

.travis.yml
Jenkinsfile
Makefile
README.markdown
lms/util/lti.py
lms/views/authentication.py
lms/views/decorators/h_api.py
lms/views/lti_launches.py
tox.ini

Re-do these to work the same as the h and bouncer ones do: run everything in tox-managed venvs, no need to create your own venvs.
This necessitated doing a pylint upgrade which triggered some new lint warnings that I fixed.

Refactor tox.ini and Makefile

---

conf/production.ini
lms/sentry.py
lms/views/error.py
requirements.in
requirements.txt
tests/lms/conftest.py
tests/lms/views/error_test.py

This gets the error reporting to Sentry basically working (but not using any advanced Sentry features yet):
1. The legacy Sentry client (`raven`) is replaced with `sentry-sdk`
2. We use `sentry-sdk`'s builtin Pyramid support, instead of a lot of custom code. This alone means that any 500 responses from our app are reported to Sentry correctly (e.g. with correct tracebacks and request details), without any support from our code. (Other 5xx and 4xx responses aren't reported automatically though.)
3. In `views/error.py` call `sentry_sdk.capture_exception()` to report non-500 5xx and 4xx responses from our app to Sentry.
This means that when talking to the h API fails and our lms app raises something like `HTTPGatewayTimeout` in response, this will be reported to Sentry.
This also means that …

Fix Sentry error reporting

---

lms/sentry.py
tox.ini

Our Sentry setup for the LMS app has a single lms-backend project
containing two environments prod and qa, but the app wasn't sending the
environment string with the crash reports so all issues were just going
into the "all environments" screen. Fix it to use the SENTRY_ENVIRONMENT
envvar to set the environment string.
Some of the other Sentry SDK's (e.g. the Node one) have builtin support
for an envvar named SENTRY_ENVIRONMENT but their Python SDK doesn't, we
have to read it ourselves.

Fix Sentry environment support

---

conf/development.ini
conf/production.ini
lms/app.py
lms/views/error.py
tests/lms/views/error_test.py
tox.ini

Depends on <https://github.com/hypothesis/lms/pull/327>.
This improves our logging of exceptions in both development and production. By logging I mean to CloudWatch Logs in production, and to the terminal and pyramid_debugtoolbar in dev. This PR does not affect crash reporting to Sentry.
What this PR does:
* Simplifies our ini files by removing a bunch of `exc_logger` stuff that we don't need in them
* Changes us to using `pyramid_debugtoolbar` only in dev and `pyramid_exclog` only in production
Recently, `pyramid_exclog` was added to both dev and production and `pyramid_debugtoolbar` was removed from dev. This PR gets us to the point of using each extension for what it's meant for: `pyramid_debugtoolbar` for dev and `pyramid_exclog` for production.
* Disables our error views in dev so …

Improve error logging again

---

conf/production.ini

Depends on <https://github.com/hypothesis/lms/pull/327> and <https://github.com/hypothesis/lms/pull/328>.
Send a lot more information when an exception happens in production by enabling pyramid_exclog's `exclog.extra_info = true` setting. This adds:
* All envvars from the environment
* All params attributes of pyramid.request.Request
* The output from pyramid.security.unauthenticated_id()
See:
https://docs.pylonsproject.org/projects/pyramid_exclog/en/latest/#settings

Log more info when an exception happens in prod

---

tests/lms/views/decorators/test_h_api.py

These tests need to account for the fact that if the response is 4xx or 5xx request's `raise_for_status()` will raise. (Future code changes will require this from the tests.)

Fix some tests

---

lms/views/decorators/h_api.py
tests/lms/views/decorators/test_h_api.py

This is to make way for adding a function named `post` in the future, can't have a test fixture named `post` anymore.

Patch requests not request.post

---

.prospector.base.yaml
lms/views/__init__.py
lms/views/decorators/h_api.py
lms/views/exceptions.py
tests/lms/views/decorators/test_h_api.py
tests/lms/views/exceptions_test.py

This PR fixes two problems with the handling of h API error responses:
1. The LMS app's HTTP status code when an h API request fails or returns an error response (4xx or 5xx) has been a 502 Bad Gateway or 504 Gateway Timeout. This is no good -- Cloudflare intercepts gateway errors from our app and replaces our error page with its own gateway error page. Fix this by returning 500 Internal Server Error responses instead.
2. The LMS app was swallowing the error response from h API, neither logging it nor sending it to Sentry. In three separate places in the code the app was doing something like this:
https://github.com/hypothesis/lms/blob/59d00cce854c4eb27f660d80819d42a67f8c537b/lms/views/decorators/h_api.py#L199-L208
The local variable `response`, which contains the error message from the h …

Fix handling of h API error responses

---

lms/config/resources.py
tests/lms/config/resources_test.py

These links do not currently work in the LMS context. Use the config
option added to the client in https://github.com/hypothesis/client/pull/820 to disable them.
Part of https://github.com/hypothesis/product-backlog/issues/843

Disable share links on annotation cards

---

lms/util/h_api.py
tests/lms/util/test_h_api.py

The max group name length in h is 25, not 30. Fixes https://github.com/hypothesis/lms/issues/330

Fix crash when course name too long

---

lms/views/module_item_configurations.py

Fix a blank page after creating an assignment in Blackboard or Moodle.
The hypothesis_url template variable was renamed to via_url in baf66092872b3a1a701bbab834eb8acf6544f8bc
Fixes https://github.com/hypothesis/lms/issues/310

Fix blank page after creating assignment

---

requirements-dev.in

Use IPython, a more powerful interactive Python shell, instead of the standard Python shell in `make shell`.

Use IPython in `make shell`

---

tox.ini

The current version of Prospector (1.1.6.2) is not compatible with the current version of pylint (2.2.0) or pylint's dependency astroid. Removing the pylint dependency lets pip install the version that prospector requires / is compatible with.

Remove dependency on pylint

---

lms/views/content_item_selection.py

This hopefully fixes creating assignments in Canvas without breaking them in Blackboard. There's no way to write unit tests for this function, and we have no way to test the app in Blackboard locally, has to be deployed to QA to test.

Fix creating assignments in Canvas

---

lms/config/resources.py
lms/views/decorators/h_api.py
tests/lms/config/resources_test.py
tests/lms/views/decorators/test_h_api.py

Generate a groupid from LMS params, and send it to the h API when creating the group.
There's also a code duplication commit in here.

Use the groupid field when creating new groups in h

---

lms/models/application_instance.py

The Brightspace settings page for configuring LTI tools sets a limit of 100
chars on the field for the shared secret for signing LTI launch requests using
OAuth 1.0. With the previous secret size of 64 bytes / 128 hex digits, the value
would be silently truncated upon entering the secret into the form.
Solve the problem by halving the length to 32 bytes / 64 hex digits which is the
same size as a SHA-256 hash, and perfectly adequate from a security point of
view.
This change will not affect existing app installations. We will need to modify
our existing Brightspace installs to make those work.
Fixes #258

Shorten length of generated consumer secrets to 64 hex digits

---

lms/config/resources.py
lms/services/__init__.py
lms/services/exceptions.py
lms/services/hapi.py
lms/util/lti.py
lms/views/decorators/h_api.py
tests/lms/config/resources_test.py
tests/lms/conftest.py
tests/lms/services/hapi_test.py
tests/lms/views/decorators/test_h_api.py

Depends on <https://github.com/hypothesis/client/pull/824>
This PR does a couple of things:
1. The LMS app's `pubids` that it stores in its database are no longer being used. They're neither written to or read from the DB anymore. Creating, updating and adding members to groups is done using the new `groupid` field instead. The app still needs to pass the `pubid` to the client in order to tell it what group to show (which is annoying -- it would be much easier if `groupid` could be used here), but it gets the `pubid` anew from the h groups API response on each launch, does not store it. Fixes <https://github.com/hypothesis/lms/issues/287>. Follow-up PRs neeed:
1. Remove the `CourseGroups` model code.
2. DB migration to delete the table.
2. If a course's name changes in the LMS the app now …

Don't use pubids from the database. And also update group names

---

lms/util/associate_user.py
lms/util/authenticate.py
lms/util/authorize_lms.py
lms/util/canvas_api.py
lms/util/lti_launch.py
lms/views/decorators/h_api.py
tests/lms/conftest.py
tests/lms/views/test_content_item_selection.py
tests/lms/views/test_lti_launches.py

The `lti_launches` and `content_item_selection` view functions are
wrapped by a nested series of decorators which handle authorization and,
when provisioning is enabled, creation of users and groups in h that
correspond to the lms course.
These decorators are hard to mock/stub in unit tests which are only
concerned with the functionality of the view callable itself. This
problem is about to be exacerbated as provisioning becomes the default
experience and all the provisioning-related decorators therefore get
activated instead of skipping their logic.
The preferred way to resolve this problem would be to refactor the view
callable to perform provisioning setup and authorization in a way that
is more easily mocked, eg. using calls to services.
As an intermediate step, this PR refactors the …

Only test view function, not decorated function in lti_launches, content_item_selection view tests

---

lms/views/content_item_selection.py
lms/views/decorators/__init__.py
lms/views/decorators/h_api.py
lms/views/lti_launches.py
tests/lms/views/decorators/test_h_api.py

Fixes https://github.com/hypothesis/lms/issues/252
This PR adjusts the way that user API requests are handled in LTI launches. It will now attempt to update an existing user via PATCH—this will have the effect of keeping a LMS user's display name in sync, and potentially other data in the future. If the user doesn't exist yet—if the PATCH request results in a 404—then it will continue on and try to create the new user.
I marked this WIP because of a question I have about 409/Conflict errors.
I have tested this locally by changing my Canvas user's display name and making sure it updates, as well as deleting that user in the `h` database and and launching the assignment again, etc., but it could use some additional scrutiny to be sure.

Add PATCH request to keep user data in sync

---

README.markdown

Since we now run the dev server in a tox-managed venv, it's also necessary to run alembic from that venv.
We could make the command a little simpler in future, something like `tox -e migrate <ALEMBIC_ARGS>` should be possible.

Fix the docs on how to use alembic

---

conf/alembic.ini

DB migration scripts normally log using `log.info()`. Fix the root logging level so that info messages actually get printed.

Blacklist in DB 0/n: Fix DB migration logging

---

lms/views/decorators/h_api.py

Don't try to access context before it has been defined.

Fix context.provisioning_enabled crash

---

README.markdown
lms/config/__init__.py
lms/config/resources.py
tests/lms/config/__init___test.py
tests/lms/config/resources_test.py
tests/lms/conftest.py
tox.ini

Enable or disable the provisioning feature based on the new `provisioning` column in the DB, instead of on the `AUTO_PROVISIONING` envvar.
This is the PR that actually enables the new DB-based feature flag, and that makes it so that all new instances will now have provisioning enabled by default.

Blacklist in DB 5/n: Enable provisioning based on DB

---

lms/static/styles/reports.css
lms/templates/reports/application_report.html.jinja2

The styling of the reports page was such that, once there's enough data, the newest table rows are in a fixed and out-of-view position and can't be seen.
Change application_report.html.jinja2 to be a standalone template and no longer extend base.html.jinja2. This means that the global lms.css file no longer applies to this page. Add a reports.css file for the page instead containing some minimal CSS to make the tables look slightly nicer.

Fix the styling of the reports page

---

lms/views/error.py

Add a Pyramid Not Found view, see:
https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/hooks.html#changing-the-not-found-view
This overrides the other error views when the problem is a 404 not found. This fixes two issues:
1. The new notfound view doesn't report 404s to Sentry. Fixes https://github.com/hypothesis/lms/issues/438
2. Internal Pyramid errors are no longer shown to the user on 404 pages. Fixes https://github.com/hypothesis/lms/issues/437

Fix 404 views

---

conf/production.ini

These may just be noise in the logs. Also, sentry_sdk's logger integration is picking these up and sending them to Sentry, where we don't want them.

Don't log HTTP errors

---

lms/views/error.py
tests/lms/views/error_test.py

Without this view LTILaunchErrors will be caught by the http_error() view above which does exactly the same thing.

Remove unneeded lti_launch_error() view

---

lms/services/hapi.py
tests/lms/services/hapi_test.py

When the requests lib raises an exception when trying to make a request to the h API, raise the resulting HAPIError "from" the original requests exception. This means the details of the original requests exception are available in Sentry.

Report requests exceptions to Sentry

---

lms/app.py
lms/templates/validation_error.html.jinja2
lms/validation/__init__.py
lms/validation/_exceptions.py
lms/validation/_oauth.py
lms/views/error.py
lms/views/oauth.py
requirements.in
requirements.txt
tests/lms/validation/__init___test.py
tests/lms/validation/_exceptions_test.py
tests/lms/validation/_oauth_test.py
tests/lms/views/error_test.py

Add validation to the `canvas_oauth_callback()` view.
Fixes https://github.com/hypothesis/lms/issues/449
Also fixes an undocumented issue that, given a valid `state` parameter, `canvas_oauth_callback()` would then crash if the `code` parameter was missing.
* Add <https://webargs.readthedocs.io/> as a new dependency, for validating requests
* Add `lms.validation`, a new top-level package intended to hold all validation code
The way this works is that validation schemas, which are just called "args" in webargs, are defined and unit-tested in `lms.validation` and then imported into views modules and used as decorators on the views. The decorator passes the validated arguments into the view function as arguments or, if validation fails, the view function is never called.
So far we have only …

Add validation layer and validate /canvas_oauth_callback

---

Makefile

Add a command `make pip-compile` to recompile `requirements.txt` after you've edited `requirements.in`, using the correct version of `pip-compile`.

Add `make pip-compile` command

---

lms/app.py
lms/extensions/feature_flags/__init__.py
lms/extensions/feature_flags/_feature_flags.py
lms/extensions/feature_flags/_providers.py
lms/routes.py
lms/views/feature_flags_test.py
tests/lms/extensions/feature_flags/__init___test.py
tests/lms/extensions/feature_flags/_feature_flags_test.py
tests/lms/extensions/feature_flags/_providers_test.py
tox.ini

Adds a feature flags Pyramid extension.
Supports setting feature flags on or off in the config file, envvars or query string, or adding custom "feature flag providers" for other sources.
Usage:
```python
config.include("lms.extensions.feature_flags")
config.add_feature_flag_providers(
"lms.extensions.feature_flags.config_file_provider".
"lms.extensions.feature_flags.envvar_provider",
"lms.extensions.feature_flags.query_string_provider".
)
if request.feature("foo"):
...
else:
...
```
Where this is going:
* It should already be possible to query feature flags from Jinja2 templates (as Pyramid makes `request` available to templates) but we may want to add some handy Jinja2 tags or something.
* Add a handy `@view_config(.., feature_flag="foo")` so that you can easily turn an entire view off …

Add feature flags support

---

lms/services/hapi.py
tests/lms/services/hapi_test.py

Add a header to H api requests that will help distinguish LMS requests from requests made by other services. Rather than making the header specific to lms, make it generic such that it can be used by other Hypothesis services to distinguish their requests as well.

Add lms header to identify lms api requests to H

---

lms/migrations/versions/cfd94b1300ce_add_applicationinstance_consumer_key_.py
lms/models/application_instance.py
tests/lms/util/_lti_launch_test.py

In practice ApplicationInstance.consumer_key is always unique. Lets
enforce that in the database schema so that code can stop having to
handle the possibility of duplicate consumer keys.
The only place where we create new ApplicationInstance's is on the
https://hypothes.is/welcome page and that page generates a new unique
consumer key every time.
In the code, the only place where new ApplicationInstance objects are
created is in `build_from_lms_url()` and that uses the `secrets` library
(stdlib) to generate a new random consumer key every time:
https://github.com/hypothesis/lms/blob/5605422139e011dc93267d27510baffe3d32e4e8/lms/models/application_instance.py#L69-L95
Also see the docs for `secrets.token_hex()` here: https://docs.python.org/3/library/secrets.html#secrets.token_hex

Add a unique constraint to ApplicationInstance.consumer_key

---

lms/util/_lti_launch.py
tests/lms/util/_lti_launch_test.py

A unique constraint ensures that there can't be multiple ApplicationInstances in the DB with the same consumer_key.

Move no-longer-needed MultipleResultsFound handling

---

tests/lms/conftest.py
tests/lms/views/test_lti_launches.py

Don't set `lti_launch_request.context` to a mock `LTILaunch` object globally for all tests, as this is causing some mysterious test failures on another branch (and I don't understand why). Instead, apply the
`LTILaunch` mock only to the one test module that needs it (and crashes without it).

Use LTILaunch context fixture only where needed

---

lms/config/resources.py
lms/models/application_instance.py
lms/services/__init__.py
lms/services/application_instance_getter.py
lms/services/exceptions.py
lms/util/__init__.py
lms/util/_lti_launch.py
lms/util/authorize_lms.py
lms/util/canvas_api.py
lms/views/content_item_selection.py
lms/views/lti_launches.py
lms/views/oauth.py
tests/lms/config/resources_test.py
tests/lms/conftest.py
tests/lms/models/test_application_instance.py
tests/lms/services/application_instance_getter_test.py
tests/lms/util/_lti_launch_test.py
tests/lms/util/test_authorize_lms.py
tests/lms/util/test_canvas_api.py

Add a new `ApplicationInstanceGetter` (`"ai_getter"`) service that replaces three different functions that were spread throughout for getting `ApplicationInstance`'s from the DB, and fixes some bugs.
Implementing this as a service works out nicer than as `util` functions or as `ApplicationInstance` model methods because Pyramid makes the `request` object, including `request.db`, available to services so code doesn't need to pass in `request.db` every time it calls a service method. (Although you do need to use `request.find_service()` to get the service.)
It turns out that none of the code that was retrieving `ApplicationInstance`'s from the DB actually needed `ApplicationInstance` model objects. Only specific properties like `developer_key`, `lms_url`, etc are needed. So rather than …

Deduplicate application instance getter code with new ApplicationInstanceGetter service

---

.travis.yml
Jenkinsfile

Tox 3.8.0 has both broken tox-pip-extensions and changed Tox's command line option parsing in a way that breaks our Makefile. For now workaround the issues by pinning Tox to the previous version.

Pin Tox to 3.7.0 to fix our Tox envs

---

.travis.yml
Jenkinsfile
Makefile
README.markdown
tox.ini

A new version of `tox-pip-extensions` that works with Tox 3.8 is now out, so we can now upgrade to Tox 3.8, and I want the new auto-provisioning feature.

Require Tox 3.8 or newer

---

Dockerfile
Jenkinsfile

And move from Glider Labs to the official Alpine Linux images. Once this is merged we should be able to enable Dependabot's docker support to keep it up to date.

Upgrade to Alpine 3.9.2

---

lms/templates/lti_launches/new_lti_launch.html.jinja2

Make `new_lti_launch.html.jinja2` inherit from the base template. This means that the contents of our iframe is now a complete HTML document, rather than some HTML with no `<html>`, `<head>` or `<body>` as before.
It also means that stuff added to the base template in the future, such as JSON config objects, will now be present in the `new_lti_launch.html.jinja2` page as well.

Session 1/n: Make new_lti_launch.html.jinja2 inherit from base

---

lms/app.py
lms/subscribers/__init__.py
lms/subscribers/_template_environment.py
lms/templates/base.html.jinja2
tests/lms/conftest.py
tests/lms/subscribers/test___init__.py
tests/lms/subscribers/test__template_environment.py

This adds a `<script type="application/json" class="js-config">.../script>` tag to all our HTML pages (via the base template). The tag contains a JSON config object that'll contain config settings for our JavaScript code. The config object is currently empty.  JavaScript can retrieve the config object with code like:
config = document.querySelector('.js-config')

Session 2/n: Add JavaScript config object to pages

---

Jenkinsfile

Because we're running frontend tests in a separate Docker container there's a limit to the make-based concurrency we can take advantage of here.
Also the server has only 2 CPUs, and is usually running more than one build at once (even a single PR kicks off two Jenkins builds).
So I don't think this makes much difference.
Things we could do to improve this:
* Have Jenkins run only one build per PR/commit not two
* If we boost the server to one with at least four cores then `-j nproc` should be able to make more of a difference. (Eight cores would be better: I think some of our other projects, like h, have more than four separate make targets that could run concurrently.)
* Be able to run frontend tests in the same Alpine Docker container as the rest. This'd mean they could go in the same …

Speed up Jenkins by running things concurrently

---

lms/values.py

Add a "value object" type for an LTI user -- an immutable object with no methods that just exposes a set of user-related fields. In the future an instance of this class will be exposed as `request.user` whenever an LTI user is authenticated, to contain more info about the user than just the `request.authenticated_userid` string can.
The `LTIUser` for the current launch params or bearer token-authenticated request will always be able to be reconstructed from the verified parameters in the request itself, hence it's not necessary to save this object in the DB.
More fields can be added in the future but currently `LTIUser` contains the two fields from the LTI launch parameters that we're going to need in the future to generate a unique `request.authenticated_userid` string for an LTI user -- …

LTI bearer tokens 4/n: Add lms.values.LTIUser value type

---

lms/app.py
lms/authentication/__init__.py
lms/config/__init__.py
tests/lms/authentication/__init___test.py
tests/lms/config/__init___test.py
tests/lms/conftest.py

I'm going to be adding more authentication stuff and I need this to be here, not in config which is totally the wrong place for it.
Note that the authorization policy is still being set in lms.config. That should move too, to lms.authorization, but I don't need to do that right now.

LTI bearer tokens 3/n: Move authentication policy into lms.authentication

---

lms/validation/__init__.py
lms/validation/_launch_params.py
tests/lms/validation/_launch_params_test.py

Depends on <https://github.com/hypothesis/lms/pull/530>.
Add `lms.validation.LaunchParamsSchema` -- a [marshmallow](https://marshmallow.readthedocs.io/en/2.x-line/) schema for validating LTI launch params. It includes a `LaunchParamsSchema(request).lti_user()` convenience method that returns the [`LTIUser` object](https://github.com/hypothesis/lms/pull/530) for the request if it's a valid LTI launch request.
Not all LTI launch params are validated yet -- only the ones that we need right now. For now this schema is only going to be used (by a future pull request) for the purpose of validating the LTI launch params in order to set `request.authenticated_userid` and `request.user` (an `LTIUser` object), hence it only validates the params needed to do that. In the more distant future I …

LTI bearer tokens 5/n: Add a schema for validating LTI launch params

---

lms/validation/__init__.py
lms/validation/_bearer_token.py
lms/validation/_exceptions.py
tests/lms/validation/_bearer_token_test.py

Depends on https://github.com/hypothesis/lms/pull/530.
Add a schema for serializing, deserializing and validating `Bearer <ENCODED_JWT>` tokens in `Authorization` headers. The JWT encodes some of the user-related launch params from an LTI launch.
The way this is going to be used is:
1. When the user launches our app in their LMS, [`LaunchParamsSchema`](https://github.com/hypothesis/lms/pull/531) will be used to validate the launch params and set `request.user` to an [`LTIUser`](https://github.com/hypothesis/lms/pull/530) object.
2. The `BearerTokenSchema` in this PR will be used to **serialize** `request.user` into a signed and timestamped `"Bearer <ENCODED_JWT>"` string rendered into the page HTML.
3. JavaScript on the page will read this `"Bearer <ENCODED_JWT>"` string from the HTML and …

LTI bearer tokens 6/n: Add a schema for bearer tokens

---

lms/authentication/_helpers.py
tests/lms/authentication/_helpers_test.py
tests/lms/conftest.py

Depends on https://github.com/hypothesis/lms/pull/530
Add a new request property, `request.lti_user`, that contains a [`LTIUser`](https://github.com/hypothesis/lms/pull/530) object for the current LTI user whenever an LTI user has been authenticated either via launch params or a bearer token.
Uses [`LaunchParamsSchema`](https://github.com/hypothesis/lms/pull/531) to validate the launch params and create the `LTIUser` or, if that fails, tries [`BearerTokenSchema`](https://github.com/hypothesis/lms/pull/532) instead. If both fail then `request.lti_user` is `None`.

LTI bearer tokens 7/n: Add the `request.lti_user` property

---

lms/authentication/_helpers.py
tests/lms/authentication/_helpers_test.py

Depends on https://github.com/hypothesis/lms/pull/530.
Add a helper function for generating a Pyramid `request.authenticated_userid` string from an LTIUser value.
This requires us to decide what a `request.authenticated_userid` string should look like for an LTI user. I've gone with:
<USER_ID>:<OAUTH_CONSUMER_KEY>
where `<USER_ID>` is the value of the LTI launch param `user_id` (i.e. the user ID from the LMS) base 64 encoded so that we know it doesn't contain `":"`. And `<OAUTH_CONSUMER_KEY>` is the value of the `oauth_consumer_key` launch param which we know doesn't contain `":"` because it was originally generated by us (and the given oauth_consumer_key has been verified to match one in our DB before setting `request.authenticated_userid`).
A `request.authenticated_userid` string is …

LTI bearer tokens 8/n: Function for generating userids from LTI params

---

lms/authentication/__init__.py
lms/authentication/_lti_policy.py
lms/authentication/_policy.py
tests/lms/authentication/__init___test.py
tests/lms/authentication/_lti_policy_test.py
tests/lms/authentication/_policy_test.py

Depends on https://github.com/hypothesis/lms/pull/533 and https://github.com/hypothesis/lms/pull/534.
Add a Pyramid  [authentication policy](https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/security.html#creating-your-own-authentication-policy) that sets `request.authenticated_userid` to a userid string based on the LTI user whenever an LTI user is authenticated either via launch params or a bearer token.
This is in addition to the existing cookie-based `AuthTktAuthenticationPolicy` that's used for the `/reports` page. If no launch params or bearer token are found in the request then the new authentication policy delegates to the old `AuthTktAuthenticationPolicy`.

LTI bearer tokens 9/n: Add an authentication policy for LTI users

---

lms/config/resources.py
lms/routes.py
lms/subscribers/_template_environment.py
lms/templates/test.html.jinja2
lms/views/error.py
lms/views/lti_launches.py
lms/views/test.py
tests/lms/subscribers/test__template_environment.py

Depends on https://github.com/hypothesis/lms/pull/532
Add a `"Bearer <ENCODED_JWT>"` string encoding an [`LTIUser`](https://github.com/hypothesis/lms/pull/530) object for the current LTI user to the JavaScript config object in the page.
Also add some test pages for testing the use of this param from JavaScript.

LTI bearer tokens 10/n: Add `authorization_param` to `js_config`

---

lms/app.py

This wasn't being `config.include()`'d, `lms/views/__init__.py::includeme()` was not being called. I'm not sure how Pyramid was nonetheless picking up the view configurations.

Include lms.views

---

README.markdown
lms/config/__init__.py
lms/config/resources.py
lms/services/hapi.py
tests/lms/config/__init___test.py
tests/lms/conftest.py
tests/lms/services/hapi_test.py
tox.ini

Use H_API_URL_PUBLIC as the h API base URL to configure the client with, and H_API_URL_PRIVATE for server-to-server API requests. Remove the old H_API_URL setting.

Separate public and private h API URLs

---

lms/templates/base.html.jinja2

Allows child templates to insert their own `<script>` tags in the right location in the page by overriding the scripts block. This enables a page to have its own CSS file that's only for that page.

Feature flags cookie 4/n: Add styles block to base Jinja2 template

---

lms/config/__init__.py
lms/config/settings.py
tests/lms/config/__init___test.py
tests/lms/config/settings_test.py

Enable all custom deployment settings to be set by either an environment variable or, failing that, a config file setting.
Previously they could only be set by environment variables.
Config file settings are the default way of doing custom deployment settings in Pyramid (environment variable support is actually a custom feature added by us) so it's good to support the default.
This also allows new required settings to be added to `conf/development.ini` and committed to git, rather than requiring developers to add them to their local environment variables.

Feature flags cookie 1/n: Enable custom settings in config files

---

conf/development.ini
lms/app.py
lms/config/__init__.py
lms/session.py
tests/lms/session_test.py
tox.ini

Depends on <https://github.com/hypothesis/lms/pull/556/>.
Add a standard Pyramid session cookie to the app.
This is needed right now in order to be able to use flash messages but the session might end up getting used for other things in the future (a Pyramid app can only have one session) so I've paid basic attention to security.
Add a new required envvar: `COOKIE_SIGNING_SECRET`.
Add new `session.py` module that sets up a standard Pyramid signed (not encrypted) cookie session using the new secret.

Feature flags cookie 2/n: Add a Pyramid session cookie

---

lms/static/styles/lms.css
lms/templates/error.html.jinja2
lms/templates/lti_launches/unauthorized.html.jinja2
lms/templates/validation_error.html.jinja2

Pin modal dialogs to the top of the page (with a margin of 80px from the top of the page) instead of vertically centering them.
This prevents dialogs from jumping around when the height of a dialog's contents changes (e.g. a new element gets added to the bottom of the dialog) and the browser vertically re-centers the dialog using its new height.

Feature flags cookie 3/n: Pin modal dialogs to the top of the page

---

conf/development.ini
lms/config/__init__.py
lms/extensions/feature_flags/__init__.py
lms/extensions/feature_flags/_exceptions.py
lms/extensions/feature_flags/_helpers.py
lms/extensions/feature_flags/_routes.py
lms/extensions/feature_flags/_static/feature-flags.css
lms/extensions/feature_flags/_templates/cookie_form.html.jinja2
lms/extensions/feature_flags/_views.py
tests/lms/extensions/feature_flags/_helpers_test.py
tests/lms/extensions/feature_flags/_views_test.py
tox.ini

Depends on <https://github.com/hypothesis/lms/pull/556>. The diff will be clearer once https://github.com/hypothesis/lms/pull/556 has been merged and this has been rebased.
Add a new required setting `FEATURE_FLAGS_COOKIE_SECRET` / `feature_flags_cookie_secret`, which is a secret used to sign a JWT that is the value of the feature flags cookie.
Also add an optional `FEATURE_FLAGS_ALLOWED_IN_COOKIE` / `feature_flags_allowed_in_cookie` setting that is the list of feature flag names that're allowed to toggled on or off in the cookie and that will be shown on the `/flags` page.
Then add the `/flags` page itself, that lets you read and write the feature flag toggles in your cookie. This is just the page for reading and writing the cookie, but the cookie isn't actually used to determine feature …

Feature flags cookie 5/n: Add /flags page for toggling flags in cookie

---

lms/app.py
lms/extensions/feature_flags/__init__.py
lms/extensions/feature_flags/_providers.py
tests/lms/extensions/feature_flags/_providers_test.py

CI will be failing until earlier PRs in this series are merged.
This adds the support for actually reading a feature flag's state from the toggles set in the cookie via the `/flags` page.
`/flags/test` is a [test page that prints the values of the foo, bar and gar feature flags](https://github.com/hypothesis/lms/blob/master/lms/views/feature_flags_test.py). If you `export FEATURE_FLAGS_ALLOWED_IN_COOKIE="foo bar gar"` and then visit [the `/flags` page](https://github.com/hypothesis/lms/pull/561) you can toggle these on and off in your cookie and then visit `/flags/test` to test that they are in fact toggled on and off.

Feature flags cookie 6/n: Read feature flags from cookies

---

lms/extensions/feature_flags/__init__.py
lms/extensions/feature_flags/_routes.py
lms/extensions/feature_flags/views/_predicates.py
lms/extensions/feature_flags/views/cookie_form.py
lms/extensions/feature_flags/views/test.py
tests/lms/extensions/feature_flags/views/_predicates_test.py
tests/lms/extensions/feature_flags/views/cookie_form_test.py

Add a `feature_flag="my_feature"` view predicate (for use in Pyramid `@view_config(...)`'s) that can be used to toggle a view on or off depending on a feature flag, or to direct requests to one view or another depending on a feature flag.
Usage:
@view_config(route_name="foo", feature_flag="foo")
def view_that_will_be_called_when_feature_flag_is_on(request):
...
@view_config(route_name="foo")
def view_that_will_be_called_when_feature_flag_is_off(self):
...
Also add a test page at `/flags/test/view-predicate`.
To test it you can visit http://localhost:8001/flags/test/view-predicate and you should see that `view_that_doesnt_require_feature_flag()` was called. Then turn on the `"foo"` feature flag and visit t http://localhost:8001/flags/test/view-predicate again and you should see that …

Auth popup 0/n: Add feature_flag="..." view predicate

---

lms/views/authentication.py

Don't show the login form (https://lms.hypothes.is/login) except when the user is trying to visit the reports page (https://lms.hypothes.is/reports) and is not logged in.
The type of login provided by the `/login` form is only used by the `/reports` page. If an unauthenticated user tries to visit some other view that requires authentication (for example a view that requires
authentication by LTI launch params, or by a bearer token, maybe an API view) it makes no sense to respond with the login form.
Unauthenticated requests to these other authentication-requiring views will now use Pyramid's default forbidden view (a 403 Forbidden response whose body is a plain HTML error page) instead.

Auth popup 1/n: Don't show login form other than for /reports

---

lms/validation/_bearer_token.py
tests/lms/validation/_bearer_token_test.py

When it opens the upcoming Canvas API authorization endpoint in a popup window JavaScript code is going to have to authenticate a `GET` request using one of our JWT bearer tokens, not just use them to authenticate XHR API requests as envisioned.
Currently these authorization params can only be put in `Authorization` headers in requests, but that doesn't work for the simple `GET` request that happens when JavaScript gets the browser to open a URL in a popup window.
Add support for reading authorization params from query params so that the popup window request can be authenticated.

Auth popup 2/n: Read auth params from query strings

---

lms/routes.py
lms/templates/content_item_selection/new_content_item_selection.html.jinja2
lms/util/authorize_lms.py
lms/views/api/canvas/authorize.py
tests/lms/views/api/canvas/authorize_test.py

Depends on https://github.com/hypothesis/lms/pull/567 and https://github.com/hypothesis/lms/pull/570.
* Add a `/api/canvas/authorize` endpoint. This is intended to be opened by the frontend code in a popup window with a `?authorization=Bearer <JWT>` query param in the URL in order to get the user to authorize us with Canvas. The endpoint constructs the correct Canvas authorize URL and redirects the popup window to it.
* Also, when the `"new_oauth"` feature flag is on, override `/canvas_oauth_callback`, the OAuth 2 redirect URI that Canvas directs the popup window back to when the user clicks Authorize or Cancel, with a stub view that will be filled out later.
* When the `"new_oauth"` feature flag is on the preexisting OAuth 2 code has been hacked to *not* redirect the iframe to the Canvas …

Auth popup 3/n: Add canvas API authorize page

---

lms/static/scripts/karma.config.js
package.json
yarn.lock

These dependencies are currently not used. When we do want to do mocking in future in the LMS frontend code, I'm going to recommend we use a [different approach](https://github.com/hypothesis/client/pull/1061) that was recently adopted in the client (see the changes in `package.json` and `karma.config.js` in the linked PR for the code that sets this up).

Remove unused proxyquire dependencies

---

Jenkinsfile
Makefile
tox.ini

Use Jenkins Pipeline's `parallel` to run everything in separate parallel stages, rather than using `make -j` to do the same.
Also enable tox/virtualenv's `sitepackages` on Jenkins which speeds builds up by 20-30secs or more. Builds are less then 2.5 mins now.
There were intermittent build failures with `make -j` due to a (probably
fixable) race condition with tox. `make -j` also didn't enable the
frontend tests to be run in parallel with everything else because the
frontend tests need to be run from a different Docker image (and
therefore a different instance of `make`). Finally, with `make -j`
Jenkins is unaware of the concurrency whereas with Jenkins Pipeline
parallel stages Jenkins can show the different stages running
concurrently in its UI and can label the stdout and stderr with …

Refactor Jenkinsfile to use Jenkins's parallel stages

---

Dockerfile
Makefile
package.json

This PR restructures the Docker build to use a separate stage for building the frontend assets, following the example in the h repo:
- It makes the Docker image smaller, as it won't have Node + Node's build dependencies in it
- It decouples the Node version used to build the frontend assets from the image used to run the Python app.
- I changed the install process to use `yarn install` rather than `npm install`. Since the repo has a yarn lockfile, we need to use yarn rather than npm in order to ensure the lockfile is respected. We could potentially remove yarn and try to use just npm instead, but that was outside the scope of what I wanted to do here
I also added a `run-docker` Makefile target to facilitate testing of the Docker image locally. I'd be happy for someone to submit a better …

Use a separate Docker build stage to build the frontend assets

---

lms/validation/__init__.py
lms/validation/_helpers.py
tests/lms/validation/__init___test.py
tests/lms/validation/_helpers_test.py

Our Webargs/Marshmallow <> Pyramid integration includes our own Pyramid view deriver that lets you use a schema to guard a view:
```python
@view_config(..., schema=CANVAS_OAUTH_CALLBACK_SCHEMA)
def oauth2_redirect(request):
...
```
This is used by [`oauth2_redirect`](https://github.com/hypothesis/lms/blob/cc24cdeafa591307912963ca098c3addb1d6ca42/lms/views/api/canvas/authorize.py#L41) and [`canvas_oauth_callback`](https://github.com/hypothesis/lms/blob/cc24cdeafa591307912963ca098c3addb1d6ca42/lms/views/oauth.py#L21).
It currently supports webargs dict-based schemas like [`CANVAS_OAUTH_CALLBACK_SCHEMA`](https://github.com/hypothesis/lms/blob/cc24cdeafa591307912963ca098c3addb1d6ca42/lms/validation/_oauth.py#L6-L9) as the argument to `schema=`.
Webargs also allows schemas to be …

Validate OAuth 2 state param 1/n: Add support for schema classes

---

lms/views/api/canvas/authorize.py
tests/lms/views/api/canvas/authorize_test.py

When the Canvas authorize popup window is opened generate secret string to pass to Canvas as the OAuth 2 `state` param and also save this string in the session cookie for later comparison to the `state` param that Canvas passes back to us.
We were already generating the `state` param and passing it to Canvas, this PR adds the saving it in the session cookie.
The session cookie itself was already added in a [previous PR](https://github.com/hypothesis/lms/pull/557). It's a signed, **not** encrypted, HTTP-only, secure cookie that expires after 20 mins of inactivity. This PR just relies on the session cookie for signing and expiry, doesn't do any of its own.

Validate OAuth 2 state param 3/n: Add OAuth 2 "state" params to session cookie

---

lms/validation/__init__.py
lms/validation/_oauth.py
lms/views/api/canvas/authorize.py
lms/views/oauth.py
tests/lms/validation/_oauth_test.py

Depends on https://github.com/hypothesis/lms/pull/586/
This shouldn't make any functional difference, but means that the schema can access more Marshmallow functionality in future.

Validate OAuth 2 state param 2/n: Turn CANVAS_OAUTH_CALLBACK_SCHEMA into a class

---

lms/validation/_oauth.py
tests/lms/validation/_oauth_test.py

Depends on https://github.com/hypothesis/lms/pull/586, https://github.com/hypothesis/lms/pull/587 and https://github.com/hypothesis/lms/pull/588/.
When the user clicks <kbd>Authorize</kbd> and Canvas redirects the popup window back to our OAuth 2 redirect_uri (`/canvas_oauth_callback`) check that the `state` param in the request's query params matches the one that we previously generated and saved in the session cookie. If the param doesn't match then don't call the view, and send back a validation error response instead.

Validate OAuth 2 state param 4/n: Validate state param on oauth2 redirect

---

lms/routes.py
lms/views/api/canvas/authorize.py
lms/views/api/canvas/files.py
lms/views/api/error.py
tests/lms/views/api/error_test.py

Authentication works correctly (a missing or incorrect `Authorization` header will result in a 403 JSON response).
But when authenticated the actual API response is faked.
To test:
1. Turn on the new_oauth feature flag.
1. Get a JWT. The easiest way to do this is to launch the app in Canvas then inspect the iframe and copy the JWT from the `<script type="application/json" class="js-config">` near the top of the iframe.
2. Send a request: `http GET "http://localhost:8001/api/canvas/courses/4/files" Authorization:"Bearer ***"`
The course ID (`4` above) doesn't do anything yet but in the real version this'll have to be the actual Canvas course ID.
3. Send a request with a missing or invalid JWT and get a 403: `http GET "http://localhost:8001/api/canvas/courses/4/files" Authorization:"Bearer …

Add a stubbed version of the upcoming Canvas files API proxy

---

Makefile
conf/development.ini
lms/config/__init__.py
tests/lms/conftest.py
tox.ini

Add a new, required deployment setting `oauth2_state_secret`. This will be used for signing JWT's that're used as OAuth 2 `state` params.

state param auth 2/n: Add new oauth2_state_secret deployment setting

---

lms/validation/_helpers/_schema.py
lms/validation/_oauth.py
tests/lms/validation/_helpers/_schema_test.py

Depends on https://github.com/hypothesis/lms/pull/601.
The standard way to initialize a marshmallow schema is:
```python
schema = MySchema()
schema.context["request"] = request
```
But our existing schemas are initialized like this instead:
```python
schema = MySchema(request)
```
Fix `CanvasOAuthCallbackSchema` to be initialized in the same way as our other schema, instead of the way it's done in the webargs docs. Fix the `initialize_schema()` helper to do it this way as well.

state param auth 3/n: Fix how CanvasOAuthCallbackSchema is initialized

---

lms/validation/__init__.py
lms/validation/_exceptions.py
lms/validation/_oauth.py
tests/lms/validation/_oauth_test.py

Extend `CanvasOAuthCallbackSchema` to support reading the LTI user from an OAuth 2 `state` query parameter.
No code uses this yet, but the functionality has been added to `CanvasOAuthCallbackSchema`:
`CanvasOAuthCallbackSchema.state_param()` is a method that generates and returns a `state` param capable of authenticating the LTI user. The `state` param is a signed and timestamped JWT containing the current `request.lti_user` and a CSRF token that's also added to the session. A view should call `state_param()` to get the value for the `?state=<VALUE>` parameter for putting into a Canvas authorization endpoint URL before redirecting the browser to it (this will be done in the next PR).
`CanvasOAuthCallbackSchema.lti_user()` is a method that returns the `LTIUser` value from the current …

state param auth 4/n: Support reading LTI user from OAuth2 state param

---

lms/authentication/_helpers.py
lms/views/api/canvas/authorize.py
tests/lms/authentication/_helpers_test.py
tests/lms/views/api/canvas/authorize_test.py

<https://github.com/hypothesis/lms/pull/604> extended `CanvasOAuthCallbackSchema` to be able to serialize and deserialize OAuth 2 `state` param values that are signed and timestamped JWTs containing the `LTIUser` value and a CSRF token. This PR:
1. Has the `authorize()` (the view that redirects the popup window to Canvas's authorize page) use one of these JWTs as the `state` query param it passes to Canvas
2. Has the authentication policy use the `state` param to set `request.authenticated_userid`, `request.effective_principals`, and `request.lti_user`.
* Turn on the new_oauth feature flag
* Turn off debug mode: `export DEBUG="false"
* Launch the app in Canvas, open the popup window, and authorize. After Canvas redirects back to our redirect_uri it'll now show the authenticated LTIUser …

state param auth 5/n: Use authenticatable state param

---

lms/migrations/versions/f36f9a0aadf4_add_oauth2_token_table.py

This table is replacing the existing `tokens` table which will (eventually) be deleted.

Get access tokens 1/n: DB migration to add oauth2_token table

---

lms/migrations/versions/f36f9a0aadf4_add_oauth2_token_table.py
lms/models/__init__.py
lms/models/application_instance.py
lms/models/oauth2_token.py
tests/lms/models/oauth2_token_test.py

A model class for storing OAuth 2 access tokens along with their optional refresh tokens and expiry times, keyed by application instance (consumer key) and LTI `user_id`.
This will eventually replace the `Token` model class which is going to be deleted.

Get access tokens 2/n: Add OAuth2Token model class

---

lms/services/__init__.py
lms/services/_helpers/__init__.py
lms/services/_helpers/canvas_api.py
lms/services/canvas_api.py
tests/lms/services/_helpers/canvas_api_test.py
tests/lms/services/canvas_api_test.py

... with code for sending an access token request to the Canvas API and returning the response.
Handling error responses from the Canvas API is not supported yet.

Get access tokens 3/n: Add CanvasAPIClient service

---

lms/views/api/canvas/authorize.py
tests/lms/views/api/canvas/authorize_test.py

In the `redirect_uri` view (which is what receives the popup window redirect from Canvas containing the authorization code query param) exchange the authorization code for an access token in a server-server
request to the Canvas API.
The access token and its refresh token and expiry time get saved to the DB but otherwise they aren't used yet.
If the DB already contains an access token for this user (same consumer key and user_id) that token will be updated rather than saving a second one.

Get access tokens 4/n: View code for getting access tokens

---

lms/static/scripts/file_picker_v2/components/FileList.js
lms/static/styles/components/_Button.scss
lms/static/styles/components/_FileList.scss
lms/static/styles/components/_Table.scss

Fix an issue with long file names in the new file picker, and update the cursor for buttons for consistency with the h website and client.
**Before:**
**After:**

Elide long file names in the new file picker

---

lms/services/_helpers/canvas_api.py
lms/services/canvas_api.py
lms/views/api/canvas/files.py
tests/lms/services/_helpers/canvas_api_test.py
tests/lms/services/canvas_api_test.py
tests/lms/views/api/canvas/files_test.py

As with the other Canvas proxy APIs there's no error handling yet.
There are several individual refactoring commits first, and then the final commit does all the work of replacing the API.
Usage:
```
$ http GET "http://localhost:8001/api/canvas/files/180/public_url" Authorization:"Bearer ***"
HTTP/1.1 200 OK
Connection: close
Content-Length: 607
Content-Type: application/json
{
"public_url": "https://instructure-uploads.s3.amazonaws.com/***"
}
```

Replace the fake public URL API with a real one

---

lms/validation/_bearer_token.py

Support reading authorization JWTs from form fields, as well as from
headers and query strings.
We'll need this in future as we're going to have a need for
authenticating form submissions (and using a form field seems nicer than
a query string on the form's `action` URL).
I didn't add a test for this because I couldn't find a way to create a
test that would fail if only "querystring" (and not "form") was in the
`locations=[...]` list and then would pass when "form" was added. Adding
the `authorization` param to the dummy request's `.params` will work
with either "querystring" or "form" or both, for example.

Read authorization param from form fields

---

lms/views/decorators/__init__.py
lms/views/decorators/h_api.py
lms/views/decorators/reports.py
tests/lms/views/decorators/reports_test.py

This can be added to LTI launch views like so:
@view_config(
decorator="lms.views.decorators.report_lti_launch",
...
)
def my_lti_launch_view(context, request):
For details see the decorator parameter documented here:
https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/viewconfig.html?highlight=decorator#non-predicate-arguments
It will add a row to the `lti_launches` DB table each time the view is
called. Rows from this table are the data used by the `/reports` page.
New views will use this instead of a helper function that the legacy
views used to append to the same table:
https://github.com/hypothesis/lms/blob/d06cae8bb0778867588c3f7e95c2050385a8776d/lms/views/lti_launches.py#L80-L93
Nothing uses the new view decorator yet.

Add report_lti_launch view decorator

---

lms/views/content_item_selection.py
lms/views/decorators/__init__.py
lms/views/decorators/legacy_h_api.py
lms/views/lti_launches.py
tests/lms/views/decorators/legacy_h_api_test.py

New versions of these decorators are going to be made that work as proper Pyramid view decorators, and these now `legacy_*` ones will eventually be deleted.

Rename the h_api decorators to legacy_*

---

lms/views/decorators/__init__.py
lms/views/decorators/h_api.py
tests/lms/views/decorators/h_api_test.py

Depends on https://github.com/hypothesis/lms/pull/640
These are the same decorators (and the same tests) as `lms.views.decorators.legacy_h_api`, but rewritten to work as Pyramid view decorators instead of plain Python `@decorator`s.
The new decorators aren't used yet, but will be used by upcoming new Pyramid views.
I renamed one of the decorators from `create_course_group()` to `upsert_course_group()` to match with `upsert_h_user()`, and also updated its docstring. The previous `create_course_group()` decorator (now `legacy_create_course_group()`)'s name was out of date since the decorator had been updated to *create or update* the course group.
There was a little bit of validation in the legacy decorators (get a param from the request, and if the param is missing do a 400). I've removed …

Add new h_api view decorators

---

lms/config/resources.py
tests/lms/config/resources_test.py

This enables protecting a view like this:
@view_config(..., permission="launch_lti_assignment")
def my_view(request):
...
and the view will only be callable by verified LTI users. This is going to be used to protect upcoming new assignment launch views.

Add "launch_lti_assignment" permission to LTI users

---

lms/migrations/versions/4ab4d06f7e3f_add_unique_constraint_to_module_item_.py
lms/models/module_item_configuration.py

In practice no two module_item_configurations with the same
resource_link_id, tool_consumer_instance_guid and document_url are ever
created, and if a duplicate did get into the DB the code would
misbehave.
See:
https://github.com/hypothesis/lms/blob/3430effa15d8f8137db908f5c40ab1df5c85f908/lms/views/lti_launches.py#L70-L77
So add a DB constraint to make sure that this can't happen, and also to
speed up a common DB query by adding an index.

Add unique constraint to module_item_configurations

---

lms/views/__init__.py
lms/views/predicates/__init__.py
lms/views/predicates/_helpers.py
lms/views/predicates/_lti_launch.py
tests/lms/views/predicates/_helpers_test.py
tests/lms/views/predicates/_lti_launch_test.py
tox.ini

Add a few custom Pyramid view predicates intended to be used with future LTI launch views.
<del>I don't want to merge this quite yet until I've finished the view code that'll use it, but it can be reviewed now.</del>
Example of how these would be used to direct different `POST` requests to the same `/lti_launches` URL to different views, depending on the properties of the requests:
```python
@view_config(
canvas_file=True,
renderer="lms:templates/basic_lti_launch/canvas_file_basic_lti_launch.html.jinja2",
)
def canvas_file_basic_lti_launch(self):
...
@view_config(db_configured=True)
def db_configured_basic_lti_launch(self):
...
@view_config(url_configured=True)
def url_configured_basic_lti_launch(self):
...
@view_config(
authorized_to_configure_assignments=True,
configured=False, …
```

Launch views refactor 1/n: Add LTI launch view predicates

---

lms/services/__init__.py
lms/services/canvas_api.py
lms/services/exceptions.py
tests/lms/services/canvas_api_test.py

This causes the `public_url` API to raise `CanvasAPIError` if we don't yet have an access token (expired or otherwise) for the user (e.g. if this is the first time this user has launched a Canvas Files assignment).
And it makes both the `list_files` and `public_url` APIs raise `CanvasAPIError` if the Canvas API request fails to get a response (e.g. a network timeout) or sends an unsuccessful response (e.g. an authorization error).
There are plenty of error cases not covered yet, and the code and tests aren't factored how I want, but this will allow us to get on with the next stage which is to integrate the new OAuth2 authorization into the assignment launches.

Launch views refactor 2/n: Raise CanvasAPIError if Canvas API request fails

---

lms/validation/_bearer_token.py
lms/validation/_launch_params.py
lms/values.py
lms/views/decorators/h_api.py
lms/views/predicates/_lti_launch.py
tests/lms/authentication/_helpers_test.py
tests/lms/conftest.py
tests/lms/validation/_bearer_token_test.py
tests/lms/validation/_launch_params_test.py
tests/lms/validation/_oauth_test.py
tests/lms/views/decorators/h_api_test.py
tests/lms/views/predicates/_lti_launch_test.py

`LTIUser` objects are the values that get serialized into JWT authorization params that are then included in XHR requests, form submissions and OAuth 2 redirects, deserialized again, and used to authenticate the user making the request.
We have an upcoming need to know the user's LTI roles not just their `user_id` and `oauth_consumer_key`, so add a new field `LTIUser.roles`.
This of course will invalidate any existing authorization params out there in the wild in people's open tabs. Fortunately this is all still behind a feature flag so we're fine.

Add LTIUser.roles value

---

lms/validation/__init__.py
lms/validation/_module_item_configuration.py
tests/lms/validation/_module_item_configuration_test.py

This schema will be used to protect the `/module_item_configurations` route. When an unconfigured assignment is launched the content item form that's rendered gets submitted to `/module_item_configurations` so that the chosen document URL can be saved in the DB. This schema will be used to validate those form submissions.

Add ConfigureModuleItemSchema

---

lms/services/launch_verifier.py
lms/templates/basic_lti_launch/basic_lti_launch.html.jinja2
lms/templates/basic_lti_launch/canvas_file_basic_lti_launch.html.jinja2
lms/templates/basic_lti_launch/unconfigured_basic_lti_launch.html.jinja2
lms/templates/basic_lti_launch/unconfigured_basic_lti_launch_not_authorized.html.jinja2
lms/views/basic_lti_launch.py
lms/views/predicates/_lti_launch.py
tests/lms/views/basic_lti_launch_test.py
tests/lms/views/predicates/_lti_launch_test.py

Depends on https://github.com/hypothesis/lms/pull/639, https://github.com/hypothesis/lms/pull/644 and https://github.com/hypothesis/lms/pull/645.
Add new views and templates for handling LTI assignment launches when the `new_oauth` feature flag is on.

Launch views refactor 3/n: Add new assignment launch views

---

lms/routes.py
lms/views/api/canvas/files.py
tests/lms/views/api/canvas/files_test.py

Rather than returning the public URL of a Canvas file and making the
frontend construct the Via URL from it, our proxy API should return the
Via URL for the Canvas file complete with https://via.hypothes.is/
prefix and query parameters. The frontend code can just use this Via URL
directly.

Change the public_url API to via_url

---

lms/config/__init__.py
lms/templates/basic_lti_launch/unconfigured_basic_lti_launch.html.jinja2
lms/views/basic_lti_launch.py
tests/lms/views/basic_lti_launch_test.py

There are only two deployments of this app - lms.hypothes.is and qa-lms.hypothes.is - and both of those have the Google Drive-related environment variables set. This app isn't intended to be used by third parties. So there's no need for the Google Drive-related settings to be optional, and the code can be simpler if it assumes that these settings are always present.
In development environments, if the developer wants to test the app without going to the trouble of creating a Google Drive client, they can just set these envvars to placeholder values as the README already says to do. Everything will work fine except that clicking on the **Select PDF from Google Drive** won't work.
We could make this even easier for developers by providing placeholder values in `development.ini` but that …

Fix the new Google Picker in non-Canvas LMS's

---

lms/config/__init__.py
lms/resources/__init__.py
lms/resources/_default.py
lms/resources/_lti_launch.py
lms/routes.py
tests/lms/resources/_default_test.py
tests/lms/resources/_lti_launch_test.py
tests/lms/services/hapi_test.py
tests/lms/views/decorators/h_api_test.py
tests/lms/views/decorators/legacy_h_api_test.py
tests/lms/views/test_lti_launches.py

For some reason the app's Pyramid resources were put in a `resources.py` module in `lms/config/` even though they have nothing to do with config.
Extract these into a `lms/resources/` package.
Also renamed `Root` to `DefaultResource` and `LTILaunch` to `LTILaunchResource`. This makes it more obvious what these classes are and makes them easier to grep for.
Also add tests for `DefaultResource`.

Move lms/config/resources.py into the right place

---

tox.ini

Pin Prospector to the latest version that works.
Pinning it in `tox.ini` like this won't enable it to be automatically updated by Dependabot. For the work needed to enable Dependabot to handle this see https://github.com/hypothesis/lms/pull/691

Fix `make lint` by pinning Prospector

---

lms/static/scripts/file_picker_v2/index.js
lms/templates/base.html.jinja2
lms/templates/basic_lti_launch/unconfigured_basic_lti_launch.html.jinja2
lms/templates/content_item_selection.html.jinja2
lms/templates/content_item_selection/new_content_item_selection.html.jinja2

This PR fixes a couple of things that were confusing about the JSON config that the LMS frontend / file picker app reads.
- The base template defined a "js-config" block, but this was not actually used anywhere
- The file picker app read its config from a "js-hypothesis-config" block, which was defined in each of the views that rendered the app. The "js-hypothesis-config" name is overloaded as elsewhere in the app it is used for configuration for the _Hypothesis client_

Rename the JSON config block that the LMS frontend app reads from

---

lms/templates/base.html.jinja2
lms/templates/basic_lti_launch/basic_lti_launch.html.jinja2

We're going to be needing the `js-rpc-server-config`,
`js-hypothesis-config` in pages that don't use the
`basic_lti_launch.html.jinja2` template or a sub-template thereof. But
currently these config objects are rendered by
`basic_lti_launch.html.jinja2` so are only available in pages based on
that template.
Move the `<script class="js-rpc-server-config">` and
`<script class="js-hypothesis-config">` objects out of the
`basic_lti_launch.html.jinja2` template and into the `base.html.jinja2`
template. Also move the `<script>` tags for the postMessage JSON RPC
server JavaScript with them.
This puts these JSON objects in the same place in the templates as the
existing `<script class="js-config">` object.
Rather than the inclusion of these objects in the page being conditional
on whether the …

Move RPC server and client configs into base template

---

lms/resources/_lti_launch.py
lms/templates/content_item_selection.html.jinja2
lms/templates/content_item_selection/new_content_item_selection.html.jinja2
tests/lms/resources/_lti_launch_test.py

Rename `authorization_param` in the `js-config` object to `authToken`. The new file picker JavaScript already reads `authToken` not `authorization_param`, and the naming style matches that of other JavaScript config settings.
Depends on https://github.com/hypothesis/lms/pull/694

Rename authorization param

---

lms/templates/base.html.jinja2
lms/templates/basic_lti_launch/unconfigured_basic_lti_launch.html.jinja2
lms/templates/content_item_selection.html.jinja2
lms/views/basic_lti_launch.py
lms/views/content_item_selection.py
tests/lms/views/basic_lti_launch_test.py
tests/lms/views/content_item_selection_test.py
tests/lms/views/test_lti_launches.py

Depends on https://github.com/hypothesis/lms/pull/694, https://github.com/hypothesis/lms/pull/693 and https://github.com/hypothesis/lms/pull/695.
Read the JavaScript config object `<script type="application/json" class="js-config">` from the Pyramid context object (`LTILaunchResource.js_config`) instead of rendering it directly in templates.
This makes the generation and rendering of js-config consistent with that of js-rpc-server-config and js-hypothesis-config, and means that the js-config object is generated in unit-tested Python code rather than in untested template code. js-config can be modified on a per-view basis by having the Python view mutate `request.context.js_config`.
1. Have `base.html.jinja2` render `context.js_config` into the page, as it already does with …

Read the js_config object from the Pyramid context

---

lms/templates/basic_lti_launch/canvas_file_basic_lti_launch.html.jinja2
lms/views/basic_lti_launch.py
tests/lms/views/basic_lti_launch_test.py

Fix `canvas_file_basic_lti_launch()` to not fetch the Canvas file's
public URL from the Canvas API as part of the initial response to the
launch request. Instead add the proxy API URL that will return the
Canvas file's URL to the `"urls"` in the JavaScript config object.
The idea is that JavaScript code will make an XHR request to the
`via_url` proxy API and use the Canvas file URL from the response to
inject the Via iframe into the DOM.
This means that the server's response to the initial launch request can
be fast as it doesn't need to talk the the Canvas API, and all requests
to the Canvas API are kept within the `/api/canvas/` proxy API views.
For more reasoning see
https://github.com/hypothesis/lms/issues/622#issuecomment-499909135

Don't fetch Canvas file URLs on launch

---

lms/templates/basic_lti_launch/canvas_file_basic_lti_launch.html.jinja2
lms/views/basic_lti_launch.py

This reverts commit 38f37e8dbcb444e87d019a49d1441a18d0ebf629.
canvas_file_basic_lti_launch.html.jinja2 doesn't add anything on top of
the base template but it's needed for future commits that will add to
it.

Add back canvas_file_basic_lti_launch.html.jinja2

---

lms/services/exceptions.py
lms/views/api/canvas/files.py
lms/views/decorators/h_api.py
lms/views/decorators/legacy_h_api.py
tests/lms/views/api/canvas/files_test.py
tests/lms/views/decorators/h_api_test.py
tests/lms/views/decorators/legacy_h_api_test.py

Change `lms.services.HAPIError`, `HAPINotFoundError` and
`CanvasAPIError` into simple `Exception` subclasses rather than
subclassing `HTTPInternalServerError`.
The reason for subclassing `HTTPInternalServerError` was that views that
call services that raise these errors could just call them blindly, not
catching the services exceptions that might be raised, and since the
services exceptions were `HTTPError`s they would cause the correct 500
Internal Server Error responses to be sent.
While this does simplify view code and tests by removing
exception-wrapping from views, it causes some problems:
We want services exceptions to all be subclasses of
`lms.services.ServiceError`. This is so that some code calling a
services method can just catch `ServiceError` and this will catch any
error …

Don't subclass HTTPError in services

---

lms/services/__init__.py
lms/services/exceptions.py
lms/views/api/canvas/files.py
lms/views/decorators/h_api.py
lms/views/decorators/legacy_h_api.py
tests/lms/services/exceptions_test.py
tests/lms/views/api/canvas/files_test.py
tests/lms/views/decorators/h_api_test.py
tests/lms/views/decorators/legacy_h_api_test.py

Depends on https://github.com/hypothesis/lms/pull/710.
Extract a base class `ExternalRequestError` to remove duplicate code
from `HAPIError` and `CanvasAPIError`.

Deduplicate exception classes

---

lms/services/__init__.py
lms/services/canvas_api.py
lms/services/exceptions.py
lms/static/styles/file-picker-app.scss
lms/templates/api/canvas/oauth2_redirect_error.html.jinja2
lms/views/api/canvas/authorize.py
tests/lms/services/canvas_api_test.py
tests/lms/views/api/canvas/authorize_test.py

Depends on <https://github.com/hypothesis/lms/pull/710> and <https://github.com/hypothesis/lms/pull/711>.
When we send the access token request to Canvas, catch any error
responses or network timeouts etc and show the user an error page with a
"Try again" button.
`CanvasAPIClient.get_token()` now raises `CanvasAPIServerError` if
there's a problem with the access token request.
The `oauth2_redirect()` view that calls `CanvasAPIClient.get_token()`
catches the `CanvasAPIServerError` and wraps it in an
`HTTPInternalServerError`.
This causes Pyramid to call the new `oauth2_redirect_error()` exception
view which renders a template with a "Try again" button that links back
to the original `authorize()` view to restart the flow.
The user is put into an infinite loop, within the popup window, of …

Oauth2 redirect error handling

---

lms/validation/__init__.py
lms/validation/_bearer_token.py
lms/validation/_helpers/__init__.py
lms/validation/_helpers/_base.py
lms/validation/_launch_params.py
lms/validation/_module_item_configuration.py
lms/validation/_oauth.py
tests/lms/validation/__init___test.py
tests/lms/validation/_module_item_configuration_test.py
tests/lms/validation/_oauth_test.py

Depends on <https://github.com/hypothesis/lms/pull/715>.
In various places we use the `requests` library to send requests to the Canvas API. `requests` will raise if we don't get a response (network error or timeout) or if the response is non-2xx. But after that we still need to validate that:
1. We can successfully parse the response body as JSON
2. The JSON contains all the required params that we need from the response
3. Each param has a valid value
Unfortunately `lms.validation` assumes that our validation schemas are all for validating Pyramid requests. So refactor `lms.validation` a little to also enable schemas that validate requests-library response objects:
1. Add `_BaseSchema` as the base class for _all_ validation schemas, just to remove some boilerplate that we were putting …

Enable validating requests-library responses using our validation schemas

---

lms/services/canvas_api.py
lms/services/exceptions.py
lms/validation/__init__.py
lms/validation/_helpers/_base.py
lms/validation/_oauth.py
tests/lms/services/canvas_api_test.py
tests/lms/services/exceptions_test.py
tests/lms/validation/_oauth_test.py

Depends on ~~https://github.com/hypothesis/lms/pull/715~~, https://github.com/hypothesis/lms/pull/716, and ~~https://github.com/hypothesis/lms/pull/717~~.
This adds `CanvasAccessTokenResponseSchema`, our first `RequestsResponseSchema` subclass, and changes `CanvasAPIClient.get_token()` to validate the Canvas API's access token response with it.
`CanvasAPIClient.get_token()` raises `CanvasAPIServerError` if Canvas's response is invalid, and the relevant view already catches `CanvasAPIServerError`'s and turns them into a "Something went wrong, try again" page.

Validate Canvas API access token responses

---

Jenkinsfile

Each build task spins up its own Docker container and, for the backend tasks, each container also installs build dependencies (build-base, python3-dev etc.). It appears that this has significant overhead and on our current Jenkins setup, builds are prone to failing as a result. Specifically, we're seeing quite a lot of timeouts when Jenkins is invoking `docker run` to run backend tests and when trying to kill containers after a successful test run. See my notes and linked issues [in this Slack message](https://hypothes-is.slack.com/archives/C1MA4E9B9/p1560333606006300).
Reduce the contention by combining the backend
lint/docstrings/formatting tasks into one, and the frontend lint + tests
into one.
~~I also added config to suppress some lint failures seen in a fresh build of `make …

Reduce the number of parallel build tasks

---

lms/services/__init__.py
lms/services/exceptions.py
tests/lms/services/exceptions_test.py

Given an exception caused by an attempted Canvas API request, there's
quite a lot of logic about how we wrap that exception in the appropriate
lms.services.CanvasAPIError subclass:
* The exception may be a requests exception representing a 401
Unauthorized response from Canvas, in which case we wrap it in a
CanvasAPIAccessTokenError.
* Any other exception (a requests exception representing a 400 Bad
Request response from Canvas, or a 500 Server Error from Canvas, or a
network error, or a validation error when validating Canvas's
response, ...) gets wrapped in a CanvasAPIServerError.
* In cases where a response was actually received from Canvas it's set
as the exception's `response` attribute, otherwise `response` is
`None`
* The exception has a `details` attribute containing a string …

Canvas API backend error handling 1/6: Add CanvasAPIError factory

---

lms/services/_helpers/canvas_api.py
lms/services/canvas_api.py
tests/lms/services/_helpers/canvas_api_test.py
tests/lms/services/canvas_api_test.py

Depends on <https://github.com/hypothesis/lms/pull/729> for CI to pass.
Add a `validated_response()` helper that takes a `requests.PreparedRequest` and an optional validation schema, sends the request, and validates the response. It'll either return a `requests.Response` with the parsed and validated params as `response.parsed_params`, or if anything goes wrong with the request or validation it'll raise `CanvasAPIAccessTokenError` or `CanvasAPIServerError`.
Change the existing `get_token()` method to use the new helper for the access token request to the Canvas API.
In the future validation and error handling will be added to the other Canvas API requests, using the same helper.
This isn't really a Canvas-specific helper, it's really just a helper for working with `requests`, and some …

Canvas API backend error handling 2/6: Add validated_response() helper method

---

lms/validation/_helpers/_base.py

Add support for schemas that validate lists of objects, where each object in the list is expected to have the same schema. The schema will be applied to each object in the list in turn.

Canvas API backend error handling 3/6: Add collection support to validation schemas

---

lms/static/scripts/file_picker_v2/components/FilePickerApp.js
lms/static/scripts/file_picker_v2/components/test/FilePickerApp-test.js
lms/templates/content_item_selection/new_content_item_selection.html.jinja2
lms/views/basic_lti_launch.py
lms/views/content_item_selection.py
tests/lms/views/basic_lti_launch_test.py
tests/lms/views/content_item_selection_test.py

- Add `enableLmsFilePicker` config option to file picker JS app and set
it in the `content_item_selection` view
It would have been possible to just test for the presence of the existing
`courseId` config field which is only set when the Canvas files API is
available. However I opted to use a separate, more explicit flag instead, as
it is possible that a field like "courseId" might be set for other
reasons in future, and that other LMSes may use different conditions
to enable or disable the LMS file picker.
- Change `new_content_item_selection` template to use the `js-config`
JSON script tag rendering provided by the base template instead of
duplicating it. All the necessary config was already present in that
tag.
Resolves one of the tasks in #624

Hide "Select PDF from Canvas" button if Canvas files is not available

---

lms/validation/__init__.py
lms/validation/_canvas.py
tests/lms/validation/_canvas_test.py

Add schemas for parsing and validating the Canvas API's list_files and public_url responses. Depends on <https://github.com/hypothesis/lms/pull/727> for the tests to pass.

Canvas API backend error handling 4/6: Add schemas for list_files and public_url responses

---

lms/services/canvas_api.py
tests/lms/services/canvas_api_test.py

Depends on https://github.com/hypothesis/lms/pull/728 and https://github.com/hypothesis/lms/pull/726 for CI to pass.
Change the `list_files` and `via_url` proxy API views to use `CanvasListFilesResponseSchema`, `CanvasPublicURLResponseSchema` and the `validated_response()` helper, in order to get error handling and validation when calling the Canvas API.

Canvas API backend error handling 5/6: Add validation and error handling to list_files and public_url APIs

---

lms/services/canvas_api.py
lms/views/api/canvas/files.py
lms/views/api/error.py
tests/lms/services/canvas_api_test.py
tests/lms/views/api/canvas/files_test.py
tests/lms/views/api/error_test.py

Depends on https://github.com/hypothesis/lms/pull/730.
I'll give this some manual testing once everything else is merged and this has been rebased, and will update the commit message which is incorrect about the details of the responses sent.
But this fixes the views to catch the service-level `CanvasAPIAccessTokenError` and `CanvasAPIError` that're sent whenever anything goes wrong with an access token or Canvas API request. The errors are turned into 400 Bad Request responses with JSON bodies, that should be suitable for the frontend to implement error handling behaviour.
You can use this branch with everything on it to test: https://github.com/hypothesis/lms/pull/732
The easiest way to test this manually is to hack the code to send incorrect Canvas API requests in various ways, and …

Canvas API backend error handling 6/6: Send 400 Bad Request JSON responses to the frontend, on Canvas API failures

---

lms/static/scripts/file_picker_v2/components/Dialog.js
lms/static/scripts/file_picker_v2/components/ErrorDialog.js
lms/static/scripts/file_picker_v2/components/ErrorDisplay.js
lms/static/scripts/file_picker_v2/components/FilePickerApp.js
lms/static/scripts/file_picker_v2/components/LMSFilePicker.js
lms/static/scripts/file_picker_v2/components/test/ErrorDialog-test.js
lms/static/scripts/file_picker_v2/components/test/ErrorDisplay-test.js
lms/static/scripts/file_picker_v2/components/test/LMSFilePicker-test.js
lms/static/scripts/file_picker_v2/utils/api.js
lms/static/scripts/file_picker_v2/utils/test/api-test.js
lms/static/scripts/polyfills.js
lms/static/styles/components/_ErrorDisplay.scss
lms/static/styles/file-picker-app.scss

**Depends on https://github.com/hypothesis/lms/pull/741**
Instead of expecting the server to provide a hint as to whether the user has authorized the H LMS app to access their LMS files, just try to fetch files when the file picker is shown and display a prompt to authorize if that fails.
As a result, the user is no longer prompted to authorize if they have already authorized the LMS in a previous session.

Always attempt to fetch files when the LMS file picker is shown

---

lms/static/scripts/file_picker_v2/components/Dialog.js
lms/static/scripts/file_picker_v2/components/ErrorDialog.js
lms/static/scripts/file_picker_v2/components/ErrorDisplay.js
lms/static/scripts/file_picker_v2/components/LMSFilePicker.js
lms/static/scripts/file_picker_v2/components/test/ErrorDialog-test.js
lms/static/scripts/file_picker_v2/components/test/ErrorDisplay-test.js
lms/static/scripts/file_picker_v2/components/test/LMSFilePicker-test.js
lms/static/scripts/file_picker_v2/utils/api.js
lms/static/scripts/file_picker_v2/utils/test/api-test.js
lms/static/scripts/polyfills.js
lms/static/styles/components/_ErrorDisplay.scss
lms/static/styles/file-picker-app.scss

This PR implements handling of different types of error that can happen when fetching files from the LMS backend. There are three possibilities for the kind of error that may happen:
1. The server responds with a generic 400 error but no details
2. The server responds with a 4xx error and specific details
3. Some other error happens,  such as a network failure
In the first case, the frontend assumes an authorization error and displays the same authorization message and button text as when the dialog is shown for the first time. In the other cases,  the error details are displayed inline:
Clicking the "send us an email" link will open an email to support@hypothes.is with the details pre-filled. Clicking the "Try again" button will re-authorize and re-fetch files. In other words, exactly …

Catch and display errors reported by LMS backend API calls

---

lms/services/canvas_api.py

Change the _access_token() helper to _oauth2_token() and have it return
the whole OAuth2Token model instead of just the access_token string.
We're going to be needing the refresh_token string from the OAuth2Token
in the future, not just the access_token string, so this change will be
needed.

Change _access_token() to _oauth2_token()

---

lms/static/scripts/file_picker_v2/components/BasicLtiLaunchApp.js
lms/static/scripts/file_picker_v2/components/ErrorDisplay.js
lms/static/scripts/file_picker_v2/components/test/BasicLtiLaunchApp-test.js
lms/static/scripts/file_picker_v2/index.js
lms/static/scripts/file_picker_v2/utils/api.js
lms/static/styles/components/_BasicLtiLaunchApp.scss
lms/static/styles/components/_ErrorDisplay.scss
lms/static/styles/components/_heading.scss
lms/static/styles/file-picker-app.scss
lms/templates/basic_lti_launch/canvas_file_basic_lti_launch.html.jinja2
lms/views/basic_lti_launch.py
tests/lms/views/basic_lti_launch_test.py

Implement a small client-side application which handles launching assignments that use Canvas files (or other LMS's files in future).
Initially the app renders a loading indicator and makes a request for the assignment content URL to the backend:
When the URL is returned, the client app renders an iframe with that URL.
If the URL cannot be fetched because authorization is required, the client will prompt the user for authorization:
If an error occurs, that will be displayed to the user:
---
**Implementation notes:**
The implementation reuses many of the components from the file picker
app, so it is implemented as a new component in the file_picker_v2
bundle. As both apps are pretty small, I think I will keep to just the one bundle
for the moment, but I will give it a more generic name in …

Implement content URL fetching at assignment launch for Canvas files

---

lms/services/_helpers/canvas_api.py
tests/lms/services/_helpers/canvas_api_test.py

This is going to be needed so that if the request fails we can use the refresh token to get a new access token and then, after having saved the new access token to the DB for next time, re-try the original request with the new access token.

Allow sending same request with different access token

---

lms/services/canvas_api.py
lms/views/api/canvas/authorize.py
tests/lms/services/canvas_api_test.py
tests/lms/views/api/canvas/authorize_test.py

Depends on https://github.com/hypothesis/lms/pull/747 for CI to pass.
Simplify CanvasAPIClient by getting rid of the separate save_token()
method, and just having get_token() save the token. So instead of:
token = canvas_api_client.get_token()
canvas_api_client.save_token(token)
It's now just:
canvas_api_client.get_token()

Get rid of save_token()

---

tests/lms/views/favicon_test.py

This is a non-standard MIME type but one that is widely used and may be
returned as the Content-Type for .ico files depending on the system's
mime type registry. This happens for example if Apache 2's mime types
are installed.
I'm sure there are many other ways of fixing this, or even removing the favicon view entirely in favour of using some other mechanism of serving a static resource. Better suggestions welcome.

Allow "image/x-icon" as the MIME type for the favicon in tests

---

lms/templates/base.html.jinja2

When provisioning is disabled, `context.hypothesis_config` is set to an
empty dictionary. Because this is a falsey value in Python, the config
was not rendered into the page, causing the client-side JS to fail.
Modify the base template to check for the existence of JS config related
values instead of falseyness.
The client continued to work when using the legacy (non-`new_oauth`)
mode because the new_lti_launch.html.jinja2 template had duplicated
logic to render this config into the page.
Fixes #755

Render Hypothesis client config into page if set but empty

---

lms/static/scripts/file_picker_v2/components/Dialog.js
lms/static/scripts/file_picker_v2/components/FileList.js
lms/static/scripts/file_picker_v2/components/Table.js
lms/static/scripts/file_picker_v2/components/test/Table-test.js
lms/static/scripts/file_picker_v2/index.js
lms/static/styles/components/_FileList.scss
lms/static/styles/components/_Table.scss
lms/static/styles/file-picker-app.scss
lms/static/styles/mixins/focus.scss
package.json
yarn.lock

This PR implements several improvements to the aesthetics and accessibility of the file list:
**General aesthetics and UX:**
- Use a much stronger visual highlight for selected rows
- Remove borders between cells. These were inherited from global styles in `lms.css`
- Remove the focus outline from the table, but only when not using keyboard input (see [:focus-visible](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible) notes)
- Vertically center file names and labels
**Accessibility:**
- Add accessible labels to the dialog's "X" button and the whole table itself
- Add an the accessible label for the contents of the name column, so that screen readers just read the filename and don't try to describe the icon
- Identify the table as a …

Improve aesthetics and accessibility of file list

---

lms/static/scripts/file_picker_v2/components/FilePickerApp.js

When the file picker form is rendered into a top-level tab instead of an
iframe, pass the URL of the current page instead of the LMS URL as the
"origin" parameter that is forwarded to the Google Picker API.
(_Note that testing this with a unit test is fiddly because `window` and `window.top` are "unforgeable" APIs. I could add some indirection here to solve that, but it seems a bit pointless for something so simple_)
Fixes #421

Pass correct `origin` value to Google Picker in new tabs

---

lms/services/_helpers/canvas_api.py
tests/lms/services/_helpers/canvas_api_test.py

Delete old Canvas API access tokens when getting a new one, by passing
the `replace_tokens` parameter to Canvas's access token endpoint. See:
https://canvas.instructure.com/doc/api/file.oauth.html#oauth2-flow-3
This does two things:
Previous versions of this app have asked for a new access token on every
single launch of the app and not used the `replace_tokens` parameter.
This creates one access token in the user's account for every time they
have launched our app.
The user's list of access tokens in Canvas could list hundreds or
thousands of access tokens from our app, and Canvas provides no way for
either a student or admin to bulk delete access tokens. They have to be
deleted one by one, requiring two clicks per token.
See:
https://community.canvaslms.com/docs/DOC-16005-42121018197 …

Delete old access tokens when getting a new one

---

lms/static/styles/components/_Button.scss
lms/static/styles/components/_Dialog.scss

Fix alignment of assignment source buttons

---

lms/services/launch_verifier.py
tests/lms/services/launch_verifier_test.py

Fix an OAuth 1.0 signature verification failure when handling an LTI
launch request where:
- There is a "url" query param (aka. the launch request is "URL configured")
- The "url" query param, _after decoding_, contains percent-encoded
query parameters.
For example, given an LTI launch request with the following URL:
"https://lms.hypothes.is/lti_launches?url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FG%25C3%25B6reme_National_park"
The LMS would generate an OAuth signature base string using the "url"
parameter "https://en.wikipedia.org/wiki/G%C3%B6reme_National_ark".
When our lms app received the request, it would parse the incoming
request so `request.params["url"]` was "https://en.wikipedia.org/wiki/G%C3%B6reme_National_ark".
However when PyLTI generates the signature base string for …

Work around bug in PyLTI's handling of URL params with percent encoded characters

---

lms/static/styles/components/_FilePickerApp.scss

Fix ragged right edges of document source buttons

---

lms/extensions/feature_flags/_helpers.py
tests/lms/extensions/feature_flags/_helpers_test.py

The way the feature flags mechanism works is that it consults a list of
feature flag "providers" in this order:
- Config file
- Environment variable
- Cookie
- Query string
When queried about a particular feature flag each provider can return
None, True or False, and the *last* provider to return either True or
False is used. So for example the feature flags cookie can return True
to enable a feature that is disabled in the config file, because the
cookie is consulted after the config file.
Unfortunately the cookie provider was _always_ returning True or False,
rather than None, even for flags that the cookie has nothing to say
about because they aren't listed in FEATURE_FLAGS_ALLOWED_IN_COOKIE.
This resulted in the cookie always having the last say (other than the
query string) and …

Don't disable all feature flags in cookie

---

lms/static/styles/components/_Table.scss

File icons for selected files have a CSS `filter` effect applied. This
creates a new stacking context which caused them to be painted on top of
the `position: sticky` table headers when the content was scrolled.
Fix this by applying a z-index to the table header.
See also https://github.com/hypothesis/lms/issues/759
**Before:**
**After:**
Related technical notes on MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

Fix file icons for selected files displaying above sticky header

---

lms/resources/_lti_launch.py
tests/lms/resources/_lti_launch_test.py

This is no longer used now that the new_oauth feature flag is turned on for everyone.

Remove support for reading launch params from DB

---

gulpfile.js
package.json
yarn.lock

Running ESLint is a matter of running a single CLI command, so there is
no need to do it through Gulp.

Simplify frontend linting

---

lms/views/api/canvas/authorize.py
tests/lms/views/api/canvas/authorize_test.py

This is a partial fix for https://github.com/hypothesis/lms/issues/806.

Include scope in canvas auth request

---

lms/static/styles/lms.css

In order to align the CSS between the preact-based front-end app and the server-rendered pages, it helps to be able to first rip out a bunch of unused CSS. This also reduces payload size, so yay.
This commit also cleans up the `lms` CSS formatting per our conventions.
Part of https://github.com/hypothesis/lms/issues/780

Remove unused CSS

---

lms/views/api/error.py
tests/lms/views/api/error_test.py

Add a fallback error handler for `/api/*` routes so that unhandled
exceptions result in JSON rather than HTML responses, to be consistent
with the frontend's expectations.

Add fallback error handler for `/api/*` routes

---

lms/services/__init__.py
lms/services/lti_outcomes.py
tests/lms/services/lti_outcomes_test.py

Add an `lti_outcomes_client` service which provides a client for reading/writing grading
information to an LMS's LTI Outcomes Management service [1], along with Canvas-specific extensions. Currently only the endpoints for reading the current score and replacing the score for an assignment are implemented, as these are the only ones needed for initial grading support.
This will be used for the initial SpeedGrader integration to record a
submission when a learner launches an assignment.
Strictly speaking the "service" could just be a utility class as it doesn't actually make use of any request parameters at the moment. I thought originally it would.
[1] https://www.imsglobal.org/specs/ltiomv1p0/specification

SpeedGrader 1/n - Add a service for sending LTI Outcomes Management requests

---

lms/routes.py
lms/validation/__init__.py
lms/validation/_api.py
lms/views/api/lti.py
tests/lms/test_routes.py
tests/lms/validation/_api_test.py
tests/lms/views/api/lti_test.py

**Depends on https://github.com/hypothesis/lms/pull/864**
Add an API endpoint to record a grading LTI launch URL in SpeedGrader
Add an API endpoint that the frontend will use to record a
grading-oriented LTI launch URL in Canvas's SpeedGrader for use when a teacher
grades the current user's annotations on an assignment.
This operation will be triggered by the frontend rather than by the
backend during the /lti_launches request, where all the necessary
information is already available, because it involves making (possibly
slow) calls to the external LMS. Instead these potentially slow
operations can happen concurrently with the assignment loading in the
user's browser.
- Add `/api/lti/submissions` endpoint to record SpeedGrader Launch URL
- Add schema to validate JSON body of requests to …

SpeedGrader 2/n - Add an API endpoint for frontend to trigger submitting of grading LTI launch URL to Canvas

---

lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
lms/static/scripts/frontend_apps/utils/api.js
lms/static/scripts/frontend_apps/utils/test/api-test.js
lms/views/basic_lti_launch.py
tests/lms/views/basic_lti_launch_test.py

**Depends on https://github.com/hypothesis/lms/pull/865**
Call `record_submission` API from frontend during LTI launch
When an assignment is launched by a student/learner, call the
`record_submission` API view provided by the backend to register a
grading LTI launch URL for the current (user, assignment) in Canvas.
This behavior is currently only enabled when the student has the "speedgrader"
feature flag enabled and when the LMS is Canvas.
- Support making POST requests to API with JSON bodies from frontend
- Pass params for call to `record_submission` API call to frontend in
JS config under `submissionParams` key
- If `submissionParams` key is present in JS config, call
`record_submission` API from frontend during an LTI launch. This
happens after the content URL is fetched, but …

SpeedGrader 3/n - Call API view to record a submission when a student starts an assignment

---

lms/resources/_lti_launch.py
lms/views/basic_lti_launch.py
tests/lms/resources/_lti_launch_test.py
tests/lms/views/basic_lti_launch_test.py

**Depends on https://github.com/hypothesis/lms/pull/865 and https://github.com/hypothesis/lms/pull/867**
This PR implements focusing on the target student in SpeedGrader in the most basic possible way, by pre-filling the search bar with `user:<username>` where `<username>` is the auto-generated hex digit string that serves as the username for provisioned users in the LMS app.
- Make `context.hypothesis_config` mutable in LTI launch views, so that custom configuration can be passed to the client in grading launches
- Respond to the `focused_user` LTI launch param added in https://github.com/hypothesis/lms/pull/865 by adding `{"query":"user:<username>"}` to the Hypothesis client's configuration

SpeedGrader 4/n - Basic implementation of focusing on a user in SpeedGrader

---

lms/validation/__init__.py
lms/validation/_launch_params.py
lms/views/api/lti.py
lms/views/basic_lti_launch.py
tests/lms/validation/_launch_params_test.py
tests/lms/views/basic_lti_launch_test.py

**Depends on https://github.com/hypothesis/lms/pull/865 and https://github.com/hypothesis/lms/pull/867**
Query params in LTI launch URLs submitted to Canvas for use in SpeedGrader get
doubly-encoded so they are still percent-encoded after Pyramid/WSGI have parsed
the request. Implement a workaround by decoding the query param a second time in
the LTI Launch view and signpost the potential issue when generating the
SpeedGrader launch URL.
More generic solutions are possible, but they could have unexpected interactions
with different parts of the system. Therefore this PR just handles the one query
param where this is a problem.
Fixes https://github.com/hypothesis/lms/issues/869

SpeedGrader 5/n - Workaround SpeedGrader launch URL encoding bug

---

Makefile
Procfile
requirements-dev.in

Change `make dev` to run both gunicorn (development web server) and `gulp watch` (frontend assets build) in one terminal, using Honcho to interleave the stdouts of both processes into the one terminal. (honcho is added as a new dev dependency and will be automatically installed by tox.)
The end result is that you just run `make dev` as before but it'll now run both gunicorn and gulp. You no longer need to run gulp separately yourself.
Also:
* `make web` is a new command that now does what `make dev` used to do: runs the web server on its own, so you can debug it 
* `make assets` is a new command that runs `gulp watch` on its own so you can debug it
* Procfile is honcho's config file, which configures `honcho start` to run `make web` and `make assets` simultaneously in one terminal. …

Run gunicorn and gulp in one terminal with Honcho

---

lms/services/__init__.py
lms/services/h_api_client.py
lms/services/h_api_requests.py
lms/views/decorators/h_api.py
tests/lms/services/h_api_client_test.py
tests/lms/services/h_api_requests_test.py
tests/lms/views/decorators/h_api_test.py

Follow up on [1] by renaming the low-level h API service to
`HAPIRequests`, to contrast with the high-level h API service
`HAPIClient`.
[1] https://github.com/hypothesis/lms/pull/888#issuecomment-521261199

Rename low-level h API service to `HAPIRequests`/`h_api_requests`

---

lms/resources/_lti_launch.py
lms/views/basic_lti_launch.py
lms/views/decorators/h_api.py
tests/lms/resources/_lti_launch_test.py
tests/lms/services/hapi_test.py
tests/lms/views/basic_lti_launch_test.py
tests/lms/views/decorators/h_api_test.py

Combine `LTILaunchResource.h_{username, display_name, userid}`
properties into a single `h_user` property which returns an `HUser`.
This removes the duplication of logic for generating the userid from the
username and authority between `LTILaunchResource` and `HUser`. In
future it will also make it possible to add other convenience properties
to `HUser`.
This is a follow-up to [1]
[1] https://github.com/hypothesis/lms/pull/888#pullrequestreview-274807714

Combine `LTILaunchResource` h user properties into `h_user`

---

tox.ini

`make dev` is getting this error:
mkdir: cannot create directory ‘/.pyenv’: Permission denied
because $HOME is not available inside tox so, when pyenv is run in tox,
it's trying to use /.pyenv instead of ~/.pyenv.
Fix this by making $HOME available to pyenv inside tox.
I'm not sure how this ever worked.

Fix make dev

---

lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
lms/static/styles/components/_BasicLtiLaunchApp.scss

This is a fix for https://github.com/hypothesis/lms/issues/768.
There are 3 states in this view that have been modified to use the Dialog component:
* a request for authorization
* a failure to fetch the assignment
* a failure to submit the assignment
The user's authorization is requested:
Fetching the assignment fails:
A user's submission fails:
This is dependent on https://github.com/hypothesis/lms/pull/927.

Use dialog in basicLtiLaunch to display error messages

---

lms/services/__init__.py
lms/services/lis_result_sourcedid.py
tests/lms/services/lis_result_sourcedid_test.py

Part of https://github.com/hypothesis/lms/issues/946
This PR adds a straightforward service for upserting rows into the `lti_result_sourcedid` table.
I've taken the route of assuming that callers will pre-validate the attributes, so the `upsert` service method is relatively "stupid" and doesn't do any sort of real thinking.
One thing to note! At one point during work on this, when alphabetizing the services, I inadvertently deleted the registration of the `canvas_api` service altogether—but _all of the tests still passed_. This seemed a little alarming to me, so I thought I'd mention it.

Add service for interacting with `LISResultSourcedId` records

---

lms/validation/__init__.py
lms/validation/_lis_result_sourcedid.py
lms/values.py
tests/lms/validation/_lis_result_sourcedid_test.py

This PR adds some validation for `lis_result_sourcedid` data. It adds a `NamedTuple` and a schema validation for the `request`.
Part of https://github.com/hypothesis/lms/issues/946

Add NamedTuple and validation for LISResultSourcedId

---

lms/services/lis_result_sourcedid.py
lms/views/basic_lti_launch.py
lms/views/decorators/__init__.py
lms/views/decorators/lis_result_sourcedid.py
tests/lms/services/lis_result_sourcedid_test.py
tests/lms/views/decorators/lis_result_sourcedid_test.py

This PR adds a view decorator that will upsert records into the `lis_result_sourcedid` tables for qualified requests (students of BlackBoard with required params on the request).
It also converts the upsert service to take three `NamedTuples` instead of a single `dict` for more rigorous typing/validation.
I'm marking it WIP simply because I'd like to do more "real" testing before deploying (e.g. on Canvas).
Fixes https://github.com/hypothesis/lms/issues/946

Add view decorator to upsert LISResultSourcedId records

---

lms/views/api/lti.py
tests/lms/views/api/lti_test.py

This small PR factors out things common to various LTI Outcomes Management proxy API views and renames things specific to Canvas/Speedgrader for clarity. This makes way for another view to be added here to support BlackBoard grading.
Part of https://github.com/hypothesis/lms/issues/948

Reorganize `lms.views.api.lti` into a view class

---

lms/services/lis_result_sourcedid.py
lms/values.py
lms/views/basic_lti_launch.py
lms/views/decorators/lis_result_sourcedid.py
lms/views/helpers/__init__.py
lms/views/helpers/frontend_app.py
tests/lms/services/lis_result_sourcedid_test.py
tests/lms/views/basic_lti_launch_test.py
tests/lms/views/helpers/frontend_app_test.py

This PR does a few things related to grading configuration for Blackboard grading:
* It adds a new feature flag, `blackboard_grading`
* When that feature flag is active AND a request comes from Blackboard AND the current user is an instructor, JS configuration is added for the frontend app to consume
* A service method has been added to retrieve relevant student-LIS Result records for the applicable assignment (these are added to the JS config).
To accomplish this, a bit of shuffling around has happened, as I'm trying to yank some of the logic out of the view layer.
Part of https://github.com/hypothesis/lms/issues/949

Add `blackboard_grading` feature flag, JS config

---

lms/resources/_default.py
lms/routes.py
lms/validation/__init__.py
lms/validation/_api.py
lms/views/api/error.py
lms/views/api/lti.py
tests/lms/test_routes.py
tests/lms/validation/_api_test.py
tests/lms/views/api/error_test.py
tests/lms/views/api/lti_test.py

Part of https://github.com/hypothesis/lms/issues/948
This PR adds a super-basic route and view to proxy over results (i.e. grades or scores) to an LTI-Outcomes-Management-compliant API. In this case our goal is to be able to submit BlackBoard Learn grades.
Also included here is a schema for validating requests to this endpoint.
How to test this (using `curl` or your preferred request-management software):
1. You'll need a properly-configured Blackboard Learn assignment pointing at your local instance of `lms`. Launch this assignment as at least one _student_ who is enrolled in the course prior to continuing.
1. Ensure that you have the `blackboard_grading` feature flag enabled in your context (i.e. browser session) and launch the assignment as an (associated) instructor.
1. If you view …

Add Proxy API for submitting LTI Outcome Results

---

lms/resources/_lti_launch.py
lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/LMSFilePicker.js
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js
lms/views/basic_lti_launch.py
lms/views/content_item_selection.py
tests/lms/resources/_lti_launch_test.py
tests/lms/views/basic_lti_launch_test.py

This is a fix for https://github.com/hypothesis/lms/issues/767. This is dependent on https://github.com/hypothesis/lms/pull/939.
To test:
1. Create an lms instance in the lms database that points to https://example.com rather than the correct canvas url. 
2. Try to create a new assignment by selecting a file from canvas.
3. It will prompt you to "authorize Hypothesis to access your files in Canvas". Click authorize.
4. A pop up will appear that opens example.com. Close this.
5. You should see:

Provide user with error details indicating an incorrect canvas url

---

Makefile
README.markdown
bin/create-testdb
tox.ini

Just copying two things that we've already had in h for a while, over to lms: install docker-compose automatically in tox so that developers don't have to go hunting through the Docker docs trying to find out how to install it on their system. And create the test DB automatically.

Automate installing docker-compose and creating the lms_test DB

---

Makefile
requirements-dev.in
tox.ini

Moving pip-compile command out of Make and the dev requirements to be a separate tox command. This means the dev env is very slightly smaller, the compile env is much smaller and we are following the more layered approach (make on tox, not instead).

Moving the pip-compile to tox and it's own env

---

lms/static/scripts/frontend_apps/utils/test/validation-test.js
lms/static/scripts/frontend_apps/utils/validation.js

*independent part of the grader PR for separate review*
Add two functions for validation of input fields
- translateToNumber - Coerces a string value to a number (if it can)
- validateGrade - Assets a number is both a numeric type and within the grade range [0-10]
simple use case
```
<input onClick={(e)=>{
const notValid = validateGrade(translateToNumber(e.target.value));
if (!notValid) {
// value okay
} else {
alert(notValid);
}
}}/>
```

Add client validation utility

---

conf/development.ini
lms/config/__init__.py
lms/views/helpers/_via.py
tests/lms/config/__init___test.py
tests/lms/conftest.py
tests/lms/views/helpers/_via_test.py

Add `use_via2_service` feature flag that when enabled, will use `https://via2.hypothes.is` instead of `https://via.hypothes.is` (or `https://qa-via2.hypothes.is` if on qa or `http://localhost:9081` if on dev). This is part of https://github.com/hypothesis/lms/issues/1030.

Add option to use via2 service via feature flag

---

lms/static/styles/_mixins.scss
lms/static/styles/_typography.scss
lms/static/styles/components/_Button.scss
lms/static/styles/components/_Dialog.scss
lms/static/styles/components/_ErrorDisplay.scss
lms/static/styles/components/_LMSGrader.scss
lms/static/styles/components/_StudentSelector.scss
lms/static/styles/components/_Table.scss
lms/static/styles/components/_heading.scss
lms/static/styles/frontend_apps.scss

The diff of the compiled lms.css and frontend_app.css are identical before and after the conversion.
ran 
`sass-migrator module --migrate-deps lms/static/styles/frontend_apps.scss `
- Manually needed to convert the `normalize.css/normalize` as migration tool balked at that.
- Converted the @ use "../variables" to use the wildcard * namespace as its our convention for variables instead of prefixing the namespace when used.
e.g. 
`variables.$grey-2`
vs 
`$grey-2`
fixes #1054

Migrate the old sass @import to @use

---

conf/development.ini
conf/production.ini
lms/app.py
lms/views/error.py
requirements-dev.in
tests/lms/views/error_test.py

Use pyramid_exclog to print exceptions and related information to the
terminal in dev, not just in production.
Also removed pyramid_debugtoolbar in dev, use pyramid_exclog's terminal
printing rather than pyramid_debugtoolbar's HTML interface for
debugging.
Also remove the logic that prevented error views from being registered
(and therefore nice error pages from being shown) in dev.
This makes dev the same as production when an error happens:
1. The proper error page will be rendered in the browser
2. The traceback and additional info will be printed to the terminal (in
production this same output should appear in Papertrail)

Use pyramid_exclog in dev

---

lms/static/images/check.svg
lms/static/scripts/frontend_apps/components/LMSGrader.js
lms/static/scripts/frontend_apps/components/SubmitGradeForm.js
lms/static/scripts/frontend_apps/components/ValidationMessage.js
lms/static/scripts/frontend_apps/components/test/LMSGrader-test.js
lms/static/scripts/frontend_apps/components/test/SubmitGradeForm-test.js
lms/static/scripts/frontend_apps/components/test/ValidationMessage-test.js
lms/static/styles/_mixins.scss
lms/static/styles/components/_StudentSelector.scss
lms/static/styles/components/_SubmitGradeForm.scss
lms/static/styles/components/_ValidationMessage.scss
lms/static/styles/frontend_apps.scss

LMSGrader can submit grades (simplified)
- Similar to the first PR, but simplified in that there is no special handling for keyboard input or any detection to disable the submit button. This simplified the PR a bit and testing a-lot-a-bit :)
- Adds new component SubmitGradeForm which is responsible for validating the grade and submitting it to the service.
- Successful grades will force the SubmitGradeForm input to animate green for 2 seconds letting the instructor know the grade was saved. (UX is just a suggestion here, but some affordance is useful for saves)
- Any error should be caught by the client error validation and won't allow the grade to be submitted.
- Service errors would ideally be rare in this case, but if they occur they will render in a dialog just like the file picker.

LMSGrader can submit grades

---

lms/views/helpers/_via.py
tests/lms/views/helpers/_via_test.py

This is now always-enabled in Via / the new proxy implementation.
Fixes #1055

Remove PDF.js v2 feature flag

---

lms/db/__init__.py

h has a [Pyramid finished callback](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request.add_finished_callback) called [`close_the_sqlalchemy_session()`](https://github.com/hypothesis/h/blob/5e27c4044c67dd6e786c93f8ae1b8ca2c692849b/h/db/__init__.py#L94-L122) that forcibly closes any unclosed DB sessions at the very end of request processing, and logs a warning because this should never happen.
lms also has a [copy of the same finished callback](https://github.com/hypothesis/lms/blob/2d17fdf8b70cabec857b715a91ad092bf9b180d3/lms/db/__init__.py#L53-L74).
This PR syncs lms's `close_the_sqlalchemy_session()` with h's:
1. Log "closing a dirty session" to Papertrail as a warning instead of reporting it to Sentry because sentry_sdk can try to read …

Sync close_the_sqlalchemy_session() with h's version

---

lms/app.py

Use pyramid_tm's explicit transaction manager.
This means that trying to access a request's transaction after
pyramid_tm has closed the request's transaction will crash, rather than
implicitly opening a new transaction that doesn't get closed (and
potentially leaking open DB connections).
This is recommended in the pyramid_tm docs:
https://docs.pylonsproject.org/projects/pyramid_tm/en/latest/#custom-transaction-managers
We *don't* use the explicit transaction manager in h because h already
has too much code that implicitly relies on implicit transaction
management. We would have to rewrite all that code to use explicit
transaction management, which might introduce bugs.
But in lms we can get away with enabling explicit transaction management
so do it now, before it's too late like it is …

Use explicit transaction manager

---

lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
lms/static/scripts/frontend_apps/components/LMSGrader.js
lms/static/scripts/frontend_apps/components/test/LMSGrader-test.js
lms/static/styles/components/_LMSGrader.scss

The course assignment is the larger `<h1>` tag here where as the name is the smaller `<h2>`. I felt that the more significant title would be the assignment as that is what always will change and the name perhaps may stay the same. 
the config now expects the course name and assignment name to be nested in the config object:
```
...
"grading":{ 
"courseName": "foo",
"courseAssignment": "bar",
"students":[ 
...
]
},
"lmsGrader":true,
...
```
I also improved the css a bit so it looks better when shrinking the window and the grader components collapse/wrap in a reasonable way.

Add course name and assignment to LMSGrader

---

lms/models/__init__.py
lms/models/application_instance.py
lms/models/group_info.py
lms/resources/_lti_launch.py
lms/services/__init__.py
lms/services/group_info_upsert.py
lms/views/decorators/_helpers.py
lms/views/decorators/h_api.py
tests/lms/models/group_info_test.py
tests/lms/resources/_lti_launch_test.py
tests/lms/services/group_info_upsert_test.py
tests/lms/views/decorators/_helpers_test.py
tests/lms/views/decorators/h_api_test.py

Depends on this DB migration: https://github.com/hypothesis/lms/pull/1087
The issue:
* This PR fixes <https://github.com/hypothesis/lms/issues/918>, which asks for a way to associate an LMS-created group found in the h DB with school/institution or LMS that the group belongs to
Testing:
* To test this PR you need to launch your local instance of the LMS app from an LMS such as Canvas. You can use the various pre-created "localhost" assignments in "Test Course 1" in https://hypothesis.instructure.com/courses/83 to do this. See https://github.com/hypothesis/lms/wiki/Testing-the-LTI-App-in-Canvas
Background:
* Whenever a teacher or student launches an assignment using our LMS app, the LMS app creates a group in h for the LMS course that the assignment belongs to. The h group has the same …

Record group info on LTI launch

---

lms/views/helpers/frontend_app.py
tests/lms/views/helpers/frontend_app_test.py

When configuring an assignment in Blackboard there is an "Enable
evaluation" option. When this is _On_, LTI launch requests for
_instructors_ have a `lis_outcome_service_url` param in the request.
When it is _Off_ they do not.
As far as I know, the LTI specs do not say anything about whether this
param should be included in requests when instructors launch an
assignment, and the URL is not actually used at all in that context, but it is
nevertheless the only obvious indicator in the LTI launch request of
whether evaluation is enabled. Therefore, we may need to take a different approach
entirely in other LMSes.
Fixes #1034
---
**Important testing caveat**
When testing this I found that evaluation could only be disabled when creating an assignment. Disabling evaluation afterwards did not …

Disable grading UI if evaluation is disabled for assignment

---

lms/static/styles/components/_StudentSelector.scss

Prior to this css fix, the arrow icon would capture the click event and prevent the select list from opening.

Prevent select icon from capturing click event

---

lms/static/styles/components/_StudentSelector.scss

This provides an extra 5px of whitespace left and right of the arrow icon per slack discussion
https://hypothes-is.slack.com/archives/C1M8NH76X/p1572998090025600?thread_ts=1572950850.013500&cid=C1M8NH76X

Increase padding on StudentSelector and its icon

---

README.markdown

The lms app is dependent on both via and via2 now. It talks directly to via2 and uses via2 to serve pdfs and via2 redirects to via for all other types of content. Update the docs to reflect this change.

Update dev docs to reflect new via2 dependency

---

lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
lms/static/scripts/frontend_apps/components/test/ErrorDialog-test.js
lms/static/scripts/frontend_apps/components/test/ErrorDisplay-test.js
lms/static/scripts/frontend_apps/components/test/FileList-test.js
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
lms/static/scripts/frontend_apps/components/test/StudentSelector-test.js
lms/static/scripts/frontend_apps/components/test/SubmitGradeForm-test.js
lms/static/scripts/frontend_apps/components/test/ValidationMessage-test.js
lms/static/scripts/frontend_apps/components/test/mock-imported-components.js

Change UI tests to follow the pattern introduced in https://github.com/hypothesis/client/pull/1470 of using `mount` rather than `shallow` Enzyme rendering for all tests, but with imported components mocked using a `mockImportedComponents` helper.
This makes the tests more consistent, and removes some manual boilerplate for mocking components.
Some of the `SubmitGradeForm` tests broke due to waiting for async tasks to complete in a brittle way (see [related discussion in issue #1095](https://github.com/hypothesis/lms/pull/1095)). This commit resolves that by making the tests wait for the same loading indicators that the user sees in order to determine whether network requests have completed or not. This makes use of a `waitFor` utility that I had introduced previously but forgotten about …

Replace shallow rendering with mocking of imported components

---

conf/development.ini

Until the Via 2 / proxy-server dev env has been sorted out. See:
https://github.com/hypothesis/proxy-server/issues/11
https://github.com/hypothesis/proxy-server/issues/12
https://github.com/hypothesis/proxy-server/issues/13

Use legacy Via in dev

---

lms/scripts/devdata.py

We [changed lms to use explicit transaction management](https://github.com/hypothesis/lms/pull/1083) and that broke `make devdata`.
If someone wanted to move the `begin()` / `abort()` / `commit()` into a `try` / `except` / `else` in [`create_all()`](https://github.com/hypothesis/lms/blob/e81fcdc84f73cbf61879773de0584c2cfe44bc04/lms/scripts/devdata.py#L34-L53) that'd be better but it doesn't really matter for the `make devdata` script

Fix `make devdata`

---

Jenkinsfile

In preparation for switching our production RDS database to Postgres 11,
change Jenkins CI to run tests in PG 11.
See also https://github.com/hypothesis/h/pull/5824. Unlike h, we don't have Travis so this change means there will be no CI tests running in PG 9.4 any more once this lands. I personally think that's not likely to be an issue given the relatively low volume of transactions, data and schema simplicity in the lms app (ie. no exotic PG-specific features are used).

Upgrade Jenkins to Postgres 11

---

.coveragerc
.gitignore
Jenkinsfile
Makefile
README.markdown
package.json
tox.ini

`codecov` was apparently getting routinely ignored, and failing so instead the idea is to:
* Introduce a fixed percentage coverage value
* Any time the total coverage falls below this the build will fail
* Every so often we will review the value and increase it to the current level (never decrease)
The idea is that for any particular project new patches must match the general level of quality of the project from a coverage point of view. Of course beating this is encouraged, and over time if we only ever revise the number upwards we should move toward 100% coverage without having a massive cliff edge of work to achieve it.

Removing codecov and replacing it with a coverage ratchet value

---

.coveragerc
lms/app.py
lms/views/error.py
tests/unit/lms/authentication/__init___test.py
tests/unit/lms/authentication/_policy_test.py
tests/unit/lms/config/settings_test.py
tests/unit/lms/resources/_default_test.py
tests/unit/lms/services/_helpers/canvas_api_test.py
tests/unit/lms/services/canvas_api_test.py
tests/unit/lms/validation/__init___test.py
tests/unit/lms/views/error_test.py

Previously we would return JSON for ValidationErrors regardless. We now specify what should happen if the user requests "text/html".
As a part of this I ran a cleaner over the imports in the tests as I remembered I'd left an un-used import. It cleaned out quite a few others too.

Using error view decorators and fixing html Validation errors

---

.coveragerc
lms/views/decorators/lis_result_sourcedid.py
lms/views/helpers/frontend_app.py
tests/unit/lms/models/lis_result_sourcedid_test.py
tests/unit/lms/services/lis_result_sourcedid_test.py
tests/unit/lms/views/decorators/lis_result_sourcedid_test.py
tests/unit/lms/views/helpers/frontend_app_test.py

Remove the "only in Blackboard" gates from our grading feature so that it's now enabled in all LMS's.
It has been tested in Blackboard (and already released to the public), Moodle and Brightspace.

Enable grading in all LMS's

---

lms/validation/_exceptions.py
lms/validation/_lti_launch_params.py
tests/functional/lti_certification/test_lti_certification_1_1.py
tests/unit/lms/validation/_lti_launch_params_test.py

Fixing a number of issues around the `lti_version` which can only be one value for LTI 1.1.
Addresses: 
* https://github.com/hypothesis/lms/issues/1113 - LTI version invalid
* https://github.com/hypothesis/lms/issues/1114 - LTI version wrong
* https://github.com/hypothesis/lms/issues/1117 - LTI version missing

LTI Certification 1.1 - Tests 1.5, 1.6 & 1.7

---

lms/validation/_lti_launch_params.py
tests/functional/lti_certification/test_lti_certification_1_1.py
tests/unit/lms/validation/_lti_launch_params_test.py

From https://www.imsglobal.org/specs/ltiv1p1/implementation-guide (search "Basic Launch Data") the only acceptable value is "basic-lti-launch-request".
Addresses:
* https://github.com/hypothesis/lms/issues/1118 - LTI message type invalid
* https://github.com/hypothesis/lms/issues/1119 - LTI message type missing

Adding testing for LTI 1.1 Certification - Parts 1.8 & 1.9

---

lms/resources/_lti_launch.py
lms/views/basic_lti_launch.py
tests/unit/lms/resources/_lti_launch_test.py

This reverts https://github.com/hypothesis/lms/pull/1184 because it
broke configuring assignments in non-Canvas LMS's.
Revert "Lint and formatting"
This reverts commit 5f1db52b8e42f82025f2b8590a773ebf3c0e6a47.
Revert "Fix some broken unit tests"
This reverts commit 578839e67ee6b3e1c8d930f793431ee4685ba325.
Revert "Adding the schema to the resource instead of the view"
This reverts commit f6e1d7cd9e95bb1b466da5ab31427657a695cbb4.

Revert PR #1184

---

lms/resources/_lti_launch.py
lms/views/basic_lti_launch.py
tests/unit/lms/resources/_lti_launch_test.py

Re-instates the reverted https://github.com/hypothesis/lms/pull/1184 but with an additional commit to avoid breaking module item configurations.

Validate launch params in resource instead of view, take 2

---

lms/resources/_lti_launch.py
lms/views/basic_lti_launch.py
tests/unit/lms/resources/_lti_launch_test.py

Revert https://github.com/hypothesis/lms/pull/1187 (validating launch
params in the resource instead of the view).
It turns out that Pyramid intitalises the resource before it does
authentication. If the resource does the validation then an
unauthenticated request can receive a validation error instead of an
authentication error (if the request also contained other invalid
params). This is wrong: authentication should happen before validation.
Revert "Don't validate launch params if not "lti_launches" route"
This reverts commit 73cd18fd8eac23194dd2fd69196334f8377e7a26.
Revert "Lint and formatting"
This reverts commit 321ebce516e43c0e10875f360a8bee4c696d1f36.
Revert "Fix some broken unit tests"
This reverts commit c435e553c6f40e996e7c1b7cad90a4d78ab31c76.
Revert "Adding the schema to the …

Revert PR #1187

---

lms/views/helpers/_via.py
tests/unit/lms/views/helpers/_via_test.py

When enabled it will append html/ to the via2 service url which is
the path to the html rewriter endpoint in the via2 service.
Note this PR also requires updating the env var FEATURE_FLAGS_ALLOWED_IN_COOKIE to include the new feature flag.

Add use_via2_html_rewriter feature flag

---

lms/models/lti_launches.py
tests/unit/lms/models/lti_launches_test.py

Use the current time as the default value, not the time at which the app
started up.

Fix LtiLaunches.created default value

---

.behaverc
Makefile
tests/bdd/environment.py
tests/bdd/features/lti_certification/section_1_invalid_launch_requests.feature
tests/bdd/step_context.py
tests/bdd/steps/lms_db.py
tests/bdd/steps/oauth1.py
tests/bdd/steps/the_app.py
tests/bdd/steps/the_fixture.py
tests/bdd/steps/the_request.py
tests/bdd/steps/the_response.py
tests/bdd/steps/the_url.py
tox.ini

* The first test (1.1) has been completed
* All the required mechanism to get behave working has been added
* You can now run `make bddtests` to run these on the command line
* The steps have been implemented in a very small re-usable style (not fewer more scenario specific steps)
* A new concept of a 'StepContext' and 'StepContextManager' class have been introduced
* These are responsible for keeping all state related to a set of steps
* They are also responsible for setup and tear down of that state
* They can register and de-register themselves from the global BDD context
* This allows us to have clean managed fixtures which don't lank around between tests
* They also cater for having one-time setup at the beginning of all tests
* This is aware of all `StepContext` objects have have …

Part 3: Completing first test and introducing StepContexts

---

lms/services/lti_outcomes.py
tests/unit/lms/services/lti_outcomes_test.py

We referred to a variable which can be undeclared by the time we get to it.
This fixes: https://github.com/hypothesis/lms/issues/1106

Fixing unbound response bug in error handling in LTI Outcomes service

---

lms/services/lti_outcomes.py
tests/unit/lms/services/lti_outcomes_test.py

This is to clear up some homeless code that was floating about in the files next to classes where they are used.
Adding class methods leaves the code nomadic if required, but also implies stronger scoping that the file level.

A small refactor to attach code to the classes they are used in

---

.behaverc
tests/bdd/environment.py
tests/bdd/features/lti_certification/section_1_invalid_launch_requests.feature
tests/bdd/higher_order_gherkin.py
tests/bdd/steps/_compiled_feature_steps.py
tests/bdd/steps/feature_steps/auth.feature
tests/bdd/steps/feature_steps/lti.feature

* This introduces the higher order gherkin injector
* This injector reads special feature step files
* These are written in Gherkin but define steps not scenarios
* These scenarios are parsed and written out to a python file
* This python file is read by behave and interpreted as normal steps
All steps and related functions exist on a continuum of scale:
* __Small steps__ are:
* :heavy_check_mark: Re-usable
* :heavy_check_mark: Composable
* :x: Hide the intent of the test 
* :heavy_check_mark: Result in less code being written 
* :x: Result in more gherkin being written
* __Large steps__ are:
* :x: Test specific
* :x: Inflexible 
* :heavy_check_mark: Reveal the intent of the test 
* :x: Result in more code being written  
* :heavy_check_mark: Result in less gherkin being written 
As steps …

Part 4: Adding the concept of Higher Order Gherkin - Steps defined in Gherkin

---

Makefile
tox.ini

1. You can just do `tox -e foo` rather than `tox -e py36-foo`
2. Use `tox -qe` rather than `tox -q -e`
3. Use `@` prefix in Makefile so make doesn't print out each command
before running it
For more explanation see:
https://github.com/hypothesis/h/pull/5866

Simplify tox commands

---

lms/services/lis_result_sourcedid.py
lms/validation/_lis_result_sourcedid.py
lms/values.py
tests/unit/lms/validation/_lis_result_sourcedid_test.py

A dict will do fine.
Spawned from: https://github.com/hypothesis/lms/pull/1247 as an attempt to split that up into more palatable chunks.
This removes the value object only, as it was only used locally.

Removing an unneccessary value object from the LIS service

---

lms/static/styles/components/_LMSGrader.scss

Fix the width of the `LMSGrader__student-count` element to prevent a potential reflow of dom elements to the next line when changing students. 
This should cover us up to 3 digits of students. e.g. "Student 999 of 999" still fits in 150px.
In this example you can see how it breaks to a second line when changing from All Students to the first student, but after fixing the width, it no longer does that.
fixes https://github.com/hypothesis/lms/issues/1194

Prevent reflow of grading components

---

lms/views/helpers/frontend_app.py

* Previously if grading is disabled, we still run the whole block
* This means we look up all students for every call
* This will be generating lots of unnecessary DB calls
This has two commits:
* The first is a straight indent of the code to show the tests passing
* The second is a refactor for an early return and to create the config separately from lookup

Don't list all students if grading is disabled

---

lms/views/basic_lti_launch.py
tests/unit/lms/views/basic_lti_launch_test.py

Moving some functions in the view `__init__` which are canvas specific into smaller sub-functions . 
This is a bit easier to read, but mostly it's to highlight the fact that they aren't general behavior that matters in anything other than a Canvas context. If that changes, we can change them.

Marking Canvas LTI Launch View specific behavior and moving into sub-functions

---

lms/models/__init__.py
lms/models/grading_info.py
lms/services/__init__.py
lms/services/grading_info.py
lms/views/basic_lti_launch.py
lms/views/helpers/frontend_app.py
tests/unit/lms/models/grading_info_test.py
tests/unit/lms/services/__init___test.py
tests/unit/lms/services/grading_info_test.py
tests/unit/lms/views/basic_lti_launch_test.py
tests/unit/lms/views/helpers/frontend_app_test.py

`LISResultSourcedId` is both confusing and misleading. The object is actually a compound of various pieces of data of which `lis_result_sourcedid` is only one. It's also completely hostile to understanding what the hell it is.
I've tried to fix everywhere referring to this but it's likely I've missed something. The LTI field is still called `lis_result_sourcedid` so that's still all over our code.

Renaming LISResultSourcedId to GroupInfo

---

lms/services/__init__.py
lms/services/lti_outcomes.py
lms/services/oauth1.py
lms/views/api/lti.py
tests/unit/lms/services/__init___test.py
tests/unit/lms/services/lti_outcomes_test.py
tests/unit/lms/services/oauth1_test.py
tests/unit/lms/views/api/lti_test.py

* The new OAuth1 service now encapsulates the secret and oauth key
* This pulls it out of the objects which everyone was passing about
* This is part of the work to eliminate the LTIOutcomesRequestParams object

A separate OAuth1 service to cut down on passing parameters about

---

lms/services/lti_outcomes.py
tests/unit/lms/services/lti_outcomes_test.py

Fixing a bug I introduced (but haven't released) detected during testing in QA. This is happens if we get None as a grade back.
The error was in breaking existing test coverage and not covering None as a case.

Fixing a bug where we fail upon getting None as a grade

---

lms/static/scripts/frontend_apps/components/SubmitGradeForm.js
lms/static/scripts/frontend_apps/utils/test/validation-test.js
lms/static/scripts/frontend_apps/utils/validation.js

I noticed this bug when submitted a grade of 3.3. When you multiple 0.33 by 10 in js, you end up with a floating point precision problem that looks like this 3.3000000000000003. This fix converts all grades to a string, checks the least significate digits and rounds to that precision. 
To replicate this bug, just submit a grade of 3.3, and refresh and you'll see 3.3000000000000003

Fix floating point precision with grade

---

lms/services/lti_outcomes.py
lms/views/api/lti.py
tests/unit/lms/services/lti_outcomes_test.py
tests/unit/lms/views/api/lti_test.py

Generally the service URL doesn't change for an installation. Therefore
the only variable variable here is 'lis_result_sourcedid'.
This simplifies the callers a lot, which still making it obvious where
the critical part of information is coming from.

LTI Outcomes: Removing the value object and replacing with a single value

---

lms/static/scripts/frontend_apps/components/SubmitGradeForm.js
lms/static/scripts/frontend_apps/components/test/SubmitGradeForm-test.js

When building the grader, I made the assumption that the currentGrade value from the service layer would always be a number, this was a false assumption. It can now handle a null or missing value. 
I was able to test this on blackboard by clearing out any previous student grades, then I was able to repro to error. Once I applied this fix, then that error was resolved and the UI worked.
Fixes https://github.com/hypothesis/lms/issues/1342

Add grader to handle null grade values

---

tox.ini

Fix a crash with the web process in macOS development environments that
outputs this error message:
objc[11433]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
This is due to an issue with recent versions of macOS that breaks all
sorts of things (Python, Ruby, Postgres, ...). Googling the error
message, setting `export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` in
every thread or post about it.
Some good posts about the issue are:
* https://blog.phusion.nl/2017/10/13/why-ruby-app-servers-break-on-macos-high-sierra-and-what-can-be-done-about-it/
* …

Fix macOS fork child process crash

---

docker-compose.yml

11.5 is the version of Postgres that we're currently using in
production.
For developers:
* Before you `git pull` this commit, backup your DB to a `dump.sql` file:
.tox/docker-compose/bin/docker-compose exec postgres pg_dump -U postgres postgres > dump.sql
* If you already have `make services` running then `make dev` will
continue using Postgres 9.4 and your existing data
* But the next time you run `make services`, though, it will recreate
your DB as a Postgres 11.5 DB. At this point your DB will be broken
because it's a Postgres 11.5 DB with Postgres 9.4 contents. `make dev`
will fail.
* You need to delete your DB contents and allow them to be created from
scratch again, to get it working:
make services args='down'
make services
* You now have a working Postgres 11.5 DB but its contents …

Upgrade the dev env to Postgres 11.5

---

lms/extensions/feature_flags/_helpers.py

Feature flag cookies are set in a first-party context from the `/flags`
form but we want them to be send when the LMS app is loaded in an
iframe, in a third-party context, inside the LMS.
Per the recipes at [1] and [2], this requires setting `SameSite=None; Secure` on
the cookie. This requirement is expected to be enforced in Chrome starting in February 2020 with Chrome 80: https://www.chromium.org/updates/same-site.
[1] https://web.dev/samesite-cookie-recipes/
[2] https://tools.ietf.org/html/draft-west-cookie-incrementalism-00#section-3.2
**Important caveat**
The `Secure` flag means that this cookie will no longer be sent over plain
HTTP connections. That will not be a problem in QA and prod but unless browsers implement
an exception for localhost, which I'm not aware they do, this will …

Set `SameSite=None` attribute on feature flag cookie

---

lms/services/lti_outcomes.py
lms/views/api/lti.py
tests/unit/lms/services/lti_outcomes_test.py
tests/unit/lms/views/api/lti_test.py

Must be merged after https://github.com/hypothesis/lms/pull/1298.
This works by having a callback we pass into the record function which allows us to modify the request.
Some interesting insights as a result of putting the code in the same place so we can see it:
* We were treating the `ltiLaunchUrl` and `submittedAt` values as independent
* In truth you get both or you don't get called
* We were treating the `submittedAt` value like a variable
* In truth we always set the exact same value
None of this is obvious when the code dealing with this was in two places.

Pulling all Canvas specific grading logic from the services to the views

---

.eslintrc
lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
lms/static/scripts/frontend_apps/components/Dialog.js
lms/static/scripts/frontend_apps/components/FileList.js
lms/static/scripts/frontend_apps/components/LMSFilePicker.js
lms/static/scripts/frontend_apps/components/StudentSelector.js
lms/static/scripts/frontend_apps/components/ValidationMessage.js
package.json
yarn.lock

This enables the [jsx-a11y ES Lint plugin](https://github.com/evcohen/eslint-plugin-jsx-a11y) which can
statically detect a subset of common accessibility errors.
Flag the current set of known errors with a `FIXME-A11Y` comment and
suppress them temporarily, so that we can fix them incrementally while
guarding against new errors.
Part of #1377. Corresponding [client PR](https://github.com/hypothesis/client/pull/1728).

Enable jsx-a11y ESLint plugin

---

lms/static/styles/components/_FileList.scss
lms/static/styles/components/_Table.scss

Enable the file selection dialog to work with a wider range of available
window heights by:
- Removing the fixed 280px (7 * $table-item-height) height assigned to the
table
- Using a flex column layout to make the file list expand/shrink to fit
its contents and overriding the default computed minimum height,
which is based on the table's content, so that the table can shrink
if necessary
This fixes an issue where the Canvas file picker dialog was getting cut
off in Canvas because the assignment selection iframe was only 340px
high. It now works:
Fixes #1416

Make the LMS file selection dialog user at smaller heights

---

lms/resources/_lti_launch.py
lms/static/scripts/postmessage_json_rpc/server/server-test.js
lms/static/scripts/postmessage_json_rpc/server/server.js
lms/templates/base.html.jinja2
tests/unit/lms/resources/_lti_launch_test.py

Part of https://github.com/hypothesis/lms/issues/1386.
We want to simplify our JavaScript config by merging multiple separate
JavaScript config objects into one nested object.
How it currently works (before this commit)
-------------------------------------------
The backend currently has an `LTILaunchResource.rpc_server_config`
property:
https://github.com/hypothesis/lms/blob/1f10d599e5e2502a4bfbde023da35e852729788e/lms/resources/_lti_launch.py#L250-L254
The `rpc_server_config` property contains the config settings for the
JavaScript JSON-RPC server:
https://github.com/hypothesis/lms/blob/master/lms/static/scripts/postmessage_json_rpc/server/server.js
It gets rendered into the HTML as `"js-rpc-server-config"`:
https://github.com/hypothesis/lms/blob/1f10d599e5e2502a4bfbde023da35e852729788e …

Move rpc_server_config into js_config

---

Makefile

Run the code formatters, linters, tests, functests, bddtests, and
coverage, backend and frontend, in a single `make all` command.
Handy for running locally before you push a pull request, so that you
don't have to type:
make checkformatting lint test functests bdd coverage
You can _almost_ run it all faster in parallel with:
make -j `nproc` all
... but sadly this fails because the unit tests, functional tests and
bddtests all share the same test DB. That should be easy enough to fix in
future.

Add a convenient `make sure` command

---

lms/static/scripts/frontend_apps/utils/api.js
lms/static/scripts/frontend_apps/utils/test/api-test.js

This is a good idea, but mostly motivated by webargs no-longer accepting JSON content without it.
This is for: https://github.com/hypothesis/lms/issues/1441

Specify the content type when sending JSON payloads

---

lms/validation/authentication/_oauth.py

This is to head off problems with defaults changing in webargs.

Specify query string as the place to look for the Canvas OAuth schema

---

lms/validation/_api.py
lms/validation/_base.py
tests/unit/conftest.py
tests/unit/lms/validation/_api_test.py
tests/unit/lms/validation/_base_test.py

* Raise an exception when JSON payloads have wrong content type
* Added a content_type to the base pyramid request object
* Lots of changes to validation/_api_test.py to use a new fixture
* This fixture is a JSON request which...
* Sets the content type
* Encodes the JSON content
* Added the content type and some variations to the base tests
----
* Easiest is probably to login to canvas as a student
* Open an assigment and pop it into a new window
* Use the dev tools to look at network requests
* Filter by 'submissions' and copy the contents as a curl request
* Modify the content type to something other than application/json

Separate JSON schemas into their own class and check content type

---

lms/static/scripts/frontend_apps/index.js
lms/static/scripts/postmessage_json_rpc/server/server-test.js
lms/static/scripts/postmessage_json_rpc/server/server.js
lms/templates/base.html.jinja2

This means that we once again have an `LTILaunchResource.js_config`
property and a matching `js-config` CSS class.
Note that the `js-` prefix is a pattern used to denote CSS classes that
exist for the purpose of enabling JavaScript to find things rather than
for styling, see:
https://github.com/hypothesis/frontend-toolkit/blob/master/docs/css-style-guide.md#classes-used-in-code
I'm not going to change that as it's a pattern used in frontend code
throughout all our apps (and it's a good idea too).
I think the addition of "-lms-" was meant to help distinguish this
config object from the other js-hypothesis-config and
js-rpc-server-config objects, but neither of those exists any more.

Rename js-lms-config back to just js-config

---

lms/resources/_lti_launch.py
lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
lms/static/scripts/postmessage_json_rpc/server/methods-test.js
lms/static/scripts/postmessage_json_rpc/server/methods.js
lms/templates/base.html.jinja2
lms/views/basic_lti_launch.py
tests/unit/lms/resources/_lti_launch_test.py
tests/unit/lms/views/basic_lti_launch_test.py

Part of https://github.com/hypothesis/lms/issues/1386.
We want to simplify our JavaScript config by merging multiple separate
JavaScript config objects into one nested object, so move the separate
`LTILaunchResource.hypothesis_config` property into
`LTILaunchResource.js_config` as a `"hypothesisClient"` sub-dict.
How it currently works (before this commit)
-------------------------------------------
The backend currently has an `LTILaunchResource.hypothesis_config`
property:
https://github.com/hypothesis/lms/blob/0abc66323919997cd76d5109021e9eafafe5c336/lms/resources/_lti_launch.py#L206-L257
The `hypothesis_config` property contains the config settings that the
JSON-RPC server will pass to the Hypothesis client.
It gets rendered into the HTML as `"js-hypothesis-config"`: …

Move hypothesis_config into js_config

---

README.markdown
conf/development.ini

Change the dev env back to legacy Via instead of Via 3 by default.
You can still visit http://localhost:8001/flags and turn on the
use_via3_url feature flag to have it use Via 3 in dev instead.
When it's time to change the dev env backt o Via 3 by default again we
can simply revert this commit.

Use legacy Via in dev by default

---

pytest.ini
tox.ini

Centralise the pytest config in a `pytest.ini` file that applies to both
`make test` and `make functests` instead of repeating command line
options in the `pytest` commands in `tox.ini`.
The new `pytest.ini` fails the tests on warnings which was already being
done for `make test` but not for `make functests` which was printing out
a warning. `make functests` will now fail on warnings too, and the one
warning that it was already printing has been silenced.
The new `pytest.ini` also contains `-q`: less output is nicer when the
tests pass.

Tweak pytest config

---

lms/resources/_lti_launch.py

`LTILaunchResouce._h_username` is a private property that is only used
in one place: another `LTILaunchResource` property
`LTILaunchResource.h_user`. The code is easier to understand and to
refactor if `_h_username` is just inline into `h_user()` as a local
variable. Reduces travel.

Inline _h_username

---

.prospector.base.yaml
lms/resources/__init__.py
lms/resources/_default.py
lms/resources/_lti_launch.py

Remove some `__all__`'s that aren't doing anything for us.
PEP 8 does say:
> "To better support introspection, modules should explicitly declare the names
> in their public API using the `__all__` attribute."
https://www.python.org/dev/peps/pep-0008/#public-and-internal-interfaces
But the `__all__`'s are a maintenance burden, they can potentially get
out of sync with the actual code if people forget to update them, and I
don't think they're doing much for us:
1. The only names in `_lti_launch.py` are `LTILaunchResource`, which is public,
and imported names which are private. And the same section of PEP 8 also says:
> "Imported names should always be considered an implementation detail ...
> unless they are an explicitly documented part of the containing module's API,
> such as `os.path` …

Remove some unnecessary __all__'s

---

.coveragerc
Jenkinsfile
Makefile
bin/create-db
bin/create-testdb
tests/bdd/environment.py
tests/bdd/steps/lms_db.py
tests/conftest.py
tests/functional/conftest.py
tests/unit/conftest.py
tests/unit/lms/session_test.py
tox.ini

Rather than all sharing a single lms-test DB have the tests, functests and
bddtests use separate lms-test, lms-functests and lms-bddtests DBs.
<del>I was noticing a problem that, when the three different tests are run together
in a single `make` command, something seemed to be sometimes leaving test data
behind in the DB that would cause later test runs to fail until the DB was
manually cleared. Was happening to me locally quite often. I didn't figure out
why. But this change seems to get rid of the problem.</del> -- this doesn't seem to fix that, I think the db_session fixture in the functests may be wrong
This also means that the tests, functests and bddtests can be run in parallel,
for example:
```terminal
$ make -j `nproc` sure
```
This takes the time to run `make sure` on my machine …

Use separate DBs for tests, functests and bddtests

---

lms/resources/lti_launch.py

Like the previously inlined `_h_username`
(5c2d47a8f68aa5d5ff64487e06778bf271a1e363), `LTILaunch._h_display_name`
is another separate `@property` that's only used in one place: the
`LTILaunch.h_user` property. So inline `_h_display_name` into `h_user`
to make the code more readable and easier to refactor by making
`_h_display_name`'s limited scope more clear.
Note that the previously-inlined username code was just a single block
of code (with no empty lines) so it could just be inlined as a block of
code with a comment:
https://github.com/hypothesis/lms/blob/64478c3110544bcaefde8b90b0e7b685311e9ca7/lms/resources/_lti_launch.py#L45-L49
But `_h_display_name` is a longer method that contains multiple blocks
of code. If it were simply inlined into `_h_user` as lines of code with
a comment at …

Inline _h_display_name into h_user

---

lms/static/scripts/bootstrap.js
lms/static/scripts/frontend_apps/components/ErrorDisplay.js
lms/static/scripts/frontend_apps/components/test/LMSGrader-test.js
lms/static/scripts/frontend_apps/utils/prop-types.js
lms/static/scripts/frontend_apps/utils/test/prop-types-test.js

This is the second part of https://github.com/hypothesis/lms/issues/1463. It fixes the remaining propTypes-related warnings when running lms frontend tests.
Several components make use of `propTypes.{element, node}` to validate that a prop contains a JSX element or a value that can appear in a JSX expression (string, boolean, null).
This fails validation checks because `propTypes.{element, node}` only work with React elements but not Preact ones. The Preact docs don't specify a preferred way to resolve this so I'm asking the community.
In the meantime, this resolves the related warnings by adding two custom prop type checkers which do the same thing and patches `propTypes.{element, node}` to use them.
---

Patch `propTypes.{element, node}` to work with Preact elements

---

lms/resources/_js_config.py
lms/resources/lti_launch.py
tests/unit/lms/resources/_js_config_test.py
tests/unit/lms/resources/lti_launch_test.py

This just moves `LTILaunchResource.js_config` into a separate helper class that `LTILaunchResource` calls, without changing the public interface yet. User code still access the config dict directly as `context.js_config` (singleton) for now.

Move JS config into collaborator

---

lms/db/__init__.py
tests/conftest.py
tests/functional/conftest.py

On master the BDD tests pollutes the test DB such that future runs of the unit
tests fail:
```terminal
$ make backend-tests
(the tests pass)
$ make bddtests
(the tests pass)
$ make backend-tests
(a bunch of assertions fail because there's unexpected data in the test DB)
```
The only way to fix this once its happened is to manually delete your test DB.
This is arguably a problem with the BDD tests: they don't seem to clean up after
themselves, whereas the functests and unit tests do.
But as a fix I've changed the functests and unit tests to delete all the test DB
tables at the beginning of a test run. Ensuring that the test DB is in a clean
state before you start a test run seems more robust than trying to always leave
the DB clean _after_ a test run no matter what happened.

Delete test DB tables before running tests

---

lms/views/helpers/_canvas_files.py
tests/unit/lms/views/helpers/_canvas_files_test.py

`canvas_files_available()` is only called in one place:
https://github.com/hypothesis/lms/blob/3c98e647c8790655b59f839cf183dbbf124c1913/lms/views/content_item_selection.py#L92

Remove an unused optional argument

---

.coveragerc
lms/resources/_js_config.py
lms/views/basic_lti_launch.py
tests/unit/lms/resources/_js_config_test.py
tests/unit/lms/views/basic_lti_launch_test.py

Move the `"debug"` settings that some views add to the JS config into the `JSConfig` class. For simplicity these are now just added for every request, not just some, which does no harm.
Just moving the code, not redesigning it.
Details:
`BasicLTILaunchViews` inserts some debug info, used by the Gherkin tests, into the JavaScript config:
https://github.com/hypothesis/lms/blob/a59fc96fd2c80aa7e015bb668c78e5041e3c5a46/lms/views/basic_lti_launch.py#L44-L51
Move this JavaScript config mutation into the `JSConfig` class and make it unconditional: the debug info is now added to the `JSConfig` for all requests (that have a `JSConfig`). The less variation of the `JSConfig` between different requests the better.

Move debug settings into JSConfig

---

lms/services/grading_info.py
lms/views/helpers/frontend_app.py
tests/unit/lms/views/helpers/frontend_app_test.py

Make `GradingInfoService.get_by_assignment()` return a list of
`(GradingInfo, HUser)` 2-tuples instead of just a list of
`GradingInfo`'s.
`get_by_assignment()` is called in only one place, and that calling code
immediately transforms `get_by_assignment()`'s list of `GradingInfo`'s
into a list of `(GradingInfo, HUser)` 2-tuples:
https://github.com/hypothesis/lms/blob/e801a012b4ca655338a35b678892e789edabad27/lms/views/helpers/frontend_app.py#L48-L57
Just have `get_by_assignment()` already return the 2-tuples itself,
simplifying the calling code.

Make get_by_assignment() return a list of 2-tuples

---

lms/resources/_js_config.py
lms/resources/lti_launch.py
lms/templates/base.html.jinja2
lms/views/basic_lti_launch.py
lms/views/content_item_selection.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/views/basic_lti_launch_test.py
tests/unit/lms/views/content_item_selection_test.py

Expose JSConfig itself directly as context.js_config, rather than only
exposing JSConfig.config.
This is because we're going to be adding new methods to JSConfig for the
views to call, so they'll need access to it.
This means that view code that wants to access the config dict directly
now has to do `context.js_config.config`, but that will eventually be
going away as we phase out direct access to this dict.

Expose the JSConfig instance directly

---

tests/unit/lms/views/basic_lti_launch_test.py

Fix a bunch of `BasicLTILaunchViews` test fixtures that were either missing, were not autouse when they should be, or were not module-scope when they should be.
* This makes the tests more correct (all the tests are now unit tests for `basic_lti_launch_test.py`, which is what they're supposed to be according to our testing approach, whereas previously some of them were also testing code from other modules)
* It also brings the code in line with our general testing patterns: the unit tests for a module always patch imports of other modules _from our own codebase_, and import patch fixtures are always module-level and autouse
* It's going to make the test code easier to refactor. I'm going to need to move a bunch of tests around between different test classes. Module-level autouse fixtures …

Fix some test fixtures

---

tests/unit/conftest.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/services/canvas_api_test.py
tests/unit/lms/services/launch_verifier_test.py
tests/unit/lms/services/lti_h_test.py
tests/unit/lms/services/lti_outcomes_test.py
tests/unit/lms/services/oauth1_test.py
tests/unit/lms/validation/authentication/_launch_params_test.py
tests/unit/lms/views/api/canvas/authorize_test.py
tests/unit/lms/views/api/canvas/files_test.py
tests/unit/lms/views/api/lti_test.py
tests/unit/lms/views/basic_lti_launch_test.py
tests/unit/lms/views/content_item_selection_test.py
tests/unit/lms/views/helpers/frontend_app_test.py

This adds fixtures to `tests/unit/conftest.py` for mock services for all
our services. We're now mocking all the services correctly in one place,
rather than mocks for particular services being distributed throughout
the tests and having inconsistencies in fixture naming. This also
removes some duplication where we had multiple fixtures in different
test files for mocking the same service.
Individual tests can of course override and modify or replace these global fixtures
in the usual way.
These are not autouse fixtures because that would cause every one of
these fixtures to be executed, including runnning
`mock.create_autospec()` which is slow, for every single test, and that
slows down a full test run significantly. Instead, modules that need
given services to be mocked declare that …

Centralize and deduplicate service fixtures

---

tests/unit/lms/views/basic_lti_launch_test.py

Let's call this test class what it is: it's the tests for
`BasicLTILaunchViews.__init__()`.
Also removed a _"test that it does not set 'lmsGrader' if X"_ test:
`BasicLTILaunchViews` _never_ sets `'lmsGrader'`. I don't think it ever
did. The test makes no sense.
Also fixed an incorrectly named test.

Rename TestBasicLTILaunch to TestBasicLTILaunchViewsInit

---

tests/unit/lms/views/basic_lti_launch_test.py

This route is already added by a global fixture:
https://github.com/hypothesis/lms/blob/07c3af58a06011a0232df7e6daa5516ffbafbe91/tests/unit/conftest.py#L222-L233

Remove an unnecessary routes fixture

---

tests/unit/conftest.py
tests/unit/lms/views/basic_lti_launch_test.py

Rather than individual tests adding this standard LTI launch param to
pyramid_request.params just add it to the global pyramid_request fixture
as we already do for other standard params.
Also removed some unnecessary setting of the tool_consumer_instance_guid
param in tests: this param is _already_ present in the global
pyramid_request fixture.

Add resource_link_id param to pyramid_request fixture

---

.coveragerc
tests/unit/lms/views/basic_lti_launch_test.py
tests/unit/lms/views/predicates/__init___test.py

Factor out some test class inheritance in `basic_lti_launch_test.py`
that was being used to run one base class of tests against a few
different view methods.
Replace this with a pytest parametrized fixture instead.
Test class inheritance is un-idiomatic in pytest and I think it might be
incompatible with some pytest features. I also found it quite confusing
(I didn't spot the inheritance, and it sent me spinning for a while) and
my experience with test class inheritance (in past lives when I worked
on projects that used nosetests) is that it usually leads to test
maintenance horror by tightly coupling test classes to each other, and
by making code harder to understand as you have to refer to multiple
classes to follow it. The main problem though is that the inheritance
and coupling is …

Remove test class inheritance

---

.coveragerc
lms/views/application_instances.py
tests/unit/conftest.py
tests/unit/lms/views/basic_lti_launch_test.py
tests/unit/lms/views/test_application_instance.py

In preparation for replacing the lti_outcome_params fixture (in a future
PR) remove some unnecessary uses of it.
This reduced coverage so I increased it again by omitting some files
that really don't need to be tested.

Factor out lti_outcome_params fixture

---

lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js

- Add title on iframe
- Add LMS Grader mode axe test (as this felt reasonable) Note: There are also a number of Dialogs that popup inside BasicLtiLaunchApp that are not reflected in `checkAccessibility` here, as Dialog shall have its own accessibility tests that reflect those relative states.

Fix a11y lint in BasicLtiLaunchApp

---

.coveragerc
lms/services/grading_info.py
lms/views/helpers/frontend_app.py
tests/unit/lms/app_test.py
tests/unit/lms/services/grading_info_test.py
tests/unit/lms/views/helpers/frontend_app_test.py

Change `GradingInfoService.get_by_assignment()` to just return
`GradingInfo` objects instead of `(GradingInfo, HUser)` 2-tuples.
The calling code (in `frontend_app.py`) is now responsible for creating
the `HUser` object corresponding to each `GradingInfo` which it needs to
do in order to create the "student" dicts that it puts into the JS
config.
Overall this ends up making the tests for both `GradingInfoService` and
`frontend_app.py` simpler, and is a better division of work between the
two.

Change get_by_assignment() to just return GradingInfos

---

lms/resources/_js_config.py

A bunch of small JSConfig tidy-ups to pave the way for coming JSConfig changes:
* More docstrings
* More code comments
* Change things that don't need to be `@property`'s to just methods
* Change things that don't need to be either `@property`'s or methods to just attributes or inline them into `config()`
* `JSConfig._hypothesis_config` is renamed to `_hypothesis_client` to match its name in the config dict, and has `@functools.lru_cache()` added to it because future `JSConfig` code is going to need to mutate `self._hypothesis_client` as a dict

Tidy up JSConfig

---

lms/resources/_js_config.py
tests/unit/lms/resources/_js_config_test.py

Also move a general JSConfig test into `TestJSConfigHypothesisClient` to clarify which part of the code it is that raises.

Document JSConfig raised exceptions

---

lms/resources/_js_config.py

There's no particular order for these methods to go in that makes sense
and, in the final version of JSConfig that I have locally,
alphabetically turned out to work well. In future it will keep similar
methods together because similar naming conventions will be used.
This commit just puts things in alphabetical order ready for future PRs
to slot right in.

Sort JSConfig methods alphabetically

---

lms/static/scripts/frontend_apps/components/FileList.js
lms/static/scripts/frontend_apps/components/LMSFilePicker.js
lms/static/scripts/frontend_apps/components/StudentSelector.js
lms/static/scripts/frontend_apps/components/SubmitGradeForm.js
lms/static/scripts/frontend_apps/components/test/StudentSelector-test.js
lms/static/scripts/frontend_apps/components/test/SubmitGradeForm-test.js
lms/static/scripts/frontend_apps/utils/hooks.js
lms/static/scripts/frontend_apps/utils/test/hooks-test.js
lms/static/styles/components/_StudentSelector.scss
lms/static/styles/components/_SubmitGradeForm.scss

This is by no means complete, but getting there. I still see lots of areas we could improve and converge on in terms of CSS, but I'd rather reserve that work in the pattern lib than duplicate whats been done on the client.
In this PR:
- Change ValidationMessage to be a button and give is a focus state
-Change SubmitGradeForm to listen to onInput instead of onKeydown to dismiss validation message
- Give SubmitGradeForm a unique id counter for axe validation
- Add onBlur to StudentSelector.js
- Remove erroneous `<a>` tag in LMSFilePicker
- Add informative comment about enableLmsFilePicker prop
- Fix missing alt attribute in FileList

Various a11y lint fixes

---

lms/resources/_js_config.py
lms/static/scripts/frontend_apps/index.js
lms/views/basic_lti_launch.py
lms/views/content_item_selection.py
tests/unit/lms/resources/_js_config_test.py
tests/unit/lms/views/basic_lti_launch_test.py
tests/unit/lms/views/content_item_selection_test.py

Depends on https://github.com/hypothesis/lms/pull/1522 for the tests to pass.
The "mode" config setting tells the JavaScript code whether it should do a normal assignment launch (`"basic-lti-launch"` mode) or whether it should show the UI for the teacher to configure the assignment (selecting the document for the assignment) (`"content-item-selection"` mode).
The mode is now changed to default to `"basic-lti-launch"` mode, and it gets explicitly changed to `"content-item-selection"` in two specific places.
Previously the default was `"content-item-selection"` (but this default was implemented in JavaScript not Python) and it had to be explicitly set to `"basic-lti-launch"` and then in one place it had to be explicitly set back to `"content-item-selection"` again _after_ changing it to …

Centralize JSConfig 3/n: Move the "mode" JavaScript setting into JSConfig

---

lms/resources/_js_config.py
lms/views/basic_lti_launch.py
lms/views/content_item_selection.py
tests/unit/lms/resources/_js_config_test.py
tests/unit/lms/views/basic_lti_launch_test.py
tests/unit/lms/views/content_item_selection_test.py

The `"authUrl"` setting is the URL of the popup window that the
JavaScript code opens when it needs the user to get us a new Canvas API
access token by (re-)authorizing us with Canvas. It's actually a URL of
the LMS app itself, not a Canvas URL, but it redirects the popup window
to the appropriate Canvas URL.
This setting should probably be named something else given that it's
actually specific to the Canvas API.
It also belongs in the `"urls"` JavaScript setting (which is a dict of
all the URLs the JavaScript code needs to know about) not as its own
top-level setting.
But this PR limits itself to moving the `"authUrl"` setting into the
`JSConfig` class.
This change means that `"authUrl"` exists in the JS config all the time
not just some of the time, which does no harm.

Centralize JSConfig 4/n: Move the "authUrl" JavaScript setting into JSConfig

---

lms/resources/lti_launch.py
lms/views/basic_lti_launch.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/views/basic_lti_launch_test.py

Move `BasicLTILaunchViews.is_launched_by_canvas()` to
`LTILaunchResource.is_canvas` (a property).
This is necessary because future `JSConfig` code is going to need to
know whether the LMS is Canvas, and `JSConfig` can't access a
`BasicLTILaunchViews` method.
One thing that both `BasicLTILaunchViews` and `JSConfig` have access to
is the `LTILaunchResource` context, so they can both read
`context.is_canvas`.
Whether or not the LMS is Canvas also seems fitting as part of the
"context".
This is also in line with keeping views thin in general. One of the
reasons for keeping code out of views is that view code isn't reusable.
Context code is usable by the context itself, context helpers like
`JSConfig`, views, services that receive the context, etc.

Centralize JSConfig 5/n: Move is_canvas into LTILaunchResource

---

lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/LMSFilePicker.js
lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js
lms/static/scripts/frontend_apps/utils/AuthWindow.js
lms/static/scripts/frontend_apps/utils/test/AuthWindow-test.js
lms/views/basic_lti_launch.py
lms/views/content_item_selection.py
tests/unit/lms/views/basic_lti_launch_test.py
tests/unit/lms/views/content_item_selection_test.py

This setting is only ever set to "Canvas". Simplify both the backend and
frontend code by just using "Canvas" as a hardcoded string and removing
the setting.

Centralize JSConfig 1/n: Remove the lmsName JavaScript setting

---

lms/static/scripts/postmessage_json_rpc/server/server-test.js
lms/static/scripts/postmessage_json_rpc/server/server.js

Relates to https://github.com/hypothesis/client/pull/1843
**Add ability to have async RPC methods handlers** 
We need to add the ability for an RPC method to be async so it can fetch a result from the lms service and potentially block on the client (e.g groups). These changes allow the methods to return to the result asynchronously and delay the postMessage response according.

Add ability to have async RPC methods handlers

---

lms/resources/_js_config.py
lms/views/basic_lti_launch.py
tests/unit/conftest.py
tests/unit/lms/resources/_js_config_test.py
tests/unit/lms/views/basic_lti_launch_test.py

Depends on https://github.com/hypothesis/lms/pull/1522 for the tests to pass.
`"focused_user"` is a JavaScript config setting that gets sent to the Hypothesis client and causes it to focus on one particular user, showing only that user's annotations. It's only used in Canvas SpeedGrader launches, to get the client to focus on the student who is being graded. The `"focused_user"` setting is _not_ used by our non-Canvas grading UX.
There's also a change in behaviour in this PR: it now configures the client to focus on a user whenever there's a `focused_user` launch param. Previously it only did this when the LMS was Canvas _and_ there was a `focused_user` launch param. The is-Canvas check was both unnecessary and incorrect:
* In practice the `focused_user` launch param only ever appears in …

Centralize JSConfig 7/n: Move the focused_user into JSConfig

---

.coveragerc
lms/resources/_js_config.py
lms/views/basic_lti_launch.py
tests/unit/lms/resources/_js_config_test.py
tests/unit/lms/views/basic_lti_launch_test.py

Depends on https://github.com/hypothesis/lms/pull/1522 for the tests to pass.
Depends on https://github.com/hypothesis/lms/pull/1520.
This PR has two separate commits, and moves a bunch of JavaScript config settings out of the views and into `JSConfig`:
* `"via_url"` is the URL for the Via iframe that the JavaScript injects into the page.
The Via URL contains the URL of the document to be annotated (in the path part of the Via URL).
Where the document URL that's needed to construct the Via URL comes from varies between different types of assignments: for DB-configured assignments it's retrieved from the `module_item_configurations` table in the DB; for URL-configured assignment it's retrieved form the `"url"` LTI launch request param; for the `configure_module_item()` view it comes from a …

Centralize JSConfig 6/n: Move via_url, via_url_callback, and submissionParams into JSConfig

---

lms/services/_helpers/canvas_api.py
tests/unit/lms/services/_helpers/canvas_api_test.py

Looking at New Relic, some Canvas API's seem to take up to a second to
respond sometimes, so I've made the timeout pretty generous at 3
seconds.

Add a timeout to Canvas API requests

---

lms/static/scripts/frontend_apps/components/SubmitGradeForm.js
lms/static/scripts/frontend_apps/components/ValidationMessage.js
lms/static/scripts/frontend_apps/components/test/SubmitGradeForm-test.js
lms/static/scripts/frontend_apps/components/test/ValidationMessage-test.js
lms/static/styles/components/_ValidationMessage.scss

This PR is exactly what was posted before, and we can continue the conversation here.
The first issue here is that a `<div>` cant have a click event. To fix that, I made it a `<button>` which created a second and more subtle a11y issue with axe validation of a parent component building this component without a `message` prop. It causes axe to complain about the button not having a readable message.
The fix was to make SubmitGradeForm selective about rendering ValidationMessage. It was not sufficient to isolate the condition directly into ValidationMessage -- this caused some unfortunate animation issues with css key frames that after many attempts, I could not work out nicely. This solution should be suffice for a11y and it renders nice. I think the one drawback is the condition inside of …

Fix a11y lint for ValidationMessage

---

lms/views/helpers/_via.py
tests/unit/lms/views/helpers/_via_test.py

This is needed to inform the client which ancestor frame to send RCP requests to. This PR needs to land before we can make any changes to via so it won't cause errors downstream.

Add via.config_frame_ancestor_level to via_url

---

lms/static/scripts/frontend_apps/common/dom.js
lms/static/scripts/frontend_apps/common/test/dom-test.js
lms/static/scripts/frontend_apps/common/test/use-element-should-close-test.js
lms/static/scripts/frontend_apps/common/use-element-should-close.js
lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
lms/static/scripts/frontend_apps/components/Dialog.js
lms/static/scripts/frontend_apps/components/ErrorDialog.js
lms/static/scripts/frontend_apps/components/test/Dialog-test.js

This is a continuation of this PR https://github.com/hypothesis/lms/pull/1481
In summary 
- Dialog may now have either a “dialog” or an “alertdialog” role depending what its used for.
- Dialog no longer has an `onKeyDown` handler. (a11y issue)
- `Escape` keyboard event is now handled with useElementShouldClose
- Add aria-modal=“true” prop to Dialog
- Dialog `id` prop is now generated with useUniqueId
- Expand Dialog `button` prop types for better accuracy
dom.js and use-elemenet-should-close.js are direct copies from the client added to a new common/ folder until we can get an imported package for such things.

Fix a11y for Dialog

---

lms/resources/_js_config.py
lms/templates/base.html.jinja2
tests/unit/lms/resources/_js_config_test.py
tests/unit/lms/views/basic_lti_launch_test.py
tests/unit/lms/views/content_item_selection_test.py

Change the mutable property JSConfig.config to a private, mutable
property JSConfig._config (it's still mutated by code within JSConfig).
Add a new JSConfig.asdict() method for the one place where code outside
of JSConfig needs to actually access the config dict (in the base
template, where it gets rendered to JSON).
Since the new asdict() just returns self._config anyway, this doesn't
make any real difference. But it might clarify the intent: code outside
of JSConfig isn't supposed to read or write the underlying config dict
anymore.

Make JSConfig.config private

---

.coveragerc
conf/development.ini
lms/config/__init__.py
lms/resources/_js_config.py
lms/static/scripts/postmessage_json_rpc/server/index.js
lms/static/scripts/postmessage_json_rpc/server/methods-test.js
lms/static/scripts/postmessage_json_rpc/server/methods.js
tests/conftest.py
tests/unit/lms/config/__init___test.py

Nothing actually calls this yet. But I have hacked the client to call it locally, and verified that it returns the list of one group ID.
Fixes https://github.com/hypothesis/lms/issues/1555

Add RPC server requestGroups method with artificial delay in dev

---

lms/app.py

Currently due to two different issues cookie based feature flags are disabling the feature flag feature across LMS:
* Feature flags are effected in an order. If a later flag provider disables a flag it is turned off
* Due to the lack of tri-state in cookie flags (https://github.com/hypothesis/lms/issues/790) it can only turn flags on or off
* Due to a bug where cookie flags are always off, any cookie flags are always disabled

Disable cookie feature flags until it's fixed

---

conf/development.ini
lms/views/helpers/_via.py
tests/unit/lms/views/helpers/_via_test.py

The previous change did not add the required `/route` to the URL for Via 3. Also changed the feature flag to be `use_via3` as I think that makes more sense than `use_via3_url`.
Feature flags are pretty bust in LMS, so to test this you either have to disable `feature_flags_allowed_in_cookie = use_via3`, or after this PR (https://github.com/hypothesis/lms/pull/1571) cookie flags will be disabled.

Fix via3 route and use more sensible feature flag name

---

README.markdown
conf/development.ini
lms/config/__init__.py
lms/views/helpers/_via.py
tests/conftest.py
tests/unit/lms/config/__init___test.py
tests/unit/lms/views/helpers/_via_test.py

You can now enable legacy Via with:
```bash
export FEATURE_FLAG_USE_LEGACY_VIA=true
```
----
This requires rebasing after a few other things:
* https://github.com/hypothesis/lms/pull/1572
* https://github.com/hypothesis/lms/pull/1571

Swap Via 3 to be the default with legacy Via as a feature flag

---

lms/resources/_js_config.py
lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
tests/unit/lms/resources/_js_config_test.py

This PR moves `urls.via_url` to a top-level setting and renames it to `viaUrl`. The `urls` sub-object will eventually be going away.

JS config reorganization 1/n: viaUrl

---

lms/resources/_js_config.py
lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/SubmitGradeForm.js
lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
lms/static/scripts/frontend_apps/config.js
tests/unit/lms/resources/_js_config_test.py

This PR introduces the new `"api"` sub-object and moves the `"via_url_callback"` setting into it, and renames it to `"viaCallbackUrl"`. The previously top-level `"authToken"` setting also moves under `"api"` (this is the token for authenticating API requests).

JS config reorganization 2/n: api 

---

bin/qt
lms/resources/_js_config.py
lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/LMSFilePicker.js
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js
tests/unit/lms/resources/_js_config_test.py

This PR moves all the file-picker related settings into a new `"filePicker"` sub-object and renames many of them. Canvas picker settings are in a `"canvas"` sub-sub-object and Google Picker settings in a `"google"` sub-sub-object.

JS config reorganization 3/n: filePicker

---

lms/resources/_js_config.py
lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
tests/unit/lms/resources/_js_config_test.py

This PR moves the `lmsGrader` setting into the already-existing `grading` sub-object of the JavaScript config object with the rest of the grading-related settings, and renames it to `enabled`. All grading settings are now gathered together in the `grading` sub-object.

JS config reorganization 4/n: grading

---

lms/resources/_js_config.py
lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
tests/unit/lms/resources/_js_config_test.py

This PR moves Canvas-specific settings into a `"canvas"` sub-object. `authUrl` is now `canvas.authUrl`, and `submissionParams` is now `canvas.speedGrader.submissionParams`.

JS config reorganization 5/n: canvas

---

tests/unit/lms/resources/lti_launch_test.py

`LTILaunchResource` is too large and as a result its test class is too large. We have cards coming up that will involve necessarily splitting `LTILaunchResource` up into multiple classes. For now, and in preparation, split its tests up into one test class per method.
This makes the tests easier to add to which we'll be doing soon.
Also removes some duplication from the tests by moving code into class-level fixtures.
Also clarifies the tests by having each test class have its own `pyramid_request` fixture, so you can see which request params each method being tested actually depends on.

Split up a test class into multiple test classes

---

tests/unit/lms/resources/lti_launch_test.py

Using more compact fixtures to reduce the size of the tests and make them easier to read

Make the h_display_name tests more compact

---

lms/resources/lti_launch.py
tests/unit/lms/resources/lti_launch_test.py

Add a method, `h_section_groupid()`, for deterministically generating a unique h groupid for a Canvas course section.
Fixes https://github.com/hypothesis/lms/issues/1410
See https://github.com/hypothesis/lms/issues/1410#issuecomment-603248954 for the design of the IDs

Add unique section groupid function

---

lms/resources/lti_launch.py
tests/unit/lms/resources/lti_launch_test.py

Fixes https://github.com/hypothesis/lms/issues/1411
The method of generating the name for a section group is just the same as how we currently [generate the names for course groups](https://github.com/hypothesis/lms/blob/cba173c7b75bda2700b1077cc07050ec68bf6059/lms/resources/lti_launch.py#L109-L133): just take the course/section name from Canvas, strip leading and trailing whitespace, and truncate it to 25 chars because that's as long as group names can be in h.
These group names do not need to be unique.
Background:
* [How to make test calls to the Canvas API](https://github.com/hypothesis/lms/wiki/How-to-Test-the-Canvas-API)
* [How to get all a course's sections from the Canvas API](https://github.com/hypothesis/lms/issues/1404) (`http GET …

Add section group name method

---

lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js

The speedGrader object is undefined so it needs to be checked before referencing a key inside of it.
I  will need to add testing for this new bit, but would like to patch prod right away. I may need to take a deeper look at the changes over the last 2 days too. But I think this puts out fires for now

Fix js error when loading assignments outside of canvas

---

tests/unit/lms/validation/_canvas_test.py

Replace some test class inheritance with shared test helper functions
and a parametrized fixture. This is simpler, more idiomatic in pytest,
and keeps test classes simple and independent and decoupled from each
other which makes the tests easier to understand and to change.
The same as done elsewhere, e.g. https://github.com/hypothesis/lms/pull/1502
The way this worked previously was that `CommonResponseSchemaTests` was
not itself a test class (it doesn't begin with `Test` so pytest won't
find it and run it) but it was used as a base class for
`TestCanvasListFilesResponseSchema` and
`TestCanvasPublicURLResponseSchema` which therefore both inherited
`CommonResponseSchemaTests`'s test methods.
`CommonResponseSchemaTests`'s tests then made use of a `schema` fixture
which …

Replace test class inheritance with functions

---

lms/services/_helpers/canvas_api.py

Each of these functions is only called in one place, and the calling
functions are still pretty short if you inline the private helper
functions, so they don't really make much sense as separate private
helper functions.
There's still a `_token_url()` helper because that one is actually
called in two different places.

Inline some private helper functions

---

tests/unit/lms/services/_helpers/canvas_api_test.py

I'm not sure why `make sure` isn't picking this up but running pylint directly on this file discovered these warnings

Fix some pylint warnings

---

tests/unit/lms/views/api/canvas/files_test.py
tests/unit/test_missing_init_files.py

Fixes https://github.com/hypothesis/lms/issues/1606
Also add a test to make sure no more test directories without an `__init__.py`
get added in future.
Also fix one lint warning that was being covered up by a missing `__init__.py`.

Add missing __init__.py files in tests

---

lms/views/api/canvas/README.md
lms/views/api/canvas/authorize.py
lms/views/api/canvas/files.py

files.py, which is just for the files-related proxy API views, had a module docstring that really documented the entire proxy API package. Moved this to a README.md file and added new docstrings to files.py and authorize.py
Here's the new README.md rendered as the `views/api/canvas` folder's README on GitHub: https://github.com/hypothesis/lms/tree/canvasapi-docstrings/lms/views/api/canvas

Reorganize some docstrings

---

.coveragerc
lms/services/_helpers/canvas_api.py
lms/services/canvas_api.py
lms/validation/__init__.py
lms/validation/_canvas.py
tests/unit/lms/services/_helpers/canvas_api_test.py
tests/unit/lms/services/canvas_api_test.py
tests/unit/lms/validation/_canvas_test.py

Add support for getting sections from the Canvas API in various ways.
Fixes https://github.com/hypothesis/lms/issues/1403
Fixes https://github.com/hypothesis/lms/issues/1404
Fixes https://github.com/hypothesis/lms/issues/1405
Note that there are no proxy API views/endpoints for these new Canvas API calls. There are only service methods for making the calls. These APIs aren't meant to be called by our frontend code directly. They'll be called by our backend code as appropriate (in response to sync API calls from the frontend)
There are three different circumstances under which we're going to need to retrieve sections from the Canvas API, in three different ways:
1. When a teacher (or any non-student) launches an assignment we want them to see the section groups for _all_ of the course …

Add support for getting sections from the Canvas API

---

tests/functional/api/basic_lti_launch.py
tests/unit/conftest.py

yield_fixture is deprecated:
https://docs.pytest.org/en/latest/yieldfixture.html
The one yield_fixture that this commit does not remove, has already been
removed by this open PR:
https://github.com/hypothesis/lms/pull/1612

Don't use deprecated yield_fixture

---

lms/services/h_api.py
lms/services/lti_h.py
lms/views/basic_lti_launch.py
lms/views/content_item_selection.py
tests/unit/lms/services/h_api_test.py
tests/unit/lms/services/lti_h_test.py

_From linked ticket https://github.com/hypothesis/lms/issues/1567:_
> Currently our code in the views calls separate methods to upsert groups, users and user membership. This should all be collected together in a single interface to prepare for bulk calling.
> 
> At the end of this ticket:
> 
> There will be a fascade for bulk calling H
> This will accept all of the details to update in one go
> The code will have been altered to use it
> Internally it will use existing mechanisms to update H as we do now
> 
The word 'facade' is used here to indicate that although we are accepting data _as if_ we are the bulk API, we are not actually implementing any bulk processing at this point. The existing `LITHService` was chosen as the target.
This is to allow work to progress in tandem with the …

Change LTIHService to look like it will with the bulk API

---

.coveragerc
lms/services/h_api.py
lms/services/lti_h.py
tests/unit/lms/services/h_api_test.py
tests/unit/lms/services/lti_h_test.py

Automatically create a machine user in h and use it as the group's creator when creating groups.
Fixes https://github.com/hypothesis/lms/issues/1400

Use a machine user to create groups

---

tests/unit/lms/authentication/_helpers_test.py
tests/unit/lms/validation/authentication/_launch_params_test.py

The schema being tested here is called LaunchParamsAuthSchema / launch_params_auth_schema, not LaunchParamsSchema. Especially since there's actually another schema elsewhere in the code that _is_ called LaunchParamsSchema, it's best if the tests use the schema's full name here.

Fix some naming in tests

---

lms/resources/lti_launch.py
lms/validation/__init__.py
lms/validation/_lti_launch_params.py
lms/views/basic_lti_launch.py
lms/views/content_item_selection.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/validation/_lti_launch_params_test.py
tests/unit/lms/views/basic_lti_launch_test.py

`LTILaunchResource` has a `_get_param()` helper that returns a param
from `request.params` or raises `HTTPBadRequest` if the param doesn't
exist:
https://github.com/hypothesis/lms/blob/4442b8f48afc3df7c11d496a3b1487603b5fea03/lms/resources/lti_launch.py#L247-L254
This legacy validation (it pre-dates the `lms.validation` package and the introduction of marshmallow) happening in the wrong place and at the wrong time is problematic for a bunch of reasons, and is really getting in the way of necessary refactoring needed to introduce the sync API. See the commit message of <https://github.com/hypothesis/lms/pull/1615/commits/4e54d571fbbe99e5c140b89f300ccdd435c6ed00> for details.
Fortunately this validation within `LTILaunchResource` also turns out to be unnecessary because most of the views …

Remove unnecessary validation code from LTILaunchResource

---

lms/validation/_module_item_configuration.py
tests/unit/lms/validation/_module_item_configuration_test.py

A recent commit changed a bunch of code in `LTILaunchResource` to read
from `request.parsed_params` not `request.params`. This means the params
being read must be added to the validation schema that the view uses.
We forgot to update the `configure_module_item()` view and its
`ConfigureModuleItemSchema`.
Fixes https://github.com/hypothesis/lms/issues/1626

Fix creating assignments in non-Canvas LMS's

---

lms/resources/_js_config.py
lms/services/lti_h.py
tests/unit/lms/resources/_js_config_test.py

Just make some code more concise by adding a few convenience variables
to `self`.
One test had to be fixed up because it was replacing `request.lti_user`
with a new object _after_ the request had already been passed to
`JSConfig`, but `JSConfig` now reads `request.lti_user` in its
`__init__()` so it still had the old `lti_user`. The fix makes the test
more correct anyway.

Add some convenience variables

---

lms/services/__init__.py
lms/services/application_instance_getter.py
tests/unit/lms/services/__init___test.py
tests/unit/lms/services/application_instance_getter_test.py

Separate `application_instance_getter_service_factory()` from the `ApplicationInstanceGetter` class itself.
This is because I'm expecting to have to register two different `ApplicationInstanceGetter` factories in two different contexts, in a future PR.
We have two different ways of doing pyramid_services in h and lms: in h the service class itself is "pure" and the factory is a separate function. In lms the service class's `__init__()` is used as the factory, so the service class itself has a dependency on `context` and `request`. I think h's way is better here and we should start migrating lms's services to it: it allows service classes to be decoupled from Pyramid, and it allows different service factories for the same service class to be registered in different contexts. Or you can …

Separate ai_getter service from service factory

---

tests/conftest.py
tests/factories/__init__.py
tests/factories/lti_user.py
tests/unit/conftest.py
tests/unit/lms/authentication/_helpers_test.py
tests/unit/lms/models/lti_user_test.py
tests/unit/lms/resources/_js_config_test.py
tests/unit/lms/services/canvas_api_test.py
tests/unit/lms/services/grading_info_test.py
tests/unit/lms/services/lti_h_test.py
tests/unit/lms/services/oauth1_test.py
tests/unit/lms/validation/authentication/_bearer_token_test.py
tests/unit/lms/validation/authentication/_oauth_test.py
tests/unit/lms/views/basic_lti_launch_test.py
tests/unit/lms/views/predicates/_lti_launch_test.py
tox.ini

In a future PR I need to add a new required argument to `LTIUser()`, which will mean updating everywhere that `LTIUser()` is called. `LTIUser()` is only called in a few places in the code, but it's called in many places in the tests, and those would all need to be updated.
Instead, add an `LTIUser` test factory so that `LTIUser()`'s arguments can be changed in future without having to change a lot of test code. Instead of calling `values.LTIUser(...)` and having to pass every required param every time, tests now call `factories.LTIUser()` with no arguments and the factory generates values for all of `values.LTIUser()`'s parameters. Or, if the test needs to pass a specific value for one of `LTIUser`'s params, it does `factories.LTIUser(some_param="some_value")`, passing only the arguments …

Add LTIUser test factory

---

lms/models/application_instance.py
lms/resources/_js_config.py
lms/resources/lti_launch.py
lms/services/__init__.py
lms/services/_helpers/canvas_api.py
lms/services/application_instance_getter.py
lms/services/canvas_api.py
lms/services/exceptions.py
lms/services/launch_verifier.py
lms/services/lti_h.py
lms/services/oauth1.py
lms/views/api/canvas/authorize.py
tests/unit/lms/models/test_application_instance.py
tests/unit/lms/resources/_js_config_test.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/services/_helpers/canvas_api_test.py
tests/unit/lms/services/application_instance_getter_test.py
tests/unit/lms/services/canvas_api_test.py
tests/unit/lms/services/launch_verifier_test.py
tests/unit/lms/services/lti_h_test.py
tests/unit/lms/views/api/canvas/authorize_test.py

Simplify `ApplicationInstanceGetter` and decouple `LTIHService` from `LTILaunchResource.provisioning_enabled`. This is part of decoupling `LTIHService` from `LTILaunchResource` entirely, so that `LTIHService` can be used in other request contexts (specifically: so that it can be used in new sync API requests).
* Change `ApplicationInstanceGetter` to receive `request.params["oauth_consumer_key"]` from pyramid_services rather than requiring it to be passed in to each method. This changes `ApplicationInstanceGetter.foo(consumer_key)` to just `ApplicationInstanceGetter.foo()` simplifying code that uses it
* Remove `LTILaunchResource.provisioning_enabled` and `LTILaunchResource.lms_url`. These were just wrappers for `ApplicationInstanceGetter` that injected …

Decouple LTIHService from LTILaunchResource.provisioning_enabled

---

.coveragerc
README.markdown
lms/assets.py
lms/db/__init__.py
lms/services/grading_info.py
lms/views/__init__.py
lms/views/api/lti.py
tests/unit/lms/config/__init___test.py
tests/unit/lms/services/grading_info_test.py
tests/unit/lms/validation/_lti_launch_params_test.py

I keep accidentally reducing coverage by deleting lines, causing the coverage test to fail, which wastes developer time. Also if I really have added lines with no coverage, I have to look for my lines in amongst the not-covered-on-master lines in the coverage report.
Fix both issues by getting coverage to 100%.
In some cases to increase coverage I fixed broken tests or added missing tests, or fixed bad code. See individual commit messages for details.
In the final commit I covered a handful of things that aren't worth testing or would be a big pain to test with `# pragma: no cover` comments. The 100% coverage is a practical benefit in itself, for the reasons above.

Get LMS unit tests to 100% percent code and branch coverage

---

lms/validation/authentication/_launch_params.py

roles is a required param so calling .get() isn't necessary here

Remove an unnecessary .get()

---

tests/factories/__init__.py
tests/factories/h_user.py
tests/unit/conftest.py
tests/unit/lms/models/h_user_test.py
tests/unit/lms/resources/_js_config_test.py
tests/unit/lms/services/grading_info_test.py
tests/unit/lms/services/h_api_test.py
tests/unit/lms/services/lti_h_test.py

Similar to `factories.LTIUser`, this is going to reduce the amount of test refactoring needed when we add new required parameters to `models.HUser` in the future, and it also forces us to improve our tests:
Add `factories.HUser`, a test factory for `models.HUser`, and change all the tests to use it instead of creating `HUser` objects directly.
This forces us to improve the tests by not specifying specific field values for test `HUser` objects when the test doesn't care about the specific values, but still specifying specific values for certain fields when the test _does_ care about them.

Add factories.HUser

---

lms/static/scripts/frontend_apps/components/Dialog.js
lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js

- Refactor BasicLtiLaunchApp-test to have a separate speed grader describe block.
- Fix <Dialog> propType warning
fixes https://github.com/hypothesis/lms/issues/1628

Add missing speedGrader config test to BasicLtiLaunchApp-test.js

---

lms/models/__init__.py
lms/models/lti_user.py
lms/resources/lti_launch.py
lms/validation/authentication/_bearer_token.py
lms/validation/authentication/_launch_params.py
tests/factories/lti_user.py
tests/unit/lms/models/lti_user_test.py
tests/unit/lms/resources/_js_config_test.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/validation/authentication/_launch_params_test.py

Add a few more fields to `models.LTIUser` (the `request.lti_user` object). Specifically, this adds all the fields necessary to generate a `models.HUser` object from _just_ a `models.LTIUser` object, and future PRs will refactor the `HUser`-generating code to do just that.

Add new fields to LTIUser

---

tests/unit/lms/services/grading_info_test.py

GradingInfoService doesn't use context.h_user.

Remove an unused context.h_user fixture

---

tests/unit/lms/services/lti_h_test.py

LTIHService doesn't use context.provisioning_enabled

Remove an unused provisioning_enabled fixture

---

lms/models/h_user.py
lms/resources/lti_launch.py
lms/services/h_api.py
lms/services/lti_h.py
tests/factories/h_user.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/services/h_api_test.py
tests/unit/lms/services/lti_h_test.py

`LTILaunchResource` currently has three separate properties:
1. `LTILaunchResource.h_user`. Returns a `models.HUser` object.
2. `LTILaunchResource.h_provider`
3. `LTILaunchResource.h_provider_unique_id`
`h_provider` and `h_provider_unique_id` are really part of the `HUser`:
they're only really used by `LTILaunchResource.h_user`.
Add two new attributes `provider` and `provider_unique_id` to `models.HUser`,
change `LTILaunchResource.h_user` to set them, and delete
`LTILaunchResource.h_provider` and `LTILaunchResource.h_provider_unique_id`.
Code that was previously reading `context.h_provider` and
`context.h_provider_unique_id` can now read `context.h_user.provider`
and `context.h_user.provider_unique_id` instead.
This also simplifies the `HAPI` service as `HAPI.create_user()` and …

Add provider and provider_unique_id fields to HUser

---

lms/models/h_user.py
lms/resources/_js_config.py
lms/resources/lti_launch.py
lms/services/h_api.py
tests/factories/h_user.py
tests/unit/lms/models/h_user_test.py
tests/unit/lms/resources/_js_config_test.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/services/h_api_test.py

Remove the `authority` attribute from `models.HUser`, and change the
`userid()` property to a `userid(authority)` instance method.
This makes creating `HUser`'s easier because you don't need
`request.registry.settings["h_authority"]` to create one.
This comes at the cost of making getting an `HUser`'s `userid` more
difficult: you now need to pass in
`request.registry.settings["h_authority"]` to the `userid` method.
Previously you could have accessed `h_user.userid` without passing in
the authority, if you had been given an already-created `HUser` from
somewhere else. But if you had to create the `HUser` yourself then you
would have needed the `"h_authority"` setting to create it anyway.
In practice I think the code is overall simpler and more flexible if we
delay needing the …

Remove authority from models.HUser

---

lms/models/h_user.py
lms/models/lti_user.py
lms/resources/_js_config.py
lms/resources/lti_launch.py
lms/services/lti_h.py
lms/views/basic_lti_launch.py
tests/unit/lms/models/h_user_test.py
tests/unit/lms/models/lti_user_test.py
tests/unit/lms/resources/_js_config_test.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/services/lti_h_test.py
tests/unit/lms/views/basic_lti_launch_test.py

Move the `LTILaunchResource.h_user` (`context.h_user`) property, which
returns the `HUser` for the current request, to
`request.lti_user.h_user`:
1. Add a new factory classmethod `models.HUser.from_lti_user(lti_user)`
that constructs an `HUser` from an `LTIUser`
2. As a convenience add a new instance property `models.LTIUser.h_user`
which is the `HUser` for the given `LTIUser`
3. This means that instead of `context.lti_user` which only works when
the context is an `LTILaunchResource`, code can now do
`request.lti_user.h_user` instead, which works whenever
`request.lti_user` isn't `None`. So code that uses the `h_user` is
now decoupled from `LTILaunchResource` and can be used in other
contexts.
4. Delete `LTILaunchResource.h_user` now that it's no longer used

Move LTILaunchResource.h_user to request.lti_user.h_user

---

tox.ini

This is broken with pip-tools 5, pin to an older version.

Fix `make pip-compile`

---

lms/models/__init__.py
lms/models/h_group.py
lms/resources/_js_config.py
lms/resources/lti_launch.py
lms/services/h_api.py
lms/services/lti_h.py
tests/factories/__init__.py
tests/factories/h_group.py
tests/unit/lms/models/h_group_test.py
tests/unit/lms/resources/_js_config_test.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/services/h_api_test.py
tests/unit/lms/services/lti_h_test.py

Add a new `models.HGroup` domain model class with
`authority_provided_id`, `groupid` and `group_name` attributes and
combine the three separate `LTILaunchResource` properties
`h_authority_provided_id`, `h_groupid` and `h_group_name` into a single
`h_group` property that returns an `HGroup`.

Merge h_authority_provided_id, h_groupid and h_group_name into h_group

---

lms/services/lti_h.py
lms/views/basic_lti_launch.py
lms/views/content_item_selection.py
tests/unit/lms/services/lti_h_test.py

This finishes decoupling `LTIHService` from `LTILaunchResource` (`self._context`) and means that `LTIHService` should now be callable by the sync API:
Remove `LTIHService.single_group_sync()` which was just a convenience method for doing `self.sync([self._context.h_group])`. Just have the views call `lti_h_svc.sync([context.h_group])` instead. The sync API view will call `lti_h_svc.sync([group_created_in_some_other_way])`

Remove single_group_sync() and decouple LTIHService from LTILaunchResource (context)

---

tests/factories/__init__.py
tests/factories/_attributes.py
tests/factories/grading_info.py
tests/factories/h_user.py
tests/factories/lti_user.py
tests/unit/conftest.py
tests/unit/lms/services/grading_info_test.py

Add a test factory for `models.GradingInfo`. Since this is the first test factory for a DB model to be added to LMS, it requires integrating Factory Boy with the DB session.
When you do `factories.GradingInfo()` (or `factories.GradingInfo.create_batch(n)`) it automatically adds them to the DB session for you.
I haven't tested but I don't think this would work in an `@parametrize` because, even though the factory classes are just imported directly not accessed via a `factories` fixture like in h, the DB session won't have been set up at the time the `@parametrize` gets evaluated so it'll crash.
_But_ you can do `factories.GradingInfo.build()` or `build_batch(n)` which just creates `GradingInfo`'s without adding them to the DB. This means that your test can use the factory without using the …

Add GradingInfo factory

---

lms/views/helpers/_via.py
tests/unit/lms/views/helpers/_via_test.py

This enables new style params which are programatically understood and passed onto the client, instead of catered for individually.
This cannot be merged until the enabling PRs to make via and via3 accept this style have been put in place:
* https://github.com/hypothesis/via3/pull/125
* https://github.com/hypothesis/via/pull/228

2 - Use new style via params "via.client.*"

---

lms/validation/_canvas.py
tests/unit/lms/validation/_canvas_test.py

When the sections dicts returned by the Canvas API contained additional items that we don't care about (which they do, with the real Canvas API) `CanvasAuthenticatedUsersSectionsResponseSchema` was raising a validation error. Fix it to just ignore the additional items instead.

Fix a bug in CanvasAuthenticatedUsersSectionsResponseSchema

---

lms/models/__init__.py
lms/models/h_group.py
lms/resources/lti_launch.py
tests/unit/lms/models/h_group_test.py
tests/unit/lms/resources/lti_launch_test.py

Extract the `_group_name()` helper method out of `LTILaunchResource` into the domain model. This reduces some test duplication, and also makes it so that future code outside of `LTILaunchResource` can call `models.h_group_name()` without duplicating any code.
Same approach as with `display_name()` for `models.LTIUser`

Extract group_name() into model

---

tox.ini

PyLint 2.5's new way of importing code doesn't work with our apps.
See:
https://github.com/PyCQA/pylint/blob/303b8d852e469379cd0f1a8891a018de5e39a966/ChangeLog#L83-L90
https://github.com/PyCQA/pylint/issues/3386
https://github.com/PyCQA/pylint/pull/3411
https://hypothes-is.slack.com/archives/C1MA4E9B9/p1587994973069200

Fix a `make lint` crash by downgrading PyLint

---

lms/db/__init__.py
tests/unit/lms/db/__init___test.py

Add a `__repr__()` to `GradingInfo`. I found this useful when debugging some test stuff.
Might be a nicer way of implementing it using [`reprlib`](https://github.com/hypothesis/lms/pull/new/add-GradingInfo-repr)?

Add GradingInfo.__repr__()

---

lms/views/helpers/_via.py
tests/unit/lms/views/helpers/_via_test.py

Got a little fancy here and introduced a simple model class here to help re-use some of the logic. The idea is to make the central bit nice and declarative (if is_pdf do this).
The document object also paves the way for us to specify that something is a PDF for Canvas docs (in the next PR)
The logic has been split into some model object so represent:
* The document 
* Via itself, making URLs based the document
The document contains a "content_type" which you can set, but if you don't it will use the same regex we have in Via 3 to guess that the doc is a PDF when we see a Google Drive doc.
The objects are tested as blackbox private components of `via_url`.
This is mostly about observing what URLs are constructed when we look at various docs by LMS. So here are some URLs to follow on the …

Skip Via 3 routing for Google Drive documents

---

lms/models/group_info.py
lms/models/oauth2_token.py
tests/unit/lms/models/group_info_test.py
tests/unit/lms/models/oauth2_token_test.py

All SQLAlchemy models already inherit a `__repr__()` from the base
class, so these aren't necessary. `__str__()` seems to fall back to just
using `__repr__()` too which is fine.
https://github.com/hypothesis/lms/blob/809b24db432e8bd61ebd294b06e7c5372b5e0456/lms/db/__init__.py#L61-L68

Remove unnecessary __str__ and __repr__ methods

---

lms/views/api/canvas/files.py
lms/views/helpers/_via.py
tests/unit/lms/views/api/canvas/files_test.py
tests/unit/lms/views/helpers/_via_test.py

This is a performance improvement which should be snappier for users and put less load on Via3.
This must be merged after: https://github.com/hypothesis/lms/pull/1685

Skip Via 3 routing for Canvas files, which are always PDFs

---

lms/resources/_js_config.py
lms/resources/default.py
lms/resources/lti_launch.py
lms/routes.py
lms/views/api/canvas/sync.py
tests/unit/lms/models/h_group_test.py
tests/unit/lms/resources/_js_config_test.py
tests/unit/lms/resources/default_test.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/routes_test.py
tests/unit/lms/views/api/canvas/sync_test.py

Add the new sync API and, if the `section_groups` feature flag is on, add the JavaScript config necessary to tell the frontend to call the sync API.
Fixes https://github.com/hypothesis/lms/issues/1566
Fixes https://github.com/hypothesis/lms/issues/1389
This PR does not include the frontend changes necessary to make it respond to the new config and actually call the sync API.
1. Adds a `context.should_use_section_groups` boolean. For now, sections groups are enabled if you're in Canvas and you have the `section_groups` feature flag on.
1. Adds the new sync API: route, ACL and view.
When called, the sync API fetches the sections from Canvas, generates groups from them, upserts the groups into h, and returns the list of groupids.
1. Adds new sync API settings to the JavaScript config.
This …

Add feature-flagged sync API

---

lms/models/group_info.py
lms/models/lti_user.py
lms/services/group_info.py
lms/validation/authentication/_bearer_token.py
lms/validation/authentication/_launch_params.py
tests/unit/conftest.py
tests/unit/lms/models/group_info_test.py
tests/unit/lms/services/group_info_test.py

Fixes https://github.com/hypothesis/lms/issues/1701
Depends on https://github.com/hypothesis/lms/pull/1704
Record info about instructors who launch our app in the `group_info`
table:
* Add a new JSON column `group_info.info`.
So far this is a JSON object with a single top-level key "instructors"
that contains a list of instructor dicts.
`group_info.info` can be extended with more info (besides instructors)
in future without a DB migration.
The instructor dicts can also be extended to hold more field in future
without a DB migration.
* Add a `GroupInfo.instructors` read-write property for convenience, and
a `GroupInfo.upsert_instructor(dict)` method the creates-or-updates an
instructor dict in a `GroupInfo`'s instructors list.
* When an instructor launches an assignment, have …

Add instructor info to group_info table

---

lms/models/group_info.py
lms/models/h_group.py
lms/services/group_info.py
lms/services/lti_h.py
lms/views/api/canvas/sync.py
tests/unit/lms/models/group_info_test.py
tests/unit/lms/services/group_info_test.py
tests/unit/lms/services/lti_h_test.py
tests/unit/lms/views/api/canvas/sync_test.py

Add a new `type` field to `group_info` that records whether a group is a course group or a section group.

Add "type" to group_info

---

lms/templates/api/canvas/oauth2_redirect_error.html.jinja2
lms/views/api/canvas/authorize.py
tests/unit/lms/views/api/canvas/authorize_test.py

Fixes https://github.com/hypothesis/lms/issues/1718
**Note**: You'll want to delete all your Canvas API access tokens from your dev DB when testing this, to force it to open the authorization popup window to try to get a new token. Run: `tox -qe docker-compose -- exec postgres psql -U postgres -c 'delete from oauth2_token;'`
**Note**: We currently only use the Canvas API for Canvas Files assignments, so you'll want to launch a Canvas Files test assignment to test this.
When creating or launching a Canvas Files assignment, if we don't already have a working Canvas API access token for the user, we open a popup window to get the user to authorize us with Canvas and save a new access token to the DB.
There are two ways that this authorization popup window dance can fail:
1. Canvas might …

Fix the error page when our Canvas developer key lacks required scopes

---

lms/static/scripts/frontend_apps/components/LMSGrader.js
lms/static/scripts/frontend_apps/components/test/LMSGrader-test.js

The client attempts to discover a last name based off the displayName, but if it does not exist, then it sorts by first name.
Additionally if there are more separators, then every word past the first is assumed to be part of the last name. This may be a false assumption but its a best effort with only having a displayName.
Finally, the displayName is changed from the service layer to show the last then first. e.g. “{last}, {first}”
---------
I thought this was going to be a bit more straight forward, nothing with LMS ever is! :)
So we have to make some assumptions here and handle all the edge cases. We really don't know what the first or last names are so I went ahead with some general assumptions that hopefully are mostly right or at least make some sense when ordering.
To test, try this …

Sort students by last, then first name

---

lms/services/canvas_api.py
tests/unit/lms/services/canvas_api_test.py

This is to prepare for splitting these into separate files which work together.
This PR:
* Keeps everything in the same files
* Moves all the basic calling machinery and authentication to a base class
* Has all the data calls implemented on top of that
* Removes some duplicate mentions (every function can raise the same errors)

Split the Canvas API into a data part and authentication part

---

lms/models/application_instance.py
lms/resources/_js_config.py
lms/resources/lti_launch.py
lms/services/application_instance_getter.py
lms/views/api/canvas/authorize.py
lms/views/application_instances.py
tests/unit/lms/models/application_instance_test.py
tests/unit/lms/models/test_application_instance.py
tests/unit/lms/resources/_js_config_test.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/services/application_instance_getter_test.py
tests/unit/lms/views/api/canvas/authorize_test.py
tests/unit/lms/views/test_application_instance.py
tests/unit/lms/views/test_reports.py

Depends on this DB migration: https://github.com/hypothesis/lms/pull/1730/
1. Pre-existing application instances (either created before the DB migration is run and before this branch is deployed; _or_ created after the DB migration and deploying this branch but before the `"section_groups"` feature flag is enabled) should **not** get the sections feature.
2. Pre-existing application instances that have a developer key should continue to get the Canvas Files feature but **not** get the sections feature.
These pre-existing instances shouldn't request the sections API scopes, so they should keep working with a scoped dev key that only has the Files scopes.
If the dev key lacks even the Files scopes then these instances will show an error page when you try to create or launch a Canvas Files …

Enable and disable sections in various circumstances

---

lms/resources/_js_config.py
lms/resources/lti_launch.py
lms/validation/_api.py
lms/views/api/canvas/sync.py
lms/views/api/lti.py
tests/unit/lms/resources/_js_config_test.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/validation/_api_test.py
tests/unit/lms/views/api/canvas/sync_test.py
tests/unit/lms/views/api/lti_test.py

Fixes https://github.com/hypothesis/lms/issues/1694
Depends on https://github.com/hypothesis/lms/pull/1731
This gets SpeedGrader working when sections is enabled: the client shows the section group(s) that the learner being graded belongs to, rather than showing the instructor's groups.
* You'll need frontend sections support to test this:
```terminal
git cherry-pick make-the-frontend-call-the-sync-api
```
* You may also want to turn the `canvas_sections_enabled` setting on and off for all application instances in your DB (which is just a quick and easy way to turn it on/off for the app instance you happen to currently be testing with):
```terminal
tox -qe docker-compose -- exec postgres psql -U postgres -c 'update application_instances set canvas_sections_enabled = true;'
```
```terminal …
```

Add sections support to SpeedGrader launches

---

lms/app.py
lms/extensions/feature_flags/__init__.py
lms/extensions/feature_flags/_feature_flags.py
lms/extensions/feature_flags/_helpers.py
lms/extensions/feature_flags/_providers.py
lms/extensions/feature_flags/_static/feature-flags.css
lms/extensions/feature_flags/_templates/cookie_form.html.jinja2
lms/extensions/feature_flags/views/cookie_form.py
tests/unit/lms/extensions/feature_flags/__init___test.py
tests/unit/lms/extensions/feature_flags/_feature_flags_test.py
tests/unit/lms/extensions/feature_flags/_helpers_test.py

* Re-enables the cookie feature flag provider
* Adds a `as_tristate` function which is like the pyramid `asbool`, but also returns `None` for various null-like inputs
* Uses this in the cookies to allow "default" type behavior using it
* Updates the web interface to have a table (ugly but clear and functional) which allows you to change the value and also shows you the resulting state with other providers in the mix
Some refactors as well:
* Make use of the `as_tristate` in the main providers file
* Simplified the algorithm for applying all the providers to make it:
* Much simpler
* Fail fast if we get a value
Although this is enabled, **it doesn't work locally** as we have to enable secure cookies to make it work in an iframe. You can see the page working an updating locally by:
* …

Make LMS feature flag cookie settings tri-state

---

lms/extensions/feature_flags/_templates/cookie_form.html.jinja2
lms/extensions/feature_flags/views/cookie_form.py

* Also renaming variable
I think this might be a good time to retest as well (as I had accidentally left the SameSite setting unset in the previous commit).
From what I can see this is broken locally with the exception of Firefox when running under 127.0.0.1 only (not 0.0.0.0).

Fixing the column name for feature flags UI

---

lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
lms/static/scripts/frontend_apps/components/Spinner.js
lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
lms/static/scripts/frontend_apps/components/test/Spinner-test.js
lms/static/scripts/test-util/wait.js
lms/static/styles/components/_BasicLtiLaunchApp.scss

- Don’t show spinner if there is an error
- Don’t show spinner when /sync is pending
- Render the <iframe> no matter what, but hidden if content URL is null or there is an error
- Remove waitForElementToBeRemoved as its no longer needed
- Various test adjustments for the above
- Fix several false negative tests
- Add `hide` prop to Spinner for easier negative testing
----
One shortcoming is it will override an error if another comes in. In order to prevent that, it will need some rethinking about `errorState`, but I think this is a minor and in most cases, the same error will be produced (auth error).  
fixes https://github.com/hypothesis/lms/issues/1748

BasicLtiLaunchApp UI improvments

---

lms/views/helpers/_via.py
tests/unit/lms/views/helpers/_via_test.py

Set the `via.external_link_mode` query param in generated Via URLs to
ensure that non-fragment links in web pages open a new tab. This
prevents Via from navigating to a new page that then loads Hypothesis in
the "normal" mode rather than logged in an account/group that
corresponds to the LMS app.
See also https://github.com/hypothesis/via/pull/235.
Part of https://github.com/hypothesis/lms/issues/451.

Configure Via to open external links in a new tab

---

conf/development.ini
conf/production.ini
conf/supervisord.conf
gunicorn.conf.py
tox.ini

I've been having annoying issues with `make dev` and `make web` for a
while now:
1. Auto-reloading the web process on file changes doesn't seem to work
reliably. While it often does work, changing files often seems to get
the web process "stuck" and no longer working, requiring a manual
Ctrl+c and restart
2. Stopping doesn't work well. When I hit Ctrl+c to stop `make dev` or
`make web` it continues to print lines of logging to the terminal
after my shell prompt has been rendered, messing up the command line.
This also seems to break fish shell's interactive command line
features (auto completion etc)
This used to work reliably.
I think the problems started happening when we switching from gunicorn
auto-reloading to pserve auto-reloading in
https://github.com/hypothesis/lms/pull/1219. …

Fix dev server stopping and reloading

---

lms/static/styles/_variables.scss
lms/static/styles/components/_FileList.scss
lms/static/styles/components/_Table.scss

Found via sass-unused [1]. I didn't remove _all_ unused variables
because some of them are elements of our standard font stack which just
happen not to be used in the LMS repo at present. We'll likely move
those to a shared package in future.
[1] https://github.com/robertknight/sass-unused

Remove unused SCSS vars

---

.pylintrc
lms/assets.py
lms/config/settings.py
lms/models/application_instance.py
lms/models/grading_info.py
lms/models/group_info.py
lms/models/lti_launches.py
lms/models/oauth2_token.py
lms/resources/default.py
lms/services/canvas_api.py
lms/services/group_info.py
lms/services/launch_verifier.py
lms/services/lti_h.py
lms/services/oauth1.py
lms/validation/_base.py
lms/validation/_lti_launch_params.py
lms/views/helpers/_via.py

This warning frequently triggers when we don't want it to / when we can't do anything about it: SQLAlchemy model classes, Pyramid services, inline Meta classes, etc.

Disable PyLint's "too few public methods" warning

---

tests/unit/lms/services/application_instance_getter_test.py

1. Make an `@parametrize` easier to read by having it use a params dict instead of long tuples, and by having it have default values for the items in the params dict so that each parametrized case only needs to contain the values the differ from the defaults. This is going to help with future changes to this test which are going to need to add more parameters and more cases: it'll now be possible to add these without making readability even worse.
2. Add a module level `enable_section_groups_feature_flag()` helper function and `section_groups_feature_flag_enabled` fixture. These just make it easier for tests that need to turn the flag on and off. In the future we're going to have to add more such tests to this module.

Refactor a parametrize and a feature flag fixture

---

yarn.lock

Run `yarn update` to update transitive JS dependencies to current
versions. This resolves several vulnerability warnings that are showing
up in GitHub.

Update JS dependencies

---

lms/resources/lti_launch.py
tests/unit/lms/resources/lti_launch_test.py

This also made some changes to make testing easier:
* Made the canvas_sections_supported public
* Also stopped it being a property (to make it easier to mock)
Rewrote the canvas_sections_enabled tests to be canvas_sections_supported
tests.
* Run `make sql`
* Run `delete * from course`
* Goto: https://hypothesis.instructure.com/courses/125/assignments/873 (sections enabled course)
* You should see sections
* Run `select * from course;`
* You should see `{"canvas": {"sections_enabled": true}`
* Run `update course set settings='{"canvas": {"sections_enabled": false}}';`
* Refresh the page
* You should see a single course group
* Goto: https://hypothesis.instructure.com/courses/124/assignments/885 (sections disabled course)
* You should see a single course group
* Run `select * from course;` …

Read the sections enabled from course, not AI getter

---

lms/migrations/versions/db3779df3f44_back_fill_course_and_course_groups_exported_from_h_tables.py

Add a DB migration to backfill the `course` and `course_groups_exported_from_h` tables.

Backfill the course and course_groups_exported_from_h tables

---

lms/static/scripts/frontend_apps/components/Dialog.js
lms/static/scripts/frontend_apps/components/ErrorDisplay.js
lms/static/scripts/frontend_apps/components/test/Dialog-test.js
lms/static/styles/components/_BasicLtiLaunchApp.scss
lms/static/styles/components/_Dialog.scss
lms/static/styles/components/_ErrorDisplay.scss
lms/static/styles/components/_FileList.scss
lms/static/styles/components/_LMSFilePicker.scss
lms/static/styles/components/_URLPicker.scss
lms/static/styles/frontend_apps.scss
lms/templates/api/canvas/oauth2_redirect_error.html.jinja2
lms/templates/base.html.jinja2

- Increase max-width of dialogs to 700px
- Allow dialogs to expand to 90% of the height to take advantage of extra space
- Allow extremely long content in dialogs to scroll, but not hide any bottom buttons out of the view
- Coverage & delete some CSS settings among various dialogs used
- Fix bug where non-json error details text was not formatted pretty in <ErrorDisplay>
- Fix bug that set “undefined” class in <Dialog> when not passing a `contentClass` prop.
- Add new DisplayError classes to oauth_redirect_error template
--------
Cherry picked changes in this PR against master, rather than demo branch. this is the PR to be merged, rather than the following: https://github.com/hypothesis/lms/pull/1780
To demo, use `eng+canvasteacher@hypothes.is` account. The test assignments, with various …

Dialog css fixes

---

lms/models/group_info.py
tests/unit/lms/models/group_info_test.py
tests/unit/lms/services/group_info_test.py

Not sure how we got here, but groups infos in the wild don't have the defaults set. In general I think we must always assume this value is blank.
The result of this is reading a GroupInfo with "info = None" will cause a crash. ~This isn't an issue with using JSON fields, it's an issue of not using them correctly. We must never assume a key is present, or have a much better strategy for trying to setup the defaults.~ Seems we should have set this, although I still feel this is a risky way to go.
~I'm not sure if the DB migration was supposed to catch this. Working out how we got here can probably wait.~ It was, so how this has happened is a mystery. A real possibility is something we aren't thinking of is resulting in this getting blanked.

GroupInfo info defaults should be applied on read, not create

---

lms/services/canvas_api.py
tests/unit/lms/services/canvas_api_test.py

We filter exact duplicates and fail on sections with different names.
This is to attempt to help with the _suspected_ cause of some failures with the Bulk API which it looks like could only be caused by sending two identical ids. 
This is most likely because Canvas sends us back the same data twice. Another, astronomically less likely, possibility is that we have a SHA-1 clash.

Add a method which filters and checks for duplicate sections

---

lms/static/scripts/frontend_apps/components/ErrorDisplay.js
lms/static/scripts/frontend_apps/components/test/ErrorDisplay-test.js

Resolve a possible confusion when expanding the "Error Details" section
of error dialogs in short viewports by scrolling the contents into view
after the `<details>` is toggled open.
On browsers that support it, the view will be scrolled smoothly, on others (eg. Safari) it will scroll instantly.
Fixes #1824
----
For example, given this error dialog:
Clicking on the "Error details" text will expand the contents and scroll like so:

Scroll error details into view when `<details>` is opened

---

docker-compose.yml

This enables health-checking of the Postgres service to see whether Postgres is up or not by using the `docker inspect` command. For example:
docker inspect -f {{.State.Health.Status}} lms_postgres_1
Here's a Python script for checking whether a given service is running
and healthy:
#!/usr/bin/env python
"""
Exit with 0 if all the given services are healthy, 1 otherwise.
Usage:
bin/check-services lms_postgres_1 ...
"""
from sys import argv, exit
from subprocess import check_output, DEVNULL
def check_service(service):
try:
status = (
check_output(
[
"docker",
"inspect",
"-f",
"{{.State.Health.Status}}",
service,
],
stderr=DEVNULL,
)
.decode()
.strip()
)
except:
pass
else:
if status == "healthy":
return True
return False
if __name__ == "__main__":
for service in argv[1:]:
if not …

Add Docker Compose healthcheck config

---

conf/development.ini

And also better represent what happens in production.
This is after changes were made in VIa 3 which made it both possible to run through NGINX and to drop special CORS support.

Change LMS to run Via 3 through NGINX to avoid CORS issues

---

Makefile
lms/scripts/__init__.py
lms/scripts/initdb.py
setup.py

Depends on #1853 in order to work properly.
Fixes #1708
To test it:
1. Delete your DB:
$ make services args='down'
$ make services
2. Verify that your DB hasn't been initialized:
$ docker exec -it lms_postgres_1 psql -U postgres -c "\d"
Did not find any relations.
3. Run the script:
$ tox -qqe dev --run-command 'initdb conf/development.ini'
4. Verify that now your DB has been initialized:
$ docker exec -it lms_postgres_1 psql -U postgres -c "\d"
List of relations
Schema |               Name                |   Type   |  Owner
--------+-----------------------------------+----------+----------
public | application_instances             | table    | postgres
public | application_instances_id_seq      | sequence | postgres
public | course                            | table    | postgres
... …

Add a convenient `make db` command

---

.coveragerc
conf/development.ini
lms/pshell.py

See: https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/commandline.html#extending-the-shell
Add some custom convenience variables to `make shell`. This means that
when you run `make shell` you'll see this:
$ make shell
Python 3.6.9 (default, May 26 2020, 13:51:02)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.
Environment:
app          The WSGI application.
db           Active DB session.
m            The lms.models package.
models       The lms.models package.
registry     Active Pyramid registry.
request      Active request object.
root         Root of the default resource tree.
root_factory Default root factory used to create `root`.
session      Active DB session.
tm           Active …

Add some convenience variables to `make shell`

---

lms/pshell.py
requirements-dev.in
tests/factories/__init__.py
tests/unit/conftest.py

Make the test factories available in `make shell`'s environment so you do things like this:
```python
$ make shell
Python 3.6.9 (default, May 26 2020, 13:51:02)
...
In [1]: f.LTIUser()                                                                                                                                                                                     
Out[1]: LTIUser(user_id='8955e3587d3831542127e503dbdcafac8125e98d', oauth_consumer_key='Hypothesise8ef1f48811f42990fadfa0147696bbe', roles='Learner', tool_consumer_instance_guid='f34f2010df2144cc496bf8ff87ecdd5d6a8f5e25', display_name='Karen Paul', email='')
```

Add test factories to `make shell`

---

lms/static/styles/components/_ErrorDisplay.scss

Very long single words / tokens can break out of the details area and cause
horizontal scrolling and hidden content.
This is kind of tricky. You need one of the exceptions that has a massive stack trace in it to see the difference. You could also get any old error and bodge the text to see it.
If I find an easy way I'll add it.
Before:
After:

Try and prevent error details from escaping from the box

---

lms/static/scripts/frontend_apps/common/dom.js
lms/static/scripts/frontend_apps/common/use-element-should-close.js
lms/static/scripts/frontend_apps/components/Dialog.js
lms/static/scripts/frontend_apps/components/LMSGrader.js
lms/static/scripts/frontend_apps/components/Table.js
lms/static/scripts/frontend_apps/components/ValidationMessage.js
lms/static/scripts/frontend_apps/utils/api.js
lms/static/scripts/frontend_apps/utils/grader-service.js
lms/static/scripts/frontend_apps/utils/validation.js
lms/static/scripts/postmessage_json_rpc/client/client.js
lms/static/scripts/postmessage_json_rpc/client/random.js
lms/static/scripts/tsconfig.json
package.json
yarn.lock

Similar to what we did in the client recently, this adds a `yarn typecheck` command which uses the TypeScript compiler to check for JSDoc errors and semantic errors in JavaScript code. About half of the errors that were reported were basic JSDoc mistakes, and I have also fixed those here in separate individual commits.
There are still many (~70) errors left to resolve, so for the moment this command is not run during CI and instead developers must run it manually. The idea is that we will gradually work our way through those in separate PRs.

Add `yarn typecheck` command, but don't run it during CI yet, and fix basic JSDoc errors

---

tests/unit/lms/services/canvas_api_test.py
tox.ini

This PR takes a matcher which was written here and sub-sequently moved out to `h-matchers` and replaces it with the new version now in `h-matchers`. 
* The tests haven't been changed at all, the request matcher is just gone
* There was some tomfoolery with the imports I fixed as well

Remove prototype matcher for h-matchers version

---

lms/models/__init__.py
lms/models/_hashed_id.py
lms/models/h_group.py
lms/models/h_user.py
lms/resources/lti_launch.py
lms/views/api/canvas/sync.py
tests/factories/h_group.py
tests/unit/lms/models/_hashed_id_test.py
tests/unit/lms/models/h_group_test.py
tests/unit/lms/models/h_user_test.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/views/api/canvas/sync_test.py

Partially achieves: https://github.com/hypothesis/lms/issues/1753
* We now have a re-usable "hashed_id" function which the models use to create ids
* This replaces all the places which performed hashed based ids before
* All construction logic has been centralised into the models
* Services are responsible for getting the right values, and the model is responsible for combining them
* This simplifies test and removes lots of "magic" hex values which opaquely line up with input strings
* Went to town as a result of this on the Canvas sync tests to try and make them easier to understand
* The changes have been broken up into four commits
* The commits do not work individually, but hopefully help when reading it
* The biggest changes are to the sync tests (which was the motivator for this)

Centralise model object creation and refactor Canvas sync tests

---

lms/models/h_group.py
lms/views/api/canvas/sync.py
tests/unit/lms/models/h_group_test.py
tests/unit/lms/views/api/canvas/sync_test.py

By unifying the flow of speedgrader with the other ways of syncing we can now:
* Split each section up into discrete parts
* Remove an inner function (as it's only used once)
* Remove the path which allowed `HGroups` to be created without a name
As a result the main sync function is now:
```python
def sync(self):
groups = self._to_groups(self._get_sections())
self._sync_to_h(groups)
authority = self._request.registry.settings["h_authority"]
return [group.groupid(authority) for group in groups]
```
This is for: https://github.com/hypothesis/lms/issues/1753

Simpler clearer Canvas Sync API

---

lms/static/scripts/frontend_apps/utils/google-api-client.js
lms/static/scripts/frontend_apps/utils/test/google-api-client-test.js
package.json
yarn.lock

Add the `@types/gapi` package recommended in the Google API loader's
README [1]. This fixes the errors reported in this file when running `yarn typecheck`.
[1] https://github.com/google/google-api-javascript-client#features

Fix Google API loader typecheck errors

---

lms/static/scripts/frontend_apps/components/CanvasOAuth2RedirectErrorApp.js
lms/static/scripts/frontend_apps/config.js
lms/static/scripts/frontend_apps/index.js
lms/static/scripts/frontend_apps/test/config-test.js
lms/static/scripts/postmessage_json_rpc/server/index.js
lms/static/scripts/postmessage_json_rpc/server/server.js
lms/static/scripts/postmessage_json_rpc/server/test/index-test.js
lms/static/scripts/postmessage_json_rpc/server/test/server-test.js

Originally the LMS frontend and postmessage RPC server were entirely
separate and read configuration from different sources. For various
reasons the frontend app and RPC server were unified into a single
application that read the same configuration object, however the
configuration parsing was duplicated multiple times in the frontend.
This commit centralizes the knowledge of how to parse frontend
configuration from the page in a `readConfig` function in `config.js`.
Rather than having this function be called in multiple places, the
frontend's `index.js` calls this function once and then passes the
necessary configuration through to `startRpcServer` and the `Server`
constructor.
As part of this cleanup, JSDoc definitions of the structure of the
config object expected by the frontend have …

Centralize frontend configuration parsing and documentation

---

lms/static/scripts/bootstrap.js
lms/static/scripts/frontend_apps/components/Spinner.js
lms/static/scripts/frontend_apps/components/StudentSelector.js
lms/static/scripts/frontend_apps/components/SubmitGradeForm.js
lms/static/scripts/frontend_apps/components/SvgIcon.js
lms/static/scripts/frontend_apps/components/test/SvgIcon-test.js
lms/static/scripts/frontend_apps/icons.js
lms/static/scripts/frontend_apps/index.js
lms/static/styles/components/_SvgIcon.scss

Update the `SvgIcon` component to match the latest version from
`src/shared/components` in the `client` repository, with the casing of
file names and class names adapted to the LMS frontend's conventions [2].
The main change is to the way that icons are registered [1]. Icons are
now registered in `frontend_apps/index.js` by a call to `registerIcons`
and then referenced via a `name` prop in components.
In future we should look to publish components like this as a package and then consume
it on our various repos. This PR will make that easier by making the APIs consistent.
[1] The lms and client repositories evolved different means of enabling
icons to be used by `SvgIcon` without hardcoding the list of icons
within the component itself. The client's method has several advantages:
- It …

Update `SvgIcon` component to latest version from client

---

lms/static/scripts/frontend_apps/components/FilePickerApp.js

This required adding explicit hints in a few places where types could not be inferred automatically.
One non-trivial change here is to change the method used to get a reference to a form's submit button from using `formElement.querySelector(...)` to just adding a ref to the submit button directly.

Fix type checking errors in FilePickerApp

---

Makefile
Procfile

These should have been removed by https://github.com/hypothesis/lms/pull/1897/ but weren't

Remove some remnants of Honcho

---

lms/static/scripts/frontend_apps/components/Dialog.js
lms/static/scripts/frontend_apps/components/URLPicker.js

This PR converts the prop documentation for `Dialog` from prop-types to JSDoc and makes some improvements to it in the process. In doing this I uncovered a mistake in `URLPicker` where the wrong function was used to create refs (`createRef` instead of `useRef`). This mistake went unnoticed because of the way the refs were used, but in general is not safe because `createRef` creates a new object every time that it is called, whereas `useRef` returns the same object on each render.

Convert `Dialog` props from prop-types to JSDoc and fix ref usage in `URLPicker`

---

lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/index.js

- Report a useful error in the console if the `#app` container for the
LMS frontend is missing. This would indicate an error in the template
rendered by the backend. Without this TS reports, correctly, that
the root element passed to `render` might be `null`.
- Convert FilePickerApp props to JSDoc and indicate that props provided
for use in tests are optional

Fix a couple of typecheck errors in the LMS entry point

---

lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
lms/static/scripts/frontend_apps/components/LMSGrader.js

Improve the documentation and also use a shared definition of what a
"student" object looks like.
There is an open "TODO" in the code about changing a `username` property
to `userid` but I didn't make this change as the client's code still
references the `username` property [1] in one place without also
checking for `userid`.
[1] https://github.com/hypothesis/client/blob/ef82cf66d1a9616143d0bdb30c5a3da0cdd2ed4e/src/sidebar/store/modules/selection.js#L162

Convert `LMSGrader` props from prop-types to JSDoc

---

lms/static/scripts/frontend_apps/components/FileList.js
lms/static/scripts/frontend_apps/components/LMSFilePicker.js
lms/static/scripts/frontend_apps/components/Table.js

Migrate the documentation for `Table` and `FileList` from prop-types to
JSDoc and add more specific types.
In the process two minor issues were found:
- `Table` assumed that items had a `name` property but `FileList` passed in
items with no such property. Due to the way `name` was used (as a `key`
value) this fortunately did not cause any visible problems.
- If the user pressed 'Enter' when the table was focused but no items
were selected, that could cause an error in the calling component due
to a callback (`onUseItem`) being called with `null`

Convert prop documentation from prop-types to JSDoc for `Table` and `FileList`

---

lms/static/scripts/frontend_apps/components/StudentSelector.js

As part of this clarify details such as how the selected student is
represented in the `onSelectStudent` callback.

Convert prop docs for StudentSelector from prop-types to JSDoc

---

lms/static/scripts/frontend_apps/common/dom.js
lms/static/scripts/frontend_apps/common/use-element-should-close.js
lms/static/scripts/frontend_apps/components/SubmitGradeForm.js
lms/static/scripts/postmessage_json_rpc/client/client.js
lms/static/scripts/postmessage_json_rpc/server/index.js

This PR fixes the remaining errors when running `yarn typecheck`, except
for several (4) related to a mixup of numbers and strings when formatting
grades that will be addressed separately.
One of the errors in `postmessage_json_rpc/server/index.js` indicates a
design issue that stems from an earlier version of the code where the
RPC server and LMS frontend were separate JS applications. As this PR is
focused on fixing typecheck errors I have just made a note of the issue and
added a check in case `getSidebarWindow` is called when the server has not
been started.

Fix most remaining typecheck errors

---

lms/static/scripts/frontend_apps/components/SubmitGradeForm.js
lms/static/scripts/frontend_apps/utils/test/validation-test.js
lms/static/scripts/frontend_apps/utils/validation.js

This is the final PR to make `yarn typecheck` run without producing any errors. Once it lands, we can make that command part of the CI process.
- The `scaleGrade` function in `validation.js` was documented to return
a number but could actually return a number or a string. Since it
formats a number for display, change it to always return a string.
I think there is room to simplify these functions but for now I just
fixed the inconsistency in the return values and updated the tests.
- Remove unnecessary `async`-ness in tests
Note that there are some unrelated typecheck errors in `SubmitGradeForm.js` which are fixed in https://github.com/hypothesis/lms/pull/1920.

Fix mixup of strings and numbers when formatting grades

---

Makefile

Now that all the errors have been fixed, make `yarn typecheck` part of
the checks that `make frontend-lint` runs which in turn makes it part of the CI checks.

Add `yarn typecheck` to `make frontend-lint`

---

.github/workflows/continuous-integration.yml
tox.ini

Fixes https://github.com/hypothesis/lms/issues/1874
This gets all the CI checks that we run on Jenkins (or that `make sure` runs) working on GitHub Actions as well: backend and frontend formatting, linting and unit, functional and BDD tests.
See the checks running on GitHub Actions here: https://github.com/hypothesis/lms/actions?query=branch%3Agha
This runs two GitHub Actions jobs named backend and frontend in parallel. Within the backend job, after installing everything, the backend formatting, linting, and unit, functional and BDD tests all run in parallel:
* In parallel:
* backend:
* In serial:
- Start Postgres Docker container
- Install Python 3.6.9
- Update pip
- Install tox
- Checkout the lms git repo
- Create the test databases
- Install the frontend dependencies
- Build the …

Copy all CI checks to GitHub Actions

---

lms/migrations/versions/5086e8b137b9_add_settings_server_default_and_not_.py
lms/models/application_instance.py
lms/models/course.py

...and also make `ApplicationSettings.settings` not-nullable like `Course.settings` already is.
Make `ApplicationInstance.settings` default to an empty dict rather than `NULL` at the Postgres level, and make it not nullable at the Postgres level.
In practice there are no NULLs in the QA or prod DBs. Let's enforce that at the DB level so that we don't need to worry about enforcing it (or potentially failing to enforce it) at the Python level (including both Python app code and future migration scripts).

Add ApplicationInstance.settings and Course.settings server_defaults

---

lms/migrations/versions/5086e8b137b9_add_settings_server_default_and_not_.py

There are ApplicationInstances on QA and prod with NULL settings. Need to backfill those before making the column not-NULLable.

Fix a migration script

---

lms/models/application_instance.py
lms/models/application_settings.py
lms/models/course.py
lms/services/course.py
tests/factories/course.py
tests/unit/lms/models/application_instance_test.py
tests/unit/lms/models/application_settings_test.py
tests/unit/lms/models/course_test.py
tests/unit/lms/services/application_instance_getter_test.py
tests/unit/lms/services/course_test.py

**Depends on** https://github.com/hypothesis/lms/pull/1907 for the tests to pass.
This means that instead of doing this:
https://github.com/hypothesis/lms/blob/2e7133a6714a06347d1fbc3d080d602e755ec44e/lms/models/application_instance.py#L34-L50
which is repeated in both [`ApplicationInstance`](https://github.com/hypothesis/lms/blob/2e7133a6714a06347d1fbc3d080d602e755ec44e/lms/models/application_instance.py#L34-L50) and [`Course`](https://github.com/hypothesis/lms/blob/2e7133a6714a06347d1fbc3d080d602e755ec44e/lms/models/course.py#L26-L35), both places (and any future ones) can now just do this one-liner:
https://github.com/hypothesis/lms/blob/90d8df42328c7a594a981964dd55f34832684154/lms/models/application_instance.py#L34
* The boilerplate code that's required in each model class to use …

Make ApplicationSettings a SQLAlchemy type

---

tests/factories/course.py

Test factories for SQLAlchemy models should have
`FACTORY_CLASS=SQLAlchemyModelFactory`. This lets Factory Boy know that
it's a SQLAlchemy factory and means that it automatically adds it to the
test DB session when you do `factories.course()`,
`factories.course.create()` or `factories.course.create_batch()`.
If you want to make one _without_ adding it to the DB session (or
without even needing to have a DB session) use `build()` or
`build_batch()`.
See `factories.GradingInfo` for an existing example of this.

Fix the Course test factory

---

tests/functional/api/basic_lti_launch_test.py

"Separator comments" aren't really part of our code style.
You can tell when something's a fixture because it has an
`@pytest.fixture` decorator on it. You can tell when something is a
helper method because it neither has the `@pytest.fixture` decorator nor
has a name beginning with `test_`. You can tell when something is an
assertion method (a special kind of test helper method) because it has a
name beginning with `assert_`.
It's a good idea to group these different kind of methods together but
we don't need separator comments for them, and we never use these kind
of comments anywhere else in our code.
The comments are liable to become misleading when people modify things or
add new things in the wrong places.

Remove some unnecessary comments

---

lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
lms/static/scripts/frontend_apps/components/CanvasOAuth2RedirectErrorApp.js
lms/static/scripts/frontend_apps/components/ErrorDialog.js
lms/static/scripts/frontend_apps/components/ErrorDisplay.js
lms/static/scripts/frontend_apps/components/LMSFilePicker.js
lms/static/scripts/frontend_apps/components/LMSGrader.js
lms/static/scripts/frontend_apps/components/Spinner.js
lms/static/scripts/frontend_apps/components/StudentSelector.js
lms/static/scripts/frontend_apps/components/SubmitGradeForm.js
lms/static/scripts/frontend_apps/components/URLPicker.js
lms/static/scripts/frontend_apps/components/ValidationMessage.js
lms/static/scripts/frontend_apps/components/test/SubmitGradeForm-test.js
lms/static/scripts/frontend_apps/config.js

This surfaced an issue where several properties were missing from the
`StudentInfo` type listed in `frontend_apps/config.js`. These properties are
needed when calling the API to submit a grade update.
It also surfaced an issue where the `SubmitGradeForm` component redundantly took
a nullable `student` prop as well as a `disabled` prop.  Whether to disable the
form can be inferred from whether `student` is null or not (and _should_ be to
avoid a possible inconsistency).

Convert remaining UI component docs to JSDoc

---

tests/factories/requests_.py
tests/unit/lms/services/canvas_api/conftest.py

This tidies up the `Response` factory a little, separating things out into separate methods and making the code/logic "flatter".
The behaviour of the factory hasn't changed.
Demo
----
Non-JSON responses:
```python
>>> response = factories.requests.Response()
>>> response.encoding
'utf-8'
>>> response.status_code
500
>>> response.headers
{}
>>> response.raw is None
True
>>> response.json()
JSONDecodeError
```
Lower-casing headers:
```python
>>> factories.requests.Response(headers={"FOO": "BAR"}).headers
{"foo": "BAR"}
```
Encoding raw bodies:
```python
>>> factories.requests.Response(raw="hi").raw.read()
b'hi'
```
JSON:
```python
>>> factories.requests.Response(json_data={"foo": "bar"}).json()
{'foo': 'bar'}
>>> factories.requests.Response(json_data={"foo": "bar"}).raw.read()
b'{"foo": …
```

Tidy up the requests.Response test factory

---

lms/models/group_info.py
tests/unit/lms/services/group_info_test.py

Part of https://github.com/hypothesis/lms/issues/1839
`GroupInfo.info` is one of three JSON columns that we added to LMS before we realised that using JSON in Postgres is quite a pain due to lack of mutation tracking and lack of defaults and constraints.
The other two are `ApplicationInstance.settings` and `Course.settings`, which we've made safe (ish) and the model code nice enough by introducing a custom SQLAlchemy type `ApplicationSettings` with safe `get()` and `set()` methods and a docstring warning you not to bypass them: https://github.com/hypothesis/lms/pull/1909
`ApplicationSettings` doesn't apply to the `GroupInfo.info` column. `ApplicationSettings` is for maintaining a two-level dict in which each top-level item is a sub-dict and then the sub-dicts contain settings (and the …

Tidy up GroupInfo.info

---

lms/models/application_instance.py
lms/models/course.py
tests/factories/__init__.py
tests/factories/_attributes.py
tests/factories/application_instance.py
tests/functional/api/basic_lti_launch_test.py
tests/functional/conftest.py
tests/unit/lms/models/application_instance_test.py
tests/unit/lms/models/grading_info_test.py
tests/unit/lms/models/group_info_test.py
tests/unit/lms/models/oauth2_token_test.py
tests/unit/lms/services/application_instance_getter_test.py
tests/unit/lms/services/canvas_api_test.py
tests/unit/lms/services/course_test.py
tests/unit/lms/services/group_info_test.py

Extracted from https://github.com/hypothesis/lms/pull/1923/ but with some changes:
* Added `FACTORY_CLASS=SQLAlchemyModelFactory` to the factory so that Factory Boy adds instances to the DB session automatically.
* I've updated all the existing tests to use the new factory
* Also used the `ApplicationInstance` as a sub-factory in the `OAuth2Token` factory, separate PR: https://github.com/hypothesis/lms/pull/1942
* Also used the `ApplicationInstance` as a sub-factory in the `Course` factory, separate PR: https://github.com/hypothesis/lms/pull/1944

Add ApplicationInstance test factory

---

tests/factories/__init__.py
tests/factories/application_instance.py
tests/factories/attributes.py
tests/factories/course.py
tests/factories/grading_info.py
tests/factories/h_user.py
tests/factories/lti_user.py
tests/factories/oauth2_token.py
tests/unit/lms/services/canvas_api_test.py

Extracted from https://github.com/hypothesis/lms/pull/1923/ but with some changes:
* Added `FACTORY_CLASS=SQLAlchemyModelFactory` to the factory so that Factory Boy adds instances to the DB session automatically.
* Added `application_instance=SubFactory(ApplicationInstance)` to the factory so that, when you do `factories.OAuth2Token()`, Factory Boy will also generate an `ApplicationInstance` object (using `factories.ApplicationInstance`) and set it as the new `OAuth2Token`'s application instance.
`OAuth2Token` has a non-nullable foreign key to `ApplicationInstance` so you can't save an `OAuth2Token` to the DB without first creating a matching `ApplicationInstance`, so it's convenient for the factory to do this for you. This simplifies a lot of tests that were having to create …

Add OAuth2Token test factory

---

lms/static/scripts/frontend_apps/api-types.js
lms/static/scripts/frontend_apps/components/FileList.js
lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/utils/api.js
lms/static/scripts/frontend_apps/utils/content-item.js

Add an `api-types.js` file which describes the various objects sent to
or received from the LMS backend by the LMS frontend. Currently this
only has one type, `File` for an object in the LMS file picker.

Add a central location for typedefs for API types

---

lms/static/scripts/frontend_apps/utils/content-item.js
lms/static/scripts/frontend_apps/utils/test/content-item-test.js

**Depends on https://github.com/hypothesis/lms/pull/1957**
Refactor the `contentItemFromUrl` and `contentItemFromFile` functions so
that it is easier to add new types of LMS assignment in future. Also add
missing tests for this module.

Refactor `contentItemFromXYZ` functions and add missing tests

---

bin/logger

Avoid formatting lines containing certain strings as errors if even they
come from stderr. This avoids `make dev` printing a whole bunch of
non-error output with bold red error styling.
Copy the `bin/logger` script from https://github.com/hypothesis/h/pull/6125 with
a minor change to the `NON_ERROR_MARKERS` variable to account for the
slightly different formatting of `INFO` lines from gunicorn. The
"Starting monitor" string was also removed from `NON_ERROR_MARKERS`
because that line isn't output when starting `make dev`.

Suppress error formatting for log lines containing certain strings

---

lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js
lms/static/scripts/frontend_apps/utils/api.js
lms/static/scripts/frontend_apps/utils/test/api-test.js
lms/views/api/error.py
tests/unit/lms/views/api/error_test.py

Some of the error responses use `error_message` rather than just `message`. This inconsistency created an issue where in some cases, error details were passed but ignored on the client because ApiError was only setting its `errorMessage` param to `error_message` rather than `message`.
fixes https://github.com/hypothesis/lms/issues/1741
This PR is related to closing https://github.com/hypothesis/lms/pull/1857

Fix error payload to use `message` rather than `error_message`

---

tests/factories/course.py
tests/unit/lms/services/course_test.py

This does mean that if a test creates a new `Course` and then it wants to call `course.settings.set()` or `get()` before having added it to the DB, the test has to first set `settings={}` itself because the `server_default` only takes effect on saving to the DB. This is the same as how `models.Course.settings` works for production code, though, so I think it might be best for the factory _not_ to hide that fact.
I think maybe a good guide for how clever a factory should be / how many of the model's attributes a factory should autogenerate might be: it should generate the minimum set of attrs necessary to save the object to the DB. And `settings` isn't necessary for that. It's a balance between making factories convenient for tests to use (reducing how much work a test must do itself) …

Remove an unnecessary `settings` attribute

---

tests/factories/course.py
tests/unit/lms/services/course_test.py

* Add `application_instance=SubFactory(ApplicationInstance)` to the `Course` factory so that, when you do `factories.Course()`, Factory Boy will also generate an `ApplicationInstance` object (using `factories.ApplicationInstance`) and set it as the new `Course`'s application instance.
`Course` has a non-nullable foreign key to `ApplicationInstance` so you can't save a `Course` to the DB without first creating a matching `ApplicationInstance`, so it's convenient for the factory to do this for you.
If you _don't_ want an `ApplicationInstance` to be generated for you, you can override it:
```python
factories.Course(application_instance=None)
```
If you already have an `ApplicationInstance` and want that to be used, you can pass it in:
```python …
```

Add Course.application_instance sub-factory

---

lms/static/styles/components/_ErrorDisplay.scss

By default the `Dialog` component's width is set based on the preferred
width of the dialog content, up to a default maximum of min(700px,
90vw). In dialogs that have an "Error details" section rendered by an
`ErrorDisplay`, this can cause the dialog's width to change when the
error details are expanded and collapsed. When the `ErrorDisplay` is
collapsed the preferred width depends only on the `<summary>`. When
open, it also depends upon the content, which by default is the laid-out
width of the error message before any line breaking happens.
This commit resolves the issue by setting `width` to override the
intrinsic width of the error message which is used when calculating the
width of the dialog but then also `min-width` to make the error message
fill the final width allocated to the …

Prevent dialog size from changing when error details opened

---

lms/static/scripts/frontend_apps/components/ErrorDisplay.js
lms/static/scripts/frontend_apps/components/LMSFilePicker.js
lms/static/scripts/frontend_apps/components/test/ErrorDisplay-test.js
lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js

Add trailing periods to error messages if they do not already end with
punctuation.
The error messages to come from a variety of sources so it is difficult to
ensure that they are always consistent about whether or not they end
with punctuation. Therefore we treat this as a formatting concern and
add it if necessary when rendering the error.
Fixes #1891

Render error messages as sentences

---

lms/static/scripts/.eslintrc

Remove the `ecmaVersion` setting which overrode settings from the
`eslint-config-hypothesis` package and caused an error if trying to use
ES language features from ES 2019+

Remove an obsolete ESLint config setting

---

Jenkinsfile

These are now being run on GitHub Actions so there's no point in running them on Jenkins as well.

Remove code formatting and linting from Jenkins

---

lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
lms/static/scripts/frontend_apps/components/Button.js
lms/static/scripts/frontend_apps/components/Dialog.js
lms/static/scripts/frontend_apps/components/LMSFilePicker.js

- Move the `aria-*` attributes down from the dialog root element to its content wrapper. This seems to prevent Voice Over from reading out “x items in group” after reading the header.
- Add `aria-describedby`. This facilitates reading of the actual content by the screen readers
- Pass a button ref as `initialFocus` for dialogs that have an authorize button in BasicLtiLaunchApp. This allows the screen reader to state the call to action after reading the content.
- These concepts are from https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/alertdialog.html
fixes https://github.com/hypothesis/lms/issues/1782

Improve screen readers on dialog errors

---

conf/development.ini
lms/views/helpers/_via.py
tests/unit/lms/views/helpers/_via_test.py

This also includes the shortcut of going directly to the pywb end-point.
The flag is `use_via_rewriter` which can be enabled using cookies at: http://0.0.0.0:8001/flags
This should enable:
* A short cut directly to the `pywb` end-point for known HTML documents
* Adding the `via.rewrite` param for unknown types
This doesn't work right now, as the rewrite isn't implemented, but the routing should work
Of course... you can't use the cookie flag due to the secure / not-secure cookie issue. So I think the only way to test is to set the environment variable: FEATURE_FLAG_USE_VIA_REWRITER
Then start everything and visit: https://hypothesis.instructure.com/courses/125/assignments/873
This should be broken, but when you inspect the location it should have `/html/v` in it.

Add a feature flag for enabling Via internal `pywb` rewriter

---

lms/static/scripts/frontend_apps/components/Dialog.js

b04e102270ddd01eeac2b25d826a143d0f03e7c1 added a div with an ID that
wrapped the contents of a dialog, that was then referenced by `aria-describedby`
in order to cause screen readers to announce the text of the dialog when opened.
Unfortunately wrapping the children broke the layout of the Canvas file picker
when there were many files in the table - see #2003. In addition,
labeling the entire contents of the dialog as the description is not
always appropriate. Typically only static text (eg. the first paragraph)
should be labeled this way.
This commit reverts the addition of `aria-describedby` to fix the
problem with the Canvas file picker while we look for a better solution.
For more background, the intended use of aria-describedby in the context of dialogs is described …

Remove `aria-describedby` wrapper around dialog children

---

lms/static/scripts/frontend_apps/components/Dialog.js
lms/static/scripts/frontend_apps/components/test/Dialog-test.js

This is a follow-up to https://github.com/hypothesis/lms/pull/2018 which
re-introduces accessible descriptions for dialogs using a different
approach. Instead of wrapping all of the dialog contents in an element
which is marked as the description, a layout effect instead picks out
the first `<p>` element, if any, and marks it as the description.
Compared to the previous approach this has some benefits:
- It only identifies static text as a description, not non-descriptive
elements like tables or images
- It doesn't wrap the children, which avoids the issue that was fixed
in #2018
There is also a downside in that it won't update if the dialog's content
changes after it is initially displayed. I believe this is an acceptible
limitation.
There are other approaches we could consider such as …

Re-introduce accessible descriptions for dialogs

---

lms/services/exceptions.py
tests/unit/lms/services/exceptions_test.py

Don't include exceptions from the `requests` library in the `"details"` field of `CanvasAPIError`'s.

Don't include requests exceptions in CanvasAPIErrors

---

lms/static/scripts/frontend_apps/components/Dialog.js
lms/static/scripts/frontend_apps/components/test/Dialog-test.js

Ignore the `initialFocus` prop passed to `Dialog` and focus the root
element of the dialog if the `initialFocus` element is not rendered or
disabled at the point when the focusing logic runs.
Such a scenario may indicate a logic error in the parent of `Dialog` but
if that happens it is better to focus the dialog than cause an error, which
will most likely leave focus on whatever element launched the dialog.
This change is a follow-up to https://github.com/hypothesis/lms/pull/1951.

Ignore `initialFocus` if element is `null` or disabled

---

lms/services/exceptions.py
tests/unit/lms/services/exceptions_test.py

When a Canvas API refresh token expires (or the access token gets deleted from Canvas) Canvas sends us a "refresh_token not found" error response. When this happens just ask the user to re-authorize, don't show them an error dialog that makes it look like something went wrong.

Don't show error dialogs when refresh tokens expire

---

lms/static/scripts/bootstrap.js
lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
lms/static/scripts/frontend_apps/components/test/LMSGrader-test.js
lms/static/scripts/postmessage_json_rpc/test/client-test.js

If an uncaught exception is thrown or promise rejected in-between tests,
ensure the test suite fails. This applies a workaround for an issue in
karma-mocha which was earlier applied for the client in
https://github.com/hypothesis/client/pull/2421.
This caught several problems in the existing tests which are also fixed
in this commit:
- `LSMGrader` did not mock the complex `SubmitGradeForm` component as
we would normally do, and also did not do all the setup required for
testing `SubmitGradeForm`. As a result, the tests ended up attempting
real API calls which triggered warnings and produced exceptions which
went uncaught. Resolve the issue by using `mockImportedComponents` to
mock all imported components
- One of the tests for `postmessage_json_rpc/client` did not mock a response
from the …

Fail test if an async error happens in-between tests

---

lms/static/scripts/frontend_apps/components/Dialog.js
lms/static/scripts/frontend_apps/components/FileList.js
package.json
yarn.lock

This fixes an issue with handling of optional properties (see [1]) which required
a couple of code changes.
- Mark `onSelectFile` and `onUseFile` as required props in `FileList`
- Update a type cast
[1] https://github.com/hypothesis/client/pull/2465.

Upgrade to TypeScript v4.0

---

lms/views/api/error.py
tests/unit/lms/views/api/error_test.py

No functional change, just refactoring.
The diff is bad due to indentation changing but these are the same exact views, just moved into a class.
This removes duplication of the `renderer="json"` in the view configs, and also makes the tests a little nicer.
It's going to make future changes to these exception views nicer too.

Move exception views into a view class

---

lms/resources/__init__.py
lms/resources/oauth2_redirect.py
lms/routes.py
tests/unit/lms/resources/_js_config_test.py
tests/unit/lms/resources/oauth2_redirect_test.py
tests/unit/lms/views/api/canvas/authorize_test.py

There's nothing Canvas-specific about this. It only has the Canvas-specific name because it's only used in Canvas currently, but I'm pretty sure we're gonna end up using this for Blackboard OAuth 2 redirects as well.
The only reason this view exists is because the `"canvas_oauth_callback"` and `"canvas_api.authorize"` routes that use it (the two routes for the authorization popup window) need `context.js_config` to be set (because they use the Preact app for the error dialog that's shown if we receive a bad redirect from Canvas). They can't use the default resource because it doesn't have `context.js_config`. And `context.js_config` can't be added to the default resource because that resource is used by a bunch of views that don't and can't have `context.js_config`.

Rename CanvasOAuth2RedirectResource to OAuth2RedirectResource

---

tests/unit/lms/config/__init___test.py

Remove unneeded unicode_literals imports

---

lms/resources/default.py
lms/resources/oauth2_redirect.py
lms/views/api/canvas/authorize.py
lms/views/api/canvas/files.py
lms/views/api/canvas/sync.py
lms/views/api/lti.py
tests/unit/lms/resources/default_test.py

Merge the separate `"canvas_api"`, `"lti_outcomes"`, and `"sync_api"` permissions into a single `"api"` permission.
These permissions are all given to LTI users anyway so it doesn't make any difference, and there's really no need to give certain users access to only certain APIs: just giving LTI users access to the whole API is fine.
We're soon going to be adding Blackboard API endpoints that will need to be protected by permissions and we don't want to have to add another separare `"blackboard_api"` permission. Instead it'll just reuse this new `"api"` permission.

Merge the different API permissions into one

---

tests/unit/lms/services/canvas_api/_authenticated_test.py

This `lms/services/canvas_api/_authenticated.py` unit test fixture just wants to create a mock `TokenStore` object so that it can be passed as an argument to `AuthenticatedClient.__init__()` (this is a little difficult to track down: the mock `token_store` is passed to `AuthenticatedClient.__init__()` in the [`authenticated_client` fixture `tests/unit/lms/services/canvas_api/conftest.py`](https://github.com/hypothesis/lms/blob/fe108203ffe0359645a7ef84387a49893e4a1411/tests/unit/lms/services/canvas_api/conftest.py#L44)).
The test **does not** want to replace the name `"lms.services.canvas_api._token_store.TokenStore"` (in `_token_store.py`'s namespace) with a mock. The use of `patch()`, which replaces names in namespaces, is incorrect and misleading: `create_autospec()` is the right tool …

Fix a bad patch fixture

---

lms/resources/_js_config.py
lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
lms/static/scripts/frontend_apps/components/FileList.js
lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/LMSFilePicker.js
lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js
lms/static/scripts/frontend_apps/config.js
lms/static/scripts/frontend_apps/utils/AuthWindow.js
lms/static/scripts/frontend_apps/utils/api.js
lms/static/scripts/frontend_apps/utils/test/api-test.js
tests/unit/lms/resources/_js_config_test.py

Fixes https://github.com/hypothesis/lms/issues/2061
Instead of a single `authUrl` setting in the JavaScript config, change it to three `authUrl` settings: one for each OAuth 2.0 API endpoint used. Currently this is three endpoints:
1. The sync API
2. The Canvas files list API
3. The Canvas files Via URL API
This config tidy up is intended to make way for adding Blackboard API support in future.
This will break the frontend: it needs to be updated to work with these config changes.
Specific changes:
* Remove the `config.canvas.authUrl` setting from the JavaScript config.
This has now been replaced by multiple per-endpoint `authUrl` settings, in the different API endpoint configs distributed throughout the config object.
* Also remove the `config.authUrl` setting.
This was a duplicate of …

Make the authUrl setting per-endpoint

---

tests/unit/lms/services/canvas_api/_authenticated_test.py
tests/unit/lms/services/canvas_api/_token_store_test.py
tests/unit/lms/services/canvas_api/client_test.py
tests/unit/lms/services/canvas_api/conftest.py
tests/unit/lms/services/canvas_api/factory_test.py

Make it so that the only unit tests that instantiate a `TokenStore` object are the ones in `_token_store_test.py`. All others use a an autospecced mock `TokenStore`.
This is so that `TokenStore` can be moved from `lms.services.canvas_api._token_store.TokenStore` to a top-level service (`lms.services.token_store.TokenStore`) so that it can be shared by `CanvasAPIClient`, the upcoming `BlackboardAPIClient`, and possibly others in future.
When `TokenStore` is a top-level service it no longer makes sense for unit tests to consider it a close collaborator of `CanvasAPIClient` and not mock it.
`TokenStore` has a very simple API: it has only `save(access_token, refresh_token, expires_in)` and `get()` (no arguments) methods so it's very simple to mock and to assert that users like …

Isolate TokenStore in unit tests

---

lms/services/__init__.py
lms/services/canvas_api/_authenticated.py
lms/services/canvas_api/factory.py
lms/services/token_store.py
tests/unit/conftest.py
tests/unit/lms/services/canvas_api/_authenticated_test.py
tests/unit/lms/services/canvas_api/client_test.py
tests/unit/lms/services/canvas_api/conftest.py
tests/unit/lms/services/canvas_api/factory_test.py
tests/unit/lms/services/token_store_test.py

Move `services.canvas_api._token_store.TokenStore` to a top-level service (`services.token_store.TokenStore`) and register it with pyramid_services as the `"token_store"` service.
This is because `TokenStore` isn't actually Canvas-specific: it's just a get-and-set service for `models.OAuth2Token`, which is a generic model for storing OAuth 2 tokens. `TokenStore` is used by `CanvasAPIClient` and will soon be used by the upcoming `BlackboardAPIClient` and possibly others in future.

Make canvas_api._token_store a top-level service

---

lms/services/__init__.py
lms/services/canvas_api/factory.py
lms/services/oauth2_token.py
tests/unit/conftest.py
tests/unit/lms/services/canvas_api/_authenticated_test.py
tests/unit/lms/services/canvas_api/client_test.py
tests/unit/lms/services/canvas_api/conftest.py
tests/unit/lms/services/canvas_api/factory_test.py
tests/unit/lms/services/oauth2_token_test.py

Just to make it clearer what it actually is: it's a service wrapper for `models.OAuth2Token`. Getting "OAuth 2" in there is particularly important

Rename TokenStore to OAuth2TokenService

---

lms/services/canvas_api/_authenticated.py
lms/services/canvas_api/factory.py
tests/unit/lms/services/canvas_api/conftest.py
tests/unit/lms/services/canvas_api/factory_test.py

I think it's a little weird for the name of the `"oauth2_token"` service to change to something completely different (`token_store`) when it gets passed to `AuthenticatedClient`. Makes the code hard to follow / makes it hard to know what `token_store` actually is. So rename `token_store` to `oauth2_token_service`. This is consistent with how references to other services are named, elsewhere in the code (`*_svc` is sometimes used but `*_service` is more common).

Rename AuthenticatedClient._token_store to oauth2_token_service

---

lms/services/__init__.py
lms/services/canvas_api/_authenticated.py
lms/services/exceptions.py
lms/services/oauth2_token.py
tests/unit/lms/services/canvas_api/_authenticated_test.py
tests/unit/lms/services/oauth2_token_test.py

It doesn't make sense to raise a Canvas-specific error from this generic OAuth 2 service. Add a new `NoOAuth2Token` exception and raise that instead.
Catch `NoOAuth2Token` in the (Canvas-specific) `AuthenticatedClient` that calls `OAuth2TokenService` and wrap it in `CanvasAPIAccessTokenError`, so the rest of the Canvas API services and views are unaffected

Don't raise CanvasAPIAccessTokenError from OAuth2TokenService

---

lms/resources/_js_config.py
lms/routes.py
lms/services/canvas_api/factory.py
lms/views/api/canvas/authorize.py
lms/views/api/exceptions.py
tests/unit/lms/resources/_js_config_test.py
tests/unit/lms/services/canvas_api/factory_test.py
tests/unit/lms/views/api/canvas/authorize_test.py

This is to make way for the Blackboard API routes to be added:
* Consistenly use `"canvas_api.*"` for Canvas API route names
* Consistently use `"canvas_api.oauth.*"` for Canvas API authorization route names
* Put the `"authorize"` route before the `"callback"` route because that's the order they get called in

Tidy up some routes

---

tests/.pylintrc
tests/unit/lms/extensions/feature_flags/_helpers_test.py
tests/unit/lms/services/canvas_api/_basic_test.py

As we've already done for argument, function, method and class names. This PyLint rule doesn't fit with our usual naming style in tests

Disable invalid-name warnings in tests

---

lms/resources/_js_config.py
lms/routes.py
lms/views/api/blackboard/authorize.py
lms/views/api/blackboard/files.py
lms/views/api/exceptions.py
tests/unit/lms/resources/_js_config_test.py
tests/unit/lms/views/api/blackboard/authorize_test.py
tests/unit/lms/views/api/blackboard/files_test.py

Depends on:
This adds the JavaScript config stuff for Blackboard Files, and fake versions of all the Blackboard Files API views. Nothing actually communicates with the Blackboard API yet. But the fake views should behave the same as the real ones will from the frontend's point of view, so this should be enough to enable the frontend to be developed.
Changes:
1. When the `"blackboard_files"` feature flag is on and an instructor launches an unconfigured assignment, add the Blackboard file picker config to the JS config. This causes the frontend to show the <kbd>Choose PDF from Blackboard</kbd> button. The JS config specifies an API call to the fake Blackboard list files API. The fake Blackboard authorization URL is also in this config.
2. When a _configured_ Blackboard assignment is …

Add Blackboard API JS config and fake views

---

lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js

**nb. This may conflict with https://github.com/hypothesis/lms/pull/2062, so I suggest that PR is merged first.**
Remove the `FakeFileList` and `FakeButton` component mocks in the `LMSFilePicker` tests. Mocking
these imports is already handled by `mockImportedComponents`.

Remove unnecessary UI component mocks

---

requirements/dev.in
requirements/dev.txt

This seems to be unnecessary and causes problems.
See:
https://github.com/hypothesis/lms/pull/2111
https://github.com/hypothesis/via3/pull/262

Remove `-e .` from requirements

---

lms/services/lti_outcomes.py
tests/unit/lms/services/lti_outcomes_test.py

Requests to an LMS's LTI Outcomes Service endpoint had no timeout
set, so if the LMS instance was unresponsive this could cause the
gunicorn worker to hang for an extended period of time and be
unavailable to process other requests.
This commit applies the same 9-second timeout to LTI Outcomes requests
that are applied to Canvas API requests. See `lms.services.canvas_api._basic`.
Slack discussion of related incident: https://hypothes-is.slack.com/archives/C074BUPEG/p1602494853011300

Set a timeout on requests to LTI Outcomes Service

---

lms/static/scripts/postmessage_json_rpc/test/server-test.js

Don’t assume the port is 9876. If the client tests are running multiple instances, then the port number may not be 9876. This can happen if client tests are running at the same time lms tests are running. If lms starts second, then the port number may be 9877.
---------
I noticed these tests were failing for me and it was a bit hard to track down. I finally realized the port number was off by one, then it occured to me that I also had the client tests running in another instance of MS code. I did a grep in the client repo and it does not look like we are making this assumption there. I think this only was an issue with LMS.

Don’t hardcode karma config port number

---

lms/services/lti_outcomes.py
tests/unit/lms/services/lti_outcomes_test.py

`record_result` was rejecting scores of zero because it was treating them as if they were None. This fixes the response so it won’t ignore a 0 value but will still ignore a None value.
fixes #1345 
-----------
I confirmed that at least with moodle and blackboard, if you enter the grader UI, you can indeed set a value of zero for a student. This lead me to believe on our LMS backend was not handling the score right. I tracked this down to an exception being throw in `_get_body` due to malformed xml because the <resultRecord> was missing.

Allow score 0 to be saved

---

.babelrc
lms/static/scripts/frontend_apps/utils/test/google-picker-client-test.js

We recently established a new minimum set of supported browsers for the
Hypothesis client [1] and updated the JS compilation settings accordingly.
This commit brings the LMS frontend's minimum supported browsers in line
with the client.
The related PR https://github.com/hypothesis/lms/pull/2203 adds a warning banner which will be displayed in browsers that don't support the modern JS syntax to which the LMS frontend is now compiled.
[1] https://github.com/hypothesis/client/pull/2659

Synchronize Babel configuration with the client

---

lms/static/styles/frontend_apps.scss

- Remove imports of mixin modules which are not directly used by the
entry point. Since we're using SASS modules these are now imported
directly from other modules that need them.
- Update the component style import list to match whay uses them (Preact
vs. other sources of HTML)

Cleanup frontend SASS entry point

---

gulpfile.js
lms/assets.ini
lms/static/scripts/browser_check/.babelrc
lms/static/scripts/browser_check/browser-check.js
lms/static/scripts/browser_check/index.js
lms/static/scripts/browser_check/test/browser-check-test.js
lms/static/styles/_variables.scss
lms/static/styles/components/_browser-check-warning.scss
lms/static/styles/frontend_apps.scss
lms/templates/basic_lti_launch/basic_lti_launch.html.jinja2

This PR adds a client-side check for the current browser's compatibility with the LMS app and shows
a warning banner if it is not supported.
The check and banner are included in a new `browser_check` JS bundle which is loaded before the main
frontend app bundle and is compiled to work in older browsers. It performs feature tests to decide
whether to show the banner, similar to the client's boot script. If the checks fail, an advisory banner
with a support link is shown:
When the banner is shown this does not stop the frontend app from
attempting to load. That way we can accept rare false positives in these
checks and still let users attempt to use the LMS application.
Fixes https://github.com/hypothesis/product-backlog/issues/1141 [1]
[1] This fixes the issue *as-stated* but I strongly …

Display a warning banner in old + unsupported browsers

---

lms/static/scripts/browser_check/browser-check.js

Add a browser feature test for [`Element.prepend()` method](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/prepend). This fixes a
failure of the "unsupported browser" banner to show in older,
unsupported versions of Edge (<= 16). This test is also a good match for
our minimum Chrome version (available in v54, our minimum is Chrome
v55).
Part of https://github.com/hypothesis/product-backlog/issues/1141.

Make browser support test work better in Edge Legacy

---

lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
lms/static/styles/components/_BasicLtiLaunchApp.scss

The content `<iframe>`'s size was set using a `height="100%` attribute.
In situations when the grader bar is shown, this caused the iframe to be
the wrong height in Firefox (but not Chrome). Instead of being the
height of the viewport minus the height of the grader, it ended up being
the same height as the viewport. I don't know exactly why Firefox and Chrome
produce different results here or which is right, but sizing the iframe the correct
way fixes the problem.
This PR fixes the issue by using `flex-grow: 1` to make the iframe fill
the remaining space in the `LMSGrader` parent after the grader is
allocated space. This produces the same results in all browsers.
To make this sizing method work in contexts where the `LMSGrader`
is not used, the `BasicLtiLaunchApp__content` container was …

Fix content iframe size in grader in Firefox

---

.babelrc
package.json

Move the browser support list from `.babelrc` to package.json, where it
will be seen by both CSS and JS processing tools. This results in
slightly smaller CSS bundles due to avoiding unnecessary vendor
prefixing.
See https://github.com/hypothesis/client/pull/2698

Move browser support list to `browserslist` key in package.json

---

lms/static/scripts/tsconfig.json

This did not find any additional errors but could catch some in future.
`noImplicitAny` is left off because we still have un-annotated
parameters in the code that would need addressing first.

Enable `strict` option in tsconfig.json

---

lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
lms/static/scripts/frontend_apps/utils/api.js
lms/static/scripts/frontend_apps/utils/test/api-test.js

This PR adds a more specific and helpful error message in LTI launches that fail due to the Canvas file used in the assignment not being accessible, following the proposal in https://github.com/hypothesis/lms/issues/2217#issuecomment-722281453.
When the backend reports that fetching the content URL for an assignment
launch fails due to a Canvas file permission error, indicated by
`"error_code": "canvas_api_permission_error"` in the API response, show
a specific dialog for that error. This dialog explains common causes of
the problem and how to rectify them. It also differs from the generic
error dialog in that clicking "Try again" does not retry authorization,
since we know that is not necessary.
Summary of changes in this PR:
- Add an `errorCode` property to the `ApiError` error class …

Show custom error dialog for Canvas file permission errors

---

lms/services/__init__.py
lms/services/exceptions.py
lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
lms/static/scripts/frontend_apps/utils/api.js
lms/static/scripts/frontend_apps/utils/test/api-test.js
lms/views/api/exceptions.py
tests/unit/lms/services/exceptions_test.py
tests/unit/lms/views/api/exceptions_test.py

Part of https://github.com/hypothesis/lms/issues/2217
Depends on https://github.com/hypothesis/lms/pull/2222
Add a custom error response from our Canvas proxy API for Canvas API permissions errors. This error response is used:
* When a learner launches a Canvas Files assignment and the assignment's file is marked as _Unpublished_ in Canvas
* When a user launches a Canvas Files assignment in a course that was created from another course using Canvas's course copy feature, and the user isn't a member of the original course (so they don't have permission to read the original course's copy of the file)
* There might also be other ways to get a permissions error from the Canvas API?
Of course, adding a custom error response doesn't help any users until the frontend code has been updated to …

Add custom error response for Canvas API permissions errors

---

lms/resources/_js_config.py
lms/routes.py
lms/services/__init__.py
lms/services/canvas_api/client.py
lms/services/exceptions.py
lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
lms/static/scripts/frontend_apps/components/ErrorDisplay.js
lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
lms/views/api/canvas/files.py
lms/views/api/exceptions.py
lms/views/basic_lti_launch.py
tests/unit/lms/resources/_js_config_test.py
tests/unit/lms/services/canvas_api/client_test.py
tests/unit/lms/views/api/canvas/files_test.py
tests/unit/lms/views/basic_lti_launch_test.py

Show instructors an error message when they're launching a Canvas files assignment and the assignment's file ID isn't found in the course:
This happens when:
* The assignment was copied from another course using Canvas's course-copy feature: the new copies of the assignment's still have the file ID from the original course's copy of the file
* The assignment's file has been deleted from Canvas

Show instructors an error when Canvas file ID not found

---

lms/static/scripts/frontend_apps/components/Button.js
lms/static/scripts/frontend_apps/components/CanvasOAuth2RedirectErrorApp.js
lms/static/scripts/frontend_apps/components/ErrorDisplay.js
lms/static/scripts/frontend_apps/components/FileList.js
lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/LMSGrader.js
lms/static/scripts/frontend_apps/components/SubmitGradeForm.js
lms/static/scripts/frontend_apps/components/SvgIcon.js
lms/static/scripts/frontend_apps/components/Table.js
lms/static/scripts/frontend_apps/components/URLPicker.js
lms/static/scripts/frontend_apps/components/ValidationMessage.js
lms/static/scripts/frontend_apps/config.js
lms/static/scripts/frontend_apps/utils/AuthWindow.js
lms/static/scripts/frontend_apps/utils/api.js
lms/static/scripts/frontend_apps/utils/google-api-client.js
lms/static/scripts/frontend_apps/utils/google-picker-client.js
lms/static/scripts/postmessage_json_rpc/client.js
lms/static/scripts/postmessage_json_rpc/random.js
lms/static/scripts/postmessage_json_rpc/server.js
lms/static/scripts/tsconfig.json
package.json
yarn.lock

Fix the remaining issues that prevented the lms frontend from being
compiled with `noImplicitAny` enabled and remove the override in
`tsconfig.json`. Note that this setting is implicitly enabled by default when
`strict` is `true`.
The result is that the types of all identifiers must be either specified
or inferred, improving documentation for the reader and helping to catch
some minor bugs.

Enable `noImplicitAny` option in TypeScript config

---

lms/static/scripts/frontend_apps/components/Button.js
package.json

This is to match the bumped Chrome version in the client.
This set of changes also includes an unrelated fix to a type in the `Button` component to soothe CI grouchiness.

Bump Chrome version to 57

---

tox.ini

A handful of make commands are currently broken:
$ make db
make: *** [Makefile:32: db] Error 1
(the underlying error, silenced by `tox -qq`, is: `ERROR: InvocationError for command could not find executable initdb`)
$ make devdata
ERROR: InvocationError for command could not find executable devdata
$ make shell
ModuleNotFoundError: No module named 'lms'
The problem seems to be that the lms module and its console scripts aren't available in the tox env `dev`.
This seems to have been caused by this previous PR https://github.com/hypothesis/lms/pull/2112 that removed `-e .` from `requirements/dev.*` in order to work around this issue in pip-compile: https://github.com/jazzband/pip-tools/issues/204
Note that the comments on the pip-compile issue suggest replacing `-e .` with `-e …

Fix broken make commands

---

tests/unit/lms/views/basic_lti_launch_test.py
tests/unit/lms/views/predicates/_lti_launch_test.py

Depends on [Add ModuleItemConfiguration test factory](https://github.com/hypothesis/lms/pull/2265).
Mocking model classes is always optional, and replacing these mocks with the real model / DB and a test factory makes the tests better.
It also makes some test changes that I need to make in a [following pull request](https://github.com/hypothesis/lms/pull/2262/commits) much easier.
Note that I didn't remove _all_ uses of mocked `ModuleItemConfiguration`'s: in some tests mocking it was actually better.

Remove ModuleItemConfiguration test mocks

---

lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
lms/static/scripts/frontend_apps/components/LaunchErrorDialog.js
lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
lms/static/scripts/frontend_apps/components/test/LaunchErrorDialog-test.js

Extract the various error dialogs that can be shown by the `BasicLtiLaunchApp` component into a separate `LaunchErrorDialog` component. This will help keep `BasicLtiLaunchApp` readable as new error cases are added. It also makes testing easier as the `BasicLtiLaunchApp` tests can focus on checking _which_ error dialog is shown and the `LaunchErrorDialog` component tests check _what_ is shown in a particular error dialog.
There should be no visual changes to the dialogs, except for a minor change in the layout of the text for the case when creating the speedgrader submission fails in Canvas due to fixing an inconsistency wrt. the other dialogs.

Extract `LaunchErrorDialog` component

---

lms/static/styles/_variables.scss
lms/static/styles/components/_BasicLtiLaunchApp.scss
lms/static/styles/components/_FilePickerApp.scss
lms/static/styles/components/_SubmitGradeForm.scss

Make 100px the size of the standard spinner.
One of them was not centered vertically.
Before:
After:

Center and standardise the size of a few spinners

---

lms/views/basic_lti_launch.py
lms/views/predicates/__init__.py
lms/views/predicates/_lti_launch.py
tests/unit/lms/views/basic_lti_launch_test.py
tests/unit/lms/views/predicates/__init___test.py
tests/unit/lms/views/predicates/_lti_launch_test.py

Fixes [course copy in Blackboard](https://github.com/hypothesis/lms/issues/2261).
When you copy a course in Blackboard, Blackboard copies all of the course's Hypothesis assignments but the new copies of the assignments all get new `resource_link_id`'s. Since the `resource_link_id` launch param is what we use to look up the assignment's settings (`ModuleItemConfiguration`) we fail to find the settings for the new copy of the assignment: to us it just looks like a brand new assignment, a new `resource_link_id` that we've never seen before. So we show the dialog asking to choose the document for the assignment.
It turns out that Blackboard also includes an undocumented and non-standard launch param `resource_link_id_history`, which is the `resource_link_id` of the original assignment that …

Fix course copy in Blackboard

---

lms/static/scripts/frontend_apps/components/Button.js
lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/LMSFilePicker.js
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js

After clicking on `Select PDF` button a number of different interfaces could render:
* full filepicker: files are fetched and displayed without problem
* empty filepicker: no associated files in the LMS for that curse
* authorization error
* other error
Previously, we optimistically displayed the filepicker, but if an error raised the layout was shifted quickly.
Based on [this conversation](https://app.slack.com/client/T03QZM0HN/C07NXBDNW/thread/C07NXBDNW-1605712544.110500), it was decided that :
* FilePickerApp will show the loading spinner when a button is clicked, and
* LMSFilePicker won't render while trying to fetch files.
This will prevent the LMSFilePicker component to re-render from one state from another.
This is an example screenshoot  of going through two consecutive …

Reduce layout shift after selecting PDF files

---

lms/views/basic_lti_launch.py
lms/views/predicates/__init__.py
lms/views/predicates/_lti_launch.py
tests/unit/lms/views/basic_lti_launch_test.py
tests/unit/lms/views/predicates/__init___test.py
tests/unit/lms/views/predicates/_lti_launch_test.py

Add Brightspace course copy support. Fixes https://github.com/hypothesis/lms/issues/2282
Course copy works exactly the same in Brightspace as it does in Blackboard: the copied assignments get a new `resource_link_id` so we can't find their settings in our DB, but the original `resource_link_id` is supplied in an additional launch param. In Blackboard this additional launch param is called `resource_link_id_history`, in Brightspace it's `ext_d2l_resource_link_id_history`.
There's some work in this PR to make previously Blackboard-specific code generic. The actual amount of new code we'd have to add if we came across a third LMS that worked in a new way (but with a third param name) is pretty minimal / the amount of Blackboard or Brightspace-specific code is pretty minimal. It's roughly …

Add Brightspace course copy support

---

lms/static/scripts/frontend_apps/components/Dialog.js
lms/static/scripts/frontend_apps/components/ErrorDialog.js
lms/static/scripts/frontend_apps/components/SubmitGradeForm.js
lms/static/scripts/frontend_apps/components/test/Dialog-test.js
lms/static/scripts/frontend_apps/components/test/SubmitGradeForm-test.js

- Add a dialog that the alerts the user that an error has occurred when fetching a students grade.
- Kill off the grade loading spinner in the grade input field after an error.
- Add cancelLabel to ErrorDialog  / Dialog to override the button's label for more appropriate action naming.
-----
This is part of an effort to make the erros a bit more understandable from the customer's point of view to help our own triage efforts. We are seeing that GET requests to `api/lti/result?lis_result_sourcedid` failing in some customer environments. It's unclear why, but it was initially unclear what the problem was because failed GET requests were not handled in a reasonable way on the UI. It was previously assuming that such things were unlikely to fail. Since that is not the case, this simply adds …

Improve the behavior or grade fetch errors

---

lms/services/lti_outcomes.py

Add logging to help see the XML response from customer's LMS that may be potentially causing the issue related to "Malformed LTI outcome response"
-------
The goal here is to see the XML response (as a dict) of the customer's LMS when requesting a grade. 
relates to https://github.com/hypothesis/support/issues/124

Add temporary logging to help debug XML error

---

lms/static/scripts/frontend_apps/components/ErrorDisplay.js
lms/static/styles/components/_ErrorDisplay.scss

Allow long text that details how to open a support ticket to wrap in small dialogs rather than displaying a horizontal scrollbar

Prevent error support text from having scroll bars

---

lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js

_Do_ re-authorize with Canvas (requesting a new access token) when
clicking the <kbd>Try again</kbd> button after Canvas Files errors from
the proxy API.
Problem
-------
See https://github.com/hypothesis/support/issues/162
1. Hack the code to request access tokens without the sections scopes:
diff --git a/lms/views/api/canvas/authorize.py b/lms/views/api/canvas/authorize.py
index 39b310d9..1fa5f4e5 100644
--- a/lms/views/api/canvas/authorize.py
+++ b/lms/views/api/canvas/authorize.py
@@ -25,9 +25,6 @@ FILES_SCOPES = (
#: The Canvas API scopes that we need for our Sections feature.
SECTIONS_SCOPES = (
-    "url:GET|/api/v1/courses/:id",
-    "url:GET|/api/v1/courses/:course_id/sections",
-    "url:GET|/api/v1/courses/:course_id/users/:id",
)
2. Delete all the OAuth 2 tokens from your DB to …

Do re-authorize after Canvas files errors

---

lms/services/exceptions.py
tests/unit/lms/services/exceptions_test.py

If we get an `"Insufficient scopes on access token"` error from the Canvas API just show the user the non-error *Authorize* dialog so they can get us a new access token (we'll always request one with the needed scopes). Don't show the user an error dialog: this is an expected / unavoidable circumstance, and getting a new access token should always fix the problem.
Fixes https://github.com/hypothesis/lms/issues/2345
Unfortunately we have no choice but to use the English-language string `"Insufficient scopes on access token."` to identify this particular type of error. Canvas doesn't provide any kind of error codes meant for machines. The HTTP status can't be used because the same status is shared by different types of error that we need to respond differently to.
I've tested in three …

Don't show error for "insufficient scopes"

---

conf/development.ini
lms/resources/_js_config.py
lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
lms/static/scripts/frontend_apps/config.js
lms/static/scripts/frontend_apps/utils/content-item.js
lms/static/scripts/frontend_apps/utils/test/content-item-test.js
tests/unit/lms/resources/_js_config_test.py

This commit adds a option to the file picker app which configures an
assignment that will use a hard-coded VitalSource book and chapter. This
assignment configuration is currently not handled by the LTI launch
code. This will follow in subsequent PRs.
This option is currently behind a `vitalsource` feature flag which is enabled via cookies, to enable the VitalSource developers to turn it on for themselves.
In future our LMS app will query the VitalSource API for a list of available books and allow the user to make a selection.
**Decision points:**
This is a note about some decisions that I need to discuss with the LMS owners:
- What should the format of the query params be for different types of LMS assignment? In this PR I've just copied the example of the way Canvas files assignments …

Add "VitalSource Book" option to file picker behind feature flag

---

lms/services/lti_outcomes.py

Log LTIOutcomesAPIError exceptions so they are picked up by sentry for easier debugging.

Log LTIOutcomesAPIError exceptions from _get_body

---

lms/static/scripts/frontend_apps/components/ErrorDialog.js
lms/static/scripts/frontend_apps/components/SubmitGradeForm.js
lms/static/styles/components/_Dialog.scss
lms/static/styles/components/_ErrorDisplay.scss
lms/static/styles/components/_LMSGrader.scss

Fix incorrect fetch grade message …
The fetch grade error was incorrectly showing the wrong message
------------
- Remove ":(" from ErrorDialog's title text for submit and fetch errors
- Set font size for Dialog content
- Remove focus outline when Dialog's content pane is in focus
- Do not override font color in LMSGrader
- ~Add default font color to body ($grey-7)~
- Use standard font sizes for LMSGrader
-----------
_Updates_
**Refactored this PR to only include CSS/text issues to dialogs. Pulled out the retry feature and will include that in another PR.
** removed body color, (will fix in follow up PR)
This PR builds off the orignal here
https://github.com/hypothesis/lms/pull/2329
fixes #2320
**Before**
**After**

Dialog visual fixes

---

lms/services/__init__.py
lms/services/vitalsource.py
tests/conftest.py
tests/unit/lms/services/__init___test.py
tests/unit/lms/services/vitalsource_test.py

This tweaks the Vital Source factory and tests to use our latest approach to services:
Add a separate `factory()` function for `VitalSourceService` so that the `VitalSourceService` class itself is more "pure" and doesn't depend on the Pyramid context and request.

Separate VitalSource launch factory

---

lms/config/__init__.py
lms/resources/_js_config.py
lms/services/__init__.py
lms/services/vitalsource.py
lms/views/basic_lti_launch.py
lms/views/predicates/__init__.py
lms/views/predicates/_lti_launch.py
tests/conftest.py
tests/unit/conftest.py
tests/unit/lms/resources/_js_config_test.py
tests/unit/lms/services/__init___test.py
tests/unit/lms/services/vitalsource_test.py
tests/unit/lms/views/basic_lti_launch_test.py
tests/unit/lms/views/predicates/__init___test.py
tests/unit/lms/views/predicates/_lti_launch_test.py
tox.ini

_This PR contains the backend changes extracted from https://github.com/hypothesis/lms/pull/2390 and rebase on master. See that PR for manual testing steps._
----
This commit adds support for loading the VitalSource book viewer in an
LTI launch if the assignment URL contains `vitalsource_enabled=true` in
the query params, similar to how Canvas files assignments are
configured.
The VitalSource book viewer is loaded via the LTI 1.1 launch process.
When an assignment is configured to use VitalSource, the backend
generates form parameters for an LTI launch and signs them using a
key and secret specified by two new env vars: `VITALSOURCE_LTI_LAUNCH_KEY`
and `VITALSOURCE_LTI_LAUNCH_SECRET`. These form parameters are rendered into
the configuration for the LMS frontend.
Existing logic in the LMS …

Support launching assignments using VitalSource books

---

lms/views/predicates/_lti_launch.py
tests/unit/lms/views/predicates/_lti_launch_test.py

Fix a regression introduced in https://github.com/hypothesis/lms/pull/2416 where the check for an assignment being URL-configured in the `configured` predicate was accidentally removed. Also fix a flaw in the tests that caused this issue to go unnoticed. See commit message for details.
I also added a test for the assignment being configured via a VitalSource book. The functionality was implemented but not tested in https://github.com/hypothesis/lms/pull/2416.

Fix `configured` predicate test not checking whether assignment is URL-configured

---

lms/views/helpers/_via.py
requirements/bddtests.txt
requirements/dev.txt
requirements/functests.txt
requirements/lint.txt
requirements/requirements.txt
requirements/tests.txt
tests/unit/lms/views/helpers/_via_test.py

Checkout versions of:
https://github.com/hypothesis/lms/pull/2457 (this PR)
https://github.com/hypothesis/checkmatelib/pull/8
https://github.com/hypothesis/h-vialib/pull/20
https://github.com/hypothesis/via3/pull/392
https://github.com/hypothesis/viahtml/pull/90
https://github.com/hypothesis/checkmate/pull/206
use your local copy of the libraries:
checkmate on via3 and viahtml
```
commands=
dev: pip install -e /home/marcos/hypo/checkmatelib
```
and h-vialib on lms
```
commands=
dev: pip install -e /home/marcos/hypo/h-vialib
```
- Start all the services and check and assigment that result in a block with your local checkmate (this one does at the moment: https://hypothesis.instructure.com/courses/125/assignments/1069)
You should see the short version of the blocked page.
"lms" has gone …

Include value for blocked_for for via/checkmate

---

lms/assets.py
tests/unit/lms/views/favicon_test.py
tests/unit/lms/views/predicates/_helpers_test.py

This PR fixes a couple of unclosed files that caused tests to fail with `ResourceWarning` errors in newer Python versions. It also accommodates a trivial change in the text of an error message between Python 3.6.x and Python 3.9.x.
Following this change all of the unit tests which do not depend on PyCrypto pass under Python 3.6.x and Python 3.9.x. The remaining cause of test failures with newer Python versions in the lms app is the unmaintained PyCrypto package which we'll need to replace. See https://github.com/hypothesis/lms/issues/2451.
See also https://github.com/hypothesis/h/pull/6508

Fix resource leaks that cause test failures in newer Python versions

---

lms/resources/_js_config.py
lms/services/__init__.py
lms/services/grant_token.py
tests/unit/conftest.py
tests/unit/lms/resources/_js_config_test.py
tests/unit/lms/services/grant_token_test.py

_This is a follow-up to https://github.com/hypothesis/lms/pull/2487._
Extract the logic that generates login ("grant") tokens for the Hypothesis client
into a `grant_token` service so that it can be re-used for an API view
that will allow the LMS frontend to regenerate the grant token when
needed.
I retained the existing "grant token" terminology in this PR, although the purpose of that is not immediately obvious from the name. Perhaps we should rename it to `client_login_token` in future?

Extract client login token generation into a service

---

lms/validation/authentication/_bearer_token.py
lms/validation/authentication/_helpers/_jwt.py
tests/unit/lms/validation/authentication/_bearer_token_test.py
tests/unit/lms/validation/authentication/_helpers/_jwt_test.py

Following up on [this Slack thread](https://hypothes-is.slack.com/archives/C4K6M7P5E/p1615897553001500?thread_ts=1615543250.068600&cid=C4K6M7P5E), this PR extends the lifetime of the JWT used by the LMS frontend in API calls to the backend from one to 24 hours. This makes it much less likely that it will expire in the middle of a user session.
The other uses of JWT (eg. for the state param in OAuth 2 flows) continue to use tokens with a one hour expiry.
- Add `lifetime` parameter to `encode_jwt` helper. The default remains at one hour. This allows different consumers to set different lifetimes
- Set a custom 24-hour lifetime on the JWT generated by the backend for the LMS frontend to use in API calls

Extend frontend API token lifetime from 1 to 24 hours

---

lms/routes.py
lms/services/grant_token.py
lms/static/scripts/frontend_apps/index.js
lms/static/scripts/frontend_apps/services/client-rpc.js
lms/static/scripts/frontend_apps/services/test/client-rpc-test.js
lms/static/scripts/frontend_apps/utils/jwt.js
lms/static/scripts/frontend_apps/utils/test/jwt-test.js
lms/views/api/grant_token.py
tests/unit/lms/services/grant_token_test.py
tests/unit/lms/views/api/grant_token_test.py

~~**Depends on https://github.com/hypothesis/lms/pull/2500**~~
During an LTI launch the LMS backend generates a grant token for use by the Hypothesis client that is valid for 5 minutes.
If the Hypothesis client attempts to fetch its configuration after this time has elapsed then the client will fail to log in. With the sidebar application this rare because the sidebar launches as soon as Via loads. It could happen however if the LMS frontend did not load the assignment content immediately but instead paused for Canvas OAuth and the user took more than 5 minutes to respond. With the client's "Notebook" application this is expected to be much more common however, because the notebook isn't loaded until the user explicitly chooses the "Open notebook" menu option.
Fix the issue by modifying …

Refresh grant token if necessary when Hypothesis client fetches configuration

---

tests/unit/lms/validation/authentication/_helpers/_jwt_test.py

The tests were attempting to check the age of a Unix timestamp in a JWT
token by comparing the `exp` field in the payload against
`datetime.datetime.utcnow().timestamp()`. This expression however
returns the wrong value. `utcnow()` returns a "naive" datetime,
which has no TZ information, and `timestamp()` assumes, incorrectly, that "naive"
datetimes are using the local timezone.
The fix here is to use `datetime.now(timezone.utc)` to generate an
"aware" datetime, for which `timestamp()` returns the correct value.
See https://docs.python.org/3/library/datetime.html#datetime.datetime.timestamp
This fixes the tests failing during daylight savings in the UK.

Fix timezone handling issue in JWT tests

---

lms/static/scripts/frontend_apps/components/SubmitGradeForm.js
lms/static/scripts/frontend_apps/components/test/SubmitGradeForm-test.js

In order to help pinpoint moodle grading errors, it will help to relay more information to the client so that it may be captured in a screen shot at the time the error occurs. This helps prevent losing metadata when the logs expire in paper trail after too much time.
--------
This is just the client change in this PR
https://github.com/hypothesis/lms/pull/2536

Render more details with LTI outcome errors

---

tests/functional/api/basic_lti_launch_test.py
tests/functional/conftest.py
tests/functional/views/reports_test.py

Split from the pyramid 2.0 PR
Wanted to confirm what's the behavior of the /report endpoint before update/changes.

Functional tests for /reports and extra case for no auth on /lti_launch

---

lms/services/lti_outcomes.py
tests/unit/lms/services/lti_outcomes_test.py

When users see a grading error, its helpful to capture to error details at the same time so we can more quickly discover causes for these errors. Passing the response data to the LTIOutcomesAPIError will allow it to propagate to the client and render in the error dialog.

Add imsx_description to LTIOutcomesAPIError details

---

lms/routes.py
lms/services/canvas_api/client.py
lms/views/api/canvas/authorize.py
lms/views/api/canvas/groups.py
tests/unit/lms/services/canvas_api/client_test.py
tests/unit/lms/views/api/canvas/authorize_test.py
tests/unit/lms/views/api/canvas/groups_test.py

(there's probably a more straightforward method to test this)
```make sql```
An run something simlar to this, use a `where id = X` or similar if you rather not enable it in all instances locally.
```update application_instances set settings = jsonb_set(settings, '{canvas,groups_enabled}', 'true');```
```make sql``` (or same shell as before)
Delete all oauth tokens locally, again, use `delete where ...` if you rather target an specific one.
```truncate  oauth2_token;``` 
head to `https://hypothesis.instructure.com/courses/125/assignments/1575` open any assigment and click "authorize"
I found the easiest to copy it from any other API call on the browerer, for example after opening the assigment, open the network tab on the brower and copy the Authorization header from the call to …

Add course group set endpoint to canvas API

---

lms/models/application_instance.py
requirements/bddtests.txt
requirements/dev.txt
requirements/format.txt
requirements/functests.txt
requirements/lint.txt
requirements/requirements.in
requirements/requirements.txt
requirements/tests.txt

For: https://github.com/hypothesis/lms/issues/2590
`pycrypto` is unsuppored and `pycryptodome` is nearly a drop in replacement for it

Replace `pycrypto` with `pycryptodome`

---

lms/models/application_instance.py
lms/services/application_instance_getter.py
requirements/bddtests.txt
requirements/dev.txt
requirements/format.txt
requirements/functests.txt
requirements/lint.txt
requirements/requirements.in
requirements/requirements.txt
requirements/tests.txt

Born of: https://github.com/hypothesis/lms/pull/2611 for: https://github.com/hypothesis/lms/issues/2590
The 'x' varient changes the name of the installed package so it's no longer a direct replacement for `pycrypto`. This means it can't conflict with it and both can be installed. It _also_ means that tools which inspect the virtual env can see it's not installed and don't get confused between the two.
I _think_ this fixes some bugs I've been having locally when switching branches where it says "AES" cannot be found. I think this is also affecting CI.

Use `pycryptodomex` instead of `pycryptodome`

---

lms/services/__init__.py
lms/services/exceptions.py
lms/services/launch_verifier.py
requirements/bddtests.txt
requirements/dev.txt
requirements/functests.txt
requirements/lint.txt
requirements/requirements.in
requirements/requirements.txt
requirements/tests.txt
tests/unit/lms/services/launch_verifier_test.py

For: https://github.com/hypothesis/lms/issues/2590
PyLTI is kind of unmaintained and the tests are very broken. This replaces it with `oauthlib` which we already use.
* The way `oauthlib` works is you have to sub-class objects and fill in loads of methods
* The major difficulty in this was previously our code and tests were pretty confused about whether this was a POST or a GET. It's always a POST. This mostly just confused me.
* There's also some weirdness where the URL we get isn't necessarily the one that was signed against. We have to strip any GET params prior to checking the signature
* Due to the important thing being the request body, and the tests previously written around the `params` exclusively the tests were quite heavily rewritten
Nothing really to do but try it against a …

Replace `PyLTI` with `oauthlib`

---

lms/static/scripts/frontend_apps/components/Dialog.js
lms/static/scripts/frontend_apps/components/test/Dialog-test.js
lms/static/styles/components/_Button.scss
lms/static/styles/components/_Dialog.scss
lms/static/styles/frontend_apps.scss

Depends on https://github.com/hypothesis/lms/pull/2594
This is the first go at replacing Button with LabeledButton. This is more or less a straight conversion as simple as it gets.
Replace Button in Dialog.js …
- Include @hypothesis/frontend-shared/styles in css main file
- Replace Button with LabeledButton
-----------
Only the cancel button has changed.
**Before**
**After**

Replace Button in Dialog.js

---

lms/static/scripts/frontend_apps/components/CanvasOAuth2RedirectErrorApp.js
lms/static/scripts/frontend_apps/components/test/CanvasOAuth2RedirectErrorApp-test.js

~_Depends on https://github.com/hypothesis/lms/pull/2604_~
Test URL for auth
http://localhost:8001/canvas_oauth_callback?authUrl=blah
Test assignment for missing keys
https://hypothesis.instructure.com/courses/121/assignments/850
**Before**
**After**

Update canvas oauth buttons

---

lms/static/scripts/frontend_apps/components/LaunchErrorDialog.js
lms/static/scripts/frontend_apps/components/test/LaunchErrorDialog-test.js

Straightforward conversion to LabledButton
**Before**
**After**

Update to LabeldButton in LauchErrorDialog

---

lms/views/api/exceptions.py

`NoOAuth2Token` is never raised by any view, so it never gets caught by
the exception view.
`NoOAuth2Token` is only ever raised by `OAuth2TokenService.get()`
https://github.com/hypothesis/lms/blob/486f56a6324cd100735737f90787a9c8b8641b70/lms/services/oauth2_token.py#L58
`OAuth2TokenService` is only ever used by `CanvasAPIClient`:
https://github.com/hypothesis/lms/blob/486f56a6324cd100735737f90787a9c8b8641b70/lms/services/canvas_api/factory.py#L22
`CanvasAPIClient` (or more accurately its private helper class
`AuthenticatedClient`) catches `NoOAuth2Token` and turns it into
`CanvasAPIAccessTokenError`:
https://github.com/hypothesis/lms/blob/486f56a6324cd100735737f90787a9c8b8641b70/lms/services/canvas_api/_authenticated.py#L61-L65

Remove NoOAuth2Token from exception views

---

lms/sentry.py
lms/services/__init__.py
lms/services/canvas_api/_authenticated.py
lms/services/canvas_api/client.py
lms/services/exceptions.py
lms/views/api/exceptions.py
tests/unit/lms/sentry_test.py
tests/unit/lms/services/canvas_api/_authenticated_test.py
tests/unit/lms/services/canvas_api/client_test.py
tests/unit/lms/services/exceptions_test.py
tests/unit/lms/services/oauth2_token_test.py
tests/unit/lms/views/api/exceptions_test.py

This is some ground work before adding in Blackboard API support.
A new `ProxyAPIError` base class is added which both `CanvasAPIError`
and `LTIOutcomesAPIError` inherit from. In future a new
`BlackboardAPIError` will also inherit from this. The
`proxy_api_error()` exception view that was previously associated with
`CanvasAPIError` and `LTIOutcomesAPIError` is now associated with
`ProxyAPIError` so if future Blackboard code uses `ProxyAPIError` it'll
get the exception view behavior for free.
`CanvasAPIAccessTokenError` is renamed to `ProxyAPIError` so that it can
be reused by the Blackboard API code. For example
`CanvasAPIAccessTokenError`'s are filtered out from Sentry. Since that's
now been changed to a `ProxyAPIAccessTokenError` that the Blackboard
code can also use, the Blackboard …

Add ProxyAPIError and ProxyAPIAccessTokenError

---

lms/static/styles/_variables.scss
lms/static/styles/components/_Button.scss
lms/static/styles/components/_LMSGrader.scss
lms/static/styles/components/_StudentSelector.scss
lms/static/styles/components/_SubmitGradeForm.scss
lms/static/styles/components/_ValidationMessage.scss
lms/static/styles/frontend_apps.scss

A few basic sass changes across the app.
- Fix the default color of the app to match the client with grey7.  This means the dialog text (previously black) is very slightly lighter and the grading bar text (prevently grey6) is very slightly darker. 
- Bake in a default cursor pointer effect for all buttons and button-like elements. This also matches the client's behavoir. Note that some of these sass changes will be wiped out when we convert the buttons over. Currently, the new buttons don't have a pointer styling so there is a lack of affordance for users when hovering over buttons--this fixes that.

Set default color in body

---

Makefile
tox.ini

This also means it will trigger the build if necessary, for example after a clean.

Fix `make shell` after recent changes

---

lms/static/scripts/frontend_apps/components/CanvasOAuth2RedirectErrorApp.js
lms/static/scripts/frontend_apps/components/LMSFilePicker.js
lms/static/scripts/frontend_apps/components/test/CanvasOAuth2RedirectErrorApp-test.js
lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js

Testing libraries uses `data-testid`. We have a fixture of both
`data-test` and `data-testid`. This changes makes consitent use of
`data-testid`.

Change `data-test` to `data-testid`

---

lms/routes.py
lms/views/admin.py
tests/unit/lms/views/admin_test.py

All of these should work:
/admin/ vs /admin
/admin/instances/ vs /admin/instances
/admin/instance/XXXX vs /admin/instance/XXXX/

Admin routes default to trailing slash but will work without it

---

Makefile

It is sometimes useful to run only the frontend or the backend tests. I
made that options more obvious by adding them on the `make help` output.
In addition I removed the reference to gulp and substitute it by a more
general `yarn test`

Specify frontend and backend tests options

---

lms/resources/_js_config.py
lms/templates/admin/instance.html.jinja2
lms/views/admin.py
tests/unit/lms/resources/_js_config_test.py

Replace the `"blackboard_files"` feature flag with a `blackboard.files_enabled` application instance setting. This allows us to enable Blackboard files for our test assignments in our test Blackboard instance, without enabling them for the public. Also once Blackboard files has been released to the public I think it might be opt-in at least at first, in which case we'll just keep using this setting.
One day we might want to enable Blackboard files by default at which point we'd need to detect whether the LMS is Blackboard (so as not to show the Blackboard files button in non-Blackboard LMS's) and then, when talking to the Blackboard API totally fails, detect that and show an error message explaining how the user needs to get their admin to set up an OAuth client in Blackboard.

Add the blackboard.files_enabled setting

---

lms/models/application_instance.py
lms/services/canvas_api/factory.py
tests/unit/lms/models/application_instance_test.py
tests/unit/lms/services/canvas_api/factory_test.py

The Canvas API client uses the netloc of `ApplicationInstance.lms_url`
as the base host to construct Canvas API URLs. The Blackboard API client
is going to have to do the same, so move the netloc parsing into the
model where both services can use it.

Add ApplicationInstance.lms_host()

---

tests/unit/lms/services/vitalsource_test.py

Add missing "/" character to allowed chars list in a test checking for a
Base64 string. This caused [occassional failures](https://github.com/hypothesis/lms/pull/2686/checks?check_run_id=2599723103) in this test.
[1] https://en.wikipedia.org/wiki/Base64#Base64_table

Allow "/" char when checking Base64 string in a test

---

lms/resources/_js_config.py
tests/unit/lms/resources/_js_config_test.py

This helper method is documented as raising `ConsumerKeyError` but I
don't think it actually does raise it: it catches it and returns
`False`.
There's no point in catching `ConsumerKeyError` here though because
`_canvas_files_available()` is only called by one method
(`enable_content_item_selection_mode()`) and that method already calls a
bunch of other things that can raise `ConsumerKeyError`.

Simplify _canvas_files_available()

---

lms/views/api/canvas/authorize.py

Found another place where `ApplicationInstance.lms_url` was being parsed with `urlparse()`.

Use ApplicationInstance.lms_host()

---

lms/views/api/blackboard/files.py
tests/unit/lms/views/api/blackboard/files_test.py

You would need the frontend changes from
https://github.com/hypothesis/lms/pull/2636 to actually test this, but:
`ProxyAPIAccessTokenError` is the one that has an exception view:
https://github.com/hypothesis/lms/blob/e174b161e90918c94402b8e662e150b063b67b42/lms/views/api/exceptions.py#L107-L109
The exception view returns a response that triggers the frontend to show
a "You need to authorize" dialog.
If the view raises `NoOAuth2Token` instead that gets caught by the
catch-all exception view that triggers a "Something went wrong" dialog.

Raise ProxyAPIAccessTokenError not NoOAuth2Token

---

lms/security.py
lms/validation/authentication/__init__.py
lms/validation/authentication/_oauth.py
lms/views/api/blackboard/authorize.py
lms/views/api/canvas/authorize.py
tests/unit/lms/security_test.py
tests/unit/lms/validation/authentication/_oauth_test.py
tests/unit/lms/views/api/blackboard/authorize_test.py
tests/unit/lms/views/api/canvas/authorize_test.py

There's nothing Canvas-specific about this schema and it's actually now used by the blackboard authorize() view as well.

Rename CanvasOAuthCallbackSchema to OAuthCallbackSchema

---

README.markdown
conf/development.ini
tests/conftest.py
tests/unit/lms/config/__init___test.py
tests/unit/lms/views/helpers/_via_test.py

It's just called "Via" now.
Also removed documentation of Via HTML as a dependency in README.markdown. Via HTML is a dependency of Via, let Via's README document it.

Remove references to Via 3

---

lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js

This field was removed in 8c4cb991cda7c2aac1d7cd28b293d1eb32c870c2 under
the mistaken assumption that it is not used. However this field is in
fact used in non-Canvas LMSes where the URL for an assignment is
configured on the first launch.
**Testing:**
Steps to reproduce:
1. In Moodle create a new External Tool assignment and select Hypothesis as the external tool
2. Click "Save and display" at the bottom of the assignment configuration form
3. When the assignment launches, you should see the content selection app. Choose a URL for the assignment
4. After submitting the URL, the assignment should load
Slack thread: https://hypothes-is.slack.com/archives/C2BLQDKHA/p1621364059016100

Re-add `document_url` form field to `FilePickerApp`

---

lms/resources/_js_config.py
tests/unit/lms/resources/_js_config_test.py

Turn off the `allowFlagging` option to remove the flag icon from
annotation cards in the LMS context.
Relates to https://github.com/hypothesis/client/pull/3424

Remove flag icon from annotation cards for LMS users

---

lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/FilePickerFormFields.js
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
lms/static/scripts/frontend_apps/components/test/FilePickerFormFields-test.js

Extract the rendering of hidden form fields in `FilePickerApp` into a separate `FilePickerFormFields` component. This will keep `FilePickerApp` more manageable as additional steps are added to the assignment configuration flow.
There are no functional changes in this PR.
Part of https://github.com/hypothesis/lms/issues/2524.
---
**Testing:**
- Try configuring LMS assignments in Canvas using the various available options (Enter URL, select file from Canvas, select file from Google). The "External tool URL" that appears in Canvas should be the same as before.

Extract FilePickerApp hidden form field rendering into separate component

---

lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/FilePickerFormFields.js
lms/static/scripts/frontend_apps/components/test/FilePickerFormFields-test.js
lms/static/scripts/frontend_apps/utils/content-item.js
lms/static/scripts/frontend_apps/utils/test/content-item-test.js

Combine the `contentItemFor<ContentType>` functions into a single
`contentItemForContent` function which accepts a `Content` object as an
argument, as well as additional query params to add to the launch URL.
Combining these functions removes the need to switch on the content type in other
places in the code.
The support for adding additional query params will be used to add the
`group_set` query param in assignments that are configured to use
groups.

Merge `contentItemFor*` functions

---

lms/static/scripts/frontend_apps/components/AuthButton.js
lms/static/scripts/frontend_apps/components/LMSFilePicker.js
lms/static/scripts/frontend_apps/components/test/AuthButton-test.js
lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js

Extract the logic for showing an authorization prompt, when fetching
files from the LMS fails, into a separate `AuthButton` component.
This simplifies the `LMSFilePicker` component and tests and will enable the
"Authorize" button logic to be reused in other places.
Part of https://github.com/hypothesis/lms/issues/2524.
----
**Manual testing:**
1. Delete your existing access token for the "localhost (make devdata)" installation of Hypothesis at https://hypothesis.instructure.com/profile/settings
2. Create an assignment and select the "Select PDF from Canvas" option
3. Click "Authorize" and verify that the auth popup appears
4. Check that clicking "Authorize" while the auth popup is open brings focus to the already-open window
5. Check that files are shown after the authorization flow in …

Extract logic to show auth popup into `AuthButton` component

---

lms/models/__init__.py
lms/models/_mixins.py
lms/models/grading_info.py

Using the existing definitions of created and & updated
Running alembic revision --autogenerate results in an empty migration.
There's more models that have `created` but not updated, does it make sense to have CreatedMixin?

Timestamped model mixin

---

lms/models/application_instance.py
lms/templates/admin/instance.html.jinja2
lms/views/basic_lti_launch.py
lms/views/content_item_selection.py
tests/unit/lms/models/application_instance_test.py
tests/unit/lms/views/basic_lti_launch_test.py
tests/unit/lms/views/content_item_selection_test.py

The standalone migration needs to be deployed first: https://github.com/hypothesis/lms/pull/2705
To test it
- Apply DB migration `hdev alembic upgrade head`
- Launch any assignment on canvas
- Check values no present on the new fields 
`select * from application_instances where tool_consumer_instance_guid is not null;`
- Manually change the GUID value to another 
`update application_instances set tool_consumer_instance_guid = 'UNIQUE GUID' where tool_consumer_instance_guid is not null;`
- Launch the assignment again, you should see an error logged on LMS' ouput

Add LMS fields to ApplicationInstance

---

lms/services/canvas_api/_basic.py
tests/unit/lms/services/canvas_api/_authenticated_test.py
tests/unit/lms/services/canvas_api/_basic_test.py
tests/unit/lms/services/canvas_api/client_test.py
tests/unit/lms/services/canvas_api/conftest.py

Problem
-------
A bunch of tests in `tests/unit/lms/services/canvas_api/` aren't
actually testing what they think they're testing. If you break the
`tests/unit/lms/services/canvas_api_client/conftest.py::http_session()`
fixture:
```diff
diff --git a/tests/unit/lms/services/canvas_api/conftest.py b/tests/unit/lms/services/canvas_api/conftest.py
index 984f8113..9cf46dc6 100644
--- a/tests/unit/lms/services/canvas_api/conftest.py
+++ b/tests/unit/lms/services/canvas_api/conftest.py
@@ -18,9 +18,7 @@ def http_session(patch):
session = session()
def set_response(json_data=None, raw=None, status_code=200):
-        session.send.return_value = factories.requests.Response(
-            json_data=json_data, raw=raw, status_code=status_code
-        )
+        session.send.side_effect = …
```

Fix some broken CanvasAPIClient tests

---

lms/services/__init__.py
lms/services/exceptions.py
lms/services/h_api.py
lms/services/http.py
lms/services/lti_outcomes.py
tests/unit/conftest.py
tests/unit/lms/services/h_api_test.py
tests/unit/lms/services/http_test.py
tests/unit/lms/services/lti_outcomes_test.py

Problem
-------
There's a bit of logic that's repeated in a few places about using
`requests` to send a request, receive the response, and validate the
response using a `marshmallow` schema, with associated error handling
and tests, re-using a TCP session, making sure appropriate timeouts are
always used, etc. This is a basic version of the logic that's repeated:
```python
session = requests.Session()
try:
response = session.request(method, url, timeout=9, ...)
response.raise_for_status()
except requests.RequestException as err:
raise CustomHTTPErrorClass(response) from err
validated_data = None
if schema:
try:
validated_data = schema(response).parse()
except lms.validation.ValidationError as err:
raise CustomHTTPValidationErrorClass(response) from err
return (response, validated_data) …
```

Deduplicate `requests` usage with a new service

---

lms/static/scripts/frontend_apps/api-types.js
lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/FilePickerFormFields.js
lms/static/scripts/frontend_apps/components/GroupConfigSelector.js
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
lms/static/scripts/frontend_apps/components/test/FilePickerFormFields-test.js
lms/static/scripts/frontend_apps/components/test/GroupConfigSelector-test.js

**Depends on ~~https://github.com/hypothesis/lms/pull/2700~~, ~~https://github.com/hypothesis/lms/pull/2706~~, ~~https://github.com/hypothesis/lms/pull/2717~~, ~~https://github.com/hypothesis/lms/pull/2707~~**
Add support in the `FilePickerApp` frontend app for configuring whether an assignment uses groups and which group set it uses. The current UI is not polished but it supports the workflow end-to-end. Polishing the UI to match the mocks will happen in subsequent PRs.
- Check for `groupsEnabled` config property in app config. When this
flag is set, selecting the content no longer auto-submits the form
but instead presents a checkbox to select whether groups are enabled
and a list of available group sets.
- Add a `GroupConfigSelector` component which presents the checkbox to
choose …

Support configuring group set for assignment in file picker UI

---

gulpfile.js
lms/assets.ini
lms/routes.py
lms/static/scripts/ui-playground/index.js
lms/static/styles/ui-playground/ui-playground.scss
lms/templates/ui-playground.html.jinja2
lms/views/ui_playground.py
scripts/gulp/create-style-bundle.js
tests/unit/lms/views/test_ui_playground.py

Add ui-playground …
- Add /ui-playground route and view
- Add static routes for js and css bundle files that ui-playground needs from the /build folder
- Add basic ui-playground html template
- Add js and css bundles for ui-playground app from frontend-shared
- Add eslint file to ignore arrow functions --otherwise causing errors in IDE
----------
http://localhost:8001/ui-playground
This is a prototype for adding the basic ui-playground to LMS and leveraging pyramid instead of using express.  This adds a new route called /ui-playground and also allows several static resources to be served from the temporary build/ dir that our frontend code uses to drop bundled resources.
This only sets up the ui playground but does not add any custom LMS pages or components. I could imagine we may have …

Add UI playground

---

requirements/requirements.in
requirements/requirements.txt

Installing webargs gets us marshmallow, but we could remove webargs
one day and continue using marshmallow. This means we list it as an independant
requirement, and that it therefore shows up in our dependency analysis.

We rely on marshmallow directly, not just as a dependency of webargs

---

lms/config/__init__.py
lms/views/api/blackboard/authorize.py
tests/conftest.py
tests/unit/lms/views/api/blackboard/authorize_test.py
tox.ini

When the user clicks the <kbd>Choose PDF from Blackboard</kbd> button, if we don't already have a Blackboard API access token for that user, the frontend opens a popup window to Blackboard's OAuth authorization page in order to start the process of getting an access token and saving it in our DB.
The view that the popup window opens to is `views/api/blackboard/authorize.py::authorize()` and our current implementation of that view is a fake: it just redirects directly to our OAuth redirect view instead of to Blackboard:
https://github.com/hypothesis/lms/blob/c4b4614aa7544ce3840150ca48da61d6cb1d2781/lms/views/api/blackboard/authorize.py#L9-L20
What's supposed to happen is that we redirect to Blackboard's authorization page, the user clicks <kbd>Allow</kbd>, and then _Blackboard_ redirects …

Redirect to the real Blackboard authorization page

---

lms/services/canvas_api/_authenticated.py
lms/validation/authentication/__init__.py
lms/validation/authentication/_oauth.py
tests/unit/lms/services/canvas_api/_authenticated_test.py
tests/unit/lms/validation/authentication/_oauth_test.py

Extract `services.canvas_api._authenticated.TokenResponseSchema` out into `lms.validation.authentication.OAuthTokenResponseSchema`.
This is a generic OAuth 2 schema, it doesn't have anything in particular to do with Canvas and it now needs to be re-used by Blackboard (in a future PR).
This PR extracts the schema out into a reusable location in `lms.validation` and adds unit tests for the schema.
While some parts of the schema's behavior are currently covered by the integrated tests under `tests/unit/lms/services/canvas_api/` the coverage isn't very good. Currently on master you can break the schema in various ways and the tests will still pass. For example:
* You can remove the `required=True`, making the `access_token` field optional
* You can make the optional `refresh_token` and …

Extract TokenResponseSchema into OAuthTokenResponseSchema

---

lms/models/h_group.py
lms/resources/lti_launch.py
lms/views/basic_lti_launch.py
lms/views/content_item_selection.py
tests/unit/lms/models/h_group_test.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/views/basic_lti_launch_test.py
tests/unit/lms/views/content_item_selection_test.py

- Truncate all existing courses on your local DB `truncate course;`
- Create a course on your local DB an assignment https://hypothesis.instructure.com/courses/125/
- Check course rows in both tables
```
postgres=# select * from course;
-[ RECORD 1 ]---------+-------------------------------------------
consumer_key          | Hypothesisb3be0b33d0b5e4b1cf3aaf04e0e1819a
authority_provided_id | 653e9620a656a954c684942f6443fa3e3410c03a
settings              | {"canvas": {"sections_enabled": true}}
postgres=# select * from grouping;
-[ RECORD 1 ]-----------+-----------------------------------------------
created                 | 2021-05-28 13:26:58.086679
updated                 | 2021-05-28 13:26:58.086679
id                      | 1
application_instance_id | 8
authority_provided_id   | …
```

Store courses on the new Course(Grouping) table

---

lms/services/http.py

I had thought that pulling out several of `requests`'s most useful
parameters and documenting them here would be a useful cheat-sheet. All
of this information is in the requests docs but not necessarily easy to
find or all in one place in those docs.
But the really long docstring is just creating too much space between
the method header and body and all the documented `requests` parameters
are crowding out our own custom parameters (such as `schema`, and more
in future) which actually makes the docstring less useful.

Shorten HTTPService's docstring

---

lms/services/__init__.py
lms/services/blackboard_api.py
lms/views/api/blackboard/authorize.py
tests/unit/conftest.py
tests/unit/lms/services/blackboard_api_test.py
tests/unit/lms/views/api/blackboard/authorize_test.py

Actually call the Blackboard API to get a real access token and save it to the DB, instead of saving a fake one.
1. To see the <kbd>Choose PDF from Blackboard</kbd> you need to cherry-pick https://github.com/hypothesis/lms/pull/2636 onto this branch: `git cherry-pick frontend-changes-for-blackboard-files-poc`
2. You need the latest dev data: run `make devdata`
3. The authorization only triggers if you don't already have a `ModuleItemConfiguration` for the test assignment or Blackboard API access token (real or fake) for the user in your DB. You can make sure of this by deleting them: `tox -qe dockercompose -- exec postgres psql -U postgres -c "'DELETE FROM oauth2_token; DELETE FROM module_item_configurations WHERE tool_consumer_instance_guid = \'041c05b262b54282a0d9b61c42413ec0\' and …

Get real Blackboard access tokens

---

lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/GroupConfigSelector.js
lms/static/scripts/frontend_apps/components/test/GroupConfigSelector-test.js
lms/static/styles/components/_FilePickerApp.scss

This PR is the next step towards aligning the group set configuration UI with the mocks in https://github.com/hypothesis/lms/issues/2523#issuecomment-821160185.
- The first commit updates the layout and text in the main `FilePickerApp` component
- The second commit updates a checkbox label in the group set configuration step of the form
- The last commit fixes a bug where an authorization prompt in the group configuration step remained visible after de-selecting the checkbox
After these changes land there is some further work to be done on the group configuration UI elements (the checkbox, select widget and associated labels).
Part of https://github.com/hypothesis/lms/issues/2524.
----
Initial content selection screen:
(_nb. There is a VitalSource option here because I have a feature flag …

Refine group set configuration UI

---

lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
lms/static/scripts/frontend_apps/utils/format.js
lms/static/scripts/frontend_apps/utils/test/format-test.js

When displaying a short description of the content for an assignment,
shorten long URLs so that the form does not overflow the viewport.
We could have gotten away with some very simple text truncation here,
but I've tried to do a little better and truncate the URL in a way that
preserves the most informative parts. I suspect we'll have use for this
logic in other places.
Fixes #2774
---
Example of group configuration screen with truncated URL:

Truncate long URLs in "Assignment details" view

---

lms/static/scripts/frontend_apps/components/ContentSelector.js
lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/FullScreenSpinner.js
lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
lms/static/scripts/frontend_apps/components/test/FullScreenSpinner-test.js
lms/static/styles/components/_BasicLtiLaunchApp.scss
lms/static/styles/components/_ContentSelector.scss
lms/static/styles/components/_FullScreenSpinner.scss
lms/static/styles/frontend_apps.scss

Since the assignment creation form is shown in an iframe, there is no indicator in the browser when the form is being submitted and the browser is waiting for the server's response. This is not a major problem because this typically happens quickly, but in case it is slow show a spinner to indicate that something is happening.
For this purpose I have extracted and re-used the spinner + backdrop that are used when the Canvas/Blackboard file picker dialog is loading. Here it is with an artificially delayed form submission:
https://user-images.githubusercontent.com/2458/120670456-56747080-c488-11eb-91e7-154e9a13eb1c.mov

Show activity indicator when file picker form is submitted

---

lms/static/styles/components/_FilePickerApp.scss

Fix an issue where the "Assignment content" and "Group assignment" rows of the "Assignment details" form could touch visually if the assignment content row flowed onto multiple lines. The left column had a bottom margin set but the right column did not.
Fix the issue by replacing the left column's bottom margin with a `row-gap` which applies to the whole row. This gap is additive to any cell margins, so the bottom margin for the header row also had to be adjusted.
Strictly speaking `row-gap` requires browsers which are a little newer than our baseline (Safari 12, Chrome 66, Firefox 61), but only slightly. In older browsers the gap will simply be missing, which I think we can live with, as the numbers of such users is very small.
**Before:**
**After:**

Add gap between rows in Assignment details form

---

gulpfile.js
lms/static/styles/lms.scss
lms/templates/base.html.jinja2

This PR incrementally aligns the CSS used by static forms (eg. https://lms.hypothes.is/welcome, https://lms.hypothes.is/flags) with the CSS used by the frontend mini-apps (file picker, assignment launch etc.) by:
- Converting the entry point for the static form's CSS bundle (`lms.css`) to a SASS file so it can use the same mixins, variables, base styles etc. as other bundles
- Using the same CSS reset in lms.scss as frontend_apps.scss
- Changing the font stack and default text color in the static forms to match that used by the frontend apps
- Removing several universal / generic selectors in lms.css
The initial motivation for this was that I uncovered that the frontend apps were loading both the `lms.css` and `frontend_apps.css` bundles and some universal selectors in `lms.css` were …

Align CSS used by static form and frontend apps

---

lms/static/scripts/frontend_apps/components/GroupConfigSelector.js
lms/static/styles/components/_GroupConfigSelector.scss
lms/static/styles/frontend_apps.scss

Wrap the contents of the space below the "This is a group assignment" checkbox in a `GroupConfigSelector__select` div with a top margin. The top margin is the same as that of a `<p>` element so the visual margin is the same whether this area is displaying the authorization prompt (which begins with a paragraph) or the group set `<select>` control and its `<label>`.
**Before:**
**After:**

Add space between checkbox and group set select

---

lms/static/styles/frontend_apps.scss

https://github.com/hypothesis/lms/pull/2793 removed a `height: 100%` rule for the `<body>` and `<html>` elements which caused the assignment content iframe to shrink to a small height because `BasicLtiLaunchApp`'s styles assumed that the parent element filled the page.

Fix regression in LTI launch app height

---

lms/static/scripts/frontend_apps/components/ContentSelector.js
lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js
lms/static/scripts/frontend_apps/config.js

Add Blackboard file picker dialog and button 
Add a Blackboard file picker similar to the Canvas PDF file picker. The Blackboard file picker enabled flag is passed in from config.blackboard.enabled. The file list is passed from config.blackboard.listFile.
The selected file is sent by passing a hidden field called document_url in the POST request and is set by passing a URLContent object to FilePickerFormField's `content` prop. Note that this is slightly different than the Canvas picker which uses a FileContent object instead and gets passed via content_items hidden field.
--------------
_Based from https://github.com/hypothesis/lms/pull/2636_
Test with `blackboardteacher`
Test content link:
https://aunltd-test.blackboard.com/webapps/blackboard/execute/blti/launchPlacement?blti_placement_id …

Add Blackboard file picker dialog and button

---

lms/services/http.py
tests/unit/lms/services/http_test.py

Multiple `BlackboardAPIClient` methods are going to have to do the same duplicate bit of code:
1. Call `OAuth2TokenService` to get the access token for the current user
2. Include the access token in an `Authorizaton: Bearer <ACCESS_TOKEN>` header when calling `HTTPService`
This PR adds that functionality to `HTTPService` so that each time `BlackboardAPIClient` calls `HTTPService` it can just do `http_service.get(..., oauth=True)`.
`HTTPService.request()` is still only 25 lines long with this new feature, and its tests are easy, so I don't think it's worth splitting it into separate services yet.

Add OAuth Authorizaton header support to HTTPService

---

lms/extensions/feature_flags/_static/feature-flags.css
lms/extensions/feature_flags/_templates/cookie_form.html.jinja2
lms/static/styles/lms.scss

This PR changes some table styles, currently used only by the `/flags` page, to use a class rather than element selector. This prevents these styles unexpectedly applying to other `<table>` elements. There should be no visual changes.
I also removed a few unused CSS classes and vendor prefixes. See commits for details.

Use class for table styles

---

lms/static/scripts/frontend_apps/components/FilePickerApp.js
lms/static/scripts/frontend_apps/components/test/ErrorDisplay-test.js
lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
lms/static/scripts/frontend_apps/components/test/SubmitGradeForm-test.js
lms/static/scripts/frontend_apps/components/test/Table-test.js
lms/static/scripts/frontend_apps/components/test/URLPicker-test.js
lms/static/scripts/frontend_apps/utils/google-picker-client.js
lms/static/scripts/frontend_apps/utils/test/google-picker-client-test.js
lms/static/scripts/karma.config.js
lms/static/scripts/postmessage_json_rpc/client.js

This PR adds test cases to cover the remaining statements that were not previously covered in the frontend code, bringing coverage up to 100%. With all statements fully covered, enforcing code coverage going forwards becomes straightforward and does not require a service like Codecov. All statements must be either covered or explicitly ignored (with `/* istanbul ignore next */`). If there is code without coverage then `gulp test` will fail, but still output the same information as if the check was not enabled. This means that during development you can just ignore the error.
- Add missing test cases for various modules under the `frontend_apps` directory
- Exclude files in the `test-util` directory from code coverage. These are helpers used only within tests.
- Add `thresholds` property …

Add missing frontend tests and enforce code coverage

---

lms/models/__init__.py
lms/resources/_js_config.py
lms/resources/lti_launch.py
lms/services/canvas_api/client.py
lms/services/group_info.py
lms/services/grouping.py
lms/validation/_api.py
lms/views/api/canvas/sync.py
lms/views/api/lti.py
tests/unit/lms/resources/_js_config_test.py
tests/unit/lms/resources/lti_launch_test.py
tests/unit/lms/services/canvas_api/client_test.py
tests/unit/lms/services/grouping_test.py
tests/unit/lms/views/api/canvas/sync_test.py

- Truncate your courses and grouping tables to test the insertion of a new course & groups
```truncate grouping, course;```
- Enable groups on the application instance
http://localhost:8001/admin/instance/Hypothesisb3be0b33d0b5e4b1cf3aaf04e0e1819a/
- Open an assignment with groups https://hypothesis.instructure.com/courses/125/assignments/873
- Check the grouping table, it should contain one row for the course and for each group (if opened as a teacher). Pay attention to the parent_id relationship, sections should point to the course.
```
-[ RECORD 1 ]-----------+-------------------------------------------------------------------------------------------------------
created                 | 2021-06-07 12:47:11.497763
updated                 | 2021-06-07 12:47:11.497763
id …
```

Canvas groups backend

---

Makefile
tox.ini

This allows you to see the coverage report again without having to re-run the entire test suite.

Add `make coverage` back as a separate command

---

tests/conftest.py
tests/functional/conftest.py
tests/unit/conftest.py

For some reason we use a different session maker in the tests vs. the app. This means the `db_session` fixture doesn't really well represent the real session object.

Use the real session maker so we get an identical session

---

lms/services/__init__.py
lms/services/canvas.py
lms/services/canvas_api/client.py
lms/views/api/canvas/files.py
tests/unit/lms/services/canvas_api/client_test.py
tests/unit/lms/services/canvas_test.py
tests/unit/lms/views/api/canvas/files_test.py
tests/unit/services.py

This makes the Canvas API service a pure API interface, and means it does not also have other canvas service responsibilities. This also extracts logic from the view and puts it into the service, thinning the view.
This is being done because:
* It's probably the correct thing to do
* The amount of logic in here is about to grow a lot

Split the non Canvas API responsibilities into a new service

---

lms/static/scripts/frontend_apps/api-types.js
lms/static/scripts/frontend_apps/components/BookList.js
lms/static/scripts/frontend_apps/components/BookPicker.js
lms/static/scripts/frontend_apps/components/ChapterList.js
lms/static/scripts/frontend_apps/components/ContentSelector.js
lms/static/scripts/frontend_apps/components/Table.js
lms/static/scripts/frontend_apps/components/test/BookList-test.js
lms/static/scripts/frontend_apps/components/test/BookPicker-test.js
lms/static/scripts/frontend_apps/components/test/ChapterList-test.js
lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js
lms/static/scripts/frontend_apps/components/test/Table-test.js
lms/static/scripts/frontend_apps/utils/api.js
lms/static/scripts/frontend_apps/utils/test/api-test.js
lms/static/scripts/frontend_apps/utils/vitalsource-sample-data.js
lms/static/styles/components/_BookList.scss
lms/static/styles/components/_Table.scss
lms/static/styles/frontend_apps.scss

Modify the "Select book from VitalSource" option in the file picker app to show a book and chapter selection UI instead of submitting a hardcoded book. The data shown in the book and chapter selection UI is
currently hardcoded data, derived from the VitalSource Products API [1],
for the two books which we know are available.
- Add a loading state (`isLoading`) to the `Table` component to indicate that data is currently being fetched. This is used by the `BookList` and `ChapterList` components added in this PR.
- Add `BookPicker`, `BookList` and `ChapterList` components to support selecting a book from VitalSource and then a chapter within that book
- Modify `ContentSelector` component to show the `BookPicker` when the "Select book from VitalSource" option is selected, instead of …

Add UI to select books from VitalSource

---

lms/static/styles/components/_FilePickerApp.scss
lms/static/styles/components/_GroupConfigSelector.scss
lms/static/styles/frontend_apps.scss

This PR makes a few adjustments to the CSS layout of the `FilePickerApp` form, and obviates the need for a SASS module for the `GroupConfigSelector` (at least for now).
User-visible changes: spacing between grid sections and elements is very subtly more consistent.
* Imitate the vertical-spacing implementation and units used in the `frontend-shared` package for consistency (and eventual replacement with utility classes or mixins)
* Use `column-gap` instead of padding/margin for simplicity
These next few screenshots show the in-progress new `Checkbox` component styling:
This is what the changes look like with the current, unstyled checkbox:

Adjust `FilePickerApp` (assignment-configuration) form layout

---

requirements/bddtests.txt
requirements/dev.txt
requirements/functests.txt
requirements/lint.txt
requirements/requirements.txt
requirements/tests.txt
tests/unit/lms/views/helpers/_via_test.py

Part of https://github.com/hypothesis/viahtml/pull/192
First commit:
h_vialib was modified to include the above option to disregard other
configurations that could be present in the host page.
Although the `ignoreOtherConfiguration` is not set by the code in LMS,
given its importance we test it here too.
Second commit:
Upgrade `h-vialib` using `hdev requirements --package h-vialib` command.

Check presence of `ignoreOtherConfiguration` in `hypothesisConfig`

---

package.json
yarn.lock

Bump the package version to avail upon the new `Checkbox` element styling.
Small-groups assignment configuration flow, before:
and after:
No other user-facing changes in this package version.

Bump `frontend-shared` package to v3.1.1

---

lms/validation/_api.py
tests/unit/lms/validation/_api_test.py

Before this fix "group_set" was always present but set to None for non
groups assignments causing a validation error.
Test for failing validation for non groups assignments

Allow group_set with a None value for non group assignments

---

lms/migrations/versions/47d738f87eb5_add_file_table.py

Adds the file table for: https://github.com/hypothesis/lms/pull/2811
```
docker stop lms_postgres_1; docker rm lms_postgres_1; make services
make sql
\d+ files;
```
You should see the file table with:
```
Column          |            Type             | Collation | Nullable |             Default              
-------------------------+-----------------------------+-----------+----------+----------------------------------
created                 | timestamp without time zone |           | not null | now()
updated                 | timestamp without time zone |           | not null | now()
id                      | integer                     |           | not null | nextval('file_id_seq'::regclass)
application_instance_id | integer                     |           | …
```

Store files migration

---

lms/views/basic_lti_launch.py
tests/unit/lms/views/basic_lti_launch_test.py

For: https://github.com/hypothesis/lms/issues/2769
We don't do anything with it, and the value we set isn't useful, but it ensures Canvas looks more like a normal launch for things down stream which might look up the details.

Ensure that Canvas files launches have a module item configuration

---

lms/app.py
lms/db/__init__.py
lms/db/_bulk_action.py
lms/events/__init__.py
lms/events/subscriber.py
lms/models/__init__.py
lms/models/file.py
lms/services/canvas_api/client.py
lms/services/canvas_api/factory.py
tests/unit/lms/db/__init___test.py
tests/unit/lms/db/_bulk_action_test.py
tests/unit/lms/events/subscriber_test.py
tests/unit/lms/services/canvas_api/client_test.py
tests/unit/lms/services/canvas_api/factory_test.py

This is following on from: https://github.com/hypothesis/lms/pull/2777 where the conversation has gotten a bit too dense to follow.
This is based on https://github.com/hypothesis/lms/pull/2810 and also has https://github.com/hypothesis/lms/pull/2808 merged in. When https://github.com/hypothesis/lms/pull/2808 is merged this can be rebased to skip the first commit.
This can't be merged before: https://github.com/hypothesis/lms/pull/2824
Testing notes:
* Run `make sql`
* Run `select * from file` - You shouldn't see anything
* Open a canvas course as a teacher
* Run `select * from file` - You should see lots of records
* Open a canvas course as a teacher
* It shouldn't crash

Add a file table and update it when we retrieve a list of Canvas files (2)

---

lms/static/scripts/frontend_apps/utils/api.js
lms/static/scripts/frontend_apps/utils/grader-service.js
lms/static/scripts/frontend_apps/utils/test/api-test.js
lms/static/scripts/frontend_apps/utils/test/grader-service-test.js

Query parameters were not encoded when constructing the `/api/lti/result` URL that is used by the LMS frontend to fetch grades. This could potentially have caused problems if the `lis_*` parameters, which ultimately come from the external LMS, contained characters that require URL-encoding.
- Add optional `params` argument to `apiCall` function which specifies
an object of query params
- Use the `params` argument in `fetchGrade` rather than constructing
the query string manually
- Fix tests for `fetchGrade`. The main test called `submitGrade` rather
than `fetchGrade`.
**Manual testing:**
Log in to our Moodle instance using the `moodleteacher` account and check that grades are fetched and submitted correctly in one of the "localhost (make devdata)" assignments in …

Add missing query parameter encoding when fetching grades

---

lms/migrations/versions/a930adadac74_add_group_info_table.py
lms/migrations/versions/d54c5430ea36_delete_stale_objects.py

A table and a FK were never deleted using the migrations and alembic is
not aware of that so it tries to delete them with every `--autogenerate`
usage.
- Switch to  `master`
- Nuke the DB `docker stop lms_postgres_1; docker rm lms_postgres_1; make services`
- Get your DB from scratch using alembic `hdev alembic upgrade head`
- Autogenerate a new migration `hdev alembic revision --autogenerate`
- Autogeneraed migration contains:
```
op.drop_table('oauth2_unvalidated_credentials')                             
op.drop_constraint('fk__lis_result_sourcedid__oauth_consumer_key__applicati_7fc0', 'lis_result_sourcedid', type_='foreignkey')
```
Repeat the process on the branch (delete auto generated migration from previous steps)
- Auto generated migration it's empty
- `hdev alembic history` …

Add migration to delete stale objects when runing all alembic migrations

---

lms/models/grouping.py

It's also always assigned a full dict so no need for mutability helpers

Grouping.extra it's not ApplicationSettings

---

.coveragerc
lms/db/__init__.py
tests/conftest.py
tests/functional/conftest.py

If starting from a empty DB we should create_all and stamp the DB with
the correct alembic version so migrate head does the right thing.
If using `make db` on a non empty DB we should rely on alembic to get us
to the right state, ie don't `create_all` or stamp the DB if alembic is
present.
- Drop your DB tables
- Checkout to some commit before a table is added, eg `a2fe3341`
- `make db`. It should create the tables an stamp the DB (but not run alembic!)
```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.                                                                
INFO  [alembic.runtime.migration] Will assume transactional DDL.                                                              
INFO  [alembic.runtime.migration] Running stamp_revision  -> 5f80062abcf4 …
```

Don't create_all when alembic is present on make db

---

lms/sentry.py
lms/services/__init__.py
lms/services/blackboard_api/service.py
lms/services/canvas_api/_authenticated.py
lms/services/canvas_api/client.py
lms/services/exceptions.py
lms/services/http.py
lms/services/oauth2_token.py
lms/views/api/exceptions.py
tests/unit/lms/sentry_test.py
tests/unit/lms/services/canvas_api/_authenticated_test.py
tests/unit/lms/services/canvas_api/client_test.py
tests/unit/lms/services/exceptions_test.py
tests/unit/lms/services/http_test.py
tests/unit/lms/services/oauth2_token_test.py

Part of https://github.com/hypothesis/lms/issues/2834 (but doesn't entirely fix it yet).
How this works for Canvas on master
-----------------------------------
`AuthenticatedClient` calls `OAuth2TokenService` to get an access token
for the user. If we don't have an access token for the user
`OAuth2TokenService` will raise `NoOAuth2Token`. `AuthenticatedClient`
catches `NoOAuth2Token` and raises `ProxyAPIAccessTokenError`:
https://github.com/hypothesis/lms/blob/be46e8c356c0da97d86c53cedab28d4b31570cc4/lms/services/canvas_api/_authenticated.py#L56-L62
An exception view catches `ProxyAPIAccessTokenError` and turns it into a
specific error response. This error response causes the frontend to show
the **Authorize Hypothesis** dialog (which does not look like an error
dialog since this is an …

Fix Blackboard access token errors

---

lms/services/assignment.py
tests/unit/lms/services/assignment_test.py

For https://github.com/hypothesis/lms/pull/2783, we'd like to access the assignment directly, so expose the existing `get()` function publicly and test it.

Make the assignment service `get()` method public

---

lms/db/_bulk_action.py
tests/unit/lms/db/_bulk_action_test.py

Test course with no Canvas files but with pre-installed localhost, QA and prod application instances so you can reproduce the crash: https://hypothesis.instructure.com/courses/270 (you'll need to re-run `make devdata`)
Fixes https://github.com/hypothesis/lms/issues/2865
Slack discussion: https://hypothes-is.slack.com/archives/C2BLQDKHA/p1624372670308400
When getting the list of files for a Canvas course that has no files the
bulk upsert code that's trying to upsert the empty list of files into
the DB crashes. The reason is that this:
```python
stmt = insert(MyModel).values([])
```
produces this SQL (you can see the SQL by doing `print(stmt)` in
Python):
```sql
INSERT INTO my_table DEFAULT VALUES RETURNING my_table.id
```
The SQL tells SQLAlchemy to insert rows into the table using the DB …

Don't crash when a Canvas course has no files

---

lms/static/scripts/frontend_apps/components/BookPicker.js
lms/static/scripts/frontend_apps/components/ContentSelector.js
lms/static/scripts/frontend_apps/components/test/BookPicker-test.js
lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js
lms/static/scripts/frontend_apps/index.js
lms/static/scripts/frontend_apps/services/index.js
lms/static/scripts/frontend_apps/services/test/vitalsource-test.js
lms/static/scripts/frontend_apps/services/vitalsource.js
lms/static/scripts/frontend_apps/utils/api.js
lms/static/scripts/frontend_apps/utils/test/api-test.js

Extract the VitalSource-specific API wrappers out of `utils/api.js` and put them in a VS-specific service. This change follows the example of `GradingService`.

Move VitalSource API wrappers to a service

---

lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.js
lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
lms/static/scripts/frontend_apps/components/LMSFilePicker.js
lms/static/scripts/frontend_apps/components/LMSGrader.js
lms/static/scripts/frontend_apps/components/LaunchErrorDialog.js
lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js
lms/static/scripts/frontend_apps/components/test/LMSGrader-test.js
lms/static/scripts/frontend_apps/config.js
lms/static/scripts/frontend_apps/index.js
lms/static/scripts/frontend_apps/services/client-rpc.js
lms/static/scripts/frontend_apps/services/index.js
lms/static/scripts/frontend_apps/services/test/client-rpc-test.js
lms/static/scripts/frontend_apps/services/test/vitalsource-test.js
lms/static/scripts/frontend_apps/services/vitalsource.js
lms/static/scripts/frontend_apps/utils/api.js
lms/static/scripts/frontend_apps/utils/test/api-test.js
lms/static/styles/components/_BasicLTILaunchApp.scss
lms/static/styles/frontend_apps.scss

Update the names of several identifiers in frontend code to match the current [conventions for identifier naming](https://github.com/hypothesis/frontend-toolkit/blob/master/docs/js-guide.md#identifier-naming). See commit messages for details.
----
Note for future reference:
The shell command I used involved [fd](https://github.com/sharkdp/fd) and [sd](https://github.com/chmln/sd) (modern alternatives to `find` and `sed`):
```shellsession
$ fd . lms/static | xargs sd ApiCallInfo APICallInfo
```
For more targeted renaming of symbols I used TypeScript's rename refactoring via [`:ALERename`](https://github.com/dense-analysis/ale#2viii-refactoring-rename-actions) (in VS Code this is probably available in the context menu).

Update casing of acronyms in identifiers in frontend code

---

lms/services/blackboard_api.py
lms/validation/_base.py
tests/unit/lms/services/blackboard_api_test.py

Depends on https://github.com/hypothesis/lms/pull/2854
Fixes https://github.com/hypothesis/lms/issues/2834
Handle access token-related errors from Blackboard correctly.
It's common for Blackboard API requests to come back with an error
response that means our access token was invalid. For example this
happens when the access token has been expired or has been revoked. When
these happen we need to catch them and raise `OAuth2TokenError` so that
the frontend displays an **Authorize Hypothesis** dialog rather than
displaying a **Something went wrong** error dialog.
Testing
-------
Break all the access tokens in your DB:
tox -qe dockercompose -- exec postgres psql -U postgres -c "UPDATE oauth2_token SET access_token = 'foo';"
This will generate the same response from Blackboard as if the …

Handle access token-related errors from Blackboard

---

lms/static/scripts/frontend_apps/components/ErrorDisplay.js
lms/static/scripts/frontend_apps/components/test/ErrorDisplay-test.js
lms/static/scripts/frontend_apps/components/test/LaunchErrorDialog-test.js

Fix ErrorDisplay to show the provided message in the rare cases where error.message is not empty AND the message prop is missing.
nb. In most cases error.message's text originated from the server.
--------
There are 4 possible states for the messages that ErrorDisplay renders
1. message && error.message = "message: _error.message_"
2. message && !error.message = "message"
3. !message && error.message = "error.message"
4. !message && !error.message = ""
Prior to this fix, case 3 was not working and so the error.message was not showing in the DOM.
run `make devdata`
Load up this assignment https://aunltd-test.blackboard.com/webapps/blackboard/execute/blti/launchPlacement?blti_placement_id=_20_1&content_id=_80_1&course_id=_19_1
...you can now see the error message in the dialog
_"A problem …

Fix ErrorDisplay so it shows error.message

---

lms/resources/_js_config.py
lms/routes.py
lms/views/basic_lti_launch.py
tests/unit/lms/resources/_js_config_test.py
tests/unit/lms/views/basic_lti_launch_test.py

Pass the assignments `resource_link_id` (assignment ID) to the Canvas Files `/via_url` API.
In future PRs the `/via_url` API is going to need the `resource_link_id` to fix course-copied Canvas files assignments. It's needed to look up the assignment's `ModulteItemConfiguration` (assignment configuration) in the DB in order to get and set "Canvas file mappings" in the `ModulteItemConfiguration.extra` column.

Add resource_link_id param to via_url API

---

lms/static/scripts/frontend_apps/components/BookPicker.js
package.json
yarn.lock

This PR bumps the `frontend-shared` package version and uses in the provided `Modal` component  in the `BookPicker` component (VitalSource). This was a very simple substitution as the component API is the same as the local LMS `Dialog`, and the tests mock imported components.
These changes only replace the Modal “shell.” The content in the book- and chapter-picking steps remains unchanged. What you should expect to see: 
* The Modal "shell" looks and behaves like our standardized Panel/Dialog/Modal patterns. This is more about standardization than beautification.
* Overflowing content scrolls correctly based on viewport constraints.
A couple of notes:
* The width of the book-picking modals in Canvas, while wide enough to accommodate the content, “looks” a little narrow. This isn’t the …

Use shared `Modal` in `BookPicker` component

---

lms/services/__init__.py
lms/services/file.py
tests/factories/__init__.py
tests/factories/file.py
tests/unit/lms/services/file_test.py

This will be used by the Canvas service in future to look up matching files in the DB.
While `FileService` might look a little silly right now (it's just a single `get()` method) it actually does encapsulate a non-trivial amount of code and tests, keeping that complexity out of the higher-level business logic that's going to call this service in a future PR. It also provides a place for us to put other file-related methods in future if we ever need them (listing all the files in a course, searching for files by name and size, etc). It'd be the obvious place for code for bulk upserting files too.

Add FileService

---

lms/services/canvas.py
tests/unit/lms/services/canvas_test.py

A future PR is going to add business logic to `CanvasService.public_url_for_file()` that will call this `CanvasService.find_matching_file_in_course()`.
I've made `find_matching_file_in_course()` a separate public method because it's a logically separate unit that *could* be used by other code outside of `CanvasService` even though it isn't going to be right now, and because having it be a separate public method encourages a good method name, good docstring, and its own separate unit tests. Small separate units instead of one big unit where a top-level public method calls lots of private methods.
When searching for a matching file in a course we do this by calling the Canvas API to get a list of all the files in the course, rather than looking in our `models.File` table in the DB, because: …

Add CanvasService.find_matching_file_in_course()

---

lms/services/assignment.py
tests/unit/lms/services/assignment_test.py

This was already approved in a previous PR (https://github.com/hypothesis/lms/pull/2878) but then got lost in some rebase confusion (that PR got merged into _another_ PR and then got rebased out of that other PR before the other PR was merged into master).

Add AssignmentService.{get,set}_canvas_mapped_file_id()

---

lms/models/module_item_configuration.py
lms/services/assignment.py
tests/unit/lms/models/module_item_configuration_test.py
tests/unit/lms/services/assignment_test.py

I'm not sure [what I was thinking](https://github.com/hypothesis/lms/pull/2878#issuecomment-870505721) but this code is much simpler in the model than in the service and the higher-level code that calls it ends up simpler as well (see https://github.com/hypothesis/lms/pull/2899/files#r660780163)

Move {get,set}_canvas_file_mapping() onto model

---

lms/services/file.py
tests/unit/lms/services/file_test.py

I'm not sure [what I was thinking](https://github.com/hypothesis/lms/pull/2892#discussion_r660528549) but the higher-level code that's going to call `FileService` ends up simpler if `FileService`'s factory injects the `ApplicationInstance`. Without this change `CanvasService.public_url_for_file()` ends up with too many arguments. See https://github.com/hypothesis/lms/pull/2899/files#r660780163

Inject current ApplicationInstance into FileService

---

lms/services/canvas_api/client.py

Because `CanvasAPIClient` is a `pyramid_services` service it is a per-request singleton:
`pyramid_services` instantiates services lazily. `FooService` doesn't get instantiated until something in the request does
`request.find_service(name="foo")`. Once `FooService` has been instantiated the instance is cached in a per-request registry so that any further calls to `find_service(name="foo")` made during the same request will return the same instance. But any calls made by other requests return another instance.
This is handy because it means that services can cache things on a per-request basis just by saving them on `self` or by using the standard library's `@cached_property` and `@lru_cache` decorators.
We likely want to make use of this service-layer caching for any methods that do …

Add caching of some Canvas API responses

---

lms/views/application_instances.py
tests/unit/lms/views/test_application_instance.py

Both sections and groups enabled by default for now.

Enable canvas groups assignments on new installs

---

lms/static/scripts/frontend_apps/utils/AuthWindow.js

The fixed size auth window is a bit too small for Blackboard's content to fit. Increase the height to 560px which is just big enough to fit the content without a vertical scroll bar.
-----------
fixes https://github.com/hypothesis/lms/issues/2759

Increase height of AuthWindow popup

---

lms/models/application_instance.py
lms/models/course.py
lms/models/group_info.py
lms/models/grouping.py
lms/models/lti_launches.py
lms/models/module_item_configuration.py
lms/models/oauth2_token.py

Something mentioned the other day, I think there's some value on being able to copy paste something as simple as "a column with a string" without having to remember String vs Unicode on every PR.
---
Main benefit it's consistency across models.
Behaviour wise main difference is requiring an explicit decoding while
using bytes.
https://docs.sqlalchemy.org/en/14/core/type_basics.html#sqlalchemy.types.Unicode

Use sa.Unicode over sa.String in DB models

---

lms/models/module_item_configuration.py
lms/services/canvas.py
lms/views/api/canvas/files.py
tests/unit/lms/models/module_item_configuration_test.py
tests/unit/lms/services/canvas_test.py
tests/unit/lms/views/api/canvas/files_test.py
tests/unit/services.py

A total clone of https://github.com/hypothesis/lms/pull/2899, purely for the purposes of making review easier as the other PR is lousy with comment.
Fixes https://github.com/hypothesis/lms/issues/2764.
Testing
=====
All the test cases should work with our [Canvas test site](https://hypothesis.instructure.com/).
You need to run `make devdata` in the LMS project to make sure you have the latest development data.
To get to an SQL shell (to run the various example SQL commands in the test cases below) run `make sql`.
Test data:
* [Developer Test Course with Sections Enabled][] is the original (non-copied) test course
* [localhost (make devdata) Canvas Files Assignment] is a Canvas Files assignment in this course
* File **798** (`Françoise_Hardy.pdf`) is a PDF file in this course that the …

Fix canvas course copy 2

---

lms/services/blackboard_api.py
lms/views/api/blackboard/files.py
tests/unit/lms/services/blackboard_api_test.py
tests/unit/lms/views/api/blackboard/files_test.py

Fixes https://github.com/hypothesis/lms/issues/2031
This adds a little logic to a view but it's only a little: one `for`, one `if` and one `break`. I think it's acceptable. The view is still only  13 lines (including blanks) and I don't think its tests will be too difficult.
**Let's not generalize this:** it's probable that the `paging.nextPage` field is a common field that the Blackboard API sends in responses to different endpoints, and that this code could be put in a generic place where it could be re-used by multiple endpoints.  I haven't investigated that because I don't need to for the Blackboard Files feature. `list_files()` is the only Blackboard API endpoint that we call that returns a list of results. And we have no current plans to add any other Blackboard API-related …

Add Blackboard Files pagination support

---

lms/views/api/blackboard/files.py
tests/unit/lms/views/api/blackboard/files_test.py

When getting a course's list of files from the Blackboard API show only files, not folders.
Note that this only shows the top-level files. It doesn't return files within folders within the course. I think we may need to do more work to support folders and part of that work will likely involve _removing_ this `?type=file` parameter so that we can get both files and folders and then treat folders specially. But for now we have no folders support. Our frontend does not understand folders and thinks they're files, it lets users select folders as if they were files and then create broken assignments. So this PR at least makes it so that we have _clean_ "Blackboard Files without folders" support for now.
Blackboard's API docs are here: https://developer.blackboard.com/portal/displayApi
See …

Show only files (not folders) from Blackboard

---

lms/services/canvas_api/client.py
tests/unit/lms/services/canvas_api/client_test.py

Fixes https://github.com/hypothesis/lms/issues/2879
Sorting by name (the default) leads to, depending on number of files/ pagination, weird behavior.
For example, to reproduce the orignal bug, you can rename this file to `AAAA.pdf` (which already exists on the root folder)
https://hypothesis.instructure.com/courses/125/files/folder/Duplicated%20name%20file?
(remember to rename it back to something else to avoid leaving the course in a broken state)
change your pagination setting locally to something smaller in `lms/services/canvas_api/_basic.py` change `PAGINATION_PER_PAGE` to `2`
you'll get an exception if you try to launch the assignment. Notice that is not just a duplicated row, of the two AAAA.pdf files only one is returned but twice so information is lost.
To fix this we do both:
- …

Explicitly sort by `position` when getting files

---

lms/views/api/blackboard/_schemas.py
tests/unit/lms/views/api/blackboard/_schemas_test.py

Fixes https://github.com/hypothesis/lms/issues/2930
When getting the list of a course's files from the Blackboard API when creating an assignment only show PDF files.
As far as I can tell there's no Blackboard API parameter to request only a particular type of file. We just have to retrieve all the files ourselves and then filter them based on their `mimeType` field.
Blackboard API docs:
https://developer.blackboard.com/portal/displayApi

Only show PDFs from Blackboard

---

lms/templates/admin/instance.html.jinja2
lms/views/admin.py
tests/unit/lms/views/admin_test.py

This reduces repetition in a number of places by:
* Parameterising the settings, sub-settings and field names of checkboxes on the admin HTML page
* Using Jinja2 macros for repeated elements in the HTML
This is a precursor to Microsoft OneDrive to give us a nice small PR there.

Reduce repetition in the application instance admin pages

---

lms/static/scripts/frontend_apps/utils/google-api-client.js

We no longer use the `transform-async-to-promises` Babel plugin, so we don't need to workaround a conflict between it and the `mockable-imports` plugin.

Remove an obsolete workaround for a Babel plugin conflict

---

lms/templates/admin/instance.html.jinja2
lms/views/admin.py
tests/unit/lms/views/admin_test.py

Instead of having a different field name for each setting, just use the setting and sub-setting names to generate it.

Use the setting and sub-setting name to generate the form field name

---

lms/static/scripts/frontend_apps/components/ContentSelector.js
lms/static/scripts/frontend_apps/components/LMSFilePicker.js
lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js
lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js

Make the no file message href dynamic 
Change the LMSFilePicker to render a different documentation help link when no files are returned for Blackboard vs Canvas.
------
Update
I have refactored this PR to no longer use a provider and instead take a `missingFilesHelpLink` prop from ContentSelector.
Secondly, we have decided the 0 way to link to Blackboard docs is to link to an internal alias we maintain that has external links for file upload documentation for both ultra and classic version so blackboard. Currently there is no way to differentiate between these versions from the perspective of the client or config.
Slack discussion here
https://hypothes-is.slack.com/archives/C2BLQDKHA/p1625075688421600
Fixes https://github.com/hypothesis/lms/issues/2860

Fix blackboard content link

---

lms/services/__init__.py
lms/services/basic_blackboard_api.py
lms/views/api/blackboard/authorize.py
lms/views/api/blackboard/files.py
tests/unit/lms/services/basic_blackboard_api_test.py
tests/unit/lms/views/api/blackboard/authorize_test.py
tests/unit/lms/views/api/blackboard/files_test.py
tests/unit/services.py

This is a temporary step to make way for a new high-level client that's going to be called `BlackboardAPIClient`.
In a future commit `BasicBlackboardAPIClient` will no longer be a service and will become a private helper of `BlackboardAPIClient`.

Temporarily rename BlackboardAPIClient to BasicBlackboardAPIClient

---

lms/services/blackboard_api/_schemas.py
lms/views/api/blackboard/files.py
tests/unit/lms/services/blackboard_api/_schemas_test.py
tests/unit/lms/views/api/blackboard/files_test.py

Make the `BlackboardAPIClient` service (and its schemas) just return Blackboard API dicts in the format given by the Blackboard API, without modifying them.
The service *does* remove unwanted fields that we don't care about from the dicts. In the future we'll actually add Blackboard API query params to request only the fields we want and save network bytes.
The service does also validate that the Blackboard dicts are as we expect.
But it doesn't mutate them any further. Instead it's the view's job to not about our proxy API's response format and transform the dicts into that format.

Move "marshalling" code from schemas to views

---

lms/services/__init__.py
lms/services/blackboard_api/basic.py
lms/services/blackboard_api/client.py
lms/services/blackboard_api/factory.py
lms/views/api/blackboard/authorize.py
tests/unit/lms/services/blackboard_api/basic_test.py
tests/unit/lms/services/blackboard_api/client_test.py
tests/unit/lms/services/blackboard_api/factory_test.py
tests/unit/lms/views/api/blackboard/authorize_test.py
tests/unit/services.py

Rename the `BasicBlackboardAPIClient` class to just `BasicClient` and move it into `BlackboardAPIClient`. It's now accessible as `BlackboardAPIClient.api` and is no longer a top-level service.
Note that `BasicClient` is still public and is still used (via `BlackboardAPIClient.api`) by some external code. In a future PR it'll
become completely private.

Move BasicBlackboardAPIClient into BlackboardAPIClient

---

lms/services/blackboard_api/_basic.py
lms/services/blackboard_api/client.py
lms/services/blackboard_api/factory.py
lms/views/api/blackboard/authorize.py
tests/unit/lms/services/blackboard_api/_basic_test.py
tests/unit/lms/services/blackboard_api/client_test.py
tests/unit/lms/views/api/blackboard/authorize_test.py
tests/unit/services.py

Make `BasicClient` a private helper of `BlackboardAPIClient`. It's no longer directly accessible to external code via
`BlackboardAPIClient.api`. Instead `BlackboardAPIClient` exposes its own public methods that delegate privately to `BasicClient`.

Make BasicClient private

---

package.json
yarn.lock

Remove three unused npm dependencies:
- prop-types
- @types/prop-types
- babel-plugin-transform-async-to-promises
See commit messages for more details.

Remove unused npm deps
