lms/static/scripts/frontend_apps/components/FilePickerApp.tsx, lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js, lms/views/lti/deep_linking.py, tests/unit/lms/views/lti/deep_linking_test.py
The older version was based on a dictionary allowing arbitrary values that obscured the fact that the only value there was `group_set`.
Deep linking is sufficiently complex to add trying to get what data we might get when we know exactly its shape.
We have an idea to introduce maybe a "AssignmentConfiguration" concept which could be the same in deep linking, assignment editing and assignment retrieval. I reckon this small change will make that more obvious.
- Reconfigure https://hypothesis.instructure.com/courses/125/assignments/4682/edit?return_to=https%3A%2F%2Fhypothesis.instructure.com%2Fcourses%2F125%2Fassignments%2F4682 twice.
1. - Selecting a group set (it becomes a groups assignment)
2. - Not selecting a group set (it becomes a sections one)
=> Simplify the DL configuration to explicitly take `group_set`

lms/models/grading_info.py, tests/factories/grading_info.py, tests/unit/lms/models/grading_info_test.py, tests/unit/lms/services/grading_info_test.py
This value is present on the application instance, which grading info has a relationship with.
Removing the field here and doing the migration later. We are removing a null able columns so we have to first remove any usage of the column and later remove the column, opposite order than when adding new columns.
- Truncate local grading info
```docker compose exec postgres psql -U postgres -c "truncate lis_result_sourcedid"```
- As a learner, `aunltd.S1` launch https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2424/View?ou=6782
You'll get a new row on the table, no `tool_consumer_info_product_family_code`.
```
docker compose exec postgres psql -U postgres -c "select tool_consumer_info_product_family_code, id from  lis_result_sourcedid"
tool_consumer_info_product_family_code …
```
=> Remove `tool_consumer_info_product_family_code` from `GradingInfo`

lms/migrations/versions/106d94be7705_remove_family_grading.py, lms/models/grading_info.py, tests/factories/grading_info.py, tests/unit/lms/models/grading_info_test.py, tests/unit/lms/services/grading_info_test.py
Needs:
- https://github.com/hypothesis/lms/pull/5554
Note that in this case, because we are removing an existing column, we first remove the code that uses it, then the column itself.
```
hdev alembic upgrade head                                                                                                           
dev run-test-pre: PYTHONHASHSEED='4132713221'
INFO  [alembic.runtime.migration] Running upgrade 973c9358b616 -> 106d94be7705, Remove …
```
=> Remove LMS family from the grading table, migration.

conf/alembic.ini, lms/migrations/env.py
Always read it from the `DATABASE_URL` environment variable.
This works on the local environment (where the env var is set by tox) and in EBS (environment variable also set there).
Sanity check with something like:
```tox -e dev --run-command 'alembic downgrade -1'```
=> Simplify alembic DB URL configuration

lms/resources/_js_config/__init__.py, lms/services/lti_grading/_v13.py, tests/unit/lms/resources/_js_config/__init___test.py, tests/unit/lms/services/lti_grading/_v13_test.py
For:
- https://github.com/hypothesis/support/issues/43
The issue is:
- Student A launches assignment, we record a row in GradingInfo
- The school admins upgrade to LTI1.3
- In the process the value of `lis_result_sourcedid` for that student changes
- A teacher tries to grade Student A, it gets a "Student not in course" as using the old `lis_result_sourcedid` we recorded, not the new LTI1.3 version of that.
We'll rely on the fact user_id being the same in both LTI version. This is in theory not always true but we use the `lti/claim/lti1p1` to account for that already in the code:
https://github.com/hypothesis/lms/blob/main/lms/models/lti_params.py#L170
Doing the same test in 4 LMSes to prove that.
(setting up an actual tool upgrade in the LMS is a long process that has to be repeated once …
=> Fix for grading for grading infos created before a LTI upgrade

lms/static/scripts/frontend_apps/components/ContentFrame.tsx
This enables the "Copy transcript" button to work in Via's video player app. Without this, the button works in a standalone Via tab, but fails when embedded in the LMS app with this error:
```
The Clipboard API has been blocked because of a permissions policy applied to
the current document. See https://goo.gl/EuHzyv for more details.
```
This error does not occur if visiting a video directly (eg. at https://qa-via.hypothes.is/https://www.youtube.com/watch?v=x8TO-nrUtSI). This is because in that context, both the top level and child iframes come from the same domain, and thus the restriction on cross-origin iframes doesn't get applied to it.
See also: https://web.dev/async-clipboard/#permissions-policy-integration
Note this fix will likely not work if our LMS app is being displayed inside …
=> Enable clipboard-write permission for assignment content frame

lms/static/scripts/frontend_apps/components/ContentFrame.tsx
This enables the full-screen button in the YouTube video player to work, as long as the assignment is loaded in a new tab or the permission is also enabled for the iframe created by the LMS.
**Testing:**
1. Go to https://hypothesis.instructure.com/courses/125/assignments/4989
2. Start playing the video
3. Click the full-screen button in the video player. On `main` it will be disabled. On this branch it should work.
=> Allow use of full-screen mode in assignment content

lms/product/canvas/_plugin/grouping.py, lms/product/canvas/_plugin/misc.py, lms/product/d2l/_plugin/misc.py, lms/product/plugin/grouping.py, lms/product/plugin/misc.py, lms/resources/_js_config/__init__.py, lms/services/assignment.py, lms/services/grouping/service.py, lms/views/lti/basic_launch.py, tests/factories/assignment.py, tests/unit/conftest.py, tests/unit/lms/product/canvas/_plugin/misc_test.py, tests/unit/lms/product/d2l/_plugin/misc_test.py, tests/unit/lms/product/factory_test.py, tests/unit/lms/product/plugin/grouping_test.py, tests/unit/lms/product/plugin/misc_test.py, tests/unit/lms/services/assignment_test.py, tests/unit/lms/views/lti/basic_launch_test.py
This PR doesn't contain any D2L deep linking code but it's motivated by that.
Being more explicit about what we are doing with assignments and when will allow to plug a small difference for D2L (to handle groups).
I haven't explored here the idea we discussed about a potential "AssignmentConfiguration` dataclass or similar to keep things more focused now but I reckon is more evident in this PR where that would go.
The main change here are:
- replacing `upsert_assignment` with more explicit methods and a `get_assignment_for_launch`
- Add more parameters to the plugins that get document_url and group_set_id
Some sanity checking Canvas and D2L, no new behaviors here.
- Use a teacher login, eg: `eng+canvasteacher@hypothes.is`
- [Reconfigure a canvas …
=> Refactor lti launches to be more explicit about assignments 

lms/services/youtube.py, lms/templates/admin/application_instance/show.html.jinja2
Enable the `"youtube.enabled"` feature by default for all application
instances that don't have this feature explicitly set to `false` in the
DB.
This will enable the feature for many application instances but not all:
whenever you edit an application instance using the admin pages it
writes the default value for settings such as `youtube.enabled` into
that application instance's settings in the DB even if that setting
wasn't changed. So application instances that've been edited in admin
pages since the `youtube.enabled` setting was added to the admin pages
will have `false` in the DB for that setting. We'll need to do a DB
migration to change those to `true`.
=> Enable the YouTube feature by default

lms/migrations/versions/1872d16c28a4_enable_the_youtube_enabled_setting_for_.py
Add a DB migration to set the `youtube.enabled` application instance
setting to `true` for all those application instances that currently
have it set to `false`.
Combined with https://github.com/hypothesis/lms/pull/5598 (which enables
`youtube.enabled` for all instances that don't have a value for this
setting in the DB) this will enable the YouTube feature for all
application instances.
This migration is necessary because when you edit an instance in the
admin pages it writes the default value for every setting into the DB
for that instance, even if that setting wasn't edited. So any instances
that've been edited since the `youtube.enabled` setting was added to the
admin pages will have the previous default value of `false` in the DB.
=> Add a migration to enable the YouTube feature

lms/static/scripts/frontend_apps/components/URLPicker.tsx, lms/static/scripts/frontend_apps/components/test/URLPicker-test.js
Since the behavior of the YouTube feature flag has/is going to be changed to be enabled by default, having it disabled no longer means that the feature is coming, but that it has been consciously disabled.
Because of that, this PR changes the error we display if someone tries to use a YouTube URL in the `URLPicker`, to simply state that it is not supported.
=> Improve error displayed in URLPicker when YouTube is not enabled

lms/product/d2l/_plugin/grouping.py, tests/unit/lms/product/d2l/_plugin/grouping_test.py
With the new support for deep linking the look up is as follows:
- If we have an assignment on the DB, use that.
This will reflect the state of the assignment taking into account any possible edits.
- If we haven't seen the assignment before but the assignment has been copied form another one in the DB, use that row.
This will handle first launches of copied courses.
- If we don't have an assignment or a copy take the value from deep linking.
This will cover the case of first launches after deep linking.
- Clean the DB state
```docker compose exec postgres psql -U postgres -c "truncate assignment cascade"```
- Log in in D2L as `HypothesisEng.Teacher` 
- Create a deep linked assignment (Existing Activities -> Hypothesis link (deep linking) use a group set.
- The new assignment will have an …
=> Handle getting the configured group set in D2L

lms/migrations/versions/0c52a13c6cad_canvas_sso_urls.py, lms/views/admin/lti_registration.py, tests/unit/lms/views/admin/lti_registration_test.py
For:
- https://github.com/hypothesis/support/issues/35
See: https://community.canvaslms.com/t5/The-Product-Blog/Minor-LTI-1-3-Changes-New-OIDC-Auth-Endpoint-Support-for/ba-p/551677
```
URLs that will change:
The OIDC Auth endpoint, also called the Authorization Redirect URL
Old: https://canvas.instructure.com/api/lti/authorize_redirect
New: https://sso.canvaslms.com/api/lti/authorize_redirect
The Canvas Public JWKs endpoint
Old: https://canvas.instructure.com/api/lti/security/jwks
New: https://sso.canvaslms.com/api/lti/security/jwks
The Grant Host endpoint, sent as the aud claim in LTI Advantage API tokens
Old: https://canvas.instructure.com/login/oauth2/token
New: https://sso.canvaslms.com/login/oauth2/token
```
The old URLs will still work but there's some risk they wont in the future. …
=> Use new canvas URLs in LTI registrations

lms/static/scripts/frontend_apps/components/ContentFrame.tsx
This enables the Play button in Via's video player to work, in Chrome, before the user has interacted with the YouTube iframe. See https://developer.chrome.com/blog/autoplay/#iframe-delegation.
Fixes https://github.com/hypothesis/via/issues/1136
=> Enable autoplay permission for content frame

lms/services/jwt.py, tests/unit/lms/services/jwt_test.py
Discovered while working on:
- https://github.com/hypothesis/product-backlog/issues/1515
Invalid headers cause 500 responses. Handle the same exception than while decoding the whole token.
I haven't seen this happen in the wild but the IMS certification tool does  send an invalid header.
Simulate an invalid token with:
- On `main`:
```
curl -X POST localhost:8001/lti_launches \
-H "Content-Type: application/x-www-form-urlencoded" \
-d 'id_token=test'
````
You'll get an unhandled:
```
jwt.exceptions.DecodeError: Not enough segments
```
- On `jwt-error-handling`
same test:
```
curl -X POST localhost:8001/lti_launches \
-H "Content-Type: application/x-www-form-urlencoded" \
-d 'id_token=test'
````
you'll get a similar error but this time it's handled like other JWT related ones:
``` …
```
=> Handle invalid headers errors while decoding id_tokens

lms/product/d2l/_plugin/misc.py, lms/product/plugin/misc.py, lms/resources/_js_config/__init__.py, lms/static/scripts/frontend_apps/config.ts, lms/views/lti/deep_linking.py, tests/unit/lms/product/d2l/_plugin/misc_test.py, tests/unit/lms/product/plugin/misc_test.py, tests/unit/lms/views/lti/deep_linking_test.py
For:
- https://github.com/hypothesis/lms/issues/5544
The default, false, will apply in Canvas where the assignment title is set directly on the LMS.
In D2L the assignment title will be set up as part of our deep linking message so we'll prompt for a title there.
This PR only add the hint for the frontend to prompt for the title or not. No actual prompting happens here.
=> Expose a setting in the filepicker to prompt for an assignment title

lms/static/scripts/frontend_apps/components/FilePickerApp.tsx, lms/static/scripts/frontend_apps/components/FilePickerFormFields.tsx, lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js, lms/static/scripts/frontend_apps/components/test/FilePickerFormFields-test.js
**Depends on https://github.com/hypothesis/lms/pull/5568**
When the backend sets the `promptForTitle` flag to indicate that an assignment title should be entered by the user as part of the configuration, display a new "Title" input on the details screen. This is currently prefilled with "Hypothesis assignment" as a default. When the user submits the form, a new hidden "title" field will be added to the form submission.
Please consider the layout here preliminary and subject to change. We have also discussed potentially moving this to a separate screen, or re-ordering it.
Part of https://github.com/hypothesis/lms/issues/5544
----
=> Prompt for title in assignment config when `promptForTitle` flag is set by backend

lms/services/assignment.py, lms/services/lti_grading/_v13.py, lms/services/lti_grading/factory.py, lms/services/lti_grading/interface.py, lms/views/lti/basic_launch.py, tests/unit/lms/services/lti_grading/_v13_test.py, tests/unit/lms/services/lti_grading/factory_test.py, tests/unit/lms/views/lti/basic_launch_test.py
For:
- https://github.com/hypothesis/lms/issues/5621
In this PR we'll just read the value from the LMS in LTI1.3. Out of scope is storing it in the DB, actually using this value and anything LTI 1.1 related.
Splinting the PRs this way we can focus on LMS compatibility in this PR
In all LMSes look in the `make dev` console for a line like:
```DEBUG [lms.views.lti.basic_launch:185][MainThread] Score maximum for F7373A6B-A469-426E-8F99-138CEF897E95-1632_6782: 88.0```
as `HypothesisEng.Teacher` launch  https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2424/View?ou=6782
as `blackboardteacher`  https://aunltd-test.blackboard.com/webapps/blackboard/content/contentWrapper.jsp?content_id=_2085_1&displayName=localhost+PDF+-+LTI1.3&course_id=_19_1&navItem=content&href=%2Fwebapps%2Fbl …
=> Read score maximum of assignments 

lms/resources/_js_config/__init__.py, lms/static/scripts/frontend_apps/config.ts, lms/views/lti/basic_launch.py, tests/unit/lms/resources/_js_config/__init___test.py, tests/unit/lms/views/lti/basic_launch_test.py
For:
- https://github.com/hypothesis/lms/issues/5621
This value might be null if we are not able to retrieve it from the source LMS.
Not using this value at all, just exposing it to enable any work on the front end.
=> Expose the scoreMaximum of the current assignment to the front end

lms/data_tasks/report/create_from_scratch/02_entities/04_assignments/01_create_view.sql
Using the domains from:
https://github.com/hypothesis/lms/blob/youtube-document-url/lms/static/scripts/frontend_apps/utils/youtube.ts#L13
This could in theory capture some URLs that don't point to a video but I reckon that in the context of analytics this is probably acceptable. The same is true for drive / one drive.
If we eventually store these  URLs in some sort of `youtube://` schema we'd probably want to keep this for backwards compatibility.
=> Breakdown YouTube assignments counts

lms/models/application_instance.py, lms/product/d2l/_plugin/misc.py, lms/product/plugin/misc.py, lms/services/assignment.py, lms/templates/admin/application_instance/show.html.jinja2, tests/unit/lms/product/d2l/_plugin/misc_test.py, tests/unit/lms/services/assignment_test.py
This option which is not used in production brought significant complexity needing two plugin entry points to enable it.
Remove this feature and the MiscPlugin methods that were needed for it.
This is not enabled for any school, filter https://lms.hypothes.is/admin/instances/ for  `desire2learn.create_line_item`
While this option is not used the problem is trying to solve is still an issue. 
The current work around is to create the line item manually: 
https://web.hypothes.is/help/grading-student-annotations-in-d2l/ this is the prefered solution now in all D2L versions, see: https://github.com/hypothesis/lms/issues/4699#issuecomment-1372599744
The current work for supporting deep linking in D2L could be another avenue to solve this issue with another approach as we'll be in control of …
=> Delete unused D2L setting `create_line_item`

lms/product/plugin/course_copy.py, tests/unit/lms/product/plugin/course_copy_test.py
Fixes: https://github.com/hypothesis/lms/issues/5645
See: https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#result-rows-act-like-named-tuples
This was not properly handled in the SQLA alchemy update.
This affects course copy
- Configure [localhost scratch Assignment (LTI 1.3)](https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2431/View) 
select any content and pick group sets until the list of group sets are listed. This will store them in the DB.
With this we get the original course group sets in the local DB.
- Launch a groups assignment over the copied course [LTI1.3: Group assignment](https://aunltd.brightspacedemo.com/d2l/le/content/6898/viewContent/2785/View?ou=6898).
It will fail with `web-https (stderr)   | TypeError: tuple indices must be integers or …
=> Fix usage of `find_group_set` to the new style of Result

lms/services/lti_grading/_v11.py, lms/services/lti_grading/_v13.py, lms/services/lti_grading/interface.py, lms/validation/_api.py, lms/views/api/grading.py, tests/unit/lms/services/lti_grading/_v13_test.py, tests/unit/lms/views/api/grading_test.py
- Launch [Gradable assignment (5 points)](https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/3348/View)
- Send a grade, it should work as before
- Make a change similar to:
```diff
diff --git a/lms/views/api/grading.py b/lms/views/api/grading.py
index 7a43bf6d6..fef22e72b 100644
--- a/lms/views/api/grading.py
+++ b/lms/views/api/grading.py
@@ -41,7 +41,7 @@ class GradingViews:
self.lti_grading_service.record_result(
self.parsed_params["lis_result_sourcedid"],
score,
-            comment=self.parsed_params["comment"],
+            comment=self.parsed_params.get("comment", "Very original comment"),
)
self.request.registry.notify(
LTIEvent(
```
- Send a grade again [Gradable assignment (5 points)](https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/3348/View)
- …
=> Pass grading comments along to the LTIA grading API

lms/static/scripts/frontend_apps/components/ValidationMessage.tsx, lms/static/scripts/frontend_apps/components/test/ValidationMessage-test.js
While sketching possible ways to display a comment box for grades (as part of https://github.com/hypothesis/product-backlog/issues/1472), I saw we were deriving a piece of local state from a prop in `ValidationMessage` component, which is actually unnecessary.
This PR removes that piece of state and directly uses the prop instead.
There should be no differences in behavior or UI. To ease testing it you can change this in `SubmitGradeForm`:
```diff
diff --git a/lms/static/scripts/frontend_apps/components/SubmitGradeForm.tsx b/lms/static/scripts/frontend_apps/components/SubmitGradeForm.tsx
index becb0d43..90f4827c 100644
--- a/lms/static/scripts/frontend_apps/components/SubmitGradeForm.tsx
+++ b/lms/static/scripts/frontend_apps/components/SubmitGradeForm.tsx
@@ -120,7 +120,7 @@ export …
```
=> Do not derive local state from prop in ValidationMessage

lms/models/application_instance.py, lms/product/canvas/_plugin/grouping.py, lms/templates/admin/application_instance/show.html.jinja2, tests/unit/lms/product/canvas/_plugin/grouping_test.py
For:
- https://github.com/hypothesis/support/issues/60
- https://github.com/hypothesis/private-issues/issues/65
With the new `strict_section_membership` mode we'll only display the section/s the instructor belongs to. With the setting off we'll list all sections available in the course.
The learner operation remains the same, it only list the sections the learner belongs to in all cases.
- Log in canvas as `eng+canvasteacher@hypothes.is`
- Test the existing behavior, launch [localhost (make devdata) HTML Assignment](https://hypothesis.instructure.com/courses/125/assignments/873)
You'll get a drop down with three sections
- Enable the new setting on http://localhost:8001/admin/instance/8/
- Launch [localhost (make devdata) HTML Assignment](https://hypothesis.instructure.com/courses/125/assi …
=> New canvas setting to manage sections membership

lms/models/application_instance.py, lms/templates/admin/application_instance/show.html.jinja2, lms/views/lti/basic_launch.py, tests/unit/lms/views/lti/basic_launch_test.py
- Switch to `dynamic-max-score` and follow the instructions there
- Switch to this branch `score-max-flag` and rebase `dynamic-max-score`
Check that these are back to a scale of 10:
https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/3348/View
https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/3349/View
- Enable the new setting
http://localhost:8001/admin/instance/106/ (hypothesis section, LMS grading scale)
These are back to the 5 and 100 scales:
https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/3348/View
https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/3349/View
=> Add a new AI setting to control the use of the LMS grading scale

lms/static/scripts/frontend_apps/components/GradingControls.tsx, lms/static/scripts/frontend_apps/components/InstructorToolbar.tsx, lms/static/scripts/frontend_apps/components/SubmitGradeForm.tsx, lms/static/scripts/frontend_apps/components/test/SubmitGradeForm-test.js
This PR is part of https://github.com/hypothesis/lms/issues/5621
Use the `maximumScore` from instructor toolbar config to determine the maximum score allowed in the grading bar, instead of using the hardcoded `10` value.
These assignments have different max scores:
* `5`: https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/3348/View
* `100`: https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/3349/View
> When opening those ☝🏼, you may see a LMS error that the file was not found. A quick workaround involves editing the assignment so that the files are fetched in your local LMS instance, and then going back without changing anything nor saving.
=> Pass `scoreMaximum` from instructor config to `SubmitGradeForm`

lms/views/api/grading.py, tests/unit/lms/views/api/grading_test.py
The new version of read_result always returns a value even if the score is None.
Take this into account and check the score property of the new structure.
- In `main` open https://hypothesis.instructure.com/courses/125/assignments/5335 as `eng+canvasstudent@hypothes.is`, make an annotation. You'll see in the logs a message like: `Grade already present, not recording submission. User ID: 11`
- Switch to this branch `submission-bugfix`, reload the assignment https://hypothesis.instructure.com/courses/125/assignments/5335, make another annotation
- Nothing will show in the logs and a new submission event will be created:
```docker compose exec postgres psql -U postgres -c "select timestamp, type from event join event_type on event.type_id = event_type.id order by event.id desc;"```
=> Fix bug around canvas submissions after grading API changes

tox.ini
https://docs.python.org/3/library/devmode.html#devmode
From https://docs.python.org/3/whatsnew/3.9.html#you-should-check-for-deprecationwarning-in-your-code
```
More generally, try to run your tests in the Python Development Mode
which helps to prepare your code to make it
compatible with the next Python version.
```
=> Enable PYTHONDEVMODE in the tests

lms/static/scripts/frontend_apps/utils/fetch.ts, lms/static/scripts/frontend_apps/utils/test/fetch-test.js
This is useful to replace the `useFetch` result, eg. following a local API call that updates it on the backend, without the delay that actually re-fetching the value would incur.
As with the `useFetch` API in general, this roughly follows the API of SWR (https://swr.vercel.app/docs/mutation).
Example of how this API could be used in `SubmitGradeForm` for example:
```diff
diff --git a/lms/static/scripts/frontend_apps/components/SubmitGradeForm.tsx b/lms/static/scripts/frontend_apps/components/SubmitGradeForm.tsx
index 6b31c606..3081e40b 100644
--- a/lms/static/scripts/frontend_apps/components/SubmitGradeForm.tsx
+++ b/lms/static/scripts/frontend_apps/components/SubmitGradeForm.tsx
@@ -61,6 +61,8 @@ export default function SubmitGradeForm({
student ? () => fetchGrade(student) : undefined
); …
```
=> Add `mutate` API to `useFetch` result

lms/static/scripts/frontend_apps/components/SubmitGradeForm.tsx, lms/static/scripts/frontend_apps/components/test/SubmitGradeForm-test.js, lms/static/scripts/frontend_apps/utils/test/use-warn-on-page-unload-test.js, lms/static/scripts/frontend_apps/utils/use-warn-on-page-unload.ts
> Closes #5672 
This PR adds a listener on window's `beforeunload`, so that we can warn instructors that accidentally try to leave the page with unsaved changes.
With this, if an instructor changed the student's grade and forgot to submit it, the browser will display a warning just before reloading the page or trying to navigate somewhere else, allowing the instructor to cancel it if it was a mistake.
Unfortunately, modern browsers do not allow for the warning confirm message to be customized, so we have to stick with default implementation.
See https://stackoverflow.com/a/38880926
1. Open an assignment, for example https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/3349/View
2. Click anywhere that would take you away (like a menu link). You should be redirected to the new …
=> Warn instructors about unsaved student grades when unloading page

lms/static/scripts/frontend_apps/components/GradingControls.tsx, lms/static/scripts/frontend_apps/components/SubmitGradeForm.tsx, lms/static/scripts/frontend_apps/components/test/GradingControls-test.js, lms/static/scripts/frontend_apps/components/test/SubmitGradeForm-test.js, package.json, yarn.lock
> Fixes https://github.com/hypothesis/lms/issues/5673
Detect unsaved changes during grading, and prompt instructor before changing to another student, to avoid loosing unsaved data.
This will be more important once we introduce the [grading comment](https://github.com/hypothesis/lms/pull/5643)
[Grabación de pantalla desde 2023-09-08 16-07-15.webm](https://github.com/hypothesis/lms/assets/2719332/ddb14704-0fdf-4eb5-a93a-a0d631a78fad)
- Should we enable this only if the grading comment FF is enabled? Maybe some consider this cumbersome otherwise.
- Decision: Let's enable it always.
- What should be the default prompt action? "Discard changes" or "continue editing"?
- Decision: Make "Continue editing" be the default, as it's the one where we ensure no data is lost. It is also the initially …
=> Display confirm prompt when changing active student without submitting grade

lms/services/jwt.py, tests/unit/lms/services/jwt_test.py
Not yet used but planned for the LMS metadata in annotations feature.
Implementation copied from https://github.com/hypothesis/h-vialib/blob/main/src/h_vialib/secure/encryption.py
=> Add new method to encrypt dicts as JWEs

lms/static/scripts/frontend_apps/components/GradingControls.tsx, lms/static/scripts/frontend_apps/components/SubmitGradeForm.tsx, lms/static/scripts/frontend_apps/components/test/GradingControls-test.js
This PR fixes a bug introduced in https://github.com/hypothesis/lms/pull/5686, where the value of `hasUnsavedChanges` runs out of sync if you change to another student and decide to discard changes.
When this happens, the flag is kept with value `true`, making the confirm dialog be displayed every time you change student, even if no changes were actually made.
Some context to understand how this of state works:
* We initialize `hasUnsavedChanges` to `false`.
* Every time the grade is edited, we check if it is different than the originally loaded grade and if so, `hasUnsavedChanges` is set to `true`.
* When the grade is submit, we reset `hasUnsavedChanges` to `false`.
* Every time `hasUnsavedChanges` value changes, we need to invoke an optional `onUnsavedChanges` prop callback with the new …
=> Fix unsaved changes not being properly tracked when changes are discarded

lms/models/application_instance.py, lms/resources/_js_config/__init__.py, lms/templates/admin/application_instance/show.html.jinja2, lms/views/lti/basic_launch.py, tests/unit/lms/resources/_js_config/__init___test.py, tests/unit/lms/views/lti/basic_launch_test.py
- Add general infrastructure to enable the LMS app to enable feature flags in the Hypothesis client on a per-application instance level. These flags will be added to the feature flags in the H user profile.
- Use this infrastructure to add an AI setting that enables the import/export features in the client
Part of https://github.com/hypothesis/client/issues/5803
----
**Testing:**
~~Check out this PR together with https://github.com/hypothesis/client/issues/5803 in the client repo.~~
1. Go to http://localhost:5000/admin/features and ensure the `import_annotations` and `export_annotations` features are not enabled for everyone
2. Load the assignment at https://hypothesis.instructure.com/courses/125/assignments/874. Check that the Import / Export UI is missing in the client.
3. Go to …
=> Add application instance setting to enable import/export

lms/services/digest.py, lms/templates/email/instructor_email_digest/subject.jinja2, tests/unit/lms/services/digest_test.py, tests/unit/lms/services/mailchimp_test.py
Fixes https://github.com/hypothesis/lms/issues/5656.
This changes the subject lines of instructor email digests from:
> There has been some activity in Hypothesis
To more informative subjects like:
> Hypothesis: 34 annotations from 16 students in 7 courses
> Hypothesis: 22 annotations from 5 students in 1 course
> Hypothesis: 3 annotations from 1 student in 2 courses
> Hypothesis: 2 annotations from 1 student in 1 course
> Hypothesis: one of your students made an annotation
1. Log in to https://hypothesis.instructure.com/ as the `eng+canvasteacher@hypothes.is` user and launch [localhost (make devdata) HTML Assignment](https://hypothesis.instructure.com/courses/125/assignments/873). This is to create the record of the instructor in your local DB. Also launch [a different assignment in a …
=> Improve digest email subjects

lms/templates/email/instructor_email_digest/body.html.jinja2, tests/unit/lms/services/mailchimp_test.py
Fixes https://github.com/hypothesis/lms/issues/5676. 
This changes the line under each course in the bodies of instructor email digests from:
> Students made 9 annotations in assignments.
> A student made an annotation in an assignment.
To:
> 3 students made 9 annotations in assignments.
> 1 student made 3 annotations in assignments.
> A student made an annotation in an assignment.
1. Log in to https://hypothesis.instructure.com/ as the `eng+canvasteacher@hypothes.is` user and launch [localhost (make devdata) HTML Assignment](https://hypothesis.instructure.com/courses/125/assignments/873). This is to create the record of the instructor in your local DB. Also launch [a different assignment in a different course](https://hypothesis.instructure.com/courses/124/assignments/885)
2. Log in to …
=> Include the number of students who annotated, in the bodies of instructor email digests

lms/static/scripts/frontend_apps/components/GradingControls.tsx, lms/static/scripts/frontend_apps/components/InstructorToolbar.tsx, lms/static/scripts/frontend_apps/components/SubmitGradeForm.tsx, lms/static/scripts/frontend_apps/components/test/InstructorToolbar-test.js, lms/static/scripts/frontend_apps/components/test/SubmitGradeForm-test.js, lms/static/scripts/frontend_apps/services/grading.ts, lms/static/scripts/frontend_apps/services/test/grading-test.js
> Part of https://github.com/hypothesis/product-backlog/issues/1472
Allow instructors to provide a grading comment for every student.
[Grabación de pantalla desde 2023-09-11 12-27-28.webm](https://github.com/hypothesis/lms/assets/2719332/b7764df7-d702-4714-bf2c-a86e166f4184)
1.Make sure you enable the feature flag as described in https://github.com/hypothesis/lms/pull/5649
2. Open https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/3349/View
3. The grading bar should show a new button next to the grade, which toggles a dropdown with a textarea that can be used to define a grading comment.
4. When you select a student, the icon will changed to a "filled" state if the comment is not empty. The comment should be prefilled if there was one for this student.
5. Saving the …
=> Add grading comment controls

.github/workflows/ci.yml, requirements/bddtests.in, requirements/bddtests.txt, requirements/functests.in, requirements/functests.txt, requirements/lint.txt, requirements/tests.in, requirements/tests.txt, tests/conftest.py, tox.ini
On CI we already use parallel GitHub Actions jobs to run the different checks in parallel (formatting, lint, tests, functests, ...). Locally `make sure` uses `tox --parallel` to run each of these in parallel. This PR uses [pytest-xdist](https://github.com/pytest-dev/pytest-xdist) to also run _the unit tests themselves_ in parallel in multiple processes (one process for each CPU core) whenever you run `make test`, `make sure`, or the _Tests_ job on CI.
This should make things significantly faster both locally and on CI, especially because the unit tests are by far the slowest part of CI.
A couple of tricks are required to get this working: we add [pytest-cov](https://github.com/pytest-dev/pytest-cov) because it has builtin support for pytest-xdist (combining the coverage from the different …
=> Speed up LMS's unit tests by running them in parallel

lms/static/scripts/frontend_apps/components/GradingComment.tsx
> Depends on https://github.com/hypothesis/lms/pull/5700
> This PR addresses points 2 and 4 of https://github.com/hypothesis/lms/pull/5691#issuecomment-1715779932
Update the grading comment popover component so that its top-level component is a `Dialog` instead of a `div[role="dialog"]`.
This provides some behaviors out of the box, including:
* Close on click away
* Close on pressing `Escape`
* Restore focus on close
* Focus the textarea when opened
=> Comment popover dialog

lms/static/scripts/frontend_apps/components/GradingComment.tsx, lms/static/scripts/frontend_apps/components/GradingCommentButton.tsx, lms/static/scripts/frontend_apps/components/SubmitGradeForm.tsx, lms/static/scripts/frontend_apps/components/test/GradingCommentButton-test.js, lms/static/scripts/frontend_apps/components/test/SubmitGradeForm-test.js
> This PR addresses points 1, 2 and 4 from https://github.com/hypothesis/lms/pull/5691#issuecomment-1715779932
This PR extracts everything related with the grading comment from `SubmitGradeForm` into a separated `GradingCommentButton` component.
This way, `SubmitGradeForm` has less responsibilities to handle, and all state management around the comment can be encapsulated on a component of its own.
- I initially thought only the popover part should be extracted, keeping the button as a "trigger" inside `SubmitGradeForm`. However, I ended up extracting everything that needs to render when `allowComments` is `true`, because it allowed to move all the state pieces and hooks away from `SubmitGradeForm`.
I did create an individual `CommentPopover` component though, but it's "private" inside …
=> Extract everything related with the comment to its own component

.github/workflows/ci.yml
Enable larger GitHub Actions runners for tests and lint. The new
`runs-on` values match the name of a larger runners group that I've
created in the `hypothesis` GitHub organization.
=> Enable larger runners for tests and lint

.github/workflows/tasks.yml
=> Remove 'staging' from tasks.yml

lms/resources/_js_config/__init__.py, lms/services/application_instance.py, lms/services/lti_h.py, tests/unit/lms/resources/_js_config/__init___test.py, tests/unit/lms/services/application_instance_test.py, tests/unit/lms/services/lti_h_test.py
For:
- https://github.com/hypothesis/lms/issues/4381
Just few AI have this disabled and we've seen some launches from them.
This launches completely fail and result in a blank screen.
This commit doesn't remove the concept from the DB to keep track of which instances have it disabled in case we want to re-enable this.
Alternatively, if no costumers contact us about this we can completely remove the concept from the DB.
- Launch https://hypothesis.instructure.com/courses/123/assignments/865
compare the result in `main` (a blank screen) and in this branch:
Not the best dialog in the world but it does mention the issue and has a directly link to contact support.
=> Emit an error code for AIs with provisioning disabled

lms/tasks/email_digests.py, tests/factories/__init__.py, tests/factories/event.py, tests/unit/lms/tasks/email_digests_test.py
SQL soup testing:
[This is the new query, complete with dates based on today's task](https://report.hypothes.is/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiIgIFdJVEggY2FuZGlkYXRlX2NvdXJzZXMgQVMgXG4gIChTRUxFQ1QgZXZlbnQuY291cnNlX2lkIEFTIGNvdXJzZV9pZCBcbiAgRlJPTSBldmVudCBKT0lOIGFwcGxpY2F0aW9uX2luc3RhbmNlcyBPTiBhcHBsaWNhdGlvbl9pbnN0YW5jZXMuaWQgPSBldmVudC5hcHBsaWNhdGlvbl9pbnN0YW5jZV9pZCBcbiAgV0hFUkUgZXZlbnQudGltZXN0YW1wID49ICcyMDIzLTA5LTE4VDA1OjAwOjAwJyBBTkQgZXZlbnQudGltZXN0YW1wIDw9ICcyMDIzLTA5LTIwVDA1OjAwOjAwJyBBTkQgKChhcHBsaWNhdGlvbl9pbnN0YW5jZXMuc2V0dGluZ3MgLT4naHlwb3RoZXNpcycpIC0-PiAnaW5zdHJ1Y3Rvcl9lbWFpbF9kaWdlc3RzX2VuYWJsZWQnID0gJ3RydWUnKVxuICApXG4gICBTRUxFQ1QgRElTVElOQ1QgXCJ1c2VyXCIuaF91c2VyaWQgXG4gICBGUk9NIFwidXNlclwiIEpPSU4gYXNzaWdubWVudF9tZW1iZXJzaGl …
=> Reduce the number of email digest recipient candidates

lms/services/h_api.py, tests/unit/lms/services/h_api_test.py
Support for `fields` has been removed from H, stop sending it.
Removed from H in https://github.com/hypothesis/h/pull/8170
=> Stop sending `fields` to the annotation bulk API in H

.github/dependabot.yml
This will reduce the overall volume of PRs and conflicts between PRs for updating frontend dependencies. The configuration was copied from the client repo.
We don't currently use Sentry in the frontend in this repo, but I left the configuration on there because I expect we will use it in future.
Assuming this works as expected, I'll roll it out to other projects that have significant frontend components.
=> Enable grouped updates for frontend dependencies

lms/resources/_js_config/file_picker_config.py, lms/routes.py, lms/services/canvas_api/_pages.py, lms/services/canvas_api/client.py, lms/services/canvas_api/factory.py, lms/static/scripts/frontend_apps/config.ts, lms/views/api/canvas/authorize.py, lms/views/api/canvas/pages.py, tests/unit/lms/resources/_js_config/file_picker_config_test.py, tests/unit/lms/services/canvas_api/_pages_test.py, tests/unit/lms/services/canvas_api/client_test.py, tests/unit/lms/services/canvas_api/factory_test.py, tests/unit/lms/views/api/canvas/authorize_test.py, tests/unit/lms/views/api/canvas/pages_test.py
- Enable pages over:
http://localhost:8001/admin/instance/8/
- Use https://github.com/hypothesis/lms/pull/5717 (`canvas-pages-proxy) to get the FE bits needed to test the backend, you'll have to rebase this branch there.
- Re-configure the assignment over:
https://hypothesis.instructure.com/courses/125/assignments/5142/edit?name=Testing+creation&due_at=null&points_possible=0
- Pick Canvas Pages, it should display the pages in over: 
https://hypothesis.instructure.com/courses/125/pages
=> Proxy listing canvas pages enpoint

lms/templates/api/canvas/page.html.jinja2, lms/views/api/canvas/pages.py, tests/unit/lms/views/api/canvas/pages_test.py
Pretty basic HTML page with just the title and the body.
- Launch https://hypothesis.instructure.com/courses/125/assignments/5142
It looks similar to the vession in `main` but it does include the title now.
=> Return a template for canvas pages instead of a raw Response

lms/services/canvas_api/_pages.py, lms/templates/api/canvas/page.html.jinja2, lms/views/api/canvas/pages.py, tests/unit/lms/views/api/canvas/pages_test.py
Using the ID version of the page in canvas itself which Canvas redirects to the version using the slug.
This is the more obvious URL for us to use but the most important aspect is that is stable rather than actually being a real URL.
- Launch https://hypothesis.instructure.com/courses/125/assignments/5142
- Make an annotation
- Reload the page
- The annotation is still there
-  The canonical URL is href="https://hypothesis.instructure.com/courses/125/pages/1392 which takes you, after a redirect, to https://hypothesis.instructure.com/courses/125/pages/test-page
=> Include a canonical URL for canvas pages

lms/views/lti/oidc.py
Some LMSes don't send this value (Sakai) and ultimately is the LMS that's going to validate the value in the callback. We'll forward the value from the LMS even it's `None`.
Sanity check a LTI1.3 launch in some LMS: https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2424/View?ou=6782
=> Mark lti_message_hint as not required

lms/services/canvas_api/_pages.py, lms/services/canvas_api/factory.py, tests/unit/lms/services/canvas_api/_pages_test.py, tests/unit/lms/services/canvas_api/factory_test.py
As we do with other LMS-backed content (files in Canvas, D2L and Blackboard) we store a reference to the page in the file table for:
- Bookkeeping, being able to count the number of documents we've have seen.
- Debugging of live issues.
- And, more importantly, support our course copy process, when, once we have records of the documents in the DB we can compare the old course ones with the ones in the new course.
We store these now in "File", we should consider a future refactor to rename this table/model/service to something more generic like "Document".
- https://github.com/hypothesis/lms/pull/5717/commits needs to be merged or rebase here to make testing easiser.
- Try to reconfigure using canvas pages: https://hypothesis.instructure.com/courses/125/assignments/5142/edit?return_to=https …
=> Store references to canvas pages in the DB

lms/resources/_js_config/__init__.py, lms/routes.py, lms/views/api/canvas/pages.py, tests/unit/lms/resources/_js_config/__init___test.py, tests/unit/lms/views/api/canvas/pages_test.py
Instead of using a URL parameter use the value from LTIUser, which is signed.
Small simplification before starting the course copy work for Canvas pages. We should be using these values more often but let's start by not introducing new instances of the old method of passing assignment.
- Sanity check, launch: https://hypothesis.instructure.com/courses/125/assignments/5142
=> Don't send the assignment id on the URL for pages endpoint

lms/models/grouping.py, tests/unit/lms/models/grouping_test.py
Small PR to add these. It might lack a bit of context on the general course copy process but that PR is getting to big.
This is mostly a copy pasted of existing methods for files & groups and a small refactor to make it less of an actual copy paste.
=> Add new method to allow storing page mappings between courses

lms/resources/_js_config/__init__.py, tests/unit/lms/resources/_js_config/__init___test.py
Expose just the `assignment_id` as part of the metadata to be added to all annotations created in the LMS context.
For now the client will just use this information for new annotations (POST /api/annotation) to fill this information for now on.
This is enough for the immediate need, email digest.
We'll have to revisit this once we want to use this information for other proposes, for example retrieving annotations by group + assignment (or group + document + assignment) instead of just group + document. 
Needs: 
https://github.com/hypothesis/h/pull/8175
https://github.com/hypothesis/h/pull/8182
=> Generate annotation metadata and expose it to the client config

lms/views/api/canvas/pages.py, tests/unit/lms/views/api/canvas/pages_test.py
Not much more to add, basic alphabetically sorting based on the page's title.
=> Sort the pages returned by the list endpoint alphabetically

lms/static/scripts/frontend_apps/components/DocumentList.tsx, lms/static/scripts/frontend_apps/components/test/DocumentList-test.js
As suggested by a couple people [in slack](https://hypothes-is.slack.com/archives/C07NXBDNW/p1696949673934889), this PR changes the icon we use for LMS (Canvas) pages documents in the `DocumentList`.
Before:
After:
=> Use FileGeneric icon for LMS page documents

lms/static/scripts/frontend_apps/components/ContentSelector.tsx
In order to know which link to use, I visited the one we have for Canvas files, and the same knowledge base page had references to pages documentation.
One of them is about creating a new page, which seems like the most sensible option.
=> Add help link on how to create Canvas pages

gulpfile.mjs, lms/assets.ini, lms/static/styles/canvas_pages/canvas_pages.scss, lms/templates/api/canvas/page.html.jinja2
Add a stylesheet for the HTML content of Canvas Pages assignments. For reasons outlined at the top of canvas_pages.scss, this commit uses a re-implementation of the styling that Canvas provides for Pages. This includes the Lato font, imported via an Adobe TypeKit project [1] and styling for all of the elements that can be created using Pages' WYSIWYG editor.
Canvas Pages re-use "common" stylesheets that include > 500KB of styles for other parts of the UI, which in principle Canvas Pages HTML could reference, although we assume virtually no pages will.
Fixes https://github.com/hypothesis/lms/issues/5746
[1] https://fonts.adobe.com/fonts/lato. This is the native "home" of the Lato font. To get the typekit.net URL referenced in this commit I created a minimal Web Project and added all the …
=> Add stylesheet for Canvas Pages assignments

lms/views/admin/email.py, tests/unit/lms/views/admin/email_test.py
Missed in previous commit to adapt to the change in the bulk annotation API from updated to created filtering.
=> Change missed updated/created parameters

lms/product/canvas/_plugin/course_copy.py, lms/product/plugin/course_copy.py, lms/views/api/canvas/pages.py, tests/unit/lms/product/canvas/_plugin/course_copy_test.py, tests/unit/lms/views/api/canvas/pages_test.py
Course copy is a feature that most LMS have that allows to... well, copy a course. This is useful to prepare courses for new terms.
In general the content of the course gets copied alongside the assignments. Our assignments that point to a document in the LMS, lets day "page id 1", will still point to that document, the old course one, in the new course. Without any intervention that will make the assignment load to fail.
To fix this issue we try to find a equivalent page in the new course, like we do files. We'll base this on the title. 
Once we found the new page, we store that information in the DB so consequent launches don't need to find that information again.
- Launch https://hypothesis.instructure.com/courses/606/assignments/5710 in `main`
You'll get an error 
- Switch to this …
=> Support course copy for Canvas pages

lms/services/exceptions.py, lms/static/scripts/frontend_apps/components/LaunchErrorDialog.tsx, lms/static/scripts/frontend_apps/components/test/LaunchErrorDialog-test.js, lms/static/scripts/frontend_apps/errors.ts, lms/static/scripts/ui-playground/components/ErrorComponents.tsx, tests/unit/lms/views/api/d2l/files_test.py
- (Enable pages locally or self-merge https://github.com/hypothesis/devdata/pull/99 & `make devdata`)
- Login to canvas with 'eng+coursecopystudent`.
- Remove any info that could "solve" course copy issues: 
`docker compose exec postgres psql -U postgres -c "truncate grouping, file cascade"`
- Launch https://hypothesis.instructure.com/courses/607/assignments/5815
- Marvel at the new error message. Adapted from the files ones. We can extended it, include links etc, as we see any issues in the future.
=> Add simple message to handle canvas_page_not_found_in_course

lms/services/digest.py, tests/unit/lms/services/digest_test.py
I think this is a better naming convention for these local dataclasses
and it's consistent with the upcoming `AssignmentInfo` class which
wouldn't make sense as `UnifiedAssignment` because there's no
unification happening.
=> Rename `UnifiedCourse` -> `CourseInfo` and `UnifiedUser` -> `UserInfo`

lms/static/scripts/frontend_apps/components/StudentSelector.tsx, lms/static/scripts/frontend_apps/components/test/StudentSelector-test.js, lms/static/scripts/ui-playground/components/ToolbarPage.tsx, package.json, yarn.lock
> Requires https://github.com/hypothesis/frontend-shared/pull/1330
This PR replaces `Select` with `SelectNext` in the `StudentSelector`.
Before:
After:
`SelectNext` needs to have a "fixed" size to make sure it does not resize when selected option changes, so I have changed its sizes to be:
* 20rem for extra large devices (this was already like that)
* 16rem for large devices
* 12rem for medium devices
* full (the default) for small and extra small devices, as the components collapse in a column there.
[Grabación de pantalla desde 2023-10-18 11-56-35.webm](https://github.com/hypothesis/lms/assets/2719332/34bbc54c-a3d7-4b4a-b3c3-f293ac6c352a)
Open any assignment and verify students can be selected as with the regular select.
=> Use SelectNext for StudentSelector

lms/views/api/canvas/authorize.py, tests/unit/lms/views/api/canvas/authorize_test.py
The error message shown to users when authorization fails due to missing scopes, was missing scopes for folders and pages:
In this PR I have continued the current behavior of listing all the scopes our app _can_ use in the error, although that may create some confusion because this message could reference scopes for in-development features that we won't actually use unless the feature is turned on.
See https://hypothes-is.slack.com/archives/C4K6M7P5E/p1697628340572009
=> Add folders and pages scopes to Canvas scopes error

lms/views/api/canvas/authorize.py, tests/unit/lms/views/api/canvas/authorize_test.py
`JSConfig.enable_oauth2_redirect_error_mode` expects a `List[str]` but was being passed a `set[str]`. This caused an error later when attempting to JSON-serialize the value.
This was a regression introduced by https://github.com/hypothesis/lms/commit/5e86e5f958e2b03002cef31b95739b457fe50347.
Fixes https://hypothesis.sentry.io/issues/4576135028/?project=259908
=> Fix crash when presenting Canvas scope error message

tests/factories/application_instance.py, tests/unit/lms/services/application_instance_test.py
Give test application instances from the `ApplicationInstance` factory a
randomly generated `tool_consumer_instance_guid` by default, instead of
`None`.
I think application instances usually have a GUID most of the time, so
this makes sense as a factory default.
=> Give test application instances a GUID by default

lms/resources/_js_config/__init__.py, tests/unit/lms/resources/_js_config/__init___test.py
Add the assignment's `tool_consumer_instance_guid` to the metadata that the LMS app passes to the client for storage with annotations in h.
This is going to make it much easier to generate assignment data for digest emails in https://github.com/hypothesis/lms/pull/5755.
Also rename `assignment_id` to `resource_link_id` in the metadata so that it matches the name used for this field in the LMS app's code and DB, and restructure the metadata so that `resource_link_id` and `guid` are grouped together in an `assignment` sub-dict.
=> Add GUID to LMS annotation metadata

lms/models/lti_user.py, tests/unit/lms/models/lti_user_test.py
For:
- https://github.com/hypothesis/support/issues/46
That issue describes a problem for when someone that's both an admin and a student gets inconsistent behaviour.
This doesn't necessarily solve that but I reckon will make it more rare fixing a bug where we identify someone as an admin when they are not in fact and admin **in the current context**.
See discussion over: https://hypothes-is.slack.com/archives/C2BLQDKHA/p1698048084437489
=> Only consider admins roles that are sytem or course wide

lms/static/scripts/frontend_apps/components/FilePickerApp.tsx, lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
This PR ensures product's `groupsEnabled` setting is taken into consideration when editing an assignment, in order to not show the groups-related options if it is `false`.
This covers both if the LMS does not support groups, or if it does but they were disabled.
> **Note**
> This PR is easier to review [hidding whitespaces](https://github.com/hypothesis/lms/pull/5793/files?w=1)
1. Check out this branch.
2. Open an assignment in a non-Canvas LMS, for example https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/3348/View.
3. Go to http://localhost:8001/admin/instance/{instance_id}/ and disable groups for the LMS you choose.
4. Reload the assignment and click "Edit". You should not see any reference to groups:
5. Enable groups again and repeat previous step. You should see …
=> Take into consideration `groupsEnabled` flag in order to show groups config

lms/pshell.py
Pre-import the `lms.services` package into `make shell`'s Python shell environment as both `services` and `s`. This just allows you to use services from `make shell` more conveniently, without having to import them yourself. For example:
```python
$ make shell
>>> request.find_service(s.EmailUnsubscribeService).unsubscribe_url("***", "instructor_digest")
'http://localhost:8001/email/unsubscribe?token=***'
```
Also add `t` as an alias for `tasks`, like we have `m` for `models`, `f` for `factories` and `s` for `services`.
=> Add `s`, `services` and `t` to `make shell`'s Python environment

lms/static/scripts/frontend_apps/components/ChapterList.tsx
This avoids an unnecessary re-render of the DataTable if the chapters haven't changed, which is important if the book has a lot of pages or chapters. For this change to work requires https://github.com/hypothesis/frontend-shared/pull/1357.
=> Memo chapter list columns

lms/static/scripts/frontend_apps/components/ChapterList.tsx, lms/static/scripts/frontend_apps/components/ContentSelector.tsx, lms/static/scripts/frontend_apps/components/DocumentList.tsx, lms/static/scripts/frontend_apps/components/ErrorDisplay.tsx, lms/static/scripts/frontend_apps/components/FilePickerApp.tsx, lms/static/scripts/frontend_apps/components/GroupConfigSelector.tsx, lms/static/styles/_base.scss, package.json, tailwind.config.mjs, yarn.lock
Take advantage of rounded corner capabilities from [frontend-shared](https://github.com/hypothesis/frontend-shared/pull/1289), and add missing rounded corners where needed for consistency.
The visual changes are relatively small, so I'm adding this with no feature flags.
> **Note**
> This PR is easier to review ignoring whitespaces https://github.com/hypothesis/lms/pull/5815/files?w=1
Sanity check an assignment, including:
- Grading bar, with and without comment enabled.
- Content picker (edit and create)
- Different content types.
- Errors (authorization and such).
Closes #5811
=> Add rounded corners to UI components

lms/views/exceptions.py
A few of these don't produce any logging in local development making debugging them tricky.
Added an explicit logging here. Not sure if this would duplicate logging in a production environment. If that the case we can change this from `exception` to `debug`.
=> Log unexpected exceptions in exception view

lms/services/vitalsource/_client.py, lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/ChapterList.tsx, lms/static/scripts/frontend_apps/components/test/ChapterList-test.js, tests/unit/lms/services/vitalsource/_client_test.py
Table of Contents entries in VitalSource API responses are hierarchical. Add an indentation to rows in our TOC list to reflect this.
Example using [this VitalSource book](https://bookshelf.vitalsource.com/reader/books/VST-DOCS-EPUB3IMPLEMENTGUIDE/epubcfi/6/2[%3Bvnd.vst.idref%3Drefid-e5be9e41-3f23-4c79-a458-710c920d6563]!/4):
Part of https://github.com/hypothesis/lms/issues/5821.
=> Reflect hierarchy of table-of-contents entries in VitalSource chapter list

lms/static/scripts/frontend_apps/components/ChapterList.tsx
I think the term "Location" was an attempt to be general in case the values were not actually pages. However the VitalSource API field from which we get these values, the VS EPUB publishers guide [1] and the VS UI all use the term "page", and the intent is that the values correspond to page numbers in a physical version of the book.
[1] https://www.vitalsource.com/products/vitalsource-epub3-implementation-guide-vitalsource-vvstdocsepub3implementguide
=> Change page column heading from "Location" to "Page"

lms/product/canvas/_plugin/misc.py, tests/unit/lms/product/canvas/_plugin/misc_test.py
Fallback to custom params for deep linking configuration in Canvas
In canvas we have historically send the deep linking (DL) configuration
parameters as query parameters in the return URL.
When we started using DL in D2L we instead used LTI custom params which
can be arbitrary JSON which is more ergonomic than having to worry
about encoding issues in URLs.
Before this commit, and as part of the D2L work, we always send the
configuration as custom parameters even if never read them in Canvas,
relying only the URL.
Now, as part of the work with VitalSource we found that URL parameters
are not proxied in their LTI integration.
With this commit we continue reading the parameters from the URL as the
first option, for all existing Canvas installations, but we fallback to
custom parameters, for …
=> Fallback to custom params for deep linking configuration in Canvas

lms/tasks/email_digests.py
Increase the rate limit of the `send_instructor_email_digests()` Celery task. This is because I want to try decreasing the task's `batch_size` (see https://github.com/hypothesis/h-periodic/pull/385) and correspondingly increasing its `rate_limit` to see what effect that has on performance, with an eye towards potentially removing the batching feature altogether in order to simplify adding future features to this code.
=> Increase `send_instructor_email_digests` rate limit

lms/migrations/versions/14e959ea6f99_role_overrides.py
```
dev run-test-pre: PYTHONHASHSEED='3115633096'
INFO  [alembic.runtime.migration] Running upgrade 0c52a13c6cad -> 14e959ea6f99, Create the role_overrides table.
```
```
tox -e dev --run-command 'alembic downgrade -1'
dev run-test-pre: PYTHONHASHSEED='9935878'
dev run-test: commands[0] | alembic downgrade -1
INFO  [alembic.runtime.migration] Context impl …
```
=> Migration for the LTIRoleOverride model

lms/models/application_instance.py, lms/resources/_js_config/file_picker_config.py, lms/templates/admin/application_instance/show.html.jinja2, tests/unit/lms/resources/_js_config/file_picker_config_test.py
Add a feature flag that controls whether users can specify a page range for an assignment, as opposed to just a start point from the table of contents.
Part of https://github.com/hypothesis/lms/issues/5808
=> Add feature flag for enabling VitalSource page range selection

lms/routes.py, lms/services/h_api.py, lms/services/organization.py, lms/templates/admin/base.html.jinja2, lms/templates/admin/organization.html.jinja2, lms/templates/admin/organization.usage.html.jinja2, lms/views/admin/organization.py, tests/unit/lms/services/h_api_test.py, tests/unit/lms/services/organization_service_test.py, tests/unit/lms/views/admin/organization_test.py
The main goal of this PR is two have method to generate usage reports that doesn't involve any other scripts or untested SQL.
Once deployed the data can be compared against the number over https://docs.google.com/spreadsheets/d/1kCG9OCU-tybqtkJmdMWx_75DUqgpNwrvdq0FfU-nqrg/edit#gid=0
- Checkout this branch over in H https://github.com/hypothesis/h/pull/8275
- Open a couple of windows (normal and incognito?) as both `eng+canvasteacher@hypothes.is` and `eng+canvasstudent@hypothes.is`
- Make annotations as both users in this two separate assignments that belong to two different courses:
- In the admin pages go to the organization: http://localhost:8001/admin/org/1, …
=> Generate usage reports in the admin pages

lms/tasks/email_digests.py
Reduce the rate-limit of the `send_instructor_email_digests()` task from `30/m` to `10/m`. This is a desperate attempt to prevent problems that we've seen this morning with a small number of instances of this task failing. We increased the task's throughput yesterday and this morning it started failing. We've seen no evidence that the higher throughput is the cause for the failures, but we don't have any better ideas so let's try reducing the throughput.
Slack thread: https://hypothes-is.slack.com/archives/C0LUWQQJJ/p1700644122131399
=> Reduce `send_instructor_email_digests` rate limit

lms/services/__init__.py, lms/services/digest.py, lms/services/email_preferences.py, lms/views/email.py, tests/unit/lms/services/digest_test.py, tests/unit/lms/services/email_preferences_test.py, tests/unit/lms/views/email_test.py, tests/unit/services.py
This is because we're getting to be adding a `preferences_url()` method and other public methods to this service, it's not going to be just for unsubscribes anymore. Also, the service will be changed to read and write the new `EmailPreferences` model and the current `EmailUnsubscribe` model will eventually be removed.
=> Rename `EmailUnsubscribeService` to `EmailPreferencesService`

lms/routes.py, lms/services/vitalsource/_client.py, lms/services/vitalsource/model.py, lms/services/vitalsource/service.py, lms/views/api/vitalsource.py, tests/unit/lms/services/vitalsource/_client_test.py, tests/unit/lms/services/vitalsource/model_test.py, tests/unit/lms/services/vitalsource/service_test.py, tests/unit/lms/views/api/vitalsource_test.py
Make changes to how VS book locations are represented in the backend to support the upcoming page-range selection feature. Also add an API to generate VS document URLs. This is not currently used by the frontend.
- Support specifying the start location of a VS assignment as a page number rather than a CFI. For certain books this allows specifying a more precise starting point, compared to using CFIs that correspond to table-of-contents entries.
- Add an API for the frontend to generate the document URL for a VitalSource assignment.
Previously the frontend received the document URL from entries in the table of contents API response. We are now adding the ability to configure a page range for an assignment, so it will no longer be possible to enumerate all document URLs in the TOC response. …
=> Add backend support for page ranges in VitalSource assignment URLs

lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/BookPicker.tsx, lms/static/scripts/frontend_apps/components/ContentSelector.tsx, lms/static/scripts/frontend_apps/components/test/BookPicker-test.js, lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js, lms/static/scripts/frontend_apps/config.ts, lms/static/scripts/frontend_apps/services/test/vitalsource-test.js, lms/static/scripts/frontend_apps/services/vitalsource.ts
When the VitalSource page ranges feature is enabled, display two new inputs in the chapter/page selection form to enter
the start and end page for the assignment. When the selection is confirmed, make a call to the backend API to generate a document URL that corresponds to the selected chapter or page range.
Partially implements https://github.com/hypothesis/lms/issues/5808. This does include the page range input, but not multi-selection in the tree view.
**Testing:**
1. Enable the "page ranges" feature for VitalSource for the instance you are testing with
2. Start creating a new Hypothesis assignment and select VitalSource as the content type
3. Enter a book URL and press Select
You should see two new inputs in the content selection form:
In this UI you can either select a single entry …
=> Add page range inputs to VitalSource book picker

lms/security.py, lms/views/admin/application_instance/create.py, lms/views/admin/application_instance/downgrade.py, lms/views/admin/application_instance/move_organization.py, lms/views/admin/application_instance/search.py, lms/views/admin/application_instance/show.py, lms/views/admin/application_instance/update.py, lms/views/admin/application_instance/upgrade.py, lms/views/admin/email.py, lms/views/admin/lti_registration.py, lms/views/admin/organization.py, lms/views/admin/role.py, tests/unit/lms/security_test.py
Currently anyone with a company's email is considered an ADMIN. Changing that to STAFF.
This would make adding a more privileged "ADMIN" permissions easier to review.
=> Rename existing ADMIN permission to STAFF

lms/templates/admin/application_instance/show.html.jinja2, lms/templates/admin/base.html.jinja2, lms/templates/admin/organization/show.html.jinja2
THe current rule was hidden the Hierarchy section of organizations as it uses <li> elements.
Add a new class to the tab's li elements and use that in the selector.
- Go over http://localhost:8001/admin/org/1 and check that at least one link shows up in the hierarchy section at the bottom.
=> Use a more concrete CSS selector for tab contents

lms/views/admin/application_instance/create.py, lms/views/admin/application_instance/downgrade.py, lms/views/admin/application_instance/move_organization.py, lms/views/admin/application_instance/update.py, lms/views/admin/application_instance/upgrade.py, lms/views/admin/lti_registration.py, lms/views/admin/organization.py
**We need to add the right users to the prod environments before deploying this.**
- Go to the admin pages, check that you can search for AI/Orgs and open them
- Try to write anything, you'll get "You don't have permission" alert.
- Get [this branch](https://github.com/hypothesis/devdata/pull/100) of devdata changes and apply them with 
`tox -e dev --run-command 'python bin/make_devdata -u file:///PATH_TO_DEV_DATA_CHECKOUT_WITH_THAT_BRANCH'`
(or just go ahead and merge that and run regular `make devdata`)
- Try again, you should be able to access the restricted paths.
=> Require admin permission on sensitive admin views

lms/services/vitalsource/service.py, tests/unit/lms/services/vitalsource/service_test.py
Support vitalsource:// URLs with the start location specified as a page number rather than a CFI in `get_book_reader_url`.
I have confirmed with VS [1] that we can rely on the `/page/{number}` launch URL.
When combined with https://github.com/hypothesis/lms/pull/5849, it becomes possible to configure a VS assignment with a page range rather than a chapter URL, and have the book reader open at the specified page when the assignment is launched.
[1] https://vitalsource.slack.com/archives/C01208U1A2F/p1700227038259109
=> Support generating VS book reader URLs when start is a page number

lms/static/scripts/frontend_apps/components/BookSelector.tsx, lms/static/scripts/frontend_apps/components/URLPicker.tsx
This removes the only remaining usages of deprecated frontend-shared symbols, in preparation for v7.0.0
=> Replace deprecated  prop with

lms/services/__init__.py, lms/services/email_preferences.py, lms/services/user_preferences.py, tests/factories/__init__.py, tests/factories/user_preferences.py, tests/unit/lms/services/email_preferences_test.py, tests/unit/lms/services/user_preferences_test.py, tests/unit/services.py
Add two services for working with the new `UserPreferences` model:
1. `UserPreferencesService` is a generic service for getting and setting a user's preferences
2. The existing `EmailPreferencesService` gains new `get_preferences()` and `set_preferences()` methods. These are restricted to getting and setting a user's email preferences only. They're built on top of the new `UserPreferencesService`.
These services just encapsulate some preferences-related logic that I didn't want to put in the views directly. For example we may have multiple preferences views in future--perhaps both an HTML form for getting and setting a user's preferences, and a JSON API. Both views can use these services.
Usage
-----
```python
>>> user_preferences_svc = request.find_service(s.UserPreferencesService)
>>> # …
```
=> Add user preferences services

lms/views/admin/organization.py
This endpoint is the whole reason to add the new ADMIN permission. This one should be allowed for all STAFF members, not only admins.
=> Require STAFF permission for the usage endpoint

lms/static/scripts/frontend_apps/components/BookPicker.tsx, lms/static/scripts/frontend_apps/components/test/BookPicker-test.js, lms/static/scripts/frontend_apps/utils/test/vitalsource-test.js, lms/static/scripts/frontend_apps/utils/vitalsource.ts
Validate that page ranges entered in the picker are valid, but in a tolerant way. We accept non-numeric page numbers, because books do use them for some pages, and don't check that the end page number is in-bounds, because we don't get the final page number from the API.
=> Add tolerant validation of page ranges in VitalSource picker

lms/static/scripts/frontend_apps/components/BookPicker.tsx
Ensure the heading reads as "Choose one chapter or a page range" instead of "Choose a range of chapters or pages".
See https://hypothes-is.slack.com/archives/C4K6M7P5E/p1701195297687609?thread_ts=1701191809.129689&cid=C4K6M7P5E
=> s/Choose chapter/Choose a chapter

lms/services/digest.py, lms/services/mailchimp.py, tests/unit/lms/services/digest_test.py, tests/unit/lms/services/mailchimp_test.py
Depends on https://github.com/hypothesis/lms/pull/5857.
Begin recording additional data in the `TaskDone.data` column that's
going to be needed in future when we want each user's email digest to
count annotations from *the time that particular user's last email
digest counted annotations until* rather than just from a fixed 24hr
period.
The extra data that we're recording is:
1. The type (`"instructor_email_digest"`), to allow easily filtering for
only this type of `TaskDone` entry
2. The time (`created_before`) up until which the email that was sent
counted annotations until
=> Record extra data in the `TaskDone.data` column

lms/migrations/versions/68f4e83eec70_copy_email_unsubscribe_to_user_.py
Shouldn't be merged before https://github.com/hypothesis/lms/pull/5871.
Testing
=======
Create two `email_unsubscribe` rows and a `user_preferences` row corresponding to one of the `email_unsubscribe` rows:
```sql
$ make sql
postgres=# insert into email_unsubscribe (h_userid,tag) values ('h_userid1', 'tag1');
postgres=# insert into email_unsubscribe (h_userid,tag) values ('h_userid2', 'tag2');
insert into user_preferences (h_userid,preferences) values ('h_userid2', '{"instructor_email_digests.days.mon": true}'::jsonb);
```
Now run the migration:
```terminal
$ make db args='upgrade +1'
INFO  [alembic.runtime.migration] Running upgrade 6d72ce7efdeb -> 68f4e83eec70, Copy email_unsubscribe to user_preferences.
INFO  [68f4e83eec70_copy_email_unsubscribe_to_user__py] Found 2 unsubscribes
INFO …
```
=> Migrate unsubscribes to preferences

lms/routes.py, lms/templates/admin/application_instance/show.html.jinja2, lms/views/admin/application_instance/show.py, lms/views/admin/application_instance/update.py, lms/views/admin/role.py, tests/unit/lms/views/admin/role_test.py
This PR is an alternative to https://github.com/hypothesis/lms/pull/5842, with the difference that we use proper paths instead of URL hashes to identify the active tab.
[Grabación de pantalla desde 2023-11-22 10-48-25.webm](https://github.com/hypothesis/lms/assets/2719332/15864d73-533c-4599-aae7-691f516997ef)
* Defined new `admin.instance.section` route, which is the same as `admin.instance` but with an extra `section` route param at the end. This param needs to match `info|settings|role-overrides|danger`.
* Add client-side logic in `show.html.jinja2` template to:
* Push state to the local history every time one tab is clicked, based on the tab's `data-section-id` attribute.
* Determine the active tab based on the last segment of the URL when the page loads or the local history state …
=> Define client-side handled routes for every admin AI tab

lms/migrations/versions/522985f4fa6e_remove_the_email_unsubscribe_table.py
Depends on <https://github.com/hypothesis/lms/pull/5895>.
This has now been replaced by the new `user_preferences` table.
=> Remove the `email_unsubscribe` table

lms/resources/_js_config/__init__.py, lms/static/scripts/frontend_apps/components/AppRoot.tsx, lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.tsx, lms/static/scripts/frontend_apps/components/ContentSelector.tsx, lms/static/scripts/frontend_apps/components/EmailNotificationsApp.tsx, lms/static/scripts/frontend_apps/components/EmailNotificationsPreferences.tsx, lms/static/scripts/frontend_apps/components/FilePickerApp.tsx, lms/static/scripts/frontend_apps/components/GradingControls.tsx, lms/static/scripts/frontend_apps/components/GroupConfigSelector.tsx, lms/static/scripts/frontend_apps/components/test/AppRoot-test.js, lms/static/scripts/frontend_apps/components/test/EmailNotificationsApp-test.js, lms/static/scripts/frontend_apps/components/test/EmailNotificationsPreferences-test.js, lms/static/scripts/frontend_apps/config.ts, lms/static/scripts/frontend_apps/index.tsx, lms/static/scripts/frontend_apps/test/index-test.js, lms/static/scripts/frontend_apps/utils/api.ts, lms/templates/email/preferences.html.jinja2, lms/views/email.py, tests/unit/lms/views/email_test.py
> This PR is effectively the same as https://github.com/hypothesis/lms/pull/5900, which was accidentally closed.
Part of https://github.com/hypothesis/lms/issues/5812
This PR updates the server template so that it injects client-side config for the email preferences app to load, as we do with the file picker, assignment launch, etc.
~The logic to save preferences is not implemented here, but in https://github.com/hypothesis/lms/pull/5902~ EDIT.: Both PRs are now merged together here.
1. Check out this branch
2. Run `make shell`. Once in, run `request.find_service(s.EmailPreferencesService).preferences_url("9ea84c4bcfd9329b4495f5b27d8cb6@lms.hypothes.is", "")`.
It should generate a URL.
3. Visit that URL. You should now see the client-side preact app, but the proper checkboxes should be …
=> Make email preferences load a client-side app

lms/static/scripts/frontend_apps/components/AppRoot.tsx, lms/static/scripts/frontend_apps/components/EmailPreferences.tsx, lms/static/scripts/frontend_apps/components/EmailPreferencesApp.tsx, lms/static/scripts/frontend_apps/components/test/AppRoot-test.js, lms/static/scripts/frontend_apps/components/test/EmailPreferences-test.js, lms/static/scripts/frontend_apps/components/test/EmailPreferencesApp-test.js, lms/static/scripts/frontend_apps/config.ts, lms/static/scripts/frontend_apps/index.tsx, lms/static/scripts/frontend_apps/test/index-test.js, lms/views/email.py, tests/unit/lms/views/email_test.py
This PR renames the `email-notifications` app mode to `email-preferences`, since the client-side URL used for it is now matching the server-side one, which is `/email/preferences`, and that way it is more consistent.
Additionally, also the config option and the components have been renamed to align with the "Email preferences" semantics.
=> Rename email-notifications app mode to email-preferences

lms/static/scripts/frontend_apps/components/EmailPreferencesApp.tsx
Part of https://github.com/hypothesis/lms/issues/5812
This PR adds preliminary styles to the email preferences app, as designed in https://www.figma.com/file/CDcGyBlGdi1oEuYXCeHW3Z/Hypothesis---Email-Digest-Preferences?type=design&mode=design
There's still some ongoing conversations around the design, so this might not be the final one, but it's a clear improvement over what we have now.
- I haven't found any other example of images set in FE components, other than dynamic images coming from API calls.
For simplicity I have hardcoded the path for the logo one, and I have used the same logo we use on emails.
- The logo image is pretty big. We may want to use a smaller variation.
- I have added links to help topics and support, as we show those in the sidebar no matter the context, so I …
=> Style email preferences app layout

tests/unit/lms/services/application_instance_test.py
We've seen failures in CI that hint at duplicate name values (created by default in the factory by `Faker("company")`
Try using a different strategy for the name in these test to see if that fixes the occasional failure.
https://github.com/hypothesis/lms/actions/runs/7058488361/job/19214171307
https://github.com/hypothesis/lms/actions/runs/7030081608/job/19128913472
=> Attempt at fixing flaky test on AI search by name

lms/services/grading_info.py, lms/views/lti/basic_launch.py, tests/unit/lms/services/grading_info_test.py, tests/unit/lms/views/lti/basic_launch_test.py
Motivated by https://github.com/hypothesis/lms/pull/5890, removing the guilty Schema completely in this PR.
- Remove existing grading records: `docker compose exec postgres psql -U postgres -c "truncate lis_result_sourcedid"`
- Login in D2L as `aunltd.S1`
- Launch [Gradable assignment (5 points)
](https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/3348/View)
- Check a new record is created
`docker compose exec postgres psql -U postgres -c "select lis_outcome_service_url, lis_result_sourcedid, h_username from lis_result_sourcedid"` 
```                                                                      lis_outcome_service_url                                                                       |           lis_result_sourcedid           |           h_username …
```
=> Refactor grading service to explicitly update the  model's fields

lms/static/scripts/frontend_apps/components/BookPicker.tsx, lms/static/scripts/frontend_apps/components/test/BookPicker-test.js, lms/static/scripts/frontend_apps/services/test/vitalsource-test.js, lms/static/scripts/frontend_apps/services/vitalsource.ts
Previously when the page ranges feature was enabled we would configure the assignment with either a page range, if the user entered a page range, or a CFI start point (not a range) if the user chose a chapter. Now when the user chooses a chapter, we will instead configure the assignment with a CFI range, where the start point is the CFI of the entry the user selected, and the end point is the CFI of the next TOC entry at the same level as the one the user selected. This makes the experience consistent regardless of which selection method the user chooses.
The `[start-end)` CFI range will be picked up by the client when the assignment is launched and used to [filter annotations](https://github.com/hypothesis/client/pull/6019).
**Testing:**
- Configure an assignment in the VS picker with …
=> Set end CFI when choosing chapter from list if page ranges feature enabled

lms/services/digest.py, tests/unit/lms/services/digest_test.py
Oops, in https://github.com/hypothesis/lms/pull/5858 I forgot to include
the `h_userid` in the `task_done.data` column (`h_userid` is needed
because we're going to need to find the latest `task_done` for a given h
user, so we're going to need to filter the `task_done` table by
`h_userid`).
=> Add `h_userid` to `task_done.data`

lms/tasks/email_digests.py, tests/unit/lms/tasks/email_digests_test.py
Depends on <https://github.com/hypothesis/lms/pull/5896>.
Needs to be deployed at the same time as <https://github.com/hypothesis/h-periodic/pull/397> and not during the daily email digest generation time.
=> Remove the `batch_size` argument

lms/routes.py, lms/templates/admin/application_instance/show.html.jinja2, lms/templates/admin/base.html.jinja2, lms/templates/admin/macros.html.jinja2, lms/templates/admin/organization/show.html.jinja2, lms/views/admin/organization.py
This PR is a continuation of https://github.com/hypothesis/lms/pull/5845, which brings client-side routing to the organization tabs.
[Grabación de pantalla desde 2023-12-11 12-13-19.webm](https://github.com/hypothesis/lms/assets/2719332/186d3e4a-7221-42bb-9e56-825f07fb92b4)
In order to explicitly support the logic in more than one place, the script handling the client-side logic has been moved to a macro, which additionally allows for some extra configuration (default section, amount of segments to be considered common prefix, etc).
I have also taken the opportunity to fix some missing closing/opening tags, so it's better to review this PR [ignoring empty lines](https://github.com/hypothesis/lms/pull/5910/files?w=1), as there are many lines which only changed their indentation.
=> Add client-side routing for admin/orgs tabs

lms/tasks/email_digests.py, tests/unit/lms/tasks/email_digests_test.py
This commit can be safely reverted on Weds 20th Dec 2023 or later.
Hard-code the minimum `TaskDone.data["created_before"]` date when
generating instructor email digests.
This is to get around an issue with deploying
https://github.com/hypothesis/lms/pull/5904, which changes
the email generation code so that each email counts annotations from the
time that each user's previous email counted annotations up to
(according to the `TaskDone` table) or seven days ago, whichever is most
recent.
The problem is that we would have to wait until seven days after
https://github.com/hypothesis/lms/pull/5903 (which fixed the code that
writes to `TaskDone`) was deployed before we could deploy
https://github.com/hypothesis/lms/pull/5904 because we would need at
least seven days of correct rows in the …
=> Hard-code the minimum TaskDone created_before date

lms/tasks/email_digests.py, tests/factories/__init__.py, tests/factories/task_done.py, tests/unit/lms/tasks/email_digests_test.py
Depends on <https://github.com/hypothesis/lms/pull/5903>. Technically I think we may need to deploy <https://github.com/hypothesis/lms/pull/5903> and then wait for at least a week before deploying this PR, in order to avoid any potential for emails to count annotations that have already been counted in previous emails. I think we may be able to do a DB migration to insert some rows into `task_done` to avoid having to wait for a week.
Use the `TaskDone` table to decide the `created_after` date when generating instructor email digests. Instead of each email counting annotations from a fixed `created_after` after (5am UTC yesterday), each email will now count annotations from the time up until which this user's previously-sent email counted annotations (the `created_before` date of the …
=> Use `TaskDone` when generating emails

lms/tasks/email_digests.py, tests/unit/lms/tasks/email_digests_test.py
As dates have already been stored in the DB we need to inject tzinfo to existing dates.
[Slack thread](https://hypothes-is.slack.com/archives/C4K6M7P5E/p1702550133086829)
=> Make created_before timezone aware in send_instructor_email_digest_tasks

lms/tasks/email_digests.py, lms/views/admin/email.py, tests/unit/lms/tasks/email_digests_test.py
The admin pages for test-sending instructor email digests were broken:
the `created_after` argument was removed from the
`send_instructor_email_digest` task but the admin pages were still
trying to use this argument.
I think we want the admin pages to be able to specify a date range with
both `created_after` and `created_before` because there are annotations
that've been created in QA and prod such that the admin pages default
`created_after` and `created_before` dates result in a non-empty email
with some interesting contents.
So re-add the `created_after` argument to `send_instructor_email_digest`
as an optional argument that's only used by the admin pages.
=> Fix the email admin pages

lms/product/blackboard/__init__.py, lms/product/blackboard/_plugin/misc.py, lms/product/blackboard/product.py, lms/product/plugin/misc.py, lms/services/html_service.py, lms/services/jstor/_article_metadata.py, lms/services/lti_grading/_v13.py, lms/services/lti_grading/factory.py, tests/unit/lms/product/blackboard/_plugin/misc_test.py, tests/unit/lms/product/plugin/misc_test.py, tests/unit/lms/services/html_service_test.py, tests/unit/lms/services/lti_grading/_v13_test.py, tests/unit/lms/services/lti_grading/factory_test.py
Some LMS don't play nice with regular line breaks in grading comments (`\n`) but use HTML instead.
This PR uses a naive approach to maintain the new lines in our textarea. It doesn't however try to support the full range of HTML different LMSes support.
- Enable grading comments in http://localhost:8001/admin/instance/106/
- Lauch https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/3348/View?ou=6782
- Read the comment, it contains new lines. Change the comment.
- Reload the assignment, read the comment again, it contains the changes.
- Enable grading comments in http://localhost:8001/admin/instance/109/
- Lauch https://hypothesisuniversity.moodlecloud.com/mod/lti/view.php?id=685
- Read the comment, it contains new lines. Change the comment.
- Reload the assignment, read the …
=> Support for linebreaks in grading comments

lms/models/application_instance.py, lms/templates/admin/application_instance/show.html.jinja2, lms/views/lti/basic_launch.py, tests/unit/lms/views/lti/basic_launch_test.py
We are already reading the scale value in all instances, the flag removed here just handles exposing it to the front end, sending the actual value instead of `None`.
For LTI1.1 instances the default implementation of get_score_maximum always returns None.
In case there's any issue with the feature rollback procedure will be to just revert this commit.
- As `blackboardteacher` launch [localhost (make devdata) HTML Assignment](https://aunltd-test.blackboard.com/webapps/blackboard/execute/blti/launchPlacement?blti_placement_id=_20_1&content_id=_36_1&course_id=_19_1)
- You'll get something like:
```DEBUG [lms.views.lti.basic_launch:188][MainThread] Score maximum for _36_1: None``` in the logs
- Login as `HypothesisEng.Teacher`
- Launch 
- …
=> Enable grading scale for all instances

lms/models/application_instance.py, lms/product/plugin/misc.py, lms/templates/admin/application_instance/show.html.jinja2, tests/unit/lms/product/plugin/misc_test.py
Stop reading the application instance setting.
To rollback this change we'll have to just revert this commit to go back to read the current state of the DB.
- As `HypothesisEng.Teacher`
- Sanity check the comment box is present in [this LTI1.3](https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/3348/View) assignment but not in [the 1.1 one](https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/3350/View).
=> Enable grading comments for all LTI1.3 instances

lms/resources/_js_config/__init__.py, lms/services/vitalsource/service.py, tests/unit/lms/resources/_js_config/__init___test.py, tests/unit/lms/services/vitalsource/service_test.py
Following recent client chanes, the content range is now expected under the "focus" property instead of the "contentRange" property. eg:
```
{
"focus": {
// When content range is specified with pages.
"page": "10-20",
// When content range is specified via TOC selection.
"cfi": {
"range": "/2/4-/2/6",
"label": "Chapter 1"
}
}
}
```
Once this lands I can do end-to-end testing that a VitalSource assignment with a page range or chapter range configured only shows annotations from that range.
=> Update how content range configuration is passed to the client

lms/services/vitalsource/service.py, tests/unit/lms/services/vitalsource/service_test.py
The client configuration currently uses the plural form. See https://github.com/hypothesis/client/blob/0a7f935fe4dbdc4e8ba816629935b3cb3b858297/src/types/config.ts#L110.
=> `page` => `pages` in content focus configuration

lms/db/__init__.py, lms/events/event.py, lms/models/event.py, lms/services/event.py, lms/tasks/event.py, lms/views/api/canvas/authorize.py, tests/unit/lms/events/event_test.py, tests/unit/lms/services/event_test.py, tests/unit/lms/tasks/event_test.py, tests/unit/lms/views/api/canvas/authorize_test.py
Use the infrastructure to record events to also record instances where the backend emits a known error code to the frontend.
Start with the CANVAS_INVALID_SCOPE code in anticipation for the rollout of canvas pages.
Events stored this way record the install, course, assignment and user that are relevant.
- Restart `make dev` to get the new task registered.
- Log in into Canvas with `eng+canvasteacher@hypothes.is`
- Launch any [assignment](https://hypothesis.instructure.com/courses/121/assignments/850) from the Missing Developer Key Scopes course
- You'll get an error dialog
- Check the events in the DB
```
docker compose exec postgres psql -U postgres -c "select event.*, extra from event join event_type on event_type.id = type_id join event_data on event_data.event_id = event.id where type …
```
=> Record occurrences of CANVAS_INVALID_SCOPE in the event table

tests/unit/lms/services/lti_role_service_test.py
The assert is using the wrong search method, looking at roles instead of overrides.
=> Fix role override deleting tests 

lms/services/digest.py, lms/templates/email/instructor_email_digest/body.html.jinja2, lms/templates/email/unsubscribed.html.jinja2, lms/views/email.py, tests/unit/lms/services/digest_test.py, tests/unit/lms/views/email_test.py
This effectively releases the weekly email digests feature, as it gives users access to the page where they can change their email preferences.
In a future commit the unsubscribe URLs will be changed to also redirect to the preferences page (after unsubscribing).
Screenshot of the email footer with the new link:
=> Add preferences links to emails

.github/dependabot.yml
Many dependencies of dependencies are:
- Not pinned
- Never bumped to a new version
I'm not sure if I'm reading this correctly:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow
but maybe this will send us PR for those that can be updated.
=> Update dependencies of direct dependencies

.github/dependabot.yml
Reverts hypothesis/lms#5942
This seems to lead to  "Dependabot timed out during its update"
See:
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/troubleshooting-dependabot-errors#dependabot-timed-out-during-its-update
=> Revert "Update dependencies of direct dependencies"

tests/unit/lms/services/organization_service_test.py
The test started to fail after the new years due to some messing dates in the grouping and membership objects.
=> Add explicit dates to all test's needed objects

lms/product/canvas/_plugin/misc.py, lms/product/plugin/misc.py, tests/unit/lms/product/canvas/_plugin/misc_test.py, tests/unit/lms/product/plugin/misc_test.py
Canvas was the first LMS to support DL and we didn't prompt for title there.
When we added support for DL in D2L we added this configuration option, making the Canvas behaviour the default.
After testing with BB and Moodle we have discovered that they also require prompting for title.
Change the default and special case to `False` in the Canvas plugin.
- Reconfigure [a canvas assignment](https://hypothesis.instructure.com/courses/125/assignments/5142/edit?name=Testing+creation&due_at=null&points_possible=0) 
- No prompt for title.
- Create a new assignment [in this course](https://hypothesis.instructure.com/courses/125/assignments/5142/edit?name=Testing+creation&due_at=null&points_possible=0) using the DL flow. Existing Activities` -> 
`Hypothesis link (localhost)`
- You'll get the title …
=> Invert the default for deep linking title prompt

lms/product/d2l/_plugin/misc.py, lms/product/plugin/misc.py, tests/unit/lms/product/d2l/_plugin/misc_test.py, tests/unit/lms/product/plugin/misc_test.py
The behaviour we had in D2L applies to all LMS where we have tried deep linking being Canvas the exceptions which overrides get_document.
The behaviour is:
- If we have the assignment in the DB use its document
- If not, but we have a record of the original assignment the current launch was copied from, use that.
- If not, check if we have deep linking configuration in the launch and use that. This is likely the first launch of the assignment.
- Return None otherwise.
=> Fallback to the deeplinking configuration for url by default

lms/tasks/email_digests.py, tests/unit/lms/tasks/email_digests_test.py
This reverts <https://github.com/hypothesis/lms/pull/5916>. This PR is safe to merge on Weds 20th Dec 2023 or later.
=> Revert "Hard-code the minimum TaskDone created_before date"

lms/services/oauth2_token.py, tests/unit/lms/services/oauth2_token_test.py
When multiple installs co-exists in the same school different token requests invalidate each other causing multiple authorization requests to the LMS.
A launch in one install will request a new token, invalidating any others.
Another launch in the same school, by the same user but in a different install will not try to use the same token, request a new one invalidating the existing one.
- On `main`
- Launch both
- https://hypothesis.instructure.com/courses/125/assignments/873
- https://hypothesis.instructure.com/courses/319/assignments/3308
You'll get an authorization dialog when switching from one to another.
- Repeat the test on this branch, `oauth2-guid`, no auth dialog.
=> Fetch oauth2 token by GUID instead of application instance ID

lms/services/oauth2_token.py, tests/unit/lms/services/oauth2_token_test.py
Reverts hypothesis/lms#5939
Reverting this as some light testing in QA showed this error:
https://hypothesis.sentry.io/issues/4526546787/?alert_rule_id=342674&alert_type=issue&environment=qa&notification_uuid=017ae769-e983-472e-b518-3132d8d0e698&project=259908&referrer=slack
The problem is that while from the point of view of the LMS the user is the same in all installs for the same GUID, we could have configured each of those install with different API client ids.
Probably not a very common setup but to properly support this we should make the query aware of the install settings and only count installs with the same GUID and same client ID. That shouldn't be too complicated but the way this is stored right now, specially for canvas, the query would be different per LMS.
Not worth the …
=> Revert "Fetch oauth2 token by GUID instead of application instance ID"

requirements/bddtests.txt, requirements/checkformatting.txt, requirements/coverage.txt, requirements/dev.txt, requirements/format.txt, requirements/functests.txt, requirements/lint.txt, requirements/prod.txt, requirements/template.txt, requirements/tests.txt, tests/unit/lms/services/application_instance_test.py
This is the result of running:
make requirements --always-make args='--upgrade'
Non top level dependencies can become outdated as dependabot doesn't send PR for those.
On top of that upgrading single packages with all the existing constraints might make impassible to satisfy all constraints.
This approach makes sure we are up to date with all our dependencies as specified on the .in files but without considering any constraints in the .txt files.
=> Upgrade python dependencies

lms/static/scripts/frontend_apps/components/ContentFrame.tsx
This PR ensures the `iframe` wrapped by `ContentFrame` allows `clipboard-write` from any origin.
This is required to make copying exported annotations work when proxying a site with via inside an LMS assignment.
=> Make ContentFrame allow cross-origin clipboard-write permission

lms/models/application_instance.py, lms/templates/admin/application_instance/show.html.jinja2
Usage was removed in:
https://github.com/hypothesis/lms/commit/00e198db601650750298ea19fa5f9433af87b27a
=> Remove outdated VS configuration setting

bin/run_data_task.py, lms/app.py, lms/models/__init__.py, lms/models/_mixins/public_id.py, lms/models/region.py, lms/services/__init__.py, lms/services/region.py, tests/conftest.py, tests/unit/conftest.py, tests/unit/lms/app_test.py, tests/unit/lms/models/region_test.py, tests/unit/lms/services/region_service_test.py
Replace the `models.Regions` "enum" (and its custom approach to implementing a global singleton) with a simple service in our usual style.
=> Remove `models.Regions`

lms/resources/_js_config/__init__.py, tests/unit/lms/resources/_js_config/__init___test.py
For the assignment page ranges feature to be usable in the client, the new search UI [1] needs to be enabled.
[1] https://github.com/hypothesis/client/issues/600
=> Enable new search UI in client when page ranges feature is enabled

lms/resources/_js_config/__init__.py, lms/views/lti/deep_linking.py, tests/unit/lms/resources/_js_config/__init___test.py, tests/unit/lms/views/lti/deep_linking_test.py
Similar to the "deep_linking_settings" in LTI1.3 the LMS could include
some data in the deep linking launch that must be forwarded in the
response message.
The only LMS where we use deep linking with LTI1.1 doesn't use this
feature so this has been unnoticed for years. Canvas does send the `data` value but it doesn't check we send it back.
In preparation to support deep linking in LTI1.1 in combination with VitalSource we need to be spec complaint.
Canvas does not use the new value so we'll just double check that nothing is broken.
- Re-configure a canvas assignment: https://hypothesis.instructure.com/courses/125/assignments/5142/edit?name=Testing+creation&due_at=null&points_possible=0
- The form submitted to `https://hypothesis.instructure.com/courses/125/external_content/success/external …
=> Forward opaque deep linking data in LTI1.1

lms/pshell.py
The import is stopping the server from starting because h_testkit is not a production dependency.
Moving the import to the method as a temporary workaround.
=> Move import to method in pshell

.cookiecutter/includes/requirements/prod.in, requirements/bddtests.txt, requirements/dev.txt, requirements/functests.txt, requirements/lint.txt, requirements/prod.in, requirements/prod.txt, requirements/template.txt, requirements/tests.txt
So Dependabot keeps it up to date.
=> Make sentry-sdk a direct requirement

lms/services/oauth1.py, lms/views/lti/deep_linking.py, tests/unit/lms/services/oauth1_test.py, tests/unit/lms/views/lti/deep_linking_test.py
LTI1.1 messages sent to the LMS should be signed. That includes server-to-server messages (like the grading API) and deep linking ones that are client-to-server.
For the grading API we use OAuth1.get_client which returns a http client we can use to make requests and attaches the required parameters transparently
However for deep linking we need the frontend to be ultimately the one making the requests (submitting a form to the LMS) so we need to generate those parameters and forward them to the frontend first.
While this is required by the spec Canvas doesn't enforce signing nor does it seem to check it's validity.
The testing below just confirms that things continue working on Canvas and that new signing parameters are indeed being sent to Canvas.
- Re-configure a canvas assignment: …
=> Sign deep linking request in LTI1.1

lms/static/scripts/frontend_apps/components/FilePickerApp.tsx, lms/static/scripts/frontend_apps/components/FilePickerFormFields.tsx, lms/static/scripts/frontend_apps/components/HiddenFormFields.tsx, lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js, lms/static/scripts/frontend_apps/components/test/HiddenFormFields-test.js, lms/views/lti/deep_linking.py, tests/unit/lms/views/lti/deep_linking_test.py
FilePickerFormFields is used in two contexts with the same goal but different targets.
It could be submitting a form to our own backend or completing a deep linking (DL) response flow, submitting the form to the LMS instead.
This commit changes the values submitted to limit them to only send the deep linking one when submit to the LMS.
The only LMS where we use LTI1.1 and deep linking doesn't seem to reject the extra parameters we send (title, group set... ) so there should't be functional changes there.
Other LMS which require the payload to be signed will get confused if the signature is for a set of fields (the DL ones) but the payload includes extra values.
No new bhevour changes but lets sanity check the aspects impatcted by the change:
- In this [BB course …
=> Only send deep linking parameters when deep linking

lms/services/oauth1.py, tests/unit/lms/services/oauth1_test.py
Missing in the first PR, URI params must be included in the payload.
=> Include url params in oauth1 signature

lms/models/lti_user.py, lms/services/lti_user.py, lms/templates/config.xml.jinja2, lms/views/canvas/config.py, tests/unit/lms/models/lti_user_test.py, tests/unit/lms/services/lti_user_test.py, tests/unit/lms/views/canvas/config_test.py
For: https://github.com/hypothesis/support/issues/94
---
We already use a combination of parameters to build our display_name. Use the LMS actual "display_name" when available to build a better version of the name.
This PR also adds the custom variable in Canvas so it's available in new installs.
Make annotations in 
- LTI1.3 https://hypothesis.instructure.com/courses/319/assignments/3308
- LTI1.1 https://hypothesis.instructure.com/courses/125/assignments/873
You'll get the display name in the client.
=> Use the LMS `display_name` to build our own 

lms/models/lti_params.py, tests/unit/conftest.py, tests/unit/lms/models/lti_params_test.py
These were missing but are only needed now for configuring the "user reference" field in some VitalSource integrations.
=> Map extra LTI1.1 <-> LTI1.3 parameters

lms/static/scripts/frontend_apps/components/BookSelector.tsx, lms/static/scripts/frontend_apps/components/ErrorModal.tsx, lms/static/scripts/frontend_apps/components/JSTORPicker.tsx, lms/static/scripts/frontend_apps/components/URLFormWithPreview.tsx, lms/static/scripts/frontend_apps/components/URLPicker.tsx, package.json, yarn.lock
Closes https://github.com/hypothesis/lms/issues/6012
This is another attempt on properly implementing accessible error messages when there are validation issues in content pickers.
As described in https://github.com/hypothesis/lms/pull/6040#issuecomment-1935946769, this PR only links inputs with their corresponding error message via `aria-describedby`, while marking them as invalid with `aria-invalid="true"`.
This combination does not cover one case: When clicking "Submit" buttons, the error message is not announced by screen readers.
Adding `role="alert"` would solve that, but incidentally makes error messages be announced twice when the focus is on the input.
1. Open the content picker of an existing assignment or create a new one.
2. Run a screen reader.
3. Enter an invalid value and …
=> Link content validation errors with corresponding inputs

lms/models/application_instance.py, lms/templates/admin/application_instance/show.html.jinja2, lms/views/lti/basic_launch.py, tests/unit/lms/views/lti/basic_launch_test.py
The `export_formats` feature has been enable for everyone, so we no longer need a setting to enable it on a per LMS instance basis.
We still have the `h` feature flag which would allow to disable it for all LMS instances, in case something comes up.
=> Remove setting to enable export_formats client feature

lms/views/api/canvas/pages.py, tests/unit/lms/views/api/canvas/pages_test.py
By default ViaHTML rewrites all iframes to proxy them through the Via server. In the context of Canvas Pages assignments this breaks embeds which require authentication or which simply don't work in ViaHTML. This PR disables proxying for all iframes in Canvas Pages content, using the [`via.proxy_frames`](https://github.com/hypothesis/viahtml/pull/618) config.
Part of https://github.com/hypothesis/support/issues/98.
**Testing:**
If you load https://hypothesis.instructure.com/courses/125/assignments/5632 on `main` and inspect the video below the "Uploaded video" text in the page, you'll see that the video is part of an iframe that is proxied through Via. If you load the same assignment on this branch, you'll see that the video's iframe is not proxied.
Note that the YouTube iframe at the …
=> Disable proxying of iframes in Canvas Pages assignments

lms/migrations/versions/08dff0b683e7_grouping_copied_from.py
Generated from: https://github.com/hypothesis/lms/pull/6046
```
dev run-test-pre: PYTHONHASHSEED='791837797'
INFO  [alembic.runtime.migration] Running upgrade 522985f4fa6e -> 08dff0b683e7, Add copied from ID to groupings.
```
=> Migration for grouping.copied_from_id

lms/models/grouping.py, lms/services/course.py, lms/services/grouping/service.py, tests/unit/lms/services/course_test.py
Depends on: https://github.com/hypothesis/lms/pull/6047
Same mechanisms and naming convenient than the same concept in Assignments.
Moodle doesn't support the assignment level variable so this could be used as plan B for supporting course copy (eg, first known which is the source course an from then infer the source assignment).
For now this is useful own its own to start recording this data.
- Create the new column:
- Clean any courses in the DB:
```docker compose exec postgres psql -U postgres -c "truncate grouping cascade;"```
- Launch an assignment on a non copied course:
https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2374/View
- Launch the equivalent assignment on the copied course: …
=> Keep track of which is the source course for copied ones

lms/static/scripts/frontend_apps/components/BookPicker.tsx, lms/static/scripts/frontend_apps/components/JSTORPicker.tsx, lms/static/scripts/frontend_apps/components/LMSFilePicker.tsx, lms/static/scripts/frontend_apps/components/URLPicker.tsx, lms/static/scripts/frontend_apps/components/YouTubePicker.tsx, package.json, yarn.lock
Depends on https://github.com/hypothesis/frontend-shared/pull/1460
All content picker close buttons used to have a generic "Close" title. This PR makes it more specific so that it's clear to non-sighted users what is going to be closed, when using a screen reader.
=> Add more specific titles to content picker dialog close buttons

lms/security.py, tests/bdd/features/lti_certification/section_3_types_of_roles.feature, tests/unit/conftest.py, tests/unit/lms/security_test.py
For https://github.com/hypothesis/support/issues/101
More info in https://hypothes-is.slack.com/archives/C2BLQDKHA/p1708114316485429
We currently allow any user that manages to do a valid launch to access the application with the basic LTI_LAUNCH and API permissions. This effectively is the same level of access as any legit student in a course.
Change that behaviour, if we can't map the LTI roles to neither of our own "learner", "instructor" or "admin" types, block access.
In general a person that's not part of a course won't be allowed to do the  launch on the first place by the LMS. However there are features that makes this possible, eg. you can change the visibility of a Canvas course to "institution" to make some of the course material available to all the school's users.
Always as …
=> Don't assign any permissions for LTI users with no roles

lms/models/lti_role.py, lms/templates/admin/role.override.html.jinja2, lms/templates/admin/role.override.new.html.jinja2, tests/unit/lms/models/lti_role_test.py
Related to: https://github.com/hypothesis/support/issues/101
Assign the correct "None" value to explicit None roles
https://www.imsglobal.org/specs/ltiv1p0/implementation-guide#toc-15 
https://www.imsglobal.org/spec/lti/v1p3#role-vocabularies
This doesn't have that many practical effects on it's own, see https://github.com/hypothesis/lms/pull/6052 for a change that does change permissions.
It does however correctly classify the roles and allows the admin pages "role overrides" the ability to ignore a role, ie. instead of assigning it to teacher/admin/student we can use "None" to ignore certain role in an institution.
From slack:
When we get one of those courses everyone can see you might get a None role. We classify that as LEARNER now which is incorrect but we correctly set the scope to …
=> Handle None roles

conf/gunicorn-dev.conf.py
Passing `reload_extra_files = "lms/templates"` to gunicorn makes it to be reloaded only when a file directly under `lms/templates` is edited.
This PR ensures all nested template subdirs are also taken into consideration, by using `glob`.
The only limitation is that it will not watch for dirs that do not exist at the moment of starting the server. That would still require a manual reloading.
=> Reload dev gunicorn on any template edition regardless of subdir

lms/validation/_lti_launch_params.py, tests/unit/lms/validation/_lti_launch_params_test.py
For: https://hypothes-is.slack.com/archives/C2BLQDKHA/p1708624870185739
We have seen at least one school sending `null` here which caused the validation to fail for a field that was not required at all.
=> Allow `None` values in non required LTI fields.

tests/unit/lms/models/grading_info_test.py, tests/unit/lms/models/group_info_test.py, tests/unit/lms/models/oauth2_token_test.py
The exact wording of the error messages changes between PostgresSQL versions.
Making the assertion on the messages less concrete so it works across versions.
=> Relax assertions made on postgres error messages

lms/product/d2l/_plugin/misc.py
True is already the default in the base class MiscPlugin
=> Remove re-definition of deep_linking_prompt_for_title

lms/product/d2l/_plugin/grouping.py, lms/product/plugin/grouping.py, tests/unit/lms/product/d2l/_plugin/grouping_test.py, tests/unit/lms/product/plugin/grouping_test.py
D2L was the first non-Canvas LMS where we supported DL and non DL flows.
While getting the groups configuration we can fallback to the DL in all non-Canvas LMSes instead making the D2L behaviour the default.
The DL configuration will be `{}` if DL was not used.
=> Fallback to deep linked group set in all non-Canvas LMSes

lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.tsx, lms/static/scripts/frontend_apps/config.ts
This PR update the `authUrl` type to allow `null`, in preparation for Moodle support.
See https://github.com/hypothesis/lms/pull/6064/files#r1500879457
=> Allow authUrl to be null

lms/models/grouping.py, lms/product/__init__.py, lms/product/factory.py, lms/product/moodle/__init__.py, lms/product/moodle/_plugin/grouping.py, lms/product/moodle/product.py, lms/resources/_js_config/__init__.py, lms/services/__init__.py, lms/services/group_info.py, lms/services/moodle.py, lms/tasks/rsa_key.py, tests/unit/lms/product/moodle/_plugin/grouping_test.py, tests/unit/lms/services/moodle_test.py, tests/unit/services.py, tox.ini
This is optimized for "reviewability" so it's not production ready, is missing some error handling and support for course copy.
These are tracked over https://github.com/orgs/hypothesis/projects/134/views/1
We can however test the basic support for groups and avoid a massive PR.
- As `moodystudent` launch [HTML - Group Assignment](https://hypothesisuniversity.moodlecloud.com/mod/lti/view.php?id=861)
- The group selector shows the group the students belongs to: `Groups in grouping C`
- Make an annotation
- As `moodleteacher` launch  [HTML - Group Assignment](https://hypothesisuniversity.moodlecloud.com/mod/lti/view.php?id=861)
- You'll get the list of groups in the group select (3 of them)
- Pick "Class Clown" in the grading selector. 
- The group selector filters to only the group the …
=> Basic support for Moodle Groups

tests/unit/lms/data_tasks/report/create_from_scratch/test_01_functions/test_01_date_functions.py
replace(year=X) fails on the 29th as it not a valid date on non leap years.
To match the python and postgres sides we change the postgres side to also do the math based on days instead of `1 year`.
Further reading: https://stackoverflow.com/questions/75417195/why-is-postgresql-1-year-interval-365-days-interval
=> Make timescale tests work on leap years' 29th Feb

lms/static/scripts/frontend_apps/components/ContentSelector.tsx, lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js
This is the first of (hopefully) a few PRs trying to reduce duplicated code in the `ContentSelector` component.
Doing so is not super straightforward, as removing duplication can introduce complexity, so it needs to be done carefully.
We also plan to align the FE-BE contract, since there's room for improvement there and that could also lead to simplification in the FE components.
For now, this PR reduces a bit the code duplication around calling `onSelectContent`.
=> Reduce duplicated code in ContentSelector

lms/migrations/versions/c64961cf7254_add_service_field_to_oauth2_token.py
This is an enum indicating which API an OAuth token refers to. There are initially two values:
- "lms" - The LMS's main API (default)
- "canvas_studio" - Canvas Studio API
This PR implements the migration in the simplest possible way. We might decide to change this to avoid locking the table during deployment. See https://github.com/hypothesis/lms/pull/6091#discussion_r1509113471.
Extracted from https://github.com/hypothesis/lms/pull/6091. Part of https://github.com/hypothesis/product-backlog/issues/1528.
=> Add migration for `oauth2_token.service` field

lms/models/oauth2_token.py, tests/unit/lms/models/oauth2_token_test.py
Update the unique constraint to match the migration that was added in ad5f11445d60822d587cfe9c1495578a3311684f, where the new `service` field is part of the constraint.
=> Fix unique constraint for `oauth2_token` in new DBs

lms/app.py, lms/views/api/exceptions.py, lms/views/exceptions.py
Exclude HTTPNotFound from the more verbose logging but add an explicit logging line so 404 are not completely silent.
=> Reduce log noise for 404 requests

lms/routes.py, lms/services/course.py, lms/services/grouping/factory.py, lms/services/organization.py, lms/templates/admin/base.html.jinja2, lms/templates/admin/course/search.html.jinja2, lms/templates/admin/course/show.html.jinja2, lms/views/admin/course.py, tests/unit/lms/services/course_test.py, tests/unit/lms/views/admin/course_test.py
Extracted from the PoC, just the courses part.
I reckon this useful regardless of any usage for the analysis project.
Lately I've been writing the query to search by organization by hand a few times, this will immediately help with that.
- Go ahead to http://localhost:8001/admin/courses and click around.
=> Basic listing of courses in the admin pages

lms/product/moodle/__init__.py, lms/product/moodle/_plugin/course_copy.py, lms/product/moodle/_plugin/misc.py, lms/product/moodle/product.py, lms/services/moodle.py, lms/views/api/moodle/files.py, lms/views/api/moodle/pages.py, tests/unit/lms/product/moodle/_plugin/course_copy_test.py, tests/unit/lms/services/moodle_test.py, tests/unit/lms/views/api/moodle/files_test.py, tests/unit/lms/views/api/moodle/pages_test.py
The fix for pages & files is very similar, tackling it in one PR.
The course copy fixed rely on having information stored from the original course, to simulate that we are going to select Pages and files from the file picker in the original course and stop there, ie. just listing them for the side effect **but not saving the changes**.
- Log in in moodle as moodleteacher.
- "Select content" button in  [HTML - Group Assignment](https://hypothesisuniversity.moodlecloud.com/course/modedit.php?update=861&return=1)
- List Moodle Files
- List Moodle Pages
- [Launch the original assignment](https://hypothesisuniversity.moodlecloud.com/mod/lti/view.php?id=863&forceview=1)
Result in the following logging:
```
DEBUG [lms.views.api.moodle.files:52][MainThread] Via URL for file in the same course. …
```
=> Moodle course copy fix for Pages and Files

README.md, lms/resources/_js_config/__init__.py, lms/resources/_js_config/file_picker_config.py, lms/routes.py, lms/security.py, lms/services/__init__.py, lms/services/canvas_studio.py, lms/services/oauth2_token.py, lms/services/oauth_http.py, lms/static/scripts/frontend_apps/components/ContentSelector.tsx, lms/static/scripts/frontend_apps/components/FilePickerApp.tsx, lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js, lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js, lms/static/scripts/frontend_apps/config.ts, lms/templates/api/oauth2/client_side_redirect.html.jinja2, lms/validation/authentication/_bearer_token.py, lms/validation/authentication/_lti.py, lms/validation/authentication/_oauth.py, lms/views/api/canvas_studio.py, tests/unit/lms/resources/_js_config/__init___test.py, tests/unit/lms/resources/_js_config/file_picker_config_test.py, tests/unit/lms/security_test.py, tests/unit/lms/services/canvas_studio_test.py, tests/unit/lms/services/oauth2_token_test.py, tests/unit/lms/services/oauth_http_test.py, tests/unit/lms/validation/authentication/_oauth_test.py, tests/unit/lms/views/api/canvas_studio_test.py, tests/unit/services.py
Implement the necessary pieces to enable authorizing with Canvas Studio and selecting a video from Canvas Studio in the content picker. Launching a Canvas Studio assignment is not yet implemented and will follow separately.
This includes:
- Support for fetching, saving and reading access tokens for OAuth-based APIs other than the LMSs main API in `OAuth2TokenService` and `OAuthHTTPService`. Note that _refreshing_ of access tokens is not yet implemented. That will follow separately.
- A `CanvasStudioService` service which exposes methods to handle the OAuth authentication flow for Canvas Studio and list media files and collections available to the user.
- A set of API views for Canvas Studio authorization and listing videos. The Canvas Studio authorization currently needs some workarounds …
=> Add MVP of Canvas Studio media selection in file picker

lms/product/factory.py, tests/unit/lms/product/factory_test.py
Some canvas instances are both missing the family LMS parameter and the custom course variable.
Use the guid value to guess canvas based as another heuristic.
[Checking these values in the DB](https://metabase.hypothes.is/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiJzZWxlY3QgKiBmcm9tIGFwcGxpY2F0aW9uX2luc3RhbmNlcyB3aGVyZSB0b29sX2NvbnN1bWVyX2luc3RhbmNlX2d1aWQgbGlrZSAnJWNhbnZhcy1sbXMnIGFuZCB0b29sX2NvbnN1bWVyX2luZm9fcHJvZHVjdF9mYW1pbHlfY29kZSA8PiAnY2FudmFzJyIsInRlbXBsYXRlLXRhZ3MiOnt9fSwiZGF0YWJhc2UiOjd9LCJkaXNwbGF5IjoidGFibGUiLCJwYXJhbWV0ZXJzIjpbXSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319)
=> Check GUID naming to guess the current product family.

lms/product/moodle/__init__.py, lms/product/moodle/_plugin/course_copy.py, lms/product/moodle/_plugin/grouping.py, lms/product/moodle/_plugin/misc.py, lms/product/moodle/product.py, lms/services/moodle.py, lms/views/api/moodle/files.py, lms/views/api/moodle/pages.py, tests/unit/lms/product/moodle/_plugin/course_copy_test.py, tests/unit/lms/product/moodle/_plugin/grouping_test.py, tests/unit/lms/services/moodle_test.py, tests/unit/lms/views/api/moodle/files_test.py, tests/unit/lms/views/api/moodle/pages_test.py
- Login in moodle as `moodleteacher`.
- The course copy fix relies on storing data in the original course. Simulate that using the "Select content" button in  [HTML - Group Assignment](https://hypothesisuniversity.moodlecloud.com/course/modedit.php?update=861&return=1)
- Select any type of content and the checkbox for "This is a group assignment". Do not save the assignment. We are only after the side effect.
- Launch [
HTML - Group Assignment](https://hypothesisuniversity.moodlecloud.com/mod/lti/view.php?id=861)
- [Launch the equivalent assignment on the copied course](https://hypothesisuniversity.moodlecloud.com/mod/lti/view.php?id=887)
- Check the DB for the state there:
````
select lms_name, extra from grouping where type = 'course';
-[ RECORD 2 …
```
=> Moodle course copy fixes

lms/routes.py, lms/services/canvas_studio.py, lms/services/exceptions.py, lms/services/oauth_http.py, lms/views/api/canvas_studio.py, lms/views/api/exceptions.py, lms/views/api/refresh.py, tests/unit/lms/services/canvas_studio_test.py, tests/unit/lms/services/oauth_http_test.py, tests/unit/lms/views/api/exceptions_test.py, tests/unit/lms/views/api/refresh_test.py
This implements refreshing of Canvas Studio access tokens when required, in the same way as we do with access tokens for other APIs. Some changes were needed in the generic OAuth refresh code paths to handle the fact that we're not refreshing the access token of the LMS's main API.
- Detect when API request failure to Canvas Studio can be fixed by refreshing the access token.
- Add views and service methods to handle Canvas Studio OAuth token refresh
- Fix an issue in `OAuthHTTPService.refresh_access_token` where the service type was not passed to `OAuth2TokenService.get`.
**Testing:**
1. Authenticate with Canvas Studio as described in https://github.com/hypothesis/lms/pull/6104
2. Invalidate the access token by running `UPDATE oauth2_token SET access_token = '' WHERE service = …
=> Implement Canvas Studio access token refresh

lms/product/moodle/_plugin/grouping.py, lms/services/moodle.py, lms/views/api/moodle/files.py, lms/views/api/moodle/pages.py, tests/unit/lms/product/moodle/_plugin/grouping_test.py, tests/unit/lms/services/moodle_test.py, tests/unit/lms/views/api/moodle/files_test.py, tests/unit/lms/views/api/moodle/pages_test.py
I created a few test assignments to reproduce these scenarios. These all return the correct error code but it still displayed a generic error. We'd need wording and KD articles to link to before having the final dialogs.
- [localhost - Group assignment - Grouping without groups](https://hypothesisuniversity.moodlecloud.com/mod/lti/view.php?id=862)
- [localhost - Group assignment - Deleted group](https://hypothesisuniversity.moodlecloud.com/mod/lti/view.php?id=918)
- [localhost - Page assignment - Deleted page](https://hypothesisuniversity.moodlecloud.com/mod/lti/view.php?id=917)
- [localhost - Deleted Moodle file](https://hypothesisuniversity.moodlecloud.com/mod/lti/view.php?id=916)
=> Moodle API integration error handling

gulpfile.mjs, lms/assets.ini, lms/static/styles/moodle_pages/moodle_pages.scss, lms/templates/api/moodle/page.html.jinja2
Following what was done in https://github.com/hypothesis/lms/pull/5761 for Canvas Pages, this PR defines some basic styles to make pages loaded in assignments look as close as possible to Moodle Pages loaded inside Moodle itself.
Moodle seems to have a single `all` stylesheet that's apparently the server-side merging of a bunch of stylesheets and served in a single `/theme/styles.php/boost/{timestamp}/all` URL.
I observed pages do not add any classes to the generated markup, but only a few inlined styles. Based on that I took the bare minimum from that `all` stylesheet so that it looks close enough, which in essence only includes styles applied directly to tags.
1. Check out this branch.
2. If your LMS server is already running, run `yarn gulp build-css`
3. Open this Moodle page: …
=> Add styles matching Moodle defaults for Moodle pages

lms/static/scripts/frontend_apps/components/ContentSelector.tsx, lms/static/scripts/frontend_apps/components/LMSFilePicker.tsx, lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js
The existing UI messages work because they use the document type enum value directly in the message, and do a naive pluralization by appending "s" (ie. "videos", "pages"). This works in English, but we'll obviously need to revise how this works to support other languages in future.
Also enable breadcrumbs for Canvas Studio so the user can navigate from a collection up to the root easily.
The icon for videos still needs updating, but I will do that separately.
=> Update Canvas Studio picker to use the term "video" instead of "page"

lms/static/styles/moodle_pages/moodle_pages.scss
Update the comment in `moddle_pages.scss` to indicate that its contents come from a combination of Moodle's generated CSS and Moddle's source code.
=> Small improvement on Moodle pages stylesheet comment

lms/product/moodle/_plugin/misc.py
The way moodle handles the title means there's no perfect solution.
Prompting for the title is less confusing while creating new assignments but not ideal for editing.
Not prompting for the title makes both new/editing equally confusing always overriding the LMS with tour default.
Ideally we can prompt for the title with this commit and steer the instructors to use our own editing flow over the one in the LMS
=> Re-enable title prompt for Moodle assignments

lms/static/scripts/frontend_apps/components/LaunchErrorDialog.tsx, lms/static/scripts/frontend_apps/components/test/LaunchErrorDialog-test.js, lms/static/scripts/frontend_apps/errors.ts, lms/views/api/moodle/files.py
The group related ones are very similar to other LMSes dialogs but each LMS uses a different word for "group sets". Moodle uses "grouping".
The file/pages we'll get a link to a KB article once those exists.
=> Modals to handle Moodle error codes

lms/models/assignment.py, lms/product/canvas/_plugin/grouping.py, lms/product/canvas/_plugin/misc.py, lms/product/moodle/_plugin/misc.py, lms/product/plugin/grouping.py, lms/product/plugin/misc.py, lms/services/assignment.py, lms/views/lti/deep_linking.py, tests/unit/lms/product/canvas/_plugin/grouping_test.py, tests/unit/lms/product/canvas/_plugin/misc_test.py, tests/unit/lms/product/moodle/_plugin/grouping_test.py, tests/unit/lms/product/moodle/_plugin/misc_test.py, tests/unit/lms/product/plugin/grouping_test.py, tests/unit/lms/product/plugin/misc_test.py, tests/unit/lms/services/assignment_test.py, tests/unit/lms/views/lti/deep_linking_test.py
This PR does two things:
- Enables Moodle edits using both of our editing button and re-deep-linking in the LMS.
That done mostly in this commit: https://github.com/hypothesis/lms/pull/6113/commits/51b0fe8ecb05bf947738af521dc84ae0b2808e4b
With the caveat that it's only done for `document_url`.
- Generalized "getting assignment configuration" 
Instead of having to duplicate the logic of `document_url` also for group_set_id this commit 
https://github.com/hypothesis/lms/pull/6113/commits/51b0fe8ecb05bf947738af521dc84ae0b2808e4b
centers the logic of where to get that config from in one method and then callers can decide on which part of the config they are interested. 
- Apply the migration from https://github.com/hypothesis/lms/pull/6114 with:
`tox -e dev --run-command 'alembic upgrade …
=> Allow editing and deep linking in Moodle

lms/models/application_instance.py, lms/resources/_js_config/__init__.py, lms/resources/_js_config/file_picker_config.py, lms/services/vitalsource/factory.py, lms/services/vitalsource/service.py, lms/static/scripts/frontend_apps/components/ContentSelector.tsx, lms/static/scripts/frontend_apps/config.ts, lms/templates/admin/application_instance/show.html.jinja2, tests/unit/lms/resources/_js_config/__init___test.py, tests/unit/lms/resources/_js_config/file_picker_config_test.py, tests/unit/lms/services/vitalsource/factory_test.py, tests/unit/lms/services/vitalsource/service_test.py
This enables VitalSource page range selection for all installs. The consequences of this are:
- When configuring a VitalSource assignment, there is the option to "Choose a chapter or page range" instead of "Pick a place to start reading"
- In the assignment, we show only annotations from the selected chapter or page range, and show a toggle button in the client to choose whether to show annotations from the rest of the book
- Existing VitalSource assignments are unaffected, and work the same as before
=> Remove feature flag checks for `vitalsource.page_ranges` flag

lms/models/application_instance.py, lms/models/assignment.py, lms/models/course.py, lms/models/event.py, lms/models/group_info.py, lms/models/grouping.py, lms/models/jwt_oauth2_token.py, lms/models/organization.py, lms/models/rsa_key.py, lms/models/user.py, lms/models/user_preferences.py, lms/services/http.py, lms/services/vitalsource/_client.py, pyproject.toml
Add type annotations to columns that SQLAlchemy can't infer.
From: https://docs.sqlalchemy.org/en/20/orm/extensions/mypy.html#mypy-pep-484-support-for-orm-mappings
```
The SQLAlchemy Mypy plugin, while it has technically never left the “alpha” stage, should now be considered as deprecated in SQLAlchemy 2.0, even though it is still necessary for full Mypy support when using SQLAlchemy 1.4.
```
=> Remove deprecated sqlalchemy typing plugin

lms/static/scripts/frontend_apps/components/ContentSelector.tsx
Fixes https://github.com/hypothesis/lms/issues/6126
Most of the `OptionButton`s in the `ContentSelector` had a `title` which translated in an `aria-label` not matching the content displayed to sighted users.
During the last accessibility review we were recommended to make sure the text matches, so this PR removes those, ensuring screen readers only read the same text that's actually displayed.
=> Remove titles from ContentSelector buttons

lms/services/canvas_api/client.py, lms/services/canvas_studio.py, lms/services/d2l_api/client.py, lms/services/moodle.py, lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/ContentSelector.tsx, lms/static/scripts/frontend_apps/components/DocumentList.tsx, lms/static/scripts/frontend_apps/components/LMSFilePicker.tsx, lms/static/scripts/frontend_apps/components/test/DocumentList-test.js, lms/views/api/blackboard/files.py, lms/views/api/canvas/pages.py, tests/unit/lms/services/canvas_api/client_test.py, tests/unit/lms/services/canvas_studio_test.py, tests/unit/lms/services/d2l_api/client_test.py, tests/unit/lms/services/moodle_test.py, tests/unit/lms/views/api/blackboard/files_test.py, tests/unit/lms/views/api/canvas/pages_test.py
Split the existing `type` field in file API responses, which indicates both whether and item is a file or folder, and also what kind of file it is (page, PDF etc.) into two separate fields: `type` for file vs folder and `mime_type` for the mime type. Then change the Canvas Studio proxy APIs to set `mime_type` to `video` and use that in the frontend to display a different icon.
**Testing:**
Start creating an assignment in Canvas and open:
1) The Canvas Page picker
2) The Canvas File picker
3) The Canvas Studio picker
For each of these pickers, you should see different icons. The video file type icon is just a placeholder to show we can render something different.
=> Split `type` property for file API responses into `type`/`mime_type` and add an icon for videos

lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/ContentSelector.tsx, lms/static/scripts/frontend_apps/components/DocumentList.tsx, lms/static/scripts/frontend_apps/components/LMSFilePicker.tsx
Previously there were confusingly two similar-sounding types `File` and `Document`, where `Document` actually had common properties for files and folders, and `File` had the additional properties for folders.
Refactor this so we have:
- A base type `FileBase` containing common properties for files and folders
- Sub-types `File` and `Folder` which contain properties exclusive to files and folders respectively
Then refactor various uses of the File/Document types to make it clearer whether that code path expects files, folders or both.
This change only affects type declarations and usage, so there should be no functional changes.
=> Improve TS types used to represent files and folders in cloud storage

lms/models/lti_user.py, lms/product/factory.py, lms/product/family.py, lms/resources/_js_config/__init__.py, lms/services/lti_user.py, lms/views/api/sync.py, tests/factories/lti_user.py, tests/unit/lms/product/factory_test.py, tests/unit/lms/product/family_test.py, tests/unit/lms/resources/_js_config/__init___test.py, tests/unit/lms/services/lti_user_test.py
Based on the Moodle work we have a need to deduplicate code around files/pages/course copy.
As a first step we are going to remove different way to detect which LMS is the current one and settle in just one method that will work in all situations.
No behaviour changes with this PR, but sanity checking a few things.
- [Reconfigure a Canvas assignment](https://hypothesis.instructure.com/courses/125/assignments/5115/edit?name=Why+did+all+these+elephants+die%3F+&due_at=null&points_possible=100)
- Pick Canvas files
- [Launch a gradable D2L assignment](https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/3348/View)
- Grade a student
=> Use LTIUser to detect the LMS we are currently using

lms/views/api/groups.py
This change:
https://github.com/hypothesis/lms/pull/6088/files#diff-e6f7e7b4990c33f197f354288dc4d39872ffd099166b0897d9cc3a2d7a3195fbL534
removed the need to send any data to the list group sets endpoint. As a side effect of that the FE decides to use "GET" instead of "POST" to call the endpoint.
As the endpoint was registered with "POST" the change is causing a 404 which are not recorded in sentry or otherwise raised any alarms.
Allowing both GET & POST requests for now to this endpoint until a better solutions is found.
Go to https://hypothesis.instructure.com/courses/125/assignments/5335/edit?name=Assignment+with+no+grades&due_at=null&points_possible=0 
Select any content source and pick groups. In main you get a "Endpoint not found error". In this branch successfully returns groups.
=> Fix listing groups while configuring assignments

lms/services/canvas_api/client.py, lms/static/scripts/frontend_apps/components/ContentSelector.tsx, lms/static/scripts/frontend_apps/components/FilePickerApp.tsx, lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js, lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js, lms/views/lti/deep_linking.py, tests/unit/lms/services/canvas_api/client_test.py, tests/unit/lms/views/lti/deep_linking_test.py
Use the schema://content we use for other content sources. This is already the case at the "via url" level.
We can't remove support for canvas_files & file_id while launching assignments as old assignment will still have those parameters as part of the deep link.
- Reconfigure https://hypothesis.instructure.com/courses/125/assignments/5115 using a canvas file. Launch it.
=> Use the same structure for canvas files listing as any other source

lms/views/api/exceptions.py, tests/unit/lms/views/api/exceptions_test.py
Extend the mechanism we already use for `canvas_invalid_scope` to other error codes.
- Launch a few assignment that produce error codes:
https://hypothesis.instructure.com/courses/125/assignments/1370
https://hypothesis.instructure.com/courses/125/assignments/1683
- Check the events in the DB:
```
select timestamp, type, course_id, assignment_id, extra->'code' from event join event_data on event_data.event_id = event.id  join event_type on type_id = event_type.id where type = 'error_code';
timestamp          |    type    | course_id | assignment_id |             ?column?              
----------------------------+------------+-----------+---------------+-----------------------------------
2024-03-22 11:15:58.536867 | error_code |      1288 |           297 | "canvas_group_set_not_found" …
```
=> Store known error codes as events on the DB

yarn.lock
This fixes execution of `yarn install` in CI envs, where the yarn.lock file is not expected to change.
I run `yarn install` and commited the changes applied to the yarn.lock file.
This sometimes happens after merging a few dependabot pull requests.
=> Sync yarn.lock by running yarn install

lms/product/moodle/_plugin/misc.py, tests/unit/lms/product/moodle/_plugin/misc_test.py
For: https://github.com/hypothesis/support/issues/108
From the bugreport:
> ### Steps to reproduce
> 1. Create a Hypothesis assignment in Moodle using a non-deep linked H LMS app
> 2. Enable Deep Linking in the H LMS app
> 3. Edit the assignment using the Select Content button in the deep linked H LMS app
> 4. Change the content to a different URL, PDF or Moodle Page
> 5. Accept the changes
Recorded a video going thru that and few more cases at the end
https://github.com/hypothesis/lms/assets/1433832/9131adf7-c2cf-40e5-8cfe-eee423150333
=> Support re-DeepLinking for assignment created without DL.

lms/models/application_instance.py, lms/templates/admin/application_instance/show.html.jinja2
This identifies the admin account whose API token will be used to fetch videos and transcripts when launching assignments.
This is part of https://github.com/hypothesis/lms/pull/6139.
=> Add Canvas Studio admin account email setting

lms/services/canvas_studio.py, lms/services/oauth2_token.py, lms/services/oauth_http.py, tests/unit/lms/services/canvas_studio_test.py, tests/unit/lms/services/oauth_http_test.py
The Canvas Studio API has a constraint that only the owner of a video or an admin can use the APIs for getting a video download/playback URL or the transcript. Before this PR, only the instructor who uploaded a video could actually launch the assignment.
In https://github.com/hypothesis/lms/pull/6160 a new application instance setting `canvas_studio.admin_email` was added, which specifies the email address of a user with admin permissions in Canvas Studio. In this PR, when an assignment is launched, an API token belonging to this user is used to fetch the video and transcript. In order for this to work, the admin user must authenticate Canvas Studio once by configuring or launching an assignment. The user does not have to be an administrator within Canvas itself, they just need to have …
=> Launch Canvas Studio assignments using an admin account

lms/services/jwt.py, tests/unit/lms/services/jwt_test.py
The default changed in a pyjwt release, re enable it again.
While we don't have that many registrations (the entities that have different jwt_URLs) it's probably a good practice to limit the size of the lru_cache.
In summary: the lru_cache of the client keeps one client around per jwt_url while the internal client cache keeps indivual keys for that URL identified by their ID (kid).
=> Re-enable caching of JWKs

lms/services/h_api.py, tests/unit/lms/services/h_api_test.py
Boilerplate to call the endpoint in H, server to server and return the results.
=> Expose H's stats endpoint

lms/models/assignment.py, lms/models/assignment_grouping.py
This allows to do `assignment.groupings` to get the list of groupings a assignment has been seen in.
Without this you have to manually build the query, which is not that complex but it get tiring after a few times.
=> Add relationship from assignment to groupings

lms/views/helpers/_via.py, tests/unit/lms/views/helpers/_via_test.py
This matches the behavior of Canvas Studio's own video player, although that player uses a different mechanism (overlaying a transparent element above the video to intercept clicks).
See also https://github.com/hypothesis/via/pull/1329.
**Testing:**
- Launch the Canvas Studio video assignment at https://hypothesis.instructure.com/courses/125/assignments/6473. The video's context menu and built-in download controls should be removed.
=> Disable video download controls for Canvas Studio videos

pyproject.toml
Check is causing false positives and flaky behaviour while running pylint
=> Disable pylint's unsubscriptable-object

lms/services/canvas_studio.py, lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/DocumentList.tsx, lms/static/scripts/frontend_apps/components/test/DocumentList-test.js, tests/unit/lms/services/canvas_studio_test.py
This PR adds support for displaying media thumbnails in the file picker, instead of just the generic mime-type icons, and uses this to display thumbnails for Canvas Studio videos.
For audio files, the image that Canvas Studio uses is not available (see notes in code), so we continue to render the generic media "play" icon as a fallback.
=> Display video thumbnails in Canvas Studio picker

lms/services/canvas_studio.py, tests/unit/lms/services/canvas_studio_test.py
**Depends on https://github.com/hypothesis/lms/pull/6180**
This makes the sorting consistent with other pickers.
=> Sort the contents of the Canvas Studio file picker by type (collection vs video) then by title

lms/resources/_js_config/__init__.py, lms/static/scripts/frontend_apps/services/client-rpc.ts, lms/static/scripts/frontend_apps/services/test/client-rpc-test.js, tests/unit/lms/resources/_js_config/__init___test.py
The initial intention was that the sidebar's menu item was going to send an RPC message to the LMS font-end, and this would be programmatically submitting a form in a new tab.
However, we found a problem in Firefox, where this is not considered part of a user gesture, resulting in the new tab opening to be blocked.
This PR changes the config passed to the client so that it can be the one submitting the form by only requesting the auth token to the LMS front-end via RPC.
The client PR will follow this one.
=> Change dashboard config so that the form can be sent from sidebar's frame

lms/resources/_js_config/__init__.py, lms/services/canvas_studio.py, lms/views/api/canvas_studio.py, tests/unit/lms/resources/_js_config/__init___test.py, tests/unit/lms/views/api/canvas_studio_test.py
Get the document URL from the DB instead of passing it via a query param. This prevents users from replacing it with one that is different than used when configuring the assignment. The new code matches how the `canvas_api.pages.via_url` route works.
Fixes https://github.com/hypothesis/private-issues/issues/173
=> Remove `document_url` param from `canvas_studio_api.via_url` route

lms/events/event.py, lms/resources/_js_config/__init__.py, lms/security.py, lms/tasks/event.py, lms/views/api/canvas/authorize.py, lms/views/api/exceptions.py, lms/views/api/grading.py, lms/views/lti/basic_launch.py, lms/views/lti/deep_linking.py, tests/unit/lms/events/event_test.py, tests/unit/lms/resources/_js_config/__init___test.py, tests/unit/lms/tasks/event_test.py, tests/unit/lms/views/api/canvas/authorize_test.py, tests/unit/lms/views/api/exceptions_test.py, tests/unit/lms/views/api/grading_test.py, tests/unit/lms/views/lti/basic_launch_test.py, tests/unit/lms/views/lti/deep_linking_test.py
Instead of a one method per field called using getattr use a more
explicit approach.
Using the new approach is easier to support event for which we don't have an user.
- Clean local events:
In `make sql`
```truncate event cascade;```
- Launch https://hypothesis.instructure.com/courses/121/assignments/850 for the missing scopes event
- Launch [any assignment](https://hypothesis.instructure.com/courses/125/assignments/873)t for the launch event
- [Re-configure this assignment](https://hypothesis.instructure.com/courses/125/assignments/5115/edit?name=Hypothesis+assignment&due_at=null&points_possible=100) to get the deep linking event.
- [Edit the document of an assignment](https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2424/View?ou=6782) for the edit event
- Create/delete …
=> Refactor how events are built

lms/models/__init__.py, lms/models/assignment.py, lms/services/assignment.py, lms/views/dashboard.py, tests/unit/lms/services/assignment_test.py, tests/unit/lms/views/dashboard_test.py
Join data from H for the dashboard with LMS DB records
Use the LMS DB data to:
- Filter out teachers
- Include students that didn't make an annotation
I've been applying a hacky diff like:
```diff
diff --git a/lms/views/dashboard.py b/lms/views/dashboard.py
index b3388208a..fa250873d 100644
--- a/lms/views/dashboard.py
+++ b/lms/views/dashboard.py
@@ -51,7 +51,6 @@ class DashboardViews:
route_name="api.assignment.stats",
request_method="GET",
renderer="json",
-        permission=Permissions.DASHBOARD_VIEW,
)
def api_assignment_stats(self):
"""Fetch the stats for one particular assignment."""
@@ -96,6 +95,7 @@ class DashboardViews:
def get_request_assignment(self):
assignment = self.assignment_service.get_by_id(self.request.matchdict["id_"])
+        return assignment
if not assignment: …
```
=> Show all students (and only students) in assignments dashboards

lms/resources/_js_config/__init__.py, lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/AppRoot.tsx, lms/static/scripts/frontend_apps/components/dashboard/DashboardApp.tsx, lms/static/scripts/frontend_apps/components/dashboard/StudentsActivityTable.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/DashboardApp-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/StudentsActivityTable-test.js, lms/static/scripts/frontend_apps/components/test/AppRoot-test.js, lms/static/scripts/frontend_apps/config.ts, lms/static/scripts/frontend_apps/index.tsx, lms/static/scripts/frontend_apps/utils/date.ts, lms/static/scripts/frontend_apps/utils/test/date-test.js, tests/unit/lms/resources/_js_config/__init___test.py
Closes https://github.com/orgs/hypothesis/projects/135/views/1?pane=issue&itemId=53493112
This PR adds a new client mini-app responsible of rendering the instructor dashboard.
The client-side mini-app matches the same route generated by the server, as we did with the email preferences.
https://github.com/hypothesis/lms/assets/2719332/e928da84-2631-495d-ace7-a7d5372ec416
This PR does not implement everything as it was designed, and has some open questions that we'll have to handle later.
* The list of students is not paginated.
* The table can be ordered, but ordering happens client-side. If server-side pagination is added, we would need to add server-side ordering as well.
* The design ~is not exactly as in~ is currently very different than …
=> Create dashboard miniapp

lms/security.py, tests/unit/lms/security_test.py
Use the feature flag not only to inform the FE to display/hide the button that launches the dashboard but also to actually enable/disable fetching the stats.
=> Only include the dashboard permission if the feature is enabled

lms/services/assignment.py, tests/unit/lms/services/assignment_test.py
Memberships are not unique by assignment/user but by assignment/user/role.
=> Fix is_member to support memberships with multiple roles

lms/models/lti_user.py, lms/security.py, tests/factories/lti_user.py, tests/unit/lms/security_test.py
Fix type declaration for LTIUser.application_instance 
- Remove the default None, it must always be not None
- Include application_instance on the factory
- Refactor test that build LTIUser as fixtures. Factory boy didn't have
access to subfactories in that setup.
- Add type annotations in security.py
=> Fix type annotations in security.py

lms/static/scripts/frontend_apps/components/dashboard/DashboardApp.tsx, lms/static/scripts/frontend_apps/components/dashboard/StudentsActivityTable.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/DashboardApp-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/StudentsActivityTable-test.js, lms/static/scripts/frontend_apps/components/test/ErrorDisplay-test.js, lms/static/scripts/frontend_apps/components/test/LaunchErrorDialog-test.js
This PR removes the need to read the `assignmentId` from the URL via `useParams`, in `DashboardApp`.
As of today, this was actually not needed, and it was there as a residue of some very early implementation of the dashboard.
~Incidentally, this also defines a proper key for the students fetcher, which was previously based on the `assignmentId`, and it is now based on the actual params that can affect the API call.~
Additionally, the use of `useFetch` + `apiCall` is replaced by `useAPIFetch` (see https://github.com/hypothesis/lms/pull/6205#discussion_r1570661221).
And finally, there's a second commit which fixes some tests which have started to break due to `wouter-preact` package being added further up in the test bundle, causing the `frontend-shared` link to be bundled as `Link$1` by …
=> Remove the need for `useParams` in DashboardApp

lms/static/scripts/frontend_apps/components/dashboard/StudentsActivityTable.tsx, package.json, yarn.lock
Apply changes introduced in https://github.com/hypothesis/frontend-shared/pull/1525 to make the students list look closer to the designs:
Before:
After:
I took the opportunity to use the `useOrderedRows` hook from `frontend-shared` and drop local one.
=> Use a grid table for the students list in the dashboard

lms/security.py, lms/views/admin/__init__.py, tests/unit/lms/security_test.py
This aligns the LTI and Google policies with the EmailPreferences one which already returned None to mean "no identity".
In general views rely on permission to gate access to not often we need to check for the presence of the policy itself in regular view code.
Having all policies behave the same will make changes to the overall delegating policy simpler.
=> Return Identity | None in security policies

lms/security.py, tests/unit/lms/security_test.py
Removing the assertion-less test which mask the missing coverage. Make it explicit with the pragma declaration.
=> Mark empty methods with "no cover"

lms/models/grouping.py, lms/product/canvas/_plugin/course_copy.py, lms/product/canvas/_plugin/grouping.py, lms/product/plugin/course_copy.py, lms/product/plugin/grouping.py, lms/services/course.py, lms/static/scripts/frontend_apps/components/LaunchErrorDialog.tsx, lms/static/scripts/frontend_apps/components/test/LaunchErrorDialog-test.js, tests/unit/lms/product/canvas/_plugin/course_copy_test.py, tests/unit/lms/product/canvas/_plugin/grouping_test.py, tests/unit/lms/product/plugin/course_copy_test.py, tests/unit/lms/services/course_test.py
For:
- https://github.com/hypothesis/product-backlog/issues/1219
- Edit [an assignment](https://hypothesis.instructure.com/courses/125/assignments/873/edit?return_to=https%3A%2F%2Fhypothesis.instructure.com%2Fcourses%2F125%2Fassignments%2F873) in the original course. Don't save it, just arrive to the stage that list the group sets available.
We do this to simulate the original assignment configuration that, a side effect, stored the existing group sets in the DB.
- Launch [a groups assignment in the copied course](https://hypothesis.instructure.com/courses/607/assignments/5818) 
- [Change the name of the group](https://hypothesis.instructure.com/courses/607/groups#) set to match/not match the name of the old one: `Test group set` (Three dots menu on the right)
- Reset the mapping in the …
=> Canvas group sets course copy fix

lms/static/scripts/frontend_apps/components/dashboard/test/DashboardApp-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/StudentsActivityTable-test.js
This PR adds accessibility checks to `DashboardApp` and `StudentsActivityTable` tests, since they were not added as part of  https://github.com/hypothesis/lms/pull/6174
=> Add accessibility checks to dashboard component tests

.github/workflows/ci.yml, docker-compose.yml
For:
- https://github.com/hypothesis/playbook/issues/1147
- If you don't have the service running you can just
`make services dev`
and the right postgres version will start.
If you do have a container running it won't start after the upgrade:
- Optionally, backup the contents
```docker exec -it lms-postgres-1 pg_dumpall -U postgres > upgrade_backup.sql```
- Find the the volume ID:
```
docker inspect -f '{{ .Mounts }}' lms-postgres-1
[{volume e22d1a81e263ceb8a63b29a14bc7ec2dbe9f023e7c05742cba6694a4999a6076 /var/lib/docker/volumes/e22d1a81e263ceb8a63b29a14bc7ec2dbe9f023e7c05742cba6694a4999a6076/_data /var/lib/postgresql/data local  true }]
```
- Stop the container
`docker compose down postgres`
- And remove the volume:
`docker volume rm …
=> Upgrade postgres to 15.6 in preparation for the production upgrade

lms/security.py
While a bit more verbose it's more explicit and more "grep-able" while looking for code related to one particular route.
=> Explicitly list the authorization routes that use a query parameter

lms/routes.py, lms/security.py, lms/static/scripts/frontend_apps/components/AppRoot.tsx, lms/static/scripts/frontend_apps/components/test/AppRoot-test.js, lms/views/admin/assignment.py, lms/views/dashboard.py, tests/unit/conftest.py, tests/unit/lms/security_test.py, tests/unit/lms/views/admin/assignment_test.py, tests/unit/lms/views/dashboard_test.py
Scope dashboard cookies to the current organization. This is done to
allow multiple cookies to coexists in the same browser allowing
multiple identities from different LMSes.
We include the organization ID in the URL, not the full one (public_id)
but just the last part of the identifier (_public_id).
The full public id contains both the region (us / ca) and the type of object (org) but
those are already part of the URL (region in the host name and org is in the path)
- Open the dashboard from https://hypothesis.instructure.com/courses/125/assignments/873
- Enable the dashboard in the [D2L instance](http://localhost:8001/admin/instance/106/settings)
- Open the dashboard from https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2374/View
- Switch beetween 
- …
=> Include path in cookies and change dashboard endpoints to include the organization ID

lms/error_code.py, lms/services/vitalsource/service.py, lms/static/scripts/frontend_apps/components/ErrorDialogApp.tsx, lms/static/scripts/frontend_apps/components/test/ErrorDialogApp-test.js, lms/static/scripts/frontend_apps/errors.ts, tests/unit/lms/services/vitalsource/service_test.py
While VitalSource course launches is something only students should do to acquire a license we'll show a message for instructors pointing them to create assignments instead.
Copy from https://hypothes-is.slack.com/archives/C2C2U40LW/p1714425682592469?thread_ts=1713560092.698679&cid=C2C2U40LW
=> Show a message for instructors in VS course launches

lms/services/vitalsource/service.py, lms/views/lti/basic_launch.py, tests/unit/lms/services/vitalsource/service_test.py, tests/unit/lms/views/lti/basic_launch_test.py
Instead of trying to guess the launch from the VitalSource course materials via LTI parameters that will be different from each LMS show the message in all cases for:
- Non DL launches
- No configured assignment
In the VS integration we don't use our non-DL filepicker because it will required teachers selecting the H sku in *every* launch. We'll always use DL to configure assignments.
That means that every non configured launch must be from the course materials section.
=> Change approach to display acquired license message for VS

lms/services/canvas_studio.py, lms/static/scripts/frontend_apps/components/LaunchErrorDialog.tsx, lms/static/scripts/frontend_apps/components/test/LaunchErrorDialog-test.js, lms/static/scripts/frontend_apps/errors.ts, lms/views/api/canvas_studio.py, tests/unit/lms/services/canvas_studio_test.py, tests/unit/lms/views/api/canvas_studio_test.py
Display a more helpful error in the case where a download URL cannot be obtained for a Canvas Studio video because it is hosted in YouTube or Vimeo. At the same time, also improve the presentation of the error when the video doesn't have a transcript.
The errors look like this:
Fixes https://github.com/hypothesis/lms/issues/6231
[1] See https://hypothes-is.slack.com/archives/C1MA4E9B9/p1714472977336609
=> Display better error if Canvas Studio video cannot be used with Via

lms/services/canvas_studio.py
make typecheck is not part of CI or make sure so this type of thing is easy to miss.
I'll start a slack thread about enabling this in CI.
=> Fix File dict declaration to mark fields as not required

lms/security.py, tests/unit/lms/security_test.py
While this is more verbose than the previous approach with a function to parametrize the base class behaviour it has a couple of adventages:
- We can use one test to check the right policy for all endpoints
- It makes switching to a more declarative approach easier in the future.
=> Use one security policy class per LTIUser location

lms/extensions/feature_flags/__init__.py, lms/models/_mixins/public_id.py, lms/resources/_js_config/__init__.py, lms/scripts/init_db.py, lms/services/canvas_api/_authenticated.py, lms/services/d2l_api/client.py, lms/services/file.py, lms/services/organization.py, lms/validation/_exceptions.py, lms/views/dashboard.py, pyproject.toml, requirements/checkformatting.in, requirements/checkformatting.txt, requirements/coverage.txt, requirements/format.in, requirements/format.txt, requirements/lint.in, requirements/lint.txt, tests/unit/conftest.py, tests/unit/lms/services/canvas_studio_test.py, tests/unit/lms/services/oauth_http_test.py, tests/unit/lms/views/api/canvas/pages_test.py, tests/unit/lms/views/api/moodle/pages_test.py, tests/unit/lms/views/helpers/_via_test.py, tox.ini
A slight change of plans, as this generates a relatively big diff let's do it first and tackle linting afterwards. 
This change doesn't take much effort and reverting is also very easy, just switch the dependencies and run black/isort again.
https://docs.astral.sh/ruff/formatter/
https://docs.astral.sh/ruff/formatter/#intentional-deviations
=> Use ruff to replace black,  isort, pydocstyle & pycodestyle

lms/static/scripts/frontend_apps/components/GroupConfigSelector.tsx, lms/static/scripts/frontend_apps/components/test/GroupConfigSelector-test.js, lms/static/scripts/frontend_apps/components/test/StudentSelector-test.js, package.json, yarn.lock
Depends on https://github.com/hypothesis/frontend-shared/pull/1540
Replace the last instance of `<Select />`, in the group config selector, with `<SelectNext />`.
https://github.com/hypothesis/lms/assets/2719332/bc4438a6-8f21-4941-9634-11776b337a94
=> Use SelectNext for groups config selector

lms/resources/_js_config/__init__.py, lms/views/lti/basic_launch.py, lms/views/lti/deep_linking.py, tests/unit/lms/resources/_js_config/__init___test.py, tests/unit/lms/views/lti/basic_launch_test.py, tests/unit/lms/views/lti/deep_linking_test.py
When launching an assignment, you should now see something like this in the browser console:
We always use course and assignment information that has already been queried during the request for other purposes, so this should have almost no performance impact.
=> Add assignment and group IDs in debug info

lms/services/assignment.py, tests/unit/lms/services/assignment_test.py
SpeedGrader launches lie to us in a at least two ways related to the information we store in the DB:
- The assignment title we get tis the course's not the groups
- All SpeedGrader launches are identified as is_gradable=False
- In `main` launch: [localhost (make devdata) HTML Assignment](https://hypothesis.instructure.com/courses/125/assignments/873)
- Check the DB status:
```
docker compose exec postgres psql -U postgres -c "select title, is_gradable from assignment where resource_link_id = 'f330509e8ee8e465a55c4c88a4fcc9ef1ee992bd';"
title                   | is_gradable 
------------------------------------------+-------------
localhost (make devdata) HTML Assignment | t
(1 row)
````
- Launch [localhost (make devdata) HTML Assignment in SpeedGrader …
=> Don't update assignment details while on a SpeedGrader launch

lms/models/lti_params.py, lms/product/canvas/_plugin/misc.py, lms/product/plugin/misc.py, lms/services/assignment.py, tests/unit/lms/product/canvas/_plugin/misc_test.py, tests/unit/lms/services/assignment_test.py, tests/unit/services.py
We use assignment.is_gradable for record keeping but ultimately the
source of truth should be the current launch. If we don't have the
necessary parameters to call the grading APIs, it's not a gradable launch.
The discrepancy of both method for `is_gradable` comes (as far as we know) from SpeedGrader launches
which are always not gradable (!?) and confuse the course and assignment
parameters.
After 387ec0a we stopped recording that
bogus data in the DB. As a result of that assignment are correctly
marked as gradable in the DB but launches by students in the "submission
details" view (which used SpeedGrader launches) fail because they are in
fact, not gradable launches.
- Launch https://hypothesis.instructure.com/courses/319/assignments/3336/submissions/35
- You'll get a `KeyError` in the …
=> Trust information from the launch instead of the DB for is_gradable

lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/AppRoot.tsx, lms/static/scripts/frontend_apps/components/dashboard/DashboardApp.tsx, lms/static/scripts/frontend_apps/components/dashboard/StudentsActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/DashboardApp-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/StudentsActivity-test.js, lms/static/scripts/frontend_apps/config.ts, package.json, yarn.lock
> [!NOTE]  
> This PR depends on https://github.com/hypothesis/lms/pull/6257, with the intention to merge it there first, to then merge both together into `main`, but with the ability to review them independently.
This PR starts preparing the Dashboard FE for the [BE changes](https://github.com/hypothesis/lms/pull/6257) around making the app more API-centric.
Main changes introduced here:
* Update to latest version of wouter-preact, which supports nested routes (according to the docs, v3.0 should also support them, but I couldn't make it work until I updated to v3.1)
* Create nested wouter routes, with the intention to dynamically render different pieces/children in the dashboard based on the route.
* Move student-specific async state handling from `<DashboardApp />` to `<StudentsActivity …
=> Frontend changes for the new API-driven dashboard

lms/app.py, lms/views/exceptions.py, lms/views/lti/oidc.py, tests/unit/lms/views/exceptions_test.py, tests/unit/lms/views/lti/oidc_test.py
The current "You are not authorized" message for bad LTI configuration is misleading as it points to the current user "you" and not a wider problem.
See: https://hypothes-is.slack.com/archives/C2C2U40LW/p1715865571948539
These are not as common but we'll start showing a more informative message that points to the actual source of the problem
We reuse here the current mechanism for displaying ValidationErrors. 
- Obliterate your lti_registrations 
```update lti_registration set client_id = 'NOOO' || "id" ;``` 
(can be fixed with make devdata)
- Launch https://hypothesis.instructure.com/courses/319/assignments/3308
=> Expose more details if available in the exception for forbidden views

lms/static/scripts/frontend_apps/components/ErrorDisplay.tsx, lms/static/scripts/frontend_apps/components/test/ErrorDisplay-test.js
This looks like
- [Launch a regular assignment](https://hypothesis.instructure.com/courses/125/assignments/873), nothing should break
- Launch an [assignment with an error modal](https://hypothesis.instructure.com/courses/125/assignments/1683). Clicking "open a support ticket" should prefill the debug info.
=> Expose debug information on get-help support links

lms/services/ltia_http.py, tests/unit/lms/services/ltia_http_test.py
For:
- https://github.com/hypothesis/lms/pull/6274
We seem frequent timeouts in this type of requests. Bumping to 30 seconds to see if we can clean up the logs and find other related issues.
See errors at:
https://hypothesis.sentry.io/issues/4844569539/?project=259908&query=transaction%3Alti_api.submissions.record&referrer=issue-stream&statsPeriod=7d&stream_index=2
`HTTPSConnectionPool(host='sso.canvaslms.com', port=443): Read timed out. (read timeout=20)`
=> Increase timeout for LTIA token requests

lms/js_config_types.py, lms/models/grouping.py, lms/resources/_js_config/__init__.py, lms/routes.py, lms/services/h_api.py, lms/templates/admin/course/show.html.jinja2, lms/templates/admin/macros.html.jinja2, lms/views/dashboard/api/assignment.py, lms/views/dashboard/api/course.py, pyproject.toml, tests/unit/lms/resources/_js_config/__init___test.py, tests/unit/lms/services/h_api_test.py, tests/unit/lms/views/dashboard/api/course_test.py
/ GET http://localhost:8001/dashboard/api/course/1826/assignments/stats
```
[
{
"id": 350,
"title": "localhost (make devdata) HTML Assignment",
"stats": {
"annotations": 6,
"replies": 0,
"last_activity": "2024-05-15T07:22:26.472842"
}
},
{
"id": 351,
"title": "Link selection placement text",
"stats": {
"annotations": 0,
"replies": 0,
"last_activity": null
}
},
{
"id": 352,
"title": "",
"stats": {
"annotations": 0,
"replies": 0,
"last_activity": null
}
},
{
"id": 353,
"title": "localhost (make devdata) Groups assignment ",
"stats": {
"annotations": 1,
"replies": 0,
"last_activity": "2024-05-15T07:23:34.823135"
}
}
]
```
- Checkout https://github.com/hypothesis/h/pull/8709 in H
- Launch a bunch of assignments in https://hypothesis.instructure.com/courses/125, note the course ID
- Open …
=> Expose annotation stats for a course's assignments

lms/js_config_types.py, lms/views/dashboard/api/assignment.py, lms/views/dashboard/api/course.py, tests/unit/lms/views/dashboard/api/assignment_test.py, tests/unit/lms/views/dashboard/api/course_test.py
Expose the course assignments belong.
This should help navigation from assignment to parent and from a list of assignment of different courses as the dashboards evolve.
FInd a course ID and open an URL like:
http://localhost:8001/dashboard/api/course/1830/assignments/stats
=> Expose each assignment parent course

lms/js_config_types.py, lms/routes.py, lms/security.py, lms/templates/dashboard/index.html.jinja2, lms/views/dashboard/api/assignment.py, lms/views/dashboard/api/course.py, lms/views/dashboard/views.py, tests/unit/lms/views/dashboard/api/assignment_test.py, tests/unit/lms/views/dashboard/api/course_test.py, tests/unit/lms/views/dashboard/views_test.py
This should be enough to have the first version of the "Course dashboard". 
On top the "landing" routes added here we have merged:
- https://github.com/hypothesis/lms/pull/6267
- https://github.com/hypothesis/lms/pull/6270
- https://github.com/hypothesis/lms/pull/6271
Find the ID of course and navigate to 
http://localhost:8001/dashboard/organization/LDtcl7EUTeW2UERPJLAVtA/course/1829
you should get a mostly empty FE page.
=> Landing pages for the course dashboards

lms/static/scripts/frontend_apps/components/dashboard/StudentsActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/StudentsActivity-test.js, lms/static/scripts/frontend_apps/utils/test/url-test.js, lms/static/scripts/frontend_apps/utils/url.ts, lms/static/scripts/tsconfig.json
In preparation for more dynamic API endpoints being consumed from the dashboard's frontend, this PR adds a helper function that given a URL template and a params record, does the proper replacing and expands the final URL.
The helper function is inspired in the one [from `client`](https://github.com/hypothesis/client/blob/d366c36ccc4676dac2f6ff0ad662e525d03a1613/src/sidebar/util/url.ts#L12), but with the next changes:
1. It does not return unused params, only the expanded URL. Instead, if some provided param does not have a matching placeholder in the template, it throws an error.
2. If the URL template has more than one appearance of the same placeholder, all of them are replaced with the corresponding value.
This PR also updates the existing API calls in `StudentsActivity` to use the …
=> Add logic to dynamically build URLs from a template and params

lms/error_code.py, lms/views/api/grading.py, tests/unit/lms/views/api/grading_test.py
For:
- https://github.com/hypothesis/support/issues/110
These occur while setting a participation date limit in the course.
While this commit doesn't really solve the issue for students it:
- Generates an error message that at least mentions "submissions". The previous error was a generic one generated by an unhandled exceptions.
- Records an event in the event table pointing to the student / assignment / course
- Set a course participation end date in the past in both the LTI1.1 and LTI1.3 courses, you have to select "Course" to set the date.
- https://hypothesis.instructure.com/courses/125/settings#tab-details
- https://hypothesis.instructure.com/courses/319/settings#tab-details
**Remember to clear it by switching back to "Term" after finishing the test**
- Open a new incognito window, …
=> Capture "not in course" errors while sending Canvas submissions

lms/static/scripts/frontend_apps/components/DataLoader.tsx, lms/static/scripts/frontend_apps/components/test/DataLoader-test.js
Update the `DataLoader` so that it creates an `AbortController` during side effects and a) calls `abortController.abort()` in the side effect's cleanup function and b) passes `abortController.signal` to the `load` callback, so that consumers can use it for "abortable" async operations, like API calls.
This capability is not used anywhere yet. We can refactor usages afterwards.
=> Allow DataLoader's loading to be cancelled on unmount

lms/app.py, lms/extensions/feature_flags/views/_predicates.py, lms/product/canvas/_plugin/grouping.py, lms/product/canvas/_plugin/misc.py, lms/product/d2l/_plugin/misc.py, lms/product/moodle/_plugin/grouping.py, lms/product/moodle/_plugin/misc.py, lms/product/plugin/grouping.py, lms/services/launch_verifier.py, lms/services/lti_grading/_v11.py, lms/services/lti_grading/interface.py, lms/validation/_base.py, lms/views/api/grading.py, pyproject.toml, tests/bdd/steps/h_api.py, tests/functional/lti_certification/v13/conftest.py, tests/functional/views/basic_lti_launch_test.py, tests/pyproject.toml, tests/unit/conftest.py, tests/unit/lms/services/mailchimp_test.py, tests/unit/lms/tweens_test.py
Here I'm testing an approach to avoid a huge pylint / ruff PR.
I wouldn't do it one by one and not for every rule, only for the ones that we have now `pylint:disable=` around the code.
The noqa notes are added by ruff with:
```
.tox/lint/bin/ruff check  -q lms tests bin --add-noqa      
```
=> Check unused-argument with ruff

lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/dashboard/CourseAssignmentsActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/DashboardApp.tsx, lms/static/scripts/frontend_apps/components/dashboard/StudentsActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/CourseAssignmentsActivity-test.js, lms/static/scripts/frontend_apps/config.ts
Add a new FE route matching for the dashboard course stats displaying a list of assignments.
- There's a bit of duplication with the students table. I will address that separately.
- Loading states and errors are handled individually. There's parallel work in progress to have a generic way to show a global loading indicator: https://github.com/hypothesis/lms/pull/6287
- As we add more pages, it becomes more obvious that components don't have specific enough names. I'll rename `StudentsActivity` to `AssignmentStudentsActivity` later, as at some point, we will need `OrganizationStudentsActivity`, `CourseStudentsActivity`, etc. They will wrap shared components.
1. Go to the courses section of the LMS admin http://localhost:8001/admin/courses, then click "Search"
2. From the list, find the …
=> Add new dashboard course page FE

lms/static/scripts/frontend_apps/components/dashboard/CourseAssignmentsActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/OrderableActivityTable.tsx, lms/static/scripts/frontend_apps/components/dashboard/StudentsActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/CourseAssignmentsActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/OrderableActivityTable-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/StudentsActivity-test.js, package.json, yarn.lock
Depends on https://github.com/hypothesis/lms/pull/6285
Create a common `OrderableActivityTable` component to render activity tables in the dashboard pages. This allows to:
1. Test the table ordering logic only once.
2. Have a consistent structure and look-and-feel between sections.
Additionally, this PR makes these other changes:
1. Render titles using `CardHeader` + `CardTitle` instead of a `h2` inside the `CardContent` itself. This title will potentially be removed replaced by a breadcrumb, but that requires a bit of experimentation.
2. Make all columns in the table but the first one be sorted in descending order by default, thanks to the implementation from https://github.com/hypothesis/frontend-shared/pull/1564
=> Create common components to represent dashboard activity pages

lms/config.py, lms/models/__init__.py, lms/models/hubspot.py, lms/services/__init__.py, lms/services/hubspot/__init__.py, lms/services/hubspot/_client.py, lms/services/hubspot/service.py, lms/tasks/hubspot.py, lms/templates/admin/macros.html.jinja2, lms/templates/admin/organization/show.html.jinja2, lms/templates/admin/organization/usage.html.jinja2, lms/views/admin/organization.py, requirements/bddtests.txt, requirements/dev.in, requirements/dev.txt, requirements/functests.txt, requirements/lint.txt, requirements/prod.in, requirements/prod.txt, requirements/tests.txt, requirements/typecheck.txt, tests/conftest.py, tests/factories/__init__.py, tests/factories/hubspot_company.py, tests/unit/lms/services/hubspot/_client_test.py, tests/unit/lms/services/hubspot/service_test.py, tests/unit/lms/tasks/hubpost_test.py, tests/unit/lms/views/admin/organization_test.py, tests/unit/services.py, tox.ini
The goal is to use the data from HS to automatically generate usage report based on data (dates) from HS company deals.
As a first step we are just fetching the organizations to the LMS DB. We add that information to the admin pages mostly as a way to check the import.
Based on this information we'll generate to automated alerts in slack:
- Active orgs with no company
- Active orgs that map to more than one company.
These will need to be fixed in HS.
Yes, this information is already imported in report, see [01_hubspot_import.py
](https://github.com/hypothesis/report/blob/main/report/data_tasks/report/create_from_scratch/02_hubspot_read/02_data_import/01_hubspot_import.py)
The HB import is mostly copied and simplified from that code.
Reports imports a bunch of data from HS but it does it: …
=> Import HubSpot companies and display them in the admin pages

lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/CourseActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/DashboardApp.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/CourseActivity-test.js
To better prepare for how the dashboard is going to evolve, this PR renames `StudentsActivity` to `AssignmentActivity`, and `CourseAssignmentsActivity` to `CourseActivity`. That way, they can serve as top-level components for each dashboard page, and we can later extract specific table components and reuse them.
=> Rename StudentsActivity to AssignmentStudentsActivity

lms/routes.py, lms/security.py, lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/AppRoot.tsx, lms/static/scripts/frontend_apps/components/dashboard/CourseActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/CourseActivity-test.js, lms/static/scripts/frontend_apps/components/test/AppRoot-test.js, lms/views/dashboard/views.py, tests/unit/lms/resources/_js_config/__init___test.py, tests/unit/lms/security_test.py, tests/unit/lms/views/admin/assignment_test.py, tests/unit/lms/views/dashboard/views_test.py
> Depends on https://github.com/hypothesis/lms/pull/6296
As agreed with the broader team, this PR replaces all occurrences of `organization`, `assignment` and `course` by `organizations`, `assignments` and `courses` in all dashboard routes.
=> Use plural forms in all dashboard-related routes

lms/routes.py, lms/services/canvas_studio.py, lms/static/scripts/frontend_apps/components/LaunchErrorDialog.tsx, lms/static/scripts/frontend_apps/components/test/LaunchErrorDialog-test.js, lms/static/scripts/frontend_apps/errors.ts, lms/views/api/refresh.py, tests/unit/lms/services/canvas_studio_test.py, tests/unit/lms/views/api/refresh_test.py
Canvas Studio admin token refreshes used to be done transparently by the backend when needed, which is different than how this is handled for other APIs. We need to introduce a mechanism to prevent concurrent refreshes of access tokens, and this will be easier to do if all token refreshes work the same way. Hence this commit changes Canvas Studio APIs to fail with an error if an admin refresh token is needed, and the frontend will initiate a refresh.
Unlike other token refreshes, if it fails, we show a custom error dialog to the user which doesn't prompt them to re-authorize (they can't, the current user is not the admin) and instead shows more specific instructions.
This change only applies if the current user is *not* an admin, otherwise refreshes are handled exactly as with other APIs, …
=> Change Canvas Studio admin token refresh to work more like other refreshes

lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/CourseActivity-test.js, lms/static/scripts/frontend_apps/utils/date.ts, lms/static/scripts/frontend_apps/utils/test/date-test.js
Use a `Intl.DateTimeFormatter` instance to format last activity dates in dashboard tables, making sure they are more human-friendly than current `YYYY-MM-DD hh:mm` format.
Chosen format options translate into something like `Dec 17, 2017, 10:00 AM` for en-US, which is not too long, and therefore fits nicely in the table.
=> Use human-friendly dates in dashboard tables

lms/services/course.py, lms/views/admin/course.py, tests/unit/lms/services/course_test.py, tests/unit/lms/views/admin/course_test.py
This allows callers to decide if the want to to include children, parents or single orgs.
=> Take an explicit list of org ids instead of querying for them in course service

lms/db/__init__.py, lms/db/_locks.py, lms/resources/_js_config/__init__.py, lms/services/canvas_studio.py, lms/services/exceptions.py, lms/services/oauth2_token.py, lms/services/oauth_http.py, lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.tsx, lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js, lms/static/scripts/frontend_apps/utils/api.ts, lms/static/scripts/frontend_apps/utils/test/api-test.js, lms/views/api/exceptions.py, tests/factories/oauth2_token.py, tests/unit/lms/db/_locks_test.py, tests/unit/lms/resources/_js_config/__init___test.py, tests/unit/lms/services/canvas_studio_test.py, tests/unit/lms/services/oauth2_token_test.py, tests/unit/lms/services/oauth_http_test.py, tests/unit/lms/views/api/exceptions_test.py
Use transaction-scoped advisory locks to prevent concurrent refreshes of the
same OAuth token. If a client tries to make a conflicting request, it will fail
with an HTTP 409. The frontend will then retry a few times.  Clients that retry
after the token is refreshed will find the token is already up to date and skip
the refresh.
See [this page](https://www.postgresql.org/docs/9.1/functions-admin.html) for details of the `pg_try_advisory_xact_lock` function.
Fixes https://github.com/hypothesis/lms/issues/6247
**TODO:**
---
**Testing:**
To test this, you first need to invalidate the refresh token for an existing API. The easiest way to do this is using `UPDATE oauth2_token SET access_token = 'foo'` in the lms DB. Then apply the diff below to make the refreshes take longer than normal: …
=> Use advisory locks to prevent concurrent OAuth token refreshes

lms/templates/admin/organization/show.html.jinja2, lms/templates/admin/organization/usage.html.jinja2, lms/views/admin/organization.py, tests/unit/lms/views/admin/organization_test.py
Fixes: https://hypothesis.sentry.io/issues/5434938179/?referrer=slack&notification_uuid=affb1058-729f-4bc5-92d4-af014cdad2dc&alert_rule_id=4849653&alert_type=issue
Instead of just using the right macro in the usage page, just move the company info to the main tab.
=> Fix using wrong macro to display usage stats

lms/resources/_js_config/__init__.py, lms/routes.py, lms/security.py, lms/services/course.py, lms/services/organization.py, lms/views/dashboard/api/course.py, lms/views/dashboard/base.py, lms/views/dashboard/views.py, tests/unit/lms/resources/_js_config/__init___test.py, tests/unit/lms/security_test.py, tests/unit/lms/services/course_test.py, tests/unit/lms/services/organization_test.py, tests/unit/lms/views/dashboard/api/course_test.py, tests/unit/lms/views/dashboard/base_test.py, tests/unit/lms/views/dashboard/views_test.py
This allows to have another "extra level" for navigation.
See: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1716983621819659
The approach here is the simplest we can merge with hopefully the goal of unblocking FE work.
(Adjust public id accordingly to localhost data, I have a note about making this part of devdata in my pile)
- Entrypoint http://localhost:8001/dashboard/organizations/LDtcl7EUTeW2UERPJLAVtA
- API route: http://localhost:8001/api/dashboard/organizations/LDtcl7EUTeW2UERPJLAVtA/courses
=> Basic listing of courses in an organization

lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/DashboardBreadcrumbs.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/DashboardBreadcrumbs-test.js
Add a breadcrumbs component to the dashboard pages.
> [!TIP]
> This PR is easier to review [ignoring whitespaces](https://github.com/hypothesis/lms/pull/6298/files?w=1).
https://github.com/hypothesis/lms/assets/2719332/7ede6c81-401b-41de-9fbb-caa5f1f0ca73
I looked for examples on how some websites do breadcrumbs, and read some articles around the subject. Based on that, I decided breadcrumbs should never span multiple lines, specially in mobile devices, where they could end up using too much screen space.
Using a combination of tailwind classes, I implemented in a way that:
* Every link has a maximum width, and then they truncate their content with `text-overflow: ellipsis` individually.
The space to reserve is calculated based on the total amount of links, with a porcentual max width for …
=> Add breadcrumbs to the dashboard views

lms/services/oauth_http.py, tests/unit/lms/services/oauth_http_test.py
As a step towards preventing concurrent refreshes for all OAuth APIs, try to acquire the advisory lock on all OAuth token refreshes performed by `OAuthHTTPService`, but only prevent concurrent refreshes when the caller opts-in, which currently means only Canvas Studio. Otherwise we just write a log entry so we can count how often concurrent refreshes occur.
Tested with our D2L site for example, the log entries look like:
```
web-https (stderr)   | 2024-06-03 11:11:29,390 DEBUG [lms.services.oauth_http:127][MainThread] Concurrent OAuth token refresh with token URL "https://auth.brightspace.com/core/connect/token"
```
=> Add logging to detect concurrent token refreshes for most OAuth APIs

lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/AppRoot.tsx, lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/CourseActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/DashboardApp.tsx, lms/static/scripts/frontend_apps/components/dashboard/DashboardBreadcrumbs.tsx, lms/static/scripts/frontend_apps/components/dashboard/OrderableActivityTable.tsx, lms/static/scripts/frontend_apps/components/dashboard/OrganizationActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/DashboardBreadcrumbs-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/OrganizationActivity-test.js, lms/static/scripts/frontend_apps/config.ts, package.json, yarn.lock
Add an organization home page where we list the courses that belong to the organization.
> [!NOTE]
> The BE does not currently return the amount of assignments per course. We'll add that in a follow-up PR.
Additionally, I took the opportunity to update to the latest frontend-shared patch release, which includes [a fix](https://github.com/hypothesis/frontend-shared/pull/1574) to allow interacting with links inside `DataTable`s via <kbd>Enter</kbd> key.
https://github.com/hypothesis/lms/assets/2719332/c603583e-2bcf-4f8a-998a-984e9d96b99c
1. Open an assignment: https://hypothesis.instructure.com/courses/125/assignments/873
2. Wait for the sidebar to load, then click on the user dropdown and select "Open dashboard".
3. The dashboard's assignment view should be loaded, and the breadcrumb …
=> Create dashboard organization home page

lms/js_config_types.py, lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/CourseActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/OrganizationActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/CourseActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/OrganizationActivity-test.js, lms/views/dashboard/api/assignment.py, lms/views/dashboard/api/course.py, tests/unit/lms/views/dashboard/api/assignment_test.py, tests/unit/lms/views/dashboard/api/course_test.py
Depends on https://github.com/hypothesis/lms/pull/6325
This PR refactors three dashboard API endpoints that were returning arrays, so that they instead returns JSON objects with a single prop.
This will allow us to extend the responses in a non-breaking way in future, if we need to add extra properties, like pagination and such.
=> Make all dashboard API endpoints return a JSON object response

lms/services/hubspot/service.py, tests/unit/lms/services/hubspot/service_test.py
While this worked before as postgres cast them to dates anyway it makes the python code clearer and more explicit.
=> Explicitly return date objects instead of string in hubspot integration

lms/services/oauth_http.py, tests/unit/lms/services/oauth_http_test.py
**Depends on https://github.com/hypothesis/lms/pull/6322.**
Prevent concurrent OAuth token refreshes for all APIs using `OAuthHTTPService`, which in practice means D2L and Blackboard. The Canvas integration currently has a separate implementation (see https://github.com/hypothesis/lms/pull/6328).
**Testing:**
1. Open https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/3348/View in two separate tabs. Open Network tab in dev tools
2. Apply this diff:
```diff
diff --git a/lms/services/oauth_http.py b/lms/services/oauth_http.py
index 3de6a17ba..a024facd3 100644
--- a/lms/services/oauth_http.py
+++ b/lms/services/oauth_http.py
@@ -132,6 +132,9 @@ class OAuthHTTPService:
raise ConcurrentTokenRefreshError() from exc
+        import time
+        time.sleep(5)
+
try:
return …
```
=> Prevent concurrent OAuth token refreshes D2L, Blackboard

lms/static/scripts/frontend_apps/components/BookPicker.tsx, lms/static/scripts/frontend_apps/components/ErrorDisplay.tsx, lms/static/scripts/frontend_apps/components/ErrorModal.tsx, lms/static/scripts/frontend_apps/components/LMSFilePicker.tsx
While working on something else, I noticed a couple potential improvements in the `ErrorDisplay` component.
* While inspecting the DOM, I noticed there was a `!mt-0` class set in the Scroll container, but I didn't see any other implicit margin that could justify setting that.
Then I saw a comment in code mentioning it was a workaround that could be removed after updating frontend-shared. We have updated it multiple times since the comment was created, so I assume it is now safe to remove.
* `ErrorDisplay`'s first non-Scroll element had a hardcoded top padding via `pt-4` tailwind class.
In order to use this component outside of `ErrorModal`s, it's more convenient to not have that padding, and let consuming code control that, so I have added a `classes` prop, and passed the padding from …
=> Remove hardcoded top padding in ErrorDisplay

lms/services/course.py, lms/views/dashboard/api/course.py, lms/views/dashboard/base.py, tests/unit/lms/services/course_test.py, tests/unit/lms/views/dashboard/api/course_test.py
The same person might have multiple "User" rows for example in different applications instances.
The h_userid value would be the same thought. Explicitly use this value instead of the full object both on the method to search for courses and to check user membership.
Sanity check course listing by going to:
- http://localhost:8001/dashboard/organizations/LDtcl7EUTeW2UERPJLAVtA and clicking on any of the courses to exercise the is_member check.
=> Explicitly use h_userid to search and check membership of users to courses

lms/routes.py, tests/functional/views/admin_test.py, tests/unit/lms/views/admin/application_instance/create_test.py, tests/unit/lms/views/admin/application_instance/upgrade_test.py
Just changes to the admin pages routes here. 
This changes the current pattern and should be easier to stick to it for new URLs.
=> Settle on plurals for the admin pages URLs

lms/static/scripts/frontend_apps/components/dashboard/CourseActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/OrganizationActivity.tsx
Use text-color + underline style for links in dashboard tables.
This style is closer to the one in the designs.
Before:
After:
=> Use text-color, underline links in dashboard tables

lms/models/grouping.py, lms/models/organization.py, lms/services/course.py, lms/views/dashboard/api/course.py, tests/unit/lms/services/course_test.py, tests/unit/lms/views/dashboard/api/course_test.py
The same LMS course might be represented by more than one row in the grouping table, for example if we have seen it linked to more than one application instance.
Deduplicate them when asking for a list of course within an organization but still return the raw data in the search method.
Like other similar PRs, just sanity check the list of course over:
http://localhost:8001/dashboard/organizations/LDtcl7EUTeW2UERPJLAVtA/courses/1830
In production there are duplicates here, they should disappear after merging this.
https://lms.hypothes.is/dashboard/organizations/x9L8IC7tRRa2-rYITOx_yQ
=> Deduplicate courses when listing organization courses

lms/services/__init__.py, lms/services/organization.py, lms/services/organization_usage_report.py, lms/tasks/organization.py, lms/views/admin/organization.py, tests/unit/lms/services/organization_test.py, tests/unit/lms/services/organization_usage_report_test.py, tests/unit/lms/tasks/organization_test.py, tests/unit/lms/views/admin/organization_test.py, tests/unit/services.py
Move methods from organization service
This should be a pure refactor, no functional changes. `OrganizationService` was getting too long.
=> Create usage report service

lms/models/application_instance.py, lms/services/grading_info.py, lms/templates/admin/application_instance/show.html.jinja2, tests/unit/lms/services/grading_info_test.py
For:
- https://github.com/hypothesis/support/issues/126
Depending of when we recorded the "GradingInfos", when the LTI upgrade was made and whether or not the LMS provides the old IDs after an upgrade we might need to use one parameter or another.
We introduce a feature flag to control this behaviour for now instead of trying to make backwards incompatible changes.
Unfortunately I've not been able to reproduce this exact scenario in a local environment.
=> Add a feature flag to control which ID we use for grading in LTI1.3

lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/CourseActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/CourseActivity-test.js
Add FE changes for https://github.com/hypothesis/lms/pull/6341
The changes involve:
* Adjusting API type definitions to match the BE ones.
* Implement the same display_name fallback logic that the BE was previously doing.
In a follow-up PR we can enhance the falling-back logic, and add more information about what that means.
We will also need to improve the ordering so that items where display_name is null, are always in the bottom of the list.
This PR should not introduce any visual changes, so the only possible testing is a sanity check on the dashboard, to verify that's the case.
=> Update dashboard API type definitions

pyproject.toml
This file is auto-generated by the BDD tests, and was previously ignored
by Pylint linting.
=> Exclude _compiled_feature_steps.py from linting

lms/migrations/versions/73f0011260e4_usage_report.py, lms/models/__init__.py, lms/models/hubspot.py, lms/models/organization_usage.py, lms/services/__init__.py, lms/services/hubspot/service.py, lms/services/organization.py, lms/services/organization_usage_report.py, lms/tasks/organization.py, lms/views/admin/organization.py, pyproject.toml, tests/factories/__init__.py, tests/factories/organization_usage.py, tests/unit/lms/services/hubspot/service_test.py, tests/unit/lms/services/organization_test.py, tests/unit/lms/services/organization_usage_report_test.py, tests/unit/lms/tasks/organization_test.py, tests/unit/lms/views/admin/organization_test.py, tests/unit/services.py
Store the results in the DB for:
- Retrieval of the report without having to do the query work
- Option to graph the results in metabase over a period of time.
This commit add the option to generate these in an async (celery) task
but not code uses it yet.
The plan is to write a second  task that schedules periodic reports for
ongoing company deals.
- Remember to run migration in production
- Apply migration
```
```
- In `make shell` kick off a job
```
from datetime import datetime, timedelta
from lms.tasks.organization import generate_usage_report
org_public_id = "us.lms.org.LDtcl7EUTeW2UERPJLAVtA"
generate_usage_report.delay(db.query(models.Organization).filter_by(public_id=org_public_id).one().id, "testing", (datetime.now() - …
```
=> Option to generate usage report from a celery task

lms/js_config_types.py, lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/CourseActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/CourseActivity-test.js, lms/views/dashboard/api/assignment.py, lms/views/dashboard/api/course.py, tests/unit/lms/views/dashboard/api/assignment_test.py, tests/unit/lms/views/dashboard/api/course_test.py
We started recording student names in May 9th. Before that we only have the name if the student made an annotation as the name has always been stored in H.
Refactor the response shape to include the ID and use a now common "AnnotationMetrics" for data fetched from H in both assignments and courses responses.
=> Return user ID for students and an empty display_name when that's not available

lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js
Fix a bug where student's last activity would render the same fallback value we use for students without a display name, when the last activity was null.
This was caused by an incorrect combined condition.
Before:
After:
=> Ensure last_activity renders as empty string when it's null

lms/tasks/organization.py, tests/unit/lms/tasks/organization_test.py
Don't stop the process after finding the first existing report. Continue until we reach `limit` new reports.
=> Fix usage report scheduling to ignore already existing reports

lms/static/scripts/frontend_apps/components/dashboard/CourseActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/OrderableActivityTable.tsx, lms/static/scripts/frontend_apps/components/dashboard/OrganizationActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/CourseActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/OrderableActivityTable-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/OrganizationActivity-test.js
Allow navigating to the corresponding course or assignment when "confirming" a dashboard activity table row (double-clicking or pressing <kbd>Enter</kbd> when the row is focused).
https://github.com/hypothesis/lms/assets/2719332/ec89da2f-c9d5-4436-b728-c9781e813595
1. Check out this branch.
2. Open a an assignment dashboard.
3. Navigate one level up, to the course view.
4. Double-click any of the assignment rows. You should be taken to that assignment's view.
5. Go back to the course view again, then use the <kbd>Tab</kbd> key to focus elements until the first row is focused.
6. Using the arrow keys, move focus to any assignment row, then press <kbd>Enter</kbd>. You should be taken to that assignment's view.
The same should work in the home view.
=> Navigate in dashboard tables when "confirming" a row

lms/services/canvas_studio.py, tests/unit/lms/services/canvas_studio_test.py
We previously found cases where collections had an empty name, but it turns out the name field can be `null` as well. Adjust the validation schema to allow for this. Unfortunately there isn't another field in the same response that contains an alternative name, so just generate a fallback for now.
Fixes https://github.com/hypothesis/lms/issues/6352.
=> Handle Canvas Studio collections with null `name` field

lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/dashboard/OrderableActivityTable.tsx, lms/static/scripts/frontend_apps/components/dashboard/OrganizationActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/OrganizationActivity-test.js
Use the new course_metrics data returned for every course in the list of courses, and display it in the organization activity table.
Before:
After:
=> Add course metrics to OrganizationActivity table

lms/static/scripts/frontend_apps/utils/google-picker-client.ts, lms/static/scripts/frontend_apps/utils/test/google-picker-client-test.js
If an error occurred when attemping to change file permissions after selecting a file from Google Drive, the LMS frontend incorrectly assumed the attempt had succeeded.
The result was that launching the assignment would then likely fail, as the PDF didn't have the necessary permissions.
This is because the `request.execute` API doesn't work as the code expected. It always invokes its first argument with the response. The `request.then` API is the correct Promise-like API. The argument passed to the rejection handler then needs to be processed to turn the result into an `Error` as expected by the calling code.
With these changes, an error in the `enablePublicViewing` API should result in an error like:
changing
=> Fix errors setting Google Drive permissions not being reported

lms/routes.py
After settling on plurals for all the admin pages routes we created a conflict on the search and new organizations pages.
This is the quickest fix to allow organization creation again.
An alternative approach will be to include a pattern, something like [0-9]+, for all IDs that are a PK in the DB. That would allow to use a suffix in the /orgs/ namespace.
- Go over http://localhost:8001/admin/orgs, new organization now works.
=> Temporary fix to URL collision on the admin pages

lms/views/dashboard/base.py, tests/unit/lms/views/dashboard/base_test.py
This was shadowed in local testing while using the admin token which doesn't execute this line.
- Open the dashboard from an assignment (on a incognito window)
- Navigate at all three levels.
=> Call AssignmentService.is_member with the right parameter

lms/services/course.py, lms/services/h_api.py, lms/views/dashboard/api/assignment.py, lms/views/dashboard/api/course.py, tests/unit/lms/services/course_test.py, tests/unit/lms/services/h_api_test.py, tests/unit/lms/views/dashboard/api/assignment_test.py, tests/unit/lms/views/dashboard/api/course_test.py
Requires: https://github.com/hypothesis/h/pull/8756
At this stage I reckon is fine to merge both the H and this PR at roughly the same time and live with some time in the API.
- Checkout [this branch in H](https://github.com/hypothesis/h/pull/8756)
- Open the dashboard at the org, course and assignment level.
- At the course level, only counts by learners are counted, the number at the  course level should be the sum of the count at the assignment level.
=> Adapt HAPI to talk to the refactored query-builder style H API

lms/static/scripts/frontend_apps/utils/google-picker-client.ts, lms/static/scripts/frontend_apps/utils/test/google-picker-client-test.js
Switch from using the sensitive/restricted
`https://www.googleapis.com/auth/drive` scope to the non-restricted `https://www.googleapis.com/auth/drive.file` scope. The latter allows our app to only access files that have been shared via the Google Drive Picker, whereas the former allows access to all files.
For this to work, the OAuth client ID needs to be passed when configuring the picker, so that the selected file is later made available for use with the Google Drive API client. See https://stackoverflow.com/a/58175142/434243.
Fixes https://github.com/hypothesis/lms/issues/1333. See also [Slack thread](https://hypothes-is.slack.com/archives/C4K6M7P5E/p1718358056636239?thread_ts=1718176476.315619&cid=C4K6M7P5E).
**Testing:**
1. Go to your Google account settings and revoke Google Drive …
=> Switch to using non-restricted `drive.file` permission for Google Drive

lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/CourseActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/DashboardApp.tsx, lms/static/scripts/frontend_apps/components/dashboard/DashboardBreadcrumbs.tsx, lms/static/scripts/frontend_apps/components/dashboard/OrganizationActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/CourseActivity-test.js
So far, we have been using a design for the dashboard that matches what we have been using in other pieces of UI, like the file picker, or the email settings app. This allowed us to use existing reusable components without applying big customizations.
This PR moves the dashboard to a look-and-feel closer to the one from the [designs](https://www.figma.com/design/rugQ2tONStRF3RL9UXZaGW/Search-Explorations?node-id=1291-1432&t=hQd37oDQUbkZVHTP-0), removing the grey background and the use of `Card`s.
> [!NOTE]  
> This PR is easier to review [ignoring whitespaces](https://github.com/hypothesis/lms/pull/6358/files?w=1)
Before:
After:
=> Use a "cleaner" design for the dashboard, without cards

lms/migrations/versions/da01fe01c324_usage_report_teachers.py
Calculate the number of unique users per report, this can be calculated using the existing data of the reports which allows us to backfill the data.
In theory we could also calculate this on the fly (ie on metabase) but having the number in the DB makes it easier to do graphs etc.
- Merge and deploy this PR
- Run the migration once deployed
- Merge and deploy https://github.com/hypothesis/lms/pull/6373
- Merge and deploy https://github.com/hypothesis/lms/pull/6374
- Run the migration
=> Migration for unique teachers in reports

lms/resources/_js_config/__init__.py, lms/static/scripts/frontend_apps/config.ts, tests/unit/lms/resources/_js_config/__init___test.py
A requirement for the LMS dashboard is that we display the logged-in user display name in the header.
This PR adds a new config entry which exposes the most basic user details for the FE to display. It currently includes only the  `display_name`.
This information is not used yet. It will be used as part of https://github.com/hypothesis/lms/pull/6372
1. Launch an assignment
2. Open the browser console, and inspect generated HTML.
3. In the LMS iframe, we generate a `<script />qq tag with `class="js-config"`. It should include a block like this:
```json
{
"user": {
"display_name": "Hypothesis 101 Teacher"
}
} 
```
=> Expose logged-in LMS user basic details to the FE via config

lms/migrations/versions/8e203ad93a58_backfill_unique_teachers_for_existing_.py
Use the full report data stored in the DB to count unique users with an email, a good proxy for teachers.
See: https://github.com/hypothesis/lms/pull/6375
=> Calculate unique teachers for exiting reports

lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/CourseActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/OrderableActivityTable.tsx, lms/static/scripts/frontend_apps/components/dashboard/OrganizationActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/OrderableActivityTable-test.js, package.json, yarn.lock
This PR uses the logic introduced in https://github.com/hypothesis/frontend-shared/pull/1587 to make columns with value null be initially ordered last, and move first when the order direction changes.
Additionally, it refactors `OrderableActivityTable` to move the decision on what's the initial order direction for every column to every individual activity table.
https://github.com/hypothesis/lms/assets/2719332/9a85da0f-10f3-4b7b-93c1-3fe619f3de51
Any table where the user's last activity is null, should allow to test this behavior.
It can also be faked by making sure some null students names are returned, by applying this diff, replacing `<some-value>` with the display name of some student in your local dev database:
```diff
diff --git a/lms/views/dashboard/api/assignment.py …
```
=> Initially order null columns last in dashboard activity tables

lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.tsx, lms/static/scripts/frontend_apps/components/LaunchErrorDialog.tsx, lms/static/scripts/frontend_apps/components/test/BasicLTILaunchApp-test.js, lms/static/scripts/frontend_apps/components/test/LaunchErrorDialog-test.js, lms/static/scripts/frontend_apps/errors.ts
This is a revised version of https://github.com/hypothesis/lms/pull/6289, to improve how grading submission errors are handled in the frontend. In addition to addressing the TODOs in that draft, I have also tweaked the wording in the error messages to try and make it a bit shorter. I also used the term "Dismiss" rather than "Close" on the button to make it clearer that it is going to dismiss just the error message rather than "close" the whole assignment.
----
Summary of changes:
- Handle the `canvas_submission_course_not_available` error with a dedicated message and revise the wording of the existing submission error.
- Continue to show the assignment content underneath the submission error. The error dialog already had a translucent modal backdrop, so all that was required was to move …
=> Improve handling of grading submission errors in frontend

lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js
Proposal on how to slightly improve the experience when we have students in the assignment activity page which launched the assignment but didn't annotate.
So far we were displaying a placeholder composed out of "Student" prefix followed by the first 10 characters of the ID.
> [!NOTE]  
> For assignments newer than May 9th, 2024, this will never happen, as we now capture their display name during assignment launch, not when they first annotate.
=> Add help text for unknown students

lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/CourseActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/FormattedDate.tsx, lms/static/scripts/frontend_apps/components/dashboard/OrderableActivityTable.tsx, lms/static/scripts/frontend_apps/components/dashboard/OrganizationActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/CourseActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/OrganizationActivity-test.js
This PR tries to mitigate word wrapping in date columns of dashboard activity tables, which happens only at certain resolutions and depends on the resulting format for the user's locale.
The proposed solution is a combination of ensuring there's no word wrapping for dates, plus trying to maximize the amount of available space for those columns.
https://github.com/hypothesis/lms/assets/2719332/3a679cc3-5ce1-4234-9f05-d7dd9ef75621
This is not a perfect solution, as it's only aiming for large and medium resolutions. In small/mobile resolutions, the table still breaks, but we have [a separate issue](https://github.com/orgs/hypothesis/projects/135/views/1?pane=issue&itemId=65949275) to address that, and in that case, the solution should probably go in a different direction, and instead break …
=> Mitigate word wrapping in date columns for dashboard activity tables

lms/error_code.py, lms/services/lti_grading/_v13.py, lms/views/api/grading.py, tests/unit/lms/services/lti_grading/_v13_test.py, tests/unit/lms/views/api/grading_test.py
~~Blocked by: https://github.com/hypothesis/lms/pull/6289~~
For:
- https://github.com/hypothesis/support/issues/110
Now that we have a better error message for submissions related issues emit a known error code for these instead of silently not generating a submission.
- Log in as `eng+canvasstudent@hypothes.is` in Canvas
- Launch https://hypothesis.instructure.com/courses/319/assignments/4700
- Make one annotation.
- You'll get a generic `Grading submission failed` dialog.
=> Generate an error code when the attempts limit has been reached

lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.tsx, lms/static/scripts/frontend_apps/components/LaunchErrorDialog.tsx, lms/static/scripts/frontend_apps/components/test/LaunchErrorDialog-test.js, lms/static/scripts/frontend_apps/errors.ts
Add a custom error message for this scenario.
See https://hypothes-is.slack.com/archives/C1MA4E9B9/p1719220175035739 for discussion around the message.
**Testing:**
Follow the steps in https://github.com/hypothesis/lms/pull/6295. You should see this error:
=> Handle `canvas_submission_max_attempts` error in frontend

lms/static/scripts/frontend_apps/errors.ts
Depends on https://github.com/hypothesis/lms/pull/6390.
Unify the lists of LTI error codes used for typechecking and matched at runtime
against server error messages.
This makes adding new error codes easier and avoids a potential hazard where a
new error code is added to one list but not the other.
=> Unify error codes used for typechecking and at runtime

lms/js_config_types.py, lms/routes.py, lms/services/assignment.py, lms/services/course.py, lms/views/dashboard/api/assignment.py, lms/views/dashboard/api/course.py, lms/views/dashboard/pagination.py, tests/unit/lms/services/assignment_test.py, tests/unit/lms/services/course_test.py, tests/unit/lms/views/dashboard/api/assignment_test.py, tests/unit/lms/views/dashboard/api/course_test.py, tests/unit/lms/views/dashboard/pagination_test.py
For: https://github.com/hypothesis/lms/issues/6393
The main goal is to apply the same pagination method we just introduced for courses to a new entity and generalize the code around to avoid duplication.
- Move dashboard pagination to its own module
- Handle the limit request parameter directly in get_page
- Replace query parameters in the original URL instead of constructing it from scratch
- Use sqlalchemy.Select instead of sqlalchemy.Query. The latter is deprecated and we should move all API to the new SQLAlchemy 2.0
And finally:
- Paginated API endpoint for assignments
This is a barebones endpoint, it doesn't yet accept any query parameters for for example filter by course.
**This PR doesn't address any issues with the data returned, nullable titles, (potential) duplicate in the …
=> Paginated assignments API endpoint

lms/js_config_types.py, lms/routes.py, lms/services/assignment.py, lms/services/course.py, lms/views/dashboard/api/assignment.py, lms/views/dashboard/api/course.py, lms/views/dashboard/pagination.py, tests/unit/lms/services/assignment_test.py, tests/unit/lms/services/course_test.py, tests/unit/lms/views/dashboard/api/assignment_test.py, tests/unit/lms/views/dashboard/api/course_test.py, tests/unit/lms/views/dashboard/pagination_test.py
For:
- https://github.com/hypothesis/lms/issues/6393
Expose a API endpoint to list courses with pagination.
The intended use case is to list the courses in a drop down menu or similar to allow for filtering.
`http://localhost:8001/api/dashboard/courses?limit=2`
```
{
"courses": [
{
"id": 1883,
"title": "Copy of Developer Test Course with Sections Enabled (With Pags)"
},
{
"id": 1829,
"title": "Course copy LTI1.3"
}
],
"pagination": {
"next": "http://localhost:8001/api/dashboard/courses?cursor=%5B%22Course+copy+LTI1.3%22%2C+1829%5D&limit=2"
}
}
```
- Make sure you have an authorization cookie from the LMS admin pages visiting http://localhost:8001/admin/
- Open http://localhost:8001/api/dashboard/courses
- Play with the limit parameter, eg: …
=> Courses endpoint with pagination

lms/migrations/versions/1337584e2b07_ai_tool_consumer_instance_guid_index.py, lms/models/application_instance.py
We already make queries based on this values (eg. in FileService) and we are introducing similar queries for Canvas Studio.
```dev run-test-pre: PYTHONHASHSEED='4191188039'
INFO  [alembic.runtime.migration] Running upgrade 8e203ad93a58 -> 1337584e2b07, AI.tool_consumer_instance_guid index```
=> Create index on application_instance.tool_consumer_instance_guid

lms/services/canvas_studio.py, lms/services/oauth2_token.py, lms/services/oauth_http.py, tests/unit/lms/services/canvas_studio_test.py, tests/unit/lms/services/oauth_http_test.py
Handle the case where the same Canvas Studio OAuth client is reused for multiple installs at the same LMS, and the Canvas Studio admin has authenticated using while using a different install than the one being used to launch a Canvas Studio assignment.
Previously admin-authenticated API requests to Canvas Studio used tokens associated with the same application instance as the current LTI user.  In this commit that is changed to find a `(user, application_instance)` combination for a user who has the correct email, belongs to the same LMS, and has authenticated with Canvas Studio. If there are multiple matches, because the admin has authenticated in multiple installs, we pick the most recent.
This solution is something of a workaround for the fact that OAuth tokens in our LMS app do not …
=> Handle Canvas Studio admin token lookup when LMS has multiple installs

lms/js_config_types.py, lms/models/user.py, lms/routes.py, lms/services/user.py, lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/views/dashboard/api/assignment.py, lms/views/dashboard/api/user.py, lms/views/dashboard/pagination.py, tests/unit/lms/services/user_test.py, tests/unit/lms/views/dashboard/api/assignment_test.py, tests/unit/lms/views/dashboard/api/user_test.py, tests/unit/lms/views/dashboard/pagination_test.py
For: https://github.com/hypothesis/lms/issues/6393
```
{
"students": [
{
"id": "2a8a99bc095a8438a594cd57c1f4f0341951e360",
"display_name": "Hypothesis 101 Student"
}
],
"pagination": {
"next": "http://localhost:8001/api/dashboard/students?limit=1&cursor=%5B%22Hypothesis+101+Student%22%2C+71%5D"
}
}
```
- Make sure you have an authorization cookie from the LMS admin pages visiting http://localhost:8001/admin/
- Open http://localhost:8001/api/dashboard/students
- Play with the limit parameter, eg: http://localhost:8001/api/dashboard/students?limit=1
- Follow the `next` parameter in the response.
=> Add new API endpoint to list students

lms/views/dashboard/api/assignment.py
We found the issue, a problem with staging data in the DB.
We don't need this extra logging here for now.
=> Revert extra logging on assignment endpoint

lms/static/scripts/frontend_apps/config.ts
Following up on https://github.com/hypothesis/lms/pull/6411, update the `DashboardRoutes` definition with latest endpoints.
Additionally, add a couple code comments to explain the type, as it is getting more complex.
=> Update DashboardRoutes definiition with recently added new endpoints

lms/views/dashboard/api/course.py, tests/unit/lms/views/dashboard/api/course_test.py
Get courses now returns a select that needs to be executed before the results can be passed to get_courses_assignments_count.
- Opening something like 
http://localhost:8001/dashboard/organizations/local.lms.org.LDtcl7EUTeW2UERPJLAVtA
works again.
=> Fix course metrics listing about signature change on get_courses

lms/services/user.py, lms/views/dashboard/api/user.py, tests/unit/lms/services/user_test.py, tests/unit/lms/views/dashboard/api/user_test.py
For:
- https://github.com/hypothesis/lms/issues/6393
---
- Filter by course_id
- Filter by assignment_id
- Fetch course and assignment IDs based on:
http://localhost:8001/api/dashboard/courses
http://localhost:8001/api/dashboard/assignments
- Play around constructing URLs to filter them like:
http://localhost:8001/api/dashboard/students?course_id=1830&assignment_id=349
=> Add parameters to the students API endpoint to allow filtering

lms/static/scripts/frontend_apps/components/dashboard/DashboardApp.tsx, lms/static/scripts/frontend_apps/components/dashboard/OrganizationActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/OrganizationActivity-test.js, package.json, yarn.lock
In previous wouter-preact versions, calling `useParams()` in a nested route would only return the params for that specific route and not any potential parent.
Starting with v3.3, this is no longer the case, which allow us to simplify a bit some logic we had in `DashboardApp` where we had to call `useParams()` in order to pass a param down to `OrganizationActivity`.
Now we can call `useParams()` directly in `OrganizationActivity`, as we do in other dashboard activity components.
See the release notes for reference https://github.com/molefrog/wouter/releases/tag/v3.3.0
=> Update to latest wouter-preact with improved useParams()

lms/services/assignment.py, tests/unit/lms/services/assignment_test.py
For courses and users we have a deduplicating step that looks at an unique column and deduplicates based on that.
As we don't record duplicate assignments in the database we don't have that explicit deduplicate step but we do still have to apply DISTINCT as we are joining with other tables.
=> Deduplicate assignments with DISTINCT

lms/migrations/versions/f8ff7e49cbbf_dashboard_admin_table.py, lms/models/__init__.py, lms/models/dashboard_admin.py, lms/routes.py, lms/services/dashboard.py, lms/templates/admin/organization/show.html.jinja2, lms/views/admin/organization.py, tests/unit/lms/services/dashboard_test.py, tests/unit/lms/views/admin/organization_test.py
For:
- https://github.com/hypothesis/lms/issues/6378
This PR adds a table/model and admin pages to handle manual access to some schools admins to the dashboards.
**This PR doesn't yet take into consideration those admins to give access to the dashboards.**
```
dev run-test-pre: PYTHONHASHSEED='2402316231'
dev run-test: commands[0] | alembic upgrade headINFO  [alembic.runtime.migration] Context impl PostgresqlImpl.INFO  [alembic.runtime.migration] Will assume transactional DDL.INFO  [alembic.runtime.migration] Running upgrade 1337584e2b07 -> f8ff7e49cbbf, Create the dashboard_admin table.
```
- Play with the admin pages at …
=> Manage dashboard admins in the admin pages

lms/services/assignment.py, lms/services/course.py, lms/views/dashboard/api/assignment.py, lms/views/dashboard/api/course.py, tests/unit/lms/services/assignment_test.py, tests/unit/lms/services/course_test.py, tests/unit/lms/views/dashboard/api/assignment_test.py, tests/unit/lms/views/dashboard/api/course_test.py
Continue the cleanup from https://github.com/hypothesis/lms/commit/886d271337d81c9353f0d975d426b8258c12bfb7 and  3cee7f526af272e7adc4d15ed6dccb1a2e8bf1af
- Move assignment related methods from course service to AssignmentService.
- Apply assignment deduplication (when joining by courses) in get_assignments.
- Remove CourseService.get_assignment and replace it with calls to AssignmentService.get_assignments.
=> Move assignment related methods to AssignmentService

lms/services/assignment.py, lms/services/course.py, lms/services/h_api.py, lms/views/dashboard/api/assignment.py, lms/views/dashboard/api/course.py, lms/views/dashboard/api/user.py, tests/unit/lms/services/assignment_test.py, tests/unit/lms/services/course_test.py, tests/unit/lms/services/h_api_test.py, tests/unit/lms/views/dashboard/api/assignment_test.py, tests/unit/lms/views/dashboard/api/course_test.py, tests/unit/lms/views/dashboard/api/user_test.py
Requires and needs to be deployed together with: https://github.com/hypothesis/h/pull/8795
This is just a name change (pluralizing) and type change str vs list[str]. 
It doesn't introduce a new filter option on any LMS endpoint but filtering by multiple assignments should be easier to implement  after this change.
Sanity check all three levels of the dashboards.
=> Match changes in H's API to allow filtering by multiple assignments

lms/services/jwt.py, lms/views/exceptions.py, tests/functional/lti_certification/v13/core/test_bad_payloads.py
These are useful to debugging issues in production. We log the same message displayed to users.
Found this while re-running the LTI1.3 certification, which involves checking errors from the logs and report them back.
=> Log validation errors to the console as debug entries.

tests/functional/lti_certification/v13/grading/test_assignment_and_grading.py
We run this script once a year for the LTI1.3 certification. Adapt it to the latest set of changes since last year.
=> Adjust grading API certification test to account for API changes

lms/services/course.py, lms/views/dashboard/api/course.py, tests/unit/lms/services/course_test.py, tests/unit/lms/views/dashboard/api/course_test.py
For:
- https://github.com/hypothesis/lms/issues/6418
Same as: https://github.com/hypothesis/lms/pull/6430 but for courses.
- Play with the API at something like: 
http://localhost:8001/api/dashboard/organizations/local.lms.org.LDtcl7EUTeW2UERPJLAVtA/courses?assignment_ids=397
=> Filter courses by assignment IDs

lms/views/api/exceptions.py, tests/unit/lms/views/api/exceptions_test.py
When handling refreshable `OAuth2TokenError` exceptions, don't try to look up the existing access token in the special case where the token that needs to be refreshed is the Canvas Studio admin user's token, instead of the current user's access token.
This issue caused Canvas Studio assignment launches to fail for users if:
- The Canvas Studio admin token needed a refresh
- The current user had not directly authorized with Canvas Studio. This primarily means students, since the instructor will authorize with Canvas Studio when they create the assignment.
In this scenario the `refresh` field was omitted from the response, so users would see a non-working "Authorize Hypothesis" screen, instead of having the frontend initiate an admin user token refresh.
Fixes …
=> Fix Canvas Studio admin token refreshes triggered by students

lms/extensions/feature_flags/__init__.py, lms/models/assignment.py, lms/models/oauth2_token.py, lms/product/plugin/__init__.py, lms/product/plugin/course_copy.py, lms/product/plugin/plugin.py, lms/product/product.py, lms/services/application_instance.py, lms/services/digest.py, lms/services/group_info.py, lms/services/moodle.py, lms/validation/__init__.py, lms/validation/_lti_launch_params.py, lms/views/admin/_schemas.py, lms/views/admin/assignment.py, lms/views/admin/organization.py, lms/views/api/blackboard/files.py, lms/views/api/canvas/authorize.py, lms/views/api/canvas/files.py, lms/views/api/canvas/pages.py, lms/views/api/d2l/authorize.py, lms/views/api/d2l/files.py, lms/views/api/moodle/files.py, lms/views/api/moodle/pages.py, lms/views/lti/basic_launch.py, pyproject.toml
Make necessary changes to allow a clean mypy run after the change
=> Enable mypy's check_untyped_defs

lms/static/scripts/frontend_apps/components/GroupConfigSelector.tsx, lms/static/scripts/frontend_apps/components/StudentSelector.tsx, lms/static/scripts/frontend_apps/components/test/GroupConfigSelector-test.js, lms/static/scripts/frontend_apps/components/test/StudentSelector-test.js, package.json, yarn.lock
Update to latest frontend-shared, and replace usages of `SelectNext` with its `Select` drop-in replacement.
The frontend-shared update also brings the new UI improvements on `Select` components, around focus ring and selected option/s.
* https://github.com/hypothesis/frontend-shared/pull/1604
* https://github.com/hypothesis/frontend-shared/pull/1605
=> Replace SelectNext usages with Select

lms/views/dashboard/api/course.py
I found a typo while working on https://github.com/hypothesis/lms/pull/6453, and since I don't know how long will it take to merge that, I decided to extract the fix here.
See [my comment](https://github.com/hypothesis/lms/pull/6453/files#r1684180579) there for context.
=> Fix typo in prop name inside CoursesMetricsSchema

lms/static/scripts/frontend_apps/utils/api.ts, lms/static/scripts/frontend_apps/utils/test/api-test.js
While working on something else, I realized we were making API calls with a question mark at the end of the URL when providing an empty object as query params, or an object where all the props would end-up resulting in an ignored param, like an empty array.
This PR changes the logic a bit to avoid this, which is technically not incorrect, but it is aesthetically nicer to avoid the question mark when not needed.
=> Avoid question mark in API calls without query string

lms/services/hubspot/_client.py, lms/services/hubspot/service.py, lms/tasks/hubspot.py, tests/unit/lms/services/hubspot/_client_test.py, tests/unit/lms/services/hubspot/service_test.py, tests/unit/lms/tasks/hubpost_test.py
For:
- https://github.com/hypothesis/lms/issues/6159
This PR needs a follow up to schedule the task in h-periodic.
To summarize the process we:
- Fetch HubSpot companies with tasks.hubspot.refresh_hubspot_data
- We generate monthly usage reports for thos companies with task.organization.schedule_monthly_deal_report
now, with this commit we:
- Push the calculated numbers (unique user and teachers) to the corresponding fields in HubSpot companies.
Describing here the process I followed locally to test this end to end.
- Fetch all HubSpot companies:
```
refresh_hubspot_data.delay()
```
- Modify some of these companies to match your local organizations, eg:
```update hubspot_company set lms_organization_id = 'local.lms.org.FFIHD9f1RwyLPfx14zM_7Q' where id = 11;```
- Generate/Insert some …
=> Task to export calculated numbers of the monthly reports back to HubSpot

lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/OrganizationActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/OrganizationActivityFilters.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/OrganizationActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/OrganizationActivityFilters-test.js
This PR introduces a new component that wraps the filtering dropdowns for the dashboard homepage. For now, dropdowns will show all courses, all assignments and all students, but this may change later as we [clarify expected behaviors](https://github.com/hypothesis/lms/pull/6453#issuecomment-2242651989).
Filtering components for other sections will be implemented separately. You can find why I choose this approach here: https://github.com/hypothesis/lms/pull/6416#issuecomment-2236120392
The only purpose of this PR is to introduce the visual components, and handle the logic to display selected filters and forward them to the metrics endpoint and also filter among themselves. There are a few missing things that will be implemented afterwards:
- Load paginated information in filter dropdowns. …
=> Create filters component for dashboard organization section

lms/static/scripts/frontend_apps/components/dashboard/OrganizationActivityFilters.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/OrganizationActivityFilters-test.js
There are some cases in which we could have students without a display name, if they haven't launched an assignment before May 9th, 2024.
For the students table we decided to show a placeholder and a helper text explaining what that means (see https://github.com/hypothesis/lms/pull/6382), but for the filters dropdown we think it makes more sense to completely ignore those students. Since you don't know who they are, it's not very likely you want to filter by them.
This decision might change in the future.
Closes https://github.com/hypothesis/lms/issues/6457
=> Exclude students without a name from students filter dropdown

lms/static/scripts/frontend_apps/components/dashboard/DashboardActivityFilters.tsx, lms/static/scripts/frontend_apps/components/dashboard/OrganizationActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/DashboardActivityFilters-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/OrganizationActivity-test.js
After a few comes and goes, I ended up with the conclusion that it would be easier to have different filtering components per section.
However, after starting to apply filters in the second ~second~ PR, I realized we can in fact reuse the components.
This PR renames the `OrganizationActivityFilters` component, to a more generic `DashboardActivityFilters`, so that it can be reused in places other than the organization section, without causing confusion.
=> Rename OrganizationActivityFilters to DashboardActivityFilters

lms/views/dashboard/api/course.py, tests/unit/lms/views/dashboard/api/course_test.py
(these IDs are environment dependent)
- Courses with assignments IDs from different courses returns multiple courses:
http://localhost:8001/api/dashboard/courses?assignment_id=399&assignment_id=398
- Filter courses by user ids of different courses returns multiple courses:
http://localhost:8001/api/dashboard/courses?h_userid=acct:f6c3ed0edd8a4013bfc8d0c22b9eca@lms.hypothes.is&acct:f6c3ed0edd8a4013bfc8d0c22b9eca@lms.hypothes.is
=> Add assignment and user filters to the courses API

lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/CourseActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/DashboardApp.tsx, lms/static/scripts/frontend_apps/components/dashboard/OrganizationActivity.tsx, lms/static/scripts/frontend_apps/types.d.ts, lms/static/scripts/frontend_apps/utils/hooks.ts, lms/static/scripts/frontend_apps/utils/test/hooks-test.js, lms/views/dashboard/views.py, package.json, yarn.lock
Closes #6458 
Add a new `useDocumentTitle` hook that sets `document.title`, and use it in all dashboard page/section components to ensure the page title is in sync with what's being displayed.
To make sure we don't forget calling it in future page components, this PR also adds a dev-env-only navigation listener which sets a placeholder page title right before navigation occurs.
1. Open the dashboard.
2. Navigate to other sections and observe the page title gets updated.
Titles should be the same that the backend sets on initial server-side renders, but we could potentially get rid of the backend logic entirely.
=> Make sure dashboard page titles update when navigating

rollup.config.js
We had some rollup config to replace `process.env.NODE_ENV` with their actual values, but incorrectly set to do it as a direct replacement.
That meant that if `NODE_ENV=production`, it would replace `process.env.NODE_ENV` by the literal value `production`, which is then treated as a variable, causing a `ReferenceError: production is not defined` error.
This PR fixes that by JSON-encoding the value of `process.env.NODE_ENV` before replacing it in code, as seen in the docs https://www.npmjs.com/package/@rollup/plugin-replace
=> Make sure process.env.NODE_ENV is stringified

pyproject.toml, tests/pyproject.toml, tests/unit/lms/models/organization_test.py
Compare sets instead of list to avoid any issues around ordering.
Failed here, I haven't seen it fail locally:
https://github.com/hypothesis/lms/actions/runs/10093618220/job/27909714767?pr=6467
=> Fix flaky organization model test

lms/static/scripts/frontend_apps/components/dashboard/DashboardActivityFilters.tsx, lms/static/scripts/frontend_apps/components/dashboard/OrganizationActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/DashboardActivityFilters-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/OrganizationActivity-test.js, lms/static/scripts/frontend_apps/utils/api.ts, lms/static/scripts/frontend_apps/utils/dashboard/hooks.ts, lms/static/scripts/frontend_apps/utils/dashboard/test/hooks-test.js, lms/static/scripts/frontend_apps/utils/test/url-test.js, lms/static/scripts/frontend_apps/utils/url.ts
This PR adds a new  `useDashboardQueryFilters` hook that can be used together with `DashboardActivityFilters` to a) initialize selected filters based on query parameters on active page, and b) persist selected filters in the query string, so that they can be propagated or bookmarked.
One change needed to achieve this was that `DashboardActivityFilters` now only handles the IDs of selected elements, instead of the full objects.
https://github.com/user-attachments/assets/d0081269-ec1f-4d75-9172-e03da930ea49
> [!NOTE]  
> As of now, every filter change will replace the last history entry. We can change this later with `{ replace: false }`, which makes it internally call `history.pushState()` instead of `history.replaceState()`.
1. Open the dashboard.
2. Navigate to "All courses".
3. Change …
=> Create hook to track selected dashboard filters in query string

lms/models/assignment.py, lms/models/grouping.py, lms/services/assignment.py, lms/services/grouping/service.py, tests/unit/lms/services/assignment_test.py, tests/unit/lms/services/grouping/service_test.py
For assignments, for which we allow null names in the database we convert empty "" names to null.
As a next step will do a migration to change the names already in the DB.
=> Trim leading and trailing whitespace for assignment and course names

lms/services/assignment.py, lms/services/dashboard.py, lms/services/user.py, lms/views/dashboard/api/assignment.py, lms/views/dashboard/api/course.py, lms/views/dashboard/api/user.py, lms/views/dashboard/views.py, tests/unit/lms/services/assignment_test.py, tests/unit/lms/services/dashboard_test.py, tests/unit/lms/services/user_test.py, tests/unit/lms/views/dashboard/api/assignment_test.py, tests/unit/lms/views/dashboard/api/course_test.py, tests/unit/lms/views/dashboard/api/user_test.py, tests/unit/lms/views/dashboard/views_test.py
Applies the same pattern as https://github.com/hypothesis/lms/pull/6467 to assignments and users
- Login into canvas as: eng+canvasteacher2@hypothes.is
- Launch https://hypothesis.instructure.com/courses/125/assignments/873 and access the dashboard from there
- You should be able to see the list of students of that assignment, the assignment in the course and the course in "All courses".
- There will be just a few of each entity (unless you use eng+canvasteacher2@hypothes.is a lot for testing).
- Include `eng+canvasteacher2@hypothes.is` as an admin the relevant organization, eg: http://localhost:8001/admin/orgs/1/dashboard-admins
- Refresh the all courses view, you should see now all courses on that org.
- Access any of the new courses and any of the assignments.
=> Enforce dashboard admin access for assignments and users

lms/static/scripts/frontend_apps/components/dashboard/DashboardActivityFilters.tsx, lms/static/scripts/frontend_apps/components/dashboard/OrganizationActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/DashboardActivityFilters-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/OrganizationActivity-test.js
> Depends on https://github.com/hypothesis/lms/pull/6476
Add control to clear all selected dashboard filters in one go.
The button only appears if at least one filter is selected.
=> Add control to clear all selected dashboard filters

lms/static/scripts/frontend_apps/utils/hooks.ts
This is a small fix for a dev-only piece of logic.
In https://github.com/hypothesis/lms/pull/6469 we added an event handler that sets a placeholder document title used to ensure we don't forget to set proper titles for new URLs in future. However, that event did not take into consideration navigations where the pathname does not change, like when setting dashboard filters in the query.
Those should be considered "the same page", and therefore they don't need a different title.
With the changes in this PR we only set the placeholder title right before navigating to a different path.
=> Do not set document title placeholder if pathname didn't change

lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/CourseActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js
Remove the `Assignment:` title prefix in the dashboard assignment section.
This makes it more consistent with the course section, where no prefix is used.
Before:
After:
> This PR is the "counterpart" of https://github.com/hypothesis/lms/pull/6468
=> Remove assignment title prefix

lms/static/scripts/frontend_apps/components/dashboard/DashboardActivityFilters.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/DashboardActivityFilters-test.js
With this PR we are ensuring selected filters in one dropdown affect the values displayed in the other dropdowns, regardless the order in which they are selected.
In the home page, when no filters are applied, we start displaying the full list of courses, assignments and students. As soon as a value is changed in any of those, the other two will reload and get filtered by the just selected value.
For example, if we select a student, we will only show courses and assignments that student is part of.
If, instead, we select a course, we will show only assignments and students that are part of that course, etc.
To verify the params are being taken into consideration by the backend, apply this diff:
```diff
diff --git a/lms/views/dashboard/api/assignment.py …
```
=> Make dashboard selected filters affect each other

lms/static/scripts/frontend_apps/components/dashboard/DashboardActivityFilters.tsx
Adjust layout for dashboard filters to make sure selects are not "pushed" back when the clear filters button appears.
Previously, we ensured a minimum width of the selects by placing them in a "half-width" container, but since the clear button is also part of this container, selects had to share the space with it.
Now selects are rendered with an auto width, overwriting their default full width, but have a minimum 180px width so that they don't look too small at first.
Before:
https://github.com/user-attachments/assets/7fd41e0d-652e-4a80-bbab-ee6013d27532
After:
https://github.com/user-attachments/assets/6d3bb710-7e4b-499c-9054-b00f2e526b7a
=> Avoid filters layout changes when clear button appears

lms/migrations/versions/e5a9845d55d7_clean_grouping_and_assignment_titles.py
Since https://github.com/hypothesis/lms/pull/6472 we do the same in the python code, we trim new assignment and course titles. We also normalize empty (``) titles to null.
This PR does the same for existing titles in the DB with a DB migration.
```
dev run-test-pre: PYTHONHASHSEED='378749627'
INFO  [alembic.runtime.migration] Running upgrade f8ff7e49cbbf -> e5a9845d55d7, Clean grouping and assignment titles.
Assignment titles updated: 5
Empty assignment titles: …
```
=> Trim whitespace of existing assignment and grouping titles

lms/services/assignment.py, tests/unit/lms/services/assignment_test.py
[Most of these come from the original creation of the table](https://metabase.hypothes.is/question/1277-assignments-without-names-by-date), where we only had the title IDs.
=> Exclude empty titled assignments from get_assignments

lms/static/scripts/frontend_apps/utils/api.ts, lms/static/scripts/frontend_apps/utils/test/url-test.js, lms/static/scripts/frontend_apps/utils/url.ts
Change the type of query params provided to `apiCall` and `useAPIFetch` to be less strict and allow keys with `undefined` value (`Record<string, string | string[] | undefined>` instead of `Record<string, string | string[]>`).
Then, simply skip params with undefined value when serializing them.
This simplifies userland code, where we no longer need to check if a value is set in every place, in order to make an API call.
Also, passing an empty array currently has the same effect as not passing the param at all. Allowing `undefined` just makes it more convenient but also intuitive, as it's fair to expect a param which is undefined to be just ignored.
Some cases where this will simplify code:
* We won't have to fall back to an empty array for conditional params: …
=> Allow query params with value undefined in api calls

lms/static/scripts/frontend_apps/components/dashboard/test/OrganizationActivity-test.js
Add one extra test to `OrganizationActivity-test` to cover the behavior when `organization_public_id` is defined in dashboard config.
=> Add test to cover the presence of organization_public_id in dashboard config

lms/services/dashboard.py, lms/views/dashboard/api/assignment.py, lms/views/dashboard/api/course.py, lms/views/dashboard/api/user.py, lms/views/dashboard/views.py, tests/unit/lms/services/dashboard_test.py, tests/unit/lms/views/dashboard/api/assignment_test.py, tests/unit/lms/views/dashboard/api/course_test.py, tests/unit/lms/views/dashboard/api/user_test.py, tests/unit/lms/views/dashboard/views_test.py
For:
- https://github.com/hypothesis/lms/issues/6480
Reuse the existing admin_organization_ids mechanism to allow and filter courses to one organization.
We don't just filter by orgazaniation_id because we'd need to solve authorization seperantly. This seems like the best compromise solution that doesn't require a lot of extra code for staff members. 
Use https://github.com/hypothesis/lms/pull/6483 for easier testing
- Go into the admin pages, find an organization with local active
- Make sure you didn't add yourself as an admin to the local organization.
- Navigate thru all three levels. Get results back.
=> Filter and allow access for organizations to staff members

lms/static/scripts/frontend_apps/utils/dashboard/hooks.ts, lms/static/scripts/frontend_apps/utils/dashboard/test/hooks-test.js
Fix an issue when using `useDashboardFilters` in a non-base URL.
I assumed `navigate(...)` would keep current path when only a query string was provided (as in `navigate('?foo=bar')`), but while working on assignment and course sections filters, I realized this is not the case.
Instead, that takes you back to the base URL, with that query string, as if `navigate('/?foo=bar')` would have been used instead.
This PR ensures current `location` is preserved when calling `navigate`, and only the query string is changed.
=> Keep current location when navigating in useDashboardFilters

lms/js_config_types.py, lms/resources/_js_config/__init__.py, lms/routes.py, lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/CourseActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/DashboardActivityFilters.tsx, lms/static/scripts/frontend_apps/components/dashboard/OrganizationActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/DashboardActivityFilters-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/OrganizationActivity-test.js, lms/static/scripts/frontend_apps/config.ts, lms/templates/admin/organization/show.html.jinja2, lms/views/admin/organization.py, tests/unit/lms/resources/_js_config/__init___test.py, tests/unit/lms/views/admin/organization_test.py
Include a public_id parameter to access the dashboards when launched from the organization view in the admin pages
- Go into the admin pages, find an organization with local active course
- Make sure you didn't add yourself as an admin to the local organization.
- Navigate thru all three levels. Get results back.
=> Organization dashboard entry point for staff

lms/migrations/versions/ca27e52b7303_add_missing_indexes.py, lms/models/assignment_membership.py, lms/models/user.py
- Add index on Assignment Membership.lti_role_id
While this is part of the PK of the table it doesn't have an index from
when we query it on its own.
- Index for faster query of unique H users
```
dev run-test-pre: PYTHONHASHSEED='4043195568'
INFO  [alembic.runtime.migration] Will assume transactional DDL.INFO  [alembic.runtime.migration] Running upgrade e5a9845d55d7 -> ca27e52b7303, Add missing indexes for dashboard queries.
```
=> Create new indexes to speed up dashboard queries

lms/js_config_types.py, lms/resources/_js_config/__init__.py, tests/unit/lms/resources/_js_config/__init___test.py
This way we avoid having to deal with undefined vs null values in the frontend.
Fixes: https://hypothesis.sentry.io/issues/5664280137/?referrer=slack&notification_uuid=14c12951-d0d0-4d5c-9f08-3d24eddee6d7&alert_rule_id=4849653&alert_type=issue
- Open the dashboard as a staff member
- You'll get an exception in main,  it will be fixed in this branch.
=> Don't include public_id on the dashboard config when not present

lms/views/admin/assignment.py, lms/views/admin/course.py, tests/unit/lms/views/admin/assignment_test.py, tests/unit/lms/views/admin/course_test.py
This allows to have access to the data at all levels using the public_id mechanism
- Go to the admin pages, find an assignment, launch the dashboard.
- You'll see data at that level and all the way to "all courses".
- Repeat the same process launching from a course
=> Scope dashboards to an organization when launched from the course and assignment views

lms/static/scripts/frontend_apps/components/dashboard/AllCoursesActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/DashboardApp.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AllCoursesActivity-test.js, lms/static/scripts/frontend_apps/components/test/AppRoot-test.js
With the removal of the organization ID in the URL, and references to the organization in the dashboard, there was a component left still incorrectly referencing the organization concept.
This PR renames `OrganizationActivity` to `AllCoursesActivity` to solve that.
=> Rename OrganizationActivity to AllCoursesActivity

lms/static/scripts/frontend_apps/components/dashboard/AllCoursesActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/CourseActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/CourseActivity-test.js, lms/static/scripts/frontend_apps/utils/dashboard/navigation.ts
> Depends on https://github.com/hypothesis/lms/pull/6505
Continuing with the work from https://github.com/hypothesis/lms/pull/6453, this PR adds filters to the course section.
The main difference here is that the courses dropdown starts with the "active" course (the one represented in the URL) pre-selected. Then, selecting a different course does not apply a filter to the activity table, as we are implicitly filtering by a single course. Instead, once a different course is selected, we navigate to that course and propagate the rest of the filters there.
Additionally, if "All courses" is selected, or the "active" course is deselected, we navigate to "All courses" with the assignments and students filters preserved.
This behavior might change in future, as the product decision is still …
=> Add filters to course activity section

lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/dashboard/AllCoursesActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/CourseActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/DashboardActivityFilters.tsx
This PR adds some extra API type definitions in preparation for the pagination handling of the filters dropdowns.
Additionally, and to avoid colliding type names, it refactors a few of the existing metrics-related type names.
=> Add dashboard API response types for filters endpoints

lms/templates/admin/macros.html.jinja2
Currently the template duplicates the name in both columns:
Fix the templated to expose the context ID as the header suggests.
=> Correctly display context ID on courses lists in the admin pages

lms/migrations/versions/afa53b7464be_add_indexes_for_names_we_sort_by.py, lms/models/assignment.py, lms/models/grouping.py, lms/models/user.py
We use these to sort list in their respective queries, add the missing indices to speed them up
```
dev run-test-pre: PYTHONHASHSEED='3761224678'
INFO  [alembic.runtime.migration] Running upgrade ca27e52b7303 -> afa53b7464be, Add indexes for names we sort by in the dashboards.
```
=> Add indices for courses, assignment and user names

lms/migrations/versions/d8d33d882b88_add_index_for_membership_user_id.py, lms/models/assignment_membership.py
Similar to assignment_membership.lti_user_id, the other column part of this table's composite  primary key but often queried on it's own.
Create an index just on the user_id column to be used when queried in isolation.
`tox -e dev --run-command 'alembic upgrade head'`                                              
```
INFO  [alembic.runtime.migration] Running upgrade afa53b7464be -> d8d33d882b88, Add index for membership.user_id
```
=> Add index on assignment_membership.user_id

lms/static/scripts/frontend_apps/components/dashboard/test/AllCoursesActivity-test.js
Adapt `AllCoursesActivity-test` to the new way to read the organization public ID from the URL params instead of the dashboard config.
=> Fix AllCoursesActivity test

lms/static/scripts/frontend_apps/components/dashboard/DashboardActivityFilters.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/DashboardActivityFilters-test.js
This PR rolls back the changes introduced in https://github.com/hypothesis/lms/pull/6459, as we have realized excluding students without a `display_name` from the students dropdown, makes it harder to debug when something goes wrong.
Instead, we are now displaying a `Student name unavailable (ID: X)` placeholder, where X are the first 5 characters of the user LMS ID.
For debugging purposes, we include the full ID in the option's `title` prop.
In dev envs it might be harder to have a student without a name, so one way to reproduce that is by checking what the `/api/dashboard/students` endpoint returns for you, copying it, and pasting one student in `user.py` but with `display_name: None`, like this:
```diff
--- a/lms/views/dashboard/api/user.py
+++ b/lms/views/dashboard/api/user.py
@@ …
```
=> Include students without name in students dropdown

lms/migrations/versions/18109b584a5b_add_assignment_course_relationship.py
Add a new relationship that links courses to assignment
Migration auto generated from:
- https://github.com/hypothesis/lms/pull/6520
More context and the rest of the changes to follow on:
- https://github.com/hypothesis/lms/pull/6517
```dev run-test-pre: PYTHONHASHSEED='1184398793'
INFO  [alembic.runtime.migration] Running upgrade d8d33d882b88 -> 18109b584a5b, Add assignment course relationship.````
=> Migration for assignment.course_id

lms/services/assignment.py, lms/views/lti/basic_launch.py, tests/unit/lms/services/assignment_test.py, tests/unit/lms/views/lti/basic_launch_test.py
Make sure we keep the relationship of course / assignment up to date with each launch.
This information is also kept in `AssigmentGrouping`
More context and the rest of the changes to follow on:
- https://github.com/hypothesis/lms/pull/6517
Planned PRs:
- ~https://github.com/hypothesis/lms/pull/6519~
- ~https://github.com/hypothesis/lms/pull/6520~
- https://github.com/hypothesis/lms/pull/6525
- Backfill assignment.course_id from existing values in assignment_grouping
- Code changes to replace the current custom query by the SQLA relationship for assignment.course.
- Open any assignment, eg: https://hypothesis.instructure.com/courses/125/assignments/873
- Check that assigment.course_id has been updated:
`docker compose exec postgres psql -U postgres -c "select assignment.title assignment, …
=> Store and update the assignment / course relationship

lms/migrations/versions/f6c442c861c4_backfill_assignment_course_id.py
Needs to be merged after https://github.com/hypothesis/lms/pull/6525 
---
More context and the rest of the changes to follow on:
- https://github.com/hypothesis/lms/pull/6517
Planned PRs:
- ~https://github.com/hypothesis/lms/pull/6519~
- ~https://github.com/hypothesis/lms/pull/6520~
- https://github.com/hypothesis/lms/pull/6525
- **[Backfill assignment.course_id from existing values in assignment_grouping](https://github.com/hypothesis/lms/pull/6526)** <-- This PR
- Code changes to replace the current custom query by the SQLA relationship for assignment.course.
```tox -e dev --run-command 'alembic upgrade head'```        
```
dev run-test-pre: PYTHONHASHSEED='470380643'
;dev …
```
=> Backfill assignment.course_id from existing values in assignment_grouping

lms/static/scripts/frontend_apps/components/dashboard/DashboardApp.tsx
Remove link to `Settings` from the dashboard header.
We considered redirecting to the email settings for now, but auth was a bit tricky, so we ended up with a placeholder alerting that it was not implemented.
But even if we would have been able to redirect there, I'm not sure that was the right place. We should have first either a more generic settings page, or a dashboard-related one.
So for the MVP, I suggest we remove it entirely.
=> Remove dashboard settings entry point until we have a place to redirect

lms/static/scripts/frontend_apps/components/dashboard/DashboardActivityFilters.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/DashboardActivityFilters-test.js, lms/static/scripts/frontend_apps/utils/api.ts, lms/static/scripts/frontend_apps/utils/test/api-test.js
Add logic to load paginated items in filters dropdowns.
With the changes introduced here, dropdowns will initially load the first page of results, but when scrolling close to the bottom 20px, it will start loading the next page and append the results to the existing ones, if any.
Considerations:
* When filters change, all depending dropdowns will reset loaded pages and start with the first one again.
* When loading the first page, the dropdown will appear disabled, but when loading the next pages, users will still be able to interact with existing pages, and an extra option will be displayed at the very bottom to indicate further data loading.
* Ideally, we should find the balance between not loading data too soon, but also not showing the option loading indicator if possible.
[Grabación …
=> Add pagination handling to dashboard filters

lms/models/assignment.py, lms/views/admin/assignment.py, tests/unit/lms/models/assignment_test.py, tests/unit/lms/services/dashboard_test.py, tests/unit/lms/views/admin/assignment_test.py, tests/unit/lms/views/dashboard/api/assignment_test.py
Use a standard SQLA relationship instead of custom code to access an assignment's course.
This should just work as expected, must changes are about adjusting the tests.
More context and the rest of the changes to follow on:
- https://github.com/hypothesis/lms/pull/6517
Planned PRs:
- ~https://github.com/hypothesis/lms/pull/6519~
- ~https://github.com/hypothesis/lms/pull/6520~
- ~~https://github.com/hypothesis/lms/pull/6525~~
- ~~https://github.com/hypothesis/lms/pull/6526~~
- [Code changes to replace the current custom query by the SQLA relationship for assignment.course.](https://github.com/hypothesis/lms/pull/6528) <-- This PR
=> Replace query to fetch an assignments course by the new relationship

lms/js_config_types.py, lms/resources/_js_config/__init__.py, lms/routes.py, lms/security.py, lms/static/scripts/frontend_apps/components/AppRoot.tsx, lms/static/scripts/frontend_apps/components/dashboard/AllCoursesActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/CourseActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/DashboardActivityFilters.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AllCoursesActivity-test.js, lms/static/scripts/frontend_apps/config.ts, lms/views/admin/assignment.py, lms/views/admin/course.py, lms/views/admin/organization.py, lms/views/dashboard/views.py, tests/unit/lms/resources/_js_config/__init___test.py, tests/unit/lms/security_test.py, tests/unit/lms/views/admin/assignment_test.py, tests/unit/lms/views/admin/course_test.py, tests/unit/lms/views/admin/organization_test.py
For:
- https://github.com/hypothesis/lms/issues/6509
- We have now duplicate entry points URL, the ones scoped to one org (for staff) and the rest (for the LMS users)
- The frontend fetches the revalvnt public_id from the path parameter instead of a js_config value
- API endoints still take a public_id as any other filtering option
=> Switch approach for staff dashboard access to org scoped URL

lms/static/scripts/frontend_apps/components/dashboard/AllCoursesActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/CourseActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/DashboardActivityFilters.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AllCoursesActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/CourseActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/DashboardActivityFilters-test.js
Part of https://github.com/hypothesis/lms/issues/6490
Following the decision tracked in https://github.com/hypothesis/lms/issues/6490#issuecomment-2271562287, this PR updates the `DashboardActivityFilters` so that:
1. It brings some of the API changes made in https://github.com/hypothesis/lms/pull/6524, expecting `courses`, `assignments` and `students` as the main props.
2. Making `courses` and `assignments` accept two shapes:
* `ActivityFilterSelection`: 
```ts
{
selectedIds: string[];
onChange: (newSelectedIds: string[]) => void;
}
```
This makes everything work as it has been so far. Courses are loaded from the API, and the props determine which are selected, and what to do when selection changes.
* `ActivityFilterItem<T extends Course | Assignment>`:
```ts
{
activeItem: T;
onClear: () …
```
=> Support single active items in dashboard filters

lms/services/dashboard.py, tests/unit/lms/services/dashboard_test.py
Fixes:
- https://github.com/hypothesis/lms/issues/6534
LTI roles are course based but we were granting access to individual assignments based on the instructor having launched it in the past.
Previous commits fixed this for queries spanning multiple elements but here we are fixing the permission check for individual assignments.
- Login with `eng+canvasteacher2@hypothes.is`, launch an assignment you didn't launch before, for example:
https://hypothesis.instructure.com/courses/125/assignments/6527
- Access the dashboard, the assignment will be visible and you can access it.
- Login with `eng+canvasteacher2@hypothes.is`
- Access the dashboard without accessing the same assignment.
- The assignment would be listed but you'll get an error when trying to access it
- Repeat the last step, you …
=> Grant access to single assignments based on course membership

lms/services/assignment.py, lms/services/course.py, lms/services/dashboard.py, lms/services/user.py, lms/views/lti/basic_launch.py, lms/views/lti/deep_linking.py, tests/unit/lms/services/assignment_test.py, tests/unit/lms/services/course_test.py, tests/unit/lms/services/dashboard_test.py, tests/unit/lms/services/user_test.py, tests/unit/lms/views/lti/basic_launch_test.py, tests/unit/lms/views/lti/deep_linking_test.py
Fixes:
- https://github.com/hypothesis/lms/issues/6516
LTI roles apply only to the course level although we currently store
them at the assignment level (AssignmentMembership).
When we use instructor_h_userid to get the list of assignments a
instructor has access to we should base the decision on:
- Courses/Assignments/Users that belongs to a course where the user is an instructor.
instead of the current:
- Courses/Assignments/Users this user launched as an instructor.
This PR change the behaviour for assignments and users to settle on the course level access.
Sanity check the whole dashboard behaviour navigating around at the courses, assignment and students levels.
=> Fix query instructor_h_userid filter for assignments and users

lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js
Part of https://github.com/hypothesis/lms/issues/6490
Add filtering controls to the dashboard's assignment view, in a way that it conforms with what's described in https://github.com/hypothesis/lms/issues/6490#issuecomment-2271562287
[Grabación de pantalla desde 2024-08-08 10-41-09.webm](https://github.com/user-attachments/assets/2f0588d5-21f6-4103-9da8-84d4caa526c0)
As it was described in https://github.com/hypothesis/lms/pull/6532, the clear filters button only clears the students filter, as otherwise we would be navigated away from the active page.
Once this is merged I will open a discussion around this, to present the potentially confusing behavior, and make a decision accordingly.
=> Add filters to dashboard assignment section

lms/services/assignment.py, lms/services/course.py, lms/services/user.py
Improve performance of these queries removing the organization join on the admin_organization_ids clause's subquery.
No behaviour changes required, no test needed tweaking either, just a sanity check open the dashboard as an admin (ie from the admin pages) and navigate around.
=> Avoid unnecessary joins to filter entities by organization IDs

tests/unit/lms/services/assignment_test.py
Query must return results in a different order resulting in a test failure. 
Cast the query and expecting value to a set to ignore ordering.
=> Fix flaky test that relies on random order of query

package.json, yarn.lock
Update to the latest frontend-shared library, which among other things, brings the orderable column icon indicators.
It also removes `SelectNext`, which we wer no longer using, as LMS was already migrated to the `Select` and `MultiSelect` symbols.
=> Update to latest frontend-shared library

lms/services/dashboard.py, lms/static/scripts/frontend_apps/components/dashboard/AllCoursesActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/CourseActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/DashboardActivityFilters.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AllCoursesActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/CourseActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/DashboardActivityFilters-test.js, tests/unit/lms/services/dashboard_test.py
Closes #6541 
Rename `public_id` to `org_public_id` to make it more clear what entity it refers to.
Go to the [admin](http://localhost:8001/admin), find an organization, launch the dashboard from there, and sanity-check that data is correct.
=> Rename public_id query param to org_public_id

lms/static/scripts/frontend_apps/utils/fetch.ts, lms/static/scripts/frontend_apps/utils/test/fetch-test.js
Make sure the result from `useFetch` is reset right before retrying.
Without these changes, `isLoading` is kept as false, and the error is still set, if any.
=> Reset fetch result when retrying useFetch

lms/migrations/versions/7858a12c4e4a_add_index_for_user_deduplication.py, lms/models/user.py
For:
This shows as an expensive step on user queries query plans:
```Sort Key: user_1.h_userid, user_1.updated DESC```
which originates here:
https://github.com/hypothesis/lms/blob/main/lms/services/user.py#L183
Add an explicit index for it to speed it up.
This should also helpful for any work that refactors the "user" table and/or denormalizing this information.
`tox -e dev --run-command 'alembic upgrade head'`                           ```
```
dev run-test-pre: PYTHONHASHSEED='1727528162'
INFO  [alembic.runtime.migration] …
=> Add index for the users deduplication step

lms/resources/_js_config/__init__.py, lms/validation/authentication/_bearer_token.py, lms/views/dashboard/views.py, tests/unit/lms/resources/_js_config/__init___test.py, tests/unit/lms/views/dashboard/views_test.py
For:
- https://github.com/hypothesis/lms/issues/6550
There are three relevant duration here:
- The length of the cookie for the dashboard
- The length of the token that is encoded in the cookies
- The length of the token that's part of JSConfig
This PR makes sure that all these match and increases its duration to 7
days.
- Open the dashboard as a LMS user check the duration of the cookie in the browser.
- Take the value from the cookie, the JWT, it should have a exp value matching the cookie's
- Check the API calls make to the API endpoints, this token's exp value should also be one week long.
=> Match dashboard cookie and token lifetimes and increase its duration

lms/migrations/versions/3d0c022c716c_add_missing_indexes_for_fks.py, lms/models/assignment.py, lms/models/assignment_grouping.py, lms/models/assignment_membership.py, lms/models/grouping.py
Non-unique FKs don't get automated indexes on the referencing side. 
`AssignmentGrouping` and `AssignmentMembership` have a primary key composed of two foreign keys, while the PK has an index there's no index on the individual columns that we often use in isolation.
- Assignment.course_id, FK without an index
- GroupingMembership.user_id, FK without an index
- AssignmentGrouping.assignment_id, FK without and index, although part of the PK of AssignmentGrouping
- AssignmentGrouping.grouping_id, FK without and index, although part of the PK of AssignmentGrouping
- AssignmentMembership.assignment_id, FK without and index, although part of the PK of AssignmentMembership
--- 
```
dev run-test-pre: PYTHONHASHSEED='4146439829'
dev run-test-pre: …
```
=> Create indexes for foreign keys missing them

lms/js_config_types.py, lms/views/dashboard/api/assignment.py, tests/unit/lms/views/dashboard/api/assignment_test.py
Often assignments have the same names and belong to courses with also the same names.
To help disambiguate them we expose the creation dates of the assignments in the API.
Slack thread: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1722947283308589
The assignment creation date can be found in the responses of:
- Dropdown API call
- Single assignment API GET
- Course assignments list with metrics
=> Expose assignment creation dates on the API

lms/services/h_api.py, lms/views/dashboard/api/assignment.py, lms/views/dashboard/api/user.py, tests/unit/lms/views/dashboard/api/assignment_test.py, tests/unit/lms/views/dashboard/api/user_test.py
Needs: https://github.com/hypothesis/h/pull/8872
We are currently not counting page notes for the dashboards, include them in the count of annotations.
Slack thread: https://hypothes-is.slack.com/archives/C2C2U40LW/p1722868549707479?thread_ts=1722628855.186809&cid=C2C2U40LW
- As an instructor go to:
- Open the dashboards and see the annotations counts
- Open the same assignment as a student, make a page note
- Number goes up!
=> Count both annotation and page notes towards the annotation count

lms/static/scripts/frontend_apps/components/dashboard/AllCoursesActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/CourseActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/DashboardBreadcrumbs.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AllCoursesActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/CourseActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/DashboardBreadcrumbs-test.js, lms/static/scripts/frontend_apps/utils/api.ts, lms/static/scripts/frontend_apps/utils/dashboard/hooks.ts, lms/static/scripts/frontend_apps/utils/dashboard/test/hooks-test.js, lms/static/scripts/frontend_apps/utils/url.ts
Closes #6539 
Ensure links between dashboard views honor currently selected filters, so for example if we have selected a set of assignments in the "All courses" view and click on a course, those assignments are still selected when we go there.
> [!NOTE]  
> This PR is easier to review [ignoring whitespaces](https://github.com/hypothesis/lms/pull/6540/files?w=1)
The implemented logic and decision on what parameters to forward is described in https://github.com/hypothesis/lms/issues/6539, so just sanity check that it works as described there.
There are some edge cases I did not implement here, but we may need to later, like if you are in the assignment view, should the breadcrumbs include `assignment_id={id}` for the active assignment?
For now only filters manually selected by the user …
=> Propagate filters when navigating between dashboard views

lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/dashboard/DashboardActivityFilters.tsx, lms/static/scripts/frontend_apps/components/dashboard/FormattedDate.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AllCoursesActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/DashboardActivityFilters-test.js, lms/static/scripts/frontend_apps/utils/date.ts
> Depends on https://github.com/hypothesis/lms/pull/6554
> Closes #6556 
Add the assignment creation date to the assignments dropdown, to help disambiguate assignments with the same name.
The date is formatted based on the browser's locale.
=> Disambiguate assignment names in dashboard filters dropdown

lms/static/scripts/frontend_apps/components/dashboard/DashboardActivityFilters.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/DashboardActivityFilters-test.js
We have found some edge cases, grey areas and users confused by how our multi-select dashboard filters work.
We have plans to address those, by improving the UI and UX of the selects, making it more clear when you can select multiple items, and how to do it, but in the meantime, this PR changes filters to be single-select for now.
[Grabación de pantalla desde 2024-08-14 08-59-03.webm](https://github.com/user-attachments/assets/1d72e440-72b4-468a-9a54-28c6e558b060)
This will make it less confusing when we add the new multi-selects, as users which have already used the previous ones will see a clear visual change matching the new behavior.
This PR only replaces the use of `MultiSelect` with `Select`, but keeps the `DashboardActivityFilters` API untouched.
That means all changes we'll have …
=> Allow single selection in dashboard filters

lms/static/scripts/frontend_apps/components/dashboard/DashboardActivityFilters.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/DashboardActivityFilters-test.js
This PR fixes an overlook from https://github.com/hypothesis/lms/pull/6557, where the active assignment in the assignment view will render without a date in the filters listbox.
In that view that's the only assignment to be displayed, so disambiguating is not as critical, but the inconsistency with other views might be confusing.
This PR makes sure the date is rendered in that case as well.
Before:
After:
> [!NOTE]  
> This PR is easier to review [ignoring whitespaces](https://github.com/hypothesis/lms/pull/6566/files?w=1)
=> Ensure active assignments are rendered as selected ones

lms/security.py, lms/templates/admin/application_instance/show.html.jinja2, lms/views/lti/basic_launch.py, tests/unit/lms/security_test.py, tests/unit/lms/views/lti/basic_launch_test.py
**To merge on 19/8**
Enable the dashboards for all install without altering the DB state. To revert this just revert this PR and we'll read the DB again.
- Launch the dashboards.
=> Enable dashboard for all instructors

lms/services/user.py, tests/unit/lms/services/user_test.py
For:
While we do need to query AssignmentMembership to fetch any role related information we can bypass AssignmentMembership and assignment to just test for course membership based on the previous query.
```
SELECT grouping_membership.user_id
FROM grouping_membership
WHERE grouping_membership.grouping_id IN
(SELECT assignment_grouping.grouping_id
FROM assignment_grouping
JOIN assignment_membership ON assignment_membership.assignment_id = assignment_grouping.assignment_id
JOIN "user" ON "user".id = assignment_membership.user_id
WHERE "user".h_userid = 'acct:fa9cb7e6030416082ae66e9148abdf@lms.hypothes.is'
AND assignment_membership.lti_role_id in (SELECT lti_role.id FROM lti_role WHERE lti_role.scope = 'course' AND lti_role.type = …
```
=> Avoid AssignmentMembership join on get_user query

lms/migrations/versions/b39108c0cd35_index_on_assignment_title_is_not_null.py, lms/models/assignment.py
For:
A big time of the query time of get_assignments is spent finding assignments with not null titles.
Create an index on that condition trying to speed it up.
From the query plan:
```
Parallel Index Scan using ix__assignment_title on assignment  (cost=1833.94..114225.07 rows=74535 width=582) (actual time=5.866..60.334 rows=140 loops=3)
Index Cond: (title IS NOT NULL)
```
That 60ms out of a total of 80.
How much the query will improve will depend on the table stats, around 30 percent of the assignments have empty titles (imported from another table when we first created the assignment table), more info in https://stackoverflow.com/a/31966616
=> Create index to find non empty titles for assignments

lms/services/assignment.py
For:
In general a subquery is better for filtering, in this case because:
- It allows us to compose a query better, we don't have to worry about missing/duplicating a join
- It can be faster for non-correlated subqueries (ie queries that produce the same values for all rows). This should be the case here.
- They don't introduce duplicate rows, we can remove the distinct here.
###
No behaviour changes, to sanity check:
- Launch the dashboard and list assignments in the dropdown and for one particular course. 
- Use the student drop down to filter assignments.
=> Use a subquery instead of a join for the assignment user filter

package.json, yarn.lock
This PR updates to the latest version of `@hypothesis/frontend-shared`.
Once we merge this, all usages of `Select` will be updated to the [new look-and-feel](https://github.com/hypothesis/frontend-shared/issues/1658).
I will update the selects in the dashboard into `MultiSelect` afterwards, so that we don't have a PR focused in one topic which introduces other side effects.
=> Update to latest FE shared

lms/migrations/versions/f13a876b8877_create_the_lms_course_and_lms_user_.py
For:
Auto Generated from: 
- https://github.com/hypothesis/lms/pull/6573
```
tox -e dev --run-command 'alembic upgrade head'     
dev run-test-pre: PYTHONHASHSEED='2671712126'
INFO  [alembic.runtime.migration] Running upgrade 3d0c022c716c -> f13a876b8877, Create the lms_course and lms_user tables.
````
=> Migration for LMSUser and LMSCourse tables

lms/services/course.py, lms/services/user.py, tests/unit/lms/services/course_test.py, tests/unit/lms/services/user_test.py
For:
- Make any local launch: https://hypothesis.instructure.com/courses/125/assignments/873
- Check your local DB for the new rows:
```
docker compose exec postgres psql -U postgres -c "select * from lms_user;"
id | tool_consumer_instance_guid |               lti_user_id                |                      h_userid                       |             email             |     display_name     |          created           |          updated          
----+-----------------------------+------------------------------------------+-----------------------------------------------------+-------------------------------+----------------------+----------------------------+---------------------------
1 |                             | …
```
=> Upsert rows in LMSCourse and LMSUser 

lms/static/scripts/frontend_apps/components/dashboard/DashboardActivityFilters.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/DashboardActivityFilters-test.js
Depends on https://github.com/hypothesis/lms/pull/6581
Revert changes from https://github.com/hypothesis/lms/pull/6562, and get back the ability to select multiple items in dashboard filters.
This PR takes into consideration the new MultiSelect UI, and now, clearing courses or assignments only happens if "All courses/assignments" is selected, or if the checkbox of the active item is clicked.
https://github.com/user-attachments/assets/1108542a-18ef-4621-a4f8-16fddb3bf2a5
=> Get MultiSelect back in DashboardActivityFilters

lms/migrations/versions/1b80d29976d6_fix_lms_course_membership_user_fk.py, lms/models/lms_course.py
For:
Wrong value on the initial table definition (classic copy/paste).
Fixing the model and DB schema with a migration.
=> Migration: fix lms_course_membership.lms_user_id FK to point to the right table

lms/migrations/versions/1b80d29976d6_fix_lms_course_membership_user_fk.py, lms/models/lms_course.py, lms/services/course.py, lms/services/user.py, tests/unit/lms/services/course_test.py, tests/unit/lms/services/user_test.py
For:
This the revert-of-a-revert PR
I reverted https://github.com/hypothesis/lms/pull/6588 due to a bug, fixed in this commit: d3a7c9c0ee7d7ffffd05ef0222c5e11f3669caf0. 
We should not try to upsert "copied_from_id" in the new table as the reference to the original courses might not yet exists in the DB. We can only do that once backfill the table.
- Original PR: https://github.com/hypothesis/lms/pull/6576
- Revert: https://github.com/hypothesis/lms/pull/6588
=> Keep LMSCourse and LMSUser up to date on every launch

lms/models/grouping.py, lms/models/user.py, lms/services/course.py, lms/views/lti/basic_launch.py, tests/factories/__init__.py, tests/factories/lms_course.py, tests/factories/lms_user.py, tests/unit/lms/services/course_test.py, tests/unit/lms/views/lti/basic_launch_test.py
For:
Insert one row per user,course,role tuple in LMSCourseMembership.
We keep inserting mostly the same information in AssignmentMembership for now.
- Make any local launch: https://hypothesis.instructure.com/courses/125/assignments/873
- Check your local DB for the new rows:
```
docker compose exec postgres psql -U postgres -c "select * from lms_course_membership;"
id | lms_course_id | lms_user_id | lti_role_id |          created           |          updated           
----+---------------+-------------+-------------+----------------------------+----------------------------
1 |             7 |           1 |          21 | 2024-08-22 07:06:05.357006 | 2024-08-22 07:06:13.540303
```
=> Keep LMSCourseMembership up to date on every launch

lms/services/course.py
This allows us to keep track of the original course in LTI1.1 installs that include this parameter.
- Launch the copy of that, https://hypothesis.instructure.com/courses/252/assignments/1323 (this only happens during the creation of the course, delete the local row if launched before).
- Check copied_from status stored in the DB:
```
select original.lms_name, grouping.lms_name from grouping join grouping original on original.id = grouping.copied_from_id;
lms_name                   |                      lms_name                       
---------------------------------------------+-----------------------------------------------------
Developer Test Course with Sections Enabled | Copy of Developer Test Course with …
```
=> List the LTI1.1 parameter for course history

lms/migrations/versions/aef6a6460d0d_backfill_lmsuser.py
For:
```
dev run-test-pre: PYTHONHASHSEED='446913902'
INFO  [alembic.runtime.migration] Running upgrade 1b80d29976d6 -> aef6a6460d0d, Backfill LMSUser.
```
=> Migration: backfill LMSUser based on rows in User

lms/services/lti_grading/_v13.py, lms/services/lti_grading/factory.py, lms/services/lti_names_roles.py, lms/services/ltia_http.py, tests/unit/lms/services/lti_grading/_v13_test.py, tests/unit/lms/services/lti_grading/factory_test.py, tests/unit/lms/services/lti_names_roles_test.py, tests/unit/lms/services/ltia_http_test.py
For:
Until now all call to LTIA API happen on the context of a launch so it made sense to always scope them to the registration of that launch.
In preparation for start fetching course rosters, likely on a celery task, outside the context of a launch, take an explicit registration for LTIA calls.
This should be just a pure refactor, lets sanity check the changes:
- Launch https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/3348/View?ou=6782 as an instructor, 
- Fetch a grade for an student  (this calls the LTIA grade API).
- Submit a new one grade (another LTIA grade API call).
=> Make LTI http service take an LTIRegistration

lms/services/lti_role_service.py, tests/unit/lms/services/lti_role_service_test.py
For:
LTI1.1 provides a comma separated list of roles while LTI1.3 provides a list.
The launch LTIParams provides an abstraction for this, always returning the LTI1.1 version.
To allow using get_roles outside a launch context without having to needlessly convert between the two formats allow the method to take roles in both formats.
=> Take both a list of strings and comma separated string in get_roles

lms/models/lms_course.py
For:
This will allow us to communicate with the service outside the launch context.
See: https://www.imsglobal.org/spec/lti-nrps/v2p0#lti-1-3-integration
See https://github.com/hypothesis/lms/pull/6606
=> Add lti_context_membership_url to the LMSCourse model

lms/models/lti_params.py, lms/services/course.py, tests/unit/lms/models/lti_params_test.py, tests/unit/lms/services/course_test.py
For:
Store the url of the LTI1.3 context membership service.
This will allow us to call it outside the scope of a launch. It will also, more immediately, give us a good indication of for how many courses we receive this information at the moment.
- Launch https://hypothesis.instructure.com/courses/125/assignments/873, nothing changes, nothing explodes.
- Launch an LTI1.3 assignment, https://hypothesis.instructure.com/courses/319/assignments/3308
The service URL gets recorded in the LMSCourse table:
```select  * from lms_course where lti_context_memberships_url is not null```
=> Store LTI1.3 context_memberships_url in LMSCourse when available

lms/models/lms_course.py, lms/services/__init__.py, lms/services/course_roster.py, tests/factories/__init__.py, tests/factories/lms_course.py, tests/unit/lms/services/course_roster_test.py, tests/unit/services.py
For:
First version of the  CourseRoster service, boilerplate for the tests and just one method to call the NameRolesService method.
The service as it is in this PR won't yet be used in production code.
- Launch at least one LTI1.3 assignment https://hypothesis.instructure.com/courses/319/assignments/3308
- In `make shell`
```
from lms.services.course_roster import CourseRosterService
request.find_service(CourseRosterService).fetch_roster(db.query(models.LMSCourse).filter(models.LMSCourse.lti_context_memberships_url.is_not(None)).first())
2024-08-27 13:30:05,346 INFO  [lms.services.course_roster:38][MainThread] Roster for 3394ac098caa5997ed3d87023befb9f7e9ea4a38. Users returned 4
```
=> Single course roster fetch

lms/migrations/versions/f61cb94edfc8_backfill_lms_course.py
For:
```
dev run-test-pre: PYTHONHASHSEED='3463106992'
INFO  [alembic.runtime.migration] Running upgrade aef6a6460d0d -> f61cb94edfc8, LMSCourse backfill.
```
=> Migration: backfill LMSCourses from grouping rows

lms/services/course_roster.py, tests/unit/lms/services/course_roster_test.py
For:
Service method for store one roster row per course, user, role tuple.
- Launch at least one LTI1.3 assignment https://hypothesis.instructure.com/courses/319/assignments/3308
- In `make shell`
Fech one roster
```
from lms.services.course_roster import CourseRosterService  
request.find_service(CourseRosterService).fetch_roster(db.query(models.LMSCourse).filter(models.LMSCourse.lti_context_memberships_url.is_not(None)).first())
tm.commit()
```
in `make sql` check the presence of it in the DB:
`select * from course_roster;`
```
postgres=# select * from course_roster;
id | lms_course_id | lms_user_id | lti_role_id | active |          created           |          updated           
----+---------------+-------------+-------------+--------+--- …
```
=> Store course rosters in the DB

lms/tasks/course_roster.py, tests/unit/lms/tasks/course_roster_test.py, tests/unit/services.py
For:
A celery task that just forwards the call to the service.
- Launch at least one LTI1.3 assignment https://hypothesis.instructure.com/courses/319/assignments/3308
- In `make shell`
Fech one roster asynchronously
```
from lms.tasks.course_roster import fetch_roster
fetch_roster.delay(lms_course_id=db.query(models.LMSCourse).filter(models.LMSCourse.lti_context_memberships_url.is_not(None)).first().id)
```
In the `make dev` log you'll see something like:
```
INFO/ForkPoolWorker-16] lms.tasks.course_roster.fetch_roster[fdac8f5e-976c-4421-806a-9781c6c45cbe] Task lms.tasks.course_roster.fetch_roster[fdac8f5e-976c-4421-806a-9781c6c45cbe] succeeded in 3.8122543759982364s: None
```
=> Celery task to fetch course roster asynchronously

lms/migrations/versions/f61cb94edfc8_backfill_lms_course.py
For:
The existing LMSCourse has two assumptions, with one unique index for each:
- The same course (same authority_provided_id) can belong to multiple applications instances but we'll keep only one row in LMSCourse for it (unique h_authority_provided_id)
- authority_provided_id is generated from guid, lti_context_id, then, those two columns should also be unique together.
There's however a case when this is not true:
- Applications instance with a null GUID launches and creates a course (None, CONTEXT_ID). This generates a hashed authority_provided_id.
- The same application instance (ie, same row in ApplicationInstance) starts sending a GUID. We calculate a new (GUID, CONTEXT_ID) hash creating a new course, with a different …
=> Fix the LMSCourse backfill from grouping migration

lms/migrations/versions/e13fb37c96e5_backfill_lms_user_application_instance.py
For:
```
dev run-test-pre: PYTHONHASHSEED='2408596744'
INFO  [alembic.runtime.migration] Running upgrade f61cb94edfc8 -> e13fb37c96e5, Backfill lms_user_application_instance.
```
=> Migration: Backfill LMSUSerApplication instance

lms/migrations/versions/9e79650bed37_backfill_lms_course_application_instance.py
For:
```
tox -e dev --run-command 'alembic upgrade head'        
dev run-test-pre: PYTHONHASHSEED='427507881'
INFO  [alembic.runtime.migration] Running upgrade e13fb37c96e5 -> 9e79650bed37, LMSCourseApplicationInstance backfill.
```
=> Migration: Backfill LMSCourseApplication instance

lms/migrations/versions/481968561169_assignment_v13_id.py
For:
Auto Generated from: https://github.com/hypothesis/lms/pull/6615
More context and testing instructions over: https://github.com/hypothesis/lms/pull/6616
```
dev run-test-pre: PYTHONHASHSEED='1135265335'
INFO  [alembic.runtime.migration] Running upgrade 9e79650bed37 -> 481968561169, Assignment v13 ID.
```
=> Migration for assignment.lti_v13_resource_link_id

lms/services/assignment.py, tests/unit/conftest.py, tests/unit/lms/services/assignment_test.py
For:
To talk to the Name and Roles LTI API we use the service URL sent in LTI1.3 courses.
However to filter that by assignment we need to use the LTI1.3 assignment ID on that same course URL. 
The ID is sent in all launches but if present, we prefer the LTI1.1 (for backwards compatibility).
With this PR we now store explicitly the LTI1.3 ID to later be use the call the LTI API.
- Launch a LTI1.1 assigment: https://hypothesis.instructure.com/courses/125/assignments/873
Nothing changes
- Launch a LTI1.3 assignment: https://hypothesis.instructure.com/courses/319/assignments/3308
The LTI1.3 is stored in the DB
- Check the values in the DB:
```
docker compose exec postgres psql -U postgres -c "select  resource_link_id, lti_v13_resource_link_id …
```
=> Store LTI1.3 assignment ID explicitly in the DB

lms/services/__init__.py, lms/services/roster.py, lms/tasks/course_roster.py, lms/tasks/roster.py, tests/unit/lms/services/roster_test.py, tests/unit/lms/tasks/course_roster_test.py, tests/unit/lms/tasks/roster_test.py, tests/unit/services.py
For:
For now the criteria to fetch rosters is:
- We have a LTI Names and Roles service URL for the course.
- The course has recent launches (1 day)
- The course doesn't have a recent roster (1 week)
- Only a number of rosterd (5) per scheduled time (??, hourly?). This needs to be set in h-periodic.
- Launch at least one LTI1.3 assignment https://hypothesis.instructure.com/courses/319/assignments/3308
- In `make sql`, remove any roster in your local DB
```
truncate course_roster;
````
Schedule rosters
```
from lms.tasks.course_roster import schedule_fetching_rosters
```
```
Task lms.tasks.course_roster.schedule_fetching_rosters[83dfc791-e29c-4315-a094-2f56c4d98c14] received …
```
=> Celery task to schedule fetching rosters

lms/static/scripts/frontend_apps/components/dashboard/DashboardActivityFilters.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/DashboardActivityFilters-test.js, package.json, yarn.lock
Closes #6531
Depends on https://github.com/hypothesis/frontend-shared/pull/1685
Display an error message with a button to retry when loading items for any filtering dropdown fails.
The same kind of message is displayed regardless of the page that failed, so if the first page fails, we show the error after the "All {entity}" option, and if a subsequent page fails, we show the message after the already loaded options.
https://github.com/user-attachments/assets/e5bed471-b23a-48f3-9782-983b50e2c1c3
https://github.com/user-attachments/assets/e29675ae-408f-41ad-82dd-855db8850740
- The icon in the retry button is not the one I was looking for, but we don't have the typical "refresh" circle arrow, so I'll leave this one for now.
- When the first page is the one failing and we retry, the select …
=> Add error handling to dashboard filters

.github/workflows/ci.yml
As a temporary workaround for the changes newer versions (>3.2.0) around not uploading hidden files
=> Pin GHA's upload-artifact to 3.1.3

lms/models/application_instance.py, lms/resources/_js_config/__init__.py, lms/static/scripts/frontend_apps/config.ts, lms/templates/admin/application_instance/show.html.jinja2
New setting for the new auto-grading feature. To kickoff the development behind a feature flag. 
- Go over an application instance in the admin pages, toggle the new setting on/off
=> Feature flag for auto-grading

lms/models/json_settings.py, lms/resources/_js_config/__init__.py, tests/unit/lms/resources/_js_config/__init___test.py
Correctly pass the group parameter.
Assert the basic shape of the configuration object.
See: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1725277710700479
=> Fix the auto_grading_enabled setting get call

lms/models/grouping.py, lms/services/roster.py, lms/tasks/roster.py, tests/factories/__init__.py, tests/factories/roster.py, tests/unit/lms/services/roster_test.py, tests/unit/lms/tasks/roster_test.py
For:
Fetch assignment roster as well as course ones.
In some LMS (ie Canvas "assignment to" feature) assignment rosters will be different to courses's.
We'll start fetching both at the same frequency to compare the data in the wild.
I have written a version of this train of PRs (migration/model and this one) using just one table "Roster", that have both FK to course  and assignment.
That resulted in a more complicated table (with constraint based on one column being null, checking uniqueness the others) and the code look pretty much the same as in this PR, no duplication was avoided as while using the same table, queries to it were different.
- Launch https://hypothesis.instructure.com/courses/319/assignments/3308
- Truncate any local …
=> Fetch assignment rosters

lms/services/assignment.py, tests/unit/conftest.py, tests/unit/lms/services/assignment_test.py
For:
To sync grades outside the context of a launch we have to fetch the URL on the launches to be able to use it later.
It would be possible to fetch this URL from the rostering information but for this we'll get on each launch as it would become handy for our regular grading operations (ie the grading bar).
- Launch a LTI1.3 assignment https://hypothesis.instructure.com/courses/319/assignments/7296
- Launch a LTI1.1 assignment https://hypothesis.instructure.com/courses/125/assignments/873
- Check the data in the sql
```docker compose exec postgres psql -U postgres -c "select title, lis_outcome_service_url from assignment where lis_outcome_service_url is not null;"```
```
title                   | …
```
=> Keep record of the grading service URL for each assignment

lms/static/scripts/frontend_apps/components/AutoGradingConfigurator.tsx, lms/static/scripts/frontend_apps/components/FilePickerApp.tsx, lms/static/scripts/frontend_apps/components/GroupConfigSelector.tsx, lms/static/scripts/frontend_apps/components/test/AutoGradingConfigurator-test.js, lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js, package.json, yarn.lock
Add UI components in assignment configuration so that it is possible to enable auto grading.
The config generated by this UI is currently ignored by the BE. We have aligned the structure, so it should work once https://github.com/hypothesis/lms/pull/6634 is merged, but additional changes may be needed later.
https://github.com/user-attachments/assets/2d39e4f4-ad70-4b65-9779-6e29337bafbe
> [!WARNING]  
> There are some fundamental differences with [the designs](https://www.figma.com/design/ctCnzwkAyYArSNBYEshiCm/Hypothesis---LMS-Assignment-Grading?node-id=496-221&node-type=CANVAS&t=kT7pEfMy0RgzyH2F-0), mostly in font color and font size.
>
> Those are a side effect of the base styles in this page, which I think are mostly there for historical reasons.
> We could decide to change those, but …
=> Add UI components to configure assignments auto-grading

lms/js_config_types.py
For: 
Include an optional key on the dashboard's APIAssignment that will always not present for now.
=> Define types for autograding shared with the frontend

lms/services/roster.py, lms/tasks/roster.py, pyproject.toml, tests/unit/lms/services/roster_test.py
We have seen some issues in production where the assignment roster fetch fails with a cryptic error from Canvas.
We have not been able to reproduce this situation locally.
As we have two IDs for the same assignment lets try the LTI1.1 one.
We have tested the other following scenarios:
- LTI1.3 assignment. Use the LTI1.3 id works.
- Upgrade from LTI1.1 LTI1.3 assignment. Using the LTI1.1 ID fails while the 1.3 one works.
I don't know how to reproduce this bug (and I don't know either if this will fix it). We can however test if the pieces here are wired together to catch errors by a message on the response
- Let's simulate the opposite scenario, we'll send the LTI1.1 ID which will fail, catch that particular error message, and try again with the right ID
Apply this diff:
```diff
diff --git …
```
=> Use the LTI1.1 assignment ID after a failure to fetch a roster

lms/services/roster.py, tests/unit/lms/services/roster_test.py
We'll tackle this individually as we gather more information are able to reproduce and fix them.
See https://hypothes-is.slack.com/archives/C1MA4E9B9/p1725372178973579
=> Ignore known error codes from the rostering services

lms/scripts/init_db.py
engine.connect() used in delete() and SQLA's create_all in create() might execute in separate transactions.
Explicitly commit the schema deletion in the first step so it's visible to the rest of the init_db script.
Follow up to https://github.com/hypothesis/lms/pull/6578
=> Explicitly commit schema deletion on init_db.delete

lms/tasks/roster.py
For:
Fetch roster for the most recently created course/assignments first
=> Order roster fetching course/assignment candidates

lms/services/roster.py, tests/unit/lms/services/roster_test.py
This occurs when the assignment we try to fetch the roster for has been deleted from the LMS
These are just causing noise on the monitoring now.
=> Ignore assignment not found error while fetching rosters

lms/views/lti/deep_linking.py, tests/unit/lms/views/lti/deep_linking_test.py
For:
- The frontend calls the deep_linking_fields API with the assignment's config.
- The BE returns a JWT that must be POSTed to the LMS client side.
- That JWT contains an encoded representation of the assigned configuration. Some of those elements are encoded in and URL other are port of the launch's custom parameters.
- The client POSTs the config the LMS, the assignment is created 
- Next launches of the assignments forward to us the configuration.
This PR handles encoding the auto grading configuration as part of the deep linked parameters.
Next steps will need to read it on launches and persist it to the DB.
- Requires: https://github.com/hypothesis/lms/pull/6632
- Configure a LTI1.3 assignment with autograding, any parameters.
- Save …
=> Forward auto-grading settings to DL assignments

gulpfile.js, lms/static/scripts/frontend_apps/components/dashboard/GradeStatusChip.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/GradeStatusChip-test.js, lms/static/scripts/ui-playground/components/GradeStatusChipPage.tsx, lms/static/scripts/ui-playground/index.ts
This PR adds a new `GradeStatusChip` component that will be used in the LMS dashboard for assignments where auto-grading is enabled.
This PR does not provide any usage of the component yet, other than a very simple prototype page demonstrating their usage: http://localhost:8001/ui-playground/grade-status-chip
```tsx
<GradeStatusChip grade={100} />
<GradeStatusChip grade={80} />
<GradeStatusChip grade={68} />
<GradeStatusChip grade={38} />
<GradeStatusChip grade={0} />
<GradeStatusChip grade={120} />
<GradeStatusChip grade={-25} />
```
`GradeStatusChip` inside `DataTable`:
EDIT: I decided to implement a "neutral" variant, and use that when the grade is out of range.
EDIT: Let's keep it as is for now. Since this is a local component, it should be easy to change later if we decide to.
EDIT: …
=> Create new chip component to represent grade status

lms/js_config_types.py, lms/services/auto_grading.py, lms/views/dashboard/api/user.py, tests/unit/lms/services/auto_grading_test.py, tests/unit/lms/views/dashboard/api/user_test.py
For:
Calculate auto-grades when the assignment is configured to use them and expose them in the metrics endpoint. 
- Launch https://hypothesis.instructure.com/courses/319/assignments/7296
- Launch it again with at least one student. https://hypothesis.instructure.com/courses/319/assignments/7296
- Open the assignment dashboard, check the response for the metrics endpoints. It does now contain an `auto_grading_grade` field.
```
{
"students": [
{
"h_userid": "acct:f6c3ed0edd8a4013bfc8d0c22b9eca@lms.hypothes.is",
"lms_id": "2a8a99bc095a8438a594cd57c1f4f0341951e360",
"display_name": "Hypothesis 101 Student",
"annotation_metrics": {
"annotations": 0,
"replies": 0,
"last_activity": null
},
"auto_grading_grade": 0.0
}
]
}
```
=> Calculate and expose auto grading grade on the students metrics endpoint

lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/OrderableActivityTable.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js
Display a new "Grade" column in the assignment activity table, for assignments where auto-grading has been enabled.
1. Go to https://hypothesis.instructure.com/courses/319/assignments/7296, and log-in as the "Hypothesis 101 Teacher" teacher.
2. Edit the assignment and enable auto-grading (default values are fine).
3. Open the dashboard for that assignment. The table should show a new "Grade" column.
> Note the values of that column may not be displayed yet, as that depends on https://github.com/hypothesis/lms/pull/6664
4. Open the dashboard for any other assignment where auto-grading was not enabled. It should not show the "Grade" column.
=> Add conditional grade column to assignment activity table

lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js
In https://github.com/hypothesis/lms/pull/6666 we added a grae column to the students activity table, which renders a grade chip component that makes rows slightly taller than they were before due to the implicit padding in table cells.
This PR adds a bit of negative margin around the grade chip to compensate for that and make rows have the same height they had before.
This is the height of a row without grade column:
This is the height when the grade chip is included, before applying the changes from this PR:
And this is how it looks with the changes from this PR:
I added the smallest possible margin, which is enough so that a single line of text in any of the other cells is taller.
Bigger margins would not make a difference here, unless the rest of the cells were empty. 
I considered …
=> Reduce size taken by grade chips in activity tables

lms/services/assignment.py, lms/services/course.py, lms/services/user.py, tests/unit/lms/services/assignment_test.py, tests/unit/lms/services/course_test.py
All dashboards queries (user, assignments, courses) have to main parts:
- Filtering down the data we have access too, either as an instructor or admin
- Filtering down base on the dropdown selections
This commit generalizes the first part to be always course based. Only select data that belongs to courses where the instructor belongs or from organizations where the user is and admin.
Then we select users, assignment (or directly the courses) that belong to those courses.
This allows to greatly reduce the dataset size in the first step and narrow it down in the second.
- Login as staff, test all levels and use the dropdowns.
- Login as an instructor, test all levels and use the dropdowns.
=> Refactor dashboards data queries

lms/models/lms_user.py
For:
Migration over: https://github.com/hypothesis/lms/pull/6669
More context and testing instructions in: https://github.com/hypothesis/lms/pull/6671
=> Model changes to add lms_user.lti_v13_user_id

lms/security.py, lms/services/roster.py, lms/services/user.py, tests/unit/lms/security_test.py, tests/unit/lms/services/user_test.py
For:
In LTI1.1 launches we only get the LTI1.1 user_id. Conversely in "pure" LTI1.3 launches we only get the LTI1.3 ID.
However in updated LTI1.3 launches we get both versions, the LTI1.1 and LTI1.3 one. We have prefered the LTI1.1 for backwards compatibility, to keep the same identity in H.
While we do use now the LTI1.3 grading API we only do that in the context of a launch where we have all the parameters available to chose.
We need now to the LTI1.3 version in the DB to talk to the the grading API outside of the context of launch for the autograding feature.
- [Launch a LTI1.1 assignment](https://hypothesis.instructure.com/courses/125/assignments/873), nothing should changes
- [Launch a LTI1.3 …
=> Store the LTI1.3 user_id in LMSUser

lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/GradeIndicator.tsx, lms/static/scripts/frontend_apps/components/dashboard/GradeStatusChip.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/GradeIndicator-test.js
Add a new component that is displayed when hovering over the grade chip, which displays what were the annotation and reply requirements, and what were met.
https://github.com/user-attachments/assets/48dbc570-5c10-45eb-8020-d3088cee945c
https://github.com/user-attachments/assets/891c572f-e722-472b-a467-2ebd710a99bf
I considered using an actual popover, but it's not fully supported by all browsers yet, and requires extra positioning considerations.
We could implement a popover component in frontend-shared and use it here, but I'll probably delay that.
EDIT: For now I did the following:
1. Add an aria-live region around the popover, so that it gets announced by screen readers.
2. Add `role="tooltip"` to the popover itself.
3. Make the wrapper focusable, via `role="button"` and …
=> Add popover for grades in auto-grade assignments

lms/security.py, lms/services/user.py, lms/views/lti/basic_launch.py, lms/views/lti/deep_linking.py, tests/unit/lms/security_test.py, tests/unit/lms/services/user_test.py, tests/unit/lms/views/lti/basic_launch_test.py, tests/unit/lms/views/lti/deep_linking_test.py
We currently have access to User via request.user and that upserts `User` in practically every request.
That is itself is a questionable design but for `LMSUser` we definitely only want to update it from the data from the LMS, not data we have forwarded back to use in API calls.
Only upsert_lms_user in the two direct launches from the LMS, the "basic" launch and deep linking launches.
- [Launch a LTI1.1 assignment](https://hypothesis.instructure.com/courses/125/assignments/873), nothing should change
- [Launch a LTI1.3 assignment](https://hypothesis.instructure.com/courses/319/assignments/7296), the new ID will be stored in the DB.
- Check the ID in the table:
```
select display_name, lti_V13_user_id from lms_user;
display_name          |           lti_v13_user_id …
```
=> Only upsert LMSUser on launches

lms/js_config_types.py, lms/models/application_instance.py, lms/resources/_js_config/__init__.py, lms/templates/admin/application_instance/show.html.jinja2, tests/unit/lms/resources/_js_config/__init___test.py
For:
This will allow us to expose the configuring and calculating side of auto grading while we work on the syncing part.
=> Add a feature flag for the sync grade side of auto grading

lms/static/scripts/frontend_apps/components/dashboard/DashboardActivityFilters.tsx, lms/static/scripts/frontend_apps/components/dashboard/PaginatedMultiSelect.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/DashboardActivityFilters-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/PaginatedMultiSelect-test.js
The `PaginatedMultiSelect` component was internal to the `DashboardActivityFilters`, but it was complex enough to define its own module and independent test.
Additionally, even though I'm not fully convinced yet, but we may need to display a `PaginatedMultiSelect` out of the activity filters group.
Sanity-check that the dashboard filters are properly displayed and work as expected in every section.
=> Extract PaginatedMultiSelect to its own module

lms/resources/_js_config/__init__.py, lms/security.py, lms/services/application_instance.py, lms/services/lti_grading/_v13.py, pyproject.toml, tests/pyproject.toml, tests/unit/lms/services/canvas_studio_test.py, tests/unit/lms/services/lti_grading/_v13_test.py
Due to a bug in Blackboard (see: https://github.com/hypothesis/lms/pull/5839)
we fetch results for all students and just pick the right one.
We didn't implement pagination together with that change so we are
missing students that are part of the course but are present in other
pages.
For now will just request a large number of results and alert when we
still hit the pagination limit.
Also see: https://hypothes-is.slack.com/archives/C2C2U40LW/p1726613664446289
- Login as `blackboardteacher` in https://aunltd-test.blackboard.com/
- Launch the [LTI 1.3 assignment test assignment](https://aunltd-test.blackboard.com/webapps/blackboard/content/contentWrapper.jsp?content_id=_2085_1&displayName=localhost+PDF+-+LTI1.3&course_id=_19_1&navItem=content&href=%2Fwebapps%2Fblackboard%2Fexecute%2Fblti%2Fl …
=> Explicitly request a large number of results from BB grading API

lms/js_config_types.py, lms/models/application_instance.py, lms/resources/_js_config/__init__.py, lms/routes.py, lms/services/dashboard.py, lms/services/lti_grading/_v13.py, lms/templates/admin/application_instance/show.html.jinja2, lms/views/dashboard/api/grading.py, tests/unit/lms/resources/_js_config/__init___test.py, tests/unit/lms/services/lti_grading/_v13_test.py, tests/unit/lms/views/dashboard/api/grading_test.py
For:
Basic API endpoint to support the first version of the "Sync grades" button.
- Based on this assignment https://hypothesis.instructure.com/courses/319/assignments/7296
use a request like:
```
curl 'http://localhost:8001/api/dashboard/assignments/121/grading/sync' -X POST \
-H "Content-Type: application/json" \
-H 'Authorization: XXXXXXX' \
--data '{"grades": [{"h_userid": "acct:f6c3ed0edd8a4013bfc8d0c22b9eca@lms.hypothes.is", "grade": 0.7}]}'
```
with a token from an instructor (it won't work for staff members).
- Check the grade over: https://hypothesis.instructure.com/courses/319/assignments/7296
=> Sync grades back to the LMS for auto grading

lms/js_config_types.py, lms/models/grouping.py, lms/services/assignment.py, lms/services/user.py, lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/DashboardActivityFilters.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/DashboardActivityFilters-test.js, lms/static/scripts/frontend_apps/utils/dashboard/hooks.ts, lms/static/scripts/frontend_apps/utils/dashboard/test/hooks-test.js, lms/views/dashboard/api/assignment.py, lms/views/dashboard/api/user.py, tests/unit/lms/services/assignment_test.py, tests/unit/lms/services/user_test.py, tests/unit/lms/views/dashboard/api/assignment_test.py, tests/unit/lms/views/dashboard/api/user_test.py
Expose segments in the dashboards API
- Expose groups and sections in GET /assignment
- Take a list of group IDs (authority_provided_ids) to filter students
by
- Groups https://hypothesis.instructure.com/courses/125/assignments/1833
```
"groups": [
{
"h_authority_provided_id": "e8c66a347a5f547ae87928d4e92e5045908f8d54",
"name": "Another test group"
},
{
"h_authority_provided_id": "28b6d0a2ce206db35ef53624cb9fc66d5835fadd",
"name": "Group created after course copy"
},
{
"h_authority_provided_id": "102a25279bc609179f58cb4bf5c50d7dfc6f0929",
"name": "Group with student"
},
{
"h_authority_provided_id": "381c455de84ae2f6d2fc84142f4e898b29d748f3",
"name": "Test group"
}
```
- Sections https://hypothesis.instructure.com/courses/125/assignments/873
```
"sections": [
{
"h_authority_provided_id": …
```
=> Expose segments in the dashboards API

lms/static/scripts/frontend_apps/components/dashboard/GradeIndicator.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/GradeIndicator-test.js
This PR changes a bit how the grading popover is implemented, so that it is closer to how popovers usually work, rather than tooltips:
The main difference between tooltips and popovers, from a conceptual point of view, is that [tooltips are not expected to be shown in touch devices](https://react-spectrum.adobe.com/react-aria/Tooltip.html#accessibility), therefore they should not contain information which is otherwise not available.
However, there's a bit of overlapping between both patterns, and a few grey areas and opinions. Hence, I tried to make some sensible decisions that can be discussed here.
The changes here are the result of checking how some popular UI libraries treat popovers:
* Bootstrap: https://getbootstrap.com/docs/5.3/components/popovers
* Headless UI: …
=> Improve grading popover accessibility

lms/services/__init__.py, lms/services/auto_grading.py, lms/views/dashboard/api/user.py, tests/unit/lms/services/auto_grading_test.py, tests/unit/lms/views/dashboard/api/user_test.py, tests/unit/services.py
For: 
Make this a real service in preparation to handle GradingSync objects and ideally making this PR a little bit smaller https://github.com/hypothesis/lms/pull/6690
=> Refactor AutoGradingService as a real service

lms/static/scripts/frontend_apps/components/dashboard/GradeIndicator.tsx
Add a higher z-index to grading popover to make sure it renders over the grading chips:
Before:
https://github.com/user-attachments/assets/01f8c97c-e3f6-4ee6-a030-c343b6046681
After:
https://github.com/user-attachments/assets/571c9886-a4d0-4acb-92bd-b12b862c7a23
=> Fix grading popover being rundered underneath the grading chip

lms/views/dashboard/api/grading.py, tests/unit/lms/views/dashboard/api/grading_test.py
This is mostly a possibility while testing locally. GradeSync with not GradeSyncGrades will currently stay "in_progress" forever as no GradeSync will ever finish.
We could make changes so this type of sync is marked as finished immediately but we are better off not creating them in the first place.
- Try to create a new GradeSync with a non-existing HUserId:
```
curl 'http://localhost:8001/api/dashboard/assignments/121/grading/sync' -X POST \
-H "Content-Type: application/json" \
-H 'Authorization: Bearer ' \
--data '{"grades": [{"h_userid": "NOPE", "grade": 0.7}]}'
```
You'll now get an error:
```{"message": "No users for this grade sync. Can't find any of the provided users."}%```
=> Don't create GradeSync with no GradeSyncGrades

lms/services/auto_grading.py, tests/unit/lms/services/auto_grading_test.py
I noticed the auto-grading grade could be incorrectly calculated when an assignment is configured with scaled and separate calculation, and a user provides more annotations and/or replies than required.
Those would end up being taken into consideration for the total, making a user with, let's say 6 annotations and 0 replies, get a 100% when 3 annotations and 3 replies are required, instead of 50%.
This PR changes the logic to make sure "extra" annotations/replies are not counted when calculating the grade.
=> Fix grade calculation for scaled+separate auto-grading assignments

lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/DashboardActivityFilters.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/DashboardActivityFilters-test.js
In https://github.com/hypothesis/lms/pull/6695, we made the segments filter be dynamically displayed in the next cases:
* For any user in auto-grading assignments.
* For any user in assignments where the dedicated feature flag is enabled.
* For hypothesis staff users (when the dashboard is opened from the LMS admin) in any assignment.
However, even when some of the conditions above was met, if an assignment didn't have groups or sections, the dropdown would not be displayed. This can cause confusion and make debugging harder.
This PR changes this behavior, and makes the dropdown still be displayed, but disabled, for assignments without groups or sections.
=> Always display segments filter when the feature is enabled

lms/models/lti_registration.py, lms/product/plugin/misc.py, lms/services/lti_grading/_v13.py, tests/unit/lms/models/lti_registration_test.py, tests/unit/lms/services/lti_grading/_v13_test.py
For:
See:
https://hypothes-is.slack.com/archives/C4K6M7P5E/p1727176677869349
- Send a grade for `Hypothesis 101 Student` (`acct:f6c3ed0edd8a4013bfc8d0c22b9eca@lms.hypothes.is`), which has many submissions
Check no new submission are created but the grade is updated in:
https://hypothesis.instructure.com/courses/319/gradebook/speed_grader?assignment_id=7296&student_id=35
- Send a grade for `jeremydean+student3@hypothes.is`, (`f6c3ed0edd8a4013bfc8d0c22b9eca@lms.hypothes.is`)  who doesn't have any submission.
No submissions are created but the grade does appear in speedgrader, see:
https://hypothesis.instructure.com/courses/319/gradebook/speed_grader?assignment_id=7296&student_id=85
=> Disable submission auto-creation while submitting grades to Canvas

lms/static/scripts/frontend_apps/components/dashboard/SyncGradesButton.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/SyncGradesButton-test.js
This PR fixes a bug I introduced in a last-minute change in https://github.com/hypothesis/lms/pull/6700.
Basically, I made it refresh requests that have failed when using `usePolledAPIFetch`, so it never transitions to an error state, but also never consideres it should no longer refresh, causing the polling to continue forever.
=> Make sure usePolledAPIFetch does not continue polling in case of error

lms/js_config_types.py, lms/services/auto_grading.py, lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js, lms/views/dashboard/api/user.py, tests/unit/lms/services/auto_grading_test.py, tests/unit/lms/views/dashboard/api/user_test.py
For:
**Do not merge** This PR requires changes in the frontend to accept the new response shape from the metrics endpont.
This should enable the following in the FE/UI:
- Displaying a `new` badge or similar for grade which calculated grade
is different that the last synced value.
- Only creating a GradeSyncGrade for grades that have changed from the
last updated grade.
- Check the response from the metrics endpoint:
```
curl 'http://localhost:8001/api/dashboard/students/metrics?assignment_id=121' \
-H 'Authorization: Bearer ' \
-H 'Cache-Control: no-cache' 
```
```
{"students": [{"h_userid": "acct:f6c3ed0edd8a4013bfc8d0c22b9eca@lms.hypothes.is", "lms_id": "2a8a99bc095a8438a594cd57c1f4f0341951e360", "display_name": …
```
=> Expose the last synced grade and its date on the user metrics endpoint

lms/static/scripts/frontend_apps/components/dashboard/DashboardActivityFilters.tsx, lms/static/scripts/frontend_apps/components/dashboard/PaginatedMultiSelect.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/DashboardActivityFilters-test.js
This PR improves https://github.com/hypothesis/lms/pull/6704, by adding a more human-friendly text in segments filter when it is displayed disabled because the assignment doesn't have groups or sections.
The provisional text was `N/A`, but this PR changes it to `No sections/groups`.
Additionally, we make sure that dropdown takes as little space as possible when it is displayed disabled.
=> Display a more human-friendly text in disabled segments filter

lms/services/auto_grading.py, lms/static/scripts/frontend_apps/components/dashboard/GradeStatusChip.tsx, lms/static/scripts/frontend_apps/components/dashboard/SyncGradesButton.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/GradeStatusChip-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/SyncGradesButton-test.js, lms/views/dashboard/api/user.py, tests/unit/lms/services/auto_grading_test.py
This PR updates how grades are calculated and exposed by the BE, so that it's always a value from 0 to 1 instead of a value from 0 to 100, making it consistent to how grades are handled in other contexts.
Additionally, the FE is adjusted to ensure it also handles values from 0 to 1, and only when representing the grade in the UI it is converted to a value from 0 to 100.
The behavior and how values are shown in the UI should not have changed compared to `main`.
=> Return current auto-grading grades as a value from 0 to 1

lms/views/dashboard/api/grading.py, tests/unit/lms/views/dashboard/api/grading_test.py
For:
The previous error was very confusing as it was the same as for a non-existing endpoint both on the response to the client and the logging in the console.
- Remove your local syncs `truncate grading_sync cascade;`
- Try to get the sync for an assignment
```
curl 'http://localhost:8001/api/dashboard/assignments/121/grading/sync' -X GET \
-H "Content-Type: application/json" \
-H 'Authorization: Bearer TOKEN'
```
```{"message": "No existing grading sync for assignment:121"}%```
=> Better error message when not grading sync exists yet for an assignment

lms/services/assignment.py, lms/views/dashboard/pagination.py, tests/unit/lms/services/assignment_test.py, tests/unit/lms/views/dashboard/pagination_test.py
For:
This allows to edit assignments to no longer use auto grading.
- Edit https://hypothesis.instructure.com/courses/319/assignments/7296, don't use the auto grading option.
- Open the dashboard, no auto grading column.
- Edit https://hypothesis.instructure.com/courses/319/assignments/7296, enable auto grading, open the dashboard. See the grading column now.
=> Remove existing auto grading config when reconfiguring assignments

lms/services/auto_grading.py, tests/unit/lms/services/auto_grading_test.py
Explicitly set the join condition with LMSUser. SQLAlhcemy was assuming
`GradingSync.created_by = LMSUser`
Instead of the desired:
`GradingSyncGrade.lms_user = LMSuser`
Changing the order of the join statement in the query would also fix the problem but it's an easy detail to miss, adding the join condition explicitly instead.
=> Fix query for getting an assignment's last grades

lms/migrations/versions/aea9bbeee574_constrains_for_grading_sync_tables.py, lms/models/grading_sync.py, tests/unit/lms/services/auto_grading_test.py
For:
---
- Allow just one pending sync per assignment
- Allow just one grade per student/sync
- Remove all existing data
```truncate grading_sync cascade;```
- Insert one scheduled grading sync (IDs will need adjusting on local different environments) 
```insert into grading_sync (assignment_id, created_by_id, status) values (84, 1251, 'scheduled');```
- Try the same thing again, you'll hit the constraint:
```
ERROR:  duplicate key value violates unique constraint "ix__grading_sync_assignment_status_unique"
DETAIL:  Key (assignment_id)=(84) already exists.
```
- Same error if we try with an `in_progress`
`insert into grading_sync (assignment_id, created_by_id, status) values (84, 1251, 'in_progress');`
- But it's fine to insert a failed or …
=> Add missing constraints on GradingSync and GradingSyncGrade

lms/models/grading_sync.py, lms/services/auto_grading.py, lms/views/dashboard/api/grading.py, tests/unit/lms/views/dashboard/api/grading_test.py
For:
Expose each of the status of a grading sync grades
- Go to the dashboard, on an auto-grading assignment with a finished/failed sync, check the return data of `/api/dashboard/assignments/121/grading/sync`
```
{
"status": "finished",
"grades": [
{
"h_userid": "acct:f6c3ed0edd8a4013bfc8d0c22b9eca@lms.hypothes.is",
"grade": 0.0,
"status": "finished"
},
{
"h_userid": "acct:acea453480dde254bdf1c1058758e2@lms.hypothes.is",
"grade": 0.0,
"status": "finished"
}
]
}
```
=> Expose individual grade status

lms/services/__init__.py, lms/services/lti_grading/_v11.py, lms/services/lti_grading/factory.py, lms/services/oauth1.py, lms/views/lti/deep_linking.py, tests/unit/lms/services/__init___test.py, tests/unit/lms/services/lti_grading/_v11_test.py, tests/unit/lms/services/lti_grading/factory_test.py, tests/unit/lms/services/oauth1_test.py, tests/unit/lms/views/lti/deep_linking_test.py
For:
We need to merge the interfaces of v11 and v13 again for both to support the auto grading features.
The main difference is supporting sending grades for any applications instance, not the AI of a the current logged in user.
The first step here is to take an arbitrary AI on the oauth1 service. 
- [Re deeplink this assignment](https://hypothesis.instructure.com/courses/125/assignments/7412/edit?name=Assignment%20creation%20-%20test%20&due_at=&points_possible=0)
- Launch https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/3350/View
- We'll hit the grading API to fetch the score max:
```
Score maximum for F7373A6B-A469-426E-8F99-138CEF897E95-2545_6782: None
```
and also to read the current grade.
- Hit the API again to record …
=> Take an explicit application instance on the OAuth1 client

lms/services/lti_grading/_v13.py, lms/tasks/grading.py, tests/unit/lms/services/lti_grading/_v13_test.py, tests/unit/lms/tasks/grading_test.py
While LTIRegistration is the object that will drive authentication in
LTI1.3 API taking an application instance instead will allow to use the
same interface in LTI1.3 and LTI1.1 (where LTI registrations don't
exist)
From https://github.com/hypothesis/lms/pull/6720#issuecomment-2383125293
We have two problems:
* We have to manually create an instance to LTI13GradingService in grading/task.py to use the sync_grade method.
* Auto grading doesn't work in LTI1.1
The solution for both is to create a generic (v13 & v11) sync_grade method so we can just use find_service(LTIGradingService) and that will dispatch to the right version of the service.
The LTI1.1 version of sync_grade will need to talk to the LTI API on behalf of any applications instance (not the one from the request). To do that it …
=> Take a AI instead of registration in the sync_grade method to allow the same signature to work in both LTI versions

lms/services/assignment.py, tests/unit/conftest.py, tests/unit/lms/services/assignment_test.py
update_assignment takes care of the case where speedgrader sends us bogus data and ignores it.
Without this change we were updating lti_v13_resource_link_id and lis_outcome_url on speedgrader launches to incorrect values.
In `main` launch:
- https://hypothesis.instructure.com/courses/319/assignments/3336
`docker compose exec postgres psql -U postgres -c "select lti_v13_resource_link_id,lis_outcome_service_url from assignment where title = 'localhost (make devdata) Groups assignment';"`
```
lti_v13_resource_link_id       |                        lis_outcome_service_url                         
--------------------------------------+------------------------------------------------------------------------
4a12eea4-8f9b-4b5a-9916-abea14fde8bd | …
```
=> Only update assignment attributes in update_assignment

lms/services/lti_grading/_v13.py, lms/services/lti_grading/factory.py, lms/services/lti_grading/interface.py, lms/tasks/grading.py, tests/unit/lms/services/lti_grading/_v13_test.py, tests/unit/lms/services/lti_grading/factory_test.py, tests/unit/lms/tasks/grading_test.py
For:
This allows us to use the generic service in the grading task instead of
manually instantiating the LTI1.3 version.
We still can't use `find_service` to create the service as the celery
task placeholder request is not scoped to any application instance.
Added a new parameter to the factory to explicitly pass an application
instance to base the LTI version decision on.
This commit doesn't implement sync_grade on LTI1.1 yet.
From https://github.com/hypothesis/lms/pull/6720#issuecomment-2383125293
```
We have two problems:
* We have to manually create an instance to LTI13GradingService in grading/task.py to use the sync_grade method.
* Auto grading doesn't work in LTI1.1
The solution for both is to create a generic (v13 & v11) sync_grade …
```
=> Include sync_grade in the generic LTIGrading interface

lms/product/canvas/_plugin/course_copy.py, lms/services/canvas.py, lms/views/api/canvas/files.py, tests/unit/lms/services/canvas_test.py, tests/unit/lms/views/api/canvas/files_test.py
The course copy process should fetch file from the LMS for the current
course and rely on the data on the DB for the old course.
This is because often the instructor teaching the new course won't have
access to the old course.
Change the parameter passed to the course copy functions to be based on
the current assignment's course instead of coming from the `canvas://`
style URL.
---
- At some point an instructor configures a file assignment in the original course.
- We store all the files in that course in the DB, including the one selected for the assignment
- The course gets copied in the LMS
- A new instructor launches the new course
- We realize the assignment is configured with a file ID that's not in the new course
- **We fetch all the files in the new course**.
- We match, based on …
=> Fix course copy, fetch files form the current course, not the old one

lms/app.py, lms/renderers.py, lms/views/dashboard/api/assignment.py, tests/unit/lms/renderers_test.py, tests/unit/lms/views/dashboard/api/assignment_test.py
For:
- https://github.com/hypothesis/lms/issues/6748
---
Based on the default json serializer from pyramid but it formats datetime objects as isoformat().
It special cases datetimes without datetime information and assumes they are in UTC.
This commit introduces this seralizer as a new one on top of the default `json` as `json_iso_utc` an starts using it on the assignments API.
Short term we'll use this serializer in all dashboard related routes and longer term we'll replace all uses of json by this seralizer and then will make it the default.
- Compare the return payload from metrics `courses/metrics`:
```
{
"courses": [
{
"id": 261,
"title": "LTI 1.3 Testing",
"course_metrics": {
"assignments": 1,
"last_launched": "2024-10-02T14:23:03.566715"
}
}
]
}
```
no TZ information here, vs any …
=> New JSON renderer that handles datetime objects

lms/services/h_api.py, lms/services/organization_usage_report.py, tests/unit/lms/services/h_api_test.py
Some context of this being very slow:
https://hypothes-is.slack.com/archives/C0LUWQQJJ/p1727696994601579
---
We use this API call to fetch the groups of a given organization that have annotations.
The number of groups that belong to one organizations is potential very big so will make N request to the API based on starting batch size of 1000.
We start with a very big number to be able to tweak and balance the number of requests vs the performance of individual calls.
- Sanity check the batching with a diff like:
```
diff --git a/lms/services/h_api.py b/lms/services/h_api.py
index c76210234..c9891827f 100644
--- a/lms/services/h_api.py
+++ b/lms/services/h_api.py
@@ -143,7 +143,7 @@ class HAPI:
groups: Sequence[str],
annotations_created_after: datetime,
annotations_created_before: …
```
=> Batch calls to H groups API when we request data for a large number of groups

lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/RelativeTime.tsx, lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/DashboardBreadcrumbs.tsx, lms/static/scripts/frontend_apps/components/dashboard/SyncGradesButton.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/SyncGradesButton-test.js, lms/static/scripts/frontend_apps/components/test/RelativeTime-test.js, lms/static/scripts/frontend_apps/utils/api.ts, lms/views/dashboard/api/grading.py, tests/unit/lms/views/dashboard/api/grading_test.py
> Depends on https://github.com/hypothesis/lms/pull/6712 and https://github.com/hypothesis/lms/pull/6742
For auto-grading assignments, display the relative date in which last sync occurred.
Additionally, this PR refactors the `SyncGradesButton` so that the result of fetching current sync status is passed to it from the parent component. That way we can use that for the component displaying the last sync date, and eventually, in the students metrics table, to display individual syncing and error statuses.
This has the side effect that a few code blocks and tests have been moved from `SyncGradesButton/-test` to `AssignmentActivity/-test`.
There was some discussion around what date should be displayed as "last synced". At some point we considered exposing the date of the last non-in-progress …
=> Display last time grades were synced

lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/dashboard/SyncGradesButton.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/SyncGradesButton-test.js
> Part of [#6723](https://github.com/hypothesis/lms/issues/6723)
Add a countdown of students being synced while an auto-grading sync is in progress, instead of a spinner.
[Grabación de pantalla desde 2024-10-04 11-01-55.webm](https://github.com/user-attachments/assets/8336d97d-1eda-4008-b6be-e00c9ca93e29)
=> Display synced students count in auto-grading assignments

lms/views/dashboard/api/grading.py, tests/unit/lms/views/dashboard/api/grading_test.py
Since after https://github.com/hypothesis/lms/pull/6753, the view for `GET /grades/sync` endpoint is now using the `json_iso_utc` renderer from https://github.com/hypothesis/lms/pull/6750, this PR changes the `finish_date` so that it is returned as datetime instead of string, letting the renderer serialize it.
If you open an auto-grading assignment in the dashboard, there should be no visual differences.
=> Return grades sync finish_date as datetime

lms/migrations/versions/712c4c9a4e2e_create_lmsuserassignmentmembership.py
For:
Model changes over:
- https://github.com/hypothesis/lms/pull/6759
Testing instruction and more context over: 
- https://github.com/hypothesis/lms/pull/6760
=> Migration to create LMSUserAssignmentMembership

lms/models/__init__.py, lms/models/assignment_membership.py, tests/factories/__init__.py, tests/factories/assignment_membership.py
For:
Migration on:
- https://github.com/hypothesis/lms/pull/6758
Testing instruction and more context over: 
- https://github.com/hypothesis/lms/pull/6760
---
This is mostly a duplicate of AssignmentMembership but that table has a composite primary key that makes changes to the schema more challenging.
The new table continues the same line of work as LMSCourseMembership and similar tables.
It also includes the `lti_v11_lis_result_sourcedid` column to store the grading ID of the user in one assignment to enable participation grading in LTI1.1
=> Model definition for LMSUserAssignmentMembership

lms/services/assignment.py, lms/views/lti/basic_launch.py, tests/unit/lms/services/assignment_test.py, tests/unit/lms/views/lti/basic_launch_test.py
For:
---
This changes allow us store the LTI1.1 grading ID which is unique per assignment and user.
We do  this in a new table that follows the LMSUser, LMSCourse, LMSCourseMebmership patterns. This will allows to find membership objects without having to worry about duplicated users.
```
dev run-test-pre: PYTHONHASHSEED='602997392'
INFO …
```
=> Keep the LMSUserAssignmentMembership table in sync with AssignmentMembership

lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/SyncGradesButton.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/SyncGradesButton-test.js
Part of #6716
When the last sync status is `failed`, display the error information in a separated UI control, instead of the sync button itself.
The sync button should transition to the "Sync grades" state, so that grades that failed last time can be retried.
The designs also include a tooltip with the list of students whose grades failed to sync. However, we are also going to represent the individual sync statuses in every student row (see https://github.com/hypothesis/lms/pull/6756), so this may end up being duplicate information and I decided to not implement that here for now.
To test this, set the status of the last `grading_sync` to `failed`, as well as some of the `grading_sync_grade` that correspond to that sync.
=> Display error "badge" when last auto-grading sync failed

lms/services/lti_grading/_v11.py, lms/services/lti_grading/_v13.py, lms/services/lti_grading/factory.py, lms/services/lti_grading/interface.py, lms/tasks/grading.py, tests/unit/lms/services/lti_grading/_v11_test.py, tests/unit/lms/services/lti_grading/_v13_test.py, tests/unit/lms/services/lti_grading/factory_test.py, tests/unit/lms/tasks/grading_test.py
For:
---
- Adapt the interface of sync_grade to take a whole Assignment
This allows to take the service URL directly form the assignment in both versions and help find the right membership object in LTI1.1
- Implement the LTI1.1 version of the method.
- Check that nothing has changed syncing grades of a LTI1.3 assignment
https://hypothesis.instructure.com/courses/319/assignments/7296
- Test syncing a LTI1.1, it should behave the same way
https://hypothesis.instructure.com/courses/125/assignments/7777
=> Support for LTI1.1 on participation grading

lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/GradeIndicator.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/GradeIndicator-test.js
Depends on https://github.com/hypothesis/lms/pull/6755 and closes https://github.com/hypothesis/lms/issues/6723
Display information about individual sync statuses per student, including "error" or "syncing". 
[Grabación de pantalla desde 2024-10-07 13-44-31.webm](https://github.com/user-attachments/assets/2e498f31-ae05-4e0e-a343-27795bd0a77d)
=> Display information about individual student sync status

lms/static/scripts/frontend_apps/components/dashboard/GradeIndicator.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/GradeIndicator-test.js
Follow the [new designs](https://www.figma.com/design/ctCnzwkAyYArSNBYEshiCm/Hypothesis---LMS-Assignment-Grading?node-id=1981-147&node-type=frame&t=yMc9MmIArxsJe2tK-0) for the "syncing" badge in auto-grading assignments:
* Set a lighter background, which also improves contrast with text.
* Remove the text ellipsis, so that it is more consistent with other badges.
Before:
After:
=> Make syncing badge more subtle

lms/services/lti_grading/_v11.py, tests/unit/lms/services/lti_grading/_v11_test.py
Fixes:
https://hypothesis.sentry.io/issues/5974852740/?alert_rule_id=4849653&alert_type=issue&notification_uuid=26f3c7e6-6154-42d0-acb5-a246e9e0217f&project=259908&referrer=slack
We store one membership role per assignment, course and role. The existing query used SQLA .one() while querying by just assignment and student which would raise one more that one role existed.
Use .first instead and assert the existence of the membership object below.
The existing assert on  lti_v11_lis_result_sourcedid is there for the typechecker benefit but we also include that condition on the query
=> Fix assignment membership query to handle multiple rows per student/role

lms/static/scripts/frontend_apps/components/dashboard/SyncGradesButton.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/SyncGradesButton-test.js
In order to make it more clear when all grades are synced, this PR changes what gets displayed when the last sync succeeded, and there are exactly zero new grades to sync.
So far we were displaying the sync button disabled, with the text "Grades synced". It made sense for the button to be disabled, as otherwise people would have expected something to happen when clicking it, but that made the "grades synced" message to be too subtle.
This PR changes that so that we display a more prominent success message in place of the button when grades are currently synced. That way the message is more clear and easy to spot, but people won't expect nothing to happen when clicking on it, as it is no longer a button.
Before:
After:
https://github.com/user-attachments/assets/3ded2eb7-6e38-4fd9-8122-ca219 …
=> Make grades synced status more prominent

lms/models/lti_params.py, tests/unit/lms/models/lti_params_test.py
The creation and editing flow uses a form based API where we first serialize LTIParams for the frontend which then forwards it back to the server with the addition of any configuration for the assignment on the same form namespace.
LTIParams serialization doesn't whitelist a list of LTI parameters to forwards but instead includes every form parameter of the request except the authorization related ones.
When creation or edit includes the auto_grading_config option, this is included in the form by the FE, the BE reads the config from the form to make the changes to the assignment but also includes that key in the `formFields` serialized LTIParams for the next editing attempt.
We'll exclude `auto_grading_config` from LTIParams serialize as is not part of the LTI spec and just an internal …
=> Exclude `auto_grading_config` from LTIParams serialization

lms/migrations/versions/52755322151e_db_migration_to_back_fill_organizations.py, pyproject.toml
See: https://docs.astral.sh/ruff/rules/unnecessary-double-cast-or-process/
=> Enable ruff's C414 rule

lms/static/scripts/frontend_apps/components/FilePickerApp.tsx, lms/static/scripts/frontend_apps/components/FilePickerFormFields.tsx, lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js, lms/static/scripts/frontend_apps/components/test/FilePickerFormFields-test.js
Depends on https://github.com/hypothesis/lms/pull/6769
Implement logic so that the assignment edition form is initialized with current auto-grading config if it exists and the feature flag is enabled.
Additionally, forward this config in form fields so that assignments can edit their auto-grading config or even disable/enable it entirely.
https://github.com/user-attachments/assets/8e112b5d-285c-4a31-8171-b4ae0b3697ac
=> Forward auto-grading config when editing an assignment

lms/models/__init__.py, lms/models/assignment.py, lms/models/lti_params.py, lms/product/plugin/misc.py, lms/static/scripts/frontend_apps/components/FilePickerApp.tsx, lms/static/scripts/frontend_apps/components/FilePickerFormFields.tsx, lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js, lms/static/scripts/frontend_apps/components/test/FilePickerFormFields-test.js, lms/static/scripts/frontend_apps/config.ts, lms/validation/__init__.py, lms/validation/_lti_launch_params.py, lms/views/dashboard/api/assignment.py, lms/views/lti/basic_launch.py, lms/views/lti/deep_linking.py, tests/factories/__init__.py, tests/factories/assignment.py, tests/unit/lms/models/lti_params_test.py, tests/unit/lms/product/plugin/misc_test.py, tests/unit/lms/validation/_lti_launch_params_test.py, tests/unit/lms/views/lti/basic_launch_test.py
For:
- https://github.com/hypothesis/lms/issues/6768
---
Commenting here on the overall process for some context.
For LMS that support DL and non-DL flows we look for the configuration on:
- Our DB, this will include the last made changed via editing
This is common for launches after the assignment has been created.
- The previous version of this request, this will kick start the config of the assignment for course copy.
This might be the case for first launches of course copied assignments.
- Finally Deeplinked configuration
This will be the fallback and common on the first launch of the assignment.
See:
https://github.com/hypothesis/lms/blob/main/lms/product/plugin/misc.py#L69-L83
This PR only deals with the editing side of things but it needs to make the other changes here for testing …
=> Support for auto grading on the editing flow

lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/AutoGradingConfigurator.tsx, lms/static/scripts/frontend_apps/components/FilePickerApp.tsx, lms/static/scripts/frontend_apps/components/test/AutoGradingConfigurator-test.js
Create a single type definition representing auto-grading configuration. We had one in camelCase for the FE, and one in snake_case for the API.
This PR uses the later everywhere, so that we don't need to do casing conversions back and forth.
=> Consolidate auto-grading types

lms/static/scripts/frontend_apps/utils/test/vitalsource-test.js, lms/static/scripts/frontend_apps/utils/vitalsource.ts
Ignore leading or trailing whitespace in the input field when extracting VitalSource book IDs from the user's input in the assignment picker.
This is currently implemented in `extractBookID`, which mirrors how we do this for JSTOR, but could alternatively have been implemented as part of the input control.
Fixes https://github.com/hypothesis/support/issues/142 (see this issue for test case)
=> Ignore leading and trailing whitespace when extracting book IDs

conf/supervisord-dev.conf, conf/supervisord.conf
Email digest creates many tasks early in the morning which prevents other tasks from being executed.
We plan to move email digest tasks to its own queue, first we'll start listening to jobs in the queue and in a follow up PR we'll configure email digest task to use this queue to facilitate that transition.
See: https://github.com/hypothesis/lms/pull/6790
- Start the server locally with `make dev`
The celery startup message will show twice, once for the previous  "celery" queue:
```
worker               |  -------------- celery@lenovo v5.3.6 (emerald-rush)                                                                                                                    
worker               | --- ***** ----- …
```
=> Start a new celery worker that just listens to the email-digest queue

lms/js_config_types.py, lms/resources/_js_config/__init__.py, tests/unit/lms/resources/_js_config/__init___test.py
For:
- https://github.com/hypothesis/product-backlog/issues/1567
This will allow to expose the name of the scoped organization in the staff dashboards.
- Open an organization in the admin pages
- Open the dashboard from there
- Check the config returned by the BE:
```
"auto_grading_sync_enabled": null,
"organization": {
"name": "University of Hypothesis", "public_id": "us.lms.org.kXFNz2fJQBaQ3l5ZKF3nJA"
}, 
"routes":...
```
=> Expose organization info in the dashboard

lms/static/scripts/frontend_apps/components/dashboard/AllCoursesActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/CourseActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/DashboardBreadcrumbs.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AllCoursesActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/DashboardBreadcrumbs-test.js, lms/static/scripts/frontend_apps/config.ts, lms/static/scripts/frontend_apps/utils/dashboard/root-view-title.ts, lms/static/scripts/frontend_apps/utils/dashboard/test/root-view-title-test.js
Closes https://github.com/hypothesis/product-backlog/issues/1567
This PR changes the logic in the dashboard so that we display the organization name in the breadcrumb and "All courses" section, if the dashboard was opened for one particular org.
1. Open a course in the LMS admin, for example http://localhost:8001/admin/courses/1
2. In the upper-right corner, click "Open instructor dashboard"
3. You should see the organization name in the breadcrumbs top level element.
4. If you navigate to that element, AKA "All courses", you should see the organization's name as the view's title.
5. Now open the dashboard from an assignment in the LMS.
6. The elements mentioned above should display the text "All courses" now, as it has been up until now.
=> Display organization name in dashboard when available

lms/models/lms_course.py, lms/models/lti_user.py, lms/services/dashboard.py, lms/views/dashboard/views.py, tests/factories/__init__.py, tests/factories/lms_course.py, tests/unit/lms/services/dashboard_test.py
For:
- https://github.com/hypothesis/product-backlog/issues/1572
---
Give access to the dashboards for full organizations to users
that the LMS identifies as system wide admins (scope: system, type admin in our LTIRoles table)
- Log into BB as an instructor, e.g. `blackboardteacher`
- Open a bunch of assignments in different courses (these are the "same" assignment in different copied courses)
https://aunltd-test.blackboard.com/webapps/blackboard/execute/blti/launchPlacement?blti_placement_id=_20_1&content_id=_36_1&course_id=_19_1
https://aunltd-test.blackboard.com/webapps/blackboard/execute/blti/launchPlacement?blti_placement_id=_20_1&content_id=_1655_1&course_id=_153_1
https://aunltd-test.blackboard.com/webapps/blackboard/execute/blti/launchPlacement?blti_placement_id=_20_1&content_id=_1 …
=> Consider LTI role to grant admin status in the dashboards

lms/tasks/celery.py
Needs: https://github.com/hypothesis/lms/pull/6661
After adding a new queue on startup we'll send email digests tasks to the new queue. Existing task will still execute in the old queue.
- Start the server with `make dev` or restart it
- Go over http://localhost:8001/admin/email send a few emails
- Tags will get executed:
```
worker-email-digests (stderr) | [2024-10-22 15:26:33,251: INFO/MainProcess] Task lms.tasks.email_digests.send_instructor_email_digest[6641d500-babc-48bc-9418-af1fa4ac295f] received
worker-email-digests (stderr) | [2024-10-22 15:26:33,448: INFO/ForkPoolWorker-16] lms.tasks.email_digests.send_instructor_email_digest[6641d500-babc-48bc-9418-af1fa4ac295f] Task lms.tasks.email_digests.send_instructor_email_digest[6641d500-babc-48bc-9418-af1fa4ac295f] succeeded in …
```
=> Route email digest tasks to their own queue

lms/static/scripts/frontend_apps/components/TruncatedText.tsx, lms/static/scripts/frontend_apps/components/dashboard/DashboardActivityFilters.tsx, lms/static/scripts/frontend_apps/components/test/TruncatedText-test.js, package.json, yarn.lock
> Alternative to https://github.com/hypothesis/lms/pull/6812
> Part of https://github.com/hypothesis/product-backlog/issues/1561
Update dashboard filtering dropdowns so that:
1. Their listboxes never render out of the viewport, trying to make a smarter use of available space.
2. Their listboxes never grow bigger than the body.
3. Options with big content are truncated with `text-overflow: ellipsis`.
4. A `title` is added with the full content of listbox options when they have been truncated.
> [!NOTE]
> Points 1 and 2 are implicitly applied by updating frontend-shared to v8.8, which brings changes from https://github.com/hypothesis/frontend-shared/pull/1746
https://github.com/user-attachments/assets/d74a1b41-1d60-4e7a-bca6-bf8067869853
This approach has the problem that content may not be …
=> Make dashboard filters listboxes render always inside the viewport

lms/services/h_api.py
We keep seeing calls to this endpoint taking over 10s. The main culprit is the query the endpoint makes to get which groups have annotations. Reducing the number of groups we query per API calls should bring the API time down.
We can see the current total number of groups in this paper trail query.
https://my.papertrailapp.com/groups/14104911/events?focus=1789133066271342592&q=Generating+report+for
It seems like we have a few organizations with a few thousands of groups which should translate to one API call per 1000 groups now and calls for 250 groups after merging this.
=> Reduce batch size for H's groups bulk API call

lms/services/moodle.py
See: https://hypothes-is.slack.com/archives/C2BLQDKHA/p1730387908831469
---
We are seeing a school response that doesn't seem to contain the content type header we rely on to determine if a file still exists in Moodle.
Before we try alternative approaches to detect if a file exists lets add some logging to check the response headers.
One possible explanation could be that we are dealing with two different issues issues:
- The server doesn't return the content type header for this request
Maybe a different Moodle version? Some server configured in front of Moodle strips them.
- The file doesn't exist on the server or we can access it for some reason.
=> Add extra logging for Moodle's file check

lms/static/styles/moodle_pages/moodle_pages.scss
Migrate from SASS' global `darken` function, which is deprecated, to the `sass:color`'s module `color.adjust` function.
This solves two warnings reported by SASS:
```
DEPRECATION WARNING: Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.
Use color.adjust instead.
More info and automated migrator: https://sass-lang.com/d/import
╷
28 │ $link-hover-color: darken($link-color, 15%);
│                    ^^^^^^^^^^^^^^^^^^^^^^^^
╵
lms/static/styles/moodle_pages/moodle_pages.scss 28:20  root stylesheet
DEPRECATION WARNING: darken() is deprecated. Suggestions:
color.scale($color, $lightness: -30%)
color.adjust($color, $lightness: -15%)
More info: https://sass-lang.com/d/color-functions
╷
28 │ $link-hover-color: darken($link-color, 15%);
│ …
```
=> Fix SASS warnings due to deprecated functions

lms/models/grouping.py, lms/product/blackboard/_plugin/grouping.py, lms/product/canvas/_plugin/grouping.py, lms/product/d2l/_plugin/grouping.py, lms/product/moodle/_plugin/grouping.py, lms/services/__init__.py, lms/services/group_set.py, tests/unit/lms/models/group_set_test.py, tests/unit/lms/models/grouping_test.py, tests/unit/lms/product/blackboard/_plugin/grouping_test.py, tests/unit/lms/product/canvas/_plugin/grouping_test.py, tests/unit/lms/product/d2l/_plugin/grouping_test.py, tests/unit/lms/product/moodle/_plugin/grouping_test.py, tests/unit/lms/services/group_set_test.py, tests/unit/lms/services/roster_test.py, tests/unit/services.py
For: 
- https://github.com/hypothesis/lms/issues/6834
We currently only store group sets as a json array in "Grouping.extra". This is awkward to query and impossible to relate to other tables.
After creating LMS GroupSet we'll start recording groups sets in both tables in parallel.
- Start configuring an assignment with groups. We record the group sets the moment we list them in the creation screen, no need to to finish the configuration process.
For example:
https://hypothesis.instructure.com/courses/125/assignments/7412/edit?name=Assignment%20creation%20-%20test%20&due_at=&points_possible=0
- Check the data in the DB
```
select extra->'group_sets' from grouping where type = 'course' and extra->'group_sets' is not null;
?column? …
```
=> Store group set information in the new LMSGroupSet table

lms/migrations/versions/ba295703738b_backfill_lmsgroupset.py, tests/unit/lms/views/dashboard/pagination_test.py
For: 
- https://github.com/hypothesis/lms/issues/6834
After storing new group sets in https://github.com/hypothesis/lms/pull/6837 we'll backfill thet new table based on information from Grouping.extra
- Start configuring an assignment with groups. We record the group sets the moment we list them in the creation screen, no need to to finish the configuration process.
For example:
https://hypothesis.instructure.com/courses/125/assignments/7412/edit?name=Assignment%20creation%20-%20test%20&due_at=&points_possible=0
- Remove the rows on the new table
```
truncate lms_group_set;
```
- Run the migration
```
tox -e dev --run-command 'alembic upgrade head'     
dev run-test-pre: PYTHONHASHSEED='2142052960'
dev run-test-pre: commands[0] | pip-sync-faster requirements/dev.txt --pip-args …
```
=> Backfill migration for LMSGroupSet

lms/static/scripts/frontend_apps/components/dashboard/OrderableActivityTable.tsx
Closes https://github.com/orgs/hypothesis/projects/135?pane=issue&itemId=85690196
In some languages (like en-US), formatted dates displayed in the LMS dashboard need a bit more space than with other previously tested languages (like es-ES).
This PR reduces a bit the space reserved for the main dashboard table column in large resolutions, so that the rest of the columns have more available space and dates do not overflow.
Before:
After:
The reason dates overflow is because we use `white-space: nowrap` to avoid multiple lines, which are also not great. However, this has the side effect that, depending on the language, we may run out of space.
It would be good to test a few more languages, most common ones, and ensure we don't face similar issues, even with the changes introduced here.
=> Reserve less space for main dashboard column in large resolutions

lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/AutoGradingConfigurator.tsx, lms/static/scripts/frontend_apps/components/FilePickerApp.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/GradeIndicator-test.js, lms/static/scripts/frontend_apps/components/test/AutoGradingConfigurator-test.js
> Part of https://github.com/orgs/hypothesis/projects/135/views/1?pane=issue&itemId=85690560
This PR makes a few changes in the auto-grading configuration form, based on users feedback:
* Rename "Scaled" grading type to "Proportional". The change applies to user-facing texts only, as the internal value leaks to the BE and database. We can consolidate it later.
* Make "Proportional" the default grading type, and therefore, display it as the first option.
* Change subtitles for both grading types so that they explain how they work with an example.
Before:
After:
=> Rename "Scaled" grading type to "Proportional"

lms/static/scripts/frontend_apps/utils/api.ts, lms/static/scripts/frontend_apps/utils/test/api-test.js
This PR updates the result returned by `usePaginatedAPIFetch`, so that two new properties are included:
* `hasMorePages`: It's `true` if the server indicates there are still more pages to load, and `false` otherwise.
* `pageSize`: Indicates the maximum amount of items per page, or it's `undefined` if there's only one page.
These are useful for https://github.com/hypothesis/product-backlog/issues/1570, as they will allow us to display an exact number of items in the dropdown, or something like `100+` where 100 is the page size, but allowing to change the page sizes for every individual dropdown, without having to change the logic to represent the count badge.
=> Return pageSize and hasMorePages as part of usePaginatedAPIFetch result

lms/static/scripts/frontend_apps/components/dashboard/test/DashboardActivityFilters-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/PaginatedMultiSelect-test.js, lms/static/scripts/frontend_apps/components/test/GroupConfigSelector-test.js, package.json, yarn.lock
Update to frontend-shared 8.9, and fix a few tests that are broken due to the [change in Select](https://github.com/hypothesis/frontend-shared/pull/1762), that makes listbox content not to be rendered while it is closed.
The changes in tests involve:
1. Making sure the Select has been opened before trying to query for options or any other content that is rendered inside the listbox. One of the changes in frontend-shared 8.9 is that the listbox content is only rendered while it's open.
2. Attaching the component under test to an actual DOM element. This is required because the Select's listbox is displayed using the popover API, which throws if you try to use it on an unattached element.
=> Update to frontend-shared 8.9

lms/product/canvas/_plugin/grouping.py, lms/product/plugin/course_copy.py, lms/services/course.py, lms/services/group_set.py, tests/factories/__init__.py, tests/factories/lms_group_set.py, tests/unit/lms/product/canvas/_plugin/grouping_test.py, tests/unit/lms/product/plugin/course_copy_test.py, tests/unit/lms/services/course_test.py, tests/unit/lms/services/group_set_test.py
For: 
- https://github.com/hypothesis/lms/issues/6834
Reading group sets is used during course copy.
- First we need to fetch the groups on the original course to simulate it's initial configuration (when we store the groups).
Open https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2132/View **as an instructor** (I use `Marcos.Prieto`) edit it and force loading the group sets. No need to save the edit.
- Check the groups set are in the DB
```
select * from lms_group_set;
id | lms_id |          name          | lms_course_id |          created           |          updated           
----+--------+------------------------+---------------+----------------------------+----------------------------
38 | 22     | Group Category testing |           339 | 2024-11-07 14:23:43.794203 …
```
=> Switch group set reads to the GroupSetService

lms/migrations/versions/2f7913c24b69_backfill_lms_segment_sections.py
For:
- https://github.com/hypothesis/lms/issues/6851
- Launch a sections assignment: 
https://hypothesis.instructure.com/courses/125/assignments/874
- Check the values in LMSSegment:
``` 
select * from lms_segment where type = 'canvas_section';
id  |      type      | lms_id |   name    |         h_authority_provided_id          | lms_course_id | lms_group_set_id |          created           |          updated
-----+----------------+--------+-----------+------------------------------------------+---------------+------------------+----------------------------+----------------------------
127 | canvas_section | 144    | Section 1 | d2871e5e1c36b58f207d9ef5b22dcb7829f52e61 |           105 |                  | 2024-11-13 09:20:15.737572 | 2024-11-13 09:20:15.737572
128 | canvas_section | 145 …
```
=> Backfill LMSSegment (sections)

lms/static/scripts/frontend_apps/components/dashboard/ContentWithBadge.tsx, lms/static/scripts/frontend_apps/components/dashboard/DashboardActivityFilters.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/ContentWithBadge-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/DashboardActivityFilters-test.js, package.json, yarn.lock
> Closes https://github.com/hypothesis/product-backlog/issues/1570
> Depends on https://github.com/hypothesis/lms/pull/6850
Display the amount of items in a dashboard filter when that filter does not have a selected value.
This will help users know the items in those lists get filtered when selecting anything in the other filters.
Since filters are paginated, we'll be showing different values based on a set of conditions:
* When there's only one page of results, we'll display the total amount of results.
* When we have loaded the first page, the page size is 100, and we know there's more pages, we'll display `99+`. This ensures we keep the badge as "small" as possible for as long as possible.
* When we have loaded more than one page and we know there's still more pages, we'll display the …
=> Display amount of items in dashboard filters

lms/migrations/versions/50fb51c51314_backfill_lms_course_membership.py
For: 
We never stored course level membership information with roles. We only did that at the assignment level. 
Use the assignment level information to fill the parent course membership information. 
- Truncate the target and source tables:
```
truncate assignment_membership, lms_course_membership cascade;
```
- Launch a bunch of assignments
https://hypothesis.instructure.com/courses/125/assignments/874
- Check the state of the table now:
```
select lms_course_id, lms_user_id, lti_role_id from  lms_course_membership;
lms_course_id | lms_user_id | lti_role_id
---------------+-------------+-------------
104 | …
```
=> Backfill LMSCourseMembership

lms/static/scripts/frontend_apps/components/dashboard/PaginatedMultiSelect.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/PaginatedMultiSelect-test.js
This PR aims to fix two somewhat related but different issues:
1. Avoid loading next page in `PaginatedMultiSelect` when scrolling up:
Since we don't trigger next page loads when reaching the very bottom, but at a certain offset (20px ATM), it can happen that the user scrolls to the very bottom, and then scrolling a few pixels back up would trigger more loads, because we are still inside that offset gap.
2. Avoid a scroll event to be triggered when a new page of results is loaded:
Right before the new items are appended, the loading indicator is removed from the scrollable area that is the target for the scroll event, reducing its size. If the scroll is inside the offset gap, that triggers a new scroll event.
The good thing is that solving point 1 also solves point 2, because reducing the …
=> Avoid loading next page in PaginatedMultiSelect when scrolling up

lms/models/lms_user.py, lms/services/assignment.py, lms/services/dashboard.py, lms/services/h_api.py, lms/services/user.py, lms/views/dashboard/api/assignment.py, lms/views/dashboard/api/course.py, lms/views/dashboard/api/grading.py, lms/views/dashboard/api/user.py, lms/views/dashboard/views.py, tests/unit/lms/models/lms_user_test.py, tests/unit/lms/services/dashboard_test.py, tests/unit/lms/services/h_api_test.py, tests/unit/lms/services/user_test.py, tests/unit/lms/views/dashboard/api/assignment_test.py, tests/unit/lms/views/dashboard/api/course_test.py, tests/unit/lms/views/dashboard/api/grading_test.py, tests/unit/lms/views/dashboard/api/user_test.py, tests/unit/lms/views/dashboard/views_test.py
Split the get_user method into three different cases:
- Users for a single assignment
- Users for a single course
- Users for an organization and/or staff, ie with no filters
For these we use one simpler query that uses the new LMSUser/LMSCourse tables. This queries should be faster unless we are missing some indices.
Note that we still keep the old get_users, this will handle cases for which we have multiple assignments / course and/or segments filters. Those cases are less important for the roster features so will leave them for a follow up refactor.
---
This PR also uncludes small tweaks found along the way:
- https://github.com/hypothesis/lms/pull/6862/commits/4ce6f41192f32c55930d4fd9a7b5eaf9e6030347
Don't call the H api if there's no groups to request. This might happen (at least …
=> Refactor get_user and split it into multiple, single purpose, methods

lms/models/lms_user.py, lms/services/assignment.py, lms/services/dashboard.py, lms/services/h_api.py, lms/services/user.py, lms/views/dashboard/api/assignment.py, lms/views/dashboard/api/course.py, lms/views/dashboard/api/grading.py, lms/views/dashboard/api/user.py, lms/views/dashboard/views.py, tests/unit/lms/models/lms_user_test.py, tests/unit/lms/services/dashboard_test.py, tests/unit/lms/services/h_api_test.py, tests/unit/lms/services/user_test.py, tests/unit/lms/views/dashboard/api/assignment_test.py, tests/unit/lms/views/dashboard/api/course_test.py, tests/unit/lms/views/dashboard/api/grading_test.py, tests/unit/lms/views/dashboard/api/user_test.py, tests/unit/lms/views/dashboard/views_test.py
We can use the same helper method in the metrics and the dropdown API views.
This will become more useful once we include the roster concept, allowing to tweak the UserService call only in one place.
- Sanity check the dashboard, listing users metrics and users in the drop down while applying different filters.
=> Refactor user view, center calls to UserService.get_users

lms/services/roster.py, lms/templates/admin/assignment/show.html.jinja2, lms/templates/admin/course/show.html.jinja2, lms/templates/admin/macros.html.jinja2, lms/views/admin/assignment.py, lms/views/admin/course.py, tests/unit/lms/services/roster_test.py, tests/unit/lms/views/admin/assignment_test.py, tests/unit/lms/views/admin/course_test.py
We are going to need to start using the roster information for the auto grading feature.
To try to keep this PR size manageable we only introduce two simple methods here that just query the data.
As a bonus, mostly because it's pretty straightforward and because it simplifies testing, we also expose this information in the admin pages.
- Go to the admin pages, find the canvas LTI1.3 course
- Check the roster data at the course and assignment levels.
=> Roster service methods to retrieve data from the DB

lms/services/exceptions.py, tests/unit/lms/services/exceptions_test.py
It's not entirely clear if this is caused by a new condition, the access is revoked or the error message that canvas emits has change it's wording.
Logging this situation with the error message to keep track of how often we see them in the logs.
- Delete the token in canvas:
for `Working localhost (make devdata) API Key with All Required Scopes` 
in
https://hypothesis.instructure.com/profile/settings
- You'll get an error
- Launch again, you'll get a reauthorization prompt and will be able to launch after.
=> Force user re-authorization for revoked tokens

lms/models/application_instance.py, lms/services/dashboard.py, lms/services/roster.py, lms/services/user.py, lms/templates/admin/application_instance/show.html.jinja2, lms/templates/admin/assignment/show.html.jinja2, lms/templates/admin/course/show.html.jinja2, lms/templates/admin/macros.html.jinja2, lms/views/admin/assignment.py, lms/views/admin/course.py, lms/views/dashboard/api/user.py, tests/unit/lms/services/dashboard_test.py, tests/unit/lms/services/roster_test.py, tests/unit/lms/views/admin/assignment_test.py, tests/unit/lms/views/admin/course_test.py, tests/unit/lms/views/dashboard/api/user_test.py
Use assignment roster data when available and the FF is enabled.
Fallback to the "launch based" roster otherwise
We have three main cases.
- We have the feature flag enabled and we have the roster data
- We have the feature flag enabled and we don't have the roster data
- We have the feature flag disabled
Launch 
in `make shell`
```
```
(dashboard section, enable roster data)
http://localhost:8001/admin/instances/102/settings
- You'll see a bunch of students in the list and dropdown.
- You can filter by user using the drop down. …
=> Use assignment roster data when available and the FF is enabled

lms/tasks/roster.py
Now that we are starting to actually use the roster data fetch them more aggressively.
The task that fetches roster is currently scheduled to run every 15 minutes, change the number of rosters fetched from 5 to 50.
=> Increase the number of roster fetched in each task execution

lms/js_config_types.py, lms/views/dashboard/api/assignment.py, tests/unit/lms/views/dashboard/api/assignment_test.py
This is a potential fix for:
- https://github.com/hypothesis/product-backlog/issues/1608
This will allow  the FE to base the decision to show the "sync grades" button both on the feature flag (part of the JSConfig dictionary) and the current assignment's `is_gradable` value.
@acelaya Can you double check if this approach makes sense? I reckon we need both the FF in JSConfig and this new value. If the FF is enabled we'd still shouldn't show the button to sync grades for non-gradable assignments.
Also see:
- https://hypothes-is.slack.com/archives/C0LUWQQJJ/p1732217246293399 
- Check the new values is present on the JSON response and that that doesn't cause any issues
=> Expose assignment.is_gradable in the dashboard API

lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js, lms/static/scripts/frontend_apps/utils/dashboard/test/hooks-test.js
Depends on https://github.com/hypothesis/lms/pull/6867
Make sure the `SyncGradesButton` is not displayed for auto-grading assignments if they are not gradable.
We still display calculated grades in the dashboard, but we don't allow syncing, as that would fail if the BE indicates the assignment is not gradable.
> [!IMPORTANT]  
> The second commit in this PR is only meant to [fix an unrelated test](https://github.com/hypothesis/lms/actions/runs/12008780157/job/33472140156?pr=6869) which started to fail now.
> 
> I could not find the exact root cause, but I was able to tell it was related with the fact that multiple tests are using and modifying the global `history` object, and it seems to not be properly reset.
Creating an auto-grading assignment which is not gradable is not easy. The …
=> Hide `SyncGradesButton` for auto-grading non-gradable assignments

lms/tasks/roster.py, tests/unit/lms/tasks/roster_test.py
The existing query used a subquery that joined itself on assignments. That meant that that condition will return true if any event can be joined with an assignments, that's always true.
Avoid the join and use the parent query Assignment, making the subquery a correlated one to get the correct result.
This changes the SQL of this condition from something like:
`AND (EXISTS (SELECT event.id, event.timestamp, event.type_id, event.application_instance_id, event.course_id, event.assignment_id, event.grouping_id FROM event JOIN assignment ON event.assignment_id = assignment.id WHERE event.timestamp >= now() - '1 day '::interval))`
(with JOIN)
to
`
AND (EXISTS (SELECT event.id, event.timestamp, event.type_id, event.application_instance_id, event.course_id, event.assignment_id, event.grouping_id …
=> Fix query to find assignment rosters that need fetching

lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js, lms/static/scripts/frontend_apps/config.ts
Adjust FE to changes introduced in https://github.com/hypothesis/lms/pull/6873, removing the usage of auto-grading feature flags.
The changes imply:
- We now show the segments filter for any assignment, regardless the type.
- The sync button is now displayed for any gradable and auto-grading assignment, as long as the active user is not a hypothesis staff member.
=> Remove usage of auto-grading feature flags

lms/services/upsert.py, lms/services/user.py, tests/unit/lms/services/user_test.py
bulk_upsert will update the table columns in `update_elements` with the
value passed in updated.
In the case of lti_v13_user_id  that means that the value will be set on
LTI1.3  and removed (set to None) on LTI1.1 launches.
To fix this we change the value set from the raw value to
coalesce(value, LMSUser.lti_v13_user_id)
- Remove all of these IDs
```
update lms_user set lti_v13_user_id = null;
```
- Launch an LTI1.3 assignment:  https://hypothesis.instructure.com/courses/319/assignments/3336
- Check the value is now stored in the DB:
```select * from lms_user where lti_v13_user_id is not null;```
- Launch a LTI1.1 assignment: https://hypothesis.instructure.com/courses/125/assignments/873
- Check the DB again:
```select * from lms_user where lti_v13_user_id is not null;```
No results this …
=> Bugfix, clearing LMSUser.lti_v13_user_id on LTI1.1 launches

lms/services/user.py, tests/unit/lms/services/user_test.py
For:
Launch a LTI1.3 assignment https://hypothesis.instructure.com/courses/319/assignments/3308
- Check the value in the DB
```
select * from lms_user where lms_api_user_id is not null;
-[ RECORD 1 ]---------------+----------------------------------------------------
id                          | 2051
tool_consumer_instance_guid | VCSy8DAKCFIQYaItpSGyXhOXIlk5A6NWduVVG1u3:canvas-lms
lti_user_id                 | 969fc294ee26e3f1d0c9714af3351dc4eacfd6df
h_userid                    | acct:3a022b6c146dfd9df4ea8662178eac@lms.hypothes.is
email                       | eng+canvasteacher@hypothes.is
display_name                | DISPLAY NAME TEACHER
created                     | 2024-11-28 14:07:58.223625
updated                     | 2024-11-29 …
```
=> Store LMS API id on LMSUser during launches

tests/factories/attributes.py
We have seen some concurrency issues in CI test execution. This is an attempt to avoid collisions.
In `make shell`
```
In [1]: factories.LMSUser().h_userid
Out[1]: 'acct:user_73fc8e29-c77f-45fc-9b47-ec29f6388d2c@example.com'
In [2]: factories.User().h_userid
Out[2]: 'acct:user_730f470b-aab4-4360-a0a3-0b8de2555979@example.com'
```
=> Switch H_USERID factory from a sequence to an UUID.

lms/services/roster.py, tests/unit/lms/services/roster_test.py
For:
The LMSUser.lms_api_user_id now filled in https://github.com/hypothesis/lms/pull/6878 is also vaiivialbe in assignments rosters in Canvas.
We'll read it from the roster info while fetching it to speed up the backfill.
- Clear the DB to force roster fetching:
```truncate task_done, assignment_roster;```
- Clear any IDs you might have in the DB
```update lms_user set lms_api_user_id = null;```
- Launch a LTI1.3 assignment:
- Schedule the roster fetching, make shell:
```
```
- Check that some users have been backfilled:
```
select display_name, lms_api_user_id from lms_user where …
```
=> Backfill LMSUser.lms_api_user_id from the assignment roster data

lms/js_config_types.py, lms/models/application_instance.py, lms/resources/_js_config/__init__.py, lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js, lms/static/scripts/frontend_apps/config.ts, lms/templates/admin/application_instance/show.html.jinja2, tests/unit/lms/resources/_js_config/__init___test.py
Leave the main autoGradingEnabled configuration option but base it values on whether or not the install belongs to a Sakai school
Log in into sakai with `Sakai Administrator` on https://hypothesis-dev.longsight.com/
- Switch to `main`
-  Truncate assignments to force a reconfiguration
`truncate assignment cascade`
- Launch `localhost - autograding`, select a document, the option for auto grading is there.
- Switch to `remove-auto-grading-ff-fe`, try again, the auto grading option is not longer available.
=> Remove auto grading feature flags

tests/unit/lms/tasks/email_digests_test.py
See: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1733303125984169
Sorting the users that these fixtures return effectively randomises
their order (according to their randomly generated h_userid's) which
breaks some tests that implicitly depend on the order.
=> Fix a flakey test

lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js
> Depends on https://github.com/hypothesis/lms/pull/6899
Add a message under the students table when the list is generated from launches instead of a roster, so that teachers can better understand why some students may not be displayed in that case.
=> Roster info message

lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/GradeIndicator.tsx, lms/static/scripts/frontend_apps/components/dashboard/StudentStatusBadge.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/GradeIndicator-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/StudentStatusBadge-test.js
> Depends on https://github.com/hypothesis/lms/pull/6871
This PR adds a `drop` badge next to student names, if they have been marked as not active.
This property will be relevant only when the list of students comes from an LMS roster, but the BE will consistently return it as `true` for all students when the list is generated from launches.
The badge applies to unknown users as well.
> [!NOTE]
> At the moment of creating this PR, designs show a tooltip with the date in which a student dropped the assignment, but the BE does not expose that yet. Because of that, the tooltip is not addressed here.
Some future improvements that might make sense but are out of this PR scope, since they have not been aligned.
1. Use a lighter/italic/smaller font size for students that dropped the assignment. …
=> Display badge indicating when a student dropped an assignment

lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/RelativeTime.tsx, lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/LastSyncIndicator.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/LastSyncIndicator-test.js, lms/static/scripts/frontend_apps/components/test/RelativeTime-test.js
> Depends on https://github.com/hypothesis/lms/pull/6871
Add a roster sync indicator to the top of assignments activity sections.
This indicator can be displayed on its own, or next to the grade sync indicator for auto-grading assignments.
The grades sync indicator has also been updated to look the same as in the designs.
> Designs: https://www.figma.com/design/ctCnzwkAyYArSNBYEshiCm/Hypothesis---LMS-Assignment-Grading?node-id=1615-28&node-type=canvas&t=XWC8l0mi3ipleznw-0
> [!NOTE]  
> At this time, the designs show a way to show when fetching a roster failed, but this information is not correctly available, so this has not been implemented in this PR.
>
> Additionally, tooltips have been simplified.
Currently, the last_updated property is always ´null´, as more changes are needed in the …
=> Add roster sync indicator

lms/js_config_types.py, lms/static/scripts/frontend_apps/api-types.ts, lms/static/scripts/frontend_apps/components/RelativeTime.tsx, lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/GradeIndicator.tsx, lms/static/scripts/frontend_apps/components/dashboard/LastSyncIndicator.tsx, lms/static/scripts/frontend_apps/components/dashboard/StudentStatusBadge.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/GradeIndicator-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/LastSyncIndicator-test.js, lms/static/scripts/frontend_apps/components/dashboard/test/StudentStatusBadge-test.js, lms/static/scripts/frontend_apps/components/test/RelativeTime-test.js, lms/views/dashboard/api/user.py, tests/unit/lms/views/dashboard/api/user_test.py
Proposed changes to the API structure to accommodate roster meta-information on the metrics endpoint.
That endpoint currently return a list of students, update it to return an APIRoster object which does contain the same APIStudent entries augmented with:
active: bool, for each student.
last_udpaetd: datetime, for the whole roster.
Once we agree on a API format we could:
- In one PR change the API in the BE and the FE to expect the new structure
- In successive BE PRs, start sending the right data in the new fields.
- FE changes to present the new information.
More context:
- Proposed figma designs: https://www.figma.com/design/ctCnzwkAyYArSNBYEshiCm/Hypothesis---LMS-Assignment-Grading?node-id=2148-277&node-type=frame&t=LT23EqykFa2dtAsf-0
-  Slack thread: …
=> Expose roster information on the user metrics endpoint

lms/tasks/roster.py, tests/unit/lms/tasks/roster_test.py
Use the same logic as for assignments and courses.
For:
- https://github.com/hypothesis/lms/issues/6902
- Truncate any segment rosters you might have.
```
truncate lms_segment_roster ;
TRUNCATE TABLE
```
- Launch an LTI1.3 groups assignment
- On `make shell`, schedule fetching rosters
```
```
segment roster fetching is scheduled:
```
worker (stderr)      | [2024-12-09 10:09:17,408: INFO/ForkPoolWorker-1] lms.tasks.roster.fetch_segment_roster[3da79f05-6966-4626-a447-1ba2c3a9898c] Task lms.tasks.roster.fetch_segment_roster[3da79f05-6966-4626-a447-1ba2c3a9898c] succeeded in 0.6005973350256681s: None
worker (stderr)      | [2024-12-09 …
```
=> Schedule fetching canvas groups rosters

lms/data_tasks/report/create_from_scratch/02_entities/04_assignments/01_create_view.sql
For:
- https://github.com/hypothesis/product-backlog/issues/1613
This will change the type of assignments created every day (while running the "report refresh" GH action).
To backfill the historic data we need to run "create_from_scratch". We'll do that when we also have the "start of the week" code in to avoid having to run it twice.
=> Add missing document types to report assignment type query

lms/data_tasks/report/create_from_scratch/01_functions/01_date_functions.sql, lms/data_tasks/report/create_from_scratch/02_entities/03_events/01_create_view.sql, lms/data_tasks/report/create_from_scratch/05_activity_counts/02_groups/03_group_activity/01_create_view.jinja2.sql
For:
- https://github.com/hypothesis/product-backlog/issues/1612
This will affect new data, to refresh the existing data on report we'll need to run the GHA `create_from_scratch".
=> Use Sunday as the start of the week on report

.github/workflows/report_refresh.yml
We have been around 1h in the last few runs. Increase the time out to 1h and 30 minutes for now.
=> Increase the timeout for the report refresh workflow

lms/services/dashboard.py, lms/services/roster.py, lms/views/dashboard/api/user.py, tests/unit/lms/services/dashboard_test.py, tests/unit/lms/services/roster_test.py, tests/unit/lms/views/dashboard/api/user_test.py
We have been returning `True` for all entries until now. Actually return the value on the DB for roster entries and `True` for the ones based on launches.
- Open a LT1.1 assignment for which you have at least one student launch. Open the dashboard for it.
You get the list of students. No "drop" badges.
- Open a LTI1.3 assignment
- Make sure you have a roster for it, on `make shell`:
```
```
- Open the dashboard, you'll get the list of students, no badges.
- On `make sql`, set everyone as inactive:
```
update assignment_roster set active=false;
```
- Refresh the dashboard, …
=> Return the actual value for RosterEntry.active

lms/events/event.py, lms/tasks/event.py, tests/factories/__init__.py, tests/factories/event.py, tests/unit/conftest.py, tests/unit/lms/events/event_test.py, tests/unit/lms/tasks/event_test.py
Reverts hypothesis/lms#6832
This seems to be the cause of https://hypothes-is.slack.com/archives/C2BLQDKHA/p1733950680022549
Switching to the previous commit locally doesn't cause the issue while is consistent on this branch.
=> Revert "Store LTI launch parameters on EventData"

lms/models/lti_params.py, tests/unit/conftest.py
Use "http://www.brightspace.com" -> "org_defined_id" instead of nesting that on "https://purl.imsglobal.org/spec/lti/claim/launch_presentation"
Fixes the issue discussed over: https://hypothes-is.slack.com/archives/C2BLQDKHA/p1733264076402659
Has this ever worked? Was some initial school sending it on the wrong location?
In any case the only two install in the database that use this parameters are the ones with the issue discussed on slack so we don't have to worry about breaking anything on the old location.
- Launch https://hypothes-is.slack.com/archives/C2BLQDKHA/p1733264076402659
Check the payload for the lti_launches endpoint, it only a `id_token` parameter which is JWT.
Inspect it and check the relevant section:
```
"http://www.brightspace.com": {
"tenant_id": …
```
=> Pick org_defined_id from the right location

lms/events/event.py
We had a recent bug where LTIEvent.from_request modified the passed in data parameter.
Annotating the type as Mapping raises an type error trying to reassign keys with the following error:
Unsupported target for indexed assignment ("Mapping[Any, Any] | None")  [index]
While this doesn't prevent the issue in the whole codebase it's a good practice to annotate types with the most restrictive one.
=> Annotate event.data type as Mapping instead of dict

lms/validation/authentication/_bearer_token.py, tests/conftest.py, tests/factories/lti_user.py, tests/functional/views/lti/deep_linking_test.py
Just covering the LTI1.1 version on this commit.
This happens to be the first API functional test (other than LTI launches) in the code base.
This test breaks on the reverted commit https://github.com/hypothesis/lms/pull/6832 showing extra data showing on the payload.
=> Functional test for the DeepLinking fields API

lms/validation/authentication/_bearer_token.py, tests/conftest.py, tests/factories/lti_user.py, tests/functional/conftest.py, tests/functional/views/lti/basic_lti_launch_test.py, tests/functional/views/lti/deep_linking_test.py
Add a basic functional test for the LTI1.1 deep linking launch.
This is similar to the existing basic LTI launch test so there's some fixtures that are moved around and refactored to be able to reuse them in both cases.
This only cover the launch side of DeepLinking and the intention is just to have a sanity check type of test. In a follow up PR I'll add test for the API side of deep linking.
=> Basic functional test for DeepLinking launches

lms/data_tasks/report/create_from_scratch/02_entities/03_events/01_create_view.sql, lms/data_tasks/report/create_from_scratch/05_activity_counts/02_groups/03_group_activity/01_create_view.jinja2.sql
Fixes: [sentry issue](https://hypothesis.sentry.io/issues/6151425460/?alert_rule_id=4849653&alert_type=issue&notification_uuid=a9fa7651-769d-449e-bfe6-6f1c17fb37b3&project=259908&referrer=slack)
The multi_truncate function takes a date but we were passing a timestamp instead. Cast the type accordingly.
Issue introduced in: https://github.com/hypothesis/lms/pull/6910/
- Run 
```
tox -e dev --run-command "python bin/run_data_task.py -c conf/development.ini -t report/create_from_scratch"
```
in H first
- Run the same command in LMS now.
It success in this branch. Fails on `main`.
=> Fix report queries with a date type cast

lms/services/dashboard.py, lms/services/roster.py, lms/views/dashboard/api/user.py, tests/unit/lms/services/dashboard_test.py, tests/unit/lms/services/roster_test.py, tests/unit/lms/views/dashboard/api/user_test.py
We have been returning `None` for all entries until now. 
Actually return the value on the DB for roster entries and `None` for the ones based on launches.
- Open a LT1.1 assignment for which you have at least one student launch. Open the dashboard for it.
You'll see the 
```Full roster data for this assignment is not available. This only shows students who have previously launched it.```
message.
- Make sure you have the application instance setting enabled:
http://localhost:8001/admin/instances/102/settings 
`Enable roster data`.
- Open a LTI1.3 assignment
- Make sure you have a roster for it, on `make shell`:
```
from lms.tasks.roster import …
```
=> Return actual value for roster last_updated

lms/views/dashboard/api/user.py, lms/views/dashboard/pagination.py, tests/unit/lms/views/dashboard/api/user_test.py
While working on exposing the segments dashboard I notice a bug, selecting multiple segments in `main` fails.
This PR fixes that bug only, keeping exposing the segment rosters in a separate PR.
- On `main` open the dashboard on an assignments with groups, filter by groups. You'll get an error.
- Repeat the process on this branch. No error.
=> Fix issue while trying to fetch multiple groups rosters

tests/unit/lms/data_tasks/report/create_from_scratch/test_01_functions/test_01_date_functions.py
A previous fix for leap days broke the test for non leap years.
Original commit: https://github.com/hypothesis/lms/pull/6073
=> Fix report's multi truncate test

lms/models/lms_course.py, lms/services/course.py, tests/unit/lms/services/course_test.py
For:
- https://github.com/hypothesis/product-backlog/issues/1617
Use the value from the custom variables in canvas this indicates the course deviates from the term of the course.
We have been requesting these variables as part of the default custom variables in the config json for a while so we'll get a data for a few schools.
We'll look into applying the same patter in other LMSes.
- Launch an assignment that doesn't send the course dates
- Check the DB, no dates for this course, in `make sql`
```
select * from lms_course where lti_context_id = 'f3cd019017839c4630358662a05540f2f6ec5f93';
-[ RECORD 1 …
```
=> Store course start and end when available

lms/migrations/versions/cf20e70211f9_add_api_to_lmscourse.py
Migration to add a column for the API id for courses.
Auto generated from:
- https://github.com/hypothesis/lms/pull/6943
More context and testing instructions: 
- https://github.com/hypothesis/lms/pull/6944
=> Migration to add lms_api_course_id to LMSCourse

lms/services/course.py, tests/unit/lms/services/course_test.py
For:
Course have a LTI identifier that it's send on every launch but also have a API only ID that's needed to talk to the proprietary API of each LMS.
We do store the canvas version of this ID in a json dict in Grouping.extra but this train of PR promotes it to its own column.
- Log into canvas (`eng+canvasteacher@hypothes.is`) and launch:
- Check the correct value (125) is present on lms_course now, in `make sql`:
```
select * from lms_course where lms_api_course_id = '125';
-[ RECORD 1 ]---------------+----------------------------------------------------
id                          | 1056 …
```
=> Store the API ID for canvas courses on LMSCourse

lms/migrations/versions/9be518500f7d_backfill_lmscourse_api_lms_course_id.py
For:
While this data was in the database as part of Grouping.extra we "promoted" it to its own column on LMSCourse to make it easier to query and index.
While we only have this now for canvas now the new column names is a generic one now
See: https://github.com/hypothesis/lms/pull/6944
- Launch a couple of assignment from different courses
- Remove the ID set [by the previous PR](https://github.com/hypothesis/lms/pull/6944)
in `make sql`
```
update lms_course set lms_api_course_id = null;
UPDATE 2
```
- Run the migration to backfill the values back:
```tox -e dev --run-command 'alembic upgrade head'```
- Check the …
=> Migration to backfill LMSCourse.lms_api_course_id from existing grouping rows

lms/services/dashboard.py, lms/services/roster.py, lms/services/segment.py, lms/services/user.py, lms/views/dashboard/api/user.py, tests/factories/__init__.py, tests/factories/lms_segment.py, tests/unit/lms/services/dashboard_test.py, tests/unit/lms/services/roster_test.py, tests/unit/lms/services/segment_test.py, tests/unit/lms/services/user_test.py, tests/unit/lms/views/dashboard/api/user_test.py
Segment rosters are used a bit differently than assignments ones.
We allow filtering by **multiple** rosters and we'll display a list of those students with the metrics. For assignments we only allow to select one assignment at the time.
This adds a bit of extra complexity as we need to query the roster as a combination of rosters. Over time we'll likely move to "multi select" filters in more places in the dashboards but for now just using it on the place the UI allows for that type of query.
- Launch a LTI1.3 assignment using groups:
- Fetch the roster for those, in `make shell`:
```
from lms.tasks.roster import schedule_fetching_rosters 
```
- Open the dashboard for the assignment
- Select …
=> Expose segment rosters on the dashboards

lms/services/canvas_api/client.py, lms/services/roster.py, tests/factories/lms_user.py, tests/unit/lms/services/canvas_api/client_test.py, tests/unit/lms/services/roster_test.py
This PR includes a new method to fetch section rosters. It  doesn't yet fetch (schedule) rosters yet.
This are different than the other ones we have so far (course, assignments and Canvas groups in a few different ways:
- We use the Canvas API instead of the LTI one. This means we have to deal with users tokens, refreshing them etc.
For now we'll just attempt a token refresh if necessary. If that, or anything else fails, we'll give up.
- The API doesn't provide enough information to create the users we haven't seen.
This means that section rosters only help us to organize existing users into existing sections.
We fetch sections on every launch so discovering sections shouldn't be a concern. 
Not being able to discover new users means that we'd need the course/section roster to begin with. …
=> Fetch canvas sections rosters

lms/services/__init__.py, lms/services/canvas_api/client.py, lms/services/canvas_api/factory.py, lms/services/file.py, lms/services/roster.py, tests/factories/lms_user.py, tests/unit/lms/services/canvas_api/client_test.py, tests/unit/lms/services/canvas_api/factory_test.py, tests/unit/lms/services/file_test.py, tests/unit/lms/services/roster_test.py
Take application_instance and user_id on the Canvas API factory
to allow creating a service for arbitrary users instead of just the one
of the current request.
The same modification is also made to the file service
as it is a dependency of the Canvas service.
This will allow us to use the Canvas API to fetch sections rosters outside the request cycle, using any application instance we need.
- Sanity check the existing factory with a canvas files assignment
=> Refactor the canvas API factory to take parameters

lms/services/vitalsource/_client.py, lms/services/vitalsource/service.py, tests/unit/lms/services/vitalsource/service_test.py
The existing SKU was for a perpetual license but recently a new SKU for a limited duration.
While no new licenses are granted for the old sku existing students might only have that one.
This change adds a check for the new SKU if the old one is not found.
More context and details about the different skus on:
https://hypothes-is.slack.com/archives/C2BLQDKHA/p1737069466987259
- We can't reproduce the exact scenario (fallback from the old SKU to the new one)  but we can test the general mechanisms.
- Use a student account eg: `eng+canvasstudent@hypothes.is`. We only do VS license checks for students.
- Open this assignment which is configured to use VS student pay
https://hypothesis.instructure.com/courses/638/assignments/6493
- You'll get the following on the console:
```
2025-01-21 …
```
=> Check multiple VS SKUS for the student pay license check

.gitignore
See:
- Add *.tsbuildinfo files to .gitignore
https://github.com/hypothesis/cookiecutters/commit/819732a9422e241bfe58afea1d3b6cc29a3ab727
- Only gitignore build directory at root of repository
https://github.com/hypothesis/cookiecutters/commit/9494fe534c5cde15f1dfe19d5b2f189fcc91ef40
=> Include last .gitignore changes from the cookiecutter

.github/workflows/ci.yml
Ported from the cookiecutter template, see:
https://github.com/hypothesis/cookiecutters/commit/659029705ec2d185c1ae1f9cb7155f3a80634e5b
=> Fix coverage on CI when multiple Python versions

.github/workflows/ci.yml
This changes was made on the cookiecutter template but not actually applied to the main file
=> Use the default worker for linting on GHA

lms/services/canvas_api/client.py, lms/services/canvas_api/factory.py, tests/unit/lms/services/canvas_api/client_test.py, tests/unit/lms/services/canvas_api/factory_test.py
We suspect different permissions and roles configuration at schools affect the resulting payload.
Log the API call results to confirm this.
More context about the issue we are finding at: https://hypothes-is.slack.com/archives/C2BLQDKHA/p1737729175299909
- Launch a groups assignment https://hypothesis.instructure.com/courses/125/assignments/1833
- Click the "Speed grader" button on the top right corner.
- Check the new logging line on the server
```
Canvas API. Course groups. 'include_users'=True. 'application_instance_id'=8
```
=> Add extra logging around the Canvas API call groups endpoint

lms/migrations/versions/a8fd48c30957_create_the_lms_term_table.py
Migration auto generated from:
https://github.com/hypothesis/lms/pull/6971
https://github.com/hypothesis/lms/pull/6969
=> Migration for the LMSTerm model

lms/models/lti_params.py, lms/services/__init__.py, lms/services/course.py, lms/services/lms_term.py, tests/unit/lms/services/course_test.py, tests/unit/lms/services/lms_term_test.py, tests/unit/services.py
We'll start storing this data based on launches that contain the lastest Canvas configuration, which includes variables about terms.
This will allow us to build a backlog of courses with start and end dates.
We recently did a similar job to store course dates, which in Canvas means courses that don't belong to a term. In combination this commit this should give us coverage of all LTI1.3 courses for schools that have the most recent configuration.
See: https://github.com/hypothesis/lms/pull/6941
--- 
- Apply the migration 
```
tox -e dev --run-command 'alembic upgrade head' 
dev run-test-pre: PYTHONHASHSEED='4055832553'
INFO …
```
=> Store canvas terms info on the database

lms/static/scripts/frontend_apps/components/dashboard/PaginatedMultiSelect.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/PaginatedMultiSelect-test.js, package.json, yarn.lock
> Part of https://github.com/hypothesis/support/issues/178
> Depends on https://github.com/hypothesis/frontend-shared/pull/1864
Use the fixes introduced in https://github.com/hypothesis/frontend-shared/pull/1864 to ensure all pages are loaded in `PaginatedMultiSelect` as you scroll down.
1. Go to https://hypothesis.instructure.com/courses/319/assignments and log in as instructor
2. Launch a "bunch" of localhost assignments from there, to build a relatively long list.
3. Go to http://localhost:8001/dashboard/courses/1. You should see all assignments you lunched listed there, and they should also show in the "Assignments" dropdown.
4. Apply this diff, which does two things: a) reduce the items per page returned by paginated API calls and b) reduce the size of Select popovers, so that scroll …
=> Fix only first page being loaded in PaginatedMultiSelect

lms/services/lti_names_roles.py, tests/unit/lms/services/lti_names_roles_test.py
Pagination was missing on the original name and roles service implementation and never added when used for rostering. 
- Apply a diff like:
```diff --git a/lms/services/lti_names_roles.py b/lms/services/lti_names_roles.py
index 55a539ef0..7a50d40c1 100644
--- a/lms/services/lti_names_roles.py
+++ b/lms/services/lti_names_roles.py
@@ -41,7 +41,7 @@ class LTINamesRolesService:
service_url: str,
resource_link_id: str | None = None,
max_pages: int = 10,
-        limit: int = 100,
+        limit: int = 5,
) -> list[Member]:
"""
Get the roster for a course or assignment.
```
- Remove local rosters, in `make sql`:
```truncate course_roster, task_done CASCADE;```
- Launch any LTI1.3 assignment
- Schedule roster fetching, in `make …
=> Follow pagination links on the LTI names and roles API responses

lms/views/dashboard/api/user.py, tests/unit/lms/views/dashboard/api/user_test.py
We might return DB "Users" or "LMSUsers" depending if the data comes from rosters of launches.
Use the appropriate columns to sort users
We need to confirm this is working on both type of users
- Launch an LTI1.1 assignment where you have enough students launches to trigger pagination.
I'm using https://hypothesis.instructure.com/courses/125/assignments/873
- Open the dashboard, the drop down pagination returns different students in the second page.
- Repeat the test on a LTI1.3 
https://hypothesis.instructure.com/courses/319/assignments/7296
- You might need to force a roster fetch if you don't have one locally, in `make shell`:
```
```
- Also testing might be easier with a smaller page size:
```diff …
```
=> Use the appropriate columns to sort users

lms/services/auto_grading.py, tests/unit/lms/services/auto_grading_test.py
The code alreayd handles 0 required replies correctly, but it was deliberately ignoring the None value.
Assign a 0 to the None value to complete the calculation
=> Handle `None` required replies

lms/services/roster.py, tests/unit/lms/services/roster_test.py
These are causing:
```
CardinalityViolation: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
```
See:
https://hypothesis.sentry.io/issues/6238959334/?environment=prod&project=259908&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&statsPeriod=90d&stream_index=2
I've not been able to reproduce this with real data, but the new test cases do fail with the same exception on `main` so this looks like the right fix.
=> Deduplicate students from Canvas sections API response

lms/services/roster.py, tests/unit/lms/services/roster_test.py
We can't do about it and it's only adding noise on the logs/sentry.
We'll still log a message about it in case we need to debug these:
"Requested assignment not configured for external tool launches"
=> Ignore error when fetching assignment roster

lms/views/exceptions.py
Depending on when the exception has happened,
the renderer might be set to a different one.
Use the override to always use the basic error template.
Relevant conversation: https://hypothes-is.slack.com/archives/C2C2U40LW/p1738361139273649
This is very similar to https://github.com/hypothesis/lms/pull/6997 but for any type of error
- First in `main`
- Apply a diff like:
```diff 
--git a/lms/services/ltia_http.py b/lms/services/ltia_http.py
index f4fd27a78..c118bb4df 100644
--- a/lms/services/ltia_http.py
+++ b/lms/services/ltia_http.py
@@ -93,6 +93,9 @@ class LTIAHTTPService:
try:
token_data = response.json()
+            1 / 0
except JSONDecodeError as err:  # pragma: no cover
LOG.error("Non-json response: %s", response.text)
raise SerializableError(
```
- Launch a gradable D2L assignment …
=> Always use the error template for unexpected exceptions

lms/services/roster.py, tests/unit/lms/services/roster_test.py
We account for the API returning no "students" key in the response but Canvas can return this key with a value of None.
This bug was introduced in https://github.com/hypothesis/lms/pull/6996
Fixes:  https://hypothesis.sentry.io/issues/6270489525/?environment=prod&project=259908&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&statsPeriod=90d&stream_index=1
=> Guard against Canvas API response with None students

lms/product/canvas/_plugin/course_copy.py, lms/product/plugin/course_copy.py, tests/unit/lms/product/canvas/_plugin/course_copy_test.py
In cases where for example students don't have access to list files this allows the course copy process to continue using the information in our DB.
If the course copy ultimately fails we'll raise an exception for that particular situation.
1. At some point an instructor configures a file assignment in the original course.
2. We store all the files in that course in the DB, including the one selected for the assignment
3. The course gets copied in the LMS
4. A new instructor launches the new course
5. We realize the assignment is configured with a file ID that's not in the new course
6. We fetch all the files in the new course.
7. We match, based on the info we have now on the DB, the old file to the new file (for example based on name).
8. We store a map of new file to old file to avoid …
=> Ignore API exceptions while listing files for course copy

lms/services/assignment.py, tests/unit/lms/services/assignment_test.py
If we already have a value for lti_v11_lis_result_sourcedid in the DB don't overwrite it with a null value.
It's not entirely clear in which situations we'll get a None value after having already one in the DB but we have seen this happening in the wild.
Slack thread with more details:
https://hypothes-is.slack.com/archives/C2BLQDKHA/p1738852258730769?thread_ts=1738849292.643179&cid=C2BLQDKHA
Unfortunately I don't know how to replicate the LMS sending a null value here. I reckon the unit test does a good job here thought.
=> Don't clear lti_v11_lis_result_sourcedid when updating

lms/views/dashboard/api/assignment.py, tests/unit/lms/views/dashboard/api/assignment_test.py
To display the number of annotations on each of the assignments of
a course we need to send a list of users to H to exclude instructors.
This list of users was not based on the roster whilst the count by student
on the assignment is leading to a discrepancy in the counts.
This commit changes the method to use the roster to get the list of users
Found this issue in production, here we can see 0 annotations:
https://lms.hypothes.is/dashboard/orgs/us.lms.org.l4_OaHbURiqu88m7lmKDPQ/assignments/414569
but "13" on assignment list level: 
https://lms.hypothes.is/dashboard/orgs/us.lms.org.l4_OaHbURiqu88m7lmKDPQ/courses/32848029
I've not replicated this issue locally. 
Sanity check the assignment list locally.
=> Use roster for course assignment counts

tests/unit/lms/views/dashboard/api/assignment_test.py
This changes was made in a brach not rebased with the latest rule selection in `main`.
=> Fix linting after ruff rules update

lms/services/roster.py, tests/unit/lms/services/roster_test.py
OAuth2Error was missing in the except block while refreshing the token for section roster. This PR adds the missing exception to the except block, together with: ConcurrentTokenRefreshError and CanvasAPIError.
=> Catch OAuth2Error while refreshing token for section roster

lms/services/roster.py, tests/unit/lms/services/roster_test.py
A full exception in the logs and sentry report is overkill for this type of error.
Just log the message so we can debug them if needed
=> Ignore canvas assignment roster error

lms/services/dashboard.py, lms/services/user.py, tests/unit/lms/services/dashboard_test.py, tests/unit/lms/services/user_test.py
This simplifies the query and makes for a more clear method signature.
=> Simplify get_users_for_course to take LMSCourse instead of Grouping.id

lms/services/exceptions.py, lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.tsx, lms/static/scripts/frontend_apps/components/test/BasicLTILaunchApp-test.js, lms/static/scripts/frontend_apps/utils/api.ts, lms/views/api/exceptions.py, lms/views/api/grading.py, lms/views/helpers/__init__.py, lms/views/helpers/_logging.py, tests/unit/lms/views/api/exceptions_test.py, tests/unit/lms/views/api/grading_test.py, tests/unit/lms/views/helpers/_logging_test.py
Canvas submissions are sent when the first annotations is made during a "session" on a gradable assignment.
We have some error handling and display error dialogs accordingly but due to the indirect nature of the action is tricky to handle transactional errors like timeouts.
This commits adds a "flag" on the response of API calls to our own frontend marking the request as "retryable" allowing the FE to retry them.
- Apply a diff like
```
diff --git a/lms/views/api/grading.py b/lms/views/api/grading.py
index 7b072a36d..430d0f0cc 100644
--- a/lms/views/api/grading.py
+++ b/lms/views/api/grading.py
@@ -103,6 +103,9 @@ class GradingViews:
+        if not self.request.headers.get("Retry-Count"):
+            raise ExternalRequestError(retryable=True)
+
lis_result_sourcedid = …
```
=> Retry Canvas submission on timeout

lms/templates/config.xml.jinja2, lms/views/canvas/config.py
Use a common list of variables in both config files
These are out of sync since: https://github.com/hypothesis/lms/commit/bbecb19fd515873b988d43aee99f1d79306b426a
For the LTI1.3 config (json) the unit test checks the exact contents.
For the LTI1.1 compare the the local and prod version:
http://localhost:8001/config_xml
https://lms.hypothes.is/config_xml
=> Align canvas 1.1 and 1.3 config custom variables

lms/services/user.py, tests/unit/lms/services/user_test.py
This change will allow us to get some basic percentage of students that do send this data during launch vs those who don't **without actually storing it**.
We can revert the change after a week or two of data reporting.
=> Log the presence or absence of student email addresses

lms/views/canvas/config.py, tests/unit/lms/views/canvas/config_test.py
While we only ever needed this for the VitalSource integration, as the field to fetch the user reference, it's less error prone to always ask for it in every new install.
See:
- https://hypothes-is.slack.com/archives/C2BLQDKHA/p1740060985408929?thread_ts=1739542083.490679&cid=C2BLQDKHA
=> Adding Canvas.user.loginId to the default list of custom variables

tests/unit/lms/data_tasks/report/create_from_scratch/test_01_functions/test_01_date_functions.py
Otherwise the test fail based on the current date
depending on the leap year status, etc.
=> Hardcode dates for multi_truncate_date test

lms/models/lti_role.py, tests/unit/lms/models/lti_role_test.py
For:
- https://github.com/hypothesis/product-backlog/issues/1595
This role is always found in combination with other role so this change shouldn't have
an immediate impact on the system.
From the spec:
https://www.imsglobal.org/spec/lti/v1p3#lti-vocabulary-for-system-roles
This is a marker role to be used in conjunction with a "real" role.
It indicates this user is created by the platform for testing different user scenarios.
=> Add TEST_USER as a possible role type

tests/unit/lms/data_tasks/report/create_from_scratch/test_01_functions/test_01_date_functions.py
trailing_year relies on the current date internally and it's behavior is wonky around leap years.
Instead of trying to reliable test for it or change it's behavior we'll test every other function in the module.
=> Change the tests of multi_truncate to test every function but trailing_year

lms/models/application_instance.py, lms/models/json_settings.py, lms/templates/admin/application_instance/show.html.jinja2, lms/views/admin/application_instance/search.py, lms/views/admin/application_instance/update.py, tests/unit/lms/models/application_instance_test.py, tests/unit/lms/models/json_settings_test.py, tests/unit/lms/views/admin/application_instance/update_test.py
See: https://github.com/hypothesis/lms/pull/6043
This PR adapts #6043 to be used on top of https://github.com/hypothesis/lms/pull/7041 and only applies it to one setting for now.
- Open the admin pages settings for one AI: http://localhost:8001/admin/instances/8/
- Check the value of the setting in `make shell`
```
ai = db.get(models.ApplicationInstance, 8)
ai.settings.get_setting(ai.settings.fields[ai.settings.Settings.YOUTUBE_ENABLED])                                                                                                    
True
```
Change the values in the admin pages and recheck in the shell, you'll need to `db.refresh(ai)` between changes.
- Finally set the value to "Default (True)" in the admin pages, change now the default in the code 
```
diff --git …
```
=> Use tri-state enabled/disabled/default controls for feature flags

lms/models/application_instance.py, lms/models/json_settings.py, lms/models/organization.py, lms/services/youtube.py, lms/templates/admin/application_instance/search.html.jinja2, lms/templates/admin/application_instance/show.html.jinja2, lms/templates/admin/macros.html.jinja2, lms/templates/admin/organization/show.html.jinja2, lms/views/admin/application_instance/search.py, lms/views/admin/application_instance/show.py, lms/views/admin/application_instance/update.py, lms/views/admin/organization.py, tests/unit/lms/models/application_instance_test.py, tests/unit/lms/models/json_settings_test.py, tests/unit/lms/views/admin/application_instance/update_test.py, tests/unit/lms/views/admin/organization_test.py
Application settings in installs and organizations are a subclass of dict with some extra methods to handle a namespace (group and key).
These were defined for installs (but not orgs) but that definitions are only used to list them for the settings filter in this page:
https://lms.hypothes.is/admin/instances/
This PR:
- Adds an enum value for each setting to avoid having a "string typed" access to them
- Allows using JSONSetting object itself to fetch the setting based on it's config
- Adds an optional default value that can then be used when fetching the setting.
It only applies it to two settings, "hypothesis.notes", which is the only "textarea setting"  and "youtube.enabled" to demonstrate the usage of the default value.
=> Use an enum for ApplicationSettings and include a default value.

lms/models/application_instance.py, lms/models/lti_user.py, lms/services/lti_role_service.py, lms/services/roster.py, lms/services/user.py, lms/templates/admin/application_instance/show.html.jinja2, tests/unit/lms/models/application_instance_test.py, tests/unit/lms/services/roster_test.py, tests/unit/lms/services/user_test.py
Based on the new style of tri-state "checkboxes" introduced in https://github.com/hypothesis/lms/pull/7046
- Truncate your local users, in `make sql`:
`truncate lms_user, "user" cascade;`
- Launch https://hypothesis.instructure.com/courses/319/assignments/3336 as `eng+canvasstudent@hypothes.is`
- Check the DB, no email was recorded:
```
select display_name, email  from lms_user;
display_name      | email 
------------------------+-------
Hypothesis 101 Student | 
(1 row)
```
- Change the value of the new setting on the admin pages:
http://localhost:8001/admin/instances/102/settings
Set "Collect student emails" to Enabled.
- Launch https://hypothesis.instructure.com/courses/319/assignments/3336 again
- We got the email now:
```
select display_name, email  from lms_user;
display_name      | …
```
=> Collect student emails based on a new feature flag

lms/models/application_instance.py, lms/templates/admin/application_instance/show.html.jinja2, lms/views/lti/basic_launch.py, tests/unit/lms/models/application_instance_test.py, tests/unit/lms/views/lti/basic_launch_test.py
This setting is forwarded to the client config using "js_config.enable_client_feature"
Same approach as: https://github.com/hypothesis/lms/pull/5692
See: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1741795591884319
=> Add an AI setting for mentions

conf/supervisord-dev.conf, conf/supervisord.conf, lms/tasks/annotations.py, lms/tasks/celery.py, tests/unit/lms/tasks/annotations_test.py
Right now we won't do anything about the messages, just consume them to keep the queue empty This will be useful to setup the publishing side without building a backlog of tasks.
See https://github.com/hypothesis/h/pull/9402 for more context and testing instructions.
=> Consume messages about annotations published by H

lms/static/scripts/frontend_apps/components/dashboard/DashboardApp.tsx
A few weeks ago we [updated and consolidated](https://github.com/hypothesis/frontend-shared/pull/1849/files) all our icons. Among other things, that accidentally reduced the default size of the logo icon.
This PR ensures the same size as before is used when rendered in the LMS dashboard header icon.
Before:
After:
=> Fix dashboard logo size

.cookiecutter/includes/conf/supervisord-dev.conf.json, .cookiecutter/includes/conf/supervisord.conf.json, .cookiecutter/includes/requirements/prod.in, .gitignore, Makefile, lms/tasks/annotations.py, requirements/dev.txt, requirements/functests.txt, requirements/lint.txt, requirements/prod.in, requirements/prod.txt, requirements/tests.txt, requirements/typecheck.txt, tests/unit/lms/tasks/annotations_test.py
In this PR:
- We apply the latest changes from the cookiecutter
- We include pydantic as a dependency
See: 
https://hypothes-is.slack.com/archives/C1MA4E9B9/p1742317088514549
- And we do basic processing of annotation events, just a log line per mention for now.
- On an LMS assignment, test the following cases:
- Self mention
- Mention someone else, but post it on "Only me"
- Mention someone else
The logs on the LMS server will reflect each of those cases.
=> Basic processing of annotation events that contain mentions

lms/migrations/versions/0d265909ff85_create_the_notification_table.py, lms/models/__init__.py, lms/models/notification.py
Allows us both to report on the number of notifications sent and to ensure that a user doesn't receive multiple notifications for the same event.
This table is very similar its counterpart in H, with the following differences:
- annotation ID is just an opaque string, not a foreign key
- We store a reference to the "sender" which in H is implied to be the creator of the annotation.
- We include a FK to the relevant assignment
Model and migration on the same PR as this is not yet used.
Testing on: https://github.com/hypothesis/lms/pull/7060
=> New model and migration for Notifications

lms/routes.py, lms/services/annotation_activity_email.py, lms/tasks/annotations.py, lms/templates/admin/email.html.jinja2, lms/templates/email/mention/body.html.jinja2, lms/views/admin/email.py, tests/unit/lms/services/annotation_activity_email_test.py, tests/unit/lms/tasks/annotations_test.py
Include the text of the annotation on the email template for mentions.
This PR also fixes tab navigation via the URL
- Go to http://localhost:8001/admin/email/mentions
- The sample annotation text is displayed at the bottom.
=> Include the annotation text in the mention email body

lms/services/annotation_activity_email.py, lms/templates/email/email_layout.html.jinja2, lms/templates/email/instructor_email_digest/body.html.jinja2, lms/templates/email/mention/body.html.jinja2, lms/views/admin/email.py, tests/unit/lms/services/annotation_activity_email_test.py
Closes #7064 
Make mentions email look similar to the one sent by `h`, which is in turn based in the email digest here.
In order to achieve this, this PR extracts a common jinja layout from which both mentions and email digest templates extend.
Then every template just defines the part that is different via a content block.
The layout expects only two parameters, which the mentions email does not yet provide, `preferences_url` and `unsubscribe_url`, but adding those is not addressed here.
This PR also makes the next changes to the mention template params:
* Removes `mentioned_user`, as this information is part of the annotation text already.
* Adds `annotation_quote`, so that the pseudo annotation card looks closer to how it looks in the sidebar. As opposed to `h`, we do not display the …
=> Style mentions email template

lms/services/annotation_activity_email.py, lms/tasks/annotations.py, tests/factories/__init__.py, tests/factories/notification.py, tests/unit/lms/services/annotation_activity_email_test.py, tests/unit/lms/tasks/annotations_test.py
Check the following conditions:
- Never send more than one email per user per annotation
- Never send more that 100 emails for the same annotation
This is based on the same solution over in H
https://github.com/hypothesis/h/blob/main/h/services/notification.py#L20
- Checkout this branch on the H side https://github.com/hypothesis/h/pull/9419
- Edit an annotation you have created before with mentions https://hypothesis.instructure.com/courses/125/assignments/873
- Check the logs in LMS:
```- 
Skipping mention from 'DISPLAY NAME TEACHER' to 'Hypothesis 101 Student' in assignment 'localhost (make devdata) HTML Assignment' because user already notified    
```
=> Check whether or not we should send emails for mentions

tests/unit/lms/services/annotation_activity_email_test.py
This was missed as the new parameter was added in another branch and the original change was not rebased.
=> Fix mentions tests missing parameter

lms/services/annotation_activity_email.py, lms/tasks/annotations.py, lms/views/admin/email.py, tests/unit/lms/services/annotation_activity_email_test.py, tests/unit/lms/tasks/annotations_test.py
Depends on https://github.com/hypothesis/h/pull/9428
Part of https://github.com/orgs/hypothesis/projects/153/views/1?pane=issue&itemId=103523869
Forward the annotation quote from the mention event to the template.
=> Pass annotation quote from mention event to mention email template

lms/services/organization_usage_report.py, tests/unit/lms/services/organization_usage_report_test.py
Use the explicit role information instead of relying on whether the users
has an email address or not.
We have recently starting collecting student emails.
I don't have a good testing procedure here.
My plan is to create a report in production before merge and generate it again after merging.
=> Base usage reports "is teacher" on roles

lms/error_code.py, lms/static/scripts/frontend_apps/components/test/BasicLTILaunchApp-test.js, lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js, lms/static/scripts/frontend_apps/errors.ts, lms/static/scripts/frontend_apps/test/errors-test.js, lms/views/api/exceptions.py, tests/unit/lms/views/api/exceptions_test.py
Instead of relying on the implicit assumption that a error response without code and message means authorization error explicitly set a new error code for it.
On top of making this situation clearer, this also allows to avoid having to send a message when none is needed just to avoid implicitly marking the error as an authorization error.
Slack thread: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1743415186086139
- Force authorization errors with something like
```
truncate oauth2_token;
```
in `make sql`.
- Launch an assignment that interacts with the LMS API:
- You'll get the authorization dialog
=> Explicitly indicate authorization errors using an error code

package.json, yarn.lock
Part of https://github.com/hypothesis/client/issues/6866, this PR updates to latest frontend-shared to take advantage of the placeholder contrast improvements introduced in https://github.com/hypothesis/frontend-shared/pull/1940
Before:
After:
=> Update frontend-shared to increase input placeholder contrast

lms/models/application_instance.py, lms/templates/admin/application_instance/show.html.jinja2, lms/views/lti/basic_launch.py, tests/unit/lms/models/application_instance_test.py, tests/unit/lms/views/lti/basic_launch_test.py
Add an application instance feature flag to enable PDF image annotation. The only effect of this flag in the LMS app is to enable the `pdf_image_annotation` feature in the client.
**Testing:**
1. Go to http://localhost:5000/admin/features and make sure the `pdf_image_annotation` flag is *not* turned on for _everyone_ (first party only or specific users only is fine)
2. Go to http://localhost:8001/admin/instances/8/settings and change the "PDF image annotation" setting to "Enabled"
3. Go to a PDF assignment using this application instance such as https://hypothesis.instructure.com/courses/125/assignments/874 and verify that the client sidebar shows the extra controls that are part of the PDF image annotation feature
=> Add application instance feature flag for PDF image annotation

lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx, lms/static/scripts/frontend_apps/components/dashboard/GradeIndicator.tsx, lms/static/scripts/frontend_apps/components/dashboard/GradeStatusChip.tsx, lms/static/scripts/frontend_apps/components/dashboard/StudentStatusBadge.tsx, package.json, tailwind.config.js, yarn.lock
Replace locally-defined grade-specific shades of green, yellow and red with the ones from frontend 
-shared that were introduced in https://github.com/hypothesis/frontend-shared/pull/1944
There should be no visual differences:
=> Use shades of green, yellow and red from frontend-shared

Dockerfile
Git is required by get_version to come up with the version number based on the current commit.
=> Install git on the docker image

lms/migrations/versions/833f6b0237d8_new_lmsuser_name_columns.py, lms/models/lms_user.py, lms/services/lti_names_roles.py, lms/services/roster.py, lms/services/user.py, tests/unit/lms/services/user_test.py
We already combine these in "display_name" but
storing them separately make it easier to for example sort names by last name.
- Truncate your users table, in `make sql`
`truncate lms_user cascade`
- Launch a LTI1.1 assignment: https://hypothesis.instructure.com/courses/125/assignments/873
- Query the user:
```
postgres=# select display_name, given_name, family_name, name from lms_user;
display_name     |   given_name   | family_name |          name          
----------------------+----------------+-------------+------------------------
DISPLAY NAME TEACHER | Hypothesis 101 | Teacher     | Hypothesis 101 Teacher
(1 row)
```
- Truncate the table again
- Launch a 1.3 assignment https://hypothesis.instructure.com/courses/319/assignments/3308
- Query the user, is should have the same …
=> Store different LTI name fields separately in the DB

package.json, yarn.lock
Update `chai` to latest version in order to remove a few circular dependency warnings while running frontend tests.
See https://github.com/hypothesis/lms/pull/7105#issuecomment-2830737343
Console output after this change:
Console output before this change:
=> Update to latest chai

lms/models/lms_user.py, lms/models/lti_params.py, lms/services/roster.py, lms/services/user.py
For: 
- https://github.com/hypothesis/product-backlog/issues/1655
Not all LMSes send the middle name in the LTI params, but when they do, we should store it in the database.
Migration over https://github.com/hypothesis/lms/pull/7104
- Login into BB as `blackboardteacher`
- Launch https://aunltd-test.blackboard.com/webapps/blackboard/content/contentWrapper.jsp?content_id=_2483_1&displayName=LTI+1.3%2C+blackboard+file&course_id=_19_1&navItem=content&href=%2Fwebapps%2Fblackboard%2Fexecute%2Fblti%2FlaunchPlacement%3Fblti_placement_id%3D_148_1%26content_id%3D_2483_1%26course_id%3D_19_1
- Check the DB for middle_name in lms_user
```select * from lms_user where middle_name is not null;```
=> Store middle name when present in LTI params

lms/services/auto_grading.py, tests/unit/lms/services/auto_grading_test.py
For:
- https://github.com/hypothesis/support/issues/190
---
2 vs 3 decimal places seems to be limit to trigger rounding on the LMS side so for example for an assignment with maxScore 3, when sending the grade scaled between 0 and 1
0.33 becomes 0.99
but 0.333 becomes 1.00
- Launch https://hypothesis.instructure.com/courses/319/assignments/3308
- In make shell, try sending different grades with:
```
from datetime import datetime
from lms.services.lti_grading.factory import service_factory
ai = db.query(models.ApplicationInstance).order_by(models.ApplicationInstance.updated.desc()).first()
svc = service_factory(None, request, ai)
student = db.query(models.LMSUser).filter_by(display_name="Hypothesis 101 Student").one()
assignment = db.query(models.Assignment).order_by(models.Assignment.update …
```
=> Send three decimal places for auto grading scores

lms/static/scripts/frontend_apps/components/dashboard/GradeStatusChip.tsx, lms/static/scripts/frontend_apps/components/dashboard/test/GradeStatusChip-test.js
For:
- https://github.com/hypothesis/support/issues/190
After the BE started returning grades with more precession we now need to round them explicitly to avoid displaying too many decimal places in the dashboard.
See: https://hypothes-is.slack.com/archives/C2C2U40LW/p1745873532220369
=> Round grades to 2 decimal places in the dashboard

lms/models/application_instance.py, tests/unit/lms/views/lti/basic_launch_test.py
Enable the PDF image annotation feature by default for all LMS users.
=> Enable image annotations by default

lms/services/lti_names_roles.py, tests/unit/lms/services/lti_names_roles_test.py
Some LMSes (blackboard) include the rlid in the pagination link provided.
We have to only add the rlid query parameter if it's not already in the URL otherwise we end up duplicating it.
Noticed this while looking at:
https://hypothesis.sentry.io/issues/6261383283/?environment=prod&project=259908&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&stream_index=3
Note the error message there:
```
:"Unable to parse provided PkId string [_3034743_1,_3034743_1].
```
and the duplicate ID on that list, which shouldn't be a list at all, just one value.
=> Fix duplicate rlid parameter in LTI Names and Roles Service

lms/models/application_instance.py, lms/product/d2l/_plugin/course_copy.py, lms/product/d2l/_plugin/grouping.py, lms/product/d2l/_plugin/misc.py, lms/product/plugin/misc.py, lms/resources/_js_config/__init__.py, lms/static/scripts/frontend_apps/components/FilePickerApp.tsx, lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js, lms/static/scripts/frontend_apps/config.ts, lms/templates/admin/application_instance/show.html.jinja2, lms/views/lti/deep_linking.py, tests/functional/views/lti/deep_linking_test.py, tests/unit/lms/models/application_instance_test.py, tests/unit/lms/product/d2l/_plugin/misc_test.py, tests/unit/lms/product/plugin/misc_test.py, tests/unit/lms/views/lti/deep_linking_test.py
For:
- https://github.com/hypothesis/product-backlog/issues/1664
This PR adds the minimum UI  to able to further test this in production. 
- Log in a teacher in https://aunltd.brightspacedemo.com/d2l/le/content/6782/Home
- Make sure you can access https://localhost:48001/ in your browser, that you trust the certificate.
- Click "Existing activities" and "Hypothesis link (localhost)"
- You won't see any new controls
- Enable the new FF in http://localhost:8001/admin/instances/106/ 
- Create an assignment again, mark  the assignment as gradable and add max points.
- Launch the new assignment, the grading bar should show up and use the right amount of pointes (eg: `Grade (Out of 33)`)
- Test again, create a new assignment but left the field blank, the resulting assignment won't be gradable.
=> Prompt for max points while creating assignment

lms/product/d2l/_plugin/misc.py, lms/product/moodle/_plugin/course_copy.py, lms/product/moodle/_plugin/grouping.py, lms/product/moodle/_plugin/misc.py, lms/product/plugin/misc.py, tests/unit/lms/product/moodle/_plugin/misc_test.py
For:
- https://github.com/hypothesis/product-backlog/issues/1669
This extends #7145 to Moodle
- Log in a teacher (I'm using `moodleteacher`) in  https://hypothesisuniversity.moodlecloud.com/course/view.php?id=11
- Make sure you can access https://localhost:48001/ in your browser, that you trust the certificate.
- Toggle edit mode on the top right corner.
- Scroll to the bottom, click the `+` symbol -> `Activity or resources` -> H - localhost LTI1.3
- Select content to launch Hypothesis, pick some content
- You won't see any new controls
- Enable the new FF in http://localhost:8001/admin/instances/109/ 
- Create an assignment again, mark  the assignment as gradable and add max points.
- The UI on Moodle, under "Grade" will have the right value.
- Launch the new assignment, the grading bar …
=> Extend the prompt for grade max feature to Moodle

lms/static/scripts/frontend_apps/components/FilePickerApp.tsx, lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js, package.json, yarn.lock
For:
- https://github.com/hypothesis/product-backlog/issues/1664
This is how this look at the moment:
https://github.com/user-attachments/assets/24b218c2-c939-49c9-91ca-cf2b8f062029
(copied from https://github.com/hypothesis/lms/pull/7145)
- Log in a teacher in https://aunltd.brightspacedemo.com/d2l/le/content/6782/Home
- Make sure you can access https://localhost:48001/ in your browser, that you trust the certificate.
- Enable the new FF in http://localhost:8001/admin/instances/106/ (Prompt for gradable on creation)
- Click "Existing activities" and "Hypothesis link (localhost)"
- Select any content to see the new control
=> New info button to display more information about the max points feature

lms/static/scripts/frontend_apps/services/client-rpc.ts, lms/static/scripts/frontend_apps/services/test/client-rpc-test.js, lms/static/scripts/frontend_apps/utils/test/unsaved-changes-test.js, lms/static/scripts/frontend_apps/utils/unsaved-changes.ts
This is the LMS side of a workaround for a restriction in desktop Safari that `beforeunload` alerts do not work in cross-origin iframes. When the user has unsaved changes in the client, it sends a notification to the LMS frame which installs a `beforeunload` handler.
See https://github.com/hypothesis/client/pull/7206 for the client changes and https://github.com/hypothesis/support/issues/59#issuecomment-3068704178 for issue context.
**Testing:**
Either test in Safari or comment out calls to the `useUnsavedChanges` hook in the Hypothesis client and test in Chrome or Firefox.
1. Launch a Hypothesis assignment in a new tab. Close the tab. There should be no confirmation dialog.
2. Launch a Hypothesis assignment in a new tab. Create an annotation and enter some tags or text. Try to close the …
=> Prevent closing tab when Hypothesis client has unsaved changes

package.json, yarn.lock
Reverts hypothesis/lms#7241
With latest tailwind version we are seeing a weird `CssSyntaxError: tailwindcss: /tmp/frontend-build/lms/static/styles/frontend_apps.css:3:8: Cannot apply unknown utility class `bg-white`` error while building the docker image, so I'm reverting it
=> Revert "Bump the tailwind group with 2 updates"
