hypothesis/lms

- tests/lti/views/test_application_instance.py
* Remove test for functionality we have decided against
> Remove Out of Date Tests

- lti/templates/application_instances/new_application_instance.html.jinja2
- lti/templates/content_item_selection/new_content_item_selection.html.jinja2
- tests/lti/views/test_application_instance.py
On forms for new application and new content, add http to any URL that doesn't already have the protocol.
> Kr http on url

- .gitignore
- README.markdown
- lti/templates/application_instances/new_application_instance.html.jinja2
- lti/templates/content_item_selection/new_content_item_selection.html.jinja2
- lti/util/lti_launch.py
- lti/views/content_item_selection.py
* Add support for using google picker to select previously public google docs and spreadsheets
> Initial Picker Support 

- lms/static/styles/lms.css
- lms/templates/base.html.jinja2
- lms/templates/lti_launches/unauthorized.html.jinja2
> Add ui for student authorization

- tests/lms/views/test_authentication.py
- tests/lms/views/test_module_item_configuration.py
More unit tests to improve coverage.
> Kr more tests

- README.markdown
* Improves google setup instructions
* Add dev install instructions
> Update Readme 

- env.sh
- lms/views/lti_launches.py
- lms/views/module_item_configurations.py
- tox.ini
* Use VIA_URL environment variable instead of hardcoded url
> Remove hardcoded via url

- README.markdown
- conf/development.ini
- lms/config/__init__.py
- lms/util/authenticate.py
- lms/util/lti_launch.py
- lms/views/content_item_selection.py
- lms/views/lti_launches.py
- lms/views/module_item_configurations.py
- tests/lms/conftest.py
- tests/lms/test_security.py
- tests/lms/views/test_authentication.py
Use `registry.settings` instead of `env_setting` in app
> Use registry settings

- Jenkinsfile
Temporarily removing these so we can test the rest of what Jenkins does first. Will be putting them back later.
> Remove QA and prod deploys from Jenkinsfile

- lms/config/resources.py
- lms/security.py
- lms/util/get_password_hash.py
- tests/lms/test_routes.py
- tests/lms/test_security.py
By leaving out off an s, I accidentally whited listed the particular username I had used for testing, and not the entire report_viewers group.
> Whitelist report_viewers group

- lms/migrations/versions/3802f4d2ec5c_add_lti_launches_table.py
- lms/models/lti_launches.py
- lms/templates/reports/application_report.html.jinja2
- lms/views/lti_launches.py
- lms/views/reports.py
Record lti launchs. Add table to /reports page.
> Kr track lti launches

- Dockerfile
Now when we merge things into master the Jenkins should automatically build the javascript for us.
> Add the javascript build to the Docker file

- lms/templates/base.html.jinja2
- lms/templates/content_item_selection/new_content_item_selection.html.jinja2
* Updates the base template title to read 'Hypothesis'
* Updates the user facing note to read 'Note: sharing a file in this way creates a secret link'
> Update User Facing Text

- README.markdown
Add screenshots to illustrate various steps in developer console.
> Add screenshots to google setup instructions

- lms/static/styles/lms.css
Remove repetitive font rules from CSS and define a default font on the root (html) element instead.
Fixes https://github.com/hypothesis/lms/issues/139
> Set a bigger default font size on the html element.

- README.markdown
- lms/config/__init__.py
- tests/lms/config/__init___test.py
- tests/lms/conftest.py
<del>Depends on <https://github.com/hypothesis/lms/pull/150></del>
> Add required config settings for calling h API

- lms/static/styles/lms.css
- lms/templates/base.html.jinja2
- lms/templates/error.html.jinja2
- lms/views/error.py
- tests/lms/views/error_test.py
> Style error pages so they look better.

- lms/util/jwt.py
- lms/views/lti_launches.py
- tests/lms/views/test_lti_launches.py
Fixeshttps://github.com/hypothesis/lms/issues/137
To test, follow instructions here: https://github.com/hypothesis/lms/pull/166#issue-206755572
> Show user the error page when roles param is missing and lti launch fails.

- lms/util/lti_launch.py
- lms/views/content_item_selection.py
- lms/views/lti_launches.py
Rather than having it unnecessarily be a decorator factory.
> Make @lti_launch a simple decorator

- lms/exceptions.py
- lms/views/content_item_selection.py
- lms/views/error.py
- tests/lms/views/error_test.py
- tests/lms/views/test_content_item_selection.py
Fixes https://github.com/hypothesis/lms/issues/136
Fixes https://github.com/hypothesis/lms/issues/135
Fixes https://github.com/hypothesis/lms/issues/144
Fixes https://github.com/hypothesis/lms/issues/143
> Show error page when required LTI content item selection params are missing.

- lms/migrations/versions/efcf8671f4d3_add_the_groups_table.py
Depends on <https://github.com/hypothesis/lms/pull/189>.
See also:
* The corresponding models code to this DB migration: https://github.com/hypothesis/lms/pull/191
> [Create groups 2/n]: Add a DB migration to add the course_groups table

- lms/models/__init__.py
- lms/models/course_groups.py
- tests/lms/models/course_groups_test.py
Add the models class and tests for a new DB table for keeping a record of groups created in h.
Depends on this DB migration: <https://github.com/hypothesis/lms/pull/190>
> [Create groups 3/n]: Add models.CourseGroup

- tests/lms/config/__init___test.py
- tests/lms/conftest.py
- tests/lms/test_routes.py
- tests/lms/views/decorators/test_h_api.py
- tests/lms/views/status_test.py
- tox.ini
Fixes https://github.com/hypothesis/product-backlog/issues/749
> Change to using the new unittest.mock lib instead of the old mock

- tests/lms/views/decorators/test_h_api.py
Move some test fixtures into a location where all test classes in the module can use them. New test classes are going to be added to this module soon that will use these.
> Share some test fixtures

- tests/lms/views/decorators/test_h_api.py
Depends on <https://github.com/hypothesis/lms/pull/235>
> Make fixtures more careful

- scripts/gulp/manifest.js
See https://github.com/hypothesis/client/pull/747
> Fix Buffer constructor warning

- README.markdown
Removing references to `https` as per request from @seanh.
> Change localhost URLs from https to http in documentation

- lms/config/resources.py
- tests/lms/config/resources_test.py
Add the list of groups that should be shown in the client to the config object that we deliver to the client.
There's little point in merging this yet, until the corresponding client PR is done to test it against. Merging it wouldn't cause any harm though.
This is a fix for https://github.com/hypothesis/lms/issues/301.
> Add groups to client config object

- conf/development.ini
> Remove pyramid_debugtoolbar

- yarn.lock
See https://github.com/hypothesis/client/pull/817
> Fix build under Node 11

- lms/routes.py
Fix the content item selection flow in Canvas, which was broken by a recent refactoring.
> Fix for the content item selection flow

- tests/lms/views/error_test.py
Gets errors.py coverage up to 100%
> Fix errors tests

- lms/util/authorize_lms.py
application_instance cannot be None at this point. There is a previous if-raise statement exactly the same as this one a few lines above.
> Delete a pointless statement

- lms/views/content_item_selection.py
- lms/views/helpers/__init__.py
- lms/views/helpers/_canvas_files.py
- tests/lms/views/helpers/_canvas_files_test.py
- tests/lms/views/test_content_item_selection.py
Deduplicate a couple of helper functions and also move them into a helpers module, add tests, and fix some bugs.
Depends on <https://github.com/hypothesis/lms/pull/482/> and should rebase cleanly once <https://github.com/hypothesis/lms/pull/482/files> is merged.
> Deduplicate a couple of helper functions

- Jenkinsfile
- Makefile
Also means that frontend tests and linting are now being run on Jenkins!
> Use `make` on Jenkins

- lms/validation/_exceptions.py
Explains the `messages` format.
> Improve ValidationError docstring

- lms/templates/application_instances/create_application_instance.html.jinja2
- lms/templates/application_instances/new_application_instance.html.jinja2
> Add link to install docs on welcome page

- lms/models/__init__.py
- lms/models/application_instance.py
- lms/models/oauth2_token.py
- tests/lms/models/oauth2_token_test.py
This reverts commit 9198a4442bdc19da13d1c8a930c98f2ecd28a801.
> Revert "Remove all references to OAuth2Token / oauth2_token"

- lms/services/_helpers/canvas_api.py
- lms/services/canvas_api.py
- lms/views/api/canvas/files.py
- tests/lms/services/_helpers/canvas_api_test.py
- tests/lms/services/canvas_api_test.py
- tests/lms/views/api/canvas/files_test.py
There's no error handling etc yet, but this sends an API request to Canvas and returns the response.
> Replace the stub list files API with a real one

- lms/migrations/versions/db0e29272784_make_module_item_configurations_columns_.py
- lms/models/module_item_configuration.py
These columns should never be null.
> Make module_item_configurations columns not nullable

- .prospector.base.yaml
- lms/models/oauth2_token.py
- lms/util/jwt.py
I'm not sure how this happened but `make lint` was failing on master.
> Fix `make lint`

- lms/resources/_lti_launch.py
- lms/views/basic_lti_launch.py
- lms/views/content_item_selection.py
- tests/lms/resources/_lti_launch_test.py
- tests/lms/views/basic_lti_launch_test.py
- tests/lms/views/content_item_selection_test.py
Depends on https://github.com/hypothesis/lms/pull/697
> Deduplicate lms_url logic

- lms/static/scripts/bootstrap.js
- package.json
- yarn.lock
The latest release fixes a bug I reported upstream.
> Upgrade Preact and remove workaround for `act` bug

- tests/lms/services/canvas_api_test.py
This test class was getting too long, and this will make adding more tests easier.
> Break up TestCanvasAPIClient

- lms/services/_helpers/canvas_api.py
- tests/lms/services/_helpers/canvas_api_test.py
Just creates a request object. Code for sending it will come later
> Add refresh_token_request() helper

- lms/services/canvas_api.py
- tests/lms/services/canvas_api_test.py
Depends on https://github.com/hypothesis/lms/pull/748 and https://github.com/hypothesis/lms/pull/751 for CI to pass
> Add get_refreshed_token()

- lms/services/canvas_api.py
- tests/lms/services/canvas_api_test.py
Depends on https://github.com/hypothesis/lms/pull/752 for CI to pass.
> Automatically refresh and retry if list_files or public_url fails

- lms/static/scripts/frontend_apps/components/FilePickerApp.js
- lms/static/styles/components/_FilePickerApp.scss
> Even out file picker form's vertical rhythm

- lms/views/api/canvas/authorize.py
- lms/views/basic_lti_launch.py
- lms/views/content_item_selection.py
This is turned on for everyone now.
> Remove the new_oauth feature flag

- tests/lms/test_routes.py
Tests will fail because it depends on other PRs
> Fix a broken test

- lms/views/basic_lti_launch.py
- tests/lms/views/basic_lti_launch_test.py
This flag is now enabled for everyone in production.
Fixes #881
> Remove "speedgrader" feature flag

- lms/templates/application_instances/create_application_instance.html.jinja2
- lms/templates/application_instances/new_application_instance.html.jinja2
Fixes https://github.com/hypothesis/lms/issues/936.
> Update link to LMS documentation

- lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
- lms/static/scripts/frontend_apps/components/LMSFilePicker.js
Previously, the setState usage made it look like the states of each of the keys in the state object were being merged when in fact they were being overridden. This refactors the existing implementation to make it more clear.
> Make set state usage more clear

- lms/migrations/versions/edab0e4610e0_add_the_lis_result_sourcedid_table.py
As it says, already discussed. Part of https://github.com/hypothesis/lms/issues/946
> Add migration for `lis_result_sourcedid` table

- lms/models/__init__.py
- lms/models/lis_result_sourcedid.py
- tests/lms/models/lis_result_sourcedid_test.py
Depends on #964 
Part of https://github.com/hypothesis/lms/issues/946
> Add `LISResultSourcedId` model and tests

- package.json
- yarn.lock
This should fix a cause of flakey tests [1]
[1] https://github.com/preactjs/preact/issues/1794
> Upgrade Preact to 10.0.0-rc.3

- lms/static/scripts/frontend_apps/utils/grader-service.js
- lms/static/scripts/frontend_apps/utils/test/grader-service-test.js
Simple util to submit a grade. Also, stubs out the fetch endpoint for later.
> Add grader endpoint for submitting a grade

- lms/app.py
- lms/sentry.py
- requirements.in
- requirements.txt
Automatically retry all IntegrityErrors. See individual commit messages
> Retry IntegrityErrors

- lms/migrations/versions/a930adadac74_add_group_info_table.py
Part of this issue: https://github.com/hypothesis/lms/issues/918
This PR adds a database migration script that adds the new `group_info` table to the DB. This `group_info` table corresponds to the `GroupInfo` model in https://github.com/hypothesis/lms/pull/1088.
When you add Python code that depends on a new DB table, new DB column, or change to an existing DB column or constraint etc, that new Python code will crash if run against a DB that doesn't have a matching schema. For example the new `GroupInfo` model in https://github.com/hypothesis/lms/pull/1088 will cause the app to crash on startup on QA or production because the QA and production DBs don't have the `group_info` table that the model requires.
So before merging a PR like https://github.com/hypothesis/lms/pull/1088 it's …
> DB migration to add group_info table

- .coveragerc
- lms/views/basic_lti_launch.py
- tests/unit/lms/views/api/lti_test.py
- tests/unit/lms/views/basic_lti_launch_test.py
This feature flag is turned on for everyone in QA and prod now so it's no longer needed
> Remove blackboard_grading feature flag

- tests/functional/lti_certification/test_lti_certification_1_1.py
> Fixing a bad merge

- lms/validation/__init__.py
- lms/validation/_exceptions.py
- lms/validation/_lti_launch_params.py
- tests/functional/lti_certification/test_lti_certification_1_1.py
- tests/unit/lms/validation/_exceptions_test.py
- tests/unit/lms/validation/_lti_launch_params_test.py
For ticket: https://github.com/hypothesis/lms/issues/1111
* Introduced a new exception LTIToolRedirect
* We raise this in the validator when things have gone wrong that
should be reported to the user in the original tool
* Added tests to cover
> LTI Certification 1.1 compliance - Part 1.1

- lms/views/decorators/lis_result_sourcedid.py
- lms/views/helpers/frontend_app.py
> Don't show our grading UI in Canvas

- lms/resources/_lti_launch.py
- lms/views/basic_lti_launch.py
- tests/unit/lms/resources/_lti_launch_test.py
This is a hacky fix to get us going for now
> Adding the schema to the resource instead of the view

- tests/bdd/features/dummy.feature
- tests/bdd/features/lti_certification/section_1_invalid_launch_requests.feature
- tests/bdd/features/lti_certification/section_2_valid_launch_requests.feature
- tests/bdd/features/lti_certification/section_3_types_of_roles.feature
- tests/bdd/features/lti_certification/section_4_levels_of_user_information.feature
- tests/bdd/features/lti_certification/section_6_outcomes_1.0_service.feature
* This includes tests 1.x - 4.x + 6.x
* All were taken directly from the HTML of the certification test
> Part 2: Adding the scenario skeletons from the LTI cert 1.1 test

- tests/bdd/features/lti_certification/section_1_invalid_launch_requests.feature
- tests/bdd/steps/_compiled_feature_steps.py
- tests/bdd/steps/feature_steps/http.feature
- tests/bdd/steps/feature_steps/lti.feature
- tests/bdd/steps/the_response.py
This part of a series of changes for #1220, so you may see odd things which are in place for PRs later in the sequence.
This should be merged after #1235.
> Part 5: Completing the tests for LTI 1.1 - Section 1

- tests/bdd/features/lti_certification/section_3_types_of_roles.feature
- tests/bdd/fixtures/lti_certification_1_1/section_3/Bob.ini
- tests/bdd/fixtures/lti_certification_1_1/section_3/Jane.ini
- tests/bdd/steps/feature_steps/fixture.feature
This part of a series of changes for #1220, so you may see odd things which are in place for PRs later in the sequence.
This should be merged after #1237.
> Part 7: Completing the tests for LTI 1.1 - Section 3

- lms/views/basic_lti_launch.py
- tests/unit/lms/views/basic_lti_launch_test.py
Currently this is trying to fix the issue where grading doesn't launch, but it looks like there might be others too.
This is for: https://github.com/hypothesis/lms/issues/1128
> Fix no grading on teacher's first launch of an assignment

- lms/validation/_lti_launch_params.py
Spotted this method is a bit mysterious now my head isn't in that space. Better to document it up.
> Added a doc string to explain LTI redirects

- Jenkinsfile
- tox.ini
Is this all that is required? This is for https://github.com/hypothesis/lms/issues/1220
> Trying to make the Jenkins build fail when the gherkin tests fail

- lms/views/basic_lti_launch.py
- tests/bdd/features/lti_certification/section_1_invalid_launch_requests.feature
- tests/bdd/features/lti_certification/section_2_valid_launch_requests.feature
- tests/bdd/features/lti_certification/section_3_types_of_roles.feature
- tests/bdd/features/lti_certification/section_4_levels_of_user_information.feature
- tests/bdd/steps/__init__.py
- tests/bdd/steps/feature_steps/lms.feature
- tests/bdd/steps/h_api.py
- tests/unit/lms/views/basic_lti_launch_test.py
- tox.ini
* This caused more errors to be discovered before
* This required some debugging information in the output
* Because there's no difference between student and teacher without grading
This is for: https://github.com/hypothesis/lms/issues/1220
> Changing the gherkin tests to run on configured launches

- lms/static/scripts/frontend_apps/components/SubmitGradeForm.js
- lms/static/scripts/frontend_apps/components/test/SubmitGradeForm-test.js
Fixes https://github.com/hypothesis/lms/issues/1166
**Update:** 
- Testing fixed
- Also now selects the input field in addition to setting focus on it.
> Auto focus input field on student change

- lms/config/__init__.py
- lms/views/helpers/_via.py
- tests/conftest.py
- tests/unit/lms/config/__init___test.py
- tests/unit/lms/views/helpers/_via_test.py
This is part of hypothesis/proxy-server#19 in order to test via3 in lms.
> Add use_via3_url

- lms/services/lti_outcomes.py
- requirements.in
- requirements.txt
- tests/unit/lms/services/lti_outcomes_test.py
From https://github.com/hypothesis/lms/pull/1284
> LTI Outcomes: Python dicts for XML generation and separate Canvas specific stuff

- lms/services/lti_outcomes.py
- tests/unit/lms/services/lti_outcomes_test.py
Child of: https://github.com/hypothesis/lms/pull/1284
This helps in a few ways:
* Some general de-maddening of the tests
* There was some horribly grouped stuff that was test specific
* When we fail on a key lookup we now know which key was missing
* Generally a bit easier on the eyes than XPATH
> LTI Outcomes: Use python dicts to navigate XML

- tests/unit/lms/services/lti_outcomes_test.py
Should be merged after: https://github.com/hypothesis/lms/pull/1288
> LTI Outcomes: Move fixtures to the end of the test file

- lms/services/lti_outcomes.py
* Getting comments under the PEP-8 79 char limit
* Removing some comments which unhelpfully replicate details from other packages
Should be merged after https://github.com/hypothesis/lms/pull/1288
> LTI Outcomes: Fixing up the docstrings and comments

- README.markdown
- conf/development.ini
This is now setup in Superdev for convenience
This is for: https://github.com/hypothesis/via3/issues/35
> Set Via 3 as the default for development

- requirements.txt
- tests/unit/conftest.py
- tests/unit/lms/validation/authentication/_oauth_test.py
This reverts commit 47e33793e039217f3a005901a8363a04f1bff8aa.
This reverts commit e8b373895bc12d5e8721e8c76640b46433d95e9b.
> Revert "Bump webargs from 5.5.2 to 5.5.3"

- tests/bdd/steps/lms_db.py
- tests/unit/lms/resources/_js_config_test.py
- tests/unit/lms/resources/lti_launch_test.py
- tests/unit/lms/services/lti_outcomes_test.py
- tests/unit/lms/views/api/canvas/authorize_test.py
- tests/unit/lms/views/api/canvas/files_test.py
- tests/unit/lms/views/api/lti_test.py
This is due to a gap in our linting at present
> Remove un-used test imports

- tests/unit/lms/resources/_js_config_test.py
Future tests are going to need this.
> Centralize JSConfig 2/n: Add js_config fixture

- lms/views/helpers/_via.py
- tests/unit/lms/views/helpers/_via_test.py
- tox.ini
* Updated the tests so I could understand them
* Split up different tests into different parts
* Reworked the code into a simpler form
> Change Via3 URL generation to use URL param

- lms/values.py
- tests/unit/lms/values_test.py
Fixes https://github.com/hypothesis/lms/issues/1431
> Add is_learner()

- lms/validation/__init__.py
- lms/validation/_canvas.py
Should probably just go through the codebase and remove all of these...
> Remove some unnecessary __all__'s

- tests/unit/lms/services/h_api_test.py
Tidy up/simplify/make-consistent this test file, to make it easier to edit when we edit `h_api.py`
> Refactor h_api_test.py

- lms/migrations/versions/37710e6bcb66_add_group_info_info_column.py
This is the DB migration for https://github.com/hypothesis/lms/pull/1703
> Add DB migration for GroupInfo.info column

- lms/db/__init__.py
- lms/resources/_js_config.py
- lms/services/lti_h.py
- lms/views/api/canvas/sync.py
- lms/views/basic_lti_launch.py
- lms/views/content_item_selection.py
- tests/unit/lms/db/__init___test.py
- tests/unit/lms/resources/_js_config_test.py
- tests/unit/lms/services/grading_info_test.py
- tests/unit/lms/services/group_info_test.py
- tests/unit/lms/services/lti_h_test.py
- tests/unit/lms/views/api/canvas/sync_test.py
Fixes https://github.com/hypothesis/lms/issues/1409, although I still want to add a "type" field to distinguish course from section groups
> Make GroupInfoService work with section groups

- lms/services/canvas_api.py
- tests/unit/lms/services/canvas_api_test.py
Add support for following "rel=next" links provided by Canvas for pagination.
This will automatically apply to all end-points which use a `many=True` schema:
* This will add the `per_page=` query param to a large value
* Follow next links up to a pre-defined limit
* If a query fails for authentication reasons, it will be started from scratch
This only currently applies to `list_files` and `course_sections` as the other sections calls do not support pagination (I think).
This also enables re-use of the HTTP session which should speed up repeated calls. Based on local testing I had rough performance of:
* 600ms per call for calls without the session
* 400ms up front, then 200ms per call with a session
This will effect paginated calls, but also any situations where we attempt to retry and …
> Add pagination support to the Canvas API

- lms/models/application_instance.py
- lms/resources/_js_config.py
- lms/resources/lti_launch.py
- lms/services/application_instance_getter.py
- lms/views/api/canvas/authorize.py
- lms/views/application_instances.py
- tests/unit/lms/models/test_application_instance.py
- tests/unit/lms/resources/_js_config_test.py
- tests/unit/lms/resources/lti_launch_test.py
- tests/unit/lms/services/application_instance_getter_test.py
- tests/unit/lms/views/api/canvas/authorize_test.py
- tests/unit/lms/views/test_application_instance.py
- tests/unit/lms/views/test_reports.py
Revert https://github.com/hypothesis/lms/pull/1731 because it was accidentally merged before its DB migration.
> Revert PR #1731

- lms/migrations/versions/f0859cd029fe_add_application_instances_canvas_.py
This is the DB migration for https://github.com/hypothesis/lms/pull/1731
> DB migration to add ApplicationInstance.settings column

- lms/models/application_instance.py
- lms/resources/_js_config.py
- lms/resources/lti_launch.py
- lms/services/application_instance_getter.py
- lms/views/api/canvas/authorize.py
- lms/views/application_instances.py
- tests/unit/lms/models/application_instance_test.py
- tests/unit/lms/resources/_js_config_test.py
- tests/unit/lms/resources/lti_launch_test.py
- tests/unit/lms/services/application_instance_getter_test.py
- tests/unit/lms/views/api/canvas/authorize_test.py
- tests/unit/lms/views/test_application_instance.py
- tests/unit/lms/views/test_reports.py
This reverts commit 5adaea05851fe2f7f0749b58ce66833d52e62d4f.
> Revert "Revert PR #1731"

- lms/resources/_js_config.py
Fixes https://github.com/hypothesis/client/issues/2084
> Don't show leave-group buttons in the client

- lms/models/__init__.py
- lms/models/application_instance.py
- lms/models/application_settings.py
- lms/models/course.py
- lms/models/course_groups_exported_from_h.py
- lms/resources/lti_launch.py
- lms/services/__init__.py
- lms/services/application_instance_getter.py
- lms/services/course.py
- lms/views/api/canvas/authorize.py
- lms/views/basic_lti_launch.py
- lms/views/content_item_selection.py
- tests/unit/conftest.py
- tests/unit/lms/models/application_instance_test.py
- tests/unit/lms/models/application_settings_test.py
- tests/unit/lms/models/course_test.py
- tests/unit/lms/resources/lti_launch_test.py
- tests/unit/lms/services/application_instance_getter_test.py
- tests/unit/lms/services/course_test.py
- tests/unit/lms/views/api/canvas/authorize_test.py
- tests/unit/lms/views/basic_lti_launch_test.py
- tests/unit/lms/views/content_item_selection_test.py
Depends on https://github.com/hypothesis/lms/pull/1791
> Record course settings in db

- lms/services/course.py
- lms/views/api/canvas/authorize.py
- tests/factories/__init__.py
- tests/factories/course.py
- tests/unit/lms/services/course_test.py
- tests/unit/lms/views/api/canvas/authorize_test.py
* Add a method to check if any course in an instance has a particular setting
* Use the course setting check to see if any course has sections
> Retrieve sections scopes if enabled in any course

- lms/db/__init__.py
Automatically stamp the DB with the latest version on startup if it
isn't stamped already.
Fixes https://github.com/hypothesis/lms/issues/1751
Similar to what we already do in h:
https://github.com/hypothesis/h/blob/928fd87a4b2132716850733c99d8c016fda5356e/h/cli/commands/init.py#L33-L46
To test this:
1. Delete your DB:
$ make services args='down'
$ make services
2. Run `make dev` to recreate your DB:
$ make dev
3. Query your current DB version:
$ tox -qqe dev --run-command 'alembic -c conf/alembic.ini current'
4. Try to upgrade your DB to the latest version:
$ tox -qqe dev --run-command 'alembic -c conf/alembic.ini upgrade head'
On master (3) would print out nothing because the DB isn't stamped and
(4) would try to run all the DB migrations from the first one and crash.
On this branch (3) …
> Automate `alembic stamp`

- lms/templates/application_instances/new_application_instance.html.jinja2
Fixes https://github.com/hypothesis/lms/issues/1781.
> Update text on new_application_instance.html.jinja2

- lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
- Ignore return value of `reportSubmission` rather than returning it
from `useEffect`. The return value of `useEffect` should be an effect
cleanup function if provided.
- Add missing JSDoc comments, in particular clarify what `errorState`
is for
- Suppress a couple of TS errors where we know things TS doesn't
Some of the changes here conflict with https://github.com/hypothesis/lms/pull/1844. I will take care of updating that PR as it is on my plate to review.
> Fix typecheck errors in `BasicLtiLaunchApp`

- .github/workflows/continuous-integration.yml
> Fix GHA cache restore key

- conf/development.ini
- lms/services/application_instance_getter.py
- lms/views/application_instances.py
- tests/unit/lms/services/application_instance_getter_test.py
- tests/unit/lms/views/test_application_instance.py
Fixes https://github.com/hypothesis/lms/issues/1758
> Remove the section_groups feature flag

- lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
- lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
- Error state is not reset until after all requests have succeeded.
- The full page spinner no longer is rendered while an error is present. As a follow up, a smaller in-element spinner could be added to the dialog component
- Add missing test for auth window
----------
This is a follow up from this PR
https://github.com/hypothesis/lms/pull/1833
In short, I simply removed the spinner changes and just addressed the flickering.
Follow ups to this could be:
- how to show loading while the error is present?
- do we need to delay or throttle the onset of the spinner for very fast server errors?
fixes https://github.com/hypothesis/lms/issues/1826
> Fix flicker issue when successive errors occur

- lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
- lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
After completing OAuth authorization when launching an assignment, the
"Authorize" button should be disabled while the LMS frontend waits for
both content URL and group fetching to complete. Previously the button
was disabled while the API request to fetch the content URL was pending,
but not if the content URL had been fetched and group fetching was still
in progress.
This commit resolves that issue by adding conditional logic to the
`fetchGroups` helper to control whether it updates the `fetchCount`
state that tracks the number of API requests in flight that block
display of the content. This logic is conditional because fetching
groups does not block content display on the initial launch but it does
after authorization, to avoid a flicker (as explained in #1826) if
authorization fails …
> Disable "Authorize" button when re-fetching groups

- lms/sentry.py
This reverts commit 1a41a3ce7daebf7615e8540bf190da3b1640aec6.
> Disable Sentry's performance monitoring

- lms/resources/_js_config.py
- lms/static/scripts/frontend_apps/components/CanvasOAuth2RedirectErrorApp.js
- lms/static/scripts/frontend_apps/components/test/CanvasOAuth2RedirectErrorApp-test.js
- lms/static/scripts/frontend_apps/config.js
- lms/views/api/canvas/authorize.py
- tests/unit/lms/resources/_js_config_test.py
- tests/unit/lms/views/api/canvas/authorize_test.py
And authorize_url to auth_url.
This is for consistency with other parts of the JS config where the same URL appears as authUrl.
> Rename authorizeUrl to authUrl

- lms/static/scripts/frontend_apps/components/Dialog.js
- lms/static/scripts/frontend_apps/components/FileList.js
- lms/static/scripts/frontend_apps/components/LMSFilePicker.js
- lms/static/scripts/frontend_apps/components/test/FileList-test.js
- lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js
- lms/static/styles/components/_FileList.scss
> Show explanation if no files are found

- conf/development.ini
- lms/views/helpers/_via.py
- tests/unit/lms/views/helpers/_via_test.py
For: https://github.com/hypothesis/via3/issues/245
This removes the ability to switch on the "experimental rewriter" in Via 3, which is now gone.
> Remove the writer flag

- lms/static/scripts/frontend_apps/components/FileList.js
- lms/static/scripts/frontend_apps/components/LMSFilePicker.js
- lms/static/scripts/frontend_apps/components/Table.js
- lms/static/scripts/frontend_apps/components/test/FileList-test.js
- lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js
- lms/static/styles/components/_FileList.scss
- lms/static/styles/components/_Table.scss
Second iteration based on additional feedback from a Slack conversation:
https://app.slack.com/client/T03QZM0HN/C07NXBDNW/thread/C2BLQDKHA-1604440053.200400
In summary:
* Text has been simplified and condensed
* Text is centred on the table
* Spinner is shown on the table for at least 2s.
* A `Reload` button has been added to allow retry.
Spinner:
> Polish the warning message if no files are available in the course

- lms/services/__init__.py
- lms/services/exceptions.py
- lms/static/scripts/frontend_apps/components/BasicLtiLaunchApp.js
- lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
- lms/static/scripts/frontend_apps/utils/api.js
- lms/static/scripts/frontend_apps/utils/test/api-test.js
- lms/views/api/exceptions.py
- tests/unit/lms/services/exceptions_test.py
- tests/unit/lms/views/api/exceptions_test.py
There are some minor changes in the API's error responses too, see the test changes.
> Deduplicate API exception views

- conf/development.ini
- lms/config/__init__.py
- lms/views/helpers/_via.py
- tests/conftest.py
- tests/unit/lms/config/__init___test.py
- tests/unit/lms/views/helpers/_via_test.py
We can switch this in Via 3 if we want to.
For: https://github.com/hypothesis/via3/issues/244
> Removing the legacy Via path from LMS.

- tests/factories/__init__.py
- tests/factories/attributes.py
- tests/factories/grading_info.py
- tests/factories/lti_user.py
- tests/factories/module_item_configuration.py
Add a `ModuleItemConfiguration` test factory. Tests in a [follow-up PR](https://github.com/hypothesis/lms/pull/2266) will use it.
> Add ModuleItemConfiguration test factory

- lms/static/scripts/frontend_apps/index.js
Minor improvement, from my personal view. I believe it is easier to modify and clearer.
> Small stylistic change for better readability

- tests/unit/lms/services/canvas_api/client_test.py
This doesn't actually change any of the tests, it just splits the massive `TestCanvasAPIClient` class into separate classes, one for each `CanvasAPIClient` method that's tested.
This is going to make future commits that need to add more tests to this file much nicer.
It also has a few advantages even just for the existing tests:
* Smaller classes are easier to understand than big ones
* The scope of fixtures is reduced. Most of the tests don't actually use any of the fixtures defined in this file, and now that they're in separate, small test classes that clearly don't have any fixtures in the test class, that's easier to see. It makes it clear that the tests are as simple as they actually are
* Reducing the scope of fixtures also means that for test methods that _do_ use fixtures, those …
> Split up a large test class

- .github/stale.yml
- .github/workflows/stale.yml
See See https://github.com/hypothesis/h/pull/6457 and
https://hypothes-is.slack.com/archives/C4K6M7P5E/p1610967662111300.
> Replace the Stale app for closing inactive PRs with a GitHub Action

- lms/views/helpers/_via.py
- requirements/bddtests.txt
- requirements/dev.txt
- requirements/functests.txt
- requirements/lint.txt
- requirements/requirements.in
- requirements/requirements.txt
- requirements/tests.txt
Not ready until https://github.com/hypothesis/h-vialib/pull/8 is merged
> Use via classes from vialib

- lms/config/__init__.py
- lms/views/helpers/_via.py
- requirements/bddtests.txt
- requirements/dev.txt
- requirements/functests.txt
- requirements/lint.txt
- requirements/requirements.txt
- requirements/tests.txt
- tests/conftest.py
- tests/unit/lms/views/helpers/_via_test.py
- tox.ini
Need to update h-vialib version to https://github.com/hypothesis/h-vialib/pull/9/files
> Sign via3 urls

- package.json
- yarn.lock
Reverts hypothesis/lms#2464
Seem to break creation of assignments:
https://hypothes-is.slack.com/archives/C4K6M7P5E/p1614678103307700?thread_ts=1614591714.270000&cid=C4K6M7P5E
> Revert "Bump @babel/preset-env from 7.12.17 to 7.13.8"

- gulpfile.js
- lms/static/scripts/karma.config.js
- Use new commander options for test task exactly how the client is configured.
- Add --grep, --browser, --no-browser, and --watch options to `test` task
- Remove `test-watch` task (replaced with `test --watch`)
-----
more or less matches the task from the client and frontend-shared
> Improve test task

- lms/views/status.py
- tests/functional/status_test.py
For: https://github.com/hypothesis/product-backlog/issues/1198
> Prevent caching the results of the status end-point

- requirements/requirements.in
> Use '-' instead of '_' for package names

- lms/static/scripts/frontend_apps/components/URLPicker.js
- lms/static/scripts/frontend_apps/components/test/URLPicker-test.js
Replace Button with LabeledButton
**Before**
**After**
> Update buttons in URLPIcker

- lms/db/__init__.py
- lms/migrations/env.py
- tests/unit/conftest.py
- Change any DB backed model on `models/*.py`
- `hev alembic revision --autogenerate -m "change"`
- Review autogenerated migration
> Alembic config changes

- lms/static/scripts/frontend_apps/components/LMSFilePicker.js
- lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js
~depends on https://github.com/hypothesis/lms/pull/2604~
Use this assignment (login as Hypothesis 101 Teacher)
https://hypothesis.instructure.com/courses/125/assignments/1257
From there you can click the button to Select a PDF
**Before**
**After**
> Update LMSFilePIcker buttons

- lms/static/scripts/frontend_apps/components/LMSFilePicker.js
- lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js
This refactor replaces a switch statement for a map. The code is more
concise.
> Replaced switch by map

- bin/update_dev_data.py
https://github.com/hypothesis/lms/pull/2656 Solved the issue around imports but removed the entry point for devdata which is doing nothing on master
> Fix devdata script to acutally execute the main function

- lms/static/scripts/frontend_apps/components/FilePickerApp.js
Combine the various state fields indicating the type of content selected
for an assignment into a tagged union. This is a precursor to extracting
the content selection UI into a separate component. It also better
represents the fact that only one type of content can be selected for an
assignment.
This would have required a change to the hidden `document_url` field.
This field does not appear to be used for anything and is not a
field that appears in the specs for the Content-Item form [1], so I have
removed it.
Part of https://github.com/hypothesis/lms/issues/2524.
[1] https://www.imsglobal.org/specs/lticiv1p0/specification
> Refactor selected content representation in `FilePickerApp`

- lms/security.py
- lms/views/admin.py
> Lint fixes

- lms/resources/_js_config.py
- lms/routes.py
- lms/static/scripts/frontend_apps/config.js
- lms/views/api/canvas/groups.py
- tests/unit/conftest.py
- tests/unit/lms/resources/_js_config_test.py
- tests/unit/lms/views/api/canvas/groups_test.py
Adds 
``` 
"filePicker": {
"groupsEnabled":false,       
"listGroupCategories":{
"authUrl":"http://localhost:8001/api/canvas/oauth/authorize",
"path":"/api/canvas/courses/125/group_categories"
},
}
```
to JS config when in `content-item-selection` mode
Full config opening the content selection modal on local:
```{
"api":{
"authToken":"Bearer ey"
},
"canvas":{
},
"debug":{
"tags":[
"role:instructor"
]
},
"dev":true,
"filePicker":{
"blackboard":{
"enabled":false,
"listFiles":{
"authUrl":"http://localhost:8001/api/blackboard/oauth/authorize",
"path":"/api/blackboard/courses/XXXX/files"
}
},
"canvas":{
"enabled":true,
"groupsEnabled":false,
"listFiles":{
"authUrl":"http://localhost:8001/api/canvas/oauth/authorize",
"path":"/api/canvas/courses/125/files"
},
"listGroupCategories":{ …
```
> Groups enabled and group categories endpoint on JS Config

- lms/migrations/versions/5f80062abcf4_lms_fields_application_instance.py
Just the alembic migration for deployment.
Usage on https://github.com/hypothesis/lms/pull/2699
> Add migration adding new fields to application_instance

- lms/migrations/versions/bb11b5b06274_grouping_table.py
For the model in https://github.com/hypothesis/lms/pull/2741
> Alembic migration for grouping table

- lms/models/__init__.py
- lms/models/application_instance.py
- lms/models/course.py
- lms/models/grouping.py
- lms/services/course.py
- tests/factories/__init__.py
- tests/factories/course.py
- tests/factories/grouping.py
- tests/unit/lms/models/grouping_test.py
- tests/unit/lms/services/course_test.py
No functional changes, just added a new model (migration on https://github.com/hypothesis/lms/pull/2740) and renamed the existing one.
> New Grouping models and renaming existing `Course` as `LegacyCourse`

- lms/services/course.py
- tests/unit/lms/services/course_test.py
A few renames and new, not yet used, methods on the service
> Course service refactor

- lms/services/canvas_api/client.py
- lms/views/api/canvas/authorize.py
- tests/unit/lms/services/canvas_api/client_test.py
- tests/unit/lms/views/api/canvas/authorize_test.py
Usage of the API endpoints here https://github.com/hypothesis/lms/wiki/Canvas-API-Endpoints-Used-by-the-Hypothesis-LMS-App/_compare/fbc9fc88c9ec31a1fb51b7decd1da46d908a919b...1a4793c592da50a3d82fd458a401a9384dce2355
> New Canvas API wrappers methods and necessary scopes

- package.json
- yarn.lock
> Bump `@hypothesis/frontend-shared` to `3.0.0`

- lms/models/__init__.py
- lms/resources/_js_config.py
- lms/resources/lti_launch.py
- lms/services/canvas_api/client.py
- lms/services/group_info.py
- lms/services/grouping.py
- lms/validation/_api.py
- lms/views/api/canvas/sync.py
- lms/views/api/lti.py
- tests/unit/lms/resources/_js_config_test.py
- tests/unit/lms/resources/lti_launch_test.py
- tests/unit/lms/services/canvas_api/client_test.py
- tests/unit/lms/services/grouping_test.py
- tests/unit/lms/views/api/canvas/sync_test.py
> Revert "Canvas groups backend"

- lms/models/__init__.py
- lms/resources/_js_config.py
- lms/resources/lti_launch.py
- lms/services/canvas_api/client.py
- lms/services/group_info.py
- lms/services/grouping.py
- lms/validation/_api.py
- lms/views/api/canvas/sync.py
- lms/views/api/lti.py
- tests/unit/lms/resources/_js_config_test.py
- tests/unit/lms/resources/lti_launch_test.py
- tests/unit/lms/services/canvas_api/client_test.py
- tests/unit/lms/services/grouping_test.py
- tests/unit/lms/validation/_api_test.py
- tests/unit/lms/views/api/canvas/sync_test.py
Reverted due to a bug affecting non-groups assignments
Original PR: https://github.com/hypothesis/lms/pull/2767
Revert PR: https://github.com/hypothesis/lms/pull/2819
> Add canvas groups feature again

- requirements/bddtests.txt
- requirements/dev.txt
- requirements/functests.txt
- requirements/lint.txt
- requirements/requirements.txt
- requirements/tests.txt
I used `hdev requirements --package h-vialib`
> Upgrade h-vialib to 1.0.17

- lms/resources/_js_config.py
- lms/routes.py
- lms/services/__init__.py
- lms/services/blackboard_api/_schemas.py
- lms/services/blackboard_api/service.py
- lms/services/exceptions.py
- lms/views/api/blackboard/files.py
- lms/views/api/exceptions.py
- tests/unit/lms/resources/_js_config_test.py
- tests/unit/lms/services/blackboard_api/_schemas_test.py
- tests/unit/lms/services/blackboard_api/service_test.py
- tests/unit/lms/views/api/blackboard/files_test.py
Get real download URLs from the Blackboard API instead of fake ones.
> Download real Blackboard files

- lms/migrations/versions/bf67a1e68cea_add_assignment_extras.py
A DB migration adding a JSONB extras column for the assignment for: https://github.com/hypothesis/lms/pull/2783
> Migration for assigment extra column

- lms/models/application_instance.py
- lms/models/file.py
Add `File.application_instance` and `ApplicationInstance.files`. These are convenience attributes that'll be used in future PRs.
> Add File<>ApplicationInstance relation

- lms/services/canvas_api/client.py
- tests/unit/lms/services/canvas_api/client_test.py
Notify on sentry whenever that happens to keep track of it
From https://github.com/hypothesis/lms/pull/2880
> Remove duplicate files from canvas API

- lms/services/assignment.py
- tests/unit/lms/services/assignment_test.py
Depends on https://github.com/hypothesis/lms/pull/2876
> Add models.CanvasModuleItemConfiguration

- lms/services/canvas.py
- tests/unit/lms/services/canvas_test.py
Change the existing private method `CanvasService._file_in_course()` into a public `CanvasService.can_see_file_in_course()` method.
Some future business logic in `CanvasService` is going to make use of this method, so I'm tidying it up to make it clearer:
* Changed the name of the method.
The method doesn't tell you whether a course contains a file. It tells you whether the current user can see the file in the course.
* Added type annotations and a docstring
* Reformatted the code to be longer but more readable.
Previously it wasn't very obvious that calling this method actually makes a call to the list-files API, because that was hidden away at the end of an `any()`. Now it gets its own line.
Previously both the `file_id` param and the IDs returned by `list_files()` were passed through …
> Add CanvasService.can_see_file_in_course()

- Jenkinsfile
The LMS Jenkinfile has been updated to support deploying to a second
region in parallel with us-west-1.
> Jenkinsfile update - Deploy to a second region

- README.markdown
This is basically a no-op branch. A new line has been added to the
README file to test the deployment process.
> Testing CI workflow

- lms/db/_bulk_action.py
- tests/unit/lms/db/_bulk_action_test.py
This is an example of some of the suggestions made reviewing: https://github.com/hypothesis/lms/pull/2844
> Example of some changes suggested during review

- lms/services/oauth_http.py
- tests/unit/lms/services/oauth_http_test.py
Nothing uses this yet but a future commit will extend `BasicClient.request()` to use it.
> Add `OAuthHTTPService.refresh_token_request()`

- lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js
- lms/static/scripts/frontend_apps/components/test/LaunchErrorDialog-test.js
- lms/static/scripts/test-util/mock-imported-components.js
Also fix a few tests that broke after this change.
> Update mockImportedComponents to match other projects

- lms/routes.py
- lms/services/blackboard_api/_schemas.py
- lms/services/blackboard_api/client.py
- lms/static/scripts/frontend_apps/api-types.js
- lms/static/scripts/frontend_apps/components/LMSFilePicker.js
- lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js
- lms/views/api/blackboard/files.py
- tests/unit/lms/services/blackboard_api/_schemas_test.py
- tests/unit/lms/services/blackboard_api/client_test.py
- tests/unit/lms/views/api/blackboard/files_test.py
This adds folder support to the backend APIs for Blackboard Files.
Note that without the corresponding frontend changes to understand folders this doesn't work: it breaks the UI. So frontend changes will be needed before merging this.
This commit changes the existing `/api/blackboard/courses/{course_id}/files` API to return a mixed list of files *and* folders.
Files look pretty much like they did before except:
* They now have a new `type: "File"` field
* They now have a new `parent_id` field that is either the `id` of the parent folder or `null` for top-level files
Folders look the same as files except:
* The `id` fields of folders are not wrapped in `blackboard://` URLs like they are for files
* Folders have `type: "Folder"`
* Folders have a `contents` field which is a dict containing …
> Add folder support to Blackboard Files backend

- lms/services/__init__.py
- lms/services/exceptions.py
This is no longer used anywhere.
> Remove unused `HTTPValidationError`

- lms/migrations/versions/d9c9e65c463e_files_parent_id.py
For https://github.com/hypothesis/lms/issues/3012
Adds nullable column for tree like relationships.
Autogenerated from https://github.com/hypothesis/lms/pull/3045
> Migration for File.parent_lms_id

- lms/models/file.py
New column to store tree like relationships on Files
Migration on https://github.com/hypothesis/lms/pull/3044
> Add parent_lms_id to File model

- lms/templates/application_instances/new_application_instance.html.jinja2
Update language about features enabled by using Canvas dev credentials and include link to KB
> Update language about Canvas dev credentials

- lms/static/scripts/frontend_apps/components/URLPicker.js
- lms/static/scripts/frontend_apps/components/test/URLPicker-test.js
- package.json
- yarn.lock
This PR updates the `URLPicker` component to use the shared `Modal` and `TextInput` components. This brings them into visual/UI line with other modals involved in choosing content for an assignment during configuration.
Before, Blackboard:
After, Blackboard:
Before, Canvas:
After, Canvas:
Check out and run this branch.
1. Log in to https://aunltd-test.blackboard.com/ as `blackboardteacher`
2. Create a new assignment in [this course](https://aunltd-test.blackboard.com/ultra/courses/_19_1/cl/outline) (Content -> Build Content -> Hypothesis, localhost, make devdata) (All you need to do is give it a name and click Submit)
3. Launch the unconfigured assignment and click the “Enter URL of web page or PDF” button.
1. Go to the [Sections Enabled …
> Use common Modal, TextInput in URLPicker

- lms/services/course.py
This gets a bit on the way of doing another bigger refactor.
> Remove superfluous arg

- lms/resources/_js_config/__init__.py
- lms/services/assignment.py
- lms/static/scripts/frontend_apps/config.js
- lms/views/api/canvas/assignments.py
- tests/unit/lms/resources/_js_config/__init___test.py
- tests/unit/lms/services/assignment_test.py
- tests/unit/lms/views/api/canvas/assignments_test.py
Send the frontend details about the new create assignment endpoint.
The fronted currently ignores this so there's should be not behavior changes.
> Send the client info about the new create assignment endpoint

- lms/services/oauth2_token.py
- tests/unit/lms/services/oauth2_token_test.py
Reverts hypothesis/lms#3149
This is not broken but not providing useful information, see: https://hypothes-is.slack.com/archives/C1MA4E9B9/p1632914095038000
> Revert "Log refresh token changes"

- lms/views/exceptions.py
I don't think this docstring is actually adding anything useful.
> Remove an unnecessary docstring

- lms/static/scripts/ui-playground/index.js
- package.json
- yarn.lock
This required adapting pattern library import paths due to changes in
https://github.com/hypothesis/frontend-shared/pull/200.
> Update @hypothesis/frontend-shared to v3.11.0

- lms/static/scripts/frontend_apps/utils/test/onedrive-picker-client-test.js
Add some clarification, based on suggestion here: https://github.com/hypothesis/lms/pull/3134#discussion_r718588567
> Clarify a test in `onedrive-picker-client-test.js`

- lms/models/assignment.py
Migration on https://github.com/hypothesis/lms/pull/3117
> Model changes for new assignment.ext_lti_assignment_id

- tests/unit/lms/resources/_js_config/__init___test.py
This is to make way for https://github.com/hypothesis/lms/pull/3337.
The tests for two different methods were run together into one class, which is confusing. There was also a parametrize that I think was just making the tests less clear, and there were some missing test cases.
> Fix up some tests

- lms/views/basic_lti_launch.py
- tests/functional/views/basic_lti_launch_test.py
Reverts hypothesis/lms#3320
The explanation here: https://github.com/hypothesis/lms/pull/3320 doesn't take into consideration editing assigments which won't take effect if that PR was merged without https://github.com/hypothesis/lms/pull/3126.
> Revert "Re-enable canvas_db_configured_basic_lti_launch view"

- lms/models/grouping.py
This will become handy on the service to accept a `type_` param and avoid duplication for canvas/bb groups functions there.
> Enum values for Grouping.type

- lms/services/canvas_api/client.py
- tests/unit/lms/services/canvas_api/client_test.py
Another attempt to fix https://github.com/hypothesis/lms/issues/3392
> Further increase the Canvas groups API timeout

- lms/models/grouping.py
Needs migration before merging
> Model for storing grouping membership

- lms/resources/_js_config/__init__.py
- lms/routes.py
- lms/views/api/blackboard/sync.py
- tests/unit/lms/resources/_js_config/__init___test.py
- tests/unit/lms/views/api/blackboard/sync_test.py
Config for sync API talking into account Blackboard.
Added an empty sync API endpoint for blackboard.
> Blackboard sync API configuration

- tests/unit/lms/services/grouping_test.py
Just remove a little code duplication from this test, hopefully makes the test a little more readable.
This also rearranges the test to have the standard three sections Arrange, Act and Assert (separated by two blank lines).
> Simplify a test

- lms/models/__init__.py
This makes importing them easier.
> Add `BlackboardGroup` and `GroupingMembership` to `lms.models`

- lms/views/api/blackboard/sync.py
- tests/unit/lms/views/api/blackboard/sync_test.py
- Cherry pick https://github.com/hypothesis/lms/pull/3441 into this branch
- Launch `localhost (make devdata) Groups Assignment with 50 Groups` as a student. 
- You'll get only one group on the client.
- You'll now have a group on group_membership
```
postgres=# select * from grouping_membership ;
created           |          updated           | grouping_id | user_id 
----------------------------+----------------------------+-------------+---------
2021-11-26 16:16:07.651461 | 2021-11-26 16:16:07.651461 |           2 |       2
```
- You can add logging to `lms/services/async_oauth_http.py` to check the request being made:
```diff
--git a/lms/services/async_oauth_http.py b/lms/services/async_oauth_http.py
index 96a97fe1..9a0aab57 100644
--- a/lms/services/async_oauth_http.py
+++ …
```
> Get and store student groups on blackboard sync API

- lms/views/api/blackboard/sync.py
- tests/unit/lms/views/api/blackboard/sync_test.py
- Start following the testing for https://github.com/hypothesis/lms/pull/3448
- Launch the assigment as teacher
- They UI won't change as you change students in the grading bar but you can look at the sync api response on the browser:
```["group:203da5989dcae4e42def5624bc0f81449b02b8c4@lms.hypothes.is"]```
- The group ID should match your record on group_membership:
```
postgres=# select authority_provided_id from grouping join grouping_membership on grouping_membership.grouping_id = id ;                                                                                              
authority_provided_id           
------------------------------------------
203da5989dcae4e42def5624bc0f81449b02b8c4
(1 row)
```
> Get groups from the DB while grading on BB sync API

- Dockerfile
- gulpfile.mjs
- lms/static/styles/frontend_apps.scss
- package.json
- tailwind.config.mjs
- yarn.lock
This PR simply breaks off several commits from #3495 that serve to add the tailwind dependency, bump shared-package versions and drop in a rudimentary config and update the CSS build task and Dockerfile. 
These changes on their own don't do anything (except successfully build). 
This branch should build. That's the main objective. It does not in itself add or change any CSS.
> Add Tailwind support

- lms/static/styles/frontend_apps.scss
These styles are going away in #3495, but it's too soon to pull them just yet.
> Hey, put those styles back

- lms/static/scripts/frontend_apps/components/SubmitGradeForm.js
- lms/static/scripts/frontend_apps/components/test/SubmitGradeForm-test.js
- lms/static/scripts/frontend_apps/services/grading.js
If a student was given a zero grade, the grade was not showing when
navigating to another student and coming back to the `zero` graded
student.
Before:
https://user-images.githubusercontent.com/8555781/146576558-b75ba538-2823-4d0e-b660-d974fd03c79c.mov
After:
https://user-images.githubusercontent.com/8555781/146576607-0af340fe-570d-429d-a3e6-32ac7a6d5712.improvement
> Fix issue displaying a `zero` grade

- lms/models/grouping.py
These constraints aren't entirely obvious so it seems worth adding some explanatory comments.
> Add some comments to `models.Grouping`'s constraints

- tests/unit/lms/services/grouping_test.py
Split `TestGroupingService` into separate test classes for each method.
This just splits the test class up, doesn't change any of the tests at all other than renaming some of them and adding docstrings to a couple.
I think `GroupingService` is complicated enough that it needs a separate test class for each method: it makes it easier to see what is tested for each method and allows each method to have its own separate set of fixtures which makes it easier to understand and avoids shared fixtures potentially coupling together tests for different methods.
> Split up `TestGroupingService`

- tests/unit/lms/services/grouping_test.py
Use `functools.partial` to wrap `generate_authority_provided_id()` in a partial that injects default values for the `tool_consumer_instance_guid` and `lms_id` arguments so that each individual test doesn't need to pass these arguments. These argument values are uninteresting and don't change between tests.
* This gets rid of the `TOOL_CONSUMER_INSTANCE_GUID` constant (I think CONSTANTS like this in tests are kind of ugly and distracting)
* Each test no longer needs to pass `self.TOOL_CONSUMER_INSTANCE_GUID` as the first argument to every `svc.generate_authority_provided_id()` call (was this any better than just passing `"tool_consumer_instance_guid"` literally?)
* Tests also no longer need to pass `"lms_id"` as the _second_ argument to every `svc.generate_authority_provided_id()` call …
> Deduplicate `generate_authority_provided_id()` tests

- tests/unit/lms/views/api/canvas/sync_test.py
Small test refactor. 
Testing `_get_canvas_groups` directly was getting in the way of another PR>
> Refactor canvas sync api tests

- lms/views/api/canvas/sync.py
- tests/unit/lms/views/api/canvas/sync_test.py
We should be storing this information at least to have the same data for blackboard and canvas.
I don't think we can start using that information right away to avoid a query to the API when speed grading but we could after this builds up the table for a while.
> Canvas grouping memberships

- lms/services/grouping.py
- lms/services/upsert.py
- lms/views/api/blackboard/sync.py
- lms/views/api/canvas/sync.py
- tests/unit/lms/services/grouping_test.py
- tests/unit/lms/services/upsert_test.py
- tests/unit/lms/views/api/blackboard/sync_test.py
- tests/unit/lms/views/api/canvas/sync_test.py
Last one for https://github.com/hypothesis/lms/issues/3500
Using bulk_upsert for groupings. Needs to return the ORM objects in this one.
> Bulk upsert for groupings

- Jenkinsfile
This commit enables lms-ca-prod deployments for our Canadian environment
> Enable lms deployments for Canada

- lms/services/exceptions.py
Factor out the `_exception_class()` method. The reason is that I want to construct the exception differently in different cases in the future: sometimes `OAuth2TokenError(refresh=True, **kwargs)`, sometimes `OAuth2TokenError(refresh=False, **kwargs)`.
This introduces some duplication but the gain in flexibility is worth it.
> Factor out `_exception_class()`

- lms/models/application_instance.py
- lms/models/grading_info.py
- lms/models/group_info.py
- lms/models/oauth2_token.py
- lms/services/grading_info.py
- lms/services/group_info.py
- lms/services/lti_h.py
- lms/services/oauth2_token.py
- tests/unit/lms/services/grading_info_test.py
- tests/unit/lms/services/group_info_test.py
- tests/unit/lms/services/lti_h_test.py
- tests/unit/lms/services/oauth2_token_test.py
Model changes for the migration in https://github.com/hypothesis/lms/pull/3748. 
Needs to the deployed after the migration is deployed.
> Model changes to add application_instance_id

- lms/resources/lti_launch.py
- Use temp bool variables to capture the state in the session correctly
- Log the course's context_id instead of the consumer_key
First, what we are trying to find here is cases where we do have an existing "LegacyCourse" but not a "Course". This means that the course was created before the new "Course" model and not launched since, until now.
We are not interested in cases where both LegacyCourse and Course are created at the same time. That would be the very common case of a new course using Hypothesis.
(LegacyCourse's table name is "course", Course's is "grouping". I'll use the model names here as is less confusing)
tox -qe dockercompose -- exec postgres psql -U postgres -c "delete from grouping where type ='course'"
tox -qe dockercompose -- exec postgres psql -U postgres -c "delete …
> Fix temporally course logging logic for courses

- package.json
- tailwind.config.mjs
- yarn.lock
Update package and remove tailwind configuration now available from upstream preset.
> Update Frontend shared v4.5.2

- conf/supervisord-dev.conf
From https://github.com/hypothesis/lms/pull/3870#discussion_r855849833
> Explicitly set the number of workers in gunicorn

- lms/models/application_instance.py
- tests/unit/lms/models/application_instance_test.py
Not used anywhere yet but needed for https://github.com/hypothesis/lms/pull/3870
> Expose the LTI version on model.ApplicationInstance

- tests/unit/lms/services/lti_grading/_v11_test.py
Previously we had a complex set of fixtures which constructed the right fixture for each test. Quite a few of the arguments were specific to individual tests and put distance between the setup and the assertions of the tests.
Now there is a complete example generated, which individual tests then modify as required inside the tests, which makes them more self contained.
> Refactor grading service V11 tests main fixture

- lms/models/lti_params.py
- lms/services/__init__.py
- lms/services/grading_info.py
- lms/services/jwt.py
- lms/services/lti_grading/__init__.py
- lms/services/lti_grading/_v11.py
- lms/services/lti_grading/_v13.py
- lms/services/lti_grading/factory.py
- lms/services/lti_grading/interface.py
- lms/services/ltia_http.py
- lms/services/rsa_key.py
- lms/views/api/lti.py
- tests/functional/lti_certification/v13/grading/test_assignment_and_grading.py
- tests/unit/conftest.py
- tests/unit/lms/services/__init___test.py
- tests/unit/lms/services/jwt_test.py
- tests/unit/lms/services/lti_grading/_v11_test.py
- tests/unit/lms/services/lti_grading/_v13_test.py
- tests/unit/lms/services/lti_grading/factory_test.py
- tests/unit/lms/services/ltia_http_test.py
- tests/unit/lms/services/rsa_key_service_test.py
- tests/unit/lms/views/api/lti_test.py
- tests/unit/services.py
Nothing should have change as the code is mostly just moved around, but just in case I'm checking the grading in BB
- Launch https://aunltd-test.blackboard.com/webapps/blackboard/execute/blti/launchPlacement?blti_placement_id=_20_1&content_id=_36_1&course_id=_19_1 as `Blackboard Student 2`
- Launch the assignment again as a teacher. You should get the grading bar with one student in the dropdown now.
- Switch to the student on the drop-down. You'll get a empty grade.
- Grade the student
- Relaunch the assignment and select the student again. You'll get the submitted grade.
> Rename LTIOutcomes to LTIGrading and prepare for LTI1.3 support

- lms/services/lti_grading/_v13.py
- tests/unit/lms/services/lti_grading/_v13_test.py
For https://github.com/hypothesis/lms/issues/3909
A small fix to correctly build URLs, just appending `/something` won't work in Moodle.
> Build correct grading service URLs in Moodle

- tests/.pylintrc
> Don't lint `_compiled_feature_steps.py`

- lms/routes.py
- lms/views/canvas/config.py
- tests/unit/lms/views/canvas/config_test.py
Moving the existing /config_xml view to the canvas namespace. Including the version in the route to accommodate the v13 in a follow up PR.
Just open http://localhost:8001/config_xml
> LTI 1.1 `/config_xml` view internal rename

- lms/models/assignment.py
- lms/views/lti/deep_linking.py
For: 
Must be merged after
* https://github.com/hypothesis/lms/pull/3996
Follow the setup for the DB in https://github.com/hypothesis/lms/pull/3996
* `make sure`?
* Noodle about in Canvas?
> Change references to `module_item_configuration` to `assignment`

- lms/services/assignment.py
- lms/views/predicates/_lti_launch.py
- tests/unit/lms/services/assignment_test.py
For: 
All of this was only used in the view removed in https://github.com/hypothesis/lms/pull/4000
> Remove unused `AssignmentService` methods

- lms/resources/_js_config/__init__.py
- lms/resources/lti_launch.py
- lms/validation/__init__.py
- lms/validation/_api.py
- lms/views/api/lti.py
- tests/factories/assignment.py
- tests/functional/views/basic_lti_launch_test.py
- tests/unit/lms/resources/_js_config/__init___test.py
- tests/unit/lms/resources/lti_launch_test.py
- tests/unit/lms/validation/_api_test.py
For:
Remove references to the column before another PR to remove it from the table.
Discovered a unused schema that wasn't deleted in a previous cleanup.
> Remove references to `ext_lti_assignment`

- lms/views/lti/basic_launch.py
For:
This isn't important at all, but it makes reading the test PR here a nightmare:
* https://github.com/hypothesis/lms/pull/4029
So I've pulled it out. 
The code here is pretty much the same. A few args have been replaced with kwargs or other non-functional changes.
> Re-order the views to have common ones at the top

- README.markdown
This is basically a noop commit to test the functionality of our Jenkins
workflows.
> Testing Pipeline Deployments

- lms/static/scripts/frontend_apps/utils/api.js
- lms/static/scripts/frontend_apps/utils/test/api-test.js
This is a hook that wraps `useFetch` and deals with the details of making an authenticated API call for a given path + params. Fetching a given data item can then be done with a one-liner. Example from the upcoming JSTORPicker changes:
```js
const [articleId, setArticleId] = useState(/** @type {string|null} */ (null));
/** @type {FetchResult<Metadata>} */
const metadata = useAPIFetch(
articleId ? urlPath`/api/jstor/articles/${articleId}` : null
);
/** @type {FetchResult<Thumbnail>} */
const thumbnail = useAPIFetch(
articleId ? urlPath`/api/jstor/articles/${articleId}/thumbnail` : null
);
```
> Add `useAPIFetch` hook to simplify API fetches

- lms/migrations/versions/52ff45973d5b_remove_ext_id.py
- lms/models/assignment.py
For:
Remove the column now that https://github.com/hypothesis/lms/pull/4036 stopped using it in the code
- On `master`, start with a fresh DB
```docker stop lms_postgres_1; docker rm lms_postgres_1; make services```
- Run the migrations up until the last one
```hdev alembic upgrade head```
- Now switch to this branch `rm-ext-lti-migration` and get some regular data in:
```make devdata```
- Insert some "problematic" (null resource_link_id) rows in the table, more that 3.
```
tox -qe dockercompose -- exec postgres psql -U postgres -c "insert into assignment (tool_consumer_instance_guid, document_url, ext_lti_assignment_id) values ('TOOL', 'document', 'EXT-1');"
tox -qe dockercompose -- exec postgres psql -U postgres -c "insert into assignment …
```
> Migration to remove ext_lti_assignment_id

- lms/migrations/versions/fe80746cf145_add_lti_roles_and_assignment_membership.py
For:
* https://github.com/hypothesis/lms/issues/3993
Migration for:
* https://github.com/hypothesis/lms/pull/4062
> DB migration for LTI roles and assignment membership tables

- lms/migrations/versions/1e146996cca6_add_assignment_grouping.py
For:
* https://github.com/hypothesis/lms/issues/3992
Required for:
* https://github.com/hypothesis/lms/pull/4066
> DB migration for `assignment_grouping`

- lms/resources/_js_config/file_picker_config.py
- lms/resources/lti_launch.py
- lms/validation/_lti_launch_params.py
- tests/unit/lms/resources/_js_config/file_picker_config_test.py
- tests/unit/lms/resources/lti_launch_test.py
This reverts commit fb2a12046ce9be63b963a1e2c98312ee3a6fb52e.
> Remove `canvas_api_custom_domain` from the launch context

- lms/views/lti/deep_linking.py
- tests/unit/lms/views/lti/deep_linking_test.py
Canvas seems to ignore this value so sending the wrong value hasn't had
any effect but the IMS certification tools does check the value and
other implementations might.
- Deeplinking continues working on LTI1.3 on Canvas.
> Fix the deep linking message to be compliant with the spec

- conf/supervisord-dev.conf
- conf/supervisord.conf
- docker-compose.yml
- lms/pshell.py
- lms/tasks/celery.py
- requirements/bddtests.txt
- requirements/dev.txt
- requirements/functests.txt
- requirements/lint.txt
- requirements/requirements.in
- requirements/requirements.txt
- requirements/tests.txt
- tests/unit/lms/tasks/celery_test.py
- tox.ini
Configuration has been taken mostly verbatim from checkmate.
- `make services dev`
Now it show the output of a celery worker
> Celery initial setup

- lms/views/admin/__init__.py
- tests/unit/lms/views/admin/__init___test.py
See https://github.com/hypothesis/pyramid-googleauth/pull/5#pullrequestreview-1028730759
> Pass next parameter to pyramid_googleauth to redirect to the target URL

- lms/models/application_instance.py
- lms/templates/admin/instance.html.jinja2
- tests/unit/lms/models/application_instance_test.py
- tests/unit/lms/resources/_js_config/__init___test.py
Some niceties around LTI version.
> Improved LTI version detection

- conf/supervisord-dev.conf
- tox.ini
Aligning local and production config method
> Use WEB_CONCURRENCY for local environment

- lms/product/factory.py
- tests/unit/lms/product/factory_test.py
Guess the product family more accurately leaning on the information stored in the DB
This will work in all grading endpoints in https://github.com/hypothesis/lms/blob/b3b6170240841a3fd7fdf21bc8403fa0d878f2c6/lms/views/api/lti.py where we always guess "UNKOWN" now.
> Fallback for product family detection based on the application instance

- lms/services/http.py
- tests/unit/lms/services/http_test.py
For:
* https://github.com/hypothesis/lms/issues/4214
* https://github.com/hypothesis/lms/pull/4246
This exposes the session so people can modify it. At the moment this would be a bad idea (as everyone shares it), but we intent to _not_ use the singleton in VitalSource work.
This also:
* Cuts down the documentation which restates a lot of the requests documentation
* Removes a parameter for session which was only used for testing
* Refactors the testing to be simpler and smaller
> Expose the `HTTPService` session and refactor

- lms/services/vitalsource/_client.py
- lms/services/vitalsource/service.py
This adds some documentation, and also fixes a small piece of tech debt from previous refactors.
> Add more documentation to the VS service + small tweak

- lms/services/jstor/_article_metadata.py
- tests/unit/lms/services/jstor/_article_metadata_test.py
For:
* https://github.com/orgs/hypothesis/projects/72
This adds two things:
* Links to related items
* Details of the parent journal / book title
The output of the metadata end-point has changed from:
```json
{
"title": "Improved Set Estimators for the Coefficients of a...",
"content_status": "available", 
}
```
To:
```json
{
"title": "Improved Set Estimators for the Coefficients of a...",
"content_status": "available", 
"container": {
"type": "journal", 
"title": "The Canadian Journal of Statistics / La Revue Canadienne de Statistique"
}, 
"related_items": {
"next_id": "10.2307/3314736", 
"previous_id": "10.2307/3314734"
}
}
```
If any of the details are missing, the value will be `None`.
At the moment, this has no effect but will enable front-end features.
* Start LMS and friends
* …
> Add details of JSTOR linked items and containing journal / book title

- tests/functional/conftest.py
- tests/functional/lti_certification/v13/conftest.py
- tests/functional/lti_certification/v13/core/test_valid_teacher_launches.py
- tests/functional/views/basic_lti_launch_test.py
Same fix as https://github.com/hypothesis/lms/pull/4267 but in a different fixture.
> Fix JKT endpoint httppretty mock

- lms/migrations/versions/42b39684836f_events.py
Auto generated from the models at https://github.com/hypothesis/lms/pull/4283
This can be seen in action in https://github.com/hypothesis/lms/pull/4144
> Migration for the event_table

- lms/db/__init__.py
- lms/db/_columns.py
- lms/migrations/versions/42b39684836f_events.py
- lms/models/__init__.py
- lms/models/event.py
- lms/models/lti_role.py
Migration at https://github.com/hypothesis/lms/pull/4282
This can be seen in action in https://github.com/hypothesis/lms/pull/4144
> Models for the new event tables

- lms/services/jwt.py
- tests/unit/lms/services/jwt_test.py
Our version uses requests instead of urllib which provides an user agent
by default but also allows for further customizations down the line.
This is motivated by school having problems with this. I reckon it makes sense to have control over this in any case.
- On `main` test opening an LTI1.3 assignment with a modified JWK enpoint
```tox -qe dockercompose -- exec postgres psql -U postgres -c "update lti_registration set key_set_url = 'https://elearning.aua.am/mod/lti/certs.php' where id = 3"```
- Open https://hypothesis.instructure.com/courses/319/assignments/3308
Fails with
```
web (stderr)         |   File "/home/marcos/.pyenv/versions/3.8.12/lib/python3.8/urllib/request.py", line 649, in http_error_default
web (stderr)         |     raise HTTPError(req.full_url, code, msg, hdrs, fp) …
```
> Use our own PyJWKClient instead of the one provided by PyJWT

- lms/services/vitalsource/_client.py
- tests/unit/lms/services/vitalsource/_client_test.py
Sort of for:
* https://github.com/hypothesis/lms/issues/4215
At the moment we are logging sentry errors whenever a book is missing. These should not be raised as `ExternalRequestError`s in the cases where we handle the exception completely.
Use the following headers:
* `Content-Type: application/json`
* `X-VitalSource-API-Key`: <Get this from devdata>
Then try the following URLs
* https://api.vitalsource.com/v4/products/9999999
* Status code: 404
* Contents: `{"errors": ["Product 9999999 not found."]}`
* `Content-Type: application/json; charset=utf-8`
* https://api.vitalsource.com/v4/products/9999999/toc
* Status code: 404
* Contents: `{"errors": ["Book not found"]}`
* `Content-Type: application/json; charset=utf-8`
* https://api.vitalsource.com/v4/BROKEN
* Status code: 501 - Not …
> Capture `ExternalRequestErrors` for 404's in VitalSource instead of raising them

- README.markdown
https://github.com/hypothesis/playbook/issues/932
> Post Go-Live Release workflow test

- lms/security.py
- tests/unit/lms/security_test.py
Small refactor in security.py to accommodate further changes and new policies. 
Diff might be easier to read if done by commit.
There should not be any functional changes here, as a sanity check launch an assignment:
> Security LTISecurityPolicy refactor

- .github/workflows/tasks.yml
A workflow for running hypothesis commands inside an Elastic Beanstalk
Docker container
Part of the work towards: https://github.com/hypothesis/playbook/issues/957
---
This is a very similar workflow to what is being used by H. A PR with a better functional description can be found: https://github.com/hypothesis/h/pull/7580
The difference with the H workflow is we are running, `hypothesis` commands. In the LMS workflow we are running `alembic` commands.
> Created workflow: tasks.yml

- .github/workflows/tasks.yml
Corrected an incorrect AWS region definition.
https://hypothes-is.slack.com/archives/CR3E3S7K8/p1662468753309169
> Updated task workflow

- lms/resources/_js_config/__init__.py
- lms/static/scripts/frontend_apps/config.js
- lms/static/scripts/frontend_apps/index.js
- lms/static/scripts/frontend_apps/test/index-test.js
- tests/unit/lms/resources/_js_config/__init___test.py
Discussion: https://hypothes-is.slack.com/archives/C1MA4E9B9/p1660658193402049
> New mechanism to display values from the backend in the browser's console

- lms/services/application_instance.py
- tests/unit/lms/services/application_instance_test.py
For:
* https://github.com/hypothesis/lms/issues/4413
This is a pretty blunt instrument, but any action that attempts to get the "current" application instance will fail with an "AccountDisabled" error.
As this is a serialisable error, and serialisable errors are handled in both the UI and API, this should result in some sensible output in all cases.
This might be improved by using the public id. We might want to merge the helper ticket first.
I tried this in the `check_guid_matches()`, but that isn't on the service, so would require moving to the service first. This has the "advantage" of _really_ breaking absolutely everything.
This might not kick in instantly, as a the application instance might be allocated to a new org when it's launched, but that can only happen once... so I don't …
> Raise an exception for disabled accounts

- lms/services/vitalsource/_client.py
- lms/services/vitalsource/factory.py
- lms/services/vitalsource/service.py
- tests/unit/lms/services/vitalsource/_client_test.py
- tests/unit/lms/services/vitalsource/factory_test.py
- tests/unit/lms/services/vitalsource/service_test.py
For:
* https://github.com/hypothesis/lms/issues/4463
Our current licence checking method doesn't work. We're removing it instead of adding more.
* Start all the things
* Visit: https://hypothesis.instructure.com/courses/125
* Add a VitalSource assignment
* e.g. https://bookshelf.vitalsource.com/reader/books/L-999-70867
* It should work!
> Remove licence checks and the disable licence check option

- lms/routes.py
- lms/services/organization.py
- lms/templates/admin/base.html.jinja2
- lms/templates/admin/organization.html.jinja2
- lms/templates/admin/organization.new.html.jinja2
- lms/templates/admin/organizations.html.jinja2
- lms/views/admin/organization.py
- tests/unit/lms/services/organization_service_test.py
- tests/unit/lms/views/admin/organization_test.py
- Go over http://localhost:8001/admin/orgs
- Click a new organization with a name
- A new gets created, you can now enable/disable it.
> Organization admin pages (new and enable toggle)

- lms/models/__init__.py
- lms/models/_mixins/public_id.py
- lms/resources/_js_config/__init__.py
- lms/services/application_instance.py
- lms/services/organization.py
- lms/services/public_id.py
- lms/templates/admin/macros.html.jinja2
- lms/templates/admin/organization.html.jinja2
- lms/templates/admin/organizations.html.jinja2
- tests/unit/conftest.py
- tests/unit/lms/models/_mixins/public_id_test.py
- tests/unit/lms/models/organization_test.py
- tests/unit/lms/services/organization_service_test.py
- tests/unit/lms/services/public_id_test.py
For:
* https://github.com/hypothesis/lms/issues/4500
> Use a hybrid property on `PublicIDMixin` to remove the request method

- bin/run_sql_task.py
- lms/sql_tasks/tasks/fdw/create_from_scratch/00_create.jinja2.sql
Main objective here is see how GHA handles secrets 
Once that's checked this needs:
- Integration with the functest
- Readme for the new tasks
- Proper handling of the new variables, env var -> pyramid_setting -> jinja variable.
> Test FDW creation and GHA password masking

- bin/run_sql_task.py
- docs/configuration.md
- lms/config.py
- lms/sql_tasks/tasks/report/create_from_scratch/00_schema/00_public.jinja2.sql
- lms/sql_tasks/tasks/report/create_from_scratch/00_schema/01_create.jinja2.sql
- tox.ini
Need both access to the new report schema and also to a selection of tables in the existing public one.
- Set the new env variable in lms-qa and lms-prod
> Grant permissions to the FDW users

- .github/workflows/report_refresh.yml
For:
* https://github.com/hypothesis/report/issues/4
> Set the refresh to run in prod, not QA

- lms/sql_tasks/tasks/report/create_from_scratch/04_activity_counts/02_organization_activity/01_create_view.sql
- lms/sql_tasks/tasks/report/create_from_scratch/04_activity_counts/02_organization_activity/02_initial_fill.sql
For:
* https://github.com/hypothesis/report/issues/4
This allows us to easily implement a "last 6 months" filter. It is also the date format wanted for some reports.
> Expose the raw timestamp to allow normal date operations on it

- lms/product/__init__.py
- lms/product/d2l/__init__.py
- lms/product/d2l/product.py
- lms/product/factory.py
Requires https://github.com/hypothesis/devdata/pull/65 for testing the D2L side
Check that nothing is broken in:
- Canvas https://hypothesis.instructure.com/courses/125/assignments/873
- BB https://aunltd-test.blackboard.com/webapps/blackboard/execute/blti/launchPlacement?blti_placement_id=_20_1&content_id=_37_1&course_id=_19_1
- D2L https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/2119/View (credentials in 1Pass)
> New D2L product scaffolding

- .github/workflows/report_refresh.yml
- .github/workflows/sql_tasks.yml
For:
* https://github.com/hypothesis/report/issues/48
> Add New Relic to SQL tasks

- lms/sql_tasks/tasks/report/create_from_scratch/01_functions/01_date_functions.sql
- lms/sql_tasks/tasks/report/create_from_scratch/04_activity_counts/03_organization_activity/01_create_view.sql
- lms/sql_tasks/tasks/report/create_from_scratch/04_activity_counts/03_organization_activity/02_initial_fill.sql
For:
* https://github.com/hypothesis/report/issues/50
This allows us to conveniently check for things within the range as well as possibly do self joins to get period on period growth.
> Store the start and end dates for the reporting periods of Organization activity

- .github/workflows/report_refresh.yml
For:
* https://github.com/hypothesis/report/issues/47
> Fix script location on refresh GHA definition

- lms/services/document_url.py
- tests/unit/lms/services/document_url_test.py
Messed up the target branch on https://github.com/hypothesis/lms/pull/4711
These are the same commits
> Fix jstor issues in speedgrader

- .cookiecutter/includes/.github/workflows/environments.json
- .github/workflows/deploy.yml
- .github/workflows/redeploy.yml
Link directly to QA, Prod and Canada test assignments. This is just more convenient for one-click testing.
> Improve the GitHub environment URLs

- lms/templates/admin/base.html.jinja2
- lms/templates/admin/instances.html.jinja2
- lms/templates/admin/macros.html.jinja2
- lms/templates/admin/registrations.html.jinja2
Low hanging fruit for:
- https://github.com/hypothesis/lms/issues/4724
- Navbar has a different color than the rest of the page (me being colorblind that color is not very flashy)
- Less (but probably not yet done here) white space around the page title.
- Consistency of the buttons on the search pages (both the ones at the top and at the bottom).
- Slightly smaller text size for empty organizations/registrations.
> Admin pages layout changes

- lms/models/lti_params.py
- lms/product/d2l/__init__.py
- lms/product/d2l/_plugin/misc.py
- lms/product/d2l/product.py
- lms/product/plugin/__init__.py
- lms/product/plugin/misc.py
- lms/product/plugin/plugin.py
- lms/product/product.py
- lms/services/lti_grading/_v11.py
- lms/services/lti_grading/_v13.py
- lms/services/lti_grading/factory.py
- lms/services/lti_grading/interface.py
- lms/services/ltia_http.py
- lms/templates/admin/instance.html.jinja2
- lms/views/admin/application_instance.py
- lms/views/lti/basic_launch.py
- tests/unit/lms/product/d2l/_plugin/misc_test.py
- tests/unit/lms/product/plugin/grouping_test.py
- tests/unit/lms/product/plugin/misc_test.py
- tests/unit/lms/services/lti_grading/_v13_test.py
- tests/unit/lms/services/lti_grading/factory_test.py
- tests/unit/lms/services/ltia_http_test.py
- tests/unit/lms/views/lti/basic_launch_test.py
- tests/unit/services.py
For:
- https://github.com/hypothesis/lms/issues/4699
Placeholder location for product differences until a better abstraction
is found.
The exact methods included in this first version correspond to the ones
that will be overridden by a D2L feature coming next.
No functional changes, sanity check the changes with:
- Open https://hypothesis.instructure.com/courses/319/assignments/3308 as a student to test the aud claim change.
- Create a new assignment in blackboard (`Hypothesis (localhost, make devdata)`) to exercise the post configure hook and the is_gradable method.
> New misc plugin

- lms/models/lti_role.py
Migration on: https://github.com/hypothesis/lms/pull/4737
For:
Adds a new, nullable, column to hold the scope of each role.
> Add lti_role.scope

- lms/migrations/versions/e32d2cf33591_user_email.py
- lms/models/user.py
For:
* https://github.com/hypothesis/lms/issues/4730
Migration on: https://github.com/hypothesis/lms/pull/4786
> Users new fields, model changes

- lms/services/d2l_api/client.py
- lms/views/api/d2l/files.py
- tests/unit/lms/services/d2l_api/client_test.py
- tests/unit/lms/views/api/d2l/files_test.py
For:
- #4769 
* See: https://github.com/hypothesis/lms/pull/4795
* Check out the branch from that ticket: `d2l-file-folders-frontend` which has a prototype implementation of the front end
> Expose D2L folder structure for the file picker

- lms/resources/_js_config/__init__.py
From https://github.com/hypothesis/lms/pull/4753#pullrequestreview-1240691743
In a separate PR to better keep track of it.
> Remove duplication to get auth token in JSConfig.

- lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js
This does not have user-facing or behavior changes, it just refactors a bit the `LMSFilePicker` tests so that they await on the "proper thing" (so to speak).
Some of those tests were "accidentally" passing just because there was an `await`, forcing the next tick, and consequently making some children components to be there.
However, as part of the changes in  #4853, this is not enough anymore.
Since the same pattern is present in a handful of tests, I have extracted the refactoring to a separated PR, to avoid polluting #4853, making it harder to review.
I have locally rebased that branch and it now works with these changes.
> Adjust some LMSFilePicker tests to await on components rendering when appropriate

- lms/models/application_instance.py
This isn't really about anything, I just spotted it when working on something else and it annoyed me.
> Tidy up the comment formatting in the application instance model

- lms/product/blackboard/__init__.py
- lms/product/blackboard/_plugin/course_copy.py
- lms/product/blackboard/product.py
- lms/product/plugin/__init__.py
- lms/product/plugin/course_copy.py
- lms/product/plugin/plugin.py
- lms/views/api/blackboard/files.py
- tests/unit/lms/product/blackboard/_plugin/course_copy_test.py
- tests/unit/lms/product/plugin/course_copy_test.py
- tests/unit/lms/views/api/blackboard/files_test.py
- tests/unit/services.py
See https://github.com/hypothesis/lms/pull/4880 for the blackboard implementation.
> Course copy plugin base implementation

- lms/static/scripts/frontend_apps/components/AuthButton.tsx
- lms/static/scripts/frontend_apps/components/test/AuthButton-test.js
- lms/static/scripts/frontend_apps/components/test/AuthorizationModal-test.js
Part of https://github.com/hypothesis/lms/issues/5013
This is a very simple change and doesn't have any visual changes.
> Update shared components in `AuthButton`

- lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.tsx
- lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
Part of #5013
The only component updated was `FullScreenSpinner` => `SpinnerOverlay`, which is an exact replacement (no visual changes).
> Update shared components in `BasicLTILaunchApp`; convert to TSX

- lms/static/scripts/frontend_apps/components/BookPicker.tsx
I'm creating a separate PR for this basic conversion to make the subsequent component update PR have better review ergonomics (easier to pick out component changes in the composite PR diff: yes, I know one can review commit by commit but the reviewer experience is better without having to do that, so ergo my choice for two separate PRs here).
> Convert `BookPicker` to TSX

- lms/static/scripts/frontend_apps/components/BookSelector.tsx
Converting `BookSelector` as a separate PR from its component updates for reviewer ergonomics here...
> Convert `BookSelector` to TSX

- lms/static/scripts/frontend_apps/components/ContentSelector.tsx
This is part of https://github.com/hypothesis/lms/issues/5013
> Migrate `ContentSelector` to TypeScript

- lms/static/scripts/frontend_apps/components/GroupConfigSelector.tsx
> Migrate `GroupConfigSelector` to TypeScript

- lms/templates/admin/application_instance/new.html.jinja2
- lms/templates/admin/application_instance/search.html.jinja2
- lms/templates/admin/application_instance/show.html.jinja2
- lms/templates/admin/application_instance/upgrade.html.jinja2
- lms/views/admin/application_instance.py
For:
* https://github.com/hypothesis/lms/issues/4998
> Move the application instance admin templates into their own folders

- lms/static/scripts/frontend_apps/components/FilePickerApp.tsx
- lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
Straightforward drop-in components here.
Part of #5013 
Depends on #5038
> Update shared components in `FilePickerApp`

- lms/static/scripts/frontend_apps/components/URLPicker.tsx
- lms/static/scripts/frontend_apps/components/test/URLPicker-test.js
Part of #5013 
Depends on #5048 
I can see some improvements that could be made to the UI here, but I'm holding off, as I'd like to look at them in concert with changes to the FilePickerApp itself.
No significant user-visible changes here. No behavioral changes.
> Updated shared components in `URLPicker`

- yarn.lock
We need a recent change from this package for component updates.
> Bump `@hypothesis/frontend-shared` to v5.11.0

- lms/static/scripts/frontend_apps/components/FileList.tsx
Convert `FileList` to TSX to prep for some component updates.
> Convert `FileList` to TSX

- lms/static/scripts/frontend_apps/components/ErrorDisplay.tsx
Previous step before updating shared components from pattern lib.
> Migrate ErrorDisplay component to TypeScript

- lms/app.py
- lms/views/api/exceptions.py
Compare `main` and thins branch's console output while doing:
- tox -qe dockercompose -- exec postgres psql -U postgres -c "truncate oauth2_token" to force re-auth
- Lauch anything requiring a token 
> Reduce console noise for expected OAuth2TokenError

- package.json
- yarn.lock
This ensures we get timely updates of these packages.
> Set caret ranges on a couple of frontend package dependencies

- lms/services/user.py
This is the "search style" services we've used elsewhere to good effect. This doesn't bring much benefit right now, but starts to compound into a powerful search feature as more facets are added.
> Change the user service to use an internal query builder

- lms/services/lti_grading/_v13.py
- tests/unit/lms/services/lti_grading/_v13_test.py
Addressing some issues around canvas submissions:
https://hypothes-is.slack.com/archives/C2C2U40LW/p1677008765270819
From that thread and some debugging nothing seem to be completely broken around this feature but:
- We seem to get a lot of timeouts while taking with Canvas & this feature. This PR increases the timeout of that call.
https://github.com/hypothesis/lms/pull/5102
- There's an easy to reproduce issue where the LTI1.3 API honors the "max number of submissions" that can be configured in the UI https://github.com/hypothesis/lms/issues/4973
The PR won't offer any indication to the student that they hit that limit but it seems good enough to reduce the noise around this, see for a discussion about this:
https://hypothes-is.slack.com/archives/C4K6M7P5E/p1675419187872529
We'll need …
> Handle max submissions limit in Canvas

- lms/static/scripts/ui-playground/components/ErrorComponents.tsx
This PR ensures that all variants of the `LaunchErrorDialog` component can be seen in the pattern library at http://localhost:8001/ui-playground/errors
There are still some improvements I'd like to make to this page and its infrastructure, but this is a good step in being able to easily see all permutations of this complex error component.
Partial screenshot:
> Update pattern-library docs for `LaunchErrorDialog`

- lms/services/digest.py
- tests/unit/lms/services/digest_test.py
Fixes https://github.com/hypothesis/lms/issues/5194
**Problem:** the number of DB queries done by `DigestContext.unified_users()` and `DigestContext.unified_courses()` increases rapidly with the number of instructors that we're generating digests for and with the number of annotations that users have created in those instructors' courses. We think this won't scale well as we roll out the email digests feature to more users as it'll result in far too many DB queries. See <https://github.com/hypothesis/lms/issues/5194> for more details.
**Solution:** this PR refactors `DigestContext.unified_users()` and `DigestContext.unified_courses()` to do a fixed number of larger DB queries. They now always do exactly 2 queries (one per method) regardless of the input data, although the size of both the …
> Optimize `DigestContext` DB queries

- lms/tasks/celery.py
These are all the default settings.
> Remove unnecessary exchange and queue settings

- lms/static/scripts/frontend_apps/components/AuthButton.tsx
- lms/static/scripts/frontend_apps/components/AuthorizationModal.tsx
- lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.tsx
- lms/static/scripts/frontend_apps/components/BookPicker.tsx
- lms/static/scripts/frontend_apps/components/BookSelector.tsx
- lms/static/scripts/frontend_apps/components/Breadcrumbs.tsx
- lms/static/scripts/frontend_apps/components/ChapterList.tsx
- lms/static/scripts/frontend_apps/components/ContentSelector.tsx
- lms/static/scripts/frontend_apps/components/DataLoader.tsx
- lms/static/scripts/frontend_apps/components/ErrorDialogApp.tsx
- lms/static/scripts/frontend_apps/components/ErrorDisplay.tsx
- lms/static/scripts/frontend_apps/components/ErrorModal.tsx
- lms/static/scripts/frontend_apps/components/FileList.tsx
- lms/static/scripts/frontend_apps/components/FilePickerApp.tsx
- lms/static/scripts/frontend_apps/components/GroupConfigSelector.tsx
- lms/static/scripts/frontend_apps/components/InstructorToolbar.tsx
- lms/static/scripts/frontend_apps/components/JSTORPicker.tsx
- lms/static/scripts/frontend_apps/components/LMSFilePicker.tsx
- lms/static/scripts/frontend_apps/components/LaunchErrorDialog.tsx
- lms/static/scripts/frontend_apps/components/OAuth2RedirectErrorApp.tsx
- lms/static/scripts/frontend_apps/components/StudentSelector.tsx
- lms/static/scripts/frontend_apps/components/SubmitGradeForm.tsx
- lms/static/scripts/frontend_apps/components/URLPicker.tsx
- lms/static/scripts/ui-playground/components/EditAssignment.tsx
- lms/static/scripts/ui-playground/components/ErrorComponents.tsx
- lms/static/scripts/ui-playground/components/ToolbarPage.tsx
- package.json
- yarn.lock
Bump and ensure all imports use main entry point, not `lib/next`.
Fixes https://github.com/hypothesis/frontend-shared/issues/991
> Update `frontend-shared` to v6.0.0 and update imports

- lms/tasks/celery.py
Add a comment about our usage of Celery's `broker_transport_options`.
Note that I also removed the `interval_max` option: this option is unnecessary when `max_retries` is used and has no effect.
> Add `broker_transport_options` comment

- lms/resources/_js_config/__init__.py
- lms/resources/_js_config/file_picker_config.py
- lms/services/__init__.py
- lms/services/youtube.py
- lms/static/scripts/frontend_apps/config.ts
- tests/unit/lms/resources/_js_config/file_picker_config_test.py
- tests/unit/lms/services/youtube_test.py
- tests/unit/services.py
Very basic scaffolding for the youtube service and document source that will allow both teams to work in isolation.
> Add placeholder service and filepicker options for youtube

- lms/tasks/task_done.py
- tests/unit/lms/tasks/task_done_test.py
This will be called periodically by h-periodic (see https://github.com/hypothesis/h-periodic/pull/306)
> Add a task to delete expired `task_done` rows

- lms/services/application_instance.py
- tests/unit/lms/services/application_instance_test.py
For:
- https://github.com/hypothesis/lms/issues/5367
> Enable email digest for new application instances

- lms/migrations/versions/b11713314988_email_digest_enable_01.py
First batch of 500 schools that have at last one active instructor.
This will enable it for the following AIs:
https://metabase.hypothes.is/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiJzZWxlY3QgYXBwbGljYXRpb25faW5zdGFuY2VfaWQsIGNvdW50KFwidXNlclwiLmlkKSAgZnJvbSBhc3NpZ25tZW50X21lbWJlcnNoaXBcbmpvaW4gXCJ1c2VyXCIgb24gXCJ1c2VyXCIuaWQgPSBhc3NpZ25tZW50X21lbWJlcnNoaXAudXNlcl9pZFxuam9pbiBsdGlfcm9sZSBvbiBsdGlfcm9sZS5pZCA9IGx0aV9yb2xlX2lkXG5qb2luIGFwcGxpY2F0aW9uX2luc3RhbmNlcyBvbiBhcHBsaWNhdGlvbl9pbnN0YW5jZV9pZCA9IGFwcGxpY2F0aW9uX2luc3RhbmNlcy5pZFxud2hlcmUgXG4gICAgdHlwZSA9J2luc3RydWN0b3InIGFuZCBzY29wZSA9ICdjb3Vyc2UnXG4gICAgYW5kIGxhc3RfbGF1bmNoZWQgPj0gJzIwMjMtMDEtMDEnXG4gICAgYW5kIGNvYWxlc2NlKHNldHRpbmdzLT4naHlwb3RoZXNpcyctPj4naW5zdHJ1Y3Rvcl9lbWFpbF9kaWdlc3RzX2VuYWJsZWQ …
> Migration to enable email digest to existing AIs

- lms/services/digest.py
- tests/unit/lms/services/digest_test.py
`DigestService.send_instructor_email_digests()` is careful to collect
any errors raised when calling `send_template.delay()` into a
`SendDigestsError` and raise it, but as of
https://github.com/hypothesis/lms/pull/5351 the
`send_instructor_email_digests()` task (which calls
`DigestService.send_instructor_email_digests()`) no longer catches these
`SendDigestsError`'s, so simplify `DigestService` by removing this error
handling.
This does mean that if any one of `DigestService`'s calls to
`send_template.delay()` raises then the whole task will fail and break
out of the `for` loop skipping any remaining calls to
`send_template.delay()` that were still to be made. But Celery will
retry the task which will re-start the `for` loop from the start and
hopefully on the second or third attempt it …
> Remove unnecessary `send_instructor_email_digests()` error handling

- lms/tasks/email_digests.py
Instead of joining every row with EmailUnsubscribe and the discarding not null ones use a `not in` query against a subquery for EmailUnsubscribe.
There's an index on (h_userid", tag) so the subquery should be fairly quick.
Check the relative performance [in metabase](https://metabase.hypothes.is/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiJzZWxlY3QgZGlzdGluY3QgXCJ1c2VyXCIuaF91c2VyaWQsIGVtYWlsX3Vuc3Vic2NyaWJlLmlkIGZyb20gXCJ1c2VyXCJcbmpvaW4gYXBwbGljYXRpb25faW5zdGFuY2VzIG9uIFwidXNlclwiLmFwcGxpY2F0aW9uX2luc3RhbmNlX2lkID0gYXBwbGljYXRpb25faW5zdGFuY2VzLmlkXG5qb2luIGFzc2lnbm1lbnRfbWVtYmVyc2hpcCBvbiBcInVzZXJcIi5pZCA9IGFzc2lnbm1lbnRfbWVtYmVyc2hpcC51c2VyX2lkXG5qb2luIGx0aV9yb2xlIG9uIGx0aV9yb2xlLmlkPSBhc3NpZ25tZW50X21lbWJlcnNoaXAubHRpX3JvbGVfaWRcbndoZXJlIHNldHRpbmdzLT …
> Improve performance of email digest query for unsubscribes

- lms/migrations/versions/3a786e91f59c_email_digest_enable_04.py
Final batch to enable email digest in all AIs.
[There are only 29 AI's remanding with activity from instructors](https://metabase.hypothes.is/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiJTRUxFQ1QgZGlzdGluY3QgYXBwbGljYXRpb25faW5zdGFuY2VfaWQsIGNvdW50KFwidXNlclwiLmlkKVxuICAgIEZST00gYXNzaWdubWVudF9tZW1iZXJzaGlwXG4gICAgSk9JTiBcInVzZXJcIiBPTiBcInVzZXJcIi5pZCA9IGFzc2lnbm1lbnRfbWVtYmVyc2hpcC51c2VyX2lkXG4gICAgSk9JTiBsdGlfcm9sZSBPTiBsdGlfcm9sZS5pZCA9IGx0aV9yb2xlX2lkXG4gICAgSk9JTiBhcHBsaWNhdGlvbl9pbnN0YW5jZXMgT04gYXBwbGljYXRpb25faW5zdGFuY2VfaWQgPSBhcHBsaWNhdGlvbl9pbnN0YW5jZXMuaWRcbiAgICBXSEVSRVxuICAgICAgICAtLSBUZWFjaGVyc1xuICAgICAgICB0eXBlID0naW5zdHJ1Y3RvcicgQU5EIHNjb3BlID0gJ2NvdXJzZSdcbiAgICAgICAgLS0gQUlzIHdpdGggc29tZSByZWNlbnQgYWN0aXZpdHlcbiAgICAgICAgQU5EIGxhc3Rfb …
> Migration to enable email digest to existing AIs (04)

- lms/data_tasks/report/create_from_scratch/02_entities/04_assignments/01_create_view.sql
- lms/data_tasks/report/create_from_scratch/02_entities/04_assignments/02_initial_fill.sql
- lms/data_tasks/report/create_from_scratch/03_cross_reference/05_organization_assignments/01_create_view.sql
- lms/data_tasks/report/create_from_scratch/03_cross_reference/05_organization_assignments/02_initial_fill.sql
- lms/data_tasks/report/create_from_scratch/99_grant_permissions/01_grant_schema.jinja2.sql
- lms/data_tasks/report/refresh/01_entities_refresh.sql
- lms/data_tasks/report/refresh/02_cross_reference_refresh.sql
For: 
* https://github.com/hypothesis/report/issues/230
The intention here is to allow ourselves to remix these into views we can use in Report to give summaries of the different assignments types in an organization.
> Add a slightly sanitized view of assignments

- lms/db/__init__.py
- lms/services/course.py
- lms/views/status.py
- tests/functional/conftest.py
- tests/unit/lms/data_tasks/report/create_from_scratch/test_01_functions/test_01_date_functions.py
- tests/unit/lms/services/course_test.py
- tests/unit/lms/services/user_test.py
Extracted the lowest hanging fruit type changes from https://github.com/hypothesis/lms/pull/5283 to make that other PR smaller.  
This is probably easier to review looking at the individual commits.
> Misc SQLA 2.0 compatibility issues fixes

- lms/data_tasks/report/create_from_scratch/00_schema/03_create_fdw_schema.sql
- lms/data_tasks/report/create_from_scratch/02_entities/01_users/01_raw_users/01_create_view.jinja2.sql
- lms/data_tasks/report/create_from_scratch/02_entities/02_groups/01_raw_groups/01_create_view.jinja2.sql
- lms/data_tasks/report/create_from_scratch/03_cross_reference/01_user_groups/01_create_view.jinja2.sql
- lms/data_tasks/report/create_from_scratch/98_proxies/01_organizations.sql
- lms/data_tasks/report/create_from_scratch/98_proxies/README.md
- lms/data_tasks/report/create_from_scratch/99_grant_permissions/01_grant_schema.jinja2.sql
For:
* https://github.com/hypothesis/report/issues/255
This is intended to provide a more controlled interface with H and Reporting
> Use proxies from H and export our own from Reporting

- lms/data_tasks/report/create_from_scratch/02_entities/03_events/01_create_view.sql
To support https://github.com/hypothesis/lms/pull/5537
> Update reporting with the new "grade" event type

- lms/data_tasks/report/create_from_scratch/99_grant_permissions/01_grant_schema.jinja2.sql
For:
* https://github.com/hypothesis/report/issues/255
We shouldn't need this any more.
> Stop granting direct permissions to tables for reporting

- lms/data_tasks/report/create_from_scratch/99_grant_permissions/01_grant_schema.jinja2.sql
For:
* https://github.com/hypothesis/report/issues/255
Once these permissions are revoked once, there's nothing more to do
> Once permissions are revoked once, we are done

- lms/views/lti/deep_linking.py
- tests/unit/lms/views/lti/deep_linking_test.py
Forward the value in deep linking responses.
For:
- https://github.com/hypothesis/lms/issues/5544
- Check nothing has changed over the Canvas side, re-configure:
https://hypothesis.instructure.com/courses/125/assignments/4682/edit?name=Testing+creation+-+marcos&due_at=null&points_possible=0
- In D2L, create an assignment with deep linking (Existing activities -> Hypothesis link (deep linking). Pick D2L files.
https://aunltd.brightspacedemo.com/d2l/le/content/6782/Home 
It won't have a title (defaults to the launch URL).
- Create another one, Pick D2L files. This time make a code change similar to:
```diff
diff --git a/lms/views/lti/deep_linking.py b/lms/views/lti/deep_linking.py
index dfac0878f..ca3f915e8 100644
--- a/lms/views/lti/deep_linking.py
+++ b/lms/views/lti/deep_linking.py
@@ …
```
> Add an optional title option for assignment configuration

- tests/functional/lti_certification/v13/grading/test_assignment_and_grading.py
For:
- https://github.com/hypothesis/product-backlog/issues/1515
This is not a very satisfying approach but the whole certification process is a bit wonky.
---
Our grading service has changed leaving the example script out of date.
Modify the script to be up to date with the current codebase.
> Adapt example script for LTI certification to code changes

- lms/product/blackboard/__init__.py
- lms/product/blackboard/_plugin/misc.py
- lms/product/blackboard/product.py
- lms/product/plugin/misc.py
- lms/resources/_js_config/__init__.py
- lms/services/lti_grading/_v11.py
- lms/services/lti_grading/_v13.py
- lms/services/lti_grading/interface.py
- lms/static/scripts/frontend_apps/config.ts
- lms/views/api/grading.py
- tests/unit/lms/product/blackboard/_plugin/misc_test.py
- tests/unit/lms/product/plugin/misc_test.py
- tests/unit/lms/resources/_js_config/__init___test.py
- tests/unit/lms/services/lti_grading/_v11_test.py
- tests/unit/lms/services/lti_grading/_v13_test.py
- tests/unit/lms/views/api/grading_test.py
As a sanity check I've tested reading a grade from the following assignments:
[D2L LTI1.3](https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/3348/View)
[D2L LTI1.1](https://aunltd.brightspacedemo.com/d2l/le/content/6782/viewContent/3350/View)
[Moodle LTI1.1](https://hypothesisuniversity.moodlecloud.com/mod/lti/view.php?id=110)
[Moodle LTI1.3](https://hypothesisuniversity.moodlecloud.com/mod/lti/view.php?id=685
)[Blackboard LTI1.1](https://aunltd-test.blackboard.com/webapps/blackboard/execute/blti/launchPlacement?blti_placement_id=_20_1&content_id=_36_1&course_id=_19_1)
[Blackboard LTI1.1](https://aunltd-test.blackboard.com/webapps/blackboard/content/contentWrapper.jsp?content_id=_2085_1&displayName=localhost+PDF+-+LTI1.3&course_id=_19_1&navItem=content&href=%2Fwebapps%2Fbl …
> Return comments associated with a grade

- lms/events/event.py
- lms/models/application_instance.py
- lms/services/application_instance.py
- lms/services/file.py
- lms/services/lti_user.py
- lms/services/ltia_http.py
- lms/services/youtube.py
- pyproject.toml
- requirements/lint.in
- requirements/lint.txt
- tests/pyproject.toml
This should fix the long build times spent on pylint.
> Upgrade pylint to latest pre-release version

- lms/tasks/mailchimp.py
> Remove a print statement

- lms/static/scripts/frontend_apps/utils/test/use-warn-on-page-unload-test.js
Address improvements suggested in https://github.com/hypothesis/lms/pull/5674#discussion_r1318240639
Closes #5687
> Make useWarnOnPageUnload test more resilient by dispatching actual events

- lms/models/application_instance.py
- lms/product/plugin/misc.py
- lms/templates/admin/application_instance/show.html.jinja2
- tests/unit/lms/product/plugin/misc_test.py
To allow merging the comment related code without releasing it to customers yet.
> Add AI setting to feature flag grading comments

- lms/services/d2l_api/client.py
- tests/unit/lms/services/d2l_api/client_test.py
Based on:
https://hypothes-is.slack.com/archives/C2BLQDKHA/p1694465944144089
Searching the LMS's logs for `830497/content/toc` I could find the instances of Null  values for URL, those also had `IsBroken` = True.
D2L identifies topics as `IsBroken`, for these we:
- Allow them to have a nullable URL. Allowing the rest of the response to be validated
- Ignore them, don't try to show them in the final list of files
See https://docs.valence.desire2learn.com/res/content.html#ToC.TableOfContents for docs on the return values.
I don't know how to reproduce having a file with `IsBroken` in D2L. I've  tried a few things (more promising adding file to the table of contents but deleting it from the "course storage", no luck).
Testing just the basics here still work as expected:
- As a teacher list …
> Filter topics marked as broken by D2L

- lms/models/application_instance.py
- lms/templates/admin/application_instance/show.html.jinja2
For:
- [Support canvas pages as a document source](https://github.com/hypothesis/lms/issues/5713)
> New setting to control the pages feature

- lms/resources/_js_config/__init__.py
- lms/routes.py
- lms/security.py
- lms/services/canvas_api/_pages.py
- lms/views/api/canvas/authorize.py
- lms/views/api/canvas/pages.py
- tests/unit/lms/resources/_js_config/__init___test.py
- tests/unit/lms/services/canvas_api/_pages_test.py
- tests/unit/lms/views/api/canvas/pages_test.py
- Launch https://hypothesis.instructure.com/courses/125/assignments/5142
- The returned HTML matches the contents of https://hypothesis.instructure.com/courses/125/pages/test-page with the caveats in https://github.com/hypothesis/lms/pull/5738#discussion_r1342585938
> Proxy the contents of Canvas pages from LMS

- .cookiecutter/cookiecutter.json
- .github/workflows/ci.yml
I think 64 cores is costing us too much.
> Downgrade to 32 cores for tests and lint

- .github/workflows/report_refresh.yml
- Old time: 1530 UTC
- New time: 0530 UTC
> Changed daily schedule: Report Refresh

- lms/services/jwt.py
- tests/unit/lms/services/jwt_test.py
This reverts commit 2de109d096c1af6c660d99b79908baaea462ea52.
> Revert "Add new method to encrypt dicts as JWEs"

- lms/templates/admin/application_instance/show.html.jinja2
- lms/templates/admin/base.html.jinja2
Explicitly adding a title for the page with the problem.
Also, striping HTML when defaulting to the whole header block, it might not be the ideal title but it won't be as broken.
> Set a title on the AI detail admin page

- lms/services/digest.py
- lms/services/h_api.py
- lms/tasks/email_digests.py
- tests/unit/lms/services/digest_test.py
- tests/unit/lms/services/h_api_test.py
- tests/unit/lms/tasks/email_digests_test.py
**This needs to be deployed together with the H side.**
See https://github.com/hypothesis/h/pull/8268
> Use created instead of updated in the bulk annotation

- lms/static/scripts/frontend_apps/components/OAuth2RedirectErrorApp.tsx
Tested by manually editing the padding to an equivalent value (2rem) on this test assignment: https://hypothesis.instructure.com/courses/121/assignments/852.
Fixes https://github.com/hypothesis/lms/issues/5785
> Allow space for >= 10 items in required scopes list

- lms/services/digest.py
- tests/unit/lms/services/digest_test.py
Add a local `Annotation` model to `DigestService` to represent the
annotations that it retrieves from h's bulk API.
Problem
-------
Annotation dicts directly from h's bulk annotation API are currently
passed throughout `digest.py`'s code. This results in lots of ugly dict
accesses like this:
annotation["author"]["userid"]
annotation["group"]["authority_provided_id"]
It also means that knowledge of the structure of the annotation dicts
returned by h's bulk annotation API is spread throughout `digest.py`
instead of kept together in one place.
Both problems will get worse as we start adding more data to these
annotation dicts (see https://github.com/hypothesis/lms/pull/5755).
Solution
--------
Add a local `Annotation` model to `DigestService` and convert all the
annotations to it. Fields can …
> Add annotation model to `DigestService`

- package.json
- yarn.lock
This contains some DataTable improvements which will be needed soon for the VS picker.
> Update @hypothesis/frontend-shared to v6.12.0

- lms/routes.py
- lms/templates/admin/application_instance/show.html.jinja2
- lms/views/admin/application_instance/update.py
- tests/unit/lms/views/admin/application_instance/update_test.py
This matches the UI and makes for a smaller, more focused view.
- General values 
Go to http://localhost:8001/admin/instance/8/
Update any values over the info tab, click save and check the values are indeed updated.
- Settings
Again in  http://localhost:8001/admin/instance/8/
Update any settings and click save at the bottom. The settings are updated.
> Use a separate endpoint for AI settings

- lms/models/__init__.py
- lms/models/user_preferences.py
Depends on <https://github.com/hypothesis/lms/pull/5833>
> Add the `UserPreferences` model

- lms/models/task_done.py
Depends on <https://github.com/hypothesis/lms/pull/5856>
> Add the `task_done.data` column

- docs/configuration.md
> Document the new ADMIN_USERS env variable

- lms/static/scripts/frontend_apps/components/ContentSelector.tsx
- lms/static/scripts/frontend_apps/components/ErrorModal.tsx
- lms/static/scripts/frontend_apps/components/OAuth2RedirectErrorApp.tsx
- lms/static/scripts/frontend_apps/components/StudentSelector.tsx
- lms/static/styles/_base.scss
- package.json
- yarn.lock
Update to frontend-shared 7, and remove the rounded corners config, as that is now the default.
> Update to frontend-shared 7.0.1

- lms/db/__init__.py
- lms/services/group_info.py
- tests/unit/lms/db/__init___test.py
Remove the last usage of BASE.update_from_dict and delete the method.
> Explicitly list of GroupInfo fields being updated.

- lms/security.py
- tests/unit/lms/security_test.py
Fixes https://github.com/hypothesis/lms/issues/5914
> Don't crash if there's no email preferences cookie

- lms/models/application_instance.py
- lms/templates/admin/application_instance/show.html.jinja2
- lms/views/lti/basic_launch.py
- tests/unit/lms/views/lti/basic_launch_test.py
This flag has now been enabled in the client for all users.
> Remove LMS import/export feature flag

- lms/services/vitalsource/_client.py
Added extra logging for failed credentials calls.
Could be useful for debugging some issues around here.
> Add extra logging around VS credentials call

- lms/app.py
- lms/models/region.py
- tests/unit/lms/models/region_test.py
> Remove `request.region`

- bin/run_data_task.py
- lms/app.py
- lms/models/__init__.py
- lms/models/_mixins/public_id.py
- lms/models/public_id.py
- lms/models/region.py
- lms/services/__init__.py
- lms/services/region.py
- tests/conftest.py
- tests/unit/conftest.py
- tests/unit/lms/app_test.py
- tests/unit/lms/models/public_id_test.py
- tests/unit/lms/models/region_test.py
- tests/unit/lms/services/region_service_test.py
This method isn't really doing anything but a dict lookup. It works
better as a `__post_init__()` on the dataclass.
> Remove `Regions.from_code()`

- lms/static/scripts/frontend_apps/components/FilePickerApp.tsx
- lms/static/scripts/frontend_apps/components/InstructorToolbar.tsx
- lms/static/scripts/frontend_apps/components/LaunchErrorDialog.tsx
- package.json
- yarn.lock
> Update to wouter-preact 3.0

- lms/resources/_js_config/__init__.py
- lms/routes.py
- lms/services/moodle.py
- lms/views/api/moodle/files.py
- lms/views/helpers/_via.py
- requirements/bddtests.txt
- requirements/dev.txt
- requirements/functests.txt
- requirements/lint.txt
- requirements/prod.txt
- requirements/tests.txt
- requirements/typecheck.txt
- tests/unit/lms/resources/_js_config/__init___test.py
- tests/unit/lms/views/api/moodle/files_test.py
- As `moodleteacher` launch [Existing Moodle File](https://hypothesisuniversity.moodlecloud.com/mod/lti/view.php?id=863)
- The Moodle files is proxied and displayed.
> Proxy Moodle files using Via

- lms/resources/_js_config/__init__.py
- lms/resources/_js_config/file_picker_config.py
- lms/routes.py
- lms/security.py
- lms/services/moodle.py
- lms/static/scripts/frontend_apps/components/ContentSelector.tsx
- lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js
- lms/static/scripts/frontend_apps/config.ts
- lms/templates/api/moodle/page.html.jinja2
- lms/views/api/moodle/pages.py
- tests/unit/lms/resources/_js_config/__init___test.py
- tests/unit/lms/resources/_js_config/file_picker_config_test.py
- tests/unit/lms/services/moodle_test.py
- tests/unit/lms/views/api/moodle/pages_test.py
- As `moodleteacher` go to [Moodle assignment](https://hypothesisuniversity.moodlecloud.com/course/modedit.php?update=865&return=1
) an "Select Content"
- Select Moodle Pages, pick one.
- Launch again, get the content of the page as the assignment content.
> Basic support for Moodle pages

- lms/views/api/exceptions.py
- lms/views/exceptions.py
Error was causing these to show up in sentry causing a lot of noise.
> Change log level for 404 to info.

- lms/views/api/moodle/files.py
- lms/views/api/moodle/pages.py
- tests/unit/lms/views/api/moodle/files_test.py
- tests/unit/lms/views/api/moodle/pages_test.py
Move the course copy logic to a private function.
> Refactor Moodle page and files views to improve readability

- lms/models/grouping.py
- lms/routes.py
- lms/services/assignment.py
- lms/templates/admin/assignment/show.html.jinja2
- lms/templates/admin/course/show.html.jinja2
- lms/templates/admin/macros.html.jinja2
- lms/views/admin/assignment.py
- tests/unit/lms/services/assignment_test.py
- tests/unit/lms/views/admin/assignment_test.py
- tests/unit/lms/views/admin/course_test.py
Similar to courses very, basic listing of assignments in the admin pages.
Go to the admin pages -> course -> search -> view any of the courses. There's a now a list of assignments per course + you can view the details page.
> Basic listing of course's assignments in the admin pages

- lms/migrations/versions/7ef5569fca11_assignment_deep_linking_uuid.py
Autogenerated from https://github.com/hypothesis/lms/pull/6114
> Migration for assignment.deep_linking_id

- lms/templates/admin/application_instance/show.html.jinja2
We have quite a few switched for VS, creating its own section.
> Create VS section in the settings page

- lms/static/scripts/frontend_apps/components/ContentSelector.tsx
- lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js
~~Needs https://github.com/hypothesis/lms/pull/6133 to remove Canvas special behaviour.~~
Use display_name in all sources that provide it. Small refactor around this.
> Content selector refactor

- lms/static/scripts/frontend_apps/components/LaunchErrorDialog.tsx
> Link to KB article on moodle related error dialogs

- lms/security.py
- lms/validation/authentication/_bearer_token.py
- lms/views/dashboard.py
- tests/unit/lms/security_test.py
- tests/unit/lms/validation/authentication/_bearer_token_test.py
- tests/unit/lms/views/dashboard_test.py
Follow the notes over: https://github.com/hypothesis/lms/pull/6177
> Set and read LTIUser from cookies for dashboards

- lms/services/assignment.py
- lms/views/dashboard.py
- tests/unit/lms/services/assignment_test.py
- tests/unit/lms/views/dashboard_test.py
This PR:
- Checks that the requested assignment exists
- Checks that the current user does indeed have access to the requested assignment
- Extends the duration of the cookie in each new request.
It doesn't:
- Expose 404 / 403 in a nice way to the frontend to be handled nicely.
> Dashboard authorization

- package.json
- yarn.lock
This fixes an issue with table headers mentioned in https://github.com/hypothesis/lms/pull/6187.
> Bump @hypothesis/frontend-shared

- lms/static/scripts/frontend_apps/components/ErrorDialogApp.tsx
- lms/static/scripts/frontend_apps/components/test/ErrorDialogApp-test.js
From: https://hypothes-is.slack.com/archives/C2C2U40LW/p1713971849772839?thread_ts=1713560092.698679&cid=C2C2U40LW
> Improve  wording for the license activate modal

- lms/static/scripts/frontend_apps/components/dashboard/StudentsActivityTable.tsx
Remove some classes being set to all students table header cells but the first one, which were actually not having any effect.
> Remove unused classes from students table header

- .cookiecutter/includes/requirements/prod.in
- lms/services/rsa_key.py
- requirements/bddtests.txt
- requirements/dev.txt
- requirements/functests.txt
- requirements/lint.txt
- requirements/prod.in
- requirements/prod.txt
- requirements/tests.txt
- requirements/typecheck.in
- requirements/typecheck.txt
- tests/unit/lms/services/rsa_key_service_test.py
For:
- https://github.com/hypothesis/lms/issues/3922
Added a test on the first commit that asserts exact outputs instead of method calls.
> Remove direct python-jose dependency

- requirements/bddtests.txt
- requirements/dev.txt
- requirements/functests.txt
- requirements/lint.txt
- requirements/prod.txt
- requirements/tests.txt
- requirements/typecheck.txt
For:
- https://github.com/hypothesis/lms/issues/3922
> Upgrade h-vialib

- pyproject.toml
- requirements/lint.in
- requirements/lint.txt
- tox.ini
Another small-ish PR to introduce ruff, now to replace pydocstyle & pycodestyle
> Replace pydocstyle & pycodestyle with ruff

- lms/services/organization.py
- lms/services/user.py
- tests/unit/lms/services/user_test.py
~~Pending decision over: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1712927515721779~~
Decision meade, let's store them, we already have them in the H side anyway.
> Store student names in the DB

- lms/models/_mixins/public_id.py
- lms/models/application_instance.py
- lms/models/assignment.py
- lms/models/course.py
- lms/models/event.py
- lms/models/group_info.py
- lms/models/grouping.py
- lms/models/lti_role.py
- lms/models/organization.py
- lms/models/user_preferences.py
- lms/services/h_api.py
- lms/services/lti_grading/interface.py
- lms/services/lti_user.py
- lms/services/organization.py
- lms/services/vitalsource/service.py
- pyproject.toml
Type fixes and a few type ignores to remove another of the ignored rules from mypy's config.
> Fix all mypy `arg-type` errors in the codebase

- lms/models/assignment.py
- lms/templates/admin/assignment/show.html.jinja2
- lms/templates/admin/course/search.html.jinja2
- lms/templates/admin/macros.html.jinja2
- tests/unit/lms/models/assignment_test.py
Useful while navigating directly to an assignment, as a way to going to the course.
> Expose the course an assignment belongs to in the admin pages

- lms/js_config_types.py
- lms/models/grouping.py
- lms/resources/_js_config/__init__.py
- lms/routes.py
- lms/services/course.py
- lms/views/admin/course.py
- lms/views/dashboard/api/course.py
- lms/views/dashboard/base.py
- tests/unit/lms/resources/_js_config/__init___test.py
- tests/unit/lms/services/course_test.py
- tests/unit/lms/views/admin/course_test.py
- tests/unit/lms/views/dashboard/api/course_test.py
- tests/unit/lms/views/dashboard/base_test.py
- Find a course ID (ie in the admin pages, in the debug info after a launch)
- Make sure you have a google oauth token (ie open anything in the admin pages)
- Open http://localhost:8001/dashboard/api/course/YOURID
> Course dashboards first API building blocks

- lms/static/scripts/frontend_apps/components/ErrorDialogApp.tsx
- lms/static/scripts/frontend_apps/components/test/ErrorDialogApp-test.js
See https://hypothes-is.slack.com/archives/C2C2U40LW/p1715362133151509?thread_ts=1715109997.548269&cid=C2C2U40LW for the wording.
> Change wording of vital source license launch for instructors

- lms/migrations/versions/329313b38de1_hubspot_company.py
See: https://github.com/hypothesis/lms/pull/6293
```
INFO  [alembic.runtime.migration] Running upgrade 7ef5569fca11 -> 329313b38de1, Create hubspot_company table.
```
> Migration for HubSpotCompany

- .cookiecutter/cookiecutter.json
- .cookiecutter/includes/.github/workflows/ci.yml
- .cookiecutter/includes/docker-compose/services.yml
- .cookiecutter/includes/requirements/typecheck.in
- .github/workflows/ci.yml
- Makefile
- lms/pshell.py
- lms/services/hubspot/service.py
- lms/services/lti_role_service.py
See:
https://github.com/hypothesis/cookiecutters/pull/171
> Run mypy as part of make sure and in CI

- lms/routes.py
- lms/templates/admin/course/show.html.jinja2
- lms/views/admin/course.py
- tests/unit/lms/views/admin/course_test.py
Search for courses in:
http://localhost:8001/admin/courses
> Allow direct access to course level dashboard from the admin pages

- lms/services/canvas_api/_authenticated.py
- tests/unit/lms/services/canvas_api/_authenticated_test.py
The Canvas integration does not use `OAuthHTTPService` so concurrent refresh prevention has to be implemented separately. Fortunately this is pretty simple.
This is a counterpart to https://github.com/hypothesis/lms/pull/6323. Eventually we'd like to change the Canvas implementation to share more code with the other integrations. In the meantime this small change aligns the behavior, which will make changing Canvas to use `OAuthHTTPService` in future a smaller change.
> Prevent concurrent OAuth token refreshes in Canvas

- lms/js_config_types.py
- lms/services/course.py
- lms/views/dashboard/api/course.py
- tests/unit/lms/services/course_test.py
- tests/unit/lms/views/dashboard/api/course_test.py
Include count of assignments per course and the last time the course
itself was launched.
- Go to a URL like:
http://localhost:8001/dashboard/organizations/local.lms.org.LDtcl7EUTeW2UERPJLAVtA
Inspect the response from the BE contains the new data points.
> Expose basic metrics about courses

- lms/services/canvas_studio.py
- tests/unit/lms/services/canvas_studio_test.py
Lists of collections and media are paginated, using offset-based pagination. Fetch all of pages, up to a limit, instead of just the first one. Also increase the size for each page from 20 items up to the maximum of 50.
Fixes https://github.com/hypothesis/lms/issues/6354
> Fetch all pages of paginated Canvas Studio API responses

- lms/models/organization_usage.py
- lms/services/organization_usage_report.py
- tests/unit/lms/services/organization_usage_report_test.py
See: https://github.com/hypothesis/lms/pull/6375
> Calculate number of unique teachers for usage reports

- lms/js_config_types.py
- lms/resources/_js_config/__init__.py
- tests/unit/conftest.py
- tests/unit/lms/resources/_js_config/__init___test.py
- tests/unit/lms/views/lti/basic_launch_test.py
This would be the google email address used to log in the admin pages
Launch the dashboards both as and admin and a LTIUser.
> Expose display name for staff users

- lms/views/dashboard/api/assignment.py
To help debug issues in the staging environment.
See: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1718966529889749
> Include extra logging for assignments stats

- lms/services/assignment.py
- lms/views/dashboard/api/assignment.py
- tests/unit/lms/services/assignment_test.py
- tests/unit/lms/views/dashboard/api/assignment_test.py
For:
- https://github.com/hypothesis/lms/issues/6393
> Include option to filter by course_id in the assignments endpoint

- lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx
- lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js
- lms/views/dashboard/api/user.py
Add FE changes required for https://github.com/hypothesis/lms/pull/6419
> Pass assignment_id in query when loading dashboard students

- lms/static/scripts/tsconfig.json
- package.json
Update the baseline to match https://github.com/hypothesis/client/pull/6438.
> Update supported browsers

- lms/services/course.py
- lms/views/dashboard/api/assignment.py
- tests/unit/lms/services/course_test.py
- tests/unit/lms/views/dashboard/api/assignment_test.py
This was the only call to the method, removing it.
Similar to the change done for assignments in: 886d271337d81c9353f0d975d426b8258c12bfb7
- Sanity check all three levels of the dashboards
> Replace CourseService.get_members by UserService.get_users

- lms/views/dashboard/api/course.py
- tests/unit/lms/views/dashboard/api/course_test.py
For:
- https://github.com/hypothesis/lms/issues/6418
> Filter course metrics by course IDs

- lms/services/assignment.py
- lms/views/dashboard/api/assignment.py
- tests/unit/lms/services/assignment_test.py
- tests/unit/lms/views/dashboard/api/assignment_test.py
For:
- https://github.com/hypothesis/lms/issues/6418
- Play with the API at something like: 
http://localhost:8001/api/dashboard/courses/1826/assignments/metrics?h_userids=acct:f6c3ed0edd8a4013bfc8d0c22b9eca@lms.hypothes.is
> Filter assignment metrics by users

- lms/views/dashboard/api/assignment.py
- tests/unit/lms/services/assignment_test.py
- tests/unit/lms/views/dashboard/api/assignment_test.py
For:
- https://github.com/hypothesis/lms/issues/6418
Play with the filters in something like:
http://localhost:8001/api/dashboard/courses/1826/assignments/metrics?assignment_id=352&assignment_id=353&h_userid=acct:9ea84c4bcfd9329b4495f5b27d8cb6@lms.hypothes.is&h_userid=acct:f6c3ed0edd8a4013bfc8d0c22b9eca@lms.hypothes.is
> Filter assignment metrics by assignment IDs and user h_userid

- lms/services/user.py
- lms/views/dashboard/api/assignment.py
- lms/views/dashboard/api/user.py
- tests/unit/lms/services/user_test.py
- tests/unit/lms/views/dashboard/api/assignment_test.py
- tests/unit/lms/views/dashboard/api/user_test.py
(these IDs are environment dependent)
Basic sanity check:
- Filter by assignment ID
http://localhost:8001/api/dashboard/students?assignment_id=398
- Filter by course ID
http://localhost:8001/api/dashboard/students?course_id=1830
> Include missing filters on the users API

- lms/services/assignment.py
- lms/views/dashboard/api/assignment.py
- tests/unit/lms/services/assignment_test.py
- tests/unit/lms/views/dashboard/api/assignment_test.py
(these IDs are environment dependent)
Basic sanity check:
- Filter by user ID
http://localhost:8001/api/dashboard/assignments?h_userid=acct:f6c3ed0edd8a4013bfc8d0c22b9eca@lms.hypothes.is
- Filter by course ID
http://localhost:8001/api/dashboard/assignments?course_id=1830
> Add filters to the assignments API

- lms/services/dashboard.py
- tests/unit/lms/services/dashboard_test.py
This is the last part needed for: 
- https://github.com/hypothesis/lms/issues/6480 
and also needed for: 
- https://github.com/hypothesis/lms/issues/6378
Grant not only access to one organization but all its children
- Create a new organization http://localhost:8001/admin/org/new
- Assign your local "University of hypothesis" to that new org (make it a child)
- (In `main`) Access the staff dashboard from the new organization, you'll get an empty dashboard as there no activity on that organization.
- Switch to `admin-child-organizations` you'll get now all the activity from the children org.
> Take into consideration child organizations for dashboard admins

- lms/models/assignment.py
Adds a new FK pointing to the course this assignment belongs to. 
Migration over:
- https://github.com/hypothesis/lms/pull/6519
> Assignment.course_id column model changes

- lms/security.py
- tests/unit/lms/security_test.py
Currently our security policy applies one sub policy based on an URL path. It applies it regardless of the result, if the path matches, the security policy is used even if it returns an empty identity.
This is general the right approach as our endpoints almost always expect to be authenticated in only one way.
However for the dashboard API endpoints we want to first try the LMS authorization and if that doesn't succeed try the google authentication for staff members.
We could generalize this behaviour and apply a list of policies (usually of one element) until one succeeds for all paths. We'll leave that for a follow up PR if this is necessary in more scenarios.
- Open the dashboard from the admin pages, as a staff member
Navigate around, you should see data in all levels
You should be …
> Apply security policies for /api/dashboard endpoints in a defined order

- lms/services/assignment.py
- tests/unit/lms/services/assignment_test.py
We no longer have to de-duplicate AssignmentGrouping as this is now denormalized in Assignment.course_id
Based on that we can simplify queries on AssignmentService.
Enabled by: https://github.com/hypothesis/lms/pull/6528
There shouldn't not be any behaviour changes in this PR, sanity check the dashboard access all three levels.
> Simplify assignment queries to use assignment.course_id

- lms/services/user.py
For:
---
- Avoid unnecessary join with lti_role
LTIRole is a small table, make a subquery instead of a join to speed up the main query.
- Avoid multiple join/subquery of assignment_membership
To filter by role, course and assignments we potentially join/query assignment_membership once per filter. Use just one subquery with the necessary clauses to filter by those instead.
This speeds up the main query and also makes it easier to read.
> Avoid unnecessary joins for assignment_membership and lti_roles in get_users

- lms/services/user.py
Method local refactor, no test needs updating, no behaviour changes.
> Refactor get_user to be more explicit about the upsert logic

- lms/models/application_instance.py
- lms/models/legacy_course.py
These is just adding noise and potential confusion
> Remove unused relationship with LegacyCourse

- lms/services/course.py
- lms/services/user.py
- tests/unit/lms/services/course_test.py
- tests/unit/lms/services/user_test.py
Reverts hypothesis/lms#6576
Causing:https://hypothesis.sentry.io/issues/5746458492/?alert_rule_id=4849653&alert_type=issue&notification_uuid=f638f0b5-220a-4870-b1ff-9a38c0b4b1ef&project=259908&referrer=slack
> Revert "Upsert rows in LMSCourse and LMSUser "

- lms/migrations/versions/b97080de93bc_add_lmscourse_lti_context_memberships_.py
For:
Auto Generated from:
- https://github.com/hypothesis/lms/pull/6602
```
tox -e dev --run-command 'alembic upgrade head'  
dev run-test-pre: PYTHONHASHSEED='1387389707'                                                  dev run-test-pre: commands[0] | pip-sync-faster requirements/dev.txt --pip-args --disable-pip-version-check                                                                                   dev run-test: commands[0] | alembic upgrade head                                               
INFO  [alembic.runtime.migration] Running upgrade aef6a6460d0d -> b97080de93bc, Add …
```
> Migration for LMSCourse.lti_context_memberships

- lms/models/__init__.py
- lms/models/course_roster.py
- lms/models/lti_role.py
- lms/models/lti_user.py
- tests/factories/__init__.py
- tests/factories/course_roster.py
For:
Migration over: https://github.com/hypothesis/lms/pull/6607
See: https://github.com/hypothesis/lms/pull/6609
> Model for CourseRoster

- lms/services/__init__.py
- lms/services/roster.py
- lms/tasks/roster.py
- tests/unit/lms/services/roster_test.py
- tests/unit/lms/tasks/roster_test.py
- tests/unit/services.py
This makes room for follow up commits that will add assignment specific methods.
For sanity checking I've repeated the first steps of the testing over https://github.com/hypothesis/lms/pull/6611
> Rename CourseRosterService to RosterService

- lms/scripts/init_db.py
Delete the DB's "public" schema directly.
We do this instead of using SQLAlchemy's delete_all because we want to delete all tables in the current DB, not only the ones the current code base is aware off.
This is useful while switching between branches that include DB migrations.
---
I'd like to keep this in main for a while to see if we find any issues, if not then backport it to the cookiecutter.
> Better support for running tests in branches with different DB schemas

- lms/migrations/versions/cb5fe6e8dc09_assignment_rosters_table.py
For:
Autogenerated from: https://github.com/hypothesis/lms/pull/6636
More context and testing instructions over: 
- https://github.com/hypothesis/lms/pull/6637
> Migration for AssignmentRoster

- lms/migrations/versions/ff2f8a64f6a9_assignment_lis_outcome_service_url.py
For:
Autogenerated from: https://github.com/hypothesis/lms/pull/6643
- https://github.com/hypothesis/lms/pull/6646
> Migration for assignment.lis_outcome_service_url

- lms/models/assignment.py
For:
Migration over: https://github.com/hypothesis/lms/pull/6642
- https://github.com/hypothesis/lms/pull/6646
> Model changes for assignment.lis_outcome_service_url

- .github/workflows/ci.yml
- .github/workflows/keepalive.yml
Extracted from:
https://github.com/hypothesis/lms/pull/6630
> Apply updates from cookiecutter

- lms/migrations/versions/f521d69a47d2_migration_for_auto_grading_settings.py
For:
Model changes over: https://github.com/hypothesis/lms/pull/6649
Testing instructions over: https://github.com/hypothesis/lms/pull/6656
> Auto grading settings migration

- lms/models/assignment.py
For:
Migration over: https://github.com/hypothesis/lms/pull/6648
Testing instructions over: https://github.com/hypothesis/lms/pull/6656
> Model for auto grading settings

- lms/migrations/versions/adc83819c8d8_migration_for_lmsuser_lti_v13_user_id.py
For:
Autogenerated from: https://github.com/hypothesis/lms/pull/6670
More context and testing instructions in: https://github.com/hypothesis/lms/pull/6671
> Migration for lms_user.lti_v13_user_id

- lms/js_config_types.py
- lms/resources/_js_config/__init__.py
- tests/unit/lms/resources/_js_config/__init___test.py
For:
Expose the new endpoint to the FE config.
> Syn grades dashboard endpoint config

- lms/static/scripts/frontend_apps/utils/api.ts
- lms/static/scripts/frontend_apps/utils/test/api-test.js
This PR adds a new `usePolledAPIFetch` hook which works like `useAPIFetch`, with the difference that we can periodically repeat the request at fixed intervals, until a condition is met.
It has a similar `useAPIFetch` API, with the addition of the callback that receives the last fetch result and returns `true` or `false`, to determine if a re-fetch should be scheduled or not. 
The first use case we have for this hook is LMS auto-grading status checks. Since setting-up the infrastructure to support real-time updates is more complex, for now we will just check the grading sync status when the page loads, and if the status is "in-progress", continue polling until it transitions to "success" or "error".
```tsx
const result = usePolledAPIFetch({
path: …
```
> Add usePolledAPIFetch hook to do API polling

- lms/static/scripts/frontend_apps/utils/api.ts
- lms/static/scripts/frontend_apps/utils/test/api-test.js
While using `usePolledAPIFetch`, I noticed the fetch result will momentarily transition from `isLoading: true` to `isLoading: false` right before checking if the call needs to be refreshed (in fact this is what makes the `shouldRefresh` callback to be called).
This can cause a UI which depends on the result to flicker from a loading state to a non-loading state, and almost immediately go back to loading if `shouldRefresh` returns `true`.
This PR makes `usePolledAPIFetch` expose an independent `isLoading` flag which transitions to false only when both the actual fetch finished and `shouldRefresh` returned false, preventing the flickering.
Internally, it still uses the actual fetch result to determine when to refresh. 
Apply the next diff in order to do a 5-attempt polling to the `/_status` …
> Avoid flickering UIs between refreshes when using usePolledAPIFetch

- lms/models/__init__.py
- lms/models/grading_sync.py
- tests/factories/__init__.py
- tests/factories/grading_sync.py
For:
More context and testing instructions in https://github.com/hypothesis/lms/pull/6690
> Model for GradingSync

- lms/services/auto_grading.py
- lms/services/lti_grading/_v13.py
- lms/tasks/grading.py
- lms/views/dashboard/api/grading.py
- tests/unit/lms/services/auto_grading_test.py
- tests/unit/lms/services/lti_grading/_v13_test.py
- tests/unit/lms/services/roster_test.py
- tests/unit/lms/tasks/grading_test.py
- tests/unit/lms/views/dashboard/api/grading_test.py
- New endpoints
GET /sync
Get the last sync for an assignment.
404 If there's no existing grade sync.
POST /sync
Create a new sync for an assignment.
400 If there's already a sync in progress.
- New tasks
sync_grades
Schedules each individual grade sync for one particular GradeSync
sync_grade
Submits a grade back to the LMS. Up to two retries.
sync_grade_complete
Summarizes the status of a GradingSync
- Open the dashboard as an instructor for: 
https://hypothesis.instructure.com/courses/319/assignments/7296
- Copy the auth token of any of API calls for using it in the next curl commands.
- Create a new sync
curl 'http://localhost:8001/api/dashboard/assignments/82/grading/sync' -X POST \
-H "Content-Type: application/json" \
-H 'Authorization: Bearer TOKEN' \
--data …
> Synchronize grades back to the LMS

- lms/views/dashboard/api/grading.py
See: https://github.com/hypothesis/lms/pull/6699#pullrequestreview-2324511449
> Validate that there's at least one grade while creating new GradeSyncs

- lms/static/scripts/frontend_apps/utils/api.ts
- lms/static/scripts/frontend_apps/utils/test/api-test.js
While working on https://github.com/hypothesis/lms/pull/6680, I noticed the button would transition to "loading" instead of "syncing" when polling new API requests.
This is because internally, `useFetch` resets `data` when transitioning to the loading state. In this case however, we want to retain the previously loaded data when doing refreshes, so that we can tell the difference between the first load, and subsequent refreshes until `shouldRefresh` returns false.
This PR makes sure we track and expose the previous value of `data` while performing a fetch.
Apply this diff:
```diff
diff --git a/lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx b/lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx
index 2d8dfe92c..3818df38d 100644
--- …
```
> Track previous fetch data in usePolledAPIFetch

- lms/static/scripts/frontend_apps/api-types.ts
- lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx
- lms/static/scripts/frontend_apps/components/dashboard/SyncGradesButton.tsx
- lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js
- lms/static/scripts/frontend_apps/components/dashboard/test/SyncGradesButton-test.js
- lms/static/scripts/frontend_apps/config.ts
> Depends on https://github.com/hypothesis/lms/pull/6696
Add button in dashboard to sync grades, for assignments configured with auto-grading, and only if the `auto_grading_sync` feature flag is enabled.
https://github.com/user-attachments/assets/6c195019-b619-40c1-9a64-8e912fbd423b
> [!NOTE]  
> This PR is easier to review [ignoring whitespaces](https://github.com/hypothesis/lms/pull/6700/files?w=1)
There's a few things which will be implemented in a follow-up PR:
* Handle progress/sync status per student, as well as displaying the amount of students that were already synced.
* Filter-out students which grade didn't change. For now the button will always consider all students from the list need to be synced.
* Handle sync errors properly. Right now the button will only transition into a …
> Add button to sync grades in dashboard assignment view

- lms/static/scripts/frontend_apps/api-types.ts
- lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx
- lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js
This PR adjusts the FE to work with changes introduced in https://github.com/hypothesis/lms/pull/6701, but without adding any behavior change.
Once both this and https://github.com/hypothesis/lms/pull/6701 are merged we'll work on handling which users need to be synced and which don't.
> Adapt schema for studnets auto_grading_grade

- lms/static/scripts/frontend_apps/components/dashboard/AssignmentActivity.tsx
- lms/static/scripts/frontend_apps/components/dashboard/GradeIndicator.tsx
- lms/static/scripts/frontend_apps/components/dashboard/SyncGradesButton.tsx
- lms/static/scripts/frontend_apps/components/dashboard/test/AssignmentActivity-test.js
- lms/static/scripts/frontend_apps/components/dashboard/test/GradeIndicator-test.js
- lms/static/scripts/frontend_apps/components/dashboard/test/SyncGradesButton-test.js
> Depends on https://github.com/hypothesis/lms/pull/6710
Indicate which students have a new auto-calculated grade since the last time grades were synced.
Additionally, when syncing grades, exclude those which didn't change since last sync.
1. For now, I decided to remove the "New" label from students once the sync has been scheduled, without waiting for the actual sync to finish.
I did this because it was simpler than waiting for the actual sync to finish, but once we have sync statuses per student, I will refactor the logic to that it is more accurate and is not "broken" if the pages is reloaded or if the sync is already in progress when the page is loaded for the first time.
1. Checkout this branch
2. Delete all synced grades in your local DB: `truncate grading_sync cascade;`
3. Go to …
> Add label to grades which have changed since last sync

- lms/js_config_types.py
- lms/models/_mixins/created_updated.py
- lms/services/h_api.py
- lms/views/dashboard/api/assignment.py
- lms/views/dashboard/api/course.py
- lms/views/dashboard/api/grading.py
- lms/views/dashboard/api/user.py
- tests/unit/lms/views/dashboard/api/assignment_test.py
- tests/unit/lms/views/dashboard/api/course_test.py
- tests/unit/lms/views/dashboard/api/user_test.py
For:
- https://github.com/hypothesis/lms/issues/6748
This will return dates with timezone information
- Sanity all levels of the dashboards navigating around, starting from an auto-gradable assignment.
https://hypothesis.instructure.com/courses/319/assignments/7296
> Use the json_iso_utc serializer in all dashboard endpoints

- lms/migrations/versions/a9e5a33e96b7_backfill_lmsuserassignmentmembership.py
For:
---
Now that the python code creates LMSUserAssignmentMembership rows on each assignment backfill the existing data in one migration.
- [The select side of the migration can be tested on metabase](https://metabase.hypothes.is/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiJTRUxFQ1RcbiAgICBhc3NpZ25tZW50X21lbWJlcnNoaXAuY3JlYXRlZCxcbiAgICBhc3NpZ25tZW50X21lbWJlcnNoaXAudXBkYXRlZCxcbiAgICBhc3NpZ25tZW50X21lbWJlcnNoaXAuYXNzaWdubWVudF9pZCxcbiAgICBsbXNfdXNlci5pZCBhcyBsbXNfdXNlcl9pZCxcbiAgICBsdGlfcm9sZV9pZFxuRlJPTSBhc3NpZ25tZW50X21lbWJlcnNoaXBcbkpPSU4gXCJ1c2VyXCIgb24gYXNzaWdubWVudF9tZW1iZXJzaGlwLnVzZXJfaWQgPSBcInVzZXJcIi5pZFxuSk9JTiBcImxtc191c2VyXCIgb24gXCJ1c2VyXCIuaF91c2VyaWQgPSBcImxtc191c2VyXCIuaF91c2VyaWRcbiIsInRl …
> Backfill LMSUserAssignmentMembership based on AssignmentMembership rows

- bin/run_data_task.py
- pyproject.toml
https://docs.astral.sh/ruff/rules/too-many-nested-blocks/
> Enable ruff's PLR1702 rule

- eslint.config.js
- lms/static/scripts/frontend_apps/test/index-test.js
- package.json
- yarn.lock
Replace some local eslint config with the one introduced in https://github.com/hypothesis/frontend-toolkit/pull/54
> Use TS and JSX shared configs from eslint-config-hypothesis

- lms/db/_locks.py
- lms/models/exceptions.py
- lms/services/application_instance.py
- lms/services/blackboard_api/_schemas.py
- lms/services/exceptions.py
- lms/services/jstor/service.py
- lms/services/organization.py
- lms/services/user.py
- lms/services/vitalsource/_client.py
- lms/services/vitalsource/exceptions.py
- lms/services/youtube.py
- lms/views/api/sync.py
- pyproject.toml
See: https://docs.astral.sh/ruff/rules/#pep8-naming-n
I have not attempt to fix any of these, I have just:
````ruff check --preview -q lms tests bin --add-noqa````
which adds the relevant noqa statements. 
This will make this rule effective for new code.
> Enable ruff's N (pep8 naming) set of rules

- lms/migrations/versions/4b813a44a6c9_create_lmsgroupset_table.py
For: 
- https://github.com/hypothesis/lms/issues/6834
See https://github.com/hypothesis/lms/pull/6837 for testing instructions and more context.
> Migration for the LMSGroupSet table

- lms/models/__init__.py
- lms/models/lms_segment.py
For: 
- https://github.com/hypothesis/lms/issues/6851
For testing instruction and more context see: https://github.com/hypothesis/lms/pull/6848
> New model for LMSSegment

- lms/services/__init__.py
- lms/services/grouping/factory.py
- lms/services/grouping/service.py
- lms/services/segment.py
- tests/factories/__init__.py
- tests/factories/lms_group_set.py
- tests/factories/lms_segment.py
- tests/unit/lms/services/grouping/factory_test.py
- tests/unit/lms/services/grouping/service_test.py
- tests/unit/lms/services/segment_test.py
- tests/unit/services.py
For: 
- https://github.com/hypothesis/lms/issues/6851
- Trigger fetching group sets on this canvas course, for example re-deep-linking an assignment:
https://hypothesis.instructure.com/courses/125/assignments/1833/edit?return_to=https%3A%2F%2Fhypothesis.instructure.com%2Fcourses%2F125%2Fassignments%2F1833
No need to save the edit, just get to list the group sets.
- Launch both a sections and groups assignments:
https://hypothesis.instructure.com/courses/125/assignments/874
- Check the new rows in the DB:
```
select * from lms_segment;
id  |      type      | lms_id |              name               |         h_authority_provided_id          | lms_course_id | lms_group_set_id |          created           |          updated …
```
> Code changes to maintain the lms_segment table up to date

- lms/migrations/versions/a7e9dc7c4c0f_backfill_lms_segment_groups.py
For:
- https://github.com/hypothesis/lms/issues/6851
- Launch a groups assignment: 
- Check the values in LMSSegment:
``` 
select * from lms_segment where type = 'canvas_group';
id  |     type     | lms_id |              name               |         h_authority_provided_id          | lms_course_id | lms_group_set_id |          created           |          updated
-----+--------------+--------+---------------------------------+------------------------------------------+---------------+------------------+----------------------------+---------------------------
173 | canvas_group | 130    | Group with student              | 102a25279bc609179f58cb4bf5c50d7dfc6f0929 |           105 |              123 | 2024-11-12 09:55:04.993776 | …
```
> Backfill LMSSegment (groups)

- lms/models/application_instance.py
- lms/services/dashboard.py
- lms/services/roster.py
- lms/services/user.py
- lms/templates/admin/application_instance/show.html.jinja2
- lms/templates/admin/assignment/show.html.jinja2
- lms/templates/admin/course/show.html.jinja2
- lms/templates/admin/macros.html.jinja2
- lms/views/admin/assignment.py
- lms/views/admin/course.py
- lms/views/dashboard/api/user.py
- tests/unit/lms/services/dashboard_test.py
- tests/unit/lms/services/roster_test.py
- tests/unit/lms/views/admin/assignment_test.py
- tests/unit/lms/views/admin/course_test.py
- tests/unit/lms/views/dashboard/api/user_test.py
https://github.com/hypothesis/lms/pull/6866
> Add new feature flag to control exposing rosters on the dashboards

- lms/migrations/versions/3466cfe2cbca_add_lmsuser_lms_api_user_id.py
For:
More context and testing instructions on 
- https://github.com/hypothesis/lms/pull/6878
> Migration to add LMSUser.lms_api_user_id

- lms/models/lms_user.py
For:
More context and testing instructions on 
- https://github.com/hypothesis/lms/pull/6878
> Model changes to add LMSUser.lms_api_user_id

- lms/events/event.py
- lms/tasks/event.py
- tests/factories/__init__.py
- tests/factories/event.py
- tests/unit/conftest.py
- tests/unit/lms/events/event_test.py
- tests/unit/lms/tasks/event_test.py
Store the full LTI payload for launches to make debugging of school specific issues easier.
As this data can grow indefinitely and it doesn't provide much value after a while for debugging, we'll delete older rows in a periodic task.
- Launch a LTI1.1 assignment
- Launch a LTI1.3 assignment
- Check the data on the DB, on make sql
```
select timestamp, title, event_data.extra from event join event_data on event.id = event_id join assignment on assignment.id = assignment_id;
-[ RECORD 1 ]
timestamp | 2024-12-11 09:21:50.455989
title     | localhost (make devdata) Groups assignment - LTI1.3
extra     | {"lti_params": {"aud": "93820000000000200", "azp": …
```
> Store LTI launch parameters on EventData

- .github/workflows/data_tasks.yml
This now matches the value over the report_refresh task
> Increase data_tasks GHA timeout

- lms/events/event.py
- lms/tasks/event.py
- tests/factories/__init__.py
- tests/factories/event.py
- tests/unit/conftest.py
- tests/unit/lms/events/event_test.py
- tests/unit/lms/tasks/event_test.py
Reverts hypothesis/lms#6914
See: https://github.com/hypothesis/lms/pull/6832
The revert, as it is fails both type checking and functional tests due to:
- https://github.com/hypothesis/lms/pull/6918
- https://github.com/hypothesis/lms/pull/6920
This commits fixes the issue:
- https://github.com/hypothesis/lms/pull/6916/commits/96564d3d91fb19aa8442f8e6f180213ff9b3d1a2
- Same instructions as:
https://github.com/hypothesis/lms/pull/6832
- Also test assignment creation (deep linking) missing on the original PR
https://hypothesis.instructure.com/courses/319/assignments/7518/edit?submission_type%5B%5D=external_tool&name=Marcos%20playground%20assignment&due_at=&points_possible=0&post_to_sis=false
Save any document type and in `make sql` make a deep linking specifc query:
```
select timestamp, …
```
> Revert "Revert "Store LTI launch parameters on EventData""

- lms/migrations/versions/0aa54a98ad39_add_start_and_end_dates_for_courses.py
Auto-generated from:
https://github.com/hypothesis/lms/pull/6940
See more context and testing instructions on:
https://github.com/hypothesis/lms/pull/6941
> Migration to add start/end dates to courses

- lms/models/lms_course.py
Migration over:
https://github.com/hypothesis/lms/pull/6939
See more context and testing instructions on:
https://github.com/hypothesis/lms/pull/6941
> Model changes to add start/end dates to courses

- .cookiecutter/includes/.github/dependabot/npm/tail.yml
Add typescript-eslint to eslint dependabot package (4c6bf40)
> Migrate npm dependabot configuration change to the cookiecutter

- lms/models/__init__.py
- lms/models/lms_course.py
- lms/models/lms_term.py
Migration over: 
https://github.com/hypothesis/lms/pull/6971
https://github.com/hypothesis/lms/pull/6969
> Model for LMSTerm

- lms/tasks/roster.py
> Change how old a roster can be before it is considered stale

- lms/tasks/roster.py
Consider them stale after 3 days instead of 5.
> Refresh rosters more frequently

- package.json
- yarn.lock
No extra adjustments were needed
> Update to frontend-shared 9.0.0

- lms/services/vitalsource/service.py
- tests/unit/lms/services/vitalsource/service_test.py
Similar to: https://github.com/hypothesis/lms/pull/6954
Here we add a third SKU and document a bit the use case of each of them
> Add a new VBID to student pay license check

- lms/models/application_instance.py
- lms/resources/_js_config/file_picker_config.py
- lms/templates/admin/application_instance/show.html.jinja2
- tests/functional/views/lti/deep_linking_test.py
- tests/unit/lms/models/application_instance_test.py
Adapt moodle settings to the new style introduced in https://github.com/hypothesis/lms/pull/7046
> Adapt moodle settings to the new tri-state setting

- lms/services/annotation_activity_email.py
- lms/tasks/annotations.py
- tests/unit/lms/services/annotation_activity_email_test.py
- tests/unit/lms/tasks/annotations_test.py
Model and migration on: https://github.com/hypothesis/lms/pull/7059
```PYTHONPATH=. tox -e dev --run-command 'alembic upgrade head'```
```
dev run-test-pre: PYTHONHASHSEED='2417888063'
INFO  [alembic.runtime.migration] Running upgrade a8fd48c30957 -> 0d265909ff85, Create the notification table.
```
- Make an annotation with a mention on an assignment:  https://hypothesis.instructure.com/courses/125/assignments/873
- Check the data in the DB, in `make shell`
```
select …
```
> Create a record in the notification table when an mention emails is sent

- lms/services/annotation_activity_email.py
- tests/unit/lms/services/annotation_activity_email_test.py
These now link to the generic (digest) preferences page but it will simplify testing going forward.
- Generate an email creating an annotation with a mention on 
- On LMS' console you can see for example that we include the `List-Unsubscribe` header.
> Include preferences links in mention email template

- lms/templates/email/mention/body.html.jinja2
Based on the suggestions over: https://hypothes-is.slack.com/archives/C2C2U40LW/p1743171309690619
> Small tweaks to the mentions email template

- lms/js_config_types.py
- lms/models/lms_user.py
- lms/services/annotation_activity_email.py
- lms/services/digest.py
- lms/services/email_preferences.py
- lms/static/scripts/frontend_apps/config.ts
- lms/views/email.py
- tests/factories/__init__.py
- tests/factories/lms_user.py
- tests/unit/lms/models/lms_user_test.py
- tests/unit/lms/services/annotation_activity_email_test.py
- tests/unit/lms/services/email_preferences_test.py
- tests/unit/lms/views/email_test.py
See: #7065 and also #7072 for the front end work
- Apply a diff like this to quickly generate signed URLs:
```diff
diff --git a/lms/views/lti/basic_launch.py b/lms/views/lti/basic_launch.py
index 2fc179d8c..757641805 100644
--- a/lms/views/lti/basic_launch.py
+++ b/lms/views/lti/basic_launch.py
@@ -58,6 +58,34 @@ class BasicLaunchViews:
)
self.course = self._record_course()
+        from lms.services.email_preferences import EmailPreferencesService
+
+        self.email_preferences_service = request.find_service(EmailPreferencesService)
+        print(
+            "PREFRENCES DIGEST",
+            self.email_preferences_service.preferences_url(
+                self.request.user.h_userid, "instructor_digest"
+            ),
+        )
+        print(
+            "UNSUBSCRIBE DIGEST",
+ …
```
> Email preferences support for mentions

- lms/models/notification.py
- lms/services/annotation_activity_email.py
- tests/unit/lms/services/annotation_activity_email_test.py
- Align the value of type of Notification.type with H, mention vs MENTION.
- Check user unsubscribed and feature disabled separately.
> Small tweaks for mentions

- lms/models/application_instance.py
To be merged on Wed 9th: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1743610316065029
> Enable the mentions feature by default

- lms/_version.py
- lms/sentry.py
See: https://github.com/hypothesis/cookiecutters/pull/219
> Expose latest git commit as sentry release

- lms/migrations/versions/833f6b0237d8_new_lmsuser_name_columns.py
- lms/models/lms_user.py
Migration over: https://github.com/hypothesis/lms/pull/7101
For https://github.com/hypothesis/product-backlog/issues/1655
More context and testing instructions over: https://github.com/hypothesis/lms/pull/7103
> Model changes for new name column in LMSUser

- lms/migrations/versions/b91594c0e379_new_lmsuser_middle_name_column.py
For: 
- https://github.com/hypothesis/product-backlog/issues/1655
> Migration to add middle_name to LMSUser

- lms/services/vitalsource/service.py
- tests/unit/lms/services/vitalsource/service_test.py
Slack thread: https://hypothes-is.slack.com/archives/C2BLQDKHA/p1747661674651719
> Include new VS SKU to check for in license checks

- package.json
- yarn.lock
See https://github.com/hypothesis/client/pull/7098.
> Remove unused diff dependency

- lms/services/roster.py
- tests/unit/lms/services/roster_test.py
For:
- https://github.com/hypothesis/lms/issues/7002
These are very common errors as an assignment might be created for them but eventually removed.
We currently try to fetch this over and over as the requests fail.
This commit uses the same approach we use for ignoring errors while fetching assignments rosters.
> Ignore not found canvas group roster errors

- .github/workflows/report_refresh.yml
- Changed from 90 to 120 minutes
See Slack for more information: https://hypothes-is.slack.com/archives/CR3E3S7K8/p1752221383069199
> Increased report refresh timeout
